### ISSUE TITLE
The subviews frame of cell is different between messagesCollectionViewCellDidTapCell and cellForItemAtIndexPath

### ISSUE THREAD

**Issue by fibers** [jessesquires/JSQMessagesViewController#1004]
When the user taps the cell, the following method runs

```
- (void)messagesCollectionViewCellDidTapCell:(JSQMessagesCollectionViewCell *)cell atPosition:(CGPoint)position
{
    NSIndexPath *indexPath = [self indexPathForCell:cell];
    if (indexPath == nil) {
        return;
    }

    [self.delegate collectionView:self
            didTapCellAtIndexPath:indexPath
                    touchLocation:position];
}
```

After I inspect the subviews in cell, the frames are OK ( what means is that all the frames have been modified by Autolayout ).  
The code passed the NSIndexPath object to "didTapCellAtIndexPath" but not the cell itself.

In my own implement of "didTapCellAtIndexPath", I need decide which subviews in cell is tapped, so my code is a bit like following:

```
- (void)collectionView:(JSQMessagesCollectionView *)collectionView didTapCellAtIndexPath:(NSIndexPath *)indexPath touchLocation:(CGPoint)touchLocation{

    JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[self collectionView:collectionView cellForItemAtIndexPath:indexPath];
    UIView *view = cell.messageBubbleContainerView;

   if(CGRectContainsPoint(view.frame, touchLocation)){
         ...............
    }
}
```

But I find that the frame of "messageBubbleContrainerView" is incorrect. 
Certainly, I know there is another delegate method called "didTapMessageBubbleAtIndexPath" to handle the tapped event on "messageBubbleContrainerView".  The example code is just for elaboration.

So my question are:
1.  What's  the consideration for passing a NSIndexPath object instead of a Cell to "didTapCellAtIndexPath". I consider that most of the use cases should convert the NSIndexPath object to Cell back again in "didTapCellAtIndexPath".
2.  If there is any change to get the right frame of subviews in my own implement of "didTapCellAtIndexPath".  I don't want to change the source code.

Any help will be appreciated. Thanks

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
