### ISSUE TITLE
is it possible to customize JSQMessagesCollectionViewCell?

### ISSUE THREAD

**Issue by hellogo** [jessesquires/JSQMessagesViewController#1006]
Hi:
i want to add two buttons below the JSQMessagesCollectionViewCell,for some special text messages，not for image cell or location cell.what should i do？please show me just detail code，i already  searched issues for long time，maybe my english is not good，sometime i do not know their purpose.thank u a lot!!!

**Comment by jessesquires** [comment]
hey @hellogo - there have been many answers to this already. please search previous issues.

https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+customize+cell+is%3Aclosed
