### ISSUE TITLE
UIMenu​Controller causes text in bubbles to flicker rapidly

### ISSUE THREAD

**Issue by NitWitStudios** [jessesquires/JSQMessagesViewController#1008]
Attempting to paste text by holding down in the text field and bringing up the UIMenu​Controller causes some of the text (but not all) in existing message bubbles to start flickering rapidly and randomly. It doesn't happen 100% of the time, but happens quite frequently. 
See attached GIF for video:

![jsqmessagesviewcontroller flicker](https://cloud.githubusercontent.com/assets/1779541/7925344/5bb31222-0878-11e5-8078-2b75f38a4c1c.gif)

**Comment by sublimepremise** [comment]
I am experiencing the same issue. After testing, it looks to me like this is an iOS 8 specific issue. Can anyone else confirm?

**Comment by Kayoto1** [comment]
Same happen to me

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
