### ISSUE TITLE
Dose my own message model have to conform to JSQMessageData?

### ISSUE THREAD

**Issue by jerrypainter** [jessesquires/JSQMessagesViewController#1011]
Hey there,

I want to create my own message model, dose it have to conform to JSQMessageData if I include all necessary properties in my own message model?

Thanks for sharing and maintaining this wonderful repo!

Best,
Zixiao

**Comment by jessesquires** [comment]
thanks @jerrypainter !

Yes, you can create your own models however you like, then you must implement `JSQMessageData`.
