### ISSUE TITLE
JSQSystemSoundPlayer+JSQMessages.m changes

### ISSUE THREAD

**Issue by relatedcode** [jessesquires/JSQMessagesViewController#1012]

**Comment by relatedcode** [comment]
@jessesquires Did I miss something here?

![changes](https://cloud.githubusercontent.com/assets/5425762/7967248/2151d5de-0a29-11e5-8f37-de8744fd9767.png)

**Comment by relatedcode** [comment]
@jessesquires I have just updated to the latest version both JSQMessagesViewController and JSQSystemSoundPlayer. Thanks!

**Comment by jessesquires** [comment]
JSQMessages currently uses JSQSystemSoundPlayer 2.0.1

https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController.podspec#L25

**Comment by relatedcode** [comment]
@jessesquires Ok. Thanks!
