### ISSUE TITLE
Bubblesize of photomessages incorrect

### ISSUE THREAD

**Issue by niklas22** [jessesquires/JSQMessagesViewController#1013]
Hi!

I'd like to know how to change the size of the bubbles. 
In my case the pictures are cropped.

![bildschirmfoto 2015-06-04 um 17 54 11](https://cloud.githubusercontent.com/assets/12526311/7988271/c99354de-0ae2-11e5-97da-55d91ab40216.png)

**Comment by jessesquires** [comment]
please check the docs. you can provide a `mediaDisplaySize`

**Comment by niklas22** [comment]
the mediaView and mediaViewDisplaySize are readOnly methods. so where could i access them?
