### ISSUE TITLE
how can I insert ads(admob) like this picture?

### ISSUE THREAD

**Issue by jcsla** [jessesquires/JSQMessagesViewController#1014]
![2015-06-06 2 52 46](https://cloud.githubusercontent.com/assets/5294906/8011820/2fea32a6-0bf7-11e5-9091-28a549b9231d.png)

hello.

how can I insert ads(admob...) like this picture?

Thanks.

**Comment by jessesquires** [comment]
hey @jcsla - this isn't really specific to JSQMesssages. i would suggest asking on StackOverflow instead

**Comment by jcsla** [comment]
![kakaotalk_photo_2015-06-07-03-27-42](https://cloud.githubusercontent.com/assets/5294906/8020896/2f9a27ba-0cc5-11e5-9d63-20e9e5639761.jpeg)

I am used jsqmessage like in this application.

I want to insert admob above(android) picture.

how can I insert there?
