### ISSUE TITLE
[JSQMediaItem hash]?

### ISSUE THREAD

**Issue by FredericJacobs** [jessesquires/JSQMessagesViewController#1017]
I'm not sure I understand why this hash is binary. I can easily imaging collisions? Or am I missing something?
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Model/JSQMediaItem.m#L133

**Comment by jessesquires** [comment]
`JSQMediaItem` is an abstract base class. the concrete subclasses override this

**Comment by FredericJacobs** [comment]
Thanks!
