### ISSUE TITLE
Custom menu action strange behaviour related to input toolbar

### ISSUE THREAD

**Issue by relatedcode** [jessesquires/JSQMessagesViewController#1018]

**Comment by relatedcode** [comment]
@jessesquires I am not sure if it's a bug or a feature. If it's a feature, then it would be nice to know how to disable it. Thanks!

![ios simulator screen shot 2015 06 07 16 39 14](https://cloud.githubusercontent.com/assets/5425762/8024436/f9b01938-0d33-11e5-80c9-057df36caeb9.png)

**Comment by jessesquires** [comment]
see #1010
