### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by nachkar** [jessesquires/JSQMessagesViewController#1019]
First of all great work. Second ,I have some pointers to enhance this control : 
-You should add the timestamp label inside the bubble and add the read ,delivered and sent ticks.
-The media placeholder needs to be more flexible to change , Im having trouble setting it behind the activity indicator than changing it when image finish downloading.
-I caught a bug ,the data for item function is used too many times to create the same object which leads to a memory loss.
-If possible to add an audio bubble where this media could be played and stopped (As whatsapp)

**Comment by jessesquires** [comment]
thanks @nachkar !

please open a separate issue for each of these so we can track and discuss them individually. :smile:
