### ISSUE TITLE
Keyboard covers up messages

### ISSUE THREAD

**Issue by yisheng** [jessesquires/JSQMessagesViewController#1021]
The *first time* you focus on `textView`, messages don't auto scroll to the right place (keyboard/toolbar covers up collectionView) when the default input is Chinese.

![ios simulator screen shot 2015 6 9 11 42 04](https://cloud.githubusercontent.com/assets/352986/8050374/a5f2978c-0e9e-11e5-9233-a8280fde7c91.png)

**Comment by yxztj** [comment]
just saw the same issue here. The issue goes away after first appearance

**Comment by jessesquires** [comment]
Thanks @yisheng / @yxztj !

This looks the same as #450, so I'm going to close this as a duplicate.

Next time, please read the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) before opening an issue! :smile:

**Comment by yisheng** [comment]
Thanks for that! @jessesquires
