### ISSUE TITLE
JSQMessagesViewController  & UIAppearance

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#1024]
Quick question: dropping UIAppearance into my app, setting nabber background color. Works well except for the only view descended from JSQMessagesViewController. This is un-appearance'd ;) ..

I wonder if anyone understands why? thx, drew..

**Comment by jessesquires** [comment]
hey @wdcurry - what exactly do you mean?

> Works well except for the only view descended from JSQMessagesViewController.

**Comment by wdcurry** [comment]
i dropped a
    [[UINavigationBar appearance] setBackgroundColor:[UIColor myColor]];

into my appDelegate, and it impacts all pushed views *except* the chat view. I see no reason as of yet as to why this is.

**Comment by jessesquires** [comment]
Hm... that should not be the case. What happens if you set this directly on JSQMVC?

**Comment by wdcurry** [comment]
tis odd, this exact line in the parent of my chats tableView works properly in viewDidLoad, but does nothing in the JSQ-based chat view. I have a custom view for the title, but disabled that to test, and there is NO change to the nabber color.  Currently i am stumped for an idea.

    //Test for Jesse re color set of navbar {in viewDidLoad}
    //This exact line works in the parent viewController
    self.navigationController.view.backgroundColor = [UIColor blueColor];

**Comment by wdcurry** [comment]
hey Jesse, i found one other view that also does not have color assigned, so it might not be library (which would make sense). I will try to track this down if time permits, else i will just dump the colouring of the navbar as it isn't critical.  I simply hoping somebody here might have a clue to help ;)

**Comment by jessesquires** [comment]
@wdcurry - Does this repro in the demo project?

**Comment by wdcurry** [comment]
hey Jesse, we should close this as i had to move on and skip this issue entirely for now. But thank you!

**Comment by jessesquires** [comment]
:+1:
