### ISSUE TITLE
Crash when using custom action

### ISSUE THREAD

**Issue by sebastianludwig** [jessesquires/JSQMessagesViewController#1026]
Found by @relatedcode in #811 - good catch! It didn't happen to me on every occasion end less frequently in the iPhone 6 simulator. I must have been extremely lucky to have not hit it till now :-)

The demo app crashes when returning back to the initial table view after tapping the custom action in the context menu of a cell in the MVC.

**Comment by sebastianludwig** [comment]
Now that was a good one :-)

I just opened #1027 to fix it. The explanation what happens can be found here: http://stackoverflow.com/questions/13268502/exc-bad-access-when-accessing-parameters-in-anddo-of-ocmock

> Without the __unsafe_unretained, an object gets assigned to that address by the getArgument: method, but ARC has no clue since that takes a "void *" argument (not "id *"). Therefore, ARC does not know to add a -retain when that happens. However, as a strongly-typed local variable, it does add a release when it goes out of scope. Thus, the object will get over-released. The easiest way is to just have the local variable be __unsafe_unretained so ARC leaves it alone. –  Carl Lindberg Mar 17 '14 at 21:42

**Comment by danielpetroianu** [comment]
Hi @jessesquires, could this issue be added to 7.1.1 and released sooner, maybe next week ?
