### ISSUE TITLE
How to customize cells so that they have a coloured border like in preview images?

### ISSUE THREAD

**Issue by ryderjack** [jessesquires/JSQMessagesViewController#1028]
I know the cells are fully custoizable but was wondering if you could help point me in the direction of how to customize the borders of the cells so that the cells are white with coloured borders like in the preview images on the github page.

Cheers

**Comment by jessesquires** [comment]
Hey @ryderjack - Look at the `UIImage` category. You can pass any of these images to the MessageBubbleFactory.

**Comment by ryderjack** [comment]
Thanks for getting back to me, so do i have to pass a different image to change the colour/border - there's no properties of the bubbleImage?

Thanks

**Comment by bizibizi** [comment]
Do not use bubbles for it, return nil in bubble method.

Then add code in cellForItemAtIndexPath

cell.backgroundColor = [UIColor clearColor];
    cell.layer.rasterizationScale = [UIScreen mainScreen].scale;
    cell.layer.shouldRasterize = YES;
    
    // * Customization
    if (!isMediaMessage)
    {
        // * Text color, bubble backgroundColor color
        if (isOutgoingMessage)
        {
            cell.textView.textColor = [UIColor k_mainWhite];
            cell.textView.backgroundColor = [UIColor k_mainBlue];
        } else {
            cell.textView.textColor = [UIColor k_mainBlack];
            cell.textView.backgroundColor = [UIColor k_mainWhite];
        }
        // * Bubble backgroundColor stroke
        cell.textView.layer.borderColor = [UIColor k_blackShadow2].CGColor;
        cell.textView.layer.borderWidth = 0.6;
        cell.textView.layer.cornerRadius = 10;
        cell.textView.layer.masksToBounds = YES;
        
        // Underline TextAttributes
        cell.textView.linkTextAttributes = @{ NSForegroundColorAttributeName : cell.textView.textColor, NSUnderlineStyleAttributeName : @(NSUnderlineStyleSingle | NSUnderlinePatternSolid) };
    }

**Comment by ryderjack** [comment]
Thanks @bizibizi that code looks useful! However, since you say not to use the bubble image then there's no speech bubble part in the bottom left hand corner (as I'm looking to use this style of cell for incoming messages). Is there a way of getting the cell to look the same as bubble image but just have the borders? thanks!

**Comment by bizibizi** [comment]
@ryderjack, I do not know, I looking for it but can not achieve with default methods, so I use the code above

**Comment by ryderjack** [comment]
@bizibizi I've found a solution just using the category Jesse has provided:

make sure to add

```
#import "UIImage+JSQMessages.h"
```

and then when you initialise your image factory:
```objective-c
JSQMessagesBubbleImageFactory *bubbleFactoryOutline = [[JSQMessagesBubbleImageFactory alloc] initWithBubbleImage:[UIImage jsq_bubbleRegularStrokedImage] capInsets:UIEdgeInsetsZero];
```

The image category has a number of variations - there's more info there

**Comment by bizibizi** [comment]
do you get with it custom color of bubble and custom stroke color? (for incoming and out coming )

**Comment by Aaaaaaaron** [comment]
i think the easiest way is:
1. create your own bubble image file with customized border color and filled color based on bubble_stroked.png, which you can find it in the bundle. 
2. use @ryderjack 's method to initial the JSQMessagesBubbleImageFactory,
3. remove the color masking operation in jsq_messagesBubbleImageWithColor.

**Comment by glennposadas** [comment]
I hope this won't be a annoying for all the participants in this thread. I just figured out how to use the tailless bubble image of the library properly after reading jess' comment and might help some people in the future. Sample:

`
let incomingBubble = JSQMessagesBubbleImageFactory(bubble: UIImage.jsq_bubbleCompactTailless(), capInsets: .zero).incomingMessagesBubbleImage(with: UIColor.jsq_messageBubbleBlue())`

and use that inside your `messageBubbleImageDataForItemAt`

EZ. Thanks.
