### ISSUE TITLE
Custom Menu Action on Input Toolbar

### ISSUE THREAD

**Issue by azrahim4u** [jessesquires/JSQMessagesViewController#1029]
Hello,

I'm trying to figure out how to disable custom action menu on the input toolbar ( where you type message ) but keep the copy action. My custom action "delete" uses index path to remove a message, however when the custom action is selected from the input toolbar,  the app crashes..

![screen shot 2015-06-10 at 1 42 46 pm](https://cloud.githubusercontent.com/assets/425565/8093549/9f5f6ffc-0f76-11e5-9b7d-98600e5f6560.png)

![screen shot 2015-06-10 at 1 42 34 pm](https://cloud.githubusercontent.com/assets/425565/8093559/ac6e0e60-0f76-11e5-96c6-85ce129c3f11.png)

Thanks

**Comment by jessesquires** [comment]
See #1010

**Comment by wdcurry** [comment]
Any advice those of us who are not helping code this particular area in removing the unwanted custom menu options. I views the linked 1010, but it is not helpful (at least at my level ;) ) .. from my level of geek, it doesn't seem logical that they two menus are the same.

**Comment by jessesquires** [comment]
Hey @wdcurry / @azrahim4u - sorry about that.

The issue deals with how menu items are added via selectors, and how the `UIMenuController` searches for objects that implement the method. [Example in the demo app](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesDemo/DemoMessagesViewController.m#L72-L77)

The solution in #1010 works around this by renaming the method on the controller — though this will produce a "selector not implemented" warning.

A better solution would require some refactoring.

To avoid seeing your custom actions on the `inputTextView`, you could also remove actions from `UIMenuController` while typing — but this also gets tricky trying to add them back.

Summary: the `UIMenuController` API is awful. #singletonsAreTerrible

**Comment by wdcurry** [comment]
I thought i could get around this by adding a UILongPressGestureRecognizer recognizer into JSQMessagesInputToolbar but something is eating the longpress within the textbox, and i am so pressed on time i decided to live with it for now by simply ignoring the actions if selected within the toolbar itself. Ugly but functional for now.
