### ISSUE TITLE
Demo colors are inversed if compared to Messages

### ISSUE THREAD

**Issue by fantattitude** [jessesquires/JSQMessagesViewController#1030]
In Messages.app the colored bubbles are the one you send (so you know if it's iMessage or SMS) and grey the one you receive so it would make sense to reverse the default colors used in the demo (and maybe the component didn't look into it…)

**Comment by jessesquires** [comment]
thanks @fantattitude - this is intentional. the demo is showing how to customize.

**Comment by fantattitude** [comment]
Yeah that's what I thought but wasn't sure, maybe it would be interesting to use a different color to be clear about this intent don't you think ?
