### ISSUE TITLE
How to display a custom text when no message is displayed?

### ISSUE THREAD

**Issue by estemendoza** [jessesquires/JSQMessagesViewController#1031]
Hi!
When I load the messages view, a lot of times there are no messages, so I wanted to show a "There are no messages yet" message like in the middle or in the top of the view.

How can I do this?

Thanks

**Comment by wdcurry** [comment]
If i may speak for Jesse.. this is more a SO-type question as the messages display in a UICollectionView.  There is likely much coverage there.. ;)

**Comment by jessesquires** [comment]
thanks guys! SO would be much better for this :smile:

**Comment by estemendoza** [comment]
Created http://stackoverflow.com/questions/30853010/how-to-display-a-custom-text-when-no-message-is-displayed-in-jsqmessagesviewcont

Next time, it would be better if besides telling me that I should put this in StackOverflow (which by the way I didn't know what SO was, I am not that cool yet, thanks Jesse for the clarification) at least you could have told me if this is possible or not. If it's not possible, this ticket could be easily change to a feature request.

Thanks Jesse again for the library, is amazing.

**Comment by jessesquires** [comment]
thanks @estemendoza ! sorry for the confusion. my intention is to keep questions here that are specific to the library, that's all.
