### ISSUE TITLE
constraints issues.

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#1033]
Hopefully not sounding like a broken record here ;)  ..but:

Where is this at, referring to constraints issues? Numerous threads, closed, but the issues still exist. 

I have done nothing but set text within cells, with no moving around of anything, and see numerous constraint issues. I understand Apple does not reject on warnings, but i would prefer a clean slate if possible. Thanks.

**Comment by jessesquires** [comment]
hey @wdcurry - still a work-in-progress. the "official" discussion is at #817

**Comment by jessesquires** [comment]
PRs welcome :)
