### ISSUE TITLE
Bubbles not dynamically resizing for each JSQMessageData object

### ISSUE THREAD

**Issue by AneeshSachdeva** [jessesquires/JSQMessagesViewController#1034]
Hey everyone,

First off major props to the developer(s), this controller has cut down development costs and time and has helped my team out a ton. I'm using Swift 1.2 to develop a chat-esque app using Parse, and everything with the JSQMessagesViewController works except for one "small" thing: message bubbles do not resize dynamically for each message. All bubbles have the same size, and the size they pick is all dependent on the size created for the first bubble. So the first bubble will always be correctly sized, but then every bubble after that will only use that size. Has anyone else had this issue / know what's causing it?

My messages follow JSQMessageData, and I load the data in viewWillAppear() in my JSQMessagesViewController class. 

Thanks a lot for any help or input, and I'd be happy to share code upon request.

Thanks,
Aneesh

**Comment by jessesquires** [comment]
the value returned from `messageHash` must be unique.

see #980, #923
