### ISSUE TITLE
Resize textview programatically

### ISSUE THREAD

**Issue by Zilounay** [jessesquires/JSQMessagesViewController#1036]
Hi,

First, thank you for your library, it's really wonderful and I like it a lot :)

I'm using an attributed string in the textview, which is used to send messages and media messages.

This is probably not a bug but, for the life of me, I can't figure out how to manually resize the textview (like it does when I start typing multiline texts) when I load the image inside the textview.

I have the image nice and resized in there, i can send it, but I just have to hit "Return" once and then erase it for the textview to resize, which is obviously not an acceptable behaviour.

Can anyone pinpoint what I should do ? I'm obviously missing a method.

I've tried sizeThatFits or setting frames manually, for the content view, the textview or the input toolbar, and none of it really made me move forward.

**Comment by jessesquires** [comment]
Hey @Zilounay :smile: 

Try looking at the methods under `#pragma mark - Input toolbar utilities`

**Comment by jessesquires** [comment]
The discussion in #1070 might also be relevant
