### ISSUE TITLE
Message bubble sizing is incorrect on iPad.

### ISSUE THREAD

**Issue by bmctigue** [jessesquires/JSQMessagesViewController#1037]
Hi,
Thanks also for the great library. I believe I've found an issue with message bubble sizing on the iPad. I'm not using any image, just using the bubbleFactory. This is version 6.0.0. The issue is in JSQMessagesCollectionViewFlowLayout.m.

On line 90 of the config, we are setting self.messageBubbleLeftRightMargin:
if ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad) {
        _messageBubbleLeftRightMargin = 240.0f;
    }
    else {
        _messageBubbleLeftRightMargin = 50.0f;
    }
On line 451 we are setting the maximumTextWidth:
CGFloat maximumTextWidth = self.itemWidth - avatarSize.width - self.messageBubbleLeftRightMargin - horizontalInsetsTotal

The problem is on the iPhone6 and iPad2 the self.itemWidth is coming back as the same width, 312. The result is on the iPad the message bubbles are very narrow and tall because the margin is 240 rather than 50. I'm not sure where this hard coded value comes from, so I'm not sure how to fix it, although I would be happy to fork and fix if I can.

See attached screenshot for example:
![screenshot_6_18_15__11_31_am](https://cloud.githubusercontent.com/assets/10784/8237585/9ee4a0be-15ad-11e5-823f-ae7d618323a7.png)

Thanks,
Bruce

**Comment by jessesquires** [comment]
hey @bmctigue - this is fixed in the latest release. 

see also #947

**Comment by bmctigue** [comment]
hi jesse. I just installed 7.1.0 and I have the exact same problem. Code looks unchanged. Screenshot:
![ios_simulator_-_ipad_2_-_ipad_2___ios_8_3__12f69_](https://cloud.githubusercontent.com/assets/10784/8247172/f88562e2-1608-11e5-90a1-aefd335a0e19.png)

**Comment by mmesutt** [comment]
The same issue happend in my iPad Air (iOS 9).
