### ISSUE TITLE
Keyboard doesn't move when scrolling the input view down

### ISSUE THREAD

**Issue by bryan1anderson** [jessesquires/JSQMessagesViewController#1038]
I've been looking into this, but being that i'm mostly just familiar with swift.. i'm having a hard time figuring out how to get  the messages controller to behave like Messages app on the iPhone. The specific functionallity im referring to is when you scroll down to hide the keyboard. On the native messages app, the keyboard sticks to the inputview and moves with your finger. 

Right now the input view slides behind the keyboard, only after it's at the bottom does the keyboard dismiss and slide off view.

I want them to slide together. Any idea on how I might accomplish this?

**Comment by jessesquires** [comment]
it should do this by default. you are probably missing a call to `super` on view{Will/Did}Appear

**Comment by bryan1anderson** [comment]
it actually does this on the actual app you provide on github.

**Comment by bryan1anderson** [comment]
I can confirm this is a bug on iOS 9 as it works on my iPad running iOS 8

**Comment by jessesquires** [comment]
please always specify iOS and library versions in bug reports.

**Comment by LeoNatan** [comment]
@jessesquires Why is this issue closed? The bug here is the keyboard controller not working properly because it relies on private view hierarchy which has changed. This should be fixed to use the standard scrollview keyboard dismiss mode, which works as expected.

**Comment by jessesquires** [comment]
@LeoNatan - sorry about that :smile: - I missed the comments made after it was closed. 

FYI: I have a tendency to immediately close poorly written bug reports. Everyone's time is too valuable to be wasted.

**Comment by LeoNatan** [comment]
Haha I agree with you on that, but I've learned some leeway goes a long way on the internets. 😜

Thanks

**Comment by jessesquires** [comment]
Closing as dupe in favor of #1063

**Comment by ivan-liljeqvist** [comment]
I searched more and after an hour or so I found a solution that is simpler compared to what I've seen here. 

In KeyboardController add this function:

    -(UIView*)getKeyboardInputView {
        if([[UIDevice currentDevice].systemVersion floatValue] >= 9.0) {
            for(UIWindow* window in [[UIApplication sharedApplication] windows])
                if([window isKindOfClass:NSClassFromString(@"UIRemoteKeyboardWindow")])
                    for(UIView* subView in window.subviews)
                        if([subView isKindOfClass:NSClassFromString(@"UIInputSetHostView")])
                            for(UIView* subsubView in subView.subviews)
                                if([subsubView isKindOfClass:NSClassFromString(@"UIInputSetHostView")])
                                    return subsubView;
        } else {
            return self.textView.superview;
        }
        return nil;
    }

Change jsq_didReceiveKeyboardDidShowNotification to this:

    - (void)jsq_didReceiveKeyboardDidShowNotification:(NSNotification *)notification
    {
        self.keyboardView = [self getKeyboardInputView];
        [self jsq_setKeyboardViewHidden:NO];

        [self jsq_handleKeyboardNotification:notification completion:^(BOOL finished) {
            [self.panGestureRecognizer addTarget:self action:@selector(jsq_handlePanGestureRecognizer:)];
        }];
    }

I got the solution from here: http://stackoverflow.com/questions/32632207/cant-move-keyboard-view-ios9-swift
