### ISSUE TITLE
Receive message only appears after scroll start or keyboard appears

### ISSUE THREAD

**Issue by margono13901** [jessesquires/JSQMessagesViewController#1040]
Hi,

I noticed that the receiver's message bubble only appears after the user starts scrolling or while the keyboard has been selected. What is the probable cause of this?

**Comment by jstart** [comment]
@margono13901 it sounds like you may be fetching data in the background and not updating the UI on the main thread.  For example, if you tell the collectionView to reloadData in a completion block to a network request, it won't update until the user scrolls or some other user interaction.  Can you send a code sample of your problem?

**Comment by lenkaiser** [comment]
Are you calling this method after updating your model?
```
//Finish animation
[self finishReceivingMessage];
```

This makes sure that the collectionView scrolls to the bottom and updates the view by calling all the necessary methods.
