### ISSUE TITLE
Need advice for the customisation in JSQ as per my application

### ISSUE THREAD

**Issue by vickydhas** [jessesquires/JSQMessagesViewController#1041]
Hello Jesse,

I have researched over your library and found that its really amazing to use this for my application, below are my issues that I need an advice from you to move ahead.

I need to achieved UI of chat similar to whats app and few of its operation like mentioned below. 

1) PhotoMediaItem currently have feature to show default loading and gray image background.  I need to show a blur image as the initial chat received from XMPP is having a dirty image base64 received in stanza.
2) On received i add the photo message object with this. So i want to override the loader with Blur image and download Button on top. On press i have to start showing a custom loader like M13ProgressRingView over this photo item. 
3) On load download over from storage location I refresh the image back to original image from local path.

Same thing for video to show the behaviours like whatsapp IOS App.

Also there are certain parameters required for this settings that i need to pass in the datasource of JSQ array but my data is coming from core data that also needs to updated when relevant server information is received like message seen, sent, delivered, photo idNot downloaded, yet to start, pending, download active,upload active...and so on. 

My question is I have to manage the JSQMessage object with this additional info that is updated in my DB object but to update the JSQMessage data object i need to reload the entire UI. Is this right approach or you can advice some optimised way so I update both database and JSQ message object.

Also Can i subclass PhotoMediaItem, VideoMediaIem and LocationMedia Item as mentioned in your doc to handle this extra parameter conditions stated above to store in the UI objects.

Also is it advisable to update / Subclass the JSQMessage Object. I tried manipulating some of the classes as per my requirement but this approach totally messes the UI and data loading as it becomes lagging and inconsistent way. 

Below are the issue that have aroused due to modifying the existing classes. Summarising the requirement.

1) Autolayout messed , no compile errors but the Bubbles keeps shifting and spreading automatically.
2) Wanted to add more items and modify chat bubble as per my design of app but this needs additional parameters that I need your expertise to guide me where should i add and what is not to be touched.
3) Photo Video and Location are very generic how to customise then to add UI effects as per the requirement.
4) How to add additional Media item like Location With landmark, Audio bubble, Customised bubble extending the JSQMediaItem.

Sorry for the long email, but I felt this is more convenient library that can be customised and used by your guidance.

your response is eagerly awaited.

Regards.
Vicky

**Comment by TheEngineerz** [comment]
Very good question actually I want to ask the same thing and especially the customisation of media items like whatsapp loaders etc

**Comment by nachkar** [comment]
Same here , Im experiencing the same troubles and cant figure out how to customize the bubbles ,specially the loading indicator part before and while downloading a media.

**Comment by jessesquires** [comment]
Thanks @vickydhas ! :smile: 

I'm sorry, but I don't have time to answer. I suggest posting on StackOverflow, or something similar!
