### ISSUE TITLE
'Invalid parameter not satisfying: self.senderId != nil'

### ISSUE THREAD

**Issue by cnowak7** [jessesquires/JSQMessagesViewController#1043]
I'm doing an application right now that implements snapchat style scrolling where you swipe left on a cell to see the user's location, and swipe right to chat with the user. I'm using this with a UIPageViewController, and it's quite hard to have JSQMessagesViewController to coexist with this UIPageViewController. Since the UIPageViewController retains the state of the chat view, I need to constantly re-assign new model data (i.e. setting a new "other user" and their respective profile picture avatar). I'm getting this error a lot:

*** Assertion failure in -[Demo2MessagesViewController viewWillAppear:], /JSQMessagesViewController/Controllers/JSQMessagesViewController.m:223
2015-06-20 21:37:34.583 Nightstir[14218:414635] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: self.senderId != nil'

This error only happens when I swipe left to see the user's location FIRST and THEN swipe right to chat with the user. The following is my code to reassign model data to my chat view controller whenever you want to chat with a new user:

```
/**
 *  Override point for customization.
 *
 *  Customize your view.
 *  Look at the properties on `JSQMessagesViewController` and `JSQMessagesCollectionView` to see what is possible.
 *
 *  Customize your layout.
 *  Look at the properties on `JSQMessagesCollectionViewFlowLayout` to see what is possible.
 */
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    self.demo2Data = self.chatContainerViewController.demo2Data;
    
    self.demo2Data.messages = [[NSMutableArray alloc] init];
    /**
     *  You MUST set your senderId and display name
     */
    self.senderId = self.demo2Data.mainUser.id.description;
    self.senderDisplayName = self.demo2Data.mainUser.fullName;
    
    /**
     *  You can set custom avatar sizes
     */
    if (![NSUserDefaults incomingAvatarSetting]) {
        self.collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeZero;
    }
    
    if (![NSUserDefaults outgoingAvatarSetting]) {
        self.collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero;
    }
    
    self.showLoadEarlierMessagesHeader = NO;
    
    /**
     *  Customize your toolbar buttons
     *
     *  self.inputToolbar.contentView.leftBarButtonItem = custom button or nil to remove
     *  self.inputToolbar.contentView.rightBarButtonItem = custom button or nil to remove
     */
    self.inputToolbar.contentView.leftBarButtonItem = nil;
    
    //Set a maximum height for the input toolbar
    self.inputToolbar.maximumHeight = 100;
}

-(void)updateMessages {
    [Chat getChatsForId:self.demo2Data.otherUser.id SuccessCallback:^(NSArray* chats){
        NSMutableArray *messagesCopy = [[NSMutableArray alloc] init];
        dispatch_async(dispatch_get_main_queue(), ^{
            for (Chat *chat in chats) {
                JSQMessage *message = [[JSQMessage alloc] initWithSenderId:chat.senderId
                                                         senderDisplayName:self.demo2Data.otherUser.fullName
                                                                      date:chat.date
                                                                      text:chat.text];
                [messagesCopy addObject:message];
            }
            self.demo2Data.messages = [messagesCopy mutableCopy];
            [self.collectionView reloadData];
        });
    } errorCallback:^(NSString* error) {
        
    }];

}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    if (self.demo2Data.otherUser != self.chatContainerViewController.demo2Data.otherUser)
    {
        self.demo2Data = self.chatContainerViewController.demo2Data;
    }
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    /**
     *  Enable/disable springy bubbles, default is NO.
     *  You must set this from `viewDidAppear:`
     *  Note: this feature is mostly stable, but still experimental
     */
    self.collectionView.collectionViewLayout.springinessEnabled = NO;
    /**
     *  You MUST set your senderId and display name
     */
    self.senderId = self.demo2Data.mainUser.id.description;
    self.senderDisplayName = self.demo2Data.mainUser.fullName;
    self.updateTimer = [NSTimer scheduledTimerWithTimeInterval: 5.0 target: self
                                                      selector: @selector(updateMessages) userInfo: nil repeats: YES];
    [self.updateTimer fire];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
//    self.updateTimer = nil;
    [self.view endEditing:YES];
    [self.updateTimer invalidate];
}

- (void)viewDidDisappear:(BOOL)animated
{
    [self.demo2Data.messages removeAllObjects];
    [self.collectionView reloadData];
}
```

Am I resetting the chat view's model data the correct way? I'm wondering if it's just happening too slow, and if the way you do it in the demo with using the dispatch_async/dispatch_get_main_queue should be used to make it faster. I just need this chat view to be uncrashable and handle dynamic data at the same time.

Any help or advice would be appreciated. Thanks.

**Comment by cnowak7** [comment]
Just so you know that I'm a beginner programmer and all this is pretty complex for me. I'm even surprised that I made it this far with the project app behaving very well, so any help to a humble and thirsty for knowledge programmer would be appreciated. Thanks! :D

**Comment by jessesquires** [comment]
the assert that's throwing is in the super class's `viewDidAppear:`.

to avoid this, (1) set `senderId` **before** `viewDidAppear:` (preferable) or (2) set it before calling `super`

**Comment by cnowak7** [comment]
So even though the error said it's a problem with the viewWillAppear, the problem is happening in the viewDidAppear. My code was what I tried to fix it with, by moving everything from viewWillAppear to viewDidAppear. But either way the error is always in viewWillAppear. So is viewDidAppear the ideal one to reassign model data? What's the difference, if you don't mind me asking, for future knowledge.

**Comment by cnowak7** [comment]
Ok I tried your second option putting everything in viewDidAppear before calling `super`, but I still got the same error. I tried your first option by putting everything in viewWillAppear after calling `[super viewWillAppear:animated]`, and I still got the same error.

But I finally fixed it by putting all the re-assigning in `viewWillAppear` BEFORE calling `[super viewWillAppear:animated]` as shown below:

```
- (void)viewWillAppear:(BOOL)animated
{
    if (self.demo2Data.otherUser != self.chatContainerViewController.demo2Data.otherUser)
    {
        NSLog(@"JUST SET DIFFERENT USER");
        self.demo2Data = self.chatContainerViewController.demo2Data;
    }
    /**
     *  You MUST set your senderId and display name
     */
    self.senderId = self.demo2Data.mainUser.id.description;
    self.senderDisplayName = self.demo2Data.mainUser.fullName;
    self.updateTimer = [NSTimer scheduledTimerWithTimeInterval: 5.0 target: self
                                                      selector: @selector(updateMessages) userInfo: nil repeats: YES];
    [self.updateTimer fire];
    [super viewWillAppear:animated];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    /**
     *  Enable/disable springy bubbles, default is NO.
     *  You must set this from `viewDidAppear:`
     *  Note: this feature is mostly stable, but still experimental
     */
    self.collectionView.collectionViewLayout.springinessEnabled = NO;
}
```

Worked great! Thanks a ton for your help, I really appreciate it! :)

**Comment by jessesquires** [comment]
Oops! Sorry about that @cnowak7 - I was one method off.

I meant to say that you should move everything to `viewDidLoad`. Your solution works by calling `[super viewWillAppear:animated];` last, but `viewDidLoad` is a better place for this.

**Comment by cnowak7** [comment]
Awesome, no worries man. Just to be safe, I gotta find a way to make the
viewDidLoad to be called every time the user scroll to the chat view, since
UIPageViewController retains the instance of the chat view and make it call
viewDidLoad only once.
