### ISSUE TITLE
Language on UIMenuController

### ISSUE THREAD

**Issue by patriciasousacarbon** [jessesquires/JSQMessagesViewController#1044]
Hi,

I'm having a problem with setting the language on UIMenuController. I want to set another language on "Copy"/"Define" options that appears on log press in the cell. How can I set the language of the UIMenuController items? I'm trying without success...

Thank You.
Best regards.

**Comment by jstart** [comment]
@patriciasousacarbon Most of the strings in JSQMessagesViewController is localized and that is handled by the system.  When the user updates the iOS system locale, it should update the Copy/Define strings as well.  Can you attach a screenshot of the incorrect language being shown?

**Comment by jessesquires** [comment]
Hey @patriciasousacarbon :smile: 

Copy/Define/etc are provided by iOS. If you have custom MenuItems, you can initialize them with localized strings.
