### ISSUE TITLE
Time stamp

### ISSUE THREAD

**Issue by nachkar** [jessesquires/JSQMessagesViewController#1046]
How can I add the timestamp label inside the bubble and add the read ,delivered and sent ticks ??

**Comment by jstart** [comment]
@nachkar can you attach a screenshot of what you want the bubble to look like?

Are you saying that you want it to appear all inside the chat bubble something like this?

Hello
Sent: 4:20 PM 1/1/1 Read :heavy_check_mark:

**Comment by mohonish** [comment]
@jstart hey! i would like to know the approach that I should take to implement timestamps similar to your example.

**Comment by HuppDevelopers** [comment]
Any body has solution for the issue raised by @nachkar?
I want to add same functionality.
@jstart  same as what we have in whatsApp.
please help. 
***read ,delivered and sent tick marks with timestamp

![example](https://cloud.githubusercontent.com/assets/26135696/25553626/ba461d06-2cd5-11e7-890c-5725f20b8a3c.png)
