### ISSUE TITLE
Media Placeholder

### ISSUE THREAD

**Issue by nachkar** [jessesquires/JSQMessagesViewController#1047]
The media placeholder needs to be more flexible to change , Im having trouble setting it behind the activity indicator than changing it when image finish downloading. how can we do that ??

**Comment by jessesquires** [comment]
hey @nachkar - you can subclass or create your own media items. just follow the pattern from the existing ones

**Comment by neerajneeruz** [comment]
How can i display the JSQMessagesMediaPlaceholderView to show the indicator that the image is not yet downloaded from the web? i didnt find any thread that describes how to use JSQMessagesMediaPlaceholderView item . can you please help me
