### ISSUE TITLE
[Feature] Implement JSQAudioMediaItem

### ISSUE THREAD

**Issue by nachkar** [jessesquires/JSQMessagesViewController#1049]
If possible to add an audio bubble where this media could be played and stopped (As whatsapp).

**Comment by sam961** [comment]
It will be a nice feature if implemented!!!

**Comment by jessesquires** [comment]
pull requests are welcome :smile:

**Comment by lijie121210** [comment]
I added this feature in my app..... in swift.....sorry about that.😓  I really think this framework is easy to expand.

**Comment by KhaledAld** [comment]
@lijie121210  how to expand ????

**Comment by KhaledAld** [comment]
@lijie121210  can you help me ??

**Comment by lijie121210** [comment]
sorry...busy days...some main classes are here: https://github.com/lijie121210/EXTJSQMediaMessage  
I will commit images later...

**Comment by lijie121210** [comment]
@KhaledAld

**Comment by KhaledAld** [comment]
@lijie121210  
the play button is don't apper  
only show empty bubble

**Comment by lijie121210** [comment]
if you want to use the default button image on the cell, you can do this : In class: AudioMediaItem -> fun mediaView(_:) ->  let playIcon = UIImage.jsq_defaultPlayImage()

but I think you should know that there never has a button on the cell.  Play action should write  in :

override func collectionView(collectionView: JSQMessagesCollectionView!, didTapMessageBubbleAtIndexPath indexPath: NSIndexPath!) {
        let message = self.messages[indexPath.row]
        if message.isMediaMessage {
            if let audio = message.media as? AudioMediaItem {
                self.playAudioRecoderMessage(audio)
            }
            if let photo = message.media as? JSQPhotoMediaItem {
                self.playPhotoMessageSkimming(photo)
            }
        }
    }

**Comment by lijie121210** [comment]
@KhaledAld

**Comment by KhaledAld** [comment]
@lijie121210  
i want to show play button and progress bar  as (whatsapp)

**Comment by lijie121210** [comment]
@KhaledAld   
In class: AudioMediaItem -> fun mediaView(_:)    In this function you can set a default image, and when user tapped the bubble ;
and in func collectionView(_: didTapMessageBubbleAtIndexPath _: )   you can change the image as you want,  and show a progress view on the bubble... 

" talk is cheap  "  but I can not show you the code,  It is the end of the period, I have to finish my paper in this month. sorry...

**Comment by syrakozz** [comment]
@jessesquires it looks good , could you plz add this feature in this project,

**Comment by jessesquires** [comment]
Hi all! :smile: -- please use this thread for discussing:

- the merits of this feature / inclusion in the library
- implementation details or advice
- coordinating work or pull requests

Anything else is distracting for collaborators. Thanks!

**Comment by kshrikant** [comment]
@lijie121210 @jessesquires @KhaledAld Please can you explain in detail how to use EXTJSQMediaMessage in JSQMessagesViewController, that will be really helpful. Or any other options for audio messages ?

**Comment by eliburke** [comment]
@jessesquires I have an implementation of JSQAudioMediaItem that I can submit. It takes a URL or NSData, uses AVAudioPlayer, and shows a progress bar and timer label while playing. However, it seems like the sort of control that could be customized about 1 million ways, so I don't know if it is better to submit as is, or do additional work to make it customizable, or throw it into the demo project as an example. 

Let me know if you'd like me to submit against release_8.0 or develop or just post the code. It is currently self-contained, which is why it shows the triple dots image instead of a pause button)

![jsqaudiomediaitem](https://cloud.githubusercontent.com/assets/2371768/13617048/bf400b9c-e54a-11e5-93e4-85f7024eb38d.gif)

**Comment by jessesquires** [comment]
@eliburke -- nice! :+1: 

I think we could definitely leverage your work here. It looks like you've got everything working and hooked up! So the hardest part is done :smile: 

Per the library's design goals, our default should be as similar to iMessage as possible:

![img](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone5s/keep_audio_message.png)

iMessage has this fancy sound wave scrubber UI, but we can just use a simple `UISlider` like you have here. 

So changes would be: a more compact message bubble with a `play` button, `UISlider`, and `UILabel` on the right.

If possible, it would be great to customize colors/tintColors.

**Comment by jessesquires** [comment]
@eliburke 

So, not sure if you're up for that — but if so, I'd be happy to accept a PR! :smile: 

Not sure if `develop` or `release_8.0` would be best yet. I'd probably have to see it first. :grin: 

Regardless, I think posting a link to the code here would be a huge help for the community for those who want to add this now. (And it will help me in the future if you aren't able do a PR.)

**Comment by imran-y** [comment]
@eliburke 

Can you please share the link, so that we can get help from it, while it gets integrated in release? As soon as possible would be highly appreciated :-)

**Comment by eliburke** [comment]
Yes @imran-y I know there's pent up demand; lots of requests and issues related to playing audio. :) I'm going to take some time today to see if I can transform it along the lines that @jessesquires mentioned. If you can't wait or I get hit by a bus, take a look at SYWaveformPlayerView it does all the same stuff and just needs to be massaged into a MediaItem class.

**Comment by eliburke** [comment]
Ok, I've created PR #1495 against develop. The updated mediaView now looks like this:
![audiomedia](https://cloud.githubusercontent.com/assets/2371768/13652832/85e911a4-e61c-11e5-9752-2454dc364ab8.gif)

I'm not averse to creating a waveform view to replace the progress bar, but I wanted to your approval for a baseline implementation first. Also, I know you don't want to create external dependencies so I'd need to know if you care about me borrowing code liberally from another github project (SCWaveformView)

**Comment by jessesquires** [comment]
@eliburke this is beautiful! :star2: :heart_eyes: 

One nit for the UI, the timestamp label should be formatted `0:00`.

------------

RE: SCWaveFormView

I haven't looked at the PR yet, but will soon. For now, I think this is great! 

But, if you want to try this:
- You're correct, we should definitely minimize dependencies. I'd rather borrow code. But we should attribute it appropriately in the header comments.
- Implementing something similar to SCWaveFormView should be a separate PR
- This should *definitely* be submitted against `release_8.0`

--------

Side note:
I think for 8.0, I'm going to break up the library into subspecs — particularly for media items. This way, people can include only the media items that they want to use, and we can start including better implementations of each media item. e.g., the wave form for audio, thumbnail previews for video, etc

**Comment by syrakozz** [comment]
+1

**Comment by eliburke** [comment]
@jessesquires I'm glad you like it. You'll see when you look at the code but I have clips <60s formatted as ss.s, then mm:ss, then hh:mm:ss. If you think it needs to be strictly mm:ss I'd like to expose the format method for subclassing or add an enumeration to control its behavior.

**Comment by jessesquires** [comment]
Completed in #1495

**Comment by deore123** [comment]
@jessesquires I am new to JSQMessageViewController framework. I want learn more about the Audio feature. Can you please share the code for, how to record and send an audio using JSQMessageViewController? I really appreciate your help
