### ISSUE TITLE
How to add Activity Indicator to the Media Item

### ISSUE THREAD

**Issue by sahabe1** [jessesquires/JSQMessagesViewController#1050]
Hi jessesquires,

I want to add activity Indicator on the media item can you help us how we can add indicator to imageview

Thanks.

**Comment by jstart** [comment]
@sahabe1 Can you explain your use case in more detail?  Do you want to show a loading spinner while an image is being downloaded, then hide it when the download completes?

**Comment by TheEngineerz** [comment]
Yes I want to do the same can you @jstart  can you please tell what is the best procedure for doing it. for example if i want to add MBProgressHUD with progress

**Comment by sahabe1** [comment]
yes, I want to show a loading spinner while an image is being downloaded, then hide it when the download completes?

**Comment by sahabe1** [comment]
yes, I want to show a loading spinner while an image is being downloaded,
then hide it when the download completes?

**Comment by alezoffoli** [comment]
Idea
You can subclass JSQPhotoMediaItem (or whatever you're using) and control yourself wheter you're curently downloading the media or not

Then override mediaPlaceholderView() and return viewWithActivityIndicator() when downloading and some other view when not...

**Comment by flavionegrao** [comment]
This is what I’m handling it. Obviously you can go a way fancier if you want to, it’s showing only a spinner but the idea is the same.

Cheers, F

----------


@interface HXPhotoMediaItem : JSQPhotoMediaItem
- (instancetype)initWithPlaceholderImage:(UIImage *)placeholderImage;
@property (copy, nonatomic) UIImage* placeHolderImage;
@property (assign,nonatomic) BOOL loading;
@end


——


@interface HXPhotoMediaItem()
@property (nonatomic,strong) UIImageView* cachedPlaceholderImageView;
@property (nonatomic,strong) UIActivityIndicatorView* spinner;
@end

@implementation HXPhotoMediaItem

- (instancetype)initWithPlaceholderImage:(UIImage *)image
{
    self = [super init];
    if (self) {
        _placeHolderImage = [image copy];
        _cachedPlaceholderImageView = nil;
    }
    return self;
}

- (void)clearCachedMediaViews
{
    [super clearCachedMediaViews];
    _cachedPlaceholderImageView = nil;
}

- (void)setPlaceHolderImage:(UIImage *)placeHolderImage
{
    _placeHolderImage = [placeHolderImage copy];
    _cachedPlaceholderImageView = nil;
}

- (void)setAppliesMediaViewMaskAsOutgoing:(BOOL)appliesMediaViewMaskAsOutgoing
{
    [super setAppliesMediaViewMaskAsOutgoing:appliesMediaViewMaskAsOutgoing];
    _cachedPlaceholderImageView = nil;
}

- (UIView *)mediaPlaceholderView {
    if (!self.placeHolderImage) {
        return nil;
    }
    
    if (!self.cachedPlaceholderImageView) {
        CGSize size = [self mediaViewDisplaySize];
        UIImageView *imageView = [[UIImageView alloc] initWithImage:self.placeHolderImage];
        imageView.frame = CGRectMake(0.0f, 0.0f, size.width, size.height);
        imageView.contentMode = UIViewContentModeScaleAspectFill;
        imageView.clipsToBounds = YES;
        self.cachedPlaceholderImageView = imageView;
        
        if (self.loading) [self configSpinner];
        
        [JSQMessagesMediaViewBubbleImageMasker applyBubbleImageMaskToMediaView:imageView isOutgoing:self.appliesMediaViewMaskAsOutgoing];
    }
    
    return self.cachedPlaceholderImageView;
}

- (NSUInteger)hash
{
    return super.hash ^ self.placeHolderImage.hash;
}


- (void) setLoading:(BOOL)loading {
    _loading = loading;
    if (loading) {
        [self configSpinner];
    } else {
        [self.spinner removeFromSuperview];
        self.spinner = nil;
    }
}

- (void) configSpinner {
    if (!self.cachedPlaceholderImageView) return;
    
    if (!self.spinner) {
        UIActivityIndicatorView *spinner = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge];
        [spinner startAnimating];
        spinner.translatesAutoresizingMaskIntoConstraints = NO;
        [self.cachedPlaceholderImageView addSubview:spinner];
        [self.cachedPlaceholderImageView addConstraint:[NSLayoutConstraint constraintWithItem:self.cachedPlaceholderImageView attribute:NSLayoutAttributeCenterX relatedBy:NSLayoutRelationEqual toItem:spinner attribute:NSLayoutAttributeCenterX multiplier:1 constant:0]];
        [self.cachedPlaceholderImageView addConstraint:[NSLayoutConstraint constraintWithItem:self.cachedPlaceholderImageView attribute:NSLayoutAttributeCenterY relatedBy:NSLayoutRelationEqual toItem:spinner attribute:NSLayoutAttributeCenterY multiplier:1 constant:0]];
        self.spinner = spinner;
    }
}


#pragma mark - NSCoding

- (instancetype)initWithCoder:(NSCoder *)aDecoder
{
    self = [super initWithCoder:aDecoder];
    if (self) {
        _placeHolderImage = [aDecoder decodeObjectForKey:NSStringFromSelector(@selector(placeHolderImage))];
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)aCoder
{
    [super encodeWithCoder:aCoder];
    [aCoder encodeObject:self.placeHolderImage forKey:NSStringFromSelector(@selector(placeHolderImage))];
}

#pragma mark - NSCopying

- (instancetype)copyWithZone:(NSZone *)zone
{
    HXPhotoMediaItem *copy = [[[self class] allocWithZone:zone] initWithPlaceholderImage:self.placeHolderImage];
    copy.image = self.image;
    copy.appliesMediaViewMaskAsOutgoing = self.appliesMediaViewMaskAsOutgoing;
    return copy;
}

**Comment by jessesquires** [comment]
thanks for the answers everyone! :smile:
