### ISSUE TITLE
Adding attributed text with NSAttachment in bubble

### ISSUE THREAD

**Issue by bizibizi** [jessesquires/JSQMessagesViewController#1052]
How can I achieve it?

I tried a log of staff but can not get it, please advise some way

**Comment by jessesquires** [comment]
Hey @bizibizi - This will require lots of changes in the library. But https://github.com/jessesquires/JSQMessagesViewController/issues/347#issuecomment-130533179 will help. 

I would suggest asking this on StackOverflow. That's a better place for this kind of question. :smile:

**Comment by rkittinger** [comment]
Anyone have experience embedding animated gifs within the text message? NSAttachment does not animate its attachments... This is a very important criteria for us choosing this framework.
