### ISSUE TITLE
how to calculate bubble height after customizing bubble width

### ISSUE THREAD

**Issue by brianhu** [jessesquires/JSQMessagesViewController#1054]
I need to shorten the bubble width in some situations.
I can shorten it with setting `customAttributes.messageBubbleContainerViewWidth` in `- collectionView:cellForItemAtIndexPath:`.
However, the height of the bubble doesn't change accordingly after I customized the width, so the bubble would not be big enough to show all the text.
How do I make the framework update the height?
Thanks!

**Comment by gcarlo89** [comment]
Hi @brianhu , I've been trying to  change my bubbles width (customAttributes.messageBubbleContainerViewWidth) from collectionView:cellForItemAtIndexPath: but I've had no success, can you give me some pointers? maybe I'm missing some instruccion to relayout the cell?

**Comment by brianhu** [comment]
Hi @gcarlo89 
here is how I set the bubble width in `collectionView:cellForItemAtIndexPath:` (it's in Swift, but the idea is the same)

        let customAttributes = self.collectionView.layoutAttributesForItemAtIndexPath(indexPath) as! JSQMessagesCollectionViewLayoutAttributes
        customAttributes.messageBubbleContainerViewWidth -= aValue
        cell.applyLayoutAttributes(customAttributes)

after setting the bubble width, you also need to subclass `JSQMessagesCollectionViewFlowLayout` and do something in `sizeForItem`

    override func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        let customLayout = CustomMessagesCollectionViewFlowLayout()
        
        let size = customLayout.sizeForItem(self.collectionView(collectionView as! JSQMessagesCollectionView, messageDataForItemAtIndexPath: indexPath), longestMetaWidth: self.longestMetaWidth!)
        return size
    }

The key to customize `JSQMessagesCollectionViewFlowLayout` is overriding `messageBubbleSizeForItem:` (I used obj-c for the subclass) and changing this line:

        CGFloat maximumTextWidth = self.itemWidth - kJSQMessagesCollectionViewAvatarSizeDefault - aValue - horizontalInsetsTotal;
        
You may need to pass some values to this method to calculate the maximum text width, so actually you will probably not be "overriding" the method.  You will be creating a new method who takes your variable and returns the size calculated by your variable instead. The most part of this new method would be the same as the `messageBubbleSizeForItem` though.

**Comment by gcarlo89** [comment]
Wow! incredible detailed explanation, thanks a lot @brianhu !

**Comment by jessesquires** [comment]
Hey guys, this should now be easier. See https://github.com/jessesquires/JSQMessagesViewController/issues/347#issuecomment-130533179

**Comment by jessesquires** [comment]
Also, thanks for the answers @brianhu ! :smile:
