### ISSUE TITLE
Subclassing JSQMessagesCollectionView

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#1055]
@jessesquires 

I've run into a few places where I would like to customize JSQMessagesCollectionView, but I will need to make a few changes to JSQMessagesCollectionView to achieve the right effects.

Would you be open to a PR which does changes jsq_configureCollectionView to get the class for JSQMessagesTypingIndicatorFooterView & JSQMessagesLoadEarlierHeaderView from a method, rather than hard-coded.

It will be simple/tight change and will allow the developer to change the look of the Typing Indicator & the Load Earlier views. Low risk & zero impact to existing to developers.

Ray

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
