### ISSUE TITLE
display nickname instead of avatar image

### ISSUE THREAD

**Issue by hohl** [jessesquires/JSQMessagesViewController#1061]
Is there any way to display the nick of the user by an label instead of showing an avatar image?

**Comment by danipralea** [comment]
```[JSQMessagesAvatarImageFactory avatarImageWithUserInitials:@"ME"
                                                              backgroundColor:[UIColor colorWithWhite:0.85f alpha:1.0f]
                                                                    textColor:[UIColor colorWithWhite:0.60f alpha:1.0f]
                                                                         font:FONT_OPENSANS_SEMIBOLD_STD(13)
                                                                     diameter:kJSQMessagesCollectionViewAvatarSizeDefault];```

**Comment by jstart** [comment]
@hohl does @danipralea code snippet do what you are looking for?  Or are you looking for being able to put a small text label next to or under the chat message?  Can you attach a screenshot of the desired visuals?

**Comment by hohl** [comment]
No, I'm sorry. I've already be aware of the initials avatar images. However I'm looking a small text label instead, where it's possible to display the users nick, like "hohl", "jstart" or "danipralea".

**Comment by mp3il** [comment]
I'm looking for this feature (or some patch?) too.
Did you came up with something?

**Comment by jessesquires** [comment]
@hohl -- doesn't `senderDisplayName` do what you want?
