### ISSUE TITLE
setting min width for some bubbles [Help]

### ISSUE THREAD

**Issue by gcarlo89** [jessesquires/JSQMessagesViewController#1062]
Hi! awesome library, I was wondering which was the correct approach to setting a minimum width for some bubbles. I've tried overriding the applyLayoutAttributes: in my custom cell, but I need access to my datasource to know which cell should have a minimum width. I've been tinkering with messageBubbleLeftRightMargin in cellForItemAtIndexPath: but with no results. 
Any pointers would be great

**Comment by gcarlo89** [comment]
Ok, so I was missing the instruction [cell applyLayoutAttributes: customAttributes] in cellForItemAtIndexPath

**Comment by freak4pc** [comment]
What was the solution for this eventually ... ?

**Comment by gcarlo89** [comment]
yup, I still get some side effects when I delete a cell (it flashes back to its old width), I had to reload data in the completion block of performBatchUpdates to negate this effect. Hope I can find another way
