### ISSUE TITLE
JSQMessagesViewController in UIScrollView makes view hierarchy disappear

### ISSUE THREAD

**Issue by gudbergur** [jessesquires/JSQMessagesViewController#1067]
I have this view hierarchy:
* UINavigationController
   * view 
       * CustomViewController
          * custom view
               * UIScrollView instance
                    * JSQMessagesViewController subclassed instance

While adding the JSQMessagesViewController subclassed instance directly to the custom view works fine, adding the subclassed instance to UIScrollView makes the app exhibit some bizarre behavior in that not only does the JSQMessagesViewController not show up but the UIScrollView instance disappears.

Any idea what's going on here? I've tried lots of different things such as having intermediary content view between scrollview and the JSQMessagesViewController instance etc, as well as updating to the develop branch of JSQMessagesViewController.

**Comment by jessesquires** [comment]
hey @gudbergur - this doesn't sound specific to this library. i would try asking on StackOverflow

**Comment by gudbergur** [comment]
@jessesquires: I would be inclined to agree, but this odd behavior only happens when the viewcontroller is an instance of JSQMessagesViewController, if I change it to any other view controller everything works fine... I'm using view controller containment API's and then just using addSubview to the scrollview if it sheds any more light on the issue
