### ISSUE TITLE
How to custom textView in Swift?

### ISSUE THREAD

**Issue by paterlini** [jessesquires/JSQMessagesViewController#1069]
<img width="430" alt="2015-07-05 13 22 47" src="https://cloud.githubusercontent.com/assets/9257530/8511319/f8e4de76-2318-11e5-84d1-6528b9959e75.png">
I want customize my textView. How can I do that?

**Comment by jessesquires** [comment]
hey @paterlini - the textView can be customized just like any other `UITextView`. see the docs for details.
