### ISSUE TITLE
Remote avatars (loaded from URL)

### ISSUE THREAD

**Issue by danipralea** [jessesquires/JSQMessagesViewController#1071]
Is it by any chance possible to have avatars loaded from an URL ?
Have a compatibility with SDWebImageCache or AFNetworking (my case) as well maybe?

I think it would be really cool to have that.

**Comment by jstart** [comment]
@danipralea You should be able to do this pretty simply by subclassing JSQMessagesCollectionViewCell.  I don't think this project should be tied to tightly to any specific image fetching/caching framework.  Can you explain your specific use case?

**Comment by jessesquires** [comment]
This issue is discussed at length in many other issues, please see those threads:

https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+SDWebImage+is%3Aclosed

**Comment by jstart** [comment]
@jessesquires Would this be a good candidate for like a FAQ or Wiki page in the project?  Would you accept a PR documenting this issue?

**Comment by jessesquires** [comment]
@jstart - sounds good :+1:
