### ISSUE TITLE
About the bubble dynamic font size 

### ISSUE THREAD

**Issue by wodetian** [jessesquires/JSQMessagesViewController#1072]
hello,Do you already have a solution this problem, or is doing? 
This is you provide the Demo‘s screenshots

<img src="http://i3.tietuku.com/8aeeebab1c880480.jpg" width=300 />
<img src="http://i3.tietuku.com/4cf8e111828060f5.jpg" width=300 />

I did not understand what you said `messageHash`, can you show me?

**Comment by eak65** [comment]
I am having the same problem. When a user types more than one line, the bubble accounts for the text, however it does not show the text

**Comment by jstart** [comment]
@eak65 @wodetian can you create a sample project that reproduces the issue?  Are you saying that the dynamic text resizing isn't working properly?

**Comment by wodetian** [comment]
Don't need, you just need to run your own ![sample Demo](https://github.com/jessesquires/JSQMessagesViewController/archive/develop.zip) , and then adjust the equipment text to a minimum, would I have described problems. 

##### You can also such 

1.![download](https://github.com/jessesquires/JSQMessagesViewController/archive/develop.zip) 
2.`unzip` && `pod install`
3. Adjust equipment the default size 
<img src ='http://i3.tietuku.com/82868ed881b2f756.gif' width=300/>
4.Running will appear these problems  

Thank you very much  🍺🍺🍺🍺

**Comment by jstart** [comment]
@wodetian Let me take a look at this and test it out and see if we can come up with a solution.

**Comment by wodetian** [comment]
Thank you very much ,I wish you success  
🍺🍺🍺🍺🍺🍺

**Comment by jessesquires** [comment]
Issue #497 is tracking support for dynamic type
