### ISSUE TITLE
Input Toolbar Buttons not appearing

### ISSUE THREAD

**Issue by dealaus** [jessesquires/JSQMessagesViewController#1073]
When I build, just the text input bar takes the entire width of the toolbar, and no buttons are present. it makes it impossible to send a message. I even tried to, redundantly, set the buttons to the default in viewDidLoad(). Thoughts? Am I missing something I should be doing?

<img width="432" alt="screen shot 2015-07-06 at 6 35 51 pm" src="https://cloud.githubusercontent.com/assets/9124650/8534797/c96ee542-240d-11e5-9a1a-99171196bb1a.png">

**Comment by jessesquires** [comment]
can you reproduce this in the demo?

**Comment by dealaus** [comment]
I haven't been able to so far. The only customization of the controller I do is removing avatars and setting senderID/display name.

**Comment by gcarlo89** [comment]
Can you provide code in your viewDidLoad() where you customize the inputToolbar? You can try adding this line at the end:
self.inputToolbar.contentView.rightBarButtonItem = [JSQMessagesToolbarButtonFactory defaultSendButtonItem];
This one should set you the default Send button

**Comment by dealaus** [comment]
I already tried to manually set it to default with no luck.
   
 override func viewDidLoad() {
        super.viewDidLoad()

        Wit.sharedInstance().delegate = self
        
        title = userInfo.firstName + " " + userInfo.lastName
        navigationController?.navigationBar.topItem?.title = "Logout"
        automaticallyScrollsToMostRecentMessage = true


        collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero
        collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeZero
        self.senderId = USER_MESSAGE_ID
        self.senderDisplayName = userInfo.firstName
        self.inputToolbar.contentView.rightBarButtonItem = JSQMessagesToolbarButtonFactory.defaultSendButtonItem()
        
        
    }

**Comment by dealaus** [comment]
Not sure what caused the issue. I reloaded the controller again (I had done this probably 5 times already) and it now works. Looking into the issue.
