### ISSUE TITLE
Bubble image overlaps with status bar 

### ISSUE THREAD

**Issue by dealaus** [jessesquires/JSQMessagesViewController#1074]
I found in 7.1.0 that when the view controller has no top bar and the first message is an incoming message, that message will overlap the status bar until the input toolbar is selected. 

<img width="432" alt="screen shot 2015-07-07 at 3 04 23 pm" src="https://cloud.githubusercontent.com/assets/9124650/8554760/8116e608-24b9-11e5-875a-9324ac9d72c2.png">
<img width="432" alt="screen shot 2015-07-07 at 3 04 27 pm" src="https://cloud.githubusercontent.com/assets/9124650/8554765/8a6b401e-24b9-11e5-95da-55355d4491b1.png">

**Comment by pprevalon** [comment]
you can change the inset "topContentAdditionalInset = 100"

**Comment by jessesquires** [comment]
yep. `topContentAdditionalInset` or collection view content insets
