### ISSUE TITLE
Chat bubbles not spanning container width, spanning message width instead

### ISSUE THREAD

**Issue by sahirc** [jessesquires/JSQMessagesViewController#1075]
I've included JSQMessagesViewController as a container in another view. I haven't touched the logic around bubble rendering, but the chat bubbles I'm seeing don't span the width of the container. They span the width of the text they contain. From the examples I've seen of this awesome pod, that doesn't seem to be the default behavior. I've attached a screenshot of what I'm seeing. Any ideas on what's going on? If there's some code you'd like to see let me know and I'll attach a gist

<img width="349" alt="screen shot 2015-07-07 at 4 28 28 pm" src="https://cloud.githubusercontent.com/assets/8335749/8559751/82dd3ce2-24c5-11e5-9e8f-faf5bb5b69c9.png">

**Comment by TheEngineerz** [comment]
Yes exactly jessesquiries  please tell the best way to span the chat bubbles in text or media item. what we should do if we want to include the top/bottom label inside the chat bubble

**Comment by gcarlo89** [comment]
@sahirc if you want the bubbles to span the width of the container, you could try the following in your JSQMessagesViewController subclass:

```
-(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath{
    JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];
    JSQMessagesCollectionViewLayoutAttributes *customAttributes =  (JSQMessagesCollectionViewLayoutAttributes *)[self.collectionView layoutAttributesForItemAtIndexPath:indexPath];

   //Set your superview frame
   customAttributes.messageBubbleContainerViewWidth = self.view.frame.size.width;
   [cell applyLayoutAttributes:customAttributes];

}
```

@TheEngineerz  If you want to include the top/bottom label inside the chat bubble, I haven't tested it but this could work, in the cell xibs you could modify the size and constraints of: the bubble container, the bubble image view, and leave the text view as it is, (keep in mind that you should always return the corresponding height in heightForMessageBubbleTopLabelAtIndexPath and heightForCellBottomLabelAtIndexPath).
Tell me if it worked for any of you

**Comment by jessesquires** [comment]
@gcarlo89 — No no no. You do not want to do this. Manipulating layout information and applying layout attributes in `cellForItemAtIndexPath:` is the wrong way to do this.

If you want to edit layout information, subclass `JSQMessagesCollectionViewLayoutAttributes` and `JSQMessagesCollectionViewFlowLayout`

>/cc @sahirc @TheEngineerz

**Comment by gcarlo89** [comment]
@jessesquires Thanks for the pointer, I will look into it (I'm kind of new to UICollectionViewLayoutAttributes in general)

**Comment by sahirc** [comment]
This is more of an obj-c question at this point, but could someone please elaborate on what @jessesquires means by "subclass JSQMessagesCollectionViewLayoutAttributes and JSQMessagesCollectionViewFlowLayout" ?

I took at look at both these header files and didn't see anything that would let me adjust the bubble width. @jessesquires  could you point me to which attributes I would need to modify to widen the chat bubbles?

**Comment by gcarlo89** [comment]
@sahirc what worked for me was the following: create a new file that subclasses `JSQMessagesCollectionViewFlowLayout` and override `messageBubbleSizeForItemAtIndexPath` example:

```
#import "CustomCollectionViewFlowLayout.h"
#import "BLMessage.h"

#import "JSQMessagesCollectionViewFlowLayout.h"

#import "JSQMessageData.h"

#import "JSQMessagesCollectionView.h"
#import "JSQMessagesCollectionViewCell.h"

#import "JSQMessagesCollectionViewLayoutAttributes.h"
#import "JSQMessagesCollectionViewFlowLayoutInvalidationContext.h"

#import "UIImage+JSQMessages.h"

@implementation CriptextCollectionViewFlowLayout
//if you are going to subclass JSQMessagesCollectionViewLayoutAttributes, you should return here your custom layout attributes class
+ (Class)layoutAttributesClass
{
    return [JSQMessagesCollectionViewLayoutAttributes class];
}

- (CGSize)messageBubbleSizeForItemAtIndexPath:(NSIndexPath *)indexPath
{
    CGSize superSize = [super messageBubbleSizeForItemAtIndexPath:indexPath];
    
    BLMessage *messageItem = [self.collectionView.dataSource collectionView:self.collectionView messageDataForItemAtIndexPath:indexPath];
    
    //check if outgoing
    if ([messageItem.condition) {
        superSize = CGSizeMake(175, superSize.height);
    }
    
    
    return superSize;
}

@end
```

Important! In your JSQMessagesViewController.xib change the current flowlayout (JSQCollectionViewFlowLayout) with your subclass (CustomCollectionViewFlowLayout)

**Comment by jessesquires** [comment]
thanks @gcarlo89 - this is correct :+1:

**Comment by sahirc** [comment]
That's really helpful, thanks! One question though, isn't the xib shipped as part of the Pod? If I change what's in the pod, do I run the risk of conflicts in the future when I run 'pod update'?

**Comment by TheEngineerz** [comment]
@jessesquires as you wrote 
"If you want to edit layout information, subclass JSQMessagesCollectionViewLayoutAttributes and JSQMessagesCollectionViewFlowLayout"

ok right but please can you tell more about how should i put the top/bottom label inside message bubble both for TEXT and Media Messages. i want to do same like Whatsapp do

**Comment by gcarlo89** [comment]
@sahirc You can change it programmatically in your `JSQMessagesViewController` subclass in your `viewDidLoad` with something like this
```objective-c
self.collectionView.collectionViewLayout = [[CustomCollectionViewFlowLayout alloc] init];
```

@TheEngineerz open up another issue with your topic, don't piggy back in this one, this is mainly for discoverability reasons for other people who may haver your same problem

**Comment by sahirc** [comment]
Thanks gcarlo89. one last question, Let's say I wanted the chat incoming chat bubbles to originate from the left and the outgoing bubbles to originate from the right, with the avatar photos on the left and right as well, do you know which classes would need to be subclassed to achieve that? Right now, everythng is left aligned for me. 
I'm going for something similar to the top-left photo in https://github.com/jessesquires/JSQMessagesViewController

**Comment by gcarlo89** [comment]
@sahirc check the demo which has the behaviour that you want, set your `self.senderId`, `self.senderDisplayName` and avatar sizes in your `viewDidLoad` and check the method overrides for the CollectionView
Cheers

**Comment by sahirc** [comment]
Hmm, I am running the demo project and I've been through all the overrides, still not seeing anything that would cause the avatar photos to appear on the right instead of the left. I am setting senderId and displayName, I've confirmed this since the chat bubbles do have different colors based on outgoing and incoming messages, but something is still causing the bubbles to be left-aligned as it were, and all the avatar images to appear on the left

**Comment by sahirc** [comment]
Nevermind, figured it out. The issue wasn't with my use of JSQMessagesViewController, but with my implementation of JSQMessage. I wasn't setting the senderId in the Message object correctly. Once I switched over to using JSQMessage, the bubbles started aligning themselves correctly. Thanks for all the help!

**Comment by dealaus** [comment]
Hey @gcarlo89, thanks for the help on that. I'm trying to add components to incoming messages only that will require increasing the height of the cell. I assume I just alter the incoming xib? I'm struggling to alter the height of the cell if my condition is met.

**Comment by ronasc** [comment]
Hi, I subclassed JSQMessagesCollectionViewFlowLayout as suggested and the with changes only for text messages. media messages stays with the old with. How can I solve this? Thanks
