### ISSUE TITLE
How to add UITapGestureRecognizer for dismissing keyboard?

### ISSUE THREAD

**Issue by sahirc** [jessesquires/JSQMessagesViewController#1076]
This ones a bit odd, but the keyboard is only dismissed if I tap in the collection view after the last message. So if I tap on a chat bubble, the keyboard isn't dismissed. The behavior I want is that tapping anywhere in the view dismisses the keyboard. I can't add a UIGestureRecognizer for a single tap to the whole view though, because it overrides the recognizer for the send button. 
Is there some property I need to set to achieve this or some other workaround that allows the recognizer for the send button to work despite of a tap recognizer for the whole view?

**Comment by jessesquires** [comment]
@sahirc - this should be like adding a tap gesture recognizer to any other view.

it shouldn't conflict with the send button, which uses target/selector — not a `UIGestureRecognizer`. if you are seeing this, then you are probably doing something wrong.

to achieve what you want, add the recognizer to the `collectionView`. if you have conflicts with other recognizers, see `UIGestureRecognizerDelegate`

**Comment by sahirc** [comment]
I've tried adding a recognizer to the collectionView, but I run into the original problem of certain pieces of the collectionView not responding to taps. Everything below the last chat bubble works fine, everything above it doesn't respond. Any ideas on where to even look for what the problem could  be?

**Comment by hmaidasani** [comment]
Hey @jessesquires, I'm having the same issue as @sahirc. The collectionView tap gestures don't get recognized everywhere. A simple tap outside the keyboard does not dismiss it. Below is the code which has been adapted from issue #360. Any suggestions? 

```
import UIKit
import Foundation

class ChatViewController: JSQMessagesViewController, UIGestureRecognizerDelegate {

...
...

   override func viewDidLoad() {
        super.viewDidLoad()
        ...
        addTapGestures()
        ...
   }

   func gestureRecognizer(UIGestureRecognizer,
        shouldRecognizeSimultaneouslyWithGestureRecognizer:UIGestureRecognizer) -> Bool {
            return true
   }
    
   func addTapGestures() {
        let gesture = UITapGestureRecognizer(target: self, action: Selector("tapAndHideKeyboard:"))
        self.collectionView.addGestureRecognizer(gesture)
   }
    
   func tapAndHideKeyboard(gesture: UITapGestureRecognizer) {
        println(gesture)
        if(gesture.state == UIGestureRecognizerState.Ended) {
            if(self.inputToolbar.contentView.textView.isFirstResponder()) {
                self.inputToolbar.contentView.textView.resignFirstResponder()
            }
        }
   }

...

}
```

**Comment by DRosadoYew** [comment]
@hmaidasani it should work when adding ```gesture.delegate = self``` to ```addTapGestures```.
