### ISSUE TITLE
How to block anything detected by implemented data detector 

### ISSUE THREAD

**Issue by nanohaddad** [jessesquires/JSQMessagesViewController#1077]
I'm trying to block phone numbers/email addresses, and miserably failing. Using the current data detector has anyone found a way to block the user from sending and/or seeing the detected message.

**Comment by jessesquires** [comment]
Override `cellForItemAtIndexPath:` and turn off data detectors on the `UITextView`

**Comment by jessesquires** [comment]
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesDemo/DemoMessagesViewController.m#L479-L515

**Comment by nanohaddad** [comment]
Just to clarify, i'm trying to sensor the data not disable the data detector

**Comment by jessesquires** [comment]
ahh, i see. that will all be custom work on your part. this doesn't have much to do with the library.
