### ISSUE TITLE
How to display sender name above chat bubble for outgoing messages?

### ISSUE THREAD

**Issue by RockawayLabs** [jessesquires/JSQMessagesViewController#1078]
Hello!

Thanks for creating this amazing library! I seem to be stuck finding a way to display the sender's name for outgoing messages. For incoming messages, this sender's name is displayed right above the chat bubble. However, for outgoing messages, the sender name is not displayed for obvious reasons. In my case, I would like to enable it so that I can see the name right above outgoing messages.

Any tips would be appreciated!

Thanks again!

**Comment by jessesquires** [comment]
https://github.com/jessesquires/JSQMessagesViewController#customize-your-cells

**Comment by matthewmb340** [comment]
I can't seem to get this working i have been using the attributedTextForMessageBubbleTopLabelAtIndexPath function and printing out the return value as well as printing out the value of cell.messageBubbleTopLabel.attributedText in JSQMessagesViewController.m line 531

i have tried a swift version of the code in DemoMessagesViewController as well as a version i found online:
override func collectionView(collectionView: JSQMessagesCollectionView, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath) -> NSAttributedString? {
	var message: JSQMessage = messages[indexPath.item]
	print(message)
	/**
	 *  iOS7-style sender name labels
	 */
	if (message.senderId == self.senderId) {
		print(message.senderId)
		return nil
	}
	if indexPath.item - 1 > 0 {
		var previousMessage: JSQMessage = messages[indexPath.item - 1]
		if (previousMessage.senderId == message.senderId) {
			print(previousMessage.senderId)
			return nil
		}
	}
	/**
	 *  Don't specify attributes to use the defaults.
	 */
	let r =  NSAttributedString(string: message.senderDisplayName)
	print(r)
	return r
}

found online:
override func collectionView(collectionView: JSQMessagesCollectionView?, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        let message = messages[indexPath.item]
        switch message.senderId {
        case senderId:
            return nil
        default:
            guard let senderDisplayName = message.senderDisplayName else {
                assertionFailure()
                return nil
            }
            let r = NSAttributedString(string: senderDisplayName)
            print(r)
            return r
            
        }
    }

Both of these return the correct value and set cell.messageBubbleTopLabel.attributedText in JSQMessagesViewController.m line 531 however it is not displayed when ran (yes it returns null for messages the user sends but for any other user it returns the displayName but doesn't appear in the simulator)
