### ISSUE TITLE
cell.avatarImageView.contentmode has no effect when changed

### ISSUE THREAD

**Issue by aksharbonu** [jessesquires/JSQMessagesViewController#1079]
It is being changed in: 

- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath

**Comment by jessesquires** [comment]
Thanks @aksharbonu - :smile: please update your issue after reading the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md)
