### ISSUE TITLE
Provide custom toolbar view.

### ISSUE THREAD

**Issue by ypopovych** [jessesquires/JSQMessagesViewController#1081]
I need another type of toolbar (for speech recognition, so no textView in it).

I subclassed `JSQMessagesToolbarContentView` and `JSQMessagesInputToolbar`. In `JSQMessagesInputToolbar` I implemented `loadToolbarContentView` and returns my initialized toolbar. But `JSQMessagesViewController` try to create `JSQMessagesKeyboardController` for it, and crashes on `textView != nil` assertion. How I can disable creating of keyboard controller?

**Comment by eliburke** [comment]
@ypopovych can you please provide some more detail about how you replaced the stock input toolbar with your custom subclass? I can't figure out how to connect subclasses of those with JSQMessagesViewController, as the inputToolbar property, and its contentView are both read only. I've tried fiddling around with overriding the property and only achieved KVO-related crashes for my pains.
