### ISSUE TITLE
How to include the Top / Bottom Label inside chat bubble. 

### ISSUE THREAD

**Issue by TheEngineerz** [jessesquires/JSQMessagesViewController#1083]
Currently if we see the cells then Chat bubble only appears on the message content either it is text or media item.My question is what is the recommended way if i want to include the Top/Bottom label inside the chat bubble. for both text and media items.

**Comment by jessesquires** [comment]
hey @TheEngineerz - the library doesn't support this out-of-the-box. this would require that you make custom cells. search for this in previous issues for details.

**Comment by TheEngineerz** [comment]
Thanks @jessesquires
