### ISSUE TITLE
inputToolbar is not visible

### ISSUE THREAD

**Issue by akinnuwa** [jessesquires/JSQMessagesViewController#1084]
The input bar is never visible.I have been playing with the DemoMessagesViewController class and quite frankly still trying to wrap my head around it. I did some basic commenting-

out but surely not enough to make the input bar invisible. What am I missing?

#import "DemoMessagesViewController.h"
@implementation DemoMessagesViewController

#pragma mark - View lifecycle

/**
 *  Override point for customization.
 *
 *  Customize your view.
 *  Look at the properties on `JSQMessagesViewController` and `JSQMessagesCollectionView` to see what is possible.
 *
 *  Customize your layout.
 *  Look at the properties on `JSQMessagesCollectionViewFlowLayout` to see what is possible.
 */
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    self.title = @"JSQMessages";
    
    /**
     *  You MUST set your senderId and display name
     */
    self.senderId = kJSQDemoAvatarIdSquires;
    self.senderDisplayName = kJSQDemoAvatarDisplayNameSquires;
    
    
    /**
     *  Load up our fake data for the demo
     */
    self.demoData = [[DemoModelData alloc] init];
    
    
    /**
     *  You can set custom avatar sizes
     */
    self.collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeZero;
    self.collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero;

    
    self.showLoadEarlierMessagesHeader = YES;
    
    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithImage:[UIImage jsq_defaultTypingIndicatorImage]
                                    style:UIBarButtonItemStylePlain
        target:self action:@selector(receiveMessagePressed:)];

    /**
     *  Register custom menu actions for cells.
     */
    [JSQMessagesCollectionViewCell registerMenuAction:@selector(customAction:)];
    [UIMenuController sharedMenuController].menuItems = @[ [[UIMenuItem alloc] initWithTitle:@"Custom Action" action:@selector(customAction:)] ];

    //self.inputToolbar.contentView.leftBarButtonItem = custom button or nil to remove
    //self.inputToolbar.contentView.rightBarButtonItem = custom button or nil to remove
   // self.inputToolbar.maximumHeight = 150;
    
}
......
<img width="378" alt="screen shot 2015-07-12 at 7 28 12 pm" src="https://cloud.githubusercontent.com/assets/8429120/8639340/c0a5a142-28ce-11e5-9e98-6427abf11023.png">

**Comment by jessesquires** [comment]
see the following issues about JSQMessages + UITabbar:

https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+tabbar+is%3Aclosed
