### ISSUE TITLE
Space between keyboard and InputToolbar

### ISSUE THREAD

**Issue by sahabe1** [jessesquires/JSQMessagesViewController#1086]
Hi 

I want to remove space between inputtoolbar and keyboard. how to fix it.
please see attachment
![img_0010](https://cloud.githubusercontent.com/assets/1065015/8670147/cf03eeaa-2a37-11e5-8033-2eff1c3cbee9.PNG)

**Comment by LeoNatan** [comment]
Should be fixed with #1063

**Comment by eliburke** [comment]
The fix (in #1529) moved to release 8.

**Comment by jessesquires** [comment]
going to try to take a look at this one, too 😁

**Comment by jessesquires** [comment]
Fixed by closing #1063 for v7.3.0.

Will be properly fixed in v8.0.0 by #1529
