### ISSUE TITLE
Having some annoying issues trying to customise message cells.

### ISSUE THREAD

**Issue by freak4pc** [jessesquires/JSQMessagesViewController#1087]
So far , with some hacky-twiddling I've managed to create the following additions to my text bubbles (status icon and time label) 

![84bda493-0d96-4c0b-8a97-fb7cef3b8734](https://cloud.githubusercontent.com/assets/605076/8673949/5ff54d5e-2a43-11e5-9368-db290e366df2.jpg)

The problem starts when I'm trying to do the same for Media Cells. 
This looks something like this. As you see the display is inconsistent and I can't figure out what I'm doing wrong. Also, the "Icon" never shows up. As if there's sort of conflict between the subviews. 

![c584fb75-c75c-4103-bedc-84339933776a](https://cloud.githubusercontent.com/assets/605076/8674015/c54f3b56-2a43-11e5-8fe7-5fecdc6677bf.jpg)

The way I'm building the cells is by adding subviews with tags and then reusing them when possible.

This looks something like this : 
```swift
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
    let cell                = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell

    let msg                 = self.messages[indexPath.row]
    let bubble              = cell.messageBubbleContainerView
    let bubbleSize          = self.collectionView.collectionViewLayout.messageBubbleSizeForItemAtIndexPath(indexPath)
    let insets              = self.collectionView.collectionViewLayout.messageBubbleTextViewTextContainerInsets
    
    cell.textView?.textColor = (msg.senderId == self.senderId) ? UIColor.whiteColor() : UIColor.blackColor()
    
    if bubble.viewWithTag(21) == nil {
        let img                 = UIImageView(image: UIImage(named: msg.read ? "IcnMessageRead" : "IcnMessageSent"))
        img.tag                 = 21
        bubble.addSubview(img)
    }
    
    if bubble.viewWithTag(20) == nil {
        let lbl                 = UILabel()
        lbl.textColor           = cell.textView?.textColor
        lbl.font                = UIFont.customFont(.HelveticaNeueLight, size: 9)
        lbl.tag                 = 20
        bubble.addSubview(lbl)
    }
    
    if bubble.viewWithTag(23) == nil {
        let clock               = DDAnimatedClock(frame: CGRectMake(0, 0, 14, 14))
        clock.tag               = 23
        bubble.addSubview(clock)
    }
    
    let img                 = bubble.viewWithTag(21) as! UIImageView
    let lbl                 = bubble.viewWithTag(20) as! UILabel
    let clock               = bubble.viewWithTag(23) as! DDAnimatedClock
       /// etc etc ...
```

Then I'm just positioning by the media type. I've tried changing the frame/bounds/origin etc on the isMediaMessage clause but the UI is still not consistent. 

```swift
if msg.isMediaMessage {
    img.origin              = CGPointMake(bubbleSize.width - insets.right - img.width, bubbleSize.height - 7)
    lbl.origin              = CGPointMake(  (img.alpha == 0) ? bubbleSize.width - insets.right - lbl.width + 3 : img.x - lbl.width - 3,
        (img.alpha == 0) ? img.y - 1 : img.y)
    
    lbl.textColor           = UIColor.whiteColor()
}else{
    img.origin              = CGPointMake(bubbleSize.width - insets.right - img.width, bubbleSize.height - 7)
    lbl.origin              = CGPointMake(  (img.alpha == 0) ? bubbleSize.width - insets.right - lbl.width + 3 : img.x - lbl.width - 3,
        (img.alpha == 0) ? img.y - 1 : img.y)
    
}
```

Is there anything I'm missing?
I've thought of just extending JSQMessagesCollectionViewCell but that would mess a lot of things up since I would have to somehow access the flowLayout from the parent ... Plus, It would probably not solve the issue.

If anyone has some tips of how to make the media messages work I'd love to hear.

Thanks! 
Shai

**Comment by gcarlo89** [comment]
@freak4pc mmmmm I also had to add things on my media views. What I did was subclass `JSQMediaItem` conformed to `JSQMessageMediaData` protocol (I followed the example of `JSQPhotoMediaItem`). 
In the method `(UIView *)mediaView` I added the subviews to the final mediaView that is then cached and returned (it helps that you can define the size returned in `mediaViewDisplaySize`). 
These subviews could have a tag if you like, or you can expose them as properties in your '.h'. 
Does this help? O.o

**Comment by jessesquires** [comment]
thanks for the great answer @gcarlo89 ! :+1:

**Comment by jessesquires** [comment]
Just updated audited a bunch of old issues. Now searching for "[Custom Cells]" will display previous issues about this. They may help, too.

https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+%5BCustom+cells%5D+is%3Aclosed

**Comment by ikyh** [comment]
@freak4pc Hey. I want to implement exactly the way you have done. Can you please just brief about how you added time at the bottom of the message bubble. Most of the answers I saw are in ObjC which I am don't know. In swift I tried adding label which visually seems on `TextView` but actually is on `messageContainerView`. In the output it shows all blank cells with labelText. I am struggling a lot with it. Please tell me what am I missing. Also when we are using `cellForItem`, then what do we have to do in `JSQMessageBubbleImageDataSource`. Please help

**Comment by freak4pc** [comment]
@ikyh This issue is almost 3 years old ... Sorry but I don't remember :) 
Yikes, 3-years-ago Shai's code was kinda ugly 😛 

Also, I think this project is not as maintained as it used to be. Did you look into MessageKit ?
