### ISSUE TITLE
Prevent clipping for placeholder text in input toolbar when using custom font

### ISSUE THREAD

**Issue by joenewbry** [jessesquires/JSQMessagesViewController#1088]
Hey,

I'm trying to figure out how to prevent clipping for the placeholder text in the input toolbar when setting a custom font. Looking at the [docs](http://cocoadocs.org/docsets/JSQMessagesViewController/7.1.0/Classes/JSQMessagesInputToolbar.html#//api/name/preferredDefaultHeight) I thought setting the preferred default height in the `viewDidLoad` method of my `JSQMessagesViewController` subclass would change the height of the text view.

``` objective-c
self.inputToolbar.preferredDefaultHeight = 100.0f;
```

It looks like the `inputToolbar` is initialized and `preferredDefaultHeight` is used in `viewDidLoad` method of the `JSQMessagesViewController` class. So setting the preferred default height in the view controller subclass is too late. 

I can fork the library but that doesn't feel quite right :)

Looking forward to hearing from you,
Joe

**Comment by jessesquires** [comment]
Thanks @joenewbry ! You're right. 

`JSQMessagesViewController` should probably provide a setter for `toolbarHeightConstraint.constant`

**Comment by jessesquires** [comment]
Pull-requests welcome :smile:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
