### ISSUE TITLE
Subclassing JSQMessagesViewController's subclass

### ISSUE THREAD

**Issue by minsoe** [jessesquires/JSQMessagesViewController#1091]
I am having this strange issue. I have this MessageViewController which is a subclass of JSQMessagesViewController. Then, I create another class GroupMessageViewController which is a subclass of MessageViewController. Once I created GroupMessageViewController, I am not able to compile the project anymore by showing "JSQMessagesViewController.h not found". Anyone faced this issue before and any idea how to solve the issue.

**Comment by jessesquires** [comment]
Thanks @minsoe ! :smile: 

This doesn't sound related to the library, but seems specific to your project. Going to close. If you think that isn't right, let me know! :smile:
