### ISSUE TITLE
Keyboard gets pushed down with in-call status bar 

### ISSUE THREAD

**Issue by brianhu** [jessesquires/JSQMessagesViewController#1092]
The problem:
Keyboard gets pushed down sometimes, so the keys in the lowest row are hidden partially.
![img_0210](https://cloud.githubusercontent.com/assets/738117/8725901/7a875460-2c09-11e5-81c0-8b5ee1f8bac1.PNG)

how to reproduce:
1. Make the in-call status bar (or hot spot status bar) show
2. scroll up ( I mean scrolling up physically here, so the y value of the content offset will increase)

I can reproduce this issue on iPhone 6 and 6 plus every time.

What's interesting is that this only happens on physical devices. The same code works well on simulators.
I found there is a similar issue #219 .
I'd like to fix this and send a PR, but I have no idea why it happens.
Can someone give me a clue? 

=== Edit ===

I have been trying to fix this, and I found some more details about this issue.
1. This problem occurs when the in-call status bar shows(so the height of the status bar is 40 rather than 20) **_before**_ the app starts running. If the in-call status bar shows **_after**_ the app starts running, then every thing is good. (It's not about simulators or devices. I misunderstood it when I posted the original issue.)
2. After studying the source code, I guessed the problem was `JSQMessagesKeyboardController.m` didn't take the in-call status bar into account when calculating the frame of the keyboard in `- (void)jsq_handlePanGestureRecognizer:(UIPanGestureRecognizer *)pan`
   https://github.com/jessesquires/JSQMessagesViewController/blob/760633977008530c90bcc43f650f0f7d9eb3d2fc/JSQMessagesViewController/Controllers/JSQMessagesKeyboardController.m#L313.
3. To fix the problem, I added a `BOOL` property `statusBarWasInCall` to `JSQMessagesKeyboardController`, so I can calculate the y position of the keyboard in `jsq_handlePanGestureRecognizer` accordingly.

``` Objective-C
- (instancetype)initWithTextView:(UITextView *)textView
                     contextView:(UIView *)contextView
            panGestureRecognizer:(UIPanGestureRecognizer *)panGestureRecognizer
                        delegate:(id<JSQMessagesKeyboardControllerDelegate>)delegate

{
    NSParameterAssert(textView != nil);
    NSParameterAssert(contextView != nil);
    NSParameterAssert(panGestureRecognizer != nil);

    self = [super init];
    if (self) {
        _textView = textView;
        _contextView = contextView;
        _panGestureRecognizer = panGestureRecognizer;
        _delegate = delegate;
        _jsq_isObserving = NO;
    }

    // MY TRY: detect whether the status bar was in-call before this controller was initialized
    _statusBarWasInCall= [UIApplication sharedApplication].statusBarFrame.size.height == 40;
    return self;
}

- (void)jsq_handlePanGestureRecognizer:(UIPanGestureRecognizer *)pan
{
    CGPoint touch = [pan locationInView:self.contextView];

     // MY TRY: calculate height offset according to the status bar style
    CGFloat statusBarHeightOffset;    
    if (_statusBarWasInCall) {
        statusBarHeightOffset = 20;
    } else {
        statusBarHeightOffset = 0;
    }

    //  system keyboard is added to a new UIWindow, need to operate in window coordinates
    //  also, keyboard always slides from bottom of screen, not the bottom of a view
    CGFloat contextViewWindowHeight = CGRectGetHeight(self.contextView.window.frame);

    if ([UIDevice jsq_isCurrentDeviceBeforeiOS8]) {
        //  handle iOS 7 bug when rotating to landscape
        if (UIInterfaceOrientationIsLandscape([UIApplication sharedApplication].statusBarOrientation)) {
            contextViewWindowHeight = CGRectGetWidth(self.contextView.window.frame);
        }
    }

    CGFloat keyboardViewHeight = CGRectGetHeight(self.keyboardView.frame);

    CGFloat dragThresholdY = (contextViewWindowHeight - keyboardViewHeight - self.keyboardTriggerPoint.y);

    CGRect newKeyboardViewFrame = self.keyboardView.frame;

    BOOL userIsDraggingNearThresholdForDismissing = (touch.y > dragThresholdY);

    self.keyboardView.userInteractionEnabled = !userIsDraggingNearThresholdForDismissing;
    switch (pan.state) {
        case UIGestureRecognizerStateChanged:
        {
            newKeyboardViewFrame.origin.y = touch.y + self.keyboardTriggerPoint.y;
            //  bound frame between bottom of view and height of keyboard
            newKeyboardViewFrame.origin.y = MIN(newKeyboardViewFrame.origin.y, contextViewWindowHeight);
            newKeyboardViewFrame.origin.y = MAX(newKeyboardViewFrame.origin.y, contextViewWindowHeight - keyboardViewHeight);

            // MY TRY: minus the offset from the y position
            newKeyboardViewFrame.origin.y -= statusBarHeightOffset;

            if (CGRectGetMinY(newKeyboardViewFrame) == CGRectGetMinY(self.keyboardView.frame)) {
                return;
            }

            [UIView animateWithDuration:0.0
                                  delay:0.0
                                options:UIViewAnimationOptionBeginFromCurrentState | UIViewAnimationOptionTransitionNone
                             animations:^{
                                 self.keyboardView.frame = newKeyboardViewFrame;
                             }
                             completion:nil];
        }
            break;

        case UIGestureRecognizerStateEnded:
        case UIGestureRecognizerStateCancelled:
        case UIGestureRecognizerStateFailed:
        {
            BOOL keyboardViewIsHidden = (CGRectGetMinY(self.keyboardView.frame) >= contextViewWindowHeight);
            if (keyboardViewIsHidden) {
                [self jsq_resetKeyboardAndTextView];
                return;
            }

            CGPoint velocity = [pan velocityInView:self.contextView];
            BOOL userIsScrollingDown = (velocity.y > 0.0f);
            BOOL shouldHide = (userIsScrollingDown && userIsDraggingNearThresholdForDismissing);

            newKeyboardViewFrame.origin.y = shouldHide ? contextViewWindowHeight : (contextViewWindowHeight - keyboardViewHeight);

            // MY TRY: minus the offset from the y position
            newKeyboardViewFrame.origin.y -= statusBarHeightOffset;

            [UIView animateWithDuration:0.25
                                  delay:0.0
                                options:UIViewAnimationOptionBeginFromCurrentState | UIViewAnimationCurveEaseOut
                             animations:^{
                                 self.keyboardView.frame = newKeyboardViewFrame;
                             }
                             completion:^(BOOL finished) {
                                 self.keyboardView.userInteractionEnabled = !shouldHide;

                                 if (shouldHide) {
                                     [self jsq_resetKeyboardAndTextView];
                                 }
                             }];
        }
            break;

        default:
            break;
    }
}
```

With my modification, the keyboard position is correct when the in-call status bar appears **_before**_ the app starts running. Nonetheless, the position is incorrect when the in-call status bar appears **_after**_ the app starts running. (The situation is opposite to the one I mentioned in point 1)

Based on my study above, I guess the root of the problem is in somewhere else, but I am not sure.
@jessesquires, do you have any ideas? Thanks!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
