### ISSUE TITLE
incorrect bubble height in iphone 6 plus

### ISSUE THREAD

**Issue by hermanccw** [jessesquires/JSQMessagesViewController#1093]
Step to reproduce

1.  download latest version and expanded zip
2.  pod install
3.  input the following text "I guess not... I just don't know if all of it is correct in bm. Some stuff is wrong" and get the following result:

![screen shot 2015-07-16 at 2 27 46 pm](https://cloud.githubusercontent.com/assets/1000084/8731674/fada335a-2bc6-11e5-9dd2-c41586676bd9.png)

**Comment by hermanccw** [comment]
Found the problem. [Magic](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.m#L474) hurts sometime 

Removing the +2 fixed the width for all screen width, iphone 5/6/6plus.

Was there a reason to add the +2 before?  I tried removing the +2 on the verticalInset but that broke everything.

**Comment by jessesquires** [comment]
Hey @hermanccw - lots of legacy reasons for this.

1. Was this for iOS 9, or not?
2. Are you using a custom font? (It looks like you are)

In any case, there's now an easier way to deal with this. See https://github.com/jessesquires/JSQMessagesViewController/issues/347#issuecomment-130533179
