### ISSUE TITLE
popping JSQMessagesViewController from uinavcontroller mess up other frames

### ISSUE THREAD

**Issue by mp3il** [jessesquires/JSQMessagesViewController#1094]
Hi,

I'm having some super-weird behavior, when popping from JSQMessagesViewController:
`[self.navigationController popViewControllerAnimated:NO];`

The previous viewcontroller in the stack is being messed up and elements location (frame) being changed.

any idea what can cause that?

[EDIT]
I guess it must be related to auto layout and constraints, but if I'm not using any in my app, how should I resolve it? 

before pushing jsqmessegeviewcontroller:
![after](https://cloud.githubusercontent.com/assets/314019/8747706/fd6b1788-2c9d-11e5-8645-496b3af31045.jpg)

before

![before](https://cloud.githubusercontent.com/assets/314019/8747707/fd6c3d5c-2c9d-11e5-968d-787043ab3e19.jpg)

**Comment by gcarlo89** [comment]
This isn't related to JSQMessagesViewController at all. To confirm this, push any other viewController on top of that one, and test if popping it results in the same effect.

ps. if you don't use constraints, at least use autoresizing
cheers!

**Comment by mp3il** [comment]
@gcarlo89 thanks, but actually i did push some plain view controller and when popping it everything was at the right place :)

but if found some setTranslatesAutoresizingMaskIntoConstraints calls to the labels that was suddenly showed up in different places.

and yeah, i definitely should start using constraints!

thanks mate.
