### ISSUE TITLE
Crash presenting JSQLocationMediaItem

### ISSUE THREAD

**Issue by alezoffoli** [jessesquires/JSQMessagesViewController#1095]
Sometimes I have a crash when presenting a JSQLocationMediaItem. It is not consistent and I can't seem to always reproduce it, but it happens quite frequently.

The crash is at JSQLocationMediaItem.m, specifically inside the 

``` objectivec
createMapViewSnapshotForLocation:(CLLocation *)location
                        coordinateRegion:(MKCoordinateRegion)region
                   withCompletionHandler:(JSQLocationMediaItemCompletionBlock)completion
```

method, at:

``` objectivec
 MKAnnotationView *pin = [[MKPinAnnotationView alloc] initWithAnnotation:nil reuseIdentifier:nil]
```

Stack trace:

UIKit 0x0000000186a4e08c -[_UIViewAdditiveAnimationAction runActionForKey:object:arguments:] + 636
QuartzCore 0x00000001860b7e94 CA::Layer::set_bounds() + 404
QuartzCore 0x00000001860b7c74 -[CALayer setBounds:] + 100
MapKit 0x0000000183e959b8 -[MKLayer setBounds:] + 52
UIKit 0x00000001867d5418 -[UIView(Geometry) setBounds:] + 324
MapKit 0x0000000183e957a0 -[MKPinAnnotationView initWithAnnotation:reuseIdentifier:] + 156
JSQMessagesViewController 0x00000001007d3c2c 0x00000001007cc000 + 31788
libdispatch.dylib 0x0000000193ce9994 _dispatch_call_block_and_release + 20
libdispatch.dylib 0x0000000193ce9954 _dispatch_client_callout + 12
libdispatch.dylib 0x0000000193cf6780 _dispatch_root_queue_drain + 1844
libdispatch.dylib 0x0000000193cf7c4c _dispatch_worker_thread3 + 104
libsystem_pthread.dylib 0x0000000193ec922c _pthread_wqthread + 812
libsystem_pthread.dylib 0x0000000193ec8ef0 start_wqthread + 0

 I just wanted to see if it happened with anyone else, or if anyone can enlighten me :/

**Comment by rezasham** [comment]
Yes, I´m also seeing it. Can´t reproduce it though.

**Comment by JRam13** [comment]
Same here. It's extremely hard to reproduce too, it happens sporadically.

**Comment by jessesquires** [comment]
@alezoffoli - please update the issue after reviewing the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) :smile:

**Comment by chapayGhub** [comment]
I changed in code line
 [snapShotter startWithQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0) to
 [snapShotter startWithQueue:dispatch_get_main_queue()
And it seems fixed.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
