### ISSUE TITLE
How implement animations for messages

### ISSUE THREAD

**Issue by ypopovych** [jessesquires/JSQMessagesViewController#1097]
I want animated messages appearing. Like appears from right or left. How I can do this?

**Comment by jessesquires** [comment]
hey @ypopovych - you'll have to provide your custom FlowLayout subclass.

**Comment by AndrewSB** [comment]
Are there any examples of message insertion animations?

I've tried subclassing the `JSQMessagesCollectionViewFlowLayout` and setting that as my collectionView's layout, implementing `initialLayoutAttributesForAppearingItemAtIndexPath` to no effect.

**Comment by ypopovych** [comment]
Seems as contoller use another way of adding items. Because no initialLayoutAttributes* methods called. And even prepareForCollectionViewUpdates not called.

**Comment by jessesquires** [comment]
Hey guys — this is really more about `UICollectionViewFlowLayout` than `JSQMessages`, I would try asking for help on StackOverflow.

**Comment by ypopovych** [comment]
Found problem with animation. Controller updates table by `[self.collectionView reloadData];`
But if you reload data like this, no animation callbacks will be called in Flow Layout.
If update must be animated the simpliest way is 
```objc
[self.collectionView performBatchUpdates:^{
    [self.collectionView reloadSections:[NSIndexSet indexSetWithIndex:0]];
} completion:nil];
```

**Comment by jessesquires** [comment]
Thanks for sharing @ypopovych ! :smile:

**Comment by Insider77** [comment]
add this lines to JSQMessagesCollectionViewFlowLayout.m
```
- (UICollectionViewLayoutAttributes*)initialLayoutAttributesForAppearingItemAtIndexPath:(NSIndexPath *)itemIndexPath {
    
    UICollectionViewLayoutAttributes *attr = (JSQMessagesCollectionViewLayoutAttributes *)[super layoutAttributesForItemAtIndexPath:itemIndexPath];
    attr.alpha = 0.0;
    attr.transform = CGAffineTransformMakeScale(0, 0);
    
    return attr;
}
```

and this lines to your view controller instead of [self finishSendingMessageAnimated:YES];

```
    [self.collectionView performBatchUpdates:^{
        
         NSMutableArray *arrayWithIndexPaths = [NSMutableArray array];
        [arrayWithIndexPaths addObject:[NSIndexPath indexPathForRow:self.messages.count inSection:0]];
        [self.messages addObject:message];
        [self.collectionView insertItemsAtIndexPaths:arrayWithIndexPaths];
        
    } completion:nil];
    
    UITextView *textView = self.inputToolbar.contentView.textView;
    textView.text = nil;
    [textView.undoManager removeAllActions];
    
    [self.inputToolbar toggleSendButtonEnabled];
    
    [[NSNotificationCenter defaultCenter] postNotificationName:UITextViewTextDidChangeNotification object:textView];
    
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
    
    if (self.automaticallyScrollsToMostRecentMessage) {
        [self scrollToBottomAnimated:YES];
    }
```

P.S. of course you can use any another transforms in initialLayoutAttributesForAppearingItemAtIndexPath
