### ISSUE TITLE
Loading early messages

### ISSUE THREAD

**Issue by bizibizi** [jessesquires/JSQMessagesViewController#1098]
How can add feature of 'Loading early messages' like in iMessages ?

**Comment by jessesquires** [comment]
Hey @bizibizi - the library has the UI for this, but the implementation is up to you. :smile: 

There's some discussion about this in previous issues, you should search there. If that doesn't help, maybe look on StackOverflow for questions about paging data sources.

**Comment by gcarlo89** [comment]
What I do is I have two arrays, one with the all the messages, and the other with all the visible messages. To show the latest 20 messages, I do the following in `viewDidLoad`:
```objective-c
    int numberofcurrentmessages = (int)self.messagesArray.count;
    
  //Check if I have more than 20 messages for this conversation
    if (numberofcurrentmessages>20) {
       //messagesWithoutRead is an int that represents the  number of messages I as a user haven't seen yet
        int initposition =(messagesWithoutRead>20)? (numberofcurrentmessages - messagesWithoutRead):(numberofcurrentmessages-20);
        int endposition = (numberofcurrentmessages);
        NSRange range = NSMakeRange(initposition, endposition-initposition);
       //Get only the last 20 messages
        self.visibleMessagesArray = [[self.messagesArray subarrayWithRange:range] mutableCopy];
    }else{
       //Load all the messages
        self.visibleMessagesArray = [[NSMutableArray alloc]initWithArray:self.messagesArray];
    }
```
`self.visibleMessagesArray` is my data for the collectionView
