### ISSUE TITLE
Automatically releasing cell

### ISSUE THREAD

**Issue by sahabe1** [jessesquires/JSQMessagesViewController#1099]
Hi jessesquires,

Its getting crashed when opeaning mail composser and back to the view controller

please check the crash log

**\* -[JSQMessagesCollectionViewCellOutgoing release]: message sent to deallocated instance 0x7f88fe51d250

**Comment by jessesquires** [comment]
Thanks @sahabe1!

Please provide more info:
1. Library version 
2. iOS version
3. Devices / simulators
4. Full crash log
5. Steps to reproduce
6. List any possible related existing issues

**Comment by sahabe1** [comment]
Please find the steps:
	1.	Library version :5.3.2
	2.	iOS version :iOS 7+
	3.	Devices / simulators: All
	4.	Steps to reproduce:
1- ViewController 1 Which have TableView
2- ViewController 2 (Chat Class or DemoMessageViewController)
3- Open the Mail Composer on Message Click then Send mail or discard mail;
4-Back from Chat Class (DemoMessageViewController)  to Point 1 then it Will Crash.

**Comment by jessesquires** [comment]
Thanks @sahabe1 - can you link to a demo project that reproduces the issue?

Also, I **highly recommend** updating to the latest version of the library! — it still supports iOS 7.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
