### ISSUE TITLE
Customize Chat Cell for Likes or Favorites

### ISSUE THREAD

**Issue by udaysinghcode** [jessesquires/JSQMessagesViewController#1100]
Hi - I was wondering how you could customize the UI of the chat cell to allow a button on the same row of each chat to have a star so you can favorite chat bubbles within a group chat?

**Comment by gcarlo89** [comment]
Subclass the incoming and outgoing cells with xibs and all, add your button with all the constraints in the xib, and reference it with an outlet in your subclass. Now your model object which conforms to `JSQMessageData` must have some property so in the `cellForItemAtIndexPath` you can decide whether to show that button, or change the state of the button. Something similar worked for me.

Cheers

**Comment by dealaus** [comment]
@gcarlo89 I attempted this. Do other things need to be changed? I could not cast the cellAtIndexPath to be my custom incoming cell.

**Comment by jessesquires** [comment]
Thanks @gcarlo89 

Closing this issue, but feel free to continue the discussion :smile:

**Comment by dealaus** [comment]
@jessesquires Hey Jesse, I've been having a rough time to make this work out, I'm hoping you could chime in since you are far more experienced. I am putting buttons on incoming cells, so I created an xib and subclassed the incoming cell and added the UIButton property. However, the message bubble is not the correct size. Is there a way to change the bubble size outside of the flow layout class? In that class there is no visible property that would let a cell know whether it should be larger or not.

**Comment by gcarlo89** [comment]
@dealaus  sorry for the late post. Check if in your `viewDidLoad` you are declaring your custom cells to the collectionview:
```objective-c
/******************** Setting up my Cells **************************/
    self.outgoingCellIdentifier = [MyCustomCollectionViewCellOutgoing cellReuseIdentifier];
    self.outgoingMediaCellIdentifier = [MyCustomCollectionViewCellOutgoing mediaCellReuseIdentifier];
    
    [self.collectionView registerNib:[MyCustomCollectionViewCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingCellIdentifier];
    [self.collectionView registerNib:[MyCustomCollectionViewCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingMediaCellIdentifier];
    
    self.incomingCellIdentifier = [MyCustomCollectionViewCellIncoming cellReuseIdentifier];
    self.incomingMediaCellIdentifier = [MyCustomCollectionViewCellIncoming mediaCellReuseIdentifier];
    
    [self.collectionView registerNib:[MyCustomCollectionViewCellIncoming nib] forCellWithReuseIdentifier:self.incomingCellIdentifier];
    [self.collectionView registerNib:[MyCustomCollectionViewCellIncoming nib] forCellWithReuseIdentifier:self.incomingMediaCellIdentifier];
```
And with this you can cast in `cellForItemAtIndexPath`

```objective-c
-(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath{
    /**
     *  Override point for customizing cells
     */
    JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];
   BLMessage *message = [self.visibleMessagesArray objectAtIndex:indexPath.item];

    MyCustomCollectionViewCellOutgoing *celloutgoing;
    MyCustomCollectionViewCellIncoming *cellincoming;

   //check if outgoing
    if ([message.senderId isEqualToString:self.senderId]) {
      celloutgoing = (MyCustomCollectionViewCellOutgoing *)cell;
      //do more setup for outgoing cells
    }else{
      cellincoming = (MyCustomCollectionViewCellIncoming *)cell;
      //do more setup for incoming cells
    }

   return cell;
}
```

**Comment by dealaus** [comment]
Thanks @gcarlo89! However, now I am crashing because it is saying it could not load the nib from bundle. I changed the custom .xib's current class to the custom class. Tips?

**Comment by gcarlo89** [comment]
oooooh, I remember I had a similar problem. First I was subclassing my custom cells from `JSQMessagesCollectionViewCell` but it turns out that in the innards of the library, there are if checks for the classes `JSQMessagesCollectionViewCellIncoming` and `JSQMessagesCollectionViewCellOutgoing`. 

So I ended up subclassing `JSQMessagesCollectionViewCellIncoming` and `JSQMessagesCollectionViewCellOutgoing` respectively for my custom cells

Tell me if that solved your problem @dealaus 
Cheers

**Comment by dealaus** [comment]
That's what I currently do, but just for incoming cells....hmmm

**Comment by dealaus** [comment]
I appreciate all the help @gcarlo89 ! I currently subclass my incoming cells from JSQMessagesCollectionViewCellIncoming...hmmm

**Comment by gcarlo89** [comment]
mmmmmmm... clean project and run again? O.o can you post the error stack?

**Comment by dealaus** [comment]
```
2015-07-23 00:15:42.107 DWSAva[27490:230684] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/adeal1/Library/Developer/CoreSimulator/Devices/CFA223AA-6DD5-4084-BD1B-2D90307D103E/data/Containers/Bundle/Application/9CEE37E0-2217-4246-8DFC-8C331FC98810/DWSAva.app> (loaded)' with name 'DWSAva.DWSCustomCollectionViewCellIncoming''
*** First throw call stack:
(
	0   CoreFoundation                      0x01690746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x00f4aa97 objc_exception_throw + 44
	2   CoreFoundation                      0x0169066d +[NSException raise:format:] + 141
	3   UIKit                               0x0258ae2f -[UINib instantiateWithOwner:options:] + 1003
	4   UIKit                               0x0295dc6f -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 578
	5   UIKit                               0x0295e2dc -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 160
	6   DWSAva                              0x00067f65 -[JSQMessagesViewController collectionView:cellForItemAtIndexPath:] + 1365
	7   DWSAva                              0x000938e6 _TFC6DWSAva25DWSMessagesViewController14collectionViewfS0_FTCSo16UICollectionView22cellForItemAtIndexPathCSo11NSIndexPath_CSo20UICollectionViewCell + 150
	8   DWSAva                              0x00094de9 _TToFC6DWSAva25DWSMessagesViewController14collectionViewfS0_FTCSo16UICollectionView22cellForItemAtIndexPathCSo11NSIndexPath_CSo20UICollectionViewCell + 89
	9   UIKit                               0x0294ed5a -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 258
	10  UIKit                               0x02950e96 -[UICollectionView _updateVisibleCellsNow:] + 4947
	11  UIKit                               0x029556e1 -[UICollectionView layoutSubviews] + 281
	12  UIKit                               0x022d457a -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 668
	13  libobjc.A.dylib                     0x00f60771 -[NSObject performSelector:withObject:] + 70
	14  QuartzCore                          0x02104e47 -[CALayer layoutSublayers] + 144
	15  QuartzCore                          0x020f8925 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 403
	16  QuartzCore                          0x020f877a _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 26
	17  QuartzCore                          0x02054c52 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 284
	18  QuartzCore                          0x020560e5 _ZN2CA11Transaction6commitEv + 487
	19  QuartzCore                          0x020567fc _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	20  CoreFoundation                      0x015b186e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
	21  CoreFoundation                      0x015b17b0 __CFRunLoopDoObservers + 400
	22  CoreFoundation                      0x015a71ea __CFRunLoopRun + 1226
	23  CoreFoundation                      0x015a6a5b CFRunLoopRunSpecific + 443
	24  CoreFoundation                      0x015a688b CFRunLoopRunInMode + 123
	25  GraphicsServices                    0x056e32c9 GSEventRunModal + 192
	26  GraphicsServices                    0x056e3106 GSEventRun + 104
	27  UIKit                               0x02241106 UIApplicationMain + 1526
	28  DWSAva                              0x0007191a main + 138
	29  libdyld.dylib                       0x0392cac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
I've attempted to work through it, but still unsure.

**Comment by gcarlo89** [comment]
mmmmm the only recommendation I can give you now @dealaus is to enable the breakpoint for all exceptions and check which line causes you trouble inside `[JSQMessagesViewController collectionView:cellForItemAtIndexPath:]` and follow the 'breadcrumb' from there. Sorry I can't be of more help, if you manage to solve it please post it so others can know about it.
Cheers

**Comment by dealaus** [comment]
Will do and currently am @gcarlo89! It breaks when dequeue is called, so that's where the breadcrumbs start at least. Thanks again!

**Comment by dealaus** [comment]
Just clarification, it fails at     ```JSQMessagesCollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:cellIdentifier forIndexPath:indexPath];``` in ```cellForItemAtIndexPath```

**Comment by gcarlo89** [comment]
Quick question, the xib for your custom cell, is it a new one? or did you change the name of the existing `JSQMessagesCollectionViewCellIncoming.xib` in the finder? if that is the case, (just to cover all our bases) can you remove the reference of the xib to the project, (clean the project just in case afterwards) and then re-add it to the project
Tell me if that made a difference

**Comment by dealaus** [comment]
I created a new xib, but copy/pasted the source of the ```JSQMessagesCollectionViewCellIncoming.xib``` and then customized it from there. I remove and re-added with no luck.

**Comment by hammad** [comment]
@dealaus  In your custom cell class write these two functions:

+ (UINib *)nib
{
    return [UINib nibWithNibName:NSStringFromClass([self class]) bundle:[NSBundle bundleForClass:[self class]]];
}

+ (NSString *)cellReuseIdentifier
{
    return NSStringFromClass([self class]);
}

This code expects that your xib file name is the same as the class name.

**Comment by DBL-Lee** [comment]
@dealaus How did you resolve this problem? I am having the same problem here.

**Comment by utkbansal** [comment]
@dealaus @DBL-Lee @jessesquires how did you solve this problem? I am facing the same problem.

**Comment by rkumawat** [comment]
Hello i have integrate whole above but i am getting crashing like this,
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: cell.textView.text != nil'.
Please help me......
