### ISSUE TITLE
When long press input textview UI wink.

### ISSUE THREAD

**Issue by chindanai** [jessesquires/JSQMessagesViewController#1106]
I build the original project to iPhone 6 iOS 8.3 (12F70)

Step reproduces:
1. go to chat page
2. hold on the input text view to show magnifier
3. drage magnifier slowly to area UICollectionView 
4. some UI will wink

Please see the video : (please seek to second : 0.52)
https://drive.google.com/a/thai-g.com/file/d/0B_A5FPAMZQzDZUZCaDRSWXBNUkk2VXp4c2xCeWN0dEI3WGZN/view?usp=sharing

**Comment by jessesquires** [comment]
Thanks @chindanai ! Please update the issue after [reading the guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) :smile:

**Comment by chindanai** [comment]
I've add the steps reproduce.

**Comment by chindanai** [comment]
![ezgif com-video-to-gif-2](https://cloud.githubusercontent.com/assets/5197004/8902317/ea7332ee-3479-11e5-9b84-3fe330e2e503.gif)

**Comment by Lisajoy512** [comment]
@chindanai 
@jessesquires   I found the same problem. I want to know if you guys had solve this issue?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
