### ISSUE TITLE
How to add time inside the bubble

### ISSUE THREAD

**Issue by sahabe1** [jessesquires/JSQMessagesViewController#1108]
Please see attachment
![untitled](https://cloud.githubusercontent.com/assets/1065015/8847865/7e172b54-3150-11e5-8f8c-86cb6abe8f7c.png)

**Comment by dealaus** [comment]
For a quick way to do this you can add a subview to the cell, and override the height calculations to allow the bubble to be tall enough to include the time.

**Comment by jessesquires** [comment]
Thanks @sahabe1!

Please see the previous issues on customizing cells :smile: 
https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+%5BCustom+Cells%5D+is%3Aclosed
