### ISSUE TITLE
UITapGestureRecognizer Help

### ISSUE THREAD

**Issue by dealaus** [jessesquires/JSQMessagesViewController#1109]
I have buttons within the bubble of my messages. However, the built in tap gesture recognizer seems to be taking priority over them so I can not actually press the buttons themselves.  I tried to disable the tap recognizer, but that just didn't let me press anywhere in the bubble. Is there anyway around this?

**Comment by jessesquires** [comment]
Hey @dealaus 

You'll want to look at Apple's docs on `UIGestureRecognizer` and it's delegate. What you need is there.

Also, be sure to review the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) next time you open an issue :smile:
