### ISSUE TITLE
Best way to add a UIView/"Panel" at the start of messages

### ISSUE THREAD

**Issue by aksharbonu** [jessesquires/JSQMessagesViewController#1110]
For example, a panel which has a question for the two users to answer in their subsequent messages? 

Is this done in 

- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath?

**Comment by jessesquires** [comment]
Hey @aksharbonu -- sounds like a collection view header would be more appropriate for this. See Apple's docs more more details.
