### ISSUE TITLE
Bottom bubble shifts on rotation, scroll position not maintained. Make bubbles fixed-width?

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#1112]
@jessesquires 

In the demo app, when you rotate the view the content offset does not land very close to the bubbles that  were visible before rotation.
<img width="187" alt="screen shot 2015-07-23 at 3 11 05 pm" src="https://cloud.githubusercontent.com/assets/4912283/8863400/2b20d60a-314d-11e5-8a07-2fa38fa1991e.png">
<img width="334" alt="screen shot 2015-07-23 at 3 10 54 pm" src="https://cloud.githubusercontent.com/assets/4912283/8863401/2b3ca5e2-314d-11e5-98d7-3f82ef2010b2.png">

Part of the problem is that cells have a different size in landscape vs portrait.
Chat bubbles widths are controlled by JSQMessagesCollectionViewFlowLayout.itemWidth.
I've tried subclassing JSQMessagesCollectionViewFlowLayout and returning a constant for itemWidth (regardless of landscape or portrait) but in landscape, all of my bubbles appear in the center of the view.

It turns out that itemWidth is used to control the overall width of the cell, as well as the maximum width of the bubble portion of the cell.

Would you be opposed to a PR which splits the ways in which itemWidth is used?
I'd like to introduce a new property: textBubbleWidth
For the base class (JSQMessagesCollectionViewFlowLayout), textBubbleWidth will just call itemWidth
````
- (CGFloat)textBubbleWidth {
	return [self itemWidth];
}
````
But in subclasses, we can return the narrower of the width or the height, and in this way, we can make the rows the same size/height regardless of landscape or portrait. This will go a long way toward getting the computation of contentOffset correct.

Ray

:muscle: :sunglasses: :facepunch:

**Comment by jessesquires** [comment]
@walsh2000 — aw thanks :muscle::heart::facepunch:

This is interesting. Looking now, iMessage does not resize bubbles at all, width is fixed. This would probably be the preferable behavior. What do you think?

In the current architecture, it might be difficult to implement. Not sure. Any changes will also affect the use/purpose of `messageBubbleLeftRightMargin`.

Related issues: #989

**Comment by walsh2000** [comment]
@jessesquires 

Fixed width is actually a trivial change.

1. We break apart itemWidth & textBubbleWidth (which is what #1113 does)
2. In textBubbleWidth do something like this:

````
- (CGFloat)textBubbleWidth {
	if (preferredItemWidth == 0) {
		NSInteger sectionInset = self.sectionInset.left + self.sectionInset.right + 2;
		CGFloat width = CGRectGetWidth([(UICollectionView *)[self collectionView] bounds]) - sectionInset;
		CGFloat height = CGRectGetHeight([(UICollectionView *)[self collectionView] bounds]) - sectionInset;
		CGFloat minValue = (width<height)?width:height;
		preferredItemWidth = minValue;
	}
	return preferredItemWidth;
}
````

That's all that is required to get fixed-width bubbles.
That is exactly why I'd like PR #1113 merged.

If you'd like, I will be happy to cook up a PR which adds a property to JSQMessagesCollectionViewFlowLayout for turning on/off fixed-width bubbles.

Ray

**Comment by jessesquires** [comment]
>If you'd like, I will be happy to cook up a PR which adds a property to JSQMessagesCollectionViewFlowLayout for turning on/off fixed-width bubbles.

:+1:  Let's put this all in #1113 

Does fixed-width bubbles fix #989?

**Comment by walsh2000** [comment]
#989 would be helped by fixed width bubbles.
The __top__ will stay the same, but in chat, we really only care about the bottom.

I have come up with a solution but it is a little dirty.

The FlowLayout needs to override:
````
- (CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)proposedContentOffset
````

And then do some math to change the proposedContentOffset by the amount the view's height is changing.

It's dirty because you need to know the height (among other things) at willRotateToInterfaceOrientation-time.

I found that i couldn't do it 100% inside of targetContentOffsetForProposedContentOffset because the view's height changed by 20 pts after the rotation. So, I'm re-adjusting the contentOffset a second time after didRotateFromInterfaceOrientation in my JSQMessagesViewController subclass.
- I couldn't track down the mystery 20 pts. I thought it might be the NavBar height change, or the NavBar+StatusBar but I gave up once I found my workable/acceptable solution.

Let's tackle fixed height/width bubbles with #1113 and discuss the bottom bubble & rotation as a separate task.

**Comment by walsh2000** [comment]
I updated #1113 with a new property to control Rotation Dependent/Independent bubble widths.

I also moved that "magix" value into a getter, because I am using it :frowning: 
I probably could have gotten away without using because it is just a maximum value, but I wanted messageBubbleSizeForItemAtIndexPath & textBubbleWidth to have the same max value.

**Comment by walsh2000** [comment]
@jessesquires 

Not to rush you. Just putting this back on your radar after the weekend...
What do you think about PR #1113?

It's safe to existing apps. Developers will have to opt-in to this new behavior.
