### ISSUE TITLE
override different media item sizes 

### ISSUE THREAD

**Issue by gs-ronak** [jessesquires/JSQMessagesViewController#1115]
How to overrride mediaViewDisplaySize for a custom media item in JSQMessagesViewController?

I want to customize the size of a custom media item in JSQMessagesViewController. I am adding a label to a UIView and trying to set the size by setting the frame size of my container view.

UIView* containerView = [[UIView alloc] initWithFrame: CGRectMake(0, 0, 100, 100) ]
containerView.frame = CGRectMake(0.0f, 0.0f, 315.0f, 100.0f);
UILabel *label =  [[UILabel alloc] initWithFrame: CGRectMake(0, 0, 50, 50)];
label.text = @"vendor name";
[containerView addSubview:label];
I am able to change the size for all media items by changing the mediaViewDisplaySize in JSQMediaItem.m. However that also affects my other subclasses like images and locations.

How do I selectively set the size?

Thanks

**Comment by niranjan92** [comment]
http://stackoverflow.com/questions/31637053/how-to-overrride-mediaviewdisplaysize-for-a-custom-media-item-in-jsqmessagesview
