### ISSUE TITLE
Not able to retrive image from the message array

### ISSUE THREAD

**Issue by icaroNZ** [jessesquires/JSQMessagesViewController#1118]
First I want to say thanks for the amazing lib in few hours I was able to make a very nice chat app that looks pretty good, the only problem I found was when I try to load a photo that was in the messages array "var messages = [JSQMessage]()" where I keep all the messages sent/received, the idea been the user can tap in a photo at anytime in the conversation and the photo will open.

As you can see there is a field image there there is probably private is it intentional? If so Is there a way to retrive the photo from JSQMessage or it would be an enhancement?

Best regards,

[32]	JSQMessage	0x78707400	0x78707400
NSObject	NSObject		
_isMediaMessage	char	'\x01'	'\x01'
_senderId	__NSCFString *	"7CjXUi6426"	0x7874b730
_senderDisplayName	__NSCFString *	"Test3"	0x7874b8b0
_date	__NSDate *	2015-07-27 13:28:46 UTC	0x78707d20
_text	id	0x0	0x00000000
_media	JSQPhotoMediaItem *	0x78725d90	0x78725d90
JSQMediaItem	JSQMediaItem		
NSObject	NSObject		
_appliesMediaViewMaskAsOutgoing	BOOL	YES	'\x01'
_cachedPlaceholderView	UIView *	nil	0x00000000
_image	UIImage *	0x7887de40	0x7887de40
NSObject	NSObject		
_imageRef	__NSCFType *	0x78e67260	0x78e67260
_scale	float	1	1
_traitCollection	UITraitCollection *	0x78743a10	0x78743a10
_imageAsset	UIImageAsset *	nil	0x00000000
_cachedImageView	UIImageView *	0x788b61a0	0x788b61a0

**Comment by jessesquires** [comment]
Thanks @icaroNZ ! :smile:  I don't really understand your question, please clarify.

Also, please update the issue after reading the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md)!

**Comment by icaroNZ** [comment]
Oh I am sorry, I will do my best. The version of the lib is 7.1

I will add the steps of what I am trying to do it may be longer but easier to understand.

The user sender a pic using:
        let sendMessage = JSQMessage(senderId: senderId, displayName: senderDisplayName, media: photoItem)
        self.messages.append(sendMessage)
        self.finishSendingMessage()

Great now I can see the pic on my screen and I want to tap on it and I want it to popup full screen (for any of the old photos as well so I am using "didTapMessageBubbleAtIndexPath"

here I have:
println(messages[indexPath.row]) here retrieve my JSQMessage object for that message and I can see it has my image on it (the dump above) but I cannot retrive it

Sorry I hope I could explain the issue better, I don't know if it is really a issue or is something in object C that i don't know and I couldn't find an answer, anyway I appreciate

**Comment by icaroNZ** [comment]
I just find the answer for it here on the item #820 i have no idea how to make it in swift using the <id> but know that I know it is possible I will figure out.

Thanks!

**Comment by lichenglu** [comment]
Thanks for the question icaroNZ!
