### ISSUE TITLE
Messages start at bottom when empty

### ISSUE THREAD

**Issue by mohonish** [jessesquires/JSQMessagesViewController#1119]
Hi,

Is there any way that I can configure it such that when there are no previous chat messages the new messages start from the bottom? By default I found that it appears from the top of the container view. But I want it to appear from the bottom and move up as other messages come in.

Thanks,
Mohonish.

**Comment by jessesquires** [comment]
Hey @mohonish !

You could try to adjust the `collectionView` `contentInset`.

**Comment by mohonish** [comment]
Thank you so much @jessesquires. That did the trick! :)

**Comment by xcriss** [comment]
Hey @mohonish could you share the code? contentInset is not changing anything for me. 

Thanks
