### ISSUE TITLE
Message bubbles squashed horizontally

### ISSUE THREAD

**Issue by gurrkin** [jessesquires/JSQMessagesViewController#1120]
Hi. Just implemented JSQ into my application. I've put the view controller for the chat inside another, and for some reason my bubbles are being squashed, and are not expanding to fill more of the window. Can anyone point me in the right direction?

Here's the code:
http://paste.ofcode.org/DUssCPHMGXMxMa3F35WHfd

Here's a screenshot:
http://postimg.org/image/tigbef0c1/

Another related issue, is we're trying to add this view separately using auto layout/constraints programatically, and the chat resizes correctly. However, this causes all buttons to be disabled, and all interaction no longer works?

Thanks

**Comment by jessesquires** [comment]
Hey @gurrkin ! :smile: 

It looks like there are a lot of layout issues there. Try looking at the `messageBubbleLeftRightMargin` property on the `FlowLayout`. Also be sure to return unique values for `messageHash` on your `JSQMessageData` objects.

> P.S. Next time be sure to read the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) before opening an issue! :smile:

**Comment by gurrkin** [comment]
Thanks, this has solved my issue in regards to bubble squashing. Any ideas about the constraints though? We cannot set auto-layout programatically without the buttons etc becoming unclickable?
