### ISSUE TITLE
CollectionView frame gap from inputToolbar before inputToolbar selected

### ISSUE THREAD

**Issue by khaptonstall** [jessesquires/JSQMessagesViewController#1121]
I'm currently testing with iOS 8.1 on iPhone simulator 5s and an actual iPhone 5s and having the problem in both places. I just re-cloned the repository to make sure it wasn't my copy that was out of date. 

I'm having the problem that, when I bring up my `JSQMessagesViewController` class, there is a gap between the last message and the `inputToolbar`. 
![jsqmessages-beforescroll](https://cloud.githubusercontent.com/assets/6239518/8909882/d1dcf616-3451-11e5-88a5-20e9478dd587.png)

This gap goes away when I press on the `inputToolbar`, the keyboard displays, and then I scroll down so that the keyboard goes away. 
![jsqmessages-afterscroll](https://cloud.githubusercontent.com/assets/6239518/8909972/44e17e3e-3452-11e5-8f1d-4b2fb7dd31ae.png)

I think this has something to do with the frame of the `JSQMessagesViewController` but I can't seem to find where and how to constraints are changed when dismissing the keyboard, because that is what I wish them to be when the view loads initially.

**Comment by jessesquires** [comment]
Thanks @khaptonstall! :smile: 

You should check what the collectionView `contentInset` values are for each of these cases. The library manipulates that, not constraints, when the keyboard shows/hides.

> P.S. Next time, please read the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) before opening a new issue! :smile:

**Comment by khaptonstall** [comment]
It looks like when `viewDidAppear`, the `self.collectionView.contentInset.bottom == 93.0` and when the keyboard was dismissed, `self.collectionView.contentInset.bottom == 44.0`. Can I manually assign this value to 44.0 when `viewDidLoad`?

Also, this may be another problem, but I just noticed that when I send a new message, the bubble appears behind the `inputToolbar` and I must scroll in order to see it.

**Comment by jessesquires** [comment]
Is this related to #256?

**Comment by avityagi5** [comment]
Any update on this ?
That how to increase gap between collection view and input tool bar

**Comment by halpz** [comment]
same issue for me

**Comment by halpz** [comment]
<img width="438" alt="screen shot 2017-05-23 at 14 15 30" src="https://cloud.githubusercontent.com/assets/3755417/26355936/5389268a-3fc2-11e7-83ed-587c69fe6feb.png">
gap between most recent message and top of keyboard (gap also there when keyboard is closed)

**Comment by MikeSalvador** [comment]
Did anyone solve this issue?

**Comment by MikeSalvador** [comment]
Never mind. Solved it by using 

self.collectionView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
