### ISSUE TITLE
about topContentAdditionalInset

### ISSUE THREAD

**Issue by singer1026** [jessesquires/JSQMessagesViewController#1124]
in JSQMessageDemo
DemoMessagesViewController.m 

```
- (void)viewDidLoad{
  [super viewDidLoad];
  ……
  self.inputToolbar.maximumHeight = 120;
  self.topContentAdditionalInset = 200;
  ……
}
```

TextView value changed， but the height of textView not change

Help, please.

**Comment by jessesquires** [comment]
Thanks @singer1026 - Please update your issue after reading the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) :smile:

**Comment by singer1026** [comment]
sogou keyboard is a popular keyboard in China
https://itunes.apple.com/us/app/sou-gou-shu-ru-fa-sogou-keyboard/id917670924?mt=8

use sogou keyboard in JSQMessageDemo and self.topContentAdditionalInset = 200;
TextView value changed， but the height of textView not change.

but if I use system keyboard ,it is ok.

**Comment by jessesquires** [comment]
Thanks @singer1026! Unfortunately, the library can't do much to support third-party keyboards.
