### ISSUE TITLE
Using JSQMessagesViewController With External Programmatic Constraints

### ISSUE THREAD

**Issue by gurrkin** [jessesquires/JSQMessagesViewController#1126]
Hi.
We are currently trying to use this view controller in conjunction with programmatic constraints. When we set auto-layouts and constraints on the view belonging to the controller, such as :

 NSLayoutConstraint.constraintsWithVisualFormat("V:[top][X][bottom]", options: nil, metrics: nil, views: views)

The view successfully resizes, but we lose functionality in the buttons and user interactive places? Any ideas? Using SWIFT currently, but an help would be great.

Library version(s) : Latest
iOS version(s) : 8
Devices/Simulators affected: iPad
Complete steps to reproduce the issue : Apply programmed constrains to the view of the messages controller
Link to a project that exhibits the issue: N/A - Can't distribute code
Screenshots/GIFs/Videos showing the issue, if applicable : N/A
Full crash log, if applicable N/A
Search for and list any issues that might be related : N/A

Thanks

**Comment by jessesquires** [comment]
Thanks @gurrkin ! :smile: 

It doesn't sound like this is due to the library itself, so going to close. You might try posting on StackOverflow.

If you can repro this in the demo, let me know!
