### ISSUE TITLE
Listen to textViewBeginEditing

### ISSUE THREAD

**Issue by ankurarora** [jessesquires/JSQMessagesViewController#1131]
Hi,

First of all thanks to you for sharing such a good library. It helped me a lot.

Now, the problem I am facing is that in my project there is a need to listen TextView delegates as the moment user puts focus in textView I need to perform an action. I tried myMessageView.inputToolbar.contentView.textView.delegate = self; which is also working but that has made internal delegate to stop working. 

Is there a possibility to expose a delegate from JSQMessageViewController itself which we can utilize?

I can do that if you can give me access to the repo.

Look forward to hear back.

**Comment by jessesquires** [comment]
Hey @ankurarora - thanks!

`JSQMessagesViewController` publicly declares conformance to `UITextViewDelegate`. You can implement these methods in your subclass, just be sure to call `super` first.
