### ISSUE TITLE
TextBottomLabel

### ISSUE THREAD

**Issue by vinayv1234** [jessesquires/JSQMessagesViewController#1132]
I want to show if a message is delivered or not by using the cellBottomLabel by showing a √ mark. I was able to access the cell in the GetCell method and set its text. However, I do not see it when I run the app. What might I be doing wrong? Kindly request your help.

**Comment by jessesquires** [comment]
Thanks @vinayv1234 ! 

This question has been asked before, the following issues should help! :smile: 
https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+delivery+status+is%3Aclosed

https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=is%3Aissue+%5BCustom+cells%5D+is%3Aclosed+
