### ISSUE TITLE
textview placeholder misplace

### ISSUE THREAD

**Issue by codwam** [jessesquires/JSQMessagesViewController#1133]
```
self.inputToolbar.preferredDefaultHeight = 50;
```

while I set above property,then input two lines text and send, placeholder is misplaced?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by codwam** [comment]
Sounds sadly.
