### ISSUE TITLE
JSQMessagesViewController as subview - keyboard hides input

### ISSUE THREAD

**Issue by mp3il** [jessesquires/JSQMessagesViewController#1137]
Hi guys,

I'm using JSQMessagesViewController as a subview inside UIViewController,
I have a problem, where when I click the input and the keyboards open - the view won't move, so the keyboard actually hides the bar and the whole bottom part of the JSQMessagesViewController view.

Anything I'm missing? maybe setting JSQMessagesViewController frame is the cause? what's the best practice ?

Update: it seems that if the JSQMessagesViewController is in the bottom part of the view and a height that doesn't allow it to show both the keyboard and the input, it will hide it.

Thanks in advance
Guy.

**Comment by mp3il** [comment]
Ok, the problem was that I was creating the JSQMessagesViewController at the parent viewDidLoad
and not viewDidAppear.

make sense?

**Comment by jessesquires** [comment]
Thanks @mp3il ! 

Sounds like you solved it?

**Comment by qaysdwekat** [comment]
How i can use JSQMessagesViewController as a subview inside another UIViewController ?!?!

**Comment by mp3il** [comment]
Simply add the JSQMessagesViewController view to your vc view.

Just make sure you are doing it in your parent vc(your uiviewcontroller) after it appeared. (viewDidAppear).

**Comment by qaysdwekat** [comment]
could you give me more details ?

**Comment by mp3il** [comment]
Describe the problem your'e having / post some code so I can see what your'e doing wrong.

Basically as I mentioned:
Assuming you want to add JSQMessagesViewController to your UIViewController programmatically, you should simply add the JSQMessagesViewController view to your UIViewController view.

Just make sure you to do it after your UIViewcontroller appeared.

**Comment by qaysdwekat** [comment]
i want to make chat head like facebook, and this chat have subview contain the JSQMessagesViewController but i can't add JSQMessagesViewController view to my view
