### ISSUE TITLE
Adding data label, changing load earlier messages text color and setting up localization file

### ISSUE THREAD

**Issue by mrfarukturgut** [jessesquires/JSQMessagesViewController#1139]
Hi, I have 3 questions, and I looked up around a bit but I couldn't find something. 

Here the questions:

1-) How can I add date label to collection view?

2-) How can change 'load earlier message' button properties like font, color, background? And how can use the button? 

3-) How can I set up localization file to the project? I need to change the text data of input toolbar and I tried it programmatically but text didn't fit in the button. I also tried several ways to set up the local. file but they didn't work out. 

Lastly, I am using swift and I am kinda new to iOS programming. You can reference obj-c codes but swift will be better. 

Thanks.

**Comment by harlanhaskins** [comment]
1) Use `collectionView(_:attributedTextForCellTopLabelAtIndexPath:)`, and return the date label you'd like to use.

I use it like this:
```rust
let timestampFormatter = JSQMessagesTimestampFormatter()
override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
    let message = self.messages[indexPath.item]
    if self.shouldShowTimestampForIndexPath(indexPath) {
        return self.timestampFormatter.attributedTimestampForDate(message.timestamp)
    }
    return nil
}
```

2) Right now, the only customization you can change it is `loadEarlierMessagesHeaderTextColor`. It's a property on `JSQMessagesCollectionView`. You can use it by implementing the `JSQMessagesCollectionViewFlowLayoutDelegate` function, `collectionView(_:header:didTapLoadEarlierMessagesButton)`.

3) You have full control over the text in the input toolbar. The placeholder text should probably be set up with an `NSLocalizedString`. Look to the [Localizing Your App](https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html#//apple_ref/doc/uid/10000171i-CH5-SW1) guide for help with that.

**Comment by jessesquires** [comment]
Thanks @harlanhaskins ! :smile: :smile:

**Comment by mrfarukturgut** [comment]
in the code, there is an compiler error at if self.shouldShowTimestampForIndexPath. It says viewController does not have a member like this. can you help?

**Comment by harlanhaskins** [comment]
shouldShowTimestampForIndexPath is a function with an argument, not a property.

**Comment by mrfarukturgut** [comment]
actually i copy pasted the your code
