### ISSUE TITLE
Custom Cell height getting updated.

### ISSUE THREAD

**Issue by iurichiba** [jessesquires/JSQMessagesViewController#1140]
Hi,

I'm having a hard time understanding what methods I should override in order to display my custom cell in its default height. It shows up okay for about a second before it gets updated (probably by some method I'm missing).

![image](https://cloud.githubusercontent.com/assets/2319719/9099448/221caeb2-3ba7-11e5-96e7-cb68217458e7.png)
Then, after a second or so...
![image](https://cloud.githubusercontent.com/assets/2319719/9099456/37ccbc20-3ba7-11e5-9448-a91422188714.png)

So far, I'm testing stuff w/ placeholder values, but I tried these methods (subclassing them):
- collectionView:layout:sizeForItemAtIndexPath; (custom ViewController)
- messageBubbleSizeForItemAtIndexPath; (custom FlowLayout)
- sizeForItemAtIndexPath (custom FlowLayout)

All of them using this method body:
```
id cell = [self.collectionView cellForItemAtIndexPath:indexPath];
    if ([cell conformsToProtocol:@protocol(DHCustomMessageProtocol)]) {
        return CGSizeMake(200, 200);
    } return [super whateverMethodItsOverriding];
```

It works, but only temporarily. Any ideas on what's causing this height update?

I hope you can help me! Thanks!

**Comment by iurichiba** [comment]
So, I figured out that that "second" it stays w/ 200x200 frame is before I refresh the data and call [self.collectionView reloadData]. I guess it filters out the problem to ViewController/FlowLayout methods - are there any other methods that calculate height besides the ones cited above?

**Comment by iurichiba** [comment]
Ok, so I found out that for some reason after ``[self.collectionView reloadData] `` is called, the cell isn't recognized as conforming to DHCustomMessageProtocol. Still dunno why, but it's probably something I f'd up, so I'll take it from here.

I'm sorry if I ended up spamming - not my intention.

But I'll keep an eye on the repository, I'm learning quite a bit about it, so I guess I'll be able to help out w/ minor issues or doubts. :grin:

**Comment by jessesquires** [comment]
Thanks @iurichiba ! :smile:

**Comment by brokeniceinteractive** [comment]
@iurichiba can you post the classes of your custom cell?

**Comment by iurichiba** [comment]
@brokeniceinteractive I'm not really sure what I did back then, I just know that it's working now, hahaha! But I think I can manage to find some time so that I can create an example project later, would that help? :)

It'd be nice if I could make it work with dynamic heights, too, my algorithm is coded to work with certain fixed heights, atm. I'll keep that in mind!

**Comment by brokeniceinteractive** [comment]
Ok thank you!
