### ISSUE TITLE
Improve initialization with NS_DESIGNATED_INITIALIZER and NS_UNAVAILABLE

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1142]
Audit all classes to use `NS_DESIGNATED_INITIALIZER` or `NS_UNAVAILABLE` for initializers.

**Comment by mauruskuehne** [comment]
Have you started working on this? If you haven't, I'd like to start implementing this :smile:

**Comment by jessesquires** [comment]
@mauruskuehne go for it! :smile: 

Thanks! :clap:

**Comment by mauruskuehne** [comment]
I have a question about ```JSQMediaItem``` and its subclasses. How should I define the designated initializers for these classes? I think the designated initializers for ```JSQMediaItem``` are ```initWithMaskAsOutgoing:``` and ```initWithCoder:``` (they call ```super init```). 
But what should the designated initializers be for ```JSQLocationMediaItem```? It doesn't override one of the designated initializers of ```JSQMediaItem```. It's initializer ```initWithLocation:``` doesn't call one of the designated initializers of ```JSQMediaItem```. 
And if ```initWithLocation:``` stays a convenience initializer, shouldn't it call a designated initializer of ```JSQLocationMediaItem```?

**Comment by jessesquires** [comment]
@mauruskuehne -- great question! :smile: 

After messing around with this, it does get cumbersome. Let's hold off on this change for `JSQMediaItem`s for now

**Comment by jessesquires** [comment]
closed by #1460
