### ISSUE TITLE
Comparison of the same JSQMessage containing a JSQLocationMediaItem

### ISSUE THREAD

**Issue by KBLNY** [jessesquires/JSQMessagesViewController#1143]
Hi !
I'm using well the JSQMessagesViewController framework in a basic way.
I implemented a "Load Earlier" method doing the following:
1. first load (WillAppear) of the view : load only the 20 most recent messages from the DB
2. When the user click on the "Load Earlier" button, I load the (x + 20) next messages, where "x" is the number of the previously loaded messages.
3. I go through all loaded messages (40 the first time the button is triggered), and test the collectionView against each newly loaded message, in order to display only the next 20 messages.

Everything working great, except if the "Chat Thread" contain a "Location Message". Indeed, in that case, I found all location messages of this chat thread are duplicated, and only  location message, not text or image message.

I found the reason:
JSQMessage.m
BOOL hasEqualContent = self.isMediaMessage ? [self.media isEqual:aMessage.media] : [self.text isEqualToString:aMessage.text]; --> this line return "NO" 
This line calls JSQLocationMediaItem.m
return [self.location isEqual:locationItem.location]; returning "NO"
which is particularly strange because I set all the properties of my JSQLocationMediaItem.

Workaround:
If I replace the following line in JSQLocationMediaItem.m:
return [self.location isEqual:locationItem.location]; 
by
return (self.location.coordinate.latitude == locationItem.location.coordinate.latitude)
    && (self.location.coordinate.longitude == locationItem.location.coordinate.longitude)
    && (self.location.altitude == locationItem.location.altitude)
    && (self.location.horizontalAccuracy == locationItem.location.horizontalAccuracy)
    && (self.location.verticalAccuracy == locationItem.location.verticalAccuracy)
    && (self.location.course == locationItem.location.course)
    && (self.location.speed == locationItem.location.speed)
    && ([self.location.timestamp isEqualToDate:locationItem.location.timestamp]);
then the - (BOOL)isEqual:(id)object of JSQLocationMediaItem return "TRUE".

Did I mess up something? 
FI, I didn't check JSQVideoMediaItem. But since the equal method is already based on comparing the "fileURL" and the "isReadyToPlay", I am then confident the comparison between JSQMessages containing JSQVideoMediaItem will be right.

**Comment by chapayGhub** [comment]
Changed in code
 [snapShotter startWithQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0) to
 [snapShotter startWithQueue:dispatch_get_main_queue()
And it seems fixed.

**Comment by harlanhaskins** [comment]
If that seemingly entirely unrelated, UI-specific line fixed it, that might not have been the problem.

**Comment by davecom** [comment]
I'm seeing the same issue with regards to checking two JSQMessages for equality when they contain a location media item.

**Comment by davecom** [comment]
KBLNY - it would be great if you could submit the change as a pull request.

**Comment by bacancyhima** [comment]
JSQLocationMediaItem is setting location each time when collectionview reloads. so it returns empty bubble until location reloads. i don't want to reload other JSQLocationMediaItem while adding new item, anyone having solution for this?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
