### ISSUE TITLE
InputToolbar does not animate up when another textField gets first responder

### ISSUE THREAD

**Issue by derekjcarter** [jessesquires/JSQMessagesViewController#1145]
If you are using a contact picker with JSQMessages, when the contact picker (or any other UITextField) gets first responder, the keyboard animates up an empty frame but leaves the inputToolbar at the bottom. By removing the following code from JSQMessagesViewController, the inputToolbar moves with the keyboard with any first responder.

``` Obj-C
if (![self.inputToolbar.contentView.textView isFirstResponder] && self.toolbarBottomLayoutGuide.constant == 0.0f) {
    return;
}
```

I created a pull request for this here:  https://github.com/jessesquires/JSQMessagesViewController/pull/1144

-Derek

**Comment by jessesquires** [comment]
Hey @derekjcarter - I don't understand why you would want this behavior.

This line fixes other bugs. See #648 and #649

**Comment by derekjcarter** [comment]
Hey @jessesquires,

I'm trying to mimic the behavior of Apple's Message app.  When you click on the contact list's textfield, the input toolbar also is animated up with the keyboard.  The reason they do that is so when you are done picking contacts in the list to send the message to, the keyboard will not lose focus on the screen.

Issue #648 and #649 seem to be an issue for the opposite use case.  If you do not want to mimic Apple's behavior, then this is not an issue.  In my case, it is an issue.

I have a branch in my fork with a contact picker integrated if you want to take a look.  https://github.com/derekjcarter/JSQMessagesViewController/tree/contact-picker

Regardless which behavior you prefer, thanks for the library.  I've enjoyed getting involved with it.

Take care,
Derek

**Comment by jessesquires** [comment]
Ahh, interesting. Thanks for the update @derekjcarter ! :smile: 

I think this is the less-common case. I would definitely recommend simply overriding the following method to fit your use case.

````objective-c
- (void)keyboardController:(JSQMessagesKeyboardController *)keyboardController keyboardDidChangeFrame:(CGRect)keyboardFrame
````

**Comment by derekjcarter** [comment]
For those in the same boat and looking for help...
```Obj-C
@property (nonatomic, strong) NSLayoutConstraint *toolbarBottomLayoutGuide;

// Override
- (void)keyboardController:(JSQMessagesKeyboardController *)keyboardController keyboardDidChangeFrame:(CGRect)keyboardFrame
{
    CGFloat heightFromBottom = CGRectGetMaxY(self.collectionView.frame) - CGRectGetMinY(keyboardFrame);
    heightFromBottom = MAX(0.0f, heightFromBottom);
    
    self.toolbarBottomLayoutGuide.constant = heightFromBottom;
    [self.view setNeedsUpdateConstraints];
    [self.view layoutIfNeeded];
    
    UIEdgeInsets insets = UIEdgeInsetsMake(self.topLayoutGuide.length + self.topContentAdditionalInset, 0.0f, CGRectGetMaxY(self.collectionView.frame) - CGRectGetMinY(self.inputToolbar.frame), 0.0f);
    self.collectionView.contentInset = insets;
    self.collectionView.scrollIndicatorInsets = insets;
}
```

Thanks for the help @jessesquires

**Comment by jessesquires** [comment]
Thanks @derekjcarter ! :smile:
