### ISSUE TITLE
How to add extra left inset for incoming and rights inset for outcoming?

### ISSUE THREAD

**Issue by orkenstein** [jessesquires/JSQMessagesViewController#1147]
I want to achieve kinda this layout:
![2015-08-06 18 10 50](https://cloud.githubusercontent.com/assets/1461936/9151628/b3469f62-3e11-11e5-8603-c4447c87ad0e.png)

**Comment by orkenstein** [comment]
All I need is:

`collectionViewLayout.messageBubbleTextViewFrameInsets = UIEdgeInsetsMake(0, CHAT_MARGIN, 0, 0);`

**Comment by jessesquires** [comment]
Thanks @orkenstein ! :smile:
