### ISSUE TITLE
Link Color Issues

### ISSUE THREAD

**Issue by enouveau** [jessesquires/JSQMessagesViewController#1148]
Thanks for the wonderful library. I am using Version 7 of your library that was published through xamarin. My issue is related to the link color of the cell.UITextView. By default it is always white. I can change the foreground color of the message bubble text by setting the cell.TextView.TextColor which works great. But the link color always appears as White. I tried changing the TintColor of the UITextView so that the link color will change, but that did not work. Here is the code that I am using. Could someone please help?

    public override UICollectionViewCell GetCell (UICollectionView collectionView, NSIndexPath indexPath) 
	{
		var cell =  base.GetCell (collectionView, indexPath) as MessagesCollectionViewCell;
		cell.TextView.DataDetectorTypes = UIDataDetectorType.All;

		var message = messages [indexPath.Row];

		if (message.SenderId == SenderId) {

			// My color
			cell.TextView.TextColor = UIColor.White;
			cell.TextView.TintColor = UIColor.Yellow;

		} else {

			// Other party color
			cell.TextView.TextColor = UIColor.Black;
			cell.TextView.TintColor = UIColor.Blue;
		}

		return cell;
	}

**Comment by harlanhaskins** [comment]
Link highlight colors are controlled by UITextView's `linkTextAttributes` property.

This is what we do in Swift (not sure the exact C# syntax)
```rust
cell.textView.linkTextAttributes = [NSForegroundColorAttributeName: linkColor, NSUnderlineStyleAttributeName: 1]
```

**Comment by jessesquires** [comment]
Thanks @enouveau / @harlanhaskins !

**Comment by enouveau** [comment]
Thanks HarlanHaskins

Here is the C# code if anyone else would need it in the future:

    var key1 = new NSMutableString ();
	key1.SetString (new NSString ("NSColor"));
	var value1 = UIColor.Blue;

	var key2 = new NSMutableString ();
	key2.SetString (new NSString ("NSUnderline"));
	var value2 = new NSNumber(1);

	var dict = new NSDictionary (key1, value1, key2, value2);

	cell.TextView.WeakLinkTextAttributes = dict;

**Comment by harlanhaskins** [comment]
Does Xamarin not provide the NSString constants? Those strings aren't guaranteed to be "NSColor" and "NSUnderline"...

Also do you need to use an NSMutableString there?

**Comment by enouveau** [comment]
Good questions. I put a breakpoint in the debugger to check what type was the key and it showed a NSMutableString. So I went with that. I am not aware of any NSColor or NSUnderline constants in xamarin. Or I might not be looking at the right place.

**Comment by rvidis** [comment]
I am using UIStringAttributeKey.ForegroundColor and UIStringAttributeKey.UnderlineStyle

**Comment by DallasHoelscher** [comment]
I know this is deprecated, but if anyone is looking for this on swift 4 the values have changed. 

cell.textView?.linkTextAttributes = [NSAttributedStringKey.foregroundColor.rawValue : UIColor.blue , NSAttributedStringKey.underlineStyle.rawValue : NSUnderlineStyle.styleSingle.rawValue]

**Comment by sumitkrmishra** [comment]
I want to remove underline but this is not working
var key2 = new NSMutableString ();
key2.SetString (new NSString ("NSUnderline"));
var value2 = new NSNumber(1);

**Comment by sumitkrmishra** [comment]
> Thanks HarlanHaskins
> 
> Here is the C# code if anyone else would need it in the future:
> 
> ```
> var key1 = new NSMutableString ();
> key1.SetString (new NSString ("NSColor"));
> var value1 = UIColor.Blue;
> 
> var key2 = new NSMutableString ();
> key2.SetString (new NSString ("NSUnderline"));
> var value2 = new NSNumber(1);
> 
> var dict = new NSDictionary (key1, value1, key2, value2);
> 
> cell.TextView.WeakLinkTextAttributes = dict;
> ```

We are trying this code but underline cant not removed.
var value2 = new NSNumber(0);  //its not working

**Comment by yauhenipakala** [comment]
> Link highlight colors are controlled by UITextView's `linkTextAttributes` property.
> 
> This is what we do in Swift (not sure the exact C# syntax)
> 
> ```rust
> cell.textView.linkTextAttributes = [
>     NSForegroundColorAttributeName: linkColor,
>     NSUnderlineStyleAttributeName: NSUnderlineStyle.StyleSingle.rawValue
> ]
> ```

Simple C# port:

```cs
var linkTextAttributes = NSDictionary.FromObjectsAndKeys(
    new NSObject[]
    {
        NSNumber.FromInt32((int)NSUnderlineStyle.Single),
        UIColor.Red
    },
    new []
    {
        UIStringAttributeKey.UnderlineStyle,
        UIStringAttributeKey.ForegroundColor
    });

_textView.WeakLinkTextAttributes = linkTextAttributes;
```
