### ISSUE TITLE
[PFObject messageHash]: Unrecognized Selector Sent To Instance

### ISSUE THREAD

**Issue by pgh225** [jessesquires/JSQMessagesViewController#1152]
So I'm working on adding messaging to my app and I've been using the demo project and everything. I thought I had everything that I needed to but when I run the app, go to my "Messages" tab and select a conversation I get the following error: 

-[PFObject messageHash]: unrecognized selector sent to instance 0x7fc7d362b580

in the JSQMessagesCollectionViewFlowLayout in the messageBubbleSizeForItemAtIndexPath method.

Any help is greatly appreciated.

**Comment by harlanhaskins** [comment]
Your message class must implement the `JSQMessageData` protocol.

**Comment by pgh225** [comment]
I see that the 'messageHash' method is not implemented, but how do I go about doing that? Why is it this one method in the JSQMessageData protocol that is having problems?

**Comment by jessesquires** [comment]
Thanks @harlanhaskins !

@pgh225 - See the demo for examples :smile:
