### ISSUE TITLE
JSQMessagesViewController isn't loading

### ISSUE THREAD

**Issue by pgh225** [jessesquires/JSQMessagesViewController#1153]
I am pretty sure I've implemented everything I need to implement in order to add messaging to my app - I added a viewcontroller that is a subclass of JSQMessagesViewController, I've followed the demo project and quick tips, etc. - but when I run my app and click on a user to start a conversation, it brings me to an empty view controller. All it has is the username of the person I'm having the conversation with. There is no keyboard, no place to enter a new message, I tried adding a few test messages manually but they don't show up either. I have no idea what I've done wrong and although I've completely dissected the demo project, I feel like I'm overlooking something really simple.

**Comment by harlanhaskins** [comment]
Covering all our bases here -- are you using Storyboards? If so, are you 100% sure the class is set properly to your `JSQMessagesViewController` subclass?

**Comment by pgh225** [comment]
Yes I'm using storyboards. I've set the class to my MessagesViewController, which is a JSQMessagesViewController class. Is this the correct way to do it or am I supposed to set it to JSQMessagesViewController directly?

**Comment by harlanhaskins** [comment]
Nope, you're right by setting the class to `MessagesViewController`.
Could you post some code of how you present the view?

**Comment by pgh225** [comment]
So I have a table view where I list all of the people the current user is having conversations with. When you select on the table view cell it is supposed to take you to the chatroom. 

The code I wrote to do this is as follows in the TableViewController

-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
    if ([segue.identifier isEqualToString:@"showChat"]){
    MessagesViewController *messagesVC = segue.destinationViewController;
    NSIndexPath *indexPath = sender;
    messagesVC.chatroom = [self.availableChatRooms objectAtIndex:indexPath.row];
    }
}

and 

-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{    
    [self performSegueWithIdentifier:@"showChat" sender:indexPath];
}

The segue and everything works, so when I tap a cell it will take me to the next view controller (MessagesViewController), but nothing actually appears for some reason.

**Comment by pgh225** [comment]
Okay I figured out what was happening was just the navigator bar at the bottom was covering the input toolbar, so that's a relief. However, nothing happens when I type a message and hit the "send" button. Here is my didPressSendButton function:

-(void)didPressSendButton:(UIButton *)button withMessageText:(NSString *)text senderId:(NSString *)senderId senderDisplayName:(NSString *)senderDisplayName date:(NSDate *)date
{
    JSQMessage *message = [[JSQMessage alloc] initWithSenderId:self.currentUser.objectId
                                             senderDisplayName:self.currentUser.username
                                                          date:[NSDate date]
                                                          text:text];
    
    if (text.length != 0){
        PFObject *chat = [PFObject objectWithClassName:@"Chat"];
        [chat setObject:self.chatroom forKey:@"chatroom"];
        [chat setObject:self.currentUser forKey:@"fromUser"];
        [chat setObject:self.withUser forKey:@"toUser"];
        [chat setObject:text forKey:@"text"];
        [chat saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error){
           
            if (error){
                NSLog(@"Error: %@ %@", error, error.userInfo);
            }
            else {                
                [self.chats addObject:chat];
                [self.messages addObject:message];
                [self.collectionView reloadData];
                [self finishSendingMessage];
                [self scrollToBottomAnimated:YES];
            }       
        }];
    }   
}

**Comment by jessesquires** [comment]
Thanks @pgh225 / @harlanhaskins ! :smile:

**Comment by jessesquires** [comment]
@pgh225 - For your next issue, don't forget to review the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) first :smile:

**Comment by dmdeller** [comment]
@pgh225 -

> Okay I figured out what was happening was just the navigator bar at the bottom was covering the input toolbar

How did you determine this, and how did you fix it? I think I may be having a similar problem.

**Comment by jessesquires** [comment]
>This seems like a common enough issue that maybe it deserves a mention in the Readme or something? Just a thought.

@dmdeller - Please submit a PR! :smile:
