### ISSUE TITLE
didPressSendButton not registering

### ISSUE THREAD

**Issue by pgh225** [jessesquires/JSQMessagesViewController#1154]
I've posted a few issues recently so thanks for the help and feedback on those! My problem now is that my didPressSendButton isn't registering for some reason. I added an NSLog statement to the function but the console doesn't print anything. I'm using iOS 8/Objective-c. I'm wondering if I'm missing the implementation of something or a delegate but I'm pretty sure I would get an error if that was the case and everything else seems to be working fine. The application runs and everything, but once I enter the view controller where the conversation takes place, the send button doesn't work.

Thanks!

**Comment by jessesquires** [comment]
Thanks @pgh225 :smile: 

Please update the issue after reviewing the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md)! :smile:
