### ISSUE TITLE
Present JSQMessagesViewController with keyboard up

### ISSUE THREAD

**Issue by drussu** [jessesquires/JSQMessagesViewController#1157]
I want to start new conversations with the keyboard up (much like Apple's messaging app does, as well as Facebooks chat app, etc). Is there a standard way to tell the `JSQMessagesViewController` to pop the keyboard up without the user tapping the textfield? 

I tried using `self.keyboardController.textView.becomeFirstResponder()` in `JSQMessagesViewController`'s `viewDidLoadFunction`; however, this causes the keyboard to pop up instantly while the toolbar lags behind for 1-2 seconds. In addition, this solution does not allows the keyboard to be dismissed until the user leaves the view and comes back.

Is this impossible to achieve using the library as is? Or am I missing something?

**Comment by davepatterson** [comment]
I tried using self.keyboardController.textView.becomeFirstResponder() in JSQMessagesViewController's viewDidLoadFunction; however, this causes the keyboard to pop up instantly while the toolbar lags behind for 1-2 seconds. In addition, this solution does not allows the keyboard to be dismissed until the user leaves the view and comes back.

**Comment by davepatterson** [comment]
Sorry. I meant to say: have you tried using self.keyboardController.textView.becomeFirstResponder() in JSQMessagesViewController's viewWillAppear?

**Comment by jessesquires** [comment]
Hey @drussu / @davepatterson - this is the only way for now
