### ISSUE TITLE
empty space at bottom on first start

### ISSUE THREAD

**Issue by plenio** [jessesquires/JSQMessagesViewController#1158]
When starting the view controller the first time, I have an empty space at the bottom. 
When resizing or opening the keyboard, the empty space is gone. 

After same researching I found the problem: 
In jsq_updateCollectionViewInsets, the topLayoutGuide does not seem to be fixed. 
According to http://stackoverflow.com/questions/19140530/toplayoutguide-in-child-view-controller
the topLayoutGuide should be accessed in viewWillLayoutSubviews. 

So adding this code in my viewcontroller fixed the issue for me: 
- (void)viewWillLayoutSubviews
{
    [super viewWillLayoutSubviews];
    [self jsq_updateCollectionViewInsets];
}

I hope this info might be helpful to someone. 

I am new to github and not familiar with pull requests. If you guide me through I could do one.

**Comment by jessesquires** [comment]
This is pretty old, should be fixed with some other recent changes.

Also, haven't had any other reports of this.

Closing out.

**Comment by quanvo87** [comment]
I am having the same issue, though.

First load -> extra space on bottom under last message (regardless of how big it is).

When showing then hiding keyboard, the space is gone.

Another note is this extra space is also affecting the scroll bar. In other words, when scrolling, you can see that even the scroll bar stops at this space. It's not really an "extra space", but the view ends there.

**Comment by ignacio-chiazzo** [comment]
Is there a solution in swift for this issue? @plenio @jessesquires @quanvo87 @atroutt @ghazel

**Comment by ignacio-chiazzo** [comment]
https://github.com/jessesquires/JSQMessagesViewController/issues/1850 Take a look at this issue

**Comment by ignacio-chiazzo** [comment]
https://github.com/jessesquires/JSQMessagesViewController/issues/1850

**Comment by codeOfRobin** [comment]
I have this issue too!

**Comment by wanglouin1990925** [comment]
I have this issue too
