### ISSUE TITLE
Text view becomes selectable after tapping message

### ISSUE THREAD

**Issue by toreolsensan** [jessesquires/JSQMessagesViewController#1159]
Proving awesomeness: :muscle::sunglasses::facepunch:

I want to disable text selection because it's really confusing to understand how it works; do I tap twice, tap once then long-press, or what? I don't get it. Anyways, in my JSQMessagesViewController subclass I override cellForItemAtIndexPath:, call super, and then:

    cell.textView.selectable = NO

But the cell becomes selectable again because shouldShowMenuForItemAtIndexPath: doesn't save the previous textView's selectable state before setting it to NO, and when jsq_didReceiveMenuWillHideNotification: wants to restore the state, instead of using a saved value it simply assumes YES. Could we please save this in a property to go along with selectedIndexPathForMenu? I can make a PR if that's preferrable.

Using JSQMessagesViewController 7.1.0 on both iOS 7.1.2 and 8.4.

**Comment by toreolsensan** [comment]
If there's a better approach than setting selectable = NO I'd like to know, of course. It would be nice to let URLs be tappable.

**Comment by jessesquires** [comment]
Thanks @toreolsensan ! Interesting, definitely a bug.

> If there's a better approach than setting selectable = NO I'd like to know, of course. It would be nice to let URLs be tappable.

Yeah, the `UITextView` API is horrible for this. The behavior I want is to only be able to tap links, nothing else. But as you can see, that requires some ugly hacks.

1. Maybe try setting `userInteractionEnabled = NO`. Does that work?
2. If (1) doesn't work, a PR is welcome!

Related: #747. Eventually we'll be moving to `TTTAttributedLabel`.

**Comment by toreolsensan** [comment]
Setting `userInteractionEnabled = NO` does prevent text selection but also prevents data detectors from working.

I also tried returning nil from `JSQMessagesCellTextView selectedTextRange`. That prevented text selection while allowing links to be tapped, but now a weird magnifier appears instead when you double-tap. Seems really hard to get this right.

By the way, the `JSQMessagesCellTextView gestureRecognizer:shouldReceiveTouch:` doesn't seem to ever get called; there's no gesture recognizer being installed with this class as a delegate, is this a mistake? Also the comments claim the code is there to *ignore double-tap to prevent copy/define/etc. menu from showing*, but that doesn't seem right.

**Comment by jessesquires** [comment]
@toreolsensan - Yeah, there are lots of problems with UITextView, thus the move to `TTTAttributedLabel`

**Comment by LowAmmo** [comment]
@jessesquires - any update on the move to `TTTAttributedLabel`?

**Comment by jessesquires** [comment]
@LowAmmo -- Happening for the next major release. `8.0`

**Comment by Lucashuang0802** [comment]
Hey @jessesquires, I think this can be closed? #1337 is for migrating `UITextView` to `TTTAttributedLabel`. As for this issue, now long press is for the secondary menu. And double tapping is for text selection. 😃

**Comment by jessesquires** [comment]
👍

**Comment by deyil** [comment]
@toreolsensan - The following extension seems to do the trick for the same issue I had. Links still work from what I see. The only problem is when a cell gets selected (not text view), links lose their underline for some reason until they are unselected.

`extension JSQMessagesCellTextView {
    public override func canBecomeFirstResponder() -> Bool {
        return false
    }
}`
