### ISSUE TITLE
Gradient shading like in iMessages

### ISSUE THREAD

**Issue by winzig** [jessesquires/JSQMessagesViewController#116]
A feature request for the ability to do gradient shading of the colored bubbles, as it is in iMessages on iOS 7. It's a subtle effect, but you'll notice the color of the bubbles is lighter when they're at the top of the window, and darker when they're near the bottom.

**Comment by nathanielescribano** [comment]
Any update on this?
it would be a nice to have!

**Comment by betzerra** [comment]
@nathanielescribano check my fork at https://github.com/betzerra/JSQMessagesViewController/tree/improvement-gradient

**Comment by jessesquires** [comment]
Thanks @betzerra ! :smile: 

A PR would be nice — but probably best //after// the 8.0 release of the library, which will include a lot of refactoring and performance improvements

**Comment by betzerra** [comment]
Sure, I'll stay tuned to the 8.0 release and then doing PR :-)

-- 
Ezequiel Becerra
http://www.betzerra.com.ar
tw: @betzerra

On December 23, 2015 at 3:59:12 PM, Jesse Squires (notifications@github.com) wrote:

Thanks @betzerra !  

A PR would be nice — but probably best //after// the 8.0 release of the library, which will include a lot of refactoring and performance improvements

**Comment by jessesquires** [comment]
@betzerra :+1: Moving a bit slowly right now, but you can subscribe to #1216 and #1336 :smile:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
