### ISSUE TITLE
Incoming Message Bubbles sticking to right

### ISSUE THREAD

**Issue by pgh225** [jessesquires/JSQMessagesViewController#1160]
The title pretty much explains it all. I've looked around the issues here and I know there have been a few similar issues with problems pertaining to the message bubbles going to the wrong side of the screen but they always have to do with changing the self.senderId which I know I've done. 

Here is some of my code

-(id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    
    PFObject *chat = self.chats[indexPath.item];
    PFUser *testFromUser = chat[@"fromUser"];
    
    if ([testFromUser.objectId isEqualToString:self.currentUser.objectId]){
        NSLog(@"outgoing message");
        return self.outgoingBubbleImageData;
    }
    else {
        NSLog(@"incoming message");
        return self.incomingBubbleImageData;
    }   
}

I've included the NSLog statements to make sure that my code was able to differentiate between the current user sending the outgoing messages and the other user sending the incoming messages, which according to my console workouts out fine, yet I still have the incoming message bubbles on the right side of the screen.

![screen shot 2015-08-14 at 1 35 16 am](https://cloud.githubusercontent.com/assets/12650123/9267760/bd188a36-4222-11e5-9608-4f116fa25b2b.png)

**Comment by jessesquires** [comment]
Hey @pgh225 - Please see the previous questions. :smile: 

https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+%5Bmessage+bubble+wrong+side%5D+is%3Aclosed

> P.S. remember to search previous issues before opening a new one :smile:
