### ISSUE TITLE
The keyboard drag location doesn't work for non-full screen chats

### ISSUE THREAD

**Issue by kostub** [jessesquires/JSQMessagesViewController#1161]
In `JSQMessagesKeyboardController.m` function 

    - (void)jsq_handlePanGestureRecognizer:(UIPanGestureRecognizer *)pan

which recognizes keyboard drags calculates whether to dismiss the keyboard as follows:

    CGFloat dragThresholdY = (contextViewWindowHeight - keyboardViewHeight - self.keyboardTriggerPoint.y);
    BOOL userIsDraggingNearThresholdForDismissing = (touch.y > dragThresholdY);

However this doesn't work if the chat view is not full screen. The issue seems to be that `dragThresholdY` is calculated in window coordinates while `touch` is calculated in the co-ordinates of the contextView as follows:

    CGPoint touch = [pan locationInView:self.contextView];

I believe the correct way to do this is:

    CGPoint touch = [pan locationInView:self.contextView.window];

which fixes the drag point for the keyboard.

**Comment by jessesquires** [comment]
Thanks @kostub !
