### ISSUE TITLE
Is it possible to replace JSQMessageData text on the fly, or support a text placeholder?

### ISSUE THREAD

**Issue by eliburke** [jessesquires/JSQMessagesViewController#1163]
I have an app whose chat messages are encrypted, and I am trying to upgrade the Messages UI to something more modern. Displaying a text message can require a download and decrypt step, much the same as image retrieval.

Treating encrypted messages as "text", I have tried setting a placeholder value such as "..." and then reloading the collectionView when it is decrypted and available. Unfortunately, the bubble size is not re-calculated. I saw a suggestion on another issue to call 
          `[self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];`
but it did not have any affect. 

My other option is to treat encrypted text as "media". Unfortunately, this means re-doing all of the text layout and bubble work that is not available for media messages. And in limited testing it did not seem to handle resizing well either. 

Is there a way to force recalculation of the bubbles that I just haven't found? Or is this essentially the same issue as #497? If so, how would you suggest I proceed? Would you accept a PR that added a text placeholder?

Thanks
Eli

**Comment by eliburke** [comment]
Ok, after some sleuthing I figured out why my bubble sizes wouldn't update. The size is cached per cell in the private JSQMessagesCollectionViewFlowLayout:messageBubbleCache.

I moved the messageBubbleCache declaration out to the header file and fixed my problem by calling `    [self.collectionView.collectionViewLayout.messageBubbleCache removeObjectForKey:@(myData.messageHash)];`

So I can fork and fix, or subclass a couple of objects, but I'd rather solve this in a way that you will incorporate back into the module. Would you be ok with something like this:
````
- (void)removeFromCache:(NSString*)key
{
    if (key) {
        [self.messageBubbleCache removeObjectForKey:key];
    } else {
        [self jsq_resetLayout];
    }
} 
````

**Comment by jessesquires** [comment]
Thanks @eliburke ! :smile: 

This functionality is already accessible. Here's the correct way to do this:

````objective-c
JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context]
context.invalidateFlowLayoutMessagesCache = YES;
[self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];
````
