### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by ZhuchoG** [jessesquires/JSQMessagesViewController#1165]
Hello!

Today I get error on device with updated 8.4.1:

dyld: Library not loaded: @rpath/JSQMessagesViewController.framework/JSQMessagesViewController
  Referenced from: /private/var/mobile/Containers/Bundle/Application/5A99B1E5-894B-493D-83EE-C067D8292447/myApp.app/myApp
  Reason: Incompatible library version: myApp requires version 7.0.0 or later, but JSQMessagesViewController provides version 1.0.0

In simulator all is OK, XCode Version 6.4 (6E35b), in podfile use_frameworks! used.

Any thoughts?

**Comment by jessesquires** [comment]
Hey @ZhuchoG :smile: 

This doesn't sound related to the library. Sounds like your project settings need to be fix. You might also want to clear `DerivedData/`.

**Comment by trsneed** [comment]
@ZhuchoG I am seeing this issue as well after updating my pods. Did you solve this?

**Comment by trsneed** [comment]
@jessesquires @ZhuchoG this answer helped, I had to clean the build artifacts folder for some reason.

http://stackoverflow.com/questions/31750603/dyld-library-not-loaded-app-requires-afnetworking-2-0-0-but-provides-version-1
