### ISSUE TITLE
Allow MediaItems to provide a custom bubble image mask (for use with custom bubble images)

### ISSUE THREAD

**Issue by eliburke** [jessesquires/JSQMessagesViewController#1168]
Perhaps I am again missing the obvious, but I can't find any way to override the default bubble mask on the JSQ*MediaItem classes without subclassing and re-writing the mediaView and mediaPlaceholderView methods. 

As I see it, the problem lies in JSQMessagesViewController:cellForItemAtIndexPath:

```
    if (!isMediaMessage) {
        ... [SNIP] ...
        id<JSQMessageBubbleImageDataSource> bubbleImageDataSource = [collectionView.dataSource collectionView:collectionView messageBubbleImageDataForItemAtIndexPath:indexPath];
        if (bubbleImageDataSource != nil) {
            cell.messageBubbleImageView.image = [bubbleImageDataSource messageBubbleImage];
            cell.messageBubbleImageView.highlightedImage = [bubbleImageDataSource messageBubbleHighlightedImage];
        }
    }
    else {
        id<JSQMessageMediaData> messageMedia = [messageItem media];
        cell.mediaView = [messageMedia mediaView] ?: [messageMedia mediaPlaceholderView];
        NSParameterAssert(cell.mediaView != nil);
    }
```

Text cells ask the collectionView's data source which bubble to use, but mediaView and mediaPlaceholderView rely on a class method of JSQMessagesMediaViewBubbleImageMasker, which in turn uses the default JSQMessagesBubbleImageFactory. 

If I'm wrong... how can I customize? If I'm right, how might you like to see this fixed? I think that adding the bubbleMask as a parameter to mediaView, or adding a setter to JSQMessageMediaData makes sense. Then, Media would no longer need to know if it is incoming or outgoing,  applyIncomingBubbleImageMaskToMediaView and applyBubbleImageMaskToMediaView would become superfluous, and JSQMessagesMediaViewBubbleImageMasker could be deleted, and jsq_maskView could be moved to a class method elsewhere.

**Comment by jessesquires** [comment]
Thanks @eliburke !

This is answered in #650.

**Comment by eliburke** [comment]
@jessesquires I don't believe that this is the same issue as #650. My problem is not the direction of the chat tail, my problem is with the mask itself. I have replaced the default image mask with my own, and subclassed JSQPhotoMediaItem for my images (because I wanted to make use of the placeholder image support). 

Unfortunately, the default implementations of mediaView and mediaPlaceholderView directly call JSQMessagesMediaViewBubbleImageMasker and JSQMessagesBubbleImageFactory, and get the base chat image mask (whether left side or right side).

Is it your intention that we must re-implement all of the media objects in order to change the bubble mask?

**Comment by jessesquires** [comment]
Ahhh, got it! :+1: 

Re-opening as a feature request.

**Comment by joshuawilde** [comment]
Is there a solution for this? I'd like to be able to set the style in the `- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath` method.

**Comment by seandadashi** [comment]
+1

**Comment by erynofwales** [comment]
+1

**Comment by JonMo** [comment]
First, thanks @jessesquires for this amazing work.
I temporarily fixed this issue by changing the source code, replacing jsq_bubbleCompactImage by jsq_bubbleCompactTaillessImage in the JSQMessagesBubbleImageFactory.m

```
- (instancetype)init
{
    return [self initWithBubbleImage:[UIImage jsq_bubbleCompactTaillessImage] capInsets:UIEdgeInsetsZero];
}  
```

It is obviously not an acceptable fix. 
Is there any update to set the media bubble style in a clean way?

Thanks

**Comment by jessesquires** [comment]
@JonMo the 8.0 release will fix this problem :smile:

**Comment by JonMo** [comment]
@jessesquires Thanks!

**Comment by tonylenzi** [comment]
@JonMo 

You could use a category for this for now, might be a bit cleaner than modifying the underlying library:

```
@implementation JSQMessagesBubbleImageFactory (TailessMedia)

-(instancetype)init {
    return [self initWithBubbleImage:[UIImage jsq_bubbleCompactTaillessImage] capInsets:UIEdgeInsetsZero];
}
```

**Comment by srinathp90** [comment]
+1

**Comment by blob8129** [comment]
+1

**Comment by alejandrorbradford** [comment]
+1

**Comment by nenzitre** [comment]
+1

**Comment by eliburke** [comment]
If you are comfortable with a little hoop jumping, you can provide a custom bubble image with a little method swizzling. I posted the steps here: #1180

**Comment by antrix1989** [comment]
My solution with subclass: 
```
import UIKit
import JSQMessagesViewController

class SDPhotoMediaItem: JSQPhotoMediaItem
{
    override func mediaView() -> UIView?
    {
        if let imageView = super.mediaView() as? UIImageView {
            let masker = JSQMessagesMediaViewBubbleImageMasker(bubbleImageFactory: JSQMessagesBubbleImageFactory(bubble: UIImage.jsq_bubbleCompactTailless(), capInsets: UIEdgeInsets.zero))
            masker?.applyIncomingBubbleImageMask(toMediaView: imageView)
            
            return imageView
        }
        
        return nil
    }
}
```

**Comment by l3irdWings** [comment]
My completed subclass for update media item tailess

`class PhotoMediaItem: JSQPhotoMediaItem {
    
    var cachedImageView: UIImageView?
    var cachedPlaceholderView: UIView?
    
    override func mediaViewDisplaySize() -> CGSize {
        var screenSize = UIScreen.main.bounds.width
        guard let image = image else {
            return CGSize(width: screenSize * 0.80, height: screenSize * 0.80 * 0.66)
        }
        
        if image.size.width >= image.size.height {
            screenSize = screenSize * 0.80
        }
        else {
            screenSize = screenSize * 0.65
        }
        let resizeFactor = image.size.width / screenSize
        
        return CGSize(width: image.size.width/resizeFactor, height: image.size.height/resizeFactor)
    }

    override func mediaView() -> UIView? {
        if image == nil {
            return nil
        }
        
        if cachedImageView == nil {
            let size = self.mediaViewDisplaySize()
            let imageView = UIImageView(image: image)
            imageView.frame = CGRect(x: 0, y: 0, width: size.width, height: size.height)
            imageView.contentMode = .scaleAspectFill
            imageView.clipsToBounds = true
            let masker = JSQMessagesMediaViewBubbleImageMasker(bubbleImageFactory: JSQMessagesBubbleImageFactory(bubble: UIImage.jsq_bubbleCompactTailless(), capInsets: UIEdgeInsets.zero))
            if appliesMediaViewMaskAsOutgoing {
                masker?.applyOutgoingBubbleImageMask(toMediaView: imageView)
            }
            else {
                masker?.applyIncomingBubbleImageMask(toMediaView: imageView)
            }
            
            cachedImageView = imageView
        }
        
        return cachedImageView
    }
    
    override func mediaPlaceholderView() -> UIView! {
        if cachedPlaceholderView == nil {
            let size = mediaViewDisplaySize()
            let view = JSQMessagesMediaPlaceholderView.withActivityIndicator()
            view?.frame = CGRect(x: 0, y: 0, width: size.width, height: size.height)
            let masker = JSQMessagesMediaViewBubbleImageMasker(bubbleImageFactory: JSQMessagesBubbleImageFactory(bubble: UIImage.jsq_bubbleCompactTailless(), capInsets: UIEdgeInsets.zero))
            if appliesMediaViewMaskAsOutgoing {
                masker?.applyOutgoingBubbleImageMask(toMediaView: view)
            }
            else {
                masker?.applyIncomingBubbleImageMask(toMediaView: view)
            }
            cachedPlaceholderView = view
        }
        
        return cachedPlaceholderView
    }
    
}`

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
