### ISSUE TITLE
Keyboard Issues in ios 8.4

### ISSUE THREAD

**Issue by psopher** [jessesquires/JSQMessagesViewController#1171]
Hi Jesse,

First I'd like to thank you for making such an awesome program. I really appreciate all the work you do.

I'm having one issue though. It is related to #1076, but it isn't exactly the same. 

When I close out of the jsqmessages view controller in ios 8.2 and then re-enter the same conversation, everything works perfectly. However, on my iphone, when I close out of the jsqmessages view controller and re-enter, the keyboard no longer has a textview or send button. When I manually drag down the keyboard before leaving the view in ios 8.4, I can re-enter the conversation, and everything will work. It sounds like resignFirstResponder is working in ios 8.2 but not in ios 8.4. Below is a picture of what it looks like when I re-enter. Any ideas?

![screen shot 2015-08-21 at 11 08 56 am](https://cloud.githubusercontent.com/assets/10428964/9411626/10185086-47f5-11e5-9490-92519eebc6d9.png)

**Comment by ferrettmerr** [comment]
@psopher I ran into this problem today and took a shot at debugging it. In your View Controller that subclasses JSQMessagesViewController do you override viewDidAppear? If you do make sure you call super inside it! I had the exact same issue as you and this fixed it for me.

**Comment by jessesquires** [comment]
thanks @ferrettmerr !
