### ISSUE TITLE
Cancel "Interactive Pop Gesture" to get into a bad state

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#1174]
@jessesquires 

I've encountered a 100% reproducible way to:
1. Have the scroll to dismiss keyboard stop working
2. Have the input toolbar detach from the keyboard

<img width="188" alt="screen shot 2015-08-24 at 1 58 16 pm" src="https://cloud.githubusercontent.com/assets/4912283/9452292/3a2decee-4a68-11e5-96e0-6147ae936d90.png">

Steps:
1. Pop up keyboard
2. pull down (to hide) the predictive text
3. switch to emoji keyboard
4. start the interactive pop gesture
5. cancel the interactive pop gesture (do not finish)

Results:
1. keyboard reset to A-Z, but predictive doesn't reappear, so the toolbar floats detached from keyboard
2. scroll to dismiss the keyboard will not function

*fortunately* I know exactly why this is happening.
The fix for #257 introduced this behavior.

Regarding #257
@cswelin 
>when called from the viewDidDisappear doesn't actually remove the target action as the navigationController is nil by this point.

Great detective work there!

How does the fix for #257 (acb32dc8ae99) cause the issue?

The Interactive Pop gesture recognizer calls viewWillDisappear.
With this change, viewWillDisappear removes our action on the interactive pop gesture recognizer after the Begin state so we never get any changed/ended/cancel states.

Then if the user cancels the Interactive Pop, we do not get the notification.

There is some important logic that goes on in jsq_handleInteractivePopGestureRecognizer under the switch case of UIGestureRecognizerStateCancelled & UIGestureRecognizerStateFailed.

Could we resolve #257 & this issue by capturing the navigationViewController (or the interactivePopGestureRecognizer) at the time we addTarget and then remove-target at viewDidDisappear time ?

**Comment by walsh2000** [comment]
FWIW... the Emoji keyboard step is not required to break the scroll-to-dismiss., so please don't pigeon hole this as a "super rarely happens" bug. As often as the interactive pop gesture is cancelled, the JSQ VC is left in a broken state.

**Comment by jessesquires** [comment]
Thanks @walsh2000 ! :smile: :tada:
