### ISSUE TITLE
Proper way to Refresh the messages view

### ISSUE THREAD

**Issue by dpreston10** [jessesquires/JSQMessagesViewController#1178]
Love this product...

Im using it in a Swift project. I have a button that toggles out to another view and based upon the choices selected, upon returning to the messages view I need to refresh the list of messages.

How should I do this?

**Comment by jessesquires** [comment]
Thanks @dpreston10 !

Simply calling `reloadData` sounds like what you need

**Comment by dpreston10** [comment]
Thats what I thought too but when I do  self.collectionView.reloadData() where collectionView is JSQMessagesCollectionView does not refresh as I would expect it to
