### ISSUE TITLE
is not a valid initializer for JSQMessagesBubbleImage error

### ISSUE THREAD

**Issue by orkhanalizade** [jessesquires/JSQMessagesViewController#1179]
I connect the framework, like:

class MessagesViewController: JSQMessagesViewController {
    var outgoingBubleImage = JSQMessagesBubbleImage()
}

but it prints the next error:

is not a valid initializer for JSQMessagesBubbleImage. Use initWithMessageBubbleImage:highlightedImage: instead.'
Why this error appears?

**Comment by jessesquires** [comment]
Thanks @orkhanalizade !

Yep, use the initializer specified in the error message. :smile:

**Comment by orkhanalizade** [comment]
@jessesquires how? Can you tell me which form to use?
