### ISSUE TITLE
Tailless Message Bubble for Media Messages

### ISSUE THREAD

**Issue by mohonish** [jessesquires/JSQMessagesViewController#1180]
Is it possible to set the `jsq_bubbleRegularTaillessImage()` for media messages as well? I have implemented the tailless bubbles for normal chat messages but for media items, it always has a tail. Is there any way we can override that? Am I missing anything?

Thanks in advance!
And kudos to @jessesquires for this wonderful library!

**Comment by eliburke** [comment]
I'm going to go out on a limb and say this is related to #1168. For the 7.x releases you will probably need to create your own media object in order to remove the tails.

**Comment by mohonish** [comment]
@eliburke ah! you're right. I was expecting there should be some way since I could have tail less text chat messages.

On a related note, do you think we can adjust the insets of the media bubbles such that the media item does not cover up the entire bubble area?

**Comment by MHX792** [comment]
Any progress on this one? Is there a way to remove the tail in `7.3.2` without creating own media object?

**Comment by eliburke** [comment]
The reason the media bubbles have tails is the implementation of JSQMediaItem's mediaPlaceholderView which calls `[JSQMessagesMediaViewBubbleImageMasker applyBubbleImageMaskToMediaView:view isOutgoing:self.appliesMediaViewMaskAsOutgoing];`. 

That class method uses the default constructor of JSQMessagesBubbleImageFactory, which is hard coded to use jsq_bubbleCompactImage, which has a tail.  If you subclass JSQPhotoMediaItem you can write your own mediaPlaceholderView. 

If you are comfortable with method swizzling, you can create a category in your subclass that will modify the image at runtime to one with no tail:
```
// swizzle in our bubble mask for images
@implementation JSQMessagesBubbleImageFactory (change_mask)

+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [SwizzUtils swizzle:[self class] originalSelector:@selector(init) swizzledSelector:@selector(my_init)];
    });
}

- (instancetype)my_init {
    // this is my own image; you can use your own or any of the predefined ones available in UIImage+JSQMessages.h
    return [self initWithBubbleImage:[UIImage imageNamed:@"chat_bubble_tailless"] capInsets:UIEdgeInsetsZero]; 
}

@end
```
Here's the definition of swizzle, which I pulled out of one of the many implementations available online. Possibly ( https://github.com/rentzsch/jrswizzle ) Understand and use at your own risk:
```
#import <sys/utsname.h>
#import <objc/runtime.h>

+ (void)swizzle:(Class)swizzledClass originalSelector:(SEL)originalSelector swizzledSelector:(SEL)swizzledSelector {
    Method originalMethod = class_getInstanceMethod(swizzledClass, originalSelector);
    Method swizzledMethod = class_getInstanceMethod(swizzledClass, swizzledSelector);
    
    BOOL didAddMethod = class_addMethod(swizzledClass,
                                        originalSelector,
                                        method_getImplementation(swizzledMethod),
                                        method_getTypeEncoding(swizzledMethod));
    if (didAddMethod) {
        class_replaceMethod(swizzledClass,
                            swizzledSelector,
                            method_getImplementation(originalMethod),
                            method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, swizzledMethod);
    }
}
```

**Comment by MHX792** [comment]
Thank you for your answer!

**Comment by eliburke** [comment]
@MHX792 you're welcome.
Please let me re-iterate that anyone using this solution needs to understand what it is doing. This specific example replaces the default init method with a new one. If a future version of the library changes the default init method, IT STILL WILL NOT BE CALLED, possibly leading to unexpected or buggy behavior.

**Comment by antonverhoeven32** [comment]
how can I remove tail of media cell in Swift?

**Comment by antonverhoeven32** [comment]
@eliburke could you please let me know how I can use your solution in Swift project?
