### ISSUE TITLE
Voice dictation is aborted if the message is received while dictating

### ISSUE THREAD

**Issue by Marindrew** [jessesquires/JSQMessagesViewController#1182]
When the message is received ( and `[self.collectionView reloadData]` is called) , the standard iOS keyboard voice to text dictation (speech recognition) is aborted.

I have to press voice dictation button again to continue dictation. Seems to be that textView is reloaded when `[self.collectionView reloadData]` is called.

(similarly, if the Copy/Delete menu is opened and the user receives the message, the Copy/Delete menu will be closed)

Is there any way I can reload only once cell in collectionView or I have to reload the whole collectionView?

Library version - 
iOS version iOS 8.4
Devices affected - iPhone 6

Thanks

**Comment by jessesquires** [comment]
you can call `reloadItemsAtIndexPaths:` on collection view
