### ISSUE TITLE
Is there any way to implement swipe up to show keyboard?

### ISSUE THREAD

**Issue by hermanccw** [jessesquires/JSQMessagesViewController#1184]
Hi all,

I know that JSQ allow user to swipe down to dismiss keyboard, but is there a way to swipe up to show keyboard when the view is first presented?

I am modifying JSQMessagesKeyboardController's ```jsq_handlePanGestureRecognizer``` method and calling ```[self.textView becomeFirstResponder]``` when ```keyboardView``` is hidden or height is 0 (I am grabbing the keyboardView by looping through the window tree).  But that seems to just show the keyboard immediately and not respect the animation (frame change) in the method.

I am basically trying to mimic what Facebook Messenger do, but I think they can do that since once you get into the chat view, the first thing they do is to show a keyboard by focusing on the text field, therefore, it can get the keyboard view and it's height and not call becomeFirstResponder again during the panGesture change.

My requirement is to not show keyboard when I get into the chat view, does any one of you know if that's possible at all?

**Comment by jessesquires** [comment]
Hey @hermanccw - what exactly do you want to achieve here?

Currently, the library doesn't support "swipe up to show the keyboard". Pull requests are welcome though :smile:
