### ISSUE TITLE
Saving text input when exiting and re-entering the view controller?

### ISSUE THREAD

**Issue by jeremyeic** [jessesquires/JSQMessagesViewController#1185]
Hi,

I was wondering if there was any way to save typed text in the input toolbar when exiting and re-entering the view controller, so that whatever the user has typed does not disappear every time they exit.

**Comment by harlanhaskins** [comment]
Just keep a reference to the view controller instead of creating a new one.

**Comment by jeremyeic** [comment]
Sorry I am quite new to app development and swift, so how would you do that using the default push segue? Thanks for the help!

**Comment by jessesquires** [comment]
Actually, it would be better to save this elsewhere, then load that text via `viewWillAppear:` or `viewDidAppear:`

**Comment by gcarlo89** [comment]
@jeremyeic in my case I store the text using `NSUserDefaults` (e.g. key -> `[NSString stringWithFormat:@"conversationId:%@", convId]`), it suits me just fine. Just remember to set if after `[super viewDidAppear:animated]` otherwise the textview won't resize.

**Comment by jeremyeic** [comment]
what property of the input toolbar would you set in order to do this?

Thanks everyone for the answers

**Comment by gcarlo89** [comment]
@jeremyeic  there's your textview `[self.inputToolbar.contentView.textView setText:@"testing"];`
