### ISSUE TITLE
JSQMessages collectionView not responding correctly to reload data

### ISSUE THREAD

**Issue by dpreston10** [jessesquires/JSQMessagesViewController#1186]
See https://github.com/jessesquires/JSQMessagesViewController/issues/1178 

When I return from my navigation controller and issue 

            dispatch_async(dispatch_get_main_queue()) {
                self.collectionView.reloadData()
            }

in my viewDidAppear it loads the new data but keeps the original data as well.

How can I get the messages view to completely refresh and load entirely new data?

**Comment by jessesquires** [comment]
Hey @dpreston10 :smile: 

This doesn't sound like an issue with the library, but perhaps something in your specific project?

If you can reproduce this with the demo app, please paste a link here. If not, I would try asking this on StackOverflow instead. :+1:

**Comment by gcarlo89** [comment]
@dpreston10 Are you removing the old data from the collectionview's data source before calling `reloadData`?
