### ISSUE TITLE
JSQMessagesInputToolbar preferredDefaultHeight error

### ISSUE THREAD

**Issue by orkhanalizade** [jessesquires/JSQMessagesViewController#1187]
Hi. Why I get the next error:

    [JSQMessagesInputToolbar preferredDefaultHeight]: unrecognized selector sent to instance 0x7ffde2e73c70
     *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[JSQMessagesInputToolbar preferredDefaultHeight]: unrecognized selector sent to instance 0x7ffde2e73c70'

It happens when I use:

    class MessagesViewController: JSQMessagesViewController {

How can I fix this error? I searched a lot, but nothing helps me. Thanks in advance!

**Comment by jessesquires** [comment]
hey @orkhanalizade - maybe you need to `import` the library or update to the latest version?

**Comment by orkhanalizade** [comment]
@jessesquires I've updated my framework like

`pod "JSQMessagesViewController", "~> 7.1.0"`

but after update I get the next errors:

`failed to import bridging header '/Users/orkhanalizade/Desktop/messenger/Messenger-Bridging-Header.h'`

and 

`'GCDAsyncSocket.h' file not found`

Why?

**Comment by jessesquires** [comment]
`GCDAsyncSocket.h` is not part of this library
