### ISSUE TITLE
Cocoapods update

### ISSUE THREAD

**Issue by jdgong** [jessesquires/JSQMessagesViewController#1191]
Hi 

Just to check how often do you update the cocoa pods version? I have been using pod but there are some committed features from last version missing.

Thanks!

**Comment by jessesquires** [comment]
Hey @jdgong :smile: 

I try to work on this project as much as I can. You can stay up-to-date by checking out the milestones:
https://github.com/jessesquires/JSQMessagesViewController/milestones
