### ISSUE TITLE
Disable dismiss keyboard during scrolling 

### ISSUE THREAD

**Issue by GuyKahlon** [jessesquires/JSQMessagesViewController#1192]
Hi,

I would like to disable the ability to dismiss the keyboard when the user scrolling.
I added the code:
at JSQMessagesViewController
collectionView.keyboardDismissMode = .None

But, nothing is changed.
I wonder if it's possible to do it.

Thanks,
Guy

**Comment by jessesquires** [comment]
Hey @GuyKahlon :smile: 

To do this, you can listen to the `UIScrollViewDelegate` events and dismiss the keyboard manually.

**Comment by TheEngineerz** [comment]
@GuyKahlon how did you disable this ability can you please share the code?
