### ISSUE TITLE
First message on the bottom!

### ISSUE THREAD

**Issue by Bashta** [jessesquires/JSQMessagesViewController#1193]
Hello! Since i can not find this anywhere in the documentation or examples! Is there a way to show the first message on the bottom on the view?

**Comment by nolim1t** [comment]
Trying to find out the answer for this too

**Comment by jessesquires** [comment]
Hey @Bashta / @nolim1t :smile: 

You could reverse the data in your data source and insert new messages / collection view cells at index 0.

**Comment by Bashta** [comment]
Hello! Thank you for the response but the question was about putting the first bubble at the bottom of the screen rather than reversing the order in which the messages are shown.

**Comment by nolim1t** [comment]
Thanks for that

**Comment by gnrcampos** [comment]
@Bashta did you solve that? I'm having a problem that could be solved this way...
@jessesquires I guess he doesn't want to invert the messages order from top->bottom to bottom->top, he (and I) want that, in case the chat doesn't have enough messages to cover the whole screen, the empty space is shown in the top of the collection view instead of the bottom.

**Comment by Bashta** [comment]
@gnrcampos Yeah! Already solved this couple of days after i posted the last msg.

**Comment by gnrcampos** [comment]
@Bashta can you share your solution or explain what you did then?

**Comment by Bashta** [comment]
@gnrcampos Unfortunately i do not have access to that repo anymore, but what i did basically is :
Imported the pod as 3rd party lib and modified the tableview inside it in order to show the first message at the bottom of the screen via constraints. Very dirty solution but did the job.

**Comment by yesiammark** [comment]
Is there any solution?

**Comment by eliburke** [comment]
There is a patch to add an "Inverted Mode" (issue #665) . Unfortunately, Jesse seems pretty set against adding the feature to the core library so you're on your own for incorporating it.
