### ISSUE TITLE
Can I use my own storyboard (UIViewcontroller) and a table view inserted and just display the text input bar?

### ISSUE THREAD

**Issue by hongseung92** [jessesquires/JSQMessagesViewController#1194]
Hi Jesse, 

Thanks for your great work. I really appreciate it.

I was wondering if I could jsut use the textinputbar for my project? is this a possibility? my app is not a messenger app but social media where people can comment on posts. I have a detailsviewcontroller where I want to have the comments input bar.. so wondering if I could use your work for my project.

any help would be appreciated. thanks!

**Comment by devos50** [comment]
I have the same question. I'm working on a messaging app but I would like to use a regular UITableView with some custom rows created in Interface Builder.

**Comment by jessesquires** [comment]
Hey @hongseung92 / @devos50 - you probably could, but installing through cocoapods would bring in the entire library.

In the future, it would be great to break up all components into separate pods/repos. Unfortunately, I don't have time for this now.
