### ISSUE TITLE
Having problems Incorporating JSQMessages into Swift 2.0

### ISSUE THREAD

**Issue by JordanRoPo** [jessesquires/JSQMessagesViewController#1196]
Anybody unable to import this library into their project due to mass amounts of errors?

**Comment by juliensaad** [comment]
I haven't had any trouble importing it through CocoaPods, although the Firebase examples are both outdated and don't support Swift 2.0.

**Comment by juliensaad** [comment]
Also make sure you have version 0.38 of Cocoapods or higher by running
`gem install cocoapods --pre`

**Comment by jessesquires** [comment]
Thanks @juliensaad !

Also, `gem install cocoapods` should be fine. The 0.38.2 is out.

**Comment by JordanRoPo** [comment]
The solution to the problem I was having was to explicitly write an Import statement at the top of each of the files using JSQMessages. Where as before I used a bridging header. Hope this can help someone else

**Comment by erickva** [comment]
This does not work for me either.
I have a bridging file with:
#import <JSQSystemSoundPlayer/JSQSystemSoundPlayer.h>
#import <JSQMessagesViewController/JSQMessages.h>

Then in my MessagesViewController.swift I have:
import JSQMessagesViewController

And I get the following error:
No such module 'JSQMessagesViewController'

I don't have use_frameworks enabled in my Podfile

**Comment by mehmetsen80** [comment]
I also have the same issue... I need to use the use_framework! in my podfile because I have other objective-c libraries.. Even I import it modular in my pod file, it won't work.. `#import <JSQMessagesViewController/JSQMessagesViewController.h>`

What's the workaround of this?
