### ISSUE TITLE
Text For MessageBubble TopLabel show up at opposite side

### ISSUE THREAD

**Issue by jdgong** [jessesquires/JSQMessagesViewController#1197]
Hi 

I have this issue that the MessageBubble TopLabel showing up at opposite side, as seen in the picture:

![capture](https://cloud.githubusercontent.com/assets/13582137/9818535/c59e5502-586e-11e5-88d3-452a5eb22439.PNG)

The outgoing property is right and you can see the message bubbles themselves are well positioned, but the top label is all on the opposite side. I am using the cocoapods version. Is this a bug that have already been fixed, or is there something I missed. Please help!

**Comment by harlanhaskins** [comment]
Could you post some code?

**Comment by jdgong** [comment]
It's the basic code: 

    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        
        var message = self.messages[indexPath.item]
        return JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate(message.date)
    }

    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        var cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        var message = self.messages[indexPath.item]
        if message.senderId == self.senderId {
            cell.textView?.textColor = UIColor.whiteColor()
        } else {
            cell.textView?.textColor = UIColor.blackColor()
        }
        return cell
    }

**Comment by jdgong** [comment]
The issue seems to lie in  JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate

When I use just displayname, it shows up fine. I wonder what the attributedtimestapfordate changed

**Comment by jdgong** [comment]
Figured out the workable code:

return NSAttributedString(string: JSQMessagesTimestampFormatter.sharedFormatter().timestampForDate(message.date))

This looks weird to use a string and convert to NSAttributedString. There should be fix to enable direct use of attributedTimestampForDate

**Comment by jessesquires** [comment]
Thanks @jdgong !

Feel free to submit a PR :smile:
