### ISSUE TITLE
Position avatar at top of message bubble

### ISSUE THREAD

**Issue by joshuawilde** [jessesquires/JSQMessagesViewController#1198]
Thanks for the awesome library!

I created my own message bubble images and have implemented them and now I'd like to move the avatar image to the top of the bubble instead of the bottom (where it is now). What would you suggest I do?

**Comment by jessesquires** [comment]
Hey @joshuawilde :smile: 

It currently has a constraint that pins it to the bottom of the superview. You should be able to simply pin it to the top. :+1:

**Comment by joshuawilde** [comment]
Awesome. It worked. Thanks!

**Comment by fabriziopera** [comment]
Hi, how can i change this constraint? Do you have an example code that works?

**Comment by b-e-r-t-o** [comment]
@jessesquires @joshuawilde Could you post a sample of how you made this work?

I feel like this could be really useful.

**Comment by templeman15** [comment]
@b-e-r-t-o @fabriziopera 

Here is what I did: 

1. Copy the nibs from pods -> JSQMessagesViewController -> Resources -> and grabbed the cell incoming and outgoing nibs, paste them into my project. 

2. Rename the files to "JSQMessagesCollectionViewCellIncomingAvatarTop" and "JSQMessagesCollectionViewCellOutgoingAvatarTop" respectively 

3. In each cells nib, remove the bottom constraint on the avatar container and then move the container towards the top and set a new top constraint that replaced the bottom constraint.  

4. Set the re-use identifier on each nib respectively in IB to JSQIncoming, JSQOutgoing

5. In your controller where you subclass JSQMessagesViewController, set the following: 

`  self.collectionView?.registerNib(UINib(nibName: "JSQMessagesCollectionViewCellIncomingAvatarTop", bundle: nil), forCellWithReuseIdentifier: "JSQIncoming")
        self.collectionView?.registerNib(UINib(nibName: "JSQMessagesCollectionViewCellOutgoingAvatarTop", bundle: nil), forCellWithReuseIdentifier: "JSQOutgoing")
        
        self.incomingCellIdentifier = "JSQIncoming"
        self.outgoingCellIdentifier = "JSQOutgoing"`

**Comment by eliburke** [comment]
@templeman15 thanks for the example!

**Comment by Benny-iPhone** [comment]
don't forget to handle media messages if you need

```
self.incomingMediaCellIdentifier = "JSQIncoming"
self.outgoingMediaCellIdentifier = "JSQOutgoing"
```
