### ISSUE TITLE
Wrong message width when loaded with already present messages

### ISSUE THREAD

**Issue by ypopovych** [jessesquires/JSQMessagesViewController#1200]
Controller works fine when messages arrived from API. But if controller closed and recreated with some already present messages - message line count changed to 2. So message width greater than collection view.
There is a screenshot of a problem
![ios simulator screen shot sep 13 2015 15 59 05](https://cloud.githubusercontent.com/assets/1133713/9836837/14ff0ad8-5a31-11e5-9b61-d793a0284878.png)
How this can be fixed?
Thanks,
Yehor

**Comment by jessesquires** [comment]
Hey @ypopovych -- sounds like you need to invalidate the layout / clear the layout cache

**Comment by Yostra** [comment]
@jeffreyjackson  How do you clear layout cashe?

**Comment by ypopovych** [comment]
Use `JSQMessagesCollectionViewFlowLayoutInvalidationContext` with `[collectionView.collectionViewLayout invalidateLayoutWithContext:]`. Create context object, setup BOOL values to YES and run method with this context.
