### ISSUE TITLE
Customizing Cell

### ISSUE THREAD

**Issue by dharmikvyas** [jessesquires/JSQMessagesViewController#1202]
Hi,

I am trying to customize cell like this.

override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        var cell:JSQMessagesCollectionViewCell = ([super.collectionView(collectionView, cellForItemAtIndexPath: indexPath)] as! JSQMessagesCollectionViewCell)!;        
        return cell;        
    }

I have seen this works in Objective c (I haven't tried), but not working in swift. It gives error and warnings.
Warning : Cast from UICollectionViewCell to unrelated type JSQMessagesCollectionViewCell always fails

Error: Could not cast value of type 'Swift._SwiftDeferredNSArray' (0x106d15ac0) to 'JSQMessagesCollectionViewCell' (0x103e93b50).

I want to change some text attributes like color, fonts etc.

**Comment by maxkonovalov** [comment]
@dharmikvyas in your code you are trying to create an array with one cell and then cast it to cell type which of course always fails. Try this:
```swift
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
    let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
    // change attributes here...
    return cell
}
```

**Comment by jessesquires** [comment]
thanks @maxkonovalov
