### ISSUE TITLE
How to move avatarContainerView

### ISSUE THREAD

**Issue by z8323664** [jessesquires/JSQMessagesViewController#1204]
Hello, thank you very much for your library! 

In JSQMessagesCollectionViewCell.m, I want to move the avatarContainerView to the bottom of the cellTopLabel, not the bottom of the cell. What should I do?

/**
 *  Returns the avatar container view of the cell. This view is the superview of the cell's avatarImageView.
 *
 *  @discussion You may customize the cell by adding custom views to this container view.
 *  To do so, override `collectionView:cellForItemAtIndexPath:`
 *
 *  @warning You should not try to manipulate any properties of this view, for example adjusting
 *  its frame, nor should you remove this view from the cell or remove any of its subviews.
 *  Doing so could result in unexpected behavior.

**Comment by jessesquires** [comment]
Hey @z8323664 - see #1198

**Comment by z8323664** [comment]
OK , This problem has been solved
thanks
