### ISSUE TITLE
how to present the "delete" action

### ISSUE THREAD

**Issue by rvilches** [jessesquires/JSQMessagesViewController#1205]
Hi guys , first I have to congratulate and thank you for this excellent project. I am having trouble when I try to present the menu if a message is selected. I want the copy and delete actions but the "delete" does not appear.
here is the code that i am using as example
: 
- (BOOL)collectionView:(UICollectionView *)collectionView canPerformAction:(SEL)action forItemAtIndexPath:(NSIndexPath *)indexPath withSender:(id)sender
{
    if (action == @selector(copy:) || action == @selector(delete:)) {
        return YES;
    }

    return NO;
}

**Comment by jessesquires** [comment]
see the 7.2.0 release notes
https://github.com/jessesquires/JSQMessagesViewController/releases/tag/7.2.0
