### ISSUE TITLE
data detected links don’t display with an underline

### ISSUE THREAD

**Issue by littlebobert** [jessesquires/JSQMessagesViewController#1206]
Sorry I must just be missing something here. Running iOS 9 GM but iOS 8.4.1 reproduces as well. Data detected links don’t display with an underline.

Here’s my collectionView(:, cellForItemAtIndexPath:):

https://gist.github.com/littlebobert/32ee9a11bab3f71a3373

**Comment by harlanhaskins** [comment]
You need to use `NSUnderlineStyleAttributeName`.

```
textView.linkTextAttributes = [
    NSForegroundColorAttributeName: UIColor.whiteColor(),
    NSUnderlineStyleAttributeName: NSUnderlineStyle.StyleSingle.rawValue
]
```

**Comment by littlebobert** [comment]
thanks!

**Comment by jessesquires** [comment]
thanks @harlanhaskins ! :smile:
