### ISSUE TITLE
Keyboard coveres textfield

### ISSUE THREAD

**Issue by SimonaMilchevska** [jessesquires/JSQMessagesViewController#1209]
Hi. I am facing the issue that the keyboard is not following the input toolbar. I am calling [super viewDidAppear] ... and nothing changes. 
Moreover, i removed the code where [super viewDidAppear] is called from the demo, and the keyboard is working perfectly without this method:

 - (void)viewDidAppear:(BOOL)animated
 {
    [super viewDidAppear:animated];
    /**
   *  Enable/disable springy bubbles, default is NO.
   *  You must set this from `viewDidAppear:`
   *  Note: this feature is mostly stable, but still experimental
   */
  //self.collectionView.collectionViewLayout.springinessEnabled = [NSUserDefaults springinessSetting];
}

I know this is a duplicate, but in my case, the proposed solution is not solving my problem. 
Other possible solutions?
In iOS 8, in every simulator size.
![keyboard](https://cloud.githubusercontent.com/assets/5775060/9978498/b3065762-5f32-11e5-82c8-502e3ddfaa9b.png)

**Comment by SimonaMilchevska** [comment]
![keyboard](https://cloud.githubusercontent.com/assets/5775060/9978496/a55131aa-5f32-11e5-875c-e8cf656c8934.png)

**Comment by jessesquires** [comment]
Hey @SimonaMilchevska :smile: 

You should be calling `super` on **all** view lifecycle methods.

**Comment by SimonaMilchevska** [comment]
Hi, 
my code is exactly the same like the code from the demo project. Still in the demo works perfectly, in project the keyboard behaves different.

**Comment by SimonaMilchevska** [comment]
- (void)keyboardController:(JSQMessagesKeyboardController *)keyboardController keyboardDidChangeFrame:(CGRect)keyboardFrame
    {
        if (![self.inputToolbar.contentView.textView isFirstResponder] &&     self.toolbarBottomLayoutGuide.constant == 0.0f) {
            return;
     }

        CGFloat heightFromBottom = CGRectGetMaxY(self.collectionView.frame) -     CGRectGetMinY(keyboardFrame);

        heightFromBottom = MAX(0.0f, heightFromBottom + 40);  <----- here

        [self jsq_setToolbarBottomLayoutGuideConstant:heightFromBottom];
     } 

heightFromBottom = MAX(0.0f, heightFromBottom + 40);  added +40 here. Is this telling you something, what can be causing the issue?

**Comment by SimonaMilchevska** [comment]
ok, now i got it. Once i did some changes on the JSQMessagesViewController and the constraints where messed up :)

Problem solved! :+1:

**Comment by babac87** [comment]
"You should be calling super on all view lifecycle methods." solved my problem.
Added scrollToBottomAnimated in viewDidAppear, but didn't called super.viewDidAppear(animated).

Thx Jesse

**Comment by sree127** [comment]
Hey. Even I've the same issue. I'm calling super on every life cycle methods and I'm still not able to solve this? can someone please help?

I noticed the textview gets hidden only when I open the app from notification & otherwise it works like charm. Really weird.
