### ISSUE TITLE
Swift 2 & Xcode 7 - messageBubbleFont issue

### ISSUE THREAD

**Issue by Jamonek** [jessesquires/JSQMessagesViewController#1210]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: messageBubbleFont != nil'

Before upgrading to Swift 2 and Xcode 7, I've never had this issue until I upgraded. Where should I add the call to set the font?

**Comment by jessesquires** [comment]
Hey @Jamonek :smile: 

The error message should tell you from which file this occurred. You'll want to make sure this property is set on the layout object.

**Comment by davepatterson** [comment]
I had the same error after updating to Swift 2 & Xcode 7. It seems to stem from the JSQMessageViewController springiness as setting springinessEnabled to false fixes the issue.

**Comment by jessesquires** [comment]
Thanks all! :smile: 

Now tracking this at #1338.
