### ISSUE TITLE
messageDataForItemAtIndexPath seems to be getting called 4-10 times for each item

### ISSUE THREAD

**Issue by mypark** [jessesquires/JSQMessagesViewController#1211]
I was implementing the photo media item and noticed some extreme performance issues.  When I started debugging I noticed that `messageDataForItemAtIndexPath` was getting called 4 times for each item, whereas in another sample project I set up it was being called 10 times

Here's a dummy project I set up to test and it's calling each item 10 times even though there is only one message item.  

This was causing problems for me as that's the function where I start my async download of media photos and calling the download media request 10 times for each item was causing problems for me.

Am I mis-understanding something basic here?

```
import UIKit
import JSQMessagesViewController

class ViewController: JSQMessagesViewController {

    var messages = [JSQMessage]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.senderId = "1"
        self.senderDisplayName = "me"
        let message = JSQMessage(senderId: "admin", displayName: "Admin", text:"hello from admin")
        self.messages.append(message)
    }

    
    override func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return self.messages.count
    }
    
    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        return cell
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageBubbleImageDataSource! {
        return JSQMessagesBubbleImageFactory().incomingMessagesBubbleImageWithColor(UIColor.blueColor())
    }

    override func collectionView(collectionView: JSQMessagesCollectionView!, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageAvatarImageDataSource! {
        return nil
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, messageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageData! {
        
        //why is this called 10 times?
        
        let msg = self.messages[indexPath.item];
        let text = msg.text
        
        print(text + ":" + String(indexPath.item))
        
        return JSQMessage(senderId: msg.senderId, displayName: msg.senderDisplayName, text: text)

    }

}
```

This will output in the console

```
hello from admin:0
hello from admin:0
hello from admin:0
hello from admin:0
hello from admin:0
hello from admin:0
hello from admin:0
hello from admin:0
hello from admin:0
hello from admin:0
```

**Comment by harlanhaskins** [comment]
It asks the delegate for the message data many times by design. The cells get reused frequently -- `UICollectionView` manages it.

You can probably replace that whole function body with just `return self.messages[indexPath.item]`, too. You don't need to create a copy every time.

**Comment by mypark** [comment]
Ah ok then... will close this issue.

**Comment by jessesquires** [comment]
That's right. Thanks @harlanhaskins ! :smile:

**Comment by mypark** [comment]
BTW, if I want to set up asynchronous downloading of the media images - is there a recommended function or spot to call the callback?  Right now I have a subclass of JSQMessage that is asynchronously getting the UIImage from a url and I can expose an callback in that classes init... But is there a recommended way?
