### ISSUE TITLE
Wrong bubble width on iPad, iOS 9

### ISSUE THREAD

**Issue by oanaBan** [jessesquires/JSQMessagesViewController#1212]
When accessing Messages room with storyboard on iPad with iOS 9 (on both latest version of master branch and develop branch) the bubble width is wrong. Pls see the attached image.
![simulator screen shot 21 sep 2015 12 25 54](https://cloud.githubusercontent.com/assets/7047087/9988912/1c1fc564-605d-11e5-86ad-c70424f7504b.png)

This is not repro on iOS 8.

**Comment by harlanhaskins** [comment]
I've noticed this in some weird cases, too. Are there any constraint errors that pop up when this happens?

**Comment by Yostra** [comment]
when you go to split view on iPad air 2, same thing happens

**Comment by harlanhaskins** [comment]
Looking at this now, we really should respond to `-[UIViewController viewWillTransitionToSize:withTransitionCoordinator:]` and `-[UIViewController traitCollectionDidChange:]`.

This makes the split screen multitasking work nicely:

```objc
-(void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    context.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];
}

- (void)traitCollectionDidChange:(UITraitCollection *)previousTraitCollection {
    [super traitCollectionDidChange:previousTraitCollection];
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    context.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
}
```

Though the message bubbles are wrong at first load.
