### ISSUE TITLE
Can't find the file JSQSystemSoundPlayer

### ISSUE THREAD

**Issue by nabil-takla** [jessesquires/JSQMessagesViewController#1214]
I'm using pod install and I'm getting the error: 

can't open file: ......./Build/Products/Debug-iphonesimulator/Veniato-b.app/Frameworks/JSQSystemSoundPlayer.framework/JSQSystemSoundPlayer (No such file or directory)

Podfile: pod 'JSQMessagesViewController'
bridging file: #import "JSQMessagesViewController/JSQMessages.h"

I'd appreciate any clues to why I'm getting this error. I'm using Swift 2, iOS 9 and Xcode 7.0. Thanks!

**Comment by Dwar3xwar** [comment]
What version of Cocoapods are you using?

IIRC, the latest Cocoapods does not require a bridging header when mixing objc/swift dependencies. Simply add ```use_frameworks!``` at the top of your podfile.

**Comment by jessesquires** [comment]
Thanks @Dwar3xwar !
