### ISSUE TITLE
JSQVideoItem Thumbnail Property?

### ISSUE THREAD

**Issue by benjaminhallock** [jessesquires/JSQMessagesViewController#1220]
Why would anyone want to see a black image with a play button on it? 

As a workaround, I just use my personal thumbnail for a video with the `JSQPhotoItem`. Problem is I'd have to save the `fileURL`'s to an array to extract the correct `fileURL` according to the `objectId` of that message.

**Comment by Lucashuang0802** [comment]
@benjaminhallock we actually have implemented it here: #1823.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
