### ISSUE TITLE
Crash while loading messages

### ISSUE THREAD

**Issue by mastermyx** [jessesquires/JSQMessagesViewController#1222]
Hello :muscle::sunglasses::facepunch:, 
I add my custom VC, the same as the example VC but I load my messages. 
When the messages are loading, i have the following crash. 

```
 *** `Assertion failure in void _UIPerformResizeOfTextViewForTextContainer(NSLayoutManager *, UIView<NSTextContainerView> *, NSTextContainer *, NSUInteger)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIFoundation/UIFoundation-432/UIFoundation/TextSystem/NSLayoutManager_Private.m:1551
2015-09-24 17:04:40.912 Waydo[2075:1057862] <NSATSTypesetter: 0x136fb7100>: Exception Only run on the main thread! raised during typesetting layout manager <NSLayoutManager: 0x13807d800>
    1 containers, text backing has 0 characters
    Currently holding 0 glyphs.
    Glyph tree contents:  0 characters, 0 glyphs, 1 nodes, 64 node bytes, 0 storage bytes, 64 total bytes, 0.00 bytes per character, 0.00 bytes per glyph
    Layout tree contents:  0 characters, 0 glyphs, 0 laid glyphs, 0 laid line fragments, 1 nodes, 64 node bytes, 0 storage bytes, 64 total bytes, 0.00 bytes per character, 0.00 bytes per glyph, 0.00 laid glyphs per laid line fragment, 0.00 bytes per laid line fragment
, glyph range {0 0}. Ignoring...
*** Assertion failure in void _UIPerformResizeOfTextViewForTextContainer(NSLayoutManager *, UIView<NSTextContainerView> *, NSTextContainer *, NSUInteger)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIFoundation/UIFoundation-432/UIFoundation/TextSystem/NSLayoutManager_Private.m:1551
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only run on the main thread!'
````

I don't use any thread, so i dont know why I get this :(
Sometimes It doesn't happen when i use breakpoints, i have no idea why..

i'm on iOS9, xcode7.

Similar issue: https://github.com/jessesquires/JSQMessagesViewController/issues/1146 
but as i dont modify i dont understand. 

Any ideas guys? 
Thanks,
Arthur

**Comment by jessesquires** [comment]
Hey @mastermyx -- there must be some place in your code that you are modifying this *off* of the main thread.

**Comment by mastermyx** [comment]
Hi @jessesquires -- sorry im a beginner in objective-c, what do you mean by modifying this off? Because i only took the example and load my array of JSQMessages.

**Comment by mastermyx** [comment]
Ok I restarted and took the example again. All is working fine.
I'm adding [self loadSocket] at the end of the viewDidLoad and crashed again.
I finally find out that it was because I loaded my message in the callback of my socket. 


-(void)loadSocket
{
 self.socket = [[mySocket sharedSocket] socket];
     [[mySocket sharedSocket] joinFriend:self.userID];
    [self.socket on:@"sendMessage" callback:^(SIOParameterArray *args){
    if (args.count > 0)
    {
        NSDictionary *messagesDict = args[0];
        NSString *userID = [messagesDict objectForKey:@"userID"];
        [self.demoData.messages removeAllObjects];
        JSQMessage *msg =  [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdSquires
                                              senderDisplayName:kJSQDemoAvatarDisplayNameSquires
                                                           date:[NSDate distantPast]
                                                           text:@"Welcome to JSQMessages: A messaging UI framework for iOS."];
        JSQMessage *msg2 =  [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdSquires
                                               senderDisplayName:kJSQDemoAvatarDisplayNameSquires
                                                            date:[NSDate distantPast]
                                                            text:@"Welcome to JSQMessages: A messaging UI framework for iOS."];
        [self.demoData.messages addObject:msg];
         [self.demoData.messages addObject:msg2];
        [self.collectionView reloadData];   
    }}];

I can close this issue but if you guys have any advice to help me load this outside the callback, i'll take it :)
Thank you,
Arthur

**Comment by harlanhaskins** [comment]
@mastermyx Your `loadSocket` callback is bring run on a background thread, and you're attempting to reload the collection view on that background thread.

Replace this line:

`[self.collectionView reloadData];`

with:

```objc
dispatch_async(dispatch_get_main_queue(), ^{
    [self.collectionView reloadData];
});
```

That will ensure the collection view is only reloaded on the main thread.

**Comment by jessesquires** [comment]
Yep, that's correct. Thanks @harlanhaskins ! :smile:
