### ISSUE TITLE
Can't viewWillAppear on iOS 9 due to Unsatisfiable Constraints but only in fresh install of app

### ISSUE THREAD

**Issue by atroutt** [jessesquires/JSQMessagesViewController#1223]
:muscle::sunglasses::facepunch:

Only on a fresh install I am getting an error related to NSLayoutContstraints when trying to display my subclass of JSQMessagesViewController.

Weirdly, if you kill the app out of memory (not uninstall) everything is fine the next time you come back and try to open the chat.

Steps to reproduce
===============
* On a FRESH INSTALL of the app
* Try to open the chat window
* Get stuck on view will appear in JSQMessagesViewController and chat screen never appears. 

When I put in a breakpoint for UIViewAlertForUnsatisfiableConstraints it stops on [self.view layoutIfNeeded]; in viewWillAppear for JSQMessagesViewController:
![screen shot 2015-09-24 at 2 54 49 pm](https://cloud.githubusercontent.com/assets/37866/10083417/6b5ff56a-62cc-11e5-83fb-96d44ebafb73.png)

Environment
==========
* Using JSQMessagesViewController 7.2.0 (also tried 7.1.0, still had the issue)
* Built in XCode 7
* I CAN reproduce this on an iPhone 6 simulator with iOS 9.0  and iPod touch with iOS 9.0.1
* I CANNOT reproduce this issue on an iPhone 6 simulator with iOS 8.4

Error from console
=========
```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7ffcc3bfa760 h=--& v=--& H:[UIView:0x7ffcc3e14d30(0)]>",
    "<NSLayoutConstraint:0x7ffcc3bfb540 H:[UIView:0x7ffcc3b439b0(34)]>",
    "<NSLayoutConstraint:0x7ffcc3f024b0 H:[UIView:0x7ffcc3b83380(41)]>",
    "<NSLayoutConstraint:0x7ffcc3dec850 H:|-(8)-[UIView:0x7ffcc3b439b0]   (Names: '|':JSQMessagesToolbarContentView:0x7ffcc3d61e20 )>",
    "<NSLayoutConstraint:0x7ffcc3dec990 H:[UIView:0x7ffcc3b439b0]-(8)-[JSQMessagesComposerTextView:0x7ffcc1d66400]>",
    "<NSLayoutConstraint:0x7ffcc3dec9e0 H:[JSQMessagesComposerTextView:0x7ffcc1d66400]-(8)-[UIView:0x7ffcc3b83380]>",
    "<NSLayoutConstraint:0x7ffcc3deca80 H:[UIView:0x7ffcc3b83380]-(8)-|   (Names: '|':JSQMessagesToolbarContentView:0x7ffcc3d61e20 )>",
    "<NSLayoutConstraint:0x7ffcc3d71c80 JSQMessagesInputToolbar:0x7ffcc3870ac0.leading == JSQMessagesToolbarContentView:0x7ffcc3d61e20.leading>",
    "<NSLayoutConstraint:0x7ffcc3d91c10 H:[JSQMessagesToolbarContentView:0x7ffcc3d61e20]-(0)-|   (Names: '|':JSQMessagesInputToolbar:0x7ffcc3870ac0 )>",
    "<NSLayoutConstraint:0x7ffcc3e151c0 H:[JSQMessagesInputToolbar:0x7ffcc3870ac0]-(0)-|   (Names: '|':UIView:0x7ffcc3e14d30 )>",
    "<NSLayoutConstraint:0x7ffcc3e15210 H:|-(0)-[JSQMessagesInputToolbar:0x7ffcc3870ac0]   (Names: '|':UIView:0x7ffcc3e14d30 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7ffcc3f024b0 H:[UIView:0x7ffcc3b83380(41)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by atroutt** [comment]
Not sure if this will surprise anyone, but I did pull down the JSQMessagesViewController sample app for the 7.2.0 release and COULD NOT reproduce the issue.

**Comment by jessesquires** [comment]
@atroutt thanks so much! :muscle: :heart: :+1: 

Looks like auto-layout behavior has changed in iOS 9. Which isn't surprising because every iOS release since iOS 7 has broken something :smile: 

Interesting that the demo doesn't reproduce this. Are you loading a lot of messages? Or none?

>I think this is one of the best reports anyone has ever provided. :blush:

**Comment by atroutt** [comment]
When viewWillAppear there are no messages yet. We are pulling messages in from Firebase, but at the time, they haven't arrived yet.

I tested on the sample project with and without messages and did not experience the issue. I'm going to keep moving my code to the sample project to see if I can force the issue.

> aww thanks :blush:

**Comment by atroutt** [comment]
THIS IS NOT YOUR FAULT!

Ugh... I finally did a git bisect on my project and it turns out upgrading Branch.io from 0.10.9 to 0.11.4 causes this issue. I HAVE NO IDEA WHY. 

Sorry for wasting your time!

**Comment by harlanhaskins** [comment]
branch.io has had similar issues with me. They make a 0x0 UIWindow on first launch that breaks a ton of stuff including [BRYXBanner](https://github.com/harlanhaskins/BRYXBanner)

**Comment by atroutt** [comment]
It looks like they just released 0.11.5, which does not cause the issue.

**Comment by jessesquires** [comment]
Thanks for the update @atroutt ! :smile: No worries!

**Comment by minglini** [comment]
Im having exactly the same issue on the same line, but i dont use branch.io.
Trying to find if some other library is creating this issue...
