### ISSUE TITLE
[Localization] support vietnamese 

### ISSUE THREAD

**Issue by DungntVccorp** [jessesquires/JSQMessagesViewController#1224]
please add vietnammes language to JSQMessagesAssets

"load_earlier_messages" = "Tải thêm tin nhắn";

"send" = "Gửi";

"new_message" = "Tin nhắn mới;

thank

**Comment by jessesquires** [comment]
thanks @DungntVccorp !

I'll accept a pull request, too :smile:

**Comment by DungntVccorp** [comment]
thank @jessesquires
