### ISSUE TITLE
Warning "Invalid Bundle Structure" when submitting archive to iTC

### ISSUE THREAD

**Issue by brbgyn** [jessesquires/JSQMessagesViewController#1226]
I'm receiving a waning about files "PhotoMediaItem.o" and "VideoMediaItem.o" when uploading the ipa to iTunes Connect, using latest xcode (7.0).

The warning:

<img width="580" alt="captura de tela 2015-09-25 as 14 21 03" src="https://cloud.githubusercontent.com/assets/6548984/10107408/34cb1faa-6391-11e5-8a51-7c7d8775cdfe.png">

And right after the upload, apple sends me an e-mail saying:

```
Dear developer,

We have discovered one or more issues with your recent delivery for "MY APP". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Invalid Bundle Structure - The binary file 'Tesouro Direto.app/PhotoMediaItem.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Invalid Bundle Structure - The binary file 'Tesouro Direto.app/VideoMediaItem.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team
```

What could it be ?
Will it prevent the app from being approved ?

Thx

**Comment by jessesquires** [comment]
Hey @brbgyn -- there are no classes in the library called "PhotoMediaItem" and "VideoMediaItem", so those object files wouldn't be generated.

Are those your own subclasses of `JSQPhotoMediaItem` and `JSQVideoMediaItem`?
