### ISSUE TITLE
Register a new Collection View Cell

### ISSUE THREAD

**Issue by jenasubodh** [jessesquires/JSQMessagesViewController#1227]
How do i register a new Collection Cell in the Collection along with the existing MessagesCollectionViewCell

**Comment by jessesquires** [comment]
hey @jenasubodh :smile: see the docs for the library and `UICollectionView` (search for reuse identifiers).

**Comment by jenasubodh** [comment]
Thanks @jessesquires

**Comment by jenasubodh** [comment]
Hey @jessesquires, 

I tried creating a custom cell by inheriting the JSQMessagesCollectionViewCell class and registered the new child class in my chat screen (inherited by JSQMessagesViewController) using the approproate reuse identifier. Well that works fine.

But when i try to load the messages using the selected cell i am not able to see anything on the chat screen. I know the messages are loading because i see the scroll bar but i am not able to see the view. 

Any Thoughts ?
