### ISSUE TITLE
Pinch in and Pinch out the image, after tap image on the table

### ISSUE THREAD

**Issue by tomojiro1125** [jessesquires/JSQMessagesViewController#1228]
I would like to pinch in and pinch out after tap the image on the table.
How can I do that ?
May I ask Is there a method to do that ?

**Comment by jessesquires** [comment]
Hey @tomojiro1125 :smile: 

No support for this right now in the library.

**Comment by tomojiro1125** [comment]
Thank you for the reply :)  
I will hard coding !!

**Comment by harlanhaskins** [comment]
Just for posterity: There are many libraries that support this nicely.

https://github.com/x2on/FSImageViewer
https://github.com/NYTimes/NYTPhotoViewer
https://github.com/AdrianFlorian/AFImageViewer
https://github.com/michaelhenry/MHFacebookImageViewer

**Comment by jessesquires** [comment]
Thanks @harlanhaskins ! :smile:

**Comment by tomojiro1125** [comment]
Thank you @harlanhaskins , I will check it :)
