### ISSUE TITLE
useing JSQMessageMediaData with core data

### ISSUE THREAD

**Issue by BarFDevelopment** [jessesquires/JSQMessagesViewController#1229]
hi, 

i successfully integrated core data in my project, for my JSQMessageData i use NSManagedObject called CDChatMessage

@interface CDChatMessage : NSManagedObject < JSQMessageData >
@end
it works fine for text messages but i can't figure out how to send media messages.

JSQMessage.h have a property that represent the Media Data
@property (copy, nonatomic, readonly) id< JSQMessageMediaData > media;

what is the solution for using JSQMessageMediaData with Core Data ?

thanks.

**Comment by jessesquires** [comment]
Hey @BarFDevelopment :smile: 

Not sure I understand your question. You just need to provide an object that conforms to `JSQMessageMediaData`. Implementation details are up to you.
