### ISSUE TITLE
Layout Crash on Released App

### ISSUE THREAD

**Issue by armanshan12** [jessesquires/JSQMessagesViewController#1230]
Hi. I get the below error on Crashlytics, regarding layouts. Please let me know if you know how this can get fixed. Thanks!

layout attributes for supplementary item at index path (<NSIndexPath: 0x17765b30> {length = 2, path = 0 - 0}) changed from <JSQMessagesCollectionViewLayoutAttributes: 0x17789c30> index path: (<NSIndexPath: 0x17732b50> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 320 32); to <JSQMessagesCollectionViewLayoutAttributes: 0x177900a0> index path: (<NSIndexPath: 0x17765b30> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 320 32); zIndex = -1; without invalidating the layout

**Comment by emiliopavia** [comment]
I'm facing the same issue sometimes...

**Comment by jessesquires** [comment]
Thanks @armanshan12 ! :smile: 

Please read the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) and update your issue!
