### ISSUE TITLE
Register a new Collection View Cell

### ISSUE THREAD

**Issue by jenasubodh** [jessesquires/JSQMessagesViewController#1231]
Hey @jessesquires,

Extending #1227, was not able to ReOpen

I tried creating a custom cell by inheriting the JSQMessagesCollectionViewCell class and registered the new child class in my chat screen (inherited by JSQMessagesViewController) using the approproate reuse identifier. Well that works fine.

But when i try to load the messages using the selected cell i am not able to see anything on the chat screen. I know the messages are loading because i see the scroll bar but i am not able to see the view.

Any Thoughts ?

**Comment by GianniCarlo** [comment]
@jenasubodh  check my response in #1233 . Tell me if it helps

**Comment by jessesquires** [comment]
Thanks @GianniCarlo ! :smile:
