### ISSUE TITLE
iOS 9 crash

### ISSUE THREAD

**Issue by csontosgabor** [jessesquires/JSQMessagesViewController#1232]
I have an error while loading messages:
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x15ec64600 of class JSQMessagesComposerTextView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x15dee6a30> (
<NSKeyValueObservance 0x15f628f20: Observer: 0x162e46a00, Key path: contentSize, Options: <New: YES, Old: YES, Prior: NO> Context: 0x1002bfa10, Property: 0x15ddcc350>
)'

can anyone know whats the reason?

it worked on Xcode 6 but, with the new xcode7 i have more issues with jsqmessenger

**Comment by mmiroslav** [comment]
Any news? Did you solve this problem?
I have same issue...

**Comment by tomasicg** [comment]
@csontosgabor You most likely removed the ComposerTextView from the view stack at some point. And the bug is that its dealloc doesn't clean up the KVO hooks. Therefore, a crash occurs. I hope this gets fixed, because it's causing us some headaches as well.

**Comment by akki7017** [comment]
Any updates on this? I removed the composer view and this started to happen. i don't need to show composer view. if there is any other method, which can safely hide the composer view, i am open to it. :)

**Comment by csontosgabor** [comment]
Actually I made it, but unfortunatelly, I forget what was this issue.
send a mail acsontosgabor@gmail.com than talk about there

**Comment by akki7017** [comment]
@csontosgabor  Thanks for so quick turn around. I have sent an email.

**Comment by eliburke** [comment]
@csontosgabor @mmiroslav @tomasicg @akki7017
I can see how to cause this by calling `[self.inputToolbar.contentView.textView removeFromSuperview];` from within the Chat view controller. 

Is there a legitimate need to remove the textView in this manner? Do any of you have a solution?

**Comment by jessesquires** [comment]
closing this -- doesn't seem like a library bug.
