### ISSUE TITLE
`Custom menu actions` & `Data detectors` conflict

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [jessesquires/JSQMessagesViewController#1234]
Hi,

I see that at times when the message text is just a `number/ url/ email`, long press of message bubble causes `Data detectors` to override `Custom menu actions`. 

One workaround I could think of is to determine whether or not the message text is  just a `number/ url/ email`, in `cellForItemAtIndexPath` & disable that particular `cell.textView.dataDetectorTypes`. I haven't tried it yet though.

Is there a better way to solve this problem?

**Comment by GianniCarlo** [comment]
+1 I'm having the same problem

**Comment by GianniCarlo** [comment]
@Sufi-Al-Hussaini I found a workaround which was to override my custom cells `gestureRecognizer:shouldReceiveTouch:` with only `return YES`

```objective-c
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    return YES;
}
```

This way I can at least get the custom menu when long pressing not the bubble but the cell. I don't know yet if this has some side-effects seeing that the original implementation in `JSQMessagesCollectionViewCell` is the following:

```objective-c
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    CGPoint touchPt = [touch locationInView:self];

    if ([gestureRecognizer isKindOfClass:[UILongPressGestureRecognizer class]]) {
        return CGRectContainsPoint(self.messageBubbleContainerView.frame, touchPt);
    }
    
    return YES;
}
```

@jessesquires or can anyone shed any light as to what might be the side effects of my solution?

**Comment by jessesquires** [comment]
@GianniCarlo -- shouldn't be any negative side-effects.

The original implementation limits the touch to the message bubble, your change allows touches in the entire cell

**Comment by GianniCarlo** [comment]
@jessesquires - oh ok, I thought it might clash with another `UIGestureRecognizer` in the cell that I may not know about. But everything is working well so far 👍

**Comment by Sufi-Al-Hussaini** [comment]
Thanks a lot guys, @GianniCarlo and @jessesquires!

**Comment by ebbe-brandstrup** [comment]
Thanks for me as well @GianniCarlo  and @jessesquires! I've changed the ```shouldReceiveTouch``` method to add a bit pit "long press area padding" to address the same issue:

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    CGPoint touchPt = [touch locationInView:self];
    
    if ([gestureRecognizer isKindOfClass:[UILongPressGestureRecognizer class]]) {
        int padding = 30;
        CGRect enlargedFrame = CGRectInset(self.messageBubbleContainerView.frame, -padding, -padding);
        return CGRectContainsPoint(enlargedFrame, touchPt);
    }
    
    return YES;
}
```

**Comment by randarnold** [comment]
In JSQMessageViewController.m, what is the purpose of this line
`	[UIMenuController sharedMenuController].menuItems = nil;`
in
`- (BOOL)canPerformAction:(SEL)action withSender:(id)sender`

The nilling out the menuItems here kills my custom menus on inputToolbar.contentView.textView

Thanks
