### ISSUE TITLE
Parse markdown in messages

### ISSUE THREAD

**Issue by Luke47** [jessesquires/JSQMessagesViewController#1235]
Is there currently any chance of properly parsing / formatting markdowns in text messages?

E.g. `[link title](link)`

Before I've started using this library, I did this with attributed strings, but it seems that it isn't yet supported in this library. Is there any workaround for that?

Thank you! :)

**Comment by jessesquires** [comment]
The next major version of the library (`v8.0`) will be moving to [`TTTAttributedLabel`](https://github.com/TTTAttributedLabel/TTTAttributedLabel) which kind of supports a markdown-like syntax.

No support for this at the moment.
