### ISSUE TITLE
Set the AvatarImageView contentMode

### ISSUE THREAD

**Issue by csontosgabor** [jessesquires/JSQMessagesViewController#1236]
Hi! Maybe someone already asked this silly question, but I tried to set the avatar image view content mode in the cellForItemAtIndexPath method, but nothing happens.
I am new to swift, i tried this code:

cell.avatarImageView!.contentMode = .ScaleToFill

What did i do wrong?

**Comment by carayolthomas** [comment]
Hi there, 

I don't think you should do this for your avatars.

In viewDidLoad method you need to identify the size you want for your avatars with the `collectionViewLayout` properties (`incomingAvatarViewSize`, `outgoingAvatarViewSize`). 

And then, you should use the `JSQMessagesAvatarImageFactory` to create your `JSQMessagesAvatarImage`. This way, your images will fit perfectly with the `UICollectionViewItem` `imageView`. 

Sorry I don't have sample code to show you in Swift. 

Hope it helps :)

**Comment by jessesquires** [comment]
Thanks @carayolthomas ! :smile:
