### ISSUE TITLE
Custom bubble strange reaction

### ISSUE THREAD

**Issue by djxmax** [jessesquires/JSQMessagesViewController#1237]
Hi,

For my app, I want to add message between two bubbles : 
![capture d ecran 2015-10-02 a 09 37 45](https://cloud.githubusercontent.com/assets/7045905/10241443/50fba5de-68e9-11e5-956f-15214d21eb30.png)

So to do that, I choose to add "special" bubbles that I customise : I add a message with special Id like this (in swift)
```
let jsqmessage = JSQMessage(senderId: "specialId", senderName: "", text: "my text")
self.messages += [jsqmessage]
```

And after,  I customise my cell with this (I simplify a bit): 
```
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        if(messages[indexPath.row].senderId == "specialId"){
            let label1 = UILabel(frame: CGRectMake(0, 0, 300, 50))
            label1.center = CGPointMake(UIScreen.mainScreen().bounds.width/2, 50)
            label1.textAlignment = NSTextAlignment.Center
            label1.text = messages[indexPath.row].text
            label1.backgroundColor = UIColor.redColor()
            cell.addSubview(label1)
        }
        return cell
    }
```

But the result Is totally different, the label apprear randomly on other cell (it change each time i open the app)
![image2](https://cloud.githubusercontent.com/assets/7045905/10241856/c8930a30-68ec-11e5-80aa-2ff7b12c7eec.png)

I also add some traces with print to verify what's the problem, but the trace reaction are normal and do what they have to do.
I also try a lot of other modification but nothing work. So, 2 solutions:
- my solution is not the right one
- it's a bug

Thanks for your answer ;)
(Sorry for my english)

**Comment by GianniCarlo** [comment]
@djxmax I think your better off customizing the `collectionView:attributedTextForCellTopLabelAtIndexPath` to achieve what you're looking for (those labels are centered also). Don't forget to set the height of those labels in `collectionView:layout:heightForCellTopLabelAtIndexPath:` otherwise they won't show up. Check the demo, I think they've got an example there

**Comment by harlanhaskins** [comment]
@djxmax This line:

```objc
if(messages[indexPath.row].senderId == "specialId"){
```

Does not do what you think it does. You'll need to use:

```objc
if ([messages[indexPath.row].senderId isEqualToString:@"specialId"]) {
```

**Comment by GianniCarlo** [comment]
@harlanhaskins actually I think in Swift his syntax is ok, but correct me if I'm wrong

**Comment by harlanhaskins** [comment]
In Swift, it's perfectly fine because `char *` and `NSString` are all bridged to the same `String` type, and `==` is a special 'equivalence' operator instead of raw equality. In Objective-C, however, they're comparing the address of an `NSString` to the address of a `char`.

**Comment by GianniCarlo** [comment]
@harlanhaskins but he is programming in Swift though

**Comment by harlanhaskins** [comment]
WHOA I didn't notice. How didn't I notice? Never mind then! :+1:

**Comment by GianniCarlo** [comment]
haha ok 👍

**Comment by djxmax** [comment]
Cool, I try with ```collectionView:attributedTextForCellTopLabelAtIndexPath``` and it works.
But now, some now problem:
- if the text is too long, the line end with "...". I think that the label i limited at 1 line so, how I can change this and put 2 line.
- I have an extra padding at the bottom of the label (for the hidden bubble). How I can reduce it ?
Thanks ;)

**Comment by jessesquires** [comment]
Thanks all! :smile: 

Looks like just a few more questions to answer here.

>if the text is too long, the line end with "...". I think that the label i limited at 1 line so, how I can change this and put 2 line.

You can add newlines to your string `"\n"` and set `numberOfLines` on the label to `0`. (This might be the default, I can't remember). Then you'll want to return the correct height from the corresponding delegate method, `heightForAttributedText...`

>I have an extra padding at the bottom of the label (for the hidden bubble). How I can reduce it ? 

Not sure exactly what you mean. But I think the `heightForAttributedText...` delegate methods are what you want...
