### ISSUE TITLE
[Help] Dark overlay for a Selected/Highlighted media view

### ISSUE THREAD

**Issue by GianniCarlo** [jessesquires/JSQMessagesViewController#1239]
What I'm looking for is that with a long press, the media view has a dark overlay on it while the UIMenuController is shown, just like with a regular text message.

Does anybody have some pointers on where to start with this?

**Comment by GianniCarlo** [comment]
Well I found a hacky solution, I had a view with black background and alpha 0.5. Then have:
```objective-c
-(BOOL)collectionView:(UICollectionView *)collectionView shouldShowMenuForItemAtIndexPath:(NSIndexPath *)indexPath{
    [super collectionView:collectionView shouldShowMenuForItemAtIndexPath:indexPath];

    JSQMessage *currentMessage = [self.visibleMessagesArray objectAtIndex:indexPath.item];
    
    if ([currentMessage isMediaMessage]) {
        [((CustomMedia *)currentMessage.media).mediaView addSubview:self.overlayMedia];
        
        self.overlayMedia.frame = ((CustomMedia *)currentMessage.media).mediaView.frame;
        [((CustomMedia *)currentMessage.media).mediaView bringSubviewToFront:self.overlayMedia];
    }
    
    return YES;
}
```
Then called `[self.overlayMedia removeFromSuperView]` in different places like:
- `collectionView:performAction:forItemAtIndexPath:withSender`
- `scrollViewWillBeginDragging:`
- `collectionView:didTapCellAtIndexPath:touchLocation:`
- `collectionView:didTapMessageBubbleAtIndexPath:`

I know it's far from ideal, if somebody has some suggestions they would be much appreciated

**Comment by michaelkirk** [comment]
Can we re-open this as a feature request? I think it's universally useful.

**Comment by jessesquires** [comment]
@michaelkirk 👍

**Comment by jai** [comment]
Is anyone currently working on this? If not I'll look into it.

**Comment by jessesquires** [comment]
@jai - I don't think so

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
