### ISSUE TITLE
How can I reuse the toolbar for input in other VCs

### ISSUE THREAD

**Issue by jdgong** [jessesquires/JSQMessagesViewController#1242]
Is there a convenient way to achieve that? I see the current implementation is embed the toolbar in the xib file of JSQMessagesViewController. Is there a way to do it programmatically? Thanks!

**Comment by mmiroslav** [comment]
I asked similar question on stackoverflow... http://stackoverflow.com/questions/33019348/how-to-implement-custom-jsqmessagesinputtoolbar
Any idea?

**Comment by jdgong** [comment]
@mmiroslav  I managed to make a xib and copy the toolbar from this bundle to my xib file. It is not perfect subclassing, but it works for me so far.

**Comment by jessesquires** [comment]
Hey @jdgong and @mmiroslav :smile: 

Please see #750 and #746
