### ISSUE TITLE
iOS 9 - interactive keyboard/toolbar dismissal broken

### ISSUE THREAD

**Issue by nathanielescribano** [jessesquires/JSQMessagesViewController#1245]
![f3954bb6-6307-11e5-98c2-938302a07306](https://cloud.githubusercontent.com/assets/183247/10326500/bda7d9fe-6c50-11e5-9dd5-908d3d5bb08d.gif)

On the messaging app, the input toolbar goes down with the rest of the keyboard.
Any thoughts?
Thanks

**Comment by juliensaad** [comment]
Directly related to #1063. AcidicSkittles has posted a workaround

**Comment by jessesquires** [comment]
Thanks @nathanielescribano / @juliensaad ! :smile: 

Closing this in favor of #1063
