### ISSUE TITLE
Maintain layout/messages position when returning from presented view controller

### ISSUE THREAD

**Issue by toreolsensan** [jessesquires/JSQMessagesViewController#1246]
When presenting a new view controller from JSQMessagesViewController, I notice the messages list and the input toolbar is scrolled down during the transition (the keyboard stays, though). When navigating back again, the keyboard is still visible, but the input toolbar only becomes visible after a little while, and the messages list stays at the bottom of the full screen, i.e the latest messages are obscured by the keyboard.

Ideally I would like the view to stay exactly the way it was when presenting the new view controller: the keyboard should be visible, the input toolbar should stay visible at the same location and the position of the messages should not change. Is there a way to obtain this behaviour?

I've tested this primarily on iOS 9 with both JSQMessagesViewController 7.1.0 and recent develop/HEAD.

**Comment by wdcurry** [comment]
I would like to do the same, more logically, but one can achieve this by managing the act of leaving the VC, by setting self.automaticallyScrollsToMostRecentMessage = YES; then resetting it on the return. It is a bit messy, but works.

**Comment by jessesquires** [comment]
I think this is a bug caused by iOS 9. Should be working as expected on iOS 8.x

**Comment by jessesquires** [comment]
Sounds like the workaround proposed by @wdcurry is best for now.

There will be some major keyboard improvements in v8.0 that should address any issues here.
