### ISSUE TITLE
Optional avatar view

### ISSUE THREAD

**Issue by naluhh** [jessesquires/JSQMessagesViewController#1248]
Hi,
I'd like to copy the iMessage behavior for the "not distributed" with the avatar like a (!) mark. But I can't find a way to remove the avatar for certain cell, and only display it if the delivery failed.

I saw the #491 but they use the "avatarViewSize" property, and I can't find it.

Thank you in advance

edit:it's a private property, I found it, is there any way to not modify the code?

**Comment by zwang** [comment]
In *MessageViewController.viewDidLoad, add the following code will hide avatar for outgoing message

        self.collectionView!.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero;

Hope this help.

**Comment by jessesquires** [comment]
Hey @naluhh  - #491 has everything you need to know
