### ISSUE TITLE
Add custom label next to the bubble

### ISSUE THREAD

**Issue by Abhishek-addweb** [jessesquires/JSQMessagesViewController#1249]
I want to create the custom label which is used for time-stamp for each message. Please check the attached image for the same. Please help
![screen shot 2015-10-08 at 6 41 09 pm](https://cloud.githubusercontent.com/assets/8208326/10367141/51e8fc0a-6dec-11e5-9df5-b21670eadc25.png)

**Comment by Abhishek-addweb** [comment]
Can you please help @jessesquires

**Comment by GianniCarlo** [comment]
@Abhishek-addweb search `[Customize Cells]` or `[Custom Cells]` in issues, there's plenty of information already about custom cells

**Comment by Abhishek-addweb** [comment]
Thanks @GianniCarlo  I searched based on your filters but nothing find useful. Can you please highlight the link for the same. It'll be great for me.

**Comment by GianniCarlo** [comment]
@Abhishek-addweb I would recommend that you subclass `JSQMessagesCollectionViewCellIncoming ` and `JSQMessagesCollectionViewCellOutgoing ` respectively for your cells. There's more info about it in my first response to #1233  . Tell me if you have any doubts

**Comment by Abhishek-addweb** [comment]
Thanks @GianniCarlo . I'll check and let you know if I have any doubts.
