### ISSUE TITLE
Unwanted collection view offset when in TabBarController

### ISSUE THREAD

**Issue by mcicak** [jessesquires/JSQMessagesViewController#1250]
I have following case:

TabBarController -> NavigationController -> JSQMessagesViewController

When JSQMessagesViewController is presented, tabbar is hidden but collection view has offset as if it's visible ([screenshot](http://prntscr.com/8p7noe)).
Tapping inside input text field and then hiding keyboard sets appropriate collection view offset. But I didn't find a way to make it initially look good. Anyone has same issue?

**Comment by jessesquires** [comment]
Thanks @mcicak !

See #179
