### ISSUE TITLE
messageBubbleFont != nil

### ISSUE THREAD

**Issue by Natelegreat1** [jessesquires/JSQMessagesViewController#1252]
IFF I present my JSQMessagesViewController modally when the app is opened from suspended, I get the following crash: 
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: messageBubbleFont != nil'`

In `viewDidLoad`, I have `        self.collectionView.collectionViewLayout.messageBubbleFont = [UIFont systemFontOfSize:14 weight:UIFontWeightLight];`

I never set it to be nil...

Any ideas?

**Comment by Natelegreat1** [comment]
Not setting `self.collectionView.collectionViewLayout.springinessEnabled = BOOL` in `viewDidAppear` stopped the crashing! 

This is why I should have read the fine print!!! (*Note: this feature is mostly stable, but still experimental*)

**Comment by jessesquires** [comment]
Thanks all! :smile: 

Now tracking this at #1338.
