### ISSUE TITLE
Sent/Received checkmark inside the bubble

### ISSUE THREAD

**Issue by angeljcarrillo** [jessesquires/JSQMessagesViewController#1253]
I want to add a check marks as telegram or whatsapp, however my check marks get hidden by the color of the bubble, how I can fix that problem, or there are other way?

Best regards

![captura de pantalla 2015-10-09 a la s 17 31 45](https://cloud.githubusercontent.com/assets/13575974/10407064/a3480d24-6eab-11e5-944b-091a902478af.png)

**Comment by GianniCarlo** [comment]
@angeljcarrillo can you attach a screenshot of the desired result? As I understand it now, I would suggest that you change the color of either your checkmark or your bubble. Maybe the problem is something else, but that's what I understood from your post

**Comment by jessesquires** [comment]
@GianniCarlo - thanks for helping answer questions! Much appreciated by myself, and the community.

**Comment by GianniCarlo** [comment]
@jessesquires - Glad I can give back 😁

**Comment by angeljcarrillo** [comment]
Thank you very much for answers me, I added the screenshots, also I tried to add the image in the xib file, but it does not work

![captura de pantalla 2015-10-14 a la s 16 30 42](https://cloud.githubusercontent.com/assets/13575974/10498486/30cf85f8-7291-11e5-8da9-279ce20216ef.png)

![captura de pantalla 2015-10-14 a la s 16 23 25](https://cloud.githubusercontent.com/assets/13575974/10498556/35c05ab0-7291-11e5-9bde-62ed652eb371.png)

**Comment by angeljcarrillo** [comment]
I would like to have two checkmarks in order to I can notify the user that his or her message has been send or received, however I know how to appear and disappear image with alpha 1 and 0.

Best regards.
