### ISSUE TITLE
How to Increase bubble gap size between sender and receiver message bubbles?

### ISSUE THREAD

**Issue by milsirhc** [jessesquires/JSQMessagesViewController#1259]
I like to only increase the "gap" spacing between the sender and the receiver message bubbles so as to make it more readable with custom fonts when they reply back and forth to each other.

The spacing for their own message bubbles should stay the same.

Is there any quick way to do this?

**Comment by jessesquires** [comment]
Hey @milsirhc :smile: 

Try adjusting `minimumLineSpacing` and `interItemSpacing` on the flow layout.
