### ISSUE TITLE
Hyperlink in text Message body

### ISSUE THREAD

**Issue by mattnuns** [jessesquires/JSQMessagesViewController#1262]
I'm trying to utilise hyperlinks (i.e. a word that has an http link attributed to it) in both the sent and received text messages bubbles. As far as I can tell there doesn't seem to be any way to do this as as the "text" message element used to pass the message is an NSString and is therefore not attributable.

Are hyperlinks, i.e. a word that links/executes a url when it's tapped, in text messages possible? If so what would be the recommended approach?

Thanks,

Matt

**Comment by harlanhaskins** [comment]
The cells use `UITextView`s for their text handling, which supports URLs.

Just set the `dataDetectorTypes` on the cell's `textView` inside `cellForRowAtIndexPath`.

**Comment by mattnuns** [comment]
That would allow for URLs sent in the message but what about for hyperlinks, I.e. the word "github" would link to and open a predetermined (and attributed) page for example - github.com ?

**Comment by GianniCarlo** [comment]
@mattnuns you could look into a markdown parser library and achieve what you want

**Comment by jessesquires** [comment]
Thanks all!

The move to `TTTAttributedLabel` for the `8.0` release will enable this. Until then, clients will have to implement this themselves.
