### ISSUE TITLE
Crash IOS9

### ISSUE THREAD

**Issue by wagnerassis** [jessesquires/JSQMessagesViewController#1263]
MessageBubbleFont != nil when open chat with messages.

**Comment by eliburke** [comment]
Let me save @jessesquires some typing. Check out: #1252, #1217, #1210 
tl;dr, you probably need to turn off springiness, or refactor the way you are updating your chat bubbles.

**Comment by wagnerassis** [comment]
Thanks !

**Comment by jessesquires** [comment]
Thanks all! :smile: 

Now tracking this at #1338.
