### ISSUE TITLE
iOS 9 Scrolling collectionView not smooth

### ISSUE THREAD

**Issue by vazin** [jessesquires/JSQMessagesViewController#1264]
This problem appeared in ios 9. Even in the demo example. Also in other apps i can see such problems with UITableViews and UICollectionViews. In ios 8 everything works fine. Do you have any suggestions about it?

**Comment by dpreston10** [comment]
I also notice that the building of the collection view seems to be much slower than in iOS 8

**Comment by aspcartman** [comment]
Profiler says that bubble images are getting reloaded from png on each display call. Over and over again.
<img width="1048" alt="screen shot 2015-10-26 at 06 49 03" src="https://cloud.githubusercontent.com/assets/844194/10720972/e83fcfca-7bad-11e5-9f2e-b0dc8288003c.png">

**Comment by aspcartman** [comment]
Actually I was wrong about bubble cells. In my case it was my user's avatars. Forced them to cached prerendered versions and everything is smooth again.

**Comment by vazin** [comment]
@aspcartman Thank you for taking part in a question. Can you provide some code example? As i understand prerendered avatars  are stored in dictionary and loaded only once. Also I disabled avatars but some lags have remained.

**Comment by aspcartman** [comment]
@vazin np :)

Bubbles:
```objc
// No prerendering: images are stretchable and it doesn't worth it. Just acquire the JSQImage pair and save it in ivar
JSQMessagesBubbleImageFactory *factory  = [JSQMessagesBubbleImageFactory new];
_incomingImage = [factory incomingMessagesBubbleImageWithColor:[UIColor xs_darkBlueColor]];
_outgoingImage = [factory outgoingMessagesBubbleImageWithColor:[UIColor xs_blueColor]];
```

Avatars:
```objc
// Avatar is stored inside the User object, prerendered by custom lazy getter
- (UIImage *) avatar
{
	if (!_preRenderedAvatar)
	{
		_preRenderedAvatar = [[UIImage imageWithData:self.photoData] preRender];
	}
	return _preRenderedAvatar;
}
```

prerender:
```objc
- (UIImage *) imageSized:(CGSize)size
{
	CGRect     newRect  = CGRectIntegral(CGRectMake(0, 0, size.width, size.height));
	CGImageRef imageRef = self.CGImage;

	UIGraphicsBeginImageContextWithOptions(size, NO, 1);
	CGContextRef context = UIGraphicsGetCurrentContext();

	CGContextSetInterpolationQuality(context, kCGInterpolationHigh);

	CGAffineTransform flipVertical = CGAffineTransformMake(1, 0, 0, -1, 0, size.height);
	CGContextConcatCTM(context, flipVertical);

	CGContextDrawImage(context, newRect, imageRef);

	CGImageRef newImageRef = CGBitmapContextCreateImage(context);
	UIImage    *newImage   = [UIImage imageWithCGImage:newImageRef];

	CGImageRelease(newImageRef);
	UIGraphicsEndImageContext();
	return newImage;
}

- (UIImage *) preRender
{
	return [self imageSized:self.size];
}
```

That's it. Now everything is smooth and nice :) Good luck!

**Comment by jessesquires** [comment]
Thanks @aspcartman ! :smile: 

To clarify: the library does not cache avatar/bubble image data. This is left up to the client.
