### ISSUE TITLE
How to open the JSQMessagesViewController from push notification

### ISSUE THREAD

**Issue by SimonaMilchevska** [jessesquires/JSQMessagesViewController#1265]
Hi,
I am stuck on this one: How to pass the JSQMessagesViewControllerDelegate when opening the Chat Controller from push notification ?

Any idea/help is appreciated :)

**Comment by d4r1091** [comment]
What kind of information do you pass into notification payload?
Would be great if you pass something to "track" your flow directly into the conversation or group chat ;)

**Comment by SimonaMilchevska** [comment]
I was thinking of some handler class so that i can initialize the Chat controller together with the parameters.

**Comment by d4r1091** [comment]
that's perfect but, could you show me what kind of parameter do you send in push notification payload?
for example, i send something like:

{
.....apple stuffs.....
******ADDONS******
     "senderIdentifier" = "00393394545445"
     "msg" = "Dario: hi there"
     "type" = 1 (that means, in my app design, that is a conversation one to one, not group)
***********************
}

when i receive a notification like then, i route my app to open a view controller with the chat with this "senderIdentifier". if my list of "opened chats" has got a conversation already created with this "senderIdentifier", open that one. if not, start a new conversation with that one. ;)

**Comment by SimonaMilchevska** [comment]
In the notification payload i have the sender, receiver id, and the message.  My idea is more like:
MessagesViewController *messagesView = [[MessagesViewController  alloc] initwithRoot:root andSenderId:senderId andReceiverId:receiverId];

But where to define this method for allocation?

**Comment by d4r1091** [comment]
OK, I understand.
It's right what you want.
My question to help you is: is your app flow designed in (only) one storyboard?
If not, try to initialize the storyboard who implement your MessagesViewController from this method in your AppDelegate.m
```
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
}
```
