### ISSUE TITLE
Generic of a names in JSQMessageData protocol conflicts with existing models

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQMessagesViewController#1267]
Using stuff like 'text' and 'date' on your JSQMessageData makes this very hard to integrate into existing projects.  My core data model class already has text and date fields...Yours should really be named something like messageSentDate and messageText, for example.

**Comment by harlanhaskins** [comment]
What happens if my Core Data models use `messageSentDate` and `messageText`?

Namespace collisions are bound to happen and making a 'more specific name' isn't going to solve it.

**Comment by grosch** [comment]
True, but it's much less likely when your property names relate more to your framework.   What's more likely?  That someone already used date/text, or messageSentDate and messageText?

**Comment by jessesquires** [comment]
@grosch - Thanks for the feedback! :smile: 

I tend to agree with @harlanhaskins -- namespacing will always be a problem.

In Objective-C, if you already have a `text` property/method, then conforming to the protocol shouldn't require any extra work — all that matters is that there's a selector named `text`.

In Swift however, this might conflict, but I'm not sure. If it's CoreData, it's probably ok.

Then final issue would be if your `text` property does not correspond to what `JSQMessageData` thinks `text` is — I'm assuming this is your issue?

**Comment by grosch** [comment]
@jessesquires - My specific issue is that since I'm using Core Data (which has to be a common scenario I'd think!), my 'text' element is a variable, whereas the JSQMessageData protocol defines text as a function returning a string.  That means they can't match as Swift won't allow you to have a variable and a function with the same name.  Which is just plain dumb, but Apple disagrees on the viability of that (I opened a bug with them and they closed it saying as designed)

**Comment by grosch** [comment]
I think the core issue here is that the items in that protocol are defined as getter functions, not readonly properties, so when the auto-conversion to Swift is done, it puts them as functions.   

When's the rewrite in Swift coming out?  :)

**Comment by jessesquires** [comment]
>I think the core issue here is that the items in that protocol are defined as getter functions, not readonly properties, so when the auto-conversion to Swift is done, it puts them as functions.

This is what I suspected. I'll investigate ways to improve. Using `@property` for protocols in Objective-C is bad practice.

>When's the rewrite in Swift coming out? :)

lol i wish. one day.

**Comment by harlanhaskins** [comment]
>Using @property for protocols in Objective-C is bad practice.

I've never seen this -- why is this?

**Comment by jessesquires** [comment]
@harlanhaskins 

1. Specifies atomicity (`atomic`, `nonatomic`)
2. Specifies memory management (`copy`, `assign`, `weak`, `strong`)
3. Properties are syntactic sugar for: getter, setter, and ivar. So, *technically*, you are also specifying that conformers must have storage for an ivar. (Even with `readonly`, still technically specifies this. Although it could be a computed property.)

All of the above feel bad/wrong. The object speaking to `id<MyProtocol>` shouldn't know or care about any of the above. And not only should your protocol *not care* about these things, but enforcing them can be problematic. For example, why should your protocol dictate that my class uses `weak`?

**Comment by jessesquires** [comment]
@grosch -- Just hacked around in a playground for a minute. Here's an approach you could try if this is really problematic for you.

1. Create a struct that conforms to `JSQMessageData`
2. Forward your `NSManagedObject` data through this struct

It actually feels pretty clean to me, but I can see how it might feel cumbersome. Anyway, this will let you keep your names how you like with minimal overhead :smile: Just a few extra bytes to alloc for the `struct` and a pointer to your managed object.

````swift
//: Playground - noun: a place where people can play

import UIKit
import CoreData

protocol JSQMessageData {
    func text() -> String
    func date() -> NSDate
}


struct MessageData: JSQMessageData {

    let model: MyModel

    func text() -> String {
        return model.text
    }

    func date() -> NSDate {
        return model.date
    }
}


class MyModel: NSManagedObject {

    @NSManaged var text: String
    @NSManaged var date: NSDate

    lazy var messageData: MessageData = MessageData(model: self)

}


func messageDataForItemAtIndexPath(indexPath: NSIndexPath) -> JSQMessageData {
    let model = MyModel()
    return model.messageData
}
````

**Comment by grosch** [comment]
Thanks, @jessesquires , I'll look into this tonight when i'm home from work.

Do you have any guidance/pointers/code for the server side of chat?  Right now I'm basically doing it via push notifications, but that doesn't feel very robust.

**Comment by grosch** [comment]
@jessesquires JSQMessageData inherits from NSObjectProtocol, so your example above won't actually work as the struct can't inherit from JSQMessageData.  If you switch to class, then you get lots of errors that you haven't implemented NSObjectProtocol :(

**Comment by jessesquires** [comment]
Oh right. Easy fix, though — just inherit from `NSObject`.

````swift
//: Playground - noun: a place where people can play

import UIKit
import CoreData

protocol JSQMessageData: NSObjectProtocol {
    func text() -> String
    func date() -> NSDate
}


class MessageData: NSObject, JSQMessageData {

    let model: MyModel

    init(model: MyModel) {
        self.model = model
    }

    func text() -> String {
        return model.text
    }

    func date() -> NSDate {
        return model.date
    }
}


class MyModel: NSManagedObject {

    @NSManaged var text: String
    @NSManaged var date: NSDate

    lazy var messageData: MessageData = MessageData(model: self)

}


func messageDataForItemAtIndexPath(indexPath: NSIndexPath) -> JSQMessageData {
    let model = MyModel()
    return model.messageData
}
````

**Comment by grosch** [comment]
I got this working now, thanks for your help!

**Comment by jessesquires** [comment]
Going to keep this open and consider name changes for 8.0.

Still haven't decided what's best.

**Comment by grosch** [comment]
Honestly I think the real solution is to make it use a variable instead of a function, then the name conflicts don't matter as much because you probably get what you're expecting.

**Comment by jessesquires** [comment]
Oh right -- I should add:

Or, find out if you can import an Objective-C function as a Swift property... probably not?

**Comment by grosch** [comment]
Not via the auto-conversion, no.   Anything you define as a readonly @property will properly come in as a variable.  is there a specific reason you made those functions instead of read-only getters?

**Comment by jessesquires** [comment]
@grosch -- yeah, see the https://github.com/jessesquires/JSQMessagesViewController/issues/1267#issuecomment-149443628 above

**Comment by grosch** [comment]
Which gets us back to we need a Swift native version :)  I'm guessing at some point you'll just have to decide to halt maintenance on the ObjC version and convert it to Swift.  I'd hope at this point most people are using Swift...which I know isn't necessarily true for big companies, but we hate those guys anyways.  LOL.

**Comment by lijie121210** [comment]
Just a student, glad to read your discussion . A swift version really let me look forward to.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
