### ISSUE TITLE
collectionView.contentInset gets reset after keyboard appears

### ISSUE THREAD

**Issue by mbalex99** [jessesquires/JSQMessagesViewController#1268]
I have this in viewDidLoad
```swift
collectionView?.contentInset = UIEdgeInsetsMake(0, 0, 120, 0)
```

However it gets reset when the keyboad shows and is dismissed?

I've attached a video and as you can see I need that bottom space for the 2 buttons on top of the toolbar

Is there a proper way on v7.2.0 to achieve this?

https://www.youtube.com/watch?v=XxsRXuq7GFU

**Comment by jessesquires** [comment]
Hey @mbalex99 - interesting.

So `topContentAdditionalInset` exists for this reason — except to adjust the *top* insets.

Maybe try listening for the keyboard notifications? Either from UIKit, or `JSQMessagesKeyboardControllerNotificationKeyboardDidChangeFrame`.

**Comment by jessesquires** [comment]
Hm.. now that I think about it this should actually be:

````objective-c
@property (assign, nonatomic) UIEdgeInsets additionalContentInset;
````

**Comment by mbalex99** [comment]
I saw that method, I was curious why the other 3 sides weren't represented.
`additionalContentInset` that's such a weird name, is there a reason why we can't just override `UIEdgeInsets`?

**Comment by jessesquires** [comment]
The library manipulates `collectionView.contentInset` automatically for keyboard show/hide. There's no other way for the library to know what kind of custom subviews you've added.

**Comment by mbalex99** [comment]
Do you think this is the right track?

https://github.com/mbalex99/JSQMessagesViewController/commit/9bb06f89f3b57845100867b7100180f205af3cd5

**Comment by Lucashuang0802** [comment]
@jessesquires You can now set `contentInset` in `viewDidLoad` and the padding will remain when the keyboard appears/dismisses.

**Comment by ZvOlCuOk2009** [comment]
Excellent! This solution helped me to displacement frame  the top of the

**Comment by tamoyal** [comment]
In the latest version (`7.3.4`), setting the content inset does not work for me but setting `topContentAdditionalInset` does
