### ISSUE TITLE
whats the idea of load all avatars and display names asynchronously? i get only sender ID from server

### ISSUE THREAD

**Issue by whatya** [jessesquires/JSQMessagesViewController#1269]

**Comment by carayolthomas** [comment]
Hi there, 

I assume that you don't have messages either right? So you can still use some fake display names until you have the display name from the server. It shouldn't be a problem if you don't have any messages to show.

For all avatars, you should use fake avatars with this method of the `JSQMEssagesAvatarImageFactory` 

`+ (JSQMessagesAvatarImage *)avatarImageWithUserInitials:(NSString *)userInitials
                                        backgroundColor:(UIColor *)backgroundColor
                                              textColor:(UIColor *)textColor
                                                   font:(UIFont *)font
                                               diameter:(NSUInteger)diameter;`

Let's suppose you're getting avatars url with your WS, you can download them using some libraries such as `SDWebImage` (`SDWebImageDownloader`), then you build your dictionary of `UIImage` that you use in `- (id<JSQMessageAvatarImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageDataForItemAtIndexPath:(NSIndexPath *)indexPath`

I think this is the only way to achieve what you want to do.

Maybe, wait @jessesquires to confirm or not what I just said ;)

Have a great day!

**Comment by jessesquires** [comment]
Roughly, sounds correct to me. Thanks @carayolthomas !

**Comment by swetansh** [comment]
Can I get the same code for swift?

**Comment by bystritskiy** [comment]
**Solution on Swift 4**

You can use library "SDWebImage" 

Write to the method:  
`func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell`

```
cell.avatarImageView.sd_setImage(with: URL(string: "YOUR_URL"))
cell.avatarImageView.sd_setShowActivityIndicatorView(true)
```
