### ISSUE TITLE
Add check marks

### ISSUE THREAD

**Issue by angeljcarrillo** [jessesquires/JSQMessagesViewController#1270]
Hi I little bit new in swift, I would like to add a check marks like the picture, however I can not get it, I try add the image in the xib file of the outgoing bubble, but it does not work.

How I can add the check marks like the picture?, I think that I have to add in the index table view as a text or something like that, but how?

Best regards

![example](https://cloud.githubusercontent.com/assets/13575974/10643834/a1644534-77ea-11e5-93a3-77d554a3ba23.png)

**Comment by Liampronan** [comment]
@angeljcarrillo  I haven't done this before but #1087 may have some helpful ideas for you

**Comment by jessesquires** [comment]
Thanks @Liampronan !

Also, @angeljcarrillo -- search old issues for "[Custom Cells]"
