### ISSUE TITLE
How to change color of name and time next to bubble

### ISSUE THREAD

**Issue by tomojiro1125** [jessesquires/JSQMessagesViewController#1276]
I am sorry but it is basic question.
Though I read reference, I didn't get below question.

I want to change color of name and time next to bubble, how can I change them ?
I think there is property in the class.

![screenshot 2015-10-24 14 40 54](https://cloud.githubusercontent.com/assets/2546011/10709187/d7690cd0-7a5d-11e5-91fa-2672e993c0da.png)

Best Regards,

**Comment by Spettacolo83** [comment]
Did you find that property?
