### ISSUE TITLE
Change position of Avatar

### ISSUE THREAD

**Issue by Abhishek-addweb** [jessesquires/JSQMessagesViewController#1277]
Can we able to change the postion of avatar / profile image from bottom to top similar to skype in single thread page. 
Note: Github also follows the same.

**Comment by zwang** [comment]
Checkout the answer here. What I did is to remove the constraint on Avatar Container related to Cell Bottom Label and change it to AvatarContainer.top = BubbleTopLabel.bottom. Hope this help. 
https://github.com/jessesquires/JSQMessagesViewController/issues/1198

**Comment by jessesquires** [comment]
Thanks @zwang :smile:

**Comment by Qingzhaowang** [comment]
Thanks

**Comment by b-e-r-t-o** [comment]
@zwang @Qingzhaowang  How did you get this to work? I checked #1198, but it's still not clear how these properties are set.
