### ISSUE TITLE
Warning: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'NSUInteger' (aka 'unsigned int') vs 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') for the following

### ISSUE THREAD

**Issue by nabil-takla** [jessesquires/JSQMessagesViewController#1278]
I get the following warning when I compile JSQMessagesViewController.m:

Conflicting return type in implementation of 'supportedInterfaceOrientations': 'NSUInteger' (aka 'unsigned int') vs 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') for the following:

- (UIInterfaceOrientationMask)supportedInterfaceOrientations
{
    if ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPhone) {
        return UIInterfaceOrientationMaskAllButUpsideDown;
    }
    return UIInterfaceOrientationMaskAll;
}

I'd appreciate any help. Thanks!

**Comment by svtechnology** [comment]
You can safely ignore that error message or if you want to silence it, there are two ways of doing it.

    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Woverriding-method-mismatch"
    #pragma clang diagnostic ignored "-Wmismatched-return-types"
    - (UIInterfaceOrientationMask)supportedInterfaceOrientations
    #pragma clang diagnostic pop

OR

    #if __IPHONE_OS_VERSION_MAX_ALLOWED < 90000  
    - (NSUInteger)supportedInterfaceOrientations  
    #else  
    - (UIInterfaceOrientationMask)supportedInterfaceOrientations  
    #endif 

PS: I prefer the second one.

**Comment by jessesquires** [comment]
Using Xcode 7 should not produce this warning.

Unless, maybe, you compiling for iOS 7?

**Comment by jessesquires** [comment]
Thansk @svtechnology ! :smile:

**Comment by Amar04** [comment]
Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')

warning semantic issue in xcode8.2.1

**Comment by Amar04** [comment]
pls help me

**Comment by Amar04** [comment]
- (NSUInteger)supportedInterfaceOrientations
{
    // we could have simply not implemented this, but we choose to call super to make explicit that we
    // want the default behavior.
 return [super supportedInterfaceOrientations];
}

**Comment by Amar04** [comment]
(NSUInteger)supportedInterfaceOrientations
{
// we could have simply not implemented this, but we choose to call super to make explicit that we
// want the default behavior.
return [super supportedInterfaceOrientations];
}


Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')

warning semantic issue in xcode8.2.1
