### ISSUE TITLE
No long press menu on media messages

### ISSUE THREAD

**Issue by ebbe-brandstrup** [jessesquires/JSQMessagesViewController#1279]
Text message cells support long pressing for a menu with copy and optionally delete options. Media messages (I've only tried with photo messages) do not (simply try the first demo).

I've been trying to figure out how to enable it for media messages, but without luck! I seem to remember some comment in another issue about it being explicitly disabled for media messages somehow, but I cannot find any code that does so.

Can anyone please point me in the right direction?

**Comment by ebbe-brandstrup** [comment]
Oh... I continued searching and finally found that the menu is disabled for media messages in the shouldShowMenuForItemAtIndexPath method in JSQMessagesViewController.m.

From some of the comments in that method, it sounds like the menu I get on text messages isn't intended to be present either because there is a conflict between the default menu and the UIMenuController JSQM asks us to register menu items on?

As far as I've understood, I need the shouldShowMenuForItemAtIndexPath method to return true in any case to be able to allow deletion of media messages.

**Comment by ebbe-brandstrup** [comment]
I now managed to get the long press menu working for all the message types (swift code in my JSQMessagesViewController subclass):

```
override func collectionView(collectionView: UICollectionView, shouldShowMenuForItemAtIndexPath indexPath: NSIndexPath) -> Bool {
    // Do the custom JSQM stuff
    super.collectionView(collectionView, shouldShowMenuForItemAtIndexPath: indexPath)
    // And return true for all message types (we don't want the long press menu disabled for any message types)
    return true
}
```

I don't use any custom menu options, only copy and delete, so after registering the delete action with ```JSQMessagesCollectionViewCell.registerMenuAction(Selector("delete:"))``` in ```viewDidLoad``` I have the menu I need.

However, does this somehow flow against the current?

**Comment by GianniCarlo** [comment]
@ebbe-brandstrup The only problem I had was that the menu was showing up in the middle of the cell instead of on top of my media view. So I had to comment out `return NO;` from JSQMessagesViewController implementation of `collectionView:shouldShowMenuForItemAtIndexPath:`. I haven't had any issues so far

**Comment by GianniCarlo** [comment]
@ebbe-brandstrup oh by the way, I do have custom menu options too

**Comment by ebbe-brandstrup** [comment]
@GianniCarlo Thanks, good to hear that this approach hasn't caused you any issues.

**Comment by skensell** [comment]
Overriding almost worked for me, but it crashed when I tapped "Copy".  You have to make sure that the `text` method of your `JSQMessageData` object returns a non-nil string. Hope it helps someone.

**Comment by jayjayesh** [comment]
Hi skensell, Can you past code, How i can prevent  text method of JSQMessageData return non-nil string.

**Comment by skensell** [comment]
@jayjayesh I have a class which implements the `JSQMessageData` protocol and has a text method defined like this:
```Objective-C
- (NSString *)text {
    return self.message ? : @"";
}
```
This way, the text will never be nil.

**Comment by michaelkirk** [comment]
Thanks for the workaround @ebbe-brandstrup! 

Is this a bug, or is there a design reason the long-press-menu would be disabled for media messages?

**Comment by michaelkirk** [comment]
@skensell , @jayjayesh - returning the empty string will keep it from crashing, but you aren't actually allowing your users to copy those items. A better solution would be to not offer the "copy" action for media messages.

```

```

**Comment by eliburke** [comment]
Or.... dare I say it... implement copy:

**Comment by basawarajh-cuelogic** [comment]
Hi,
How to handle delete action in JSQMessageController, I have implemented method 

        override func collectionView(collectionView: JSQMessagesCollectionView!, didDeleteMessageAtIndexPath indexPath: NSIndexPath!) {
        self.collectionView?.deleteItemsAtIndexPaths([indexPath])
    }

Also override method 

        override func collectionView(collectionView: UICollectionView, shouldShowMenuForItemAtIndexPath indexPath: NSIndexPath) -> Bool {
        // Do the custom JSQM stuff
        super.collectionView(collectionView, shouldShowMenuForItemAtIndexPath: indexPath)
        // And return true for all message types (we don't want the long press menu disabled for any message types)
        return true
    }
    
      override func collectionView(collectionView: UICollectionView, canPerformAction action: Selector, forItemAtIndexPath indexPath: NSIndexPath, withSender sender: AnyObject?) -> Bool {
        super.collectionView(collectionView, canPerformAction: action, forItemAtIndexPath: indexPath, withSender: sender)
        return true
    }
    
    override func collectionView(collectionView: UICollectionView, performAction action: Selector, forItemAtIndexPath indexPath: NSIndexPath, withSender sender: AnyObject?) {
        super.collectionView(collectionView, performAction: action, forItemAtIndexPath: indexPath, withSender: sender)
    }

but i get crash on menu item what else to be done to work, any help would be appreciated, thanks in advance.
