### ISSUE TITLE
The bubble image arrow is always on the right direction? 

### ISSUE THREAD

**Issue by whatya** [jessesquires/JSQMessagesViewController#1280]
i have a problem, the datasource method to get the bubble image for media message never called, it is only called for text message, so when i load message from core data, even the message ID is from others, the bubble arrow is still on the right.
![simulator screen shot 2015 10 26 2 08 36](https://cloud.githubusercontent.com/assets/4310745/10722414/11b8e822-7beb-11e5-987f-4b42ca81bd17.png)

**Comment by lopper** [comment]
Hi, 

Set the appliesMediaViewMaskAsOutgoing property of the JSQPhotoMediaItem to either YES or NO. This will change the location of the bubble arrow on images.

JSQPhotoMediaItem *photo = [[JSQPhotoMediaItem alloc] initWithImage:image];
photo.appliesMediaViewMaskAsOutgoing  = NO;

**Comment by whatya** [comment]
@lopper thank you , now its works propertly

**Comment by passivebit** [comment]
Hi, I am facing this problem even for text message inputs
![simulator screen shot 17-nov-2016 6 13 34 pm](https://cloud.githubusercontent.com/assets/20870544/20389836/b12bea52-acf1-11e6-97af-e48dcb13ec06.png)
I have followed the DemoMessagesViewcontroller as given in github.
Please help!
