### ISSUE TITLE
Update non-modular import

### ISSUE THREAD

**Issue by baoluo** [jessesquires/JSQMessagesViewController#1283]
Update non-modular import #import in the file JSQSystemSoundPlayer+JSQMessage.h like so : @import JSQSystemSoundPlayer;

It's required if you want to build the lib within Xcode7.1

**Comment by jessesquires** [comment]
Hey @baoluo - The demo project is building fine under Xcode 7.1. :smile: 

Sounds like you have some issues with your project setup.

**Comment by baoluo** [comment]
Hello @jessesquires,

Thank you for your response, it does't change anything for you, but for those who use Xcode7.1 and Swift it will. 

I made this project https://github.com/processone/xmpp-messenger-ios, and some user reported the issue when they upgraded to Xcode 7.1
