### ISSUE TITLE
How can you set the font for individual messages?

### ISSUE THREAD

**Issue by muuhoffman** [jessesquires/JSQMessagesViewController#1285]
I would like some messages to have 12pt italic font, and some messages to 17pt normal font.  Where and when should I set the font so that is applied to that cell?  Currently I'm able to properly size the cell by doing this (see code below), but when I try to set the font of the cell in cellForItemAtIndexPath, its not always working:

        override func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        let messageItem = self.collectionView(self.collectionView, messageDataForItemAtIndexPath: indexPath)
        print("size for item at index path")
        // if narrator message
        if messageItem.senderId() == Constants.NarrationSenderName {
            self.collectionView?.collectionViewLayout.messageBubbleFont = narrationFont
        }
        else {
            self.collectionView?.collectionViewLayout.messageBubbleFont = messageFont
        }
        return self.collectionView!.collectionViewLayout.sizeForItemAtIndexPath(indexPath)
    }

Specifically, it seems that on load, the cells do not appear as they should, but on reloadData they do.

**Comment by jessesquires** [comment]
Hey @muuhoffman :smile: -- multiple fonts like this are not supported right now.

This will be fixed by #572.
