### ISSUE TITLE
JSQPhotoMediaItem - Image was hidden

### ISSUE THREAD

**Issue by KennyWZhang** [jessesquires/JSQMessagesViewController#1286]
```
Library version(s): 8.0_release
iOS version(s): iOS 9.0
Devices/Simulators affected: iPad Air 2
Complete steps to reproduce the issue:
a) buid & run Demo jsqmessages project (choose iPAD Air 2)
b) "push via storyboar" 
c) "Cmd + ->" to rotate the simulator 
d) scroll the collection view
e) during scrolling, you will find that image is hidden when the image comes near the top or bottom
```

![493b23ee-fdf0-4b6f-a255-e8a9813702ff-image](https://cloud.githubusercontent.com/assets/1762105/10753011/e7619072-7cc8-11e5-9f50-1c92ac95161b.png)

**Comment by Lisajoy512** [comment]
Hi,jessesquires ,I found same issue. Had you solve this problem yet?

**Comment by Lucashuang0802** [comment]
Hey, @KennyWZhang @Lisajoy512. Does the issue still exist from `7.3.4`? I could not replicate it. Can you guys provide more information based on the current version? Thx. 😄

**Comment by KennyWZhang** [comment]
@Lucashuang0802 I came into the issue on 8.0_release.

**Comment by Lucashuang0802** [comment]
@KennyWZhang I am so sorry that I have a hard time to replicate the problem by iPad Air 2 with iOS 9.0. Do you think you can post a video for better clarification? That will be extremely helpful. 😄

**Comment by 3990995** [comment]
最新的开发分支也有这个bug

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
