### ISSUE TITLE
UIToolbar above on top of screen

### ISSUE THREAD

**Issue by Siamaster** [jessesquires/JSQMessagesViewController#1287]
Is it possible to add a UIToolbar to the top of the screen for navigation purposes? I need to add a back button that dismisses the current ViewController.

**Comment by jessesquires** [comment]
Hey @Siamaster :smile: 

Should be possible. However, this doesn't sound specific to the library.

**Comment by Siamaster** [comment]
So there is no easy way, i.e api's provided by the library itself. I have to calculate the toolbars frame myself and then resize the collectionview of the JSQViewController accordingly?

**Comment by Siamaster** [comment]
Ok, I looked at the demo, it was easier than I thought :D

**Comment by jessesquires** [comment]
@Siamaster :smile: :+1:
