### ISSUE TITLE
Is it possible to scroll to bottom on initial load scrollToBottomAnimated:NO, without visible motion? Issue happens in iPhone 5 only. 

### ISSUE THREAD

**Issue by riazhazan** [jessesquires/JSQMessagesViewController#1288]
Is it possible to scroll to bottom on initial load, without visible motion?  If I put scrollToBottomAnimated:NO in viewWillAppear, first the top appeared then jumped to the bottom. This issue happends only in iphone 5 and 5s.

**Comment by jessesquires** [comment]
Thanks @riazhazan !

Looks like this is actually a dupe of #780
