### ISSUE TITLE
Crash iOS9.02 ! Using JSQMessagesViewController (7.2.0) Using JSQSystemSoundPlayer (2.0.1) Xcode 7.1

### ISSUE THREAD

**Issue by Bitrix737** [jessesquires/JSQMessagesViewController#1289]
App, Swift
I just made - pod install 
class ViewController: JSQMessagesViewController {
nothing else managed to do
App Crash at first run!

JSQMessagesViewController.m:233
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: self.senderId != nil'
*** First throw call stack:
(0x186338f5c 0x19ae3ff80 0x186338e2c 0x187227f3c 0x1000d7f3c 0x18b8a7990 0x18b8a7704 0x18b89785c 0x18b896b04 0x18b8961bc 0x18b893454 0x1843359fc 0x18b90775c 0x18bb2c088 0x18bb301a4 0x18bb2d2e4 0x19007f7ec 0x19007fb6c 0x1862f05a4 0x1862f0038 0x1862edd38 0x18621cdc0 0x18b8fc0ac 0x18b8f6f44 0x10003e574 0x19b66a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by svtechnology** [comment]
That error is self explanatory.

The library is expecting the senderId not to be null. Please set the senderId and it should work.

**Comment by Bitrix737** [comment]
tnks, sorry

**Comment by jessesquires** [comment]
Thanks @svtechnology ! :smile: :+1:
