### ISSUE TITLE
How to display an activity indicator message?

### ISSUE THREAD

**Issue by andrewhavens** [jessesquires/JSQMessagesViewController#1291]
I simply want to display a message with a loading/activity indicator. The reason for this is that I would like to handle file uploads in the background but display a "placeholder" message while the file is uploading. How can I display a message with an activity indicator?

**Comment by GianniCarlo** [comment]
@andrewhavens `JSQPhotoMediaItem` already provides this out-of-the-box, if you need it for another type of file then you can tak `JSQPhotoMediaItem` as an example of how to subclass `JSQMediaItem` and implement your own

**Comment by jessesquires** [comment]
Hey @andrewhavens! :smile: @GianniCarlo 's answer is correct.

Thanks @GianniCarlo ! :+1:

**Comment by khunshan** [comment]
@GianniCarlo  can you be more specific how it provides and to access it? I just started using. :8ball:

**Comment by davepatterson** [comment]
@khunshan You can find details of its implementation in the [docs](http://jessesquires.com/JSQMessagesViewController/)

**Comment by khunshan** [comment]
@davepatterson thanks
