### ISSUE TITLE
Long Press stop working after add or delete some cell only ios9

### ISSUE THREAD

**Issue by rafaj10** [jessesquires/JSQMessagesViewController#1294]
Hey guys i'm using this awesome framework, congrats by the way... It was perfect working but its losing longpress after add or delete some cell, any ideas?

A Video about ->
https://dl.dropboxusercontent.com/u/30253301/bug.mov

or

https://vimeo.com/144121726

Tks!

**Comment by jessesquires** [comment]
Thanks @rafaj10 ! :smile: 

Please see the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) and update your issue.

**Comment by sebyddd** [comment]
I am also encountering this issue. It happens randomly as far as I noticed.

**Comment by rafaj10** [comment]
About my case only happens with xcode 7 and ios 9...

Xcode 7.1 its ok...

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
