### ISSUE TITLE
library not found for -lJSQSystemSoundPlayer

### ISSUE THREAD

**Issue by sajadgoudarzi** [jessesquires/JSQMessagesViewController#1295]
Hey guys, I wanna use this great framework, but when i want to run the sample code, face with this error "library not found for -lJSQSystemSoundPlayer", however I added the "JSQSystemSoundPlayer" library manually. could you please help me?
Thanks

**Comment by OhMyApp** [comment]
Hi, the project uses CocoaPods (a dependancy manager: https://cocoapods.org/ ), so you want to open "JSQMessages.xcworkspace" instead of "JSQMessages.xcodeproj". Then Xcode will be able to successfully build and run the app.

**Comment by jessesquires** [comment]
Thanks @OhMyApp ! 

@sajadgoudarzi - this sounds like the problem. :smile:
