### ISSUE TITLE
How to implement delegate method TextView in toolbars

### ISSUE THREAD

**Issue by modiodio** [jessesquires/JSQMessagesViewController#1296]
Hi jess, 
Thanks for you great library
I have a small question I want to know how to implement delegate methode (like textViewShouldEndEditing,  textViewDidEndEditing) of textview in toolbar in order to implement typing indicator to other other.

Sorry for my bad English
Thanks

**Comment by jessesquires** [comment]
Hey @modiodio :smile: 

JSQMessagesViewController implements these methods. You can override them in your subclass.

**Comment by anooj1483** [comment]
I've override two methods `textViewDidBeginEditing` and `textViewDidEndEditing` .
But both are not getting called while typing.

**Comment by lutc** [comment]
I have the same problem. These methods doesn't calls
