### ISSUE TITLE
Crash when textView loose Focus and tableview contains No message

### ISSUE THREAD

**Issue by modiodio** [jessesquires/JSQMessagesViewController#1297]
Hi jess,
I want to report a bug
I am using the current stable version of the Library 7.2.0.
I have a crash when I focus on the textview in toolbar. When I swip to bottom to hide the keybord the application crash. It happend only when there are No messages in the tableview.

**Comment by GianniCarlo** [comment]
@modiodio please copy/paste crash log to have more information about the issue. FYI the library doesn't use a `UITableView` it uses a `UICollectionView`

**Comment by modiodio** [comment]
I have almost no log error.
I only see (lldb) !

**Comment by modiodio** [comment]
I got this error when I updated jsqmessage ! I had not this error before !

**Comment by GianniCarlo** [comment]
Do you have an exception breakpoint enabled? can you check your stack and see if it hangs in one of the library functions?

**Comment by modiodio** [comment]
@GianniCarlo oh yeah it stack on this line it seem to be parse library I am using
0x1002d9828 <+344>: b      0x1002d9834               ; <+356> at PFInternalUtils.m:381
Do you have an idea for this bug ?

**Comment by GianniCarlo** [comment]
mmmmm I haven't use Parse in a while now, but it looks the problem resides with Parse then, you could go ask at [their github](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX) or in [Stackoverflow](http://www.stackoverflow.com)

**Comment by modiodio** [comment]
ok ok thanks for your answer ! it helps me a lot
