### ISSUE TITLE
Broken animation when dismissing keyboard on scroll

### ISSUE THREAD

**Issue by gnrcampos** [jessesquires/JSQMessagesViewController#1299]
I'm not sure if that's actually a bug or if I'm missing something here, but I need to dismiss the keyboard when I scroll the collectionview. To achieve that, I'm using the following line:
self.collectionView.keyboardDismissMode = UIScrollViewKeyboardDismissModeOnDrag;
What happens is that the input view (where the textview, the attachment button and the send button) go back to the the wrong position for a short instant right after the keyboard is dismissed. Here's a video of what happens:
https://www.youtube.com/watch?v=PLxtd5fsw6k
iOS Simulator version 9.1
JSQMessagesViewController version 7.2.0
I tried searching for something similar among other issues but couldn't find anything, if there's already an answer for that, please show me the issue. Thanks for the great job on the library by the way!

**Comment by jessesquires** [comment]
Should be fixed in 7.3

Also will be fixed in 8.0 by 752fd38aa8b899cbe2e21b6595de58920977bfc2
