### ISSUE TITLE
Display cell top label alone

### ISSUE THREAD

**Issue by stefanocdn** [jessesquires/JSQMessagesViewController#1301]
The conversation between 2 users includes additionnal data that is not a message and that I would like to display in the conversation using the top label.

I am trying to display the cell top label alone, without the cell, but so far haven't succeeded since cellForItemAtIndexPath cannot return nil.

Any idea how to display the top label alone? Is therea way to nil the textview? I am trying to subclass the cell but can't find a solution.

**Comment by jessesquires** [comment]
Hey @stefanocdn :smile: 

This isn't currently supported in the library. But will be in the next major release. See the discussion at #321
