### ISSUE TITLE
Load avatar from URL in JSQMessagesViewController using UIImageView+AFNetworking flickering/disappearing

### ISSUE THREAD

**Issue by nnhubbard** [jessesquires/JSQMessagesViewController#1302]
I am using `JSQMessagesViewController` and need to load the avatar images async from a URL. I prefer using `AFNetworking` for this to load the image in my `collectionView:cellForItemAtIndexPath:` method:

    ZSSMessagesAvatarImage *avatarImage = [self.avatars objectForKey:message.senderId];
        if (avatarImage.url) {
            
            [cell.avatarImageView setImageWithURLRequest:[NSURLRequest requestWithURL:avatarImage.url] placeholderImage:nil success:^(NSURLRequest *request, NSHTTPURLResponse *response, UIImage *image) {
                
                cell.avatarImageView.image = image;
                
            } failure:nil];
            
        }
        cell.avatarImageView.clipsToBounds = YES;
        cell.avatarImageView.layer.cornerRadius = 22;
        cell.avatarImageView.hidden = NO;

This does correctly load the correct remove image from the URL. However, after I reload data to show more messages my avatar images disappear or flicker. I have tracked it down to the `avatarImageView` getting set to `nil` in `JSQMessagesCollectionViewCell.m` `prepareForReuse` method. If I comment out that line the avatars never disappear, but they DO get set incorrectly for the wrong user, so obviously I need to reset that `imageView` in that method.

Is there a better way to download and set the avatar image async rather than doing it in the `collectionView:cellForItemAtIndexPath:` method? I saw some other issues about this but they didn't directly address remotely downloading avatar images as you scroll.

**Comment by nnhubbard** [comment]
Nevermind, I found the error in my code.

**Comment by Luke47** [comment]
What was your error @nnhubbard ? Thanks :)

**Comment by nnhubbard** [comment]
It had nothing to do with `JSQMessagesViewController`. I was not loading my additional avatar URLs from my datasource.

**Comment by bystritskiy** [comment]
**Solution on Swift 4**

You can use library "SDWebImage" 
In method:  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell 

`cell.avatarImageView.sd_setImage(with: URL(string: "https://requizit.ru/assets/users/\(id!)/ava.jpg"))
cell.avatarImageView.sd_setShowActivityIndicatorView(true)`
