### ISSUE TITLE
Reduce Space between inputViewController and collection view

### ISSUE THREAD

**Issue by Abhishek-addweb** [jessesquires/JSQMessagesViewController#1304]
I wish to reduce the the space between inputViewController and collection view

**Comment by jessesquires** [comment]
Hey @Abhishek-addweb :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
