### ISSUE TITLE
Send button only responds to touch on left half of button

### ISSUE THREAD

**Issue by GabrielMSharp** [jessesquires/JSQMessagesViewController#1305]
Using iOS 9 in the Simulator rightBarButtonItem responds perfectly to touch.
Using iOS 9 on an actual device (iPhone 5s) the Send (rightBarButtonItem) button only seems to respond to touch on its left side. Including when button width is resized.

This appears in the project demo as well as my production app. I haven't tested iOS 8/7 so maybe Apple made some changes perhaps surrounding buttons near the edge of screens?

I've checked for the button exceeding superview bounds and for other views capturing the touch event, but can see nothing. UIWindow and the View Controller bounds also appear fine.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
