### ISSUE TITLE
Input view is stuck behind Keyboard. background Scrollview is incorrectly positioned.

### ISSUE THREAD

**Issue by moyoteg** [jessesquires/JSQMessagesViewController#1306]
![simulator screen shot nov 6 2015 4 29 28 pm](https://cloud.githubusercontent.com/assets/574112/11011298/cb9f6f02-84a3-11e5-9fa7-fc7d77d0832b.png)
<img width="684" alt="screen shot 2015-11-06 at 4 29 42 pm" src="https://cloud.githubusercontent.com/assets/574112/11011301/d074011e-84a3-11e5-91f7-efceba26d549.png">

**Comment by Cellard** [comment]
Got the same issue. Wanna see sources?

**Comment by jessesquires** [comment]
Please see #179 and the other [duplicates](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+tabbar+is%3Aclosed).

Thanks! :smile:

**Comment by Cellard** [comment]
My view has no tabbar

**Comment by Cellard** [comment]
@jessesquires, please watch http://101media.ru/JSQMessages-kbd.mov
See how keyboard covers the input view. What issue is this?

**Comment by jessesquires** [comment]
Hey @cellard :smile:

My first guess is that you aren't calling super from the view lifecycle methods.

**Comment by Cellard** [comment]
Thank you!
