### ISSUE TITLE
Assertion failure on JSQMessage.m:52

### ISSUE THREAD

**Issue by dpreston10** [jessesquires/JSQMessagesViewController#1308]
Can anyone give me a suggestion as to what this might be on my chat view controller. It doesn't crash but doesn't show the messages either.

*** Assertion failure in -[JSQMessage initWithSenderId:senderDisplayName: date :text:], /Users/dpreston10/Dropbox/Pesto/Pods/JSQMessagesViewController/JSQMessagesViewController/Model/JSQMessage.m:52

**Comment by jessesquires** [comment]
hey @dpreston10 :smile: 

All you need to do is look at the source. :smile: 

https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Model/JSQMessage.m#L52

**Comment by dpreston10** [comment]
@jessesquires 
yep and i was staring at the issue the issue in my code the whole time!! :smile:
