### ISSUE TITLE
Can you give me more example

### ISSUE THREAD

**Issue by Clever91** [jessesquires/JSQMessagesViewController#1310]
I am new in swift 2. I found this tutorial https://www.syncano.io/blog/create-ios-chat-app-part1/ but not more tutorials. plz give me same examples like upload image or set navigation right image. Thanks a lot !

**Comment by jessesquires** [comment]
Hey @Clever91 :smile: there's a demo app in the repo.

**Comment by Clever91** [comment]
@jessesquires you are rigth but i need example in swift. i don't know objective c well

**Comment by SASDOE** [comment]
@Clever91 https://github.com/firebase/ios-swift-chat-example/tree/master/FireChat-Swift

This is an example app using swift and JSQMessages

**Comment by Clever91** [comment]
@SASDOE thanks man
