### ISSUE TITLE
JSQMediaLocation does not reload

### ISSUE THREAD

**Issue by fede1608** [jessesquires/JSQMessagesViewController#1312]
When a Location message is one of the first message that appears after opening the controller it only shows a  loading animation, it wont refresh until I scroll the collection, and the cell gets redrawn.

I initialized the object like this: 
`let location :CLLocation = CLLocation(latitude: json["latitude"].doubleValue, longitude: json["longitude"].doubleValue)`
`JSQLocationMediaItem(location: location)`

I had to initialize it with nil and then set a completion callback that reloads the collectionView

**Comment by jessesquires** [comment]
Hey @fede1608 :smile: - There's an example of this in the demo app

**Comment by salyangoz** [comment]
Dear @jessesquires could you please show us the demo for the swift. We are having the same problem. Always spinning. Do you have a swift code block for this? Thanks.

**Comment by bport95** [comment]
I am also having the same issue with location messages not loading. I have looked over the demo code and can't seem to find what is causing the issue

**Comment by minglini** [comment]
Same issue here, any updates?

**Comment by bacancyhima** [comment]
JSQLocationMediaItem is setting location each time when collectionview reloads. so it returns empty bubble until location reloads. i don't want to reload other JSQLocationMediaItem while adding new item, anyone having solution for this?
