### ISSUE TITLE
Layout issue if using message view controller as a child view controller with autolayout.

### ISSUE THREAD

**Issue by markst** [jessesquires/JSQMessagesViewController#1314]
If adding a message view controller which uses auto layout to size to the same as it's superview, it is not possible to layout the collection view frame before `viewWillAppear:` occurs. 

Which means when `[self.view layoutIfNeeded]` is called on `viewWillAppear:` the frame size of the `UICollectionView` is wrong. 

I can provide an example.

**Comment by markst** [comment]
a solution for this is to add a width & height constraint before adding to the superview:

```
[chatVC.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:[view(width)]"
                                                                    options:0
                                                                    metrics:@{@"width":@(self.containerView.bounds.size.width)}
                                                                      views:@{@"view":chatVC.view}]];
[chatVC.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:[view(height)]"
                                                                    options:0
                                                                    metrics:@{@"height":@(self.containerView.bounds.size.height)}
                                                                      views:@{@"view":chatVC.view}]];
```

**Comment by markst** [comment]
constraints I wish to use rather than width & height:

```objc
[self.containerView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[view]|"
                                                                           options:0
                                                                           metrics:nil
                                                                             views:@{@"view":chatVC.view}]];
[self.containerView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|[view]|"
                                                                           options:0
                                                                           metrics:nil
                                                                             views:@{@"view":chatVC.view}]];
```

**Comment by james-teeps** [comment]
I was having the same issue - my chat view controller was embedded in a container view controller. I was able to fix the issue by forcing a layout pass just before the chat view controller is added to its container:

```
- (void)willMoveToParentViewController:(UIViewController *)parent {
  [super willMoveToParentViewController:parent];
  [self.view layoutIfNeeded];
}
```

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
