### ISSUE TITLE
cellBottomLabel not show, how to define the height?

### ISSUE THREAD

**Issue by ctoto93** [jessesquires/JSQMessagesViewController#1315]
I want to show "hh:mm" label below message content. Similar to image below (see the purple circle)
![05-02-instagrat](https://cloud.githubusercontent.com/assets/6441610/11202658/091a41aa-8d1d-11e5-9701-922897109c3e.png)

Here is how I change the cellBottomLabel:

     override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let msg = messages[indexPath.item]
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        cell.textView?.textColor = UIColor(CGColor: CGColor.colorWithHex(0x4f4f4fff))
        cell.cellBottomLabel?.text = Common.hourMinuteLabel(msg.date)
        
        return cell
    }

My assumption is, I need to define the height of cellBottomLabel, how to do that?

**Comment by radoslavyordanov** [comment]
Override this func:
    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
        return CGFloat(20)
    }

It's found in the JSQMessagesCollectionViewDelegateFlowLayout.

**Comment by radoslavyordanov** [comment]
Also instead of hacking into the cell to display the text in the cellBottom you can use this func:

    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
         return NSAttributedString(string:"test")
    }

**Comment by jessesquires** [comment]
That's correct. Thanks @radoslavyordanov ! :smile:

**Comment by ctoto93** [comment]
Thank you, it works! @radoslavyordanov
