### ISSUE TITLE
Layout Constraints Override when Adding Button in Storyboard

### ISSUE THREAD

**Issue by cloud-tribal** [jessesquires/JSQMessagesViewController#1318]
I simply add a button in Storyboard and give it Top and Leading constraints (20, 20).
In simulator nothing shows up.

I add addSubview(button) and bringSubviewToFront(button) and then it shows up.
But it's stuck top-left corner.

I mess with constraints, nothing changes.

Do I have to do this programmatically?

**Comment by jessesquires** [comment]
Hey @cloud-tribal ! :smile: 

Sounds like this is a more general question about layout constraints, not specific to this library. It might be better to check StackOverflow instead.
