### ISSUE TITLE
Input view bounces back up when keyboard is not visible

### ISSUE THREAD

**Issue by mroushdy** [jessesquires/JSQMessagesViewController#132]
![screen shot 2014-01-10 at 6 34 06 pm](https://f.cloud.github.com/assets/1895421/1889012/18dd28cc-7a15-11e3-83fa-0bb235fdcf62.png)
If you dismiss the keyboard by scrolling then scroll in the opposite direction as soon as the keyboard disappears the keyboard stays down while the input view jumps up above the hight of the keyboard.

**Comment by RajChanchal** [comment]
I am using JSQMessagesViewController in a container view. Whenever the input textfield is tapped for writing a message, the chat messages view along with input container view disappears only the keyboard is shown. This happens for iOS 8 and above.
