### ISSUE TITLE
self.collectionView!.indexPathsForVisibleItems() and visibleCells() are empty

### ISSUE THREAD

**Issue by top2tech** [jessesquires/JSQMessagesViewController#1320]
Both indexPathsForVisibleItems and visibleCells are empty, but actually it contains 51 messages as numberOfItemsInSection shows.

This is important to decide if we should scroll to bottom depends on if the last message is at the bottom of the screen.

(lldb) po self.collectionView!.indexPathsForVisibleItems()
0 elements

(lldb) po self.collectionView!.visibleCells()
0 elements

(lldb) po self.collectionView!.numberOfItemsInSection(0)
51

**Comment by jessesquires** [comment]
Thanks @top2tech !

It's hard to say what's wrong without more information. You may want to post on StackOverflow.

These 2 methods *can* return `nil`.

**Comment by AidenWK** [comment]
I have the same, so weird
