### ISSUE TITLE
Remove menu actions from inputToolbar.contentView.textView

### ISSUE THREAD

**Issue by lobyncev** [jessesquires/JSQMessagesViewController#1321]
I want add custom menu action to JSQMessagesCollectionViewCell:
[JSQMessagesCollectionViewCell registerMenuAction:@selector(customAction:)]; (see in your demo code), then custom menu actions showing in content menu inputToolbar.contentView.textView.
How not showing custom action in inputToolbar.contentView.textView?
![img_0512](https://cloud.githubusercontent.com/assets/14034793/11500369/c4dcaec0-983d-11e5-83c3-85b65d582780.jpg)

**Comment by lobyncev** [comment]
![img_0512](https://cloud.githubusercontent.com/assets/14034793/11500328/79e87354-983d-11e5-8d84-e8289a76b8fd.jpg)

**Comment by wdcurry** [comment]
This would be awesome, but if memory serves, this is tied to how Apple has setup the hierarchy of things.

**Comment by jessesquires** [comment]
Hey @lobyncev :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)

**Comment by jessesquires** [comment]
I believe @wdcurry is correct. Unfortunately, I can't confirm right now.

**Comment by dterekhov** [comment]
Hi guys! I found a way to add additional menu items to bubbles exclude inputToolbar.contentView.textView without touch any code of original JSQMessagesViewController.

In my subclass (for example DemoMessagesViewController) I added a private category at the top class:

/**
 *  Category for using private members to handle appearing menu by long tap
 */
@interface JSQMessagesViewController (Private)
@property (nonatomic, readonly) NSIndexPath *selectedIndexPathForMenu;
- (void)jsq_didReceiveMenuWillShowNotification:(NSNotification *)notification;
@end

@implementation DemoMessagesViewController
- (void)viewDidLoad {
    [super viewDidLoad];
    // Register additional long tap menu actions
    [JSQMessagesCollectionViewCell registerMenuAction:@selector(customAction:)];
}

#pragma mark - Private
- (void)jsq_didReceiveMenuWillShowNotification:(NSNotification *)notification {
    // Setup menuItems for bubble cell
    if (super.selectedIndexPathForMenu) {
        [UIMenuController sharedMenuController].menuItems = @[ [[UIMenuItem alloc] initWithTitle:@"Custom Action"
                                                                                          action:@selector(customAction:)] ];
    }
    
    [super jsq_didReceiveMenuWillShowNotification:notification];
    
    // Setup menuItems for input TextView
    [UIMenuController sharedMenuController].menuItems = nil;
}
@end

I tried any variants. But this one works for me.

**Comment by jessesquires** [comment]
Thanks for the update @dterekhov !

Maybe the library can provide a method that clients can override?

```objective-c
- (void)didReceiveMenuWillShowNotification:(NSNotification *)notification forIndexPath:(NSIndexPath *)indexPath;
```

The private method can call this, and clients can override to do what you've done here.

Would this work for you? Would you like to submit a PR for this?

**Comment by wdcurry** [comment]
This would be very welcome..

**Comment by eliburke** [comment]
@jessesquires Take a look at #1563. 
Thoughts:
- existing behavior is preserved.. if you are adding a custom menu item in your JSQMessagesViewController subclass, it will show up for all cells and the inputView.
- I don't know if the collectionView's datasource was the right place to put this
- as an alternative, registerAction could take an additional parameter for the menu item's name and we could handle this automatically

**Comment by jessesquires** [comment]
Based on #1563 (a breaking change) going to bump this to v8.0 😄

**Comment by eliburke** [comment]
Ok, but FWIW, it doesn't break anything. The protocol is optional and the behavior of one's menus is unchanged if you don't implement the new function.
