### ISSUE TITLE
 Swift pod can't depend on JSQMessagesViewController framework (v.7.2.0)

### ISSUE THREAD

**Issue by marco1981** [jessesquires/JSQMessagesViewController#1322]
I have a new pod (written in Swift) using CocoaPods in my private repository.  It will depends on JSQMessagesViewController framework.

Unfortunately the pod validation fails since it is not possible to build JSQMessagesViewController.

```
#import "/var/folders/l4/wwg_21kn59l0kqsw2_7fl_140000gn/T/CocoaPods/Lint/Pods/Target Support Files/JSQMessagesViewController/JSQMessagesViewController-umbrella.h"

/var/folders/l4/wwg_21kn59l0kqsw2_7fl_140000gn/T/CocoaPods/Lint/Pods/Target Support Files/JSQMessagesViewController/JSQMessagesViewController-umbrella.h:3:9: note: in file included from /var/folders/l4/wwg_21kn59l0kqsw2_7fl_140000gn/T/CocoaPods/Lint/Pods/Target Support Files/JSQMessagesViewController/JSQMessagesViewController-umbrella.h:3:
#import "JSQSystemSoundPlayer+JSQMessages.h"

/var/folders/l4/wwg_21kn59l0kqsw2_7fl_140000gn/T/CocoaPods/Lint/Pods/JSQMessagesViewController/JSQMessagesViewController/Categories/JSQSystemSoundPlayer+JSQMessages.h:19:9: error: include of non-modular header inside framework module 'JSQMessagesViewController.JSQSystemSoundPlayer_JSQMessages'
#import <JSQSystemSoundPlayer/JSQSystemSoundPlayer.h> 
```

To be able to build it, file ```JSQSystemSoundPlayer+JSQMessages.h``` should be changed by replacing line 19  ```#import <JSQSystemSoundPlayer/JSQSystemSoundPlayer.h>``` with this line ```@import JSQSystemSoundPlayer;```

This is an extract of my podspec:
```
Pod::Spec.new do |s|
s.name         = 'MyPod'
s.version      = '0.0.20'
s.platform     = :ios, '8.0'
s.requires_arc = true
s.source_files = 'MyPod/**/*{swift}'
s.frameworks   = 'UIKit'
s.dependency "JSQMessagesViewController", "7.2.0"
end
```

We need to have a release or branch to reference to be able to use JSQMessagesViewController also inside a swift pod.

Important note: I can't use bridging header since it is not supported on Cocoapods. I simply import the module in my swift files in this way:
```import JSQMessagesViewController```

**Comment by marco1981** [comment]
Pull request 1325 fixes it. https://github.com/jessesquires/JSQMessagesViewController/pull/1325

**Comment by jessesquires** [comment]
Closing this issue as a dupcliate in favor of #1284
