### ISSUE TITLE
Dictation Indicator issue (jsq_stringByTrimingWhitespace)

### ISSUE THREAD

**Issue by azonov** [jessesquires/JSQMessagesViewController#1323]
![thumb_img_0244_1024](https://cloud.githubusercontent.com/assets/6952285/11363725/b498e20e-92ac-11e5-9207-8b7ff265a049.jpg)
- (NSString *)jsq_stringByTrimingWhitespace
  {
  NSMutableCharacterSet *characterSet = [NSMutableCharacterSet characterSetWithCharactersInString:@"￼"];//ignoring Unicode Character 'OBJECT REPLACEMENT CHARACTER' (U+FFFC)
  [characterSet formUnionWithCharacterSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
  return [self stringByTrimmingCharactersInSet:characterSet];
  }

**Comment by jessesquires** [comment]
Hey @azonov - Please review the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) and provide more information. :smile:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
