### ISSUE TITLE
Chage text and font to JSQMessagesBubbleImageFactory

### ISSUE THREAD

**Issue by devloopers** [jessesquires/JSQMessagesViewController#1326]
Hi, 
first of all congratulations for the library.
I want to change color and font to JSQMessagesBubble, but don't find the method for the change color of text and change a font.

Thanks

**Comment by nhnam** [comment]
I override this method:
- (NSAttributedString *)collectionView:(JSQMessagesCollectionView *)collectionView attributedTextForCellBottomLabelAtIndexPath:(NSIndexPath *)indexPath {
   ChatMessage*mess = [chatMessages objectAtIndex:indexPath.row];
   NSAttributedString *att = [[NSAttributedString alloc] initWithString:mess.content attributes:@{ NSFontAttributeName:[UIFont myFontOfSize:15]}];
   return att;
}

**Comment by davepatterson** [comment]
Not sure if you're looking to do this on a cell by cell basis or if you would like to do this for all cells. Assuming that you're trying to do it for all cells, you can alter the font by overriding the messageBubbleFont property of JSQMessagesViewController's collection view. Here's an example of doing this: `self.collectionView.collectionViewLayout.messageBubbleFont = [UIFont fontWithName:@"Helvetica" size:20];`

**Comment by davepatterson** [comment]
Better yet, since JSQMessagesViewController adheres to the `JSQMessagesCollectionViewDataSource` protocol, which adheres to the `UICollectionViewDataSource` protocol, you can actually override `UICollectionViewDataSource`'s `- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` method in you JSQMessagesViewController subclass.

**Comment by jessesquires** [comment]
Thanks @davepatterson ! :smile:

**Comment by MHX792** [comment]
Unfortunately increasing the font size as described by @davepatterson does not change the bubble size automatically?!

I am trying to increase the font size (and the bubble size) when only a single emoji is sent:

            let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
            
            if message.text.isEmoji {
                cell.textView?.font = UIFont.systemFontOfSize(60)
            }

            return cell

This is what it looks like: 

![screen shot 2016-08-23 at 13 38 36](https://cloud.githubusercontent.com/assets/12123471/17889050/f11656ce-6936-11e6-87ef-85aafe822d29.png)

**Comment by jessesquires** [comment]
@MHX792 - Please only comment on 1 issue or open 1 issue. Leaving the same comment in multiple places creates confusion and more work for maintainers. 😊
