### ISSUE TITLE
UITabbar: How to resize frame of chat view and input toolbar

### ISSUE THREAD

**Issue by maksumon** [jessesquires/JSQMessagesViewController#1330]
Hi,

I've been trying to resize frame of the chat view and input toolbar. My view has a tab bar added programmatically and there will be a button right on top of the tab bar based on condition. But I'm finding it difficult in resizing the frame. I've tried following code but not working at all:

self.collectionView.frame = CGRectMake(self.collectionView.origin.x, 0, self.collectionView.width, self.collectionView.height - 100);
    self.inputToolbar.frame = CGRectMake(self.inputToolbar.origin.x, self.inputToolbar.origin.y - 100, self.inputToolbar.width, self.inputToolbar.height);

Would anyone please help me in resizing the chat view and input toolbar? I've also attached an image of how it looks like with tab bar added programmatically.

![simulator screen shot nov 29 2015 1 11 36 am](https://cloud.githubusercontent.com/assets/1089462/11453031/494e7ef4-9636-11e5-8998-de584e0bbdf7.png)

**Comment by jessesquires** [comment]
Thanks @maksumon ! :smile: 

Please see #179 for information on this.
