### ISSUE TITLE
Add attributedTextForCellTopLabelAtIndexPath when there are no messages?

### ISSUE THREAD

**Issue by cerupcat** [jessesquires/JSQMessagesViewController#1331]
Is it possible to have an attributedTextForCellTopLabelAtIndexPath when there are no messages? I'm trying to show some default text when the state is empty and there are no messages. Is there a built in way to do this?

**Comment by jessesquires** [comment]
Hey @cerupcat :smile:  

There's no built-in way to do this in the library. It's left up to the client.

You could:

1. Add a header view to the collection view
2. Add a completely new UIView for your "empty state" view

**Comment by dkc1987** [comment]
Thanks for you reply. It would be great if JSQMessagesViewController comes with new message composer too.
