### ISSUE TITLE
How to model empty/compose JSQMessageViewController

### ISSUE THREAD

**Issue by dkc1987** [jessesquires/JSQMessagesViewController#1332]
Hi,

I'm using JSQMessageViewController in my project and I feel its awesome. You guys did a brilliant job. I have a question on this. When I press compose new message how I can model empty JSQMessageViewController similar to new message compose? Is that possible with JSQMessageViewController?

Thanks for your brilliant work.

**Comment by jessesquires** [comment]
Thanks @dkc1987 ! :smile: 

I think the answer in #1331 should help. If not, let me know!
