### ISSUE TITLE
I Cant Do Any Demo

### ISSUE THREAD

**Issue by dangnguyenvu8893** [jessesquires/JSQMessagesViewController#1333]
Anyone can send me any simple demo, i can't do any thing ;'(
Sorry for my bad english

**Comment by tuanpa199** [comment]
Hi lazy man,
please code and post issues here.

**Comment by dangnguyenvu8893** [comment]
ok. wait for minutes

**Comment by dangnguyenvu8893** [comment]
![screen shot 2015-12-02 at 12 31 59 pm](https://cloud.githubusercontent.com/assets/13247811/11523005/7f862ff0-98f0-11e5-8c75-8e36ff7ccb16.png)

i just use JSQMessagesCollectionView, add all datasource Method, alway have some issue. Did i miss something

![screen shot 2015-12-02 at 12 34 02 pm](https://cloud.githubusercontent.com/assets/13247811/11523031/c90c5d0c-98f0-11e5-90d0-d517c6812b04.png)

**Comment by sebyddd** [comment]
In `cellForRowAtIndexPath`, you are returning the same thing, which basically, gets you stuck in a infinite recursive loop. Check the implementation for the collectionView's Data Source in the demo project.

**Comment by dangnguyenvu8893** [comment]
Ohm this every one, i had read wrong demo.
I have more question, how can i custom input bar, can i add more button

**Comment by jessesquires** [comment]
Thanks @sebyddd ! :smile:
