### ISSUE TITLE
Abnormal to display the text messages!

### ISSUE THREAD

**Issue by LatteCat** [jessesquires/JSQMessagesViewController#1334]
Hi, everybody here. I have met some problems that some text messages not show completely when I ran the demo for JSQMessageViewController on my iPhone 5s rather than iPhone 5s simulator. Problems show below, the <font color='red'>**red text is missed**</font>:

![img_0433_bug](https://cloud.githubusercontent.com/assets/13290865/11527847/48c54f5e-991e-11e5-9beb-752cf124c96d.png)

I haven't change any word of the demo downloaded from the repository. But the text message does not show completely, or it appended a blank line. These problems only came true on some conditions: 
- Demo runs on the **iPhone** _rather than simulator_.
- Change your **Text Size** to the **SECOND LEVEL** size.

>  On iPhone rather than simulator, you can go to **Text Size** by **_Settings -> Display & Brightness -> Text Size**_. And then change the slider to SECOND LEVEL. It seams like:
> ![simulator_screen_shot_dec_2__2015__17_45_30_bug](https://cloud.githubusercontent.com/assets/13290865/11528226/615217b2-9920-11e5-8213-694cd0cfddc1.png) Reopen the demo on the iPhone, open the JSQMessagesViewController, the default text messages will not show normally.

According some test, I found iPhone 6 plus also has these problem (Of course you should change the **Text Size** to the **SECOND LEVEL** size).

Has anyone met these problems before? I would like to hear any shared experience! Thanks~

**Comment by Grozy** [comment]
:+1:

**Comment by nathanielescribano** [comment]
I notice this for the second level and the lowest level of font size as well. I'm seeing it on the sim and actual device on 9.1.

**Comment by appleios** [comment]
May be calculating text height [as described here](http://stackoverflow.com/questions/5518147/accurately-calculating-text-height-in-cocoa-for-mac-not-ios) will help to solve the issue? ([code](https://github.com/jerrykrinock/CategoriesObjC/blob/master/NS(Attributed)String%2BGeometrics/NS(Attributed)String%2BGeometrics.m))

**Comment by mickamy** [comment]
Anyone have a workaround to solve this issue?
I'm stacking this problem for few days.
I am very new to iOS development and I can't understand Objective-C codes.

Or can we avoid this issue by using an old version of JSQ?

**Comment by TolgaB** [comment]
I can take a look if this issue is still going on.

**Comment by Lucashuang0802** [comment]
Let me update the status a little bit more here. The way to change the accessibility font in simulator is:
> Settings -> General -> Accessibility -> Larget Text

However, it does not seem that we handle accessibility. So, perhaps can you guys give more inside about the issue? Otherwise, we are going to close it. We can create a ticket for handling accessibility.

**Comment by eliburke** [comment]
@Lucashuang0802 that's not 100% true. There is no dynamic font size handling, but JSQ does make a couple of  calls to `[UIFont preferredFontForTextStyle:UIFontTextStyleBody];` which will return different values depending on the device or simulator's settings.

**Comment by Lucashuang0802** [comment]
Hey @eliburke, that's good to know. Regarding this issue, are you able to replicate it? I changed font size and could not replicate by navigating in/out the `JSQVC` or restarting the demo app.

**Comment by eliburke** [comment]
@Lucashuang0802 I'm not, no. 

Perhaps @mickamy or @LatteCat is using a different font via the appearance proxy, or by setting     `self.collectionView.collectionViewLayout.messageBubbleFont` -- can either of you set a breakpoint somewhere and tell us the font family and font size?

**Comment by jessesquires** [comment]
@Lucashuang0802 - this was possibly resolved by #1747

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
