### ISSUE TITLE
[8.0 Release] Community discussion

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1336]
The purpose of this issue is to provide a designated place to discuss the `8.0` release of the library. 

You can find on-going release notes at #1216.

**Comment by kientux** [comment]
Sad that you're going to drop iOS 7 support.

**Comment by harlanhaskins** [comment]
iOS 7 represents less than 10% of all devices, and leaves us with a lot of old code and testing burden to maintain compatibility. If your app still needs to support iOS 7, continue using JSQMessagesViewController 7.x.

**Comment by mriddle** [comment]
Hey @jessesquires is there are an issue that I can follow for extra custom cell support in this release? That is the ability to support multiple outgoing or incoming messages within the one JSQMessagesViewController.

I noticed the behaviour was introduced as part of https://github.com/jessesquires/JSQMessagesViewController/pull/137 and it looks like it may have been removed unintentionally in https://github.com/jessesquires/JSQMessagesViewController/commit/85a65f7 as part of #172 

You mentioned in https://github.com/jessesquires/JSQMessagesViewController/issues/1343 that this would be possible in this release. Will this be done as part of pulling out all cell configuration into cell factory objects?

Was hoping that with a better understanding I may be able to provide some assistance.

**Comment by jessesquires** [comment]
Thanks @mriddle ! Just opened #1720 to track and explain. Let's move this conversation there. 😄

**Comment by asher636** [comment]
Hi, when is the swift 3 version for JSQMessageViewController is releasing? TIA

**Comment by MacMeDan** [comment]
@asher636 JSQMessagesViewController is written in ObjectiveC So you can leverage it with Swift 3 right now. You may be looking for how to do that. There is a Swift3 example included in the project  that will go out with the JSQ v8 but is not dependent on it. If you want to check it out just checkout the Develop branch and pull the latest. Let me know if you need any help 👾

**Comment by asher636** [comment]
Ah man great to hear that. Thank you so much :). You guys are great.

Thanks & Regards,
[image: https://wizdevelopers.com]

**Comment by jessesquires** [comment]
@asher636 -- Currently, inter-op with Swift isn't very great. However, as @MacMeDan mentioned, this will be greatly improved with v8.0 of the library.

**Comment by jyounus** [comment]
@jessesquires I know this is a stupid question, but any idea when v8.0 will be released? I'm asking because I need to implement this into my project. 

I'm currently trying to UI complete my app as much as possible. So the question is, should I start integrating v7 into my Swift 3 project OR if I should rather wait a bit longer and instead focus on functionality on other sections of my app? 

A rough indicator like within the next 2 months or so would be enough for me to decide if I should postpone this for now and come back to it later.

The ongoing release notes says sometime during second half of 2016. But not sure how accurate that still is. :)

**Comment by jessesquires** [comment]
@jyounus - ha 😄 I would go ahead with v7. we're *at least* a few months away, likely more.

**Comment by 3lvis** [comment]
If you're planning to drop iOS 7, are you jumping to iOS 8 or iOS 9?

**Comment by i-am-chris** [comment]
Hello, any news on V8? To get them pistons running in my app too :) 
Thanks.

**Comment by NinoScript** [comment]
What about implementing v8 on top of IGListKit? 😮

**Comment by jessesquires** [comment]
@NinoScript - I've thought about. Still not sure though. I might provide a subspec via cocoapods for this though

**Comment by NinoScript** [comment]
@jessesquires, well It's not like you would be adding some third party dependency where you have no influence. You *are* working in both projects, aren't you?

It sounds like a good idea, but that's only my uninformed opinion. :)

**Comment by jessesquires** [comment]
@NinoScript - Ha, yes 😄

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
