### ISSUE TITLE
Move to TTTAttributedLabel

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1337]
Replace usage of `UITextView` in message cells.

General performance is bad, and worse with iOS 8 regressions.

Issues with `UITextView`: #747, #613, #438, #1247, #1468

https://github.com/TTTAttributedLabel/TTTAttributedLabel

Possibly move to YYText as mentioned below. https://github.com/ibireme/YYText

**Comment by harlanhaskins** [comment]
>1337

I like it.

**Comment by KanybekMomukeyev** [comment]
@jessesquires TTTAttributedLabel also not fast, 
now i am  using label from nimbus kit, this one more faster.

**Comment by appleguy** [comment]
@jessesquires I'm interested in learning about how TTTAttributedLabel could help performance in JSQMessagesViewController - what features does it have that help on that front?

**Comment by jessesquires** [comment]
@appleguy -- In most of my tests, the biggest issue was `UITextView`. Ever since TextKit, performance has regressed and now `UITextView` is super slow. As you saw in #492, in iOS 7 this library's scroll perf was great overall (maybe not perfect on really low-end devices), and we were able to optimize `UICollectionViewLayout` and Auto-Layout.

The primary reasons for using `UITextView` in the first place were: (1) data detectors, (2) familiarity / ease-of-use.

Switching to `TTTAttributedLabel` provides both of these — less of (2), but it's still a `UILabel` subclass, which is familiar.

For me, best case scenario would be zero dependencies, but `TTTAttributedLabel` is a great project.

I definitely don't doubt AsyncDisplayKit — my primary hesitation is ease-of-use / familiarity, and the impact it may have on clients (not saying this is negative or positive). My goal would be to "hide" as much of ASDK as possible internally, but I have a suspicion that clients would *eventually* have to interface with it — maybe not.

**Comment by mindz-eye** [comment]
@jessesquires UITextView also provides a set of default actions for detected links (URLs, phone numbers, locations, etc). TTTAttributedLabel doesn't have these.
I faced the same issue in one of my projects and ended up implementing a small class, which handles link interaction for TTTAttributedLabel or any other text control. See https://github.com/mindz-eye/MYLinkInteraction for details. Feel free to use it if you want, though I understand you try to keep dependencies to a minimum.

**Comment by jessesquires** [comment]
Old attempt at #767

**Comment by dzamani** [comment]
Hi @jessesquires,

I've made an attempt to use TTTAttributedLabel.
I had to update the demo projects (Swift and Obj-c) in order to use a dependency which forced me to use iOS 8.0 for Deployment Target (since it wasn't compatible with iOS 7.0).

My fork is available here : https://github.com/dzamani/JSQMessagesViewController
Could check it out and tell me what I haven't done yet before doing a PR ?

Also, it seems that there is a small glitch when you send a message of more than one line, the refresh of the other sent messages is a little bit strange.

**Comment by zhouzhongguang** [comment]
@jessesquires ,
Why not try to use YYLabel in YYText.
YYLabel has a  asynchronous display mode, that can resolve performance issues.
See https://github.com/ibireme/YYText for details

**Comment by jessesquires** [comment]
Thanks @zhouzhongguang ! We'll consider this.

**Comment by neutralinsomniac** [comment]
I second this. Scrolling performance is really bad even on my iPhone SE with NSAttributedString's

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
