### ISSUE TITLE
Crash on iOS 9 with messageBubbleFont != nil when springiness is enabled

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1338]
Only happens when `springinessEnabled = YES`. Very odd. I was able to repro, but haven't looked into this very deeply.

Related: #1263, #1252, #1217, #1210.

#### Workaround

```
self.springinessEnabled = NO;
```

**Comment by hhanesand** [comment]
Was looking at the stack trace of this crash, and I think its a direct result of a `copyWithZone:` method that sets `messageBubbleFont` to nil when copying an object.

**Comment by jessesquires** [comment]
@hhanesand - yes, that's correct. would you like to submit a PR?

**Comment by alberttai1** [comment]
@jessesquires I'm having this issue without enabling springiness. The weird thing is this only happens when I'm not using cocoapods and manually importing into project. The springiness workaround doesn't fix my problem at all. Is there any other way?

**Comment by jessesquires** [comment]
Can't reproduce this anymore. Going to close.

**Comment by eliburke** [comment]
@jessesquires FWIW I re-tested this a few weeks ago. Does not crash in the simulator but still crashes on hardware 100% of the time. I am of the opinion that it has to do with changing a cell's size while any of the "springiness" animations are occurring.

**Comment by jessesquires** [comment]
@eliburke -- hm.. I tested on device last night. iPhone 6s, iOS 9. 

i was able to repro before, and it was definitely because of `copyWithZone:`

**Comment by jessesquires** [comment]
new idea to guard against this: override `init` and set default values

**Comment by ignacio-chiazzo** [comment]
@jessesquires @Lucashuang0802 @mauruskuehne  In my case I made a workaround setting the  finishReceivingMessageAnimated(false)  as false before calling finishReceivingMessage()
