### ISSUE TITLE
Can i change BubbleImageFactory?

### ISSUE THREAD

**Issue by dangnguyenvu8893** [jessesquires/JSQMessagesViewController#1339]
Hello, can i change BubbleImageFactory turn up like this?
![screen shot 2015-12-07 at 11 49 17 am](https://cloud.githubusercontent.com/assets/13247811/11619263/69a285bc-9cd8-11e5-94ef-a445707fcc84.png)

**Comment by harlanhaskins** [comment]
`BubbleImageFactory` uses [this image](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle/Images/bubble_min%402x.png) by default for right-facing bubbles.

If you wanted to use a custom bubble image, you just need to add it to your Xcode project, figure out where the cap insets are, and instantiate a new `BubbleImageFactory` with that `UIImage` and those `capInsets`.
