### ISSUE TITLE
JSQMessagesViewController use custom nib and override class method in swift

### ISSUE THREAD

**Issue by zwang** [jessesquires/JSQMessagesViewController#1340]
I am trying to follow the guide here to use custom nib with my own swift classes: https://github.com/jessesquires/JSQMessagesViewController/pull/563

However, Xcode give me errors for the code below:

    override class func messagesViewController() -> Self {
        return MessageViewController(nibName: NSStringFromClass(MessageViewController.self), bundle: NSBundle(forClass: MessageViewController.self))
    }

    Controllers/MessageViewController.swift:222:25: Cannot override 'messagesViewController' which has been marked unavailable
    Controllers/MessageViewController.swift:223:16: Cannot convert return expression of type 'MessageViewController' to return type 'Self'

It seems to me the default implementation is not available to swift?

**Comment by jessesquires** [comment]
Thanks @zwang :smile: 

Interesting. At the moment, not 100% sure why this is. Probably because of Swift's initialization rules. I'll look into this for v8.0

**Comment by MacMeDan** [comment]
@zwang I think that https://github.com/jessesquires/JSQMessagesViewController/pull/1481 may help you achieve what you are going for here. Well At least I hope that it does. If you wouldn't mind letting me know if there is anything you don't see covered that would be helpful I will try and add it. Hope that it helps 👷🏼

**Comment by jessesquires** [comment]
We're going to be removing the `nib`s in 8.0 which will fix this issue. Going to close and track this at #1601.
