### ISSUE TITLE
Add resend button into JSQMessagesCollectionViewCell

### ISSUE THREAD

**Issue by wanyue1215** [jessesquires/JSQMessagesViewController#1342]
I want to add an resend button into JSQMessagesCollectionViewCell . What should i do

**Comment by jessesquires** [comment]
Thanks @wanyue1215 ! :smile: 

There are lots of previous questions about customizing cells. You can find the answers here:
https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=is%3Aissue+custom+cells+is%3Aclosed+

**Comment by wanyue1215** [comment]
@jessesquires  thanks 😄
