### ISSUE TITLE
Extra custom cell

### ISSUE THREAD

**Issue by mixmastertube** [jessesquires/JSQMessagesViewController#1343]
Hi,
In addition to incoming and outgoing cells, I need some extra custom cells, these extra cells should include some labels and a button.
This extra cell should be incoming and outgoing, but must coexist with the regular incoming and outgoing message and media cells.

So for what I've read subclassing JSQMessagesCollectionViewCellIncoming and JSQMessagesCollectionViewCellOutgoing cells, it's ok to customize the regular cells, but won't work for me because I need to add an extra type of cell.

Any ideas, how I could do that?

Regards.

**Comment by jessesquires** [comment]
Thanks @mixmastertube ! :smile: 

You might find some help here:
https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=+%5Bcustom+cells%5D+in%3Atitle

Otherwise, #321 and the 8.0 release will make this possible

**Comment by rkumawat** [comment]
Hello anyone help me? in image message bubble i want like this below.

![simulator screen shot 08-aug-2016 6 02 37 pm](https://cloud.githubusercontent.com/assets/2070151/17851676/e2d90a2c-6880-11e6-922e-6621a3a223b6.png)

**Comment by shashank109** [comment]
Hi mixmastertube,
I have similar situation.Have you ever been able to figure out this? Any help would be appreciated.
