### ISSUE TITLE
How do I paste a gif?

### ISSUE THREAD

**Issue by benjaminhallock** [jessesquires/JSQMessagesViewController#1345]
I can paste text, but this keyboard with gifs won't paste.

**Comment by harlanhaskins** [comment]
You'll need to add a `JSQMessagesComposerTextViewPasteDelegate` to the `textView`. Look at [JSQMessagesComposerTextView.h](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Views/JSQMessagesComposerTextView.h#L26) for more information.

**Comment by benjaminhallock** [comment]
The paste option still does not show itself, is there a setting for the UITextView to enable this to work with GIF Keyboards?

**Comment by BillCarsonFr** [comment]
You have to subclass JSQMessagesComposerTextView and override canPerformAction

    override func canPerformAction(action: Selector, withSender sender: AnyObject?) -> Bool {
        if let _ = UIPasteboard.generalPasteboard().image where action == "paste:" {
            return true
        }
        return super.canPerformAction(action, withSender: sender)
    }

Then you have to copy some xibs  (JSQMessagesViewController.xib, and toolbar i think) , tell your MessageView to use it, and then put your custom class for in the  toolbar.

Then as said by harlanhaskins set your delegate for paste
