### ISSUE TITLE
Not able to see text of Bottom Label 

### ISSUE THREAD

**Issue by gs-ronak** [jessesquires/JSQMessagesViewController#1346]
Hi

I am trying to add Sent/Unsent status message to all outgoing chat bubbles. For this, I am retuurning 40 from heightForCellBottomLabelAtIndexPath method.

Also from attributedTextForCellBottomLabelAtIndexPath method I am returning a attributed string. For example,
    NSMutableAttributedString *hogan = [[NSMutableAttributedString alloc] initWithString:@"Presenting the great... Hulk Hogan!"];
    [hogan addAttribute:NSFontAttributeName value:[UIFont systemFontOfSize:20.0] range:NSMakeRange(24, 8)];
    [hogan addAttribute:NSForegroundColorAttributeName value:[UIColor blackColor] range:NSMakeRange(10, 10)];

Now after this space between my cells have increased to 40 but I can't see any text that I am returning as attributed string. Also if I keep increasing the value from 40, space between the cells keep on increasing but cell label text not visible.

Please tell me where I am doing wrong.

**Comment by gs-ronak** [comment]
@jessesquires any chance, can you help me in this?

**Comment by julianljk** [comment]
I'm getting this issue as well, attributedTextForCellBottomLabel, attributedTextForCellTopLabel and attributedTextForMessageBubbleTopLabelAtIndexPath. 

override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        return NSAttributedString(string: "hi")
 }

**Comment by jessesquires** [comment]
Hey @gs-ronak :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)

**Comment by jessesquires** [comment]
@gs-ronak - This is really difficult to try to help debug. I wish I had more time to try to help! :smile: 

If you discover anything new, and think this is a bug, please follow the contributing guidelines to open a bug report. If you can reproduce this in the demo project, that would be most helpful.
