### ISSUE TITLE
Messages shows from bottom to top and limit the size of collection view? Advice appreciated

### ISSUE THREAD

**Issue by zwang** [jessesquires/JSQMessagesViewController#1351]
In my project, I am trying to put a view under the `JSQMessagesCollectionView` and set the background color of `JSQMessagesCollectionView` to be clear color. 

1. I want to limit maximum height of the `collectionView` to certain number, for example 120pt because I don't want the `collectionView` taking all the spaces. Currently I am achieving this by set the `topContentAdditionalInset = self.view.frame.height - collectionViewContentSize self.keyboardController.currentKeyboardFrame.height`. `collectionViewContentSize` needs to be calculated based on the number of message and height of each message cell. Any advice for better approach for setting the height of collectionView or calculating the `collectionViewContentSize`?

2. Also instead of showing message from top to bottom, I want to show the messages from bottom to top. Old message still is above new message, but the first message shows right above the keyboard. By solving problem 1, problem 2 should not be a problem. But I am wondering if there is better solution for this. 

Also, while solving problem 1, I found I need to override some methods defined in `JSQMessagesViewController.m` but I was unable to unless I move the definition to the `.h` file. For example, I want to override the `JSQMessagesKeyboardControllerDelegate` implementation and being able to reuse existing implementation by calling `super.` related methods. I don't want modify the source code if I can avoid it. Are there other ways to extend the functionality without modify existing source code of `JSQMessagesViewController`?

Any help is appreciated.

**Comment by jessesquires** [comment]
Hey @zwang :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
