### ISSUE TITLE
Any good example of JSQVideoMediaItem

### ISSUE THREAD

**Issue by novinfard** [jessesquires/JSQMessagesViewController#1354]
Hello,

Thanks for your efforts on this framework.

I googled to find any good example of JSQVideoMediaItem, but I could not find any good one. Could you please demonstrate some example?

I used the demo with the following code:

```objective-c
- (void)addVideoMediaMessage
{    
    NSBundle *bundle = [NSBundle mainBundle];
    NSString *moviePath = [bundle pathForResource:@"splash" ofType:@"m4v"];
    NSURL *videoURL = [NSURL fileURLWithPath:moviePath];
    
    JSQVideoMediaItem *videoItem = [[JSQVideoMediaItem alloc] initWithFileURL:videoURL isReadyToPlay:YES];
    JSQMessage *videoMessage = [JSQMessage messageWithSenderId:kJSQDemoAvatarIdSquires
                                                   displayName:kJSQDemoAvatarDisplayNameSquires
                                                         media:videoItem];
    [self.messages addObject:videoMessage];
}
```

I am sure the address is OK. There is no error in message box. But when I click on video message, nothing happened. (something like start video).

In addition, I need to know the supported video formats for JSQVideoMediaItem.

Thanks man

**Comment by ryanphillipthomas** [comment]
The framework does not supply the mechanics to actually play the view, simple create & display unique bubble's (video types, image types, text types, etc). What you need to do is look at the didTapMessageBubbleAtIndexPath methods, implement your own video player solution and pass the url found from the didTapMessageBubbleAtIndexPath method after getting the message and play the video from the url you get.

**Comment by jessesquires** [comment]
Thanks @ryanphillipthomas ! :smile: That's correct.

**Comment by raghunath44** [comment]
how to get videoUrl in didTapMessageBubbleAtIndexPath?Also how to play?
