### ISSUE TITLE
showing centered text without bubble

### ISSUE THREAD

**Issue by rosothefox** [jessesquires/JSQMessagesViewController#1355]
Hey,

I want to put a text that not related to the bubble chat. for example "sender1 made this conversation private". It should be with no bubble chat and can happen if there isn't any chat going on. How can this be achieved ? I tried all kind of ways to hide the bubble image, what is your suggestion?

Thanks in advance

**Comment by jessesquires** [comment]
Hey @rosothefox  :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
