### ISSUE TITLE
Easiest way for full-width "Bubble container" and "Avatar container" on top

### ISSUE THREAD

**Issue by novinfard** [jessesquires/JSQMessagesViewController#1356]
Hello,

 I need to change a full-width "Bubble container". Also I want the "Avatar container"'s position on top, as I shown on screen-shoot:
<img width="386" alt="screen shot 2015-12-17 at 11 43 17 am" src="https://cloud.githubusercontent.com/assets/611607/11864638/90bd2af2-a4b3-11e5-8c3c-a01bc3760e93.png">

I worked long time on "JSQMessagesCollectionViewCellIncoming.xib" and "JSQMessagesCollectionViewCellOutgoing.xib" but it is not working at all.

Thanks

**Comment by jessesquires** [comment]
Hey @novinfard :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
