### ISSUE TITLE
JSQMessageViewController, change color of single bubble

### ISSUE THREAD

**Issue by brokeniceinteractive** [jessesquires/JSQMessagesViewController#1357]
I have a chat with JSQMessageViewController using swift, i have a delegate that send me if last message fail, before send this delegate i change a state of message in DB from wait to fail:

```swift
func newMessageFailed(){
    print("ricevuto failed")
    self.collectionView?.reloadData()
    self.finishReceivingMessageAnimated(true)
}
```

the problem is that when method of delegate is called, the bubble don't change the color messageBubbleImageDataForItemAtIndexPath is not called again:

```swift
override func collectionView(collectionView: JSQMessagesCollectionView!, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageBubbleImageDataSource! {

   let message = messages[indexPath.item]

    return (message.status == MessageStatus.Fail.rawValue) ? self.outErrorBubbleImageView : self.outgoingBubbleImageView

    return self.incomingBubbleImageView
}
```

But if i back to navigation and then return to chat the message is correctly red!

Can you help me? thanks!

**Comment by brokeniceinteractive** [comment]
up!!

**Comment by jessesquires** [comment]
Hey @brokeniceinteractive :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
