### ISSUE TITLE
how to safely clear the messages when returning to the chatview

### ISSUE THREAD

**Issue by dpreston10** [jessesquires/JSQMessagesViewController#1360]
My app allows users to view another users info by tapping their avatar, at which they can block that user so that their message content is not visible.

What is the best way when returning to the chat view to clear the messages and reload them?

This would allow my blocking code to work on the fly. Currently it works when I dismiss the chat view and return but not when jump to another view and then back to the chat view

**Comment by jessesquires** [comment]
Thanks @dpreston10 ! :smile: 

Questions here should be specific to the library. This sounds like problems in your implementation. StackOverflow would be the more appropriate place for this.

http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller

**Comment by wdcurry** [comment]
kudos Jesse.. this should be stated more often, as more often than not, this particular repo fields questions of this genre. And no disrespect is intended to the OP..
