### ISSUE TITLE
Keyboard opening causes messages to disappear

### ISSUE THREAD

**Issue by gnrcampos** [jessesquires/JSQMessagesViewController#1361]
When the chat has just a couple of messages and the keyboard is shown it seems to move the whole GridView and the navigation bar up, so the first messages (in this case, the only ones) are disappearing.
This is the chat with just one message:
![simulator screen shot 21 de dez de 2015 17 53 10](https://cloud.githubusercontent.com/assets/8960501/11925073/da583f34-a80b-11e5-9bf4-e985a2cc3215.png)
Now the same screen, but with the keyboard:
![simulator screen shot 21 de dez de 2015 17 53 22](https://cloud.githubusercontent.com/assets/8960501/11925075/da59b31e-a80b-11e5-8087-49e670600436.png)
When I have more messages, like this:
![simulator screen shot 21 de dez de 2015 17 54 00](https://cloud.githubusercontent.com/assets/8960501/11925074/da589e98-a80b-11e5-861a-94cd6dbcfbcb.png)
It doesn't loot that strange, but it's still not right:
![simulator screen shot 21 de dez de 2015 17 54 02](https://cloud.githubusercontent.com/assets/8960501/11925072/da58281e-a80b-11e5-8971-f7baf2ec4411.png)
This is happening on both simulator and physical device.
XCode Version 7.2
iOS Version 9.2
Library Version 7.2.0

By the way, great work on this, it's really solid, thanks.

**Comment by harlanhaskins** [comment]
That doesn't look quite like a `UINavigationController` -- is that?

**Comment by gnrcampos** [comment]
@harlanhaskins it is, with it's UINavigationBar translucent property set to NO.

**Comment by KhaledAld** [comment]
@gnrcampos  how to display check mark on bottom of message ??

**Comment by gnrcampos** [comment]
@KhaledAld I used the Bottom Label. In the `- (NSAttributedString *)collectionView: attributedTextForMessageBubbleTopLabelAtIndexPath:` method you can create a `NSTextAttachment`, put an image on it and create a `NSAttributedString` with `NSAttributedString attributedStringWithAttachment:` to return.

**Comment by KhaledAld** [comment]
@gnrcampos  Thx

**Comment by gnrcampos** [comment]
I was finally able to find out what was causing this behavior. I was missing a `[super viewDidAppear:animated]` in my `viewDidAppear:` override.
