### ISSUE TITLE
'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [75.75 nan]'

### ISSUE THREAD

**Issue by diegojenzer** [jessesquires/JSQMessagesViewController#1362]
Hi there,

I am having a weird crash when I updated to Xcode 7.2 and iOS 9.2. 

On the iPhone device, I have no problem and the keyboard opens on the chat. However, when on the simulator, I get the following error:

    2015-12-21 19:18:19.957 Pink App[10347:752822] *** Terminating app due to uncaught exception 
    'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [75.75 nan]'

    *** First throw call stack:

    (

    	0   CoreFoundation                      0x0000000104b4ee65 __exceptionPreprocess + 165

    	1   libobjc.A.dylib                     0x0000000105198deb objc_exception_throw + 48

    	2   CoreFoundation                      0x0000000104b4ed9d +[NSException raise:format:] + 205

    	3   QuartzCore                          0x00000001021e8a86 _
    ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 152
	4   QuartzCore                          0x00000001021e8bf9 -[CALayer setPosition:] + 44
	5   QuartzCore                          0x00000001021e925d -[CALayer setFrame:] + 650
	6   UIKit                               0x00000001025c325f -[UIView(Geometry) setFrame:] + 356
	7   UIKit                               0x000000010272d2ad -[UIImageView _setViewGeometry:forMetric:] + 255
	8   UIKit                               0x000000010272d514 -[UIImageView setFrame:] + 58
	9   UIKit                               0x00000001025fa942 -[UIScrollView _adjustScrollerIndicators:alwaysShowingThem:] + 5461
	10  UIKit                               0x00000001026014bc -[UIScrollView(UIScrollViewInternal) _adjustForAutomaticKeyboardInfo:animated:lastAdjustment:] + 483
	11  UIKit                               0x0000000102681c6f -[UITableView _adjustForAutomaticKeyboardInfo:animated:lastAdjustment:] + 97
	12  UIKit                               0x0000000102e970e3 -[UIAutoRespondingScrollViewControllerKeyboardSupport _adjustScrollViewForKeyboardInfo:] + 328
	13  UIKit                               0x0000000102e9715e -[UIAutoRespondingScrollViewControllerKeyboardSupport _keyboardWillShow:] + 68
	14  CoreFoundation                      0x0000000104b1b69c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	15  CoreFoundation                      0x0000000104b1b3db _CFXRegistrationPost + 427
	16  CoreFoundation                      0x0000000104b1b142 ___CFXNotificationPost_block_invoke + 50
	17  CoreFoundation                      0x0000000104b60972 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1986
	18  CoreFoundation                      0x0000000104a16279 _CFXNotificationPost + 633
	19  Foundation                          0x00000001018ea109 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	20  UIKit                               0x0000000102e77b61 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke824 + 406
	21  UIKit                               0x00000001025d1370 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 582
	22  UIKit                               0x00000001025d1719 +[UIView(UIViewAnimationWithBlocks) _animateWithDuration:delay:options:animations:start:completion:] + 119
	23  UIKit                               0x0000000102e77544 -[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:] + 1589
	24  UIKit                               0x0000000102e7ef0c -[UIInputWindowController setInputViewSet:] + 983
	25  UIKit                               0x0000000102e76d08 -[UIInputWindowController performOperations:withAnimationStyle:] + 50
	26  UIKit                               0x0000000102b7eb75 -[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] + 1275
	27  UIKit                               0x0000000114840b89 -[UIPeripheralHostAccessibility setInputViews:animationStyle:] + 39
	28  UIKit                               0x000000010273551d -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 81
	29  UIKit                               0x0000000102732546 -[UIResponder becomeFirstResponder] + 617
	30  UIKit                               0x00000001025c9c59 -[UIView(Hierarchy) becomeFirstResponder] + 138
	31  UIKit                               0x0000000102ec9788 -[UITextView becomeFirstResponder] + 75
	32  UIKit                               0x0000000102a168db -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessary] + 287
	33  UIKit                               0x0000000102a1a39a -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) oneFingerTap:] + 3817
	34  UIKit                               0x0000000102a0ce73 _UIGestureRecognizerSendTargetActions + 153
	35  UIKit                               0x0000000102a094e5 _UIGestureRecognizerSendActions + 162
	36  UIKit                               0x0000000102a074e2 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 843
	37  UIKit                               0x0000000102a0f9a0 ___UIGestureRecognizerUpdate_block_invoke904 + 79
	38  UIKit                               0x0000000102a0f83e _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 342
	39  UIKit                               0x00000001029fd101 _UIGestureRecognizerUpdate + 2634
	40  UIKit                               0x0000000102594f8a -[UIWindow _sendGesturesForEvent:] + 1137
	41  UIKit                               0x00000001025961c0 -[UIWindow sendEvent:] + 849
	42  UIKit                               0x0000000102544b66 -[UIApplication sendEvent:] + 263
	43  UIKit                               0x00000001147f4871 -[UIApplicationAccessibility sendEvent:] + 77
	44  UIKit                               0x000000010251ed97 _UIApplicationHandleEventQueue + 6844
	45  CoreFoundation                      0x0000000104a7aa31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	46  CoreFoundation                      0x0000000104a7095c __CFRunLoopDoSources0 + 556
	47  CoreFoundation                      0x0000000104a6fe13 __CFRunLoopRun + 867
	48  CoreFoundation                      0x0000000104a6f828 CFRunLoopRunSpecific + 488
	49  GraphicsServices                    0x0000000105d04ad2 GSEventRunModal + 161
	50  UIKit                               0x0000000102524610 UIApplicationMain + 171
	51  Pink App                            0x0000000100d63d4d main + 109
	52  libdyld.dylib                       0x000000010628d92d start + 1

    )

    libc++abi.dylib: terminating with uncaught exception of type NSException

When I click on the accessory button, it works fine:
![Image of accessory working]
(http://i66.tinypic.com/14sh37n.png)

However, when I click on the textfield, that is when I get the error. When the keyboard want to be shown.
![Image of where it bugs]
(http://i67.tinypic.com/e8kbib.png)

I am not as experienced in Swift so I really don't know where to go from here. Can anyone help me with this issue?

@jessesquires Have you come across a similar issue as this?

Thanks to all in advance!

**Comment by jessesquires** [comment]
Hm. Seems unrelated.
