### ISSUE TITLE
Is this library ARC compatitble?

### ISSUE THREAD

**Issue by ginward** [jessesquires/JSQMessagesViewController#1363]
Hello jesse,

I saw the following code in the sources:

- (void)dealloc
{
    _delegate = nil;

    _cellTopLabel = nil;
    _messageBubbleTopLabel = nil;
    _cellBottomLabel = nil;

    _textView = nil;
    _messageBubbleImageView = nil;
    _mediaView = nil;

    _avatarImageView = nil;

    [_tapGestureRecognizer removeTarget:nil action:NULL];
    _tapGestureRecognizer = nil;
}

From my understanding, instances variables will be deallocated by ARC automatically and there is no need for setting them to nil in dealloc. 

Is there any specific reason you are doing this or is there anything missing in my understanding?

Thanks,

Jinhua

**Comment by harlanhaskins** [comment]
I don't think there is a reason -- it may have just been a force of habit. It doesn't change anything, though. The library is fully ARC compatible.
