### ISSUE TITLE
How do you handle messages when it comes?

### ISSUE THREAD

**Issue by alexliubj** [jessesquires/JSQMessagesViewController#1365]
For e.g. a new message comes, you should insert it to the last one of message array then update UI. Which way you were using to handle this? reload tableview or called this kind method insertRowsAtIndexPaths. I'm sorry I don't have that much time to go through your code to find it out. Because i'm doing the say thing now but I found when I use insertRowsAtIndexPaths my code sometimes crashes with error of saying `'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (2) must be equal to the number of rows 
contained in that section before the update (2), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
`

**Comment by alexliubj** [comment]
Any help will be appreciate.

**Comment by harlanhaskins** [comment]
Just call `collectionView?.reloadData()`.
