### ISSUE TITLE
Is it possible to apply autolayout on JSQMediaItems?

### ISSUE THREAD

**Issue by betzerra** [jessesquires/JSQMessagesViewController#1366]
If I'm not wrong, every **JSQMediaItem** has to specify its dimensions beforehand by implementing `- (CGSize)mediaViewDisplaySize`.

![screenshot4](https://cloud.githubusercontent.com/assets/681600/11961335/95c84a98-a8b6-11e5-9012-e916890298bd.jpg)

I want a **JSQMediaItem** that fits the whole cell's width. I guess I can do the same thing by getting information from the collectionView's dimension but I think that autolayout may be the cleanest thing to do.

Is there any way to achieve this?

**Comment by jessesquires** [comment]
Hey @betzerra -- there isn't a great way to do this now.

The 8.0 release will address this though. See #1429
