### ISSUE TITLE
Is it possible to set custom line height on text inside bubbles?

### ISSUE THREAD

**Issue by betzerra** [jessesquires/JSQMessagesViewController#1367]
Is it possible to set custom line height on text inside bubbles?

**Comment by harlanhaskins** [comment]
Auto Layout decides the height of the text, so you just need to specify line height in your NSAttributedString. 

```swift
let style = NSMutableParagraphStyle()
style.lineSpacing = 2
let string = NSAttributedString(string: message.text, attributes: [NSParagraphStyleAttributeName: style])
```

**Comment by betzerra** [comment]
@harlanhaskins gotcha, but I didn't find any way to use **NSAttributedString**s on the messages.

I noticed there's no attributedString property on **JSQMessage** and this issue open https://github.com/jessesquires/JSQMessagesViewController/issues/572 

Any clue?

**Comment by jessesquires** [comment]
Hey @betzerra! :smile:

Ahh, yes. That's correct. For now, you would have to have a custom fork for this.

For the 8.0 release, the API will change — instead of asking for an `NSString`, it will ask for an `NSAttributedString`.

**Comment by betzerra** [comment]
Ah, then I'll wait :D
THANKS!

-- 
Ezequiel Becerra
http://www.betzerra.com.ar
tw: @betzerra

On December 23, 2015 at 4:02:58 PM, Jesse Squires (notifications@github.com) wrote:

Hey @betzerra!  

Ahh, yes. That's correct. For now, you would have to have a custom fork for this.

For the 8.0 release, the API will change — instead of asking for an NSString, it will ask for an NSAttributedString.

**Comment by DilyanaTodorova** [comment]
There is a property messageBubbleFont that is used to calculate the bubble size. It's from the collectionViewLayout and it works nicely for me.
collectionView.collectionViewLayout.messageBubbleFont = UIFont(name: "Helvetica", size: 15.0)!
You can look at JSQMessagesCollectionViewFlowLayout class for more customizations.
