### ISSUE TITLE
Changing CollectionViewInsets causes weird scrolling behavior

### ISSUE THREAD

**Issue by vikram17000** [jessesquires/JSQMessagesViewController#1368]
Hi,

I need to show the chat bubbles on my view only in a part of it, lets say 200 pts below the nav bar and 50 pts above the toolbar (instead of them filling the entire screen). If I change the values being set accordingly in the method jsq_setCollectionViewInsetsTopValue (to for instance: UIEdgeInsetsMake(top + 200, 0.0f, bottom + 50.0, 0.0f) and then successively hit the [Send] button quite a few times (20-25), I notice strange behavior on the placement of the scrolling of the bubbles post that.

They initially get placed in the right 'segment', but post a few times, stall for a bit, and then suddenly scroll across the entire screen.

I first thought this had something to do with my project but then I created a blank test project with the library integrated and found similar scrolling discrepancies. If the insets are not modified, then the behavior is completely correct.

Is there a way folks are aware this can be fixed please? Presuming the collection insets is all that is ideally required to create the effect that I want...

Thanks much.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
