### ISSUE TITLE
keyboard return key as send

### ISSUE THREAD

**Issue by ronasc** [jessesquires/JSQMessagesViewController#1369]
Hi, I am trying to change the return key to the send key. I managed to do it by implementing
    override func textView(textView: UITextView, shouldChangeTextInRange range: NSRange, replacementText text: String) -> Bool {
        
        if text == "\n" {
            
            self.didPressSendButton(nil, withMessageText:self.keyboardController.textView?.text , senderId:self.senderId , senderDisplayName: self.senderDisplayName, date: NSDate())
        }
        
        return true
    }

But the line still breaks and the toolbarinputview becomes bigger 

I also want to add another right button and have 2 buttons on the right of the keyboard. What's the best way to do that?
Thanks in advance,
Rona

![screen shot 2015-12-24 at 12 55 58 am](https://cloud.githubusercontent.com/assets/16338222/11987082/32198948-a9d9-11e5-9030-a43327cdfc12.png)
![screen shot 2015-12-24 at 12 56 05 am](https://cloud.githubusercontent.com/assets/16338222/11987083/321a623c-a9d9-11e5-90a0-cfc8141baf91.png)

**Comment by ThePantsThief** [comment]
Make that method return `false` `if text == '\n'`

**Comment by devbriguy** [comment]
You need to `textView.resignFirstResponder()` before didPressSendButton as well.

**Comment by devbriguy** [comment]
Also reset textView text helps.

**Comment by ronasc** [comment]
Thanks, that helped. Any Idea about the 2 buttons on the right?

**Comment by devbriguy** [comment]
Inside JSQMessagesToolbaContent class it speaks to this. You would have to add the button to the right content container view and then handle it's events. 
![screen shot 2015-12-29 at 10 40 38 am](https://cloud.githubusercontent.com/assets/16087561/12036983/ecc0ffcc-ae18-11e5-9e55-472437857696.png)

**Comment by jessesquires** [comment]
Thanks @devbriguy ! :smile: 

@ronasc - there's great documentation [here](http://cocoadocs.org/docsets/JSQMessagesViewController/7.2.0/).

**Comment by ronasc** [comment]
Thanks everyone :)

**Comment by Parkyprg** [comment]
@ronasc - where did you implemented this override (textView(textView: UITextView, shouldChangeTextInRange range: NSRange, replacementText text: String) -> Bool)? In which file?
