### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by lastObject** [jessesquires/JSQMessagesViewController#1370]
hi Jesse,
when i tap the right barbuttonitem, more button, a little bit fast, media item not showing properly, couple of media item stuck in loading status. 

i tested demo use iOS9 simulator, iPhone 6, iPod 5t. based on iOS 7, 8, 9 with xcode7.2. 

thanks

**Comment by jessesquires** [comment]
Thanks @lastObject :smile: -- the demo is not very robust in this regard. This is something clients can decide how to handle, either by temporarily disabling the "send" button or otherwise
