### ISSUE TITLE
Tap message bubble to view timestamp

### ISSUE THREAD

**Issue by Farbod909** [jessesquires/JSQMessagesViewController#1372]
Hi, I'm trying to implement a feature where if the user taps on a message, the timestamp fades in above said message. Much like Facebook messenger. How would one go about doing this? I'm fairly new to iOS development and I am having trouble with changing cells and rows properties in collection views after they have been loaded initially.

Thanks

**Comment by jessesquires** [comment]
Hey @Farbod909 :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
