### ISSUE TITLE
How to add new media item?

### ISSUE THREAD

**Issue by KhaledAld** [jessesquires/JSQMessagesViewController#1373]
how to add new media item to jsqmessages

**Comment by lastObject** [comment]
checkout this 
https://github.com/relatedcode/EncryptedChat

**Comment by jessesquires** [comment]
Hey @KhaledAld :smile: 

The best way to learn this is to look at the provided media items and follow that pattern, for example `JSQPhotoMediaItem`. The demo project is also a good reference.

**Comment by KhaledAld** [comment]
@jessesquires 
Ok Thx ^_^
