### ISSUE TITLE
[HELP] I have a socket based JSQ but I found sometimes I got some message but can't successfully display?

### ISSUE THREAD

**Issue by alexliubj** [jessesquires/JSQMessagesViewController#1374]
I'm sure I got the messages. So every time i got one I put it into a async messages queue and added them into my message array. Then I go back to main thread update tableview and scroll to the bottom. But... the problem is sometimes one message will not be shown in the tableview. All the others are fine. Do you think there is anything wrong with my following code?

Thanks advanced. 

`#define WEAKSELF typeof(self) __weak weakSelf = self;

WEAKSELF
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{ // 1
        NSMutableArray *messages = [NSMutableArray arrayWithArray:weakSelf.messages];
        [messages addObject:addedMessage];
        dispatch_sync(dispatch_get_main_queue(), ^{ // 2
            weakSelf.messages = messages;
            [weakSelf.messageTableView reloadData];
            [weakSelf scrollToBottomAnimated:YES];
        });
    });`

**Comment by jessesquires** [comment]
Thanks @alexliubj ! :smile: 

Questions here should be specific to the library. This sounds like problems in your implementation. StackOverflow would be the more appropriate place for this.

http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller
