### ISSUE TITLE
error: could not build Objective-C module 'JSQMessagesViewController'

### ISSUE THREAD

**Issue by machive** [jessesquires/JSQMessagesViewController#1376]
MessagesViewController.swift>:12:8: error: could not build Objective-C module 'JSQMessagesViewController'
import JSQMessagesViewController
       ^

** BUILD FAILED **

We're trying to build our app with Jenkins and keep running into this error. I searched the repository and did not see an issue related to being unable to build the module. 

This runs fine in Xcode as a standalone app.

Anybody ever seen this issue before?

**Comment by jessesquires** [comment]
Hey @machive :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

If you think this is a bug, please let me know and we can re-open.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
