### ISSUE TITLE
missing file SPMessage.h

### ISSUE THREAD

**Issue by SidneyOtt** [jessesquires/JSQMessagesViewController#1378]
get compile error SPMessage.h file not found in DemoModelData.h

![screen shot 2016-01-01 at 1 44 39 am](https://cloud.githubusercontent.com/assets/5923170/12070318/992e9de8-b029-11e5-917a-b1f5c3e9b461.png)

**Comment by jessesquires** [comment]
This doesn't exist in the repo.

https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesDemo/DemoModelData.h#L23

Must be something you've added.
