### ISSUE TITLE
About resize photo messages.

### ISSUE THREAD

**Issue by Dean-Qian** [jessesquires/JSQMessagesViewController#1379]
Hi,jessesquires
I have some small images(like 24*24) to show on collectionView .
I think "-(CGSize)mediaViewDisplaySize" is the key function.I find "JSQMediaItem.m" implemented the protocol with static size(CGSizeMake(210.0f, 150.0f)).And in "JSQPhotoMediaItem.m" I can see something like "[self mediaViewDisplaySize]".I tried to implement "- (CGSize)mediaViewDisplaySize" in "JSQPhotoMediaItem.m" and it works.But It doesn't work when I implement it in my own controller.I'm 
confused.Is there something wrong?

**Comment by LatteCat** [comment]
Could the photos display in your own controller? If you want a photo display on the collectionView, the message which contains the photo information must conform the protocol *JSQMessageData*, and the method `- (BOOL)isMediaMessage` should return `YES`, `- (id<JSQMessageMediaData>)media` should return an instance that conform protocol *JSQMessageMediaData*, such as *JSQPhotoMediaItem*.

**Comment by jessesquires** [comment]
Thanks @LatteCat !
