### ISSUE TITLE
Slide for timestamp a la iOS 7

### ISSUE THREAD

**Issue by rahulgautam** [jessesquires/JSQMessagesViewController#138]
Hi @jessesquires, @ community, 

I would like to show message time when user swipe table view/cell from right to left,
Same as Messages app does in iPhone.
As shown in the image attached 

![timeonswipeinmessageapp](https://f.cloud.github.com/assets/1691889/1927846/25a47b50-7e6b-11e3-9976-4a469e95ea8c.png)

Please guide me how could I achieve that functionality.

**Comment by danielschonfeld** [comment]
Is there any progress on this or is it PR dependent :wink: ?

**Comment by akhilcb** [comment]
Is there any plans to make this available for a future release?

**Comment by JoeKueser** [comment]
Hate to bring this up again...but any plans to get this in?

**Comment by Mamong** [comment]
I have made it work with the idea, and translate the swift code to objc, change a little to act more lifelike:
"Note: possibly borrow ideas from: https://github.com/shaps80/iMessageStyleReveal"

**Comment by betzerra** [comment]
Just to check... this isn't implemented on JSQMessagesViewController yet, right? no PR from anyone?

**Comment by jessesquires** [comment]
@betzerra correct

**Comment by betzerra** [comment]
Alright. I'll keep you posted if I end up doing this on a separate fork :-)

**Comment by Andrew05** [comment]
Is this in the process of bring built?

**Comment by jessesquires** [comment]
hey @Andrew05 - as far as I know, it is not. 

@betzerra hasn't submitted anything yet, but maybe they have something.

A few notes:

- `v8.0` of the library is underway, so there's generally a lot of movement happening now in the project
- be sure to coordinate with us and branch fresh from `develop`
- since this would be added for 8.0, feel free to make breaking changes
- reply here with any questions/comments about design, etc.

**Comment by eliburke** [comment]
A final thought... this seems logically similar to #1593 (insofar as you have to slide the cells over) so there may be some value in looking at that patch and using / reusing the ideas.

**Comment by betzerra** [comment]
@betzerra I'm really sorry, I don't have anything :-(

**Comment by razvanpaul** [comment]
Will try to implement this: https://github.com/shaps80/iMessageStyleReveal

Anyway, thanks @jessesquires it's an amazing, beautiful library, but +1 for slide to reveal OR NSAttributedString they are really needed features.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
