### ISSUE TITLE
[HELP] CustomCell 

### ISSUE THREAD

**Issue by MurLuck** [jessesquires/JSQMessagesViewController#1380]
i wold like to get explanation on how to do it in SWIFT, what classes to subclass . what to override and so on.
any help will be appreciate
i did search for it didn't find a lot info about that

**Comment by oparinov** [comment]
What exactly do you need in a custom cell?

For me using JSQMessageMediaData really helped, it was super easy to provide a custom view.

You just need to create a class inherited from JSQMessageMediaData, and implement four required methods:

 – mediaView
– mediaViewDisplaySize
– mediaPlaceholderView 
– hash

See more here http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.2/Protocols/JSQMessageMediaData.html

Then you can just create a new message, passing an object of your custom class.

            let offlineMedia = KBHSOfflineMessageMediaData() // It's my custom class inherited from JSQMessageMediaData
            let message = JSQMessage(senderId: sender, displayName: sender, media: offlineMedia)
            self.messages += [message]

**Comment by MurLuck** [comment]
yes thats what i do for now  but the jsqmessage will set isMedia to true and thats not what i want 
i want to make custom cell for outgoing or incoming text message 
that wont contain the default labels and image view but what i will define like extra labels extra images and buttons and so on

**Comment by jessesquires** [comment]
Thanks @oparinov !

Hey @MurLuck ! :smile: 

This question has been asked many times:
https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=+%5Bcustom+cells%5D+in%3Atitle

**Comment by MurLuck** [comment]
(your free to call me igor)some of them i did read witch don't give a lot information 
some of them i didn't read so will do ,
if you can keep this issue open for 3-4 days i will be able to check the rest of the issues and see if it helps 
because the few issues i read didn't explain much about how to do it, just by theory and i don't know really well objc, 
thank

**Comment by jessesquires** [comment]
Hey @MurLuck -- no problem. Feel free to comment back here with any additional questions.

**Comment by MurLuck** [comment]
after some reaserch i didnt find somethink usefull 
what i meen is making custom cell of media and passing only media is easy but takes alot of memmory and process time , the cells are jumping when you enter the chat room 

what actully i did wanted is how to make a custom cell for text cell not media 
that contain diffirent labels and buttons inside then the jsqmessagescollectioncell ,
what class shold i subclass for that , and if i will register my own cell wont it mess the constrains ?
also after custom cell we need a class  that subclass jsqmessage

if some one can post complete guide for customization for cells it wold help alot of peaple that have same quastion like me .

**Comment by MurLuck** [comment]
after some research i didn't find something useful 
what i mean is making custom cell of media and passing only media is easy but takes a lot of memory and process time , the cells are jumping when you enter the chat room

what actually i did wanted is how to make a custom cell for text cell not media 
that contain different labels and buttons inside then the jsqmessagescollectioncell ,
what class should i subclass for that , and if i will register my own cell wont it mess the constrains ?
also after custom cell we need a class that subclass jsqmessage

if some one can post complete guide for customization for cells it wold help a lot of people that have same question like me .

Update:
after some looking in jsqmessagescollectionviewcell

to make your own custom cell
Steps Required:
1. rewrite the jsqmessagescollectionviewcell
2.create income/outgoing/mediaicome/mediaoutgoing cells
3. rewrite the function cellforrowatindexpath 
4.make a class that implement jsqmessagedata or subclass jsqmessage and extend to your needs

am i missing something?

**Comment by jessesquires** [comment]
@MurLuck - that's right.

I've updated the FAQ to include this.

https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md

**Comment by MurLuck** [comment]
thers one more way but i dont know if its good 
subclassing jsqmediaItem
customize the shit of it for your needs then
subclass jsqmessage and extend it to your medias needs 
and use only jsqmessage(initwithMediaItem)

example for extended jsqmessage

```swift
class TVChatMessageTemplate: JSQMessage {
    
    let mediaType:ISChatMediaType
    let messageSender:ISChatMessageSender
    let id:String
    
    init!(senderId: String, messageID:String,date:NSDate,media: JSQMessageMediaData,mediaType:ISChatMediaType) {
        self.id = messageID
        self.mediaType = mediaType
        
        if senderId != CoreDataTasks.sharedInstance.getUserEntityData(UserEntityDataType.PhoneNumber){
            messageSender = ISChatMessageSender.someOneElse
        }else{
            messageSender = ISChatMessageSender.MySelf
        }
        super.init(senderId: senderId, senderDisplayName: "", date: date, media: media)
    }
    
    required init?(coder aDecoder: NSCoder) {
        self.mediaType = ISChatMediaType.Text
        self.id = ""
        self.messageSender = ISChatMessageSender.MySelf
        super.init(coder: aDecoder)
    }
    
    func getMediaText() -> ISCustomMediaMessageCell{
        return self.media as! ISCustomMediaMessageCell
    }
    
    func getMediaSound() -> ISAudioMediaItem{
        return self.media as! ISAudioMediaItem
    }
}
```

example for message media:

```swift 
class ISCustomMediaMessageCell: JSQMediaItem {
    
    private var timeLabel:UILabel!
    private var textView:UITextView!
    private var statusIcon:UIImageView!
    private var warningButton:UIButton!
    private var size:CGSize!
    private var cachedMessageImageView:UIImageView?
    private var status:ISChatMessageStatus!
    
//----------------------------------------------//
    init(text:String,date:NSDate,messageStatus:ISChatMessageStatus,outgoing:Bool) {
//----------------------------------------------//
        textView = UITextView()
        timeLabel = UILabel()
        statusIcon = UIImageView()
        warningButton = UIButton()
        warningButton.hidden = true
        self.status = messageStatus
        
        super.init(maskAsOutgoing: outgoing)
        cachedMessageImageView = nil
            
        timeLabel.text = date.time
        textView.text = text
        timeLabel.text = date.time
        setTextView()
        prepareForCellLoad()
        
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    deinit{
        timeLabel = nil
        textView = nil
        statusIcon = nil
        warningButton = nil
        size = nil
        status = nil
        self.cachedMessageImageView = nil
    }
    
    override func mediaView() -> UIView! {
        return cachedMessageImageView
    }
    
    override func mediaViewDisplaySize() -> CGSize {
        return size!
    }
    
    private func prepareForCellLoad(){        
        if self.appliesMediaViewMaskAsOutgoing{
            addStatusIcon()
            setStatusIcon()
            setFailedButton()
        }
        
        let colorBackGround:UIColor = self.appliesMediaViewMaskAsOutgoing ? UIColor(red: 0.57, green: 0.60, blue: 0.89, alpha: 1) : UIColor(red:0.92, green: 0.50, blue: 0.99, alpha: 1)
        let imgView:UIImageView = status == ISChatMessageStatus.Failed && self.appliesMediaViewMaskAsOutgoing ? UIImageView(frame: CGRectMake(-failDelta()/2, 0, size!.width, size!.height)) : UIImageView(frame: CGRectMake(0, 0, size!.width, size!.height))
        
        imgView.backgroundColor = colorBackGround
        imgView.clipsToBounds = true
        imgView.addSubview(textView)
        
        if self.appliesMediaViewMaskAsOutgoing{
            imgView.addSubview(statusIcon)
            imgView.addSubview(warningButton)
        }
        
        setTimeLabel()
        imgView.addSubview(timeLabel)
        imgView.autoresizingMask = textView.autoresizingMask
        JSQMessagesMediaViewBubbleImageMasker.applyBubbleImageMaskToMediaView(imgView, isOutgoing: self.appliesMediaViewMaskAsOutgoing)
        imgView.userInteractionEnabled = true
        cachedMessageImageView = imgView
    }
    
    private func setTextView(){
        let max_Width = 0.7 * UIScreen.mainScreen().bounds.width
        textView.frame = CGRectMake(0, 0, max_Width, 0)
        textView.font = UIFont(name: "Helvetica", size: 17.0)
        textView.backgroundColor = UIColor.clearColor()
        textView.userInteractionEnabled = true
        textView.editable = false
        textView.scrollEnabled = false
        textView.showsHorizontalScrollIndicator = false
        textView.showsVerticalScrollIndicator = false
        textView.sizeToFit()
        
        
        let textView_Width = self.appliesMediaViewMaskAsOutgoing ? min(max_Width,max(textView.frame.size.width, 66)) : min(max_Width,max(textView.frame.size.width, 45))
        size =  self.appliesMediaViewMaskAsOutgoing ? CGSize(width: textView_Width + 30, height: textView.frame.size.height + 20) : CGSize(width: textView_Width + 30, height: textView.frame.size.height + 20)
        var autoResizing:UIViewAutoresizing?
        
        if self.appliesMediaViewMaskAsOutgoing{
            textView.frame = CGRectMake(10, 3, size!.width - 25, size!.height - 20)
            autoResizing = UIViewAutoresizing.FlexibleLeftMargin
        }else{
            textView.frame = CGRectMake(15,3, size!.width - 30, size!.height - 20)
            autoResizing = UIViewAutoresizing.FlexibleRightMargin
        }
        textView.autoresizingMask = autoResizing!
        
    }
    
    private func setStatusIcon(){
        switch status!{
        case .Sending:
            statusIcon.image = UIImage(named: "status_sending")!.jsq_imageMaskedWithColor(UIColor.whiteColor())
        case .Sent:
            statusIcon.image = UIImage(named: "status_sent")!.jsq_imageMaskedWithColor(UIColor.whiteColor())
        case .Received:
            statusIcon.image = UIImage(named: "status_notified")!.jsq_imageMaskedWithColor(UIColor.blueColor())
        case .Read:
            statusIcon.image = UIImage(named: "status_read")!.jsq_imageMaskedWithColor(UIColor.blueColor())
        case .Failed:
            statusIcon.image = UIImage(named: "status_sending")!.jsq_imageMaskedWithColor(UIColor.whiteColor())
        default :
            statusIcon.image = nil
        }
        if statusIcon.image != nil{
            statusIcon.image = statusIcon.image!.jsq_imageMaskedWithColor(UIColor.whiteColor())
        }
    }
    
    private func addStatusIcon(){
        statusIcon.frame = CGRectMake(15, isSingleLine() ? textView.frame.size.height - 5 : textView.frame.size.height, 15, 14)
        statusIcon.contentMode = .Left
        statusIcon.autoresizingMask = textView.autoresizingMask
        statusIcon.backgroundColor = UIColor.clearColor()
    }
    
    private func setTimeLabel(){
        timeLabel.frame = CGRectMake(0, 0, 31, 14)
        timeLabel.textColor = UIColor.whiteColor()
        timeLabel.font = UIFont(name: "Helvetica", size: 12.0)
        timeLabel.userInteractionEnabled = false
        timeLabel.alpha = 0.7
        timeLabel.textAlignment = .Left
        timeLabel.sizeToFit()
        
        var time_xPos:CGFloat
        let time_yPos:CGFloat = textView.frame.size.height//10 isSingleLine() ? textView.frame.size.height - 5 :
        
        if self.appliesMediaViewMaskAsOutgoing{
            time_xPos = statusIcon.frame.maxX + 3
        }else{
            time_xPos = textView.frame.maxX - timeLabel.frame.size.width - 5
        }
        
        timeLabel.frame = CGRectMake(time_xPos, time_yPos, timeLabel.frame.size.width, timeLabel.frame.size.height)
        timeLabel.autoresizingMask = textView.autoresizingMask
    }
    
    private func setFailedButton(){
        let b_size:CGFloat = 22
        let frame = CGRectMake(size!.width + b_size + self.failDelta()/2 + 5,(size!.height - b_size)/2 , b_size, b_size)
        warningButton.frame = frame
        warningButton.hidden = !self.isStatusFailedCase()
        warningButton.setImage(UIImage(named: "status_failed"), forState: .Normal)
    }
    
    private func isSingleLine() ->Bool {
        let textView_height = textView.frame.size.height
        let textView_width = textView.frame.size.width
        let view_width = size!.width
        return (textView_height <= 65 && textView_width <= 0.7 * view_width)
    }
    
    private func isStatusFailedCase() ->Bool {
        return status == ISChatMessageStatus.Failed
    }
    
    private func failDelta() ->CGFloat{
        return 60
    }
    
    func updateMessageStatus(status:ISChatMessageStatus){
        self.statusIcon.alpha = 0
        self.status = status
        self.setStatusIcon()
        UIView.animateWithDuration(0.5) { () -> Void in
            self.statusIcon.alpha = 1
        }
    }
    
    func getText() -> String{
        return self.textView.text!
    }
    
    func getStatus() -> String{
        return status.rawValue
    }
}

```

**Comment by jessesquires** [comment]
@MurLuck - for custom media cells, you should be able to hook into the existing infrastructure with little effort. simply follow the pattern of the existing media items.

**Comment by MurLuck** [comment]
those examples are media view for text message with custom view and layout just used media item instead of doing the second option for cell customization

**Comment by ribhuchawla** [comment]
@MurLuck Do upload your code. I am also interested in a customisation like this. Thanks!

**Comment by someone-coder** [comment]
@ribhuchawla : @MurLuck did upload his code :)
It took me a while to learn what was happening, but I was able to use his subclasses and make my own custom bubbles.  While doing it this way (subclassing JSQMediaItem) forced me to learn\build uiimageviews, labels, buttons, and autolayout constraints programaticly, I like this way because I now have full control of what is inside the bubble and how all the bubble pieces are arranged & sized.

**Comment by MurLuck** [comment]
yes you need to customize the cell search in the link below 

there is couple of ways 

i use a method that is workaround and not perfect cuz jsqmessagecell is not that easy to customize 
by what you want to do you have to use my method , or if you have time and patient
you can recode :

JSQMessagesCollectionViewFlowLayout
JSQMessagesCollectionViewCell
JSQMessagesCollectionViewCellOutgoing
JSQMessagesCollectionViewCellIncoming 

maybe i forgot some class but its a lot of work 

in version 8 @jessesquires  said that the message bubble will be more easy to customize so i advice you to wait till then

https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=%E2%9C%93&q=%5BCustom%20cells%5D%20in%3Atitle%20

**Comment by MHX792** [comment]
@MurLuck any chance that you share your xcode project? I really like your solution but I have difficulties implementing it in `ChatViewController: JSQMessagesViewController { ... }`. A usage example would be great!

**Comment by Andrew05** [comment]
@MurLuck Yes an example xcode project of some kind (with any personal things removed) would be a huge help to everyone working on customizing these cells.

**Comment by niteshtak** [comment]
@MurLuck can you please upload you code here for the customized cell. That would be a great help.

**Comment by anhphideptrai** [comment]
import UIKit
import JSQMessagesViewController.JSQMessages
import AlamofireImage

class JSQPhotoMediaItemCustom: JSQPhotoMediaItem {
    
    var imgView : UIImageView!
    var uRL     :NSURL?
    
    override init!(maskAsOutgoing: Bool) {
        super.init(maskAsOutgoing: maskAsOutgoing)
    }
    
    init(withURL url: NSURL, isOperator: Bool) {
        super.init()
        uRL                             = url
        appliesMediaViewMaskAsOutgoing  = (isOperator == true)
        let size                        = super.mediaViewDisplaySize()
        imgView                         = UIImageView()
        imgView.frame                   = CGRectMake(0, 0, size.width, size.height)
        imgView.contentMode             = .ScaleAspectFill
        imgView.clipsToBounds           = true
        imgView.backgroundColor         = UIColor.jsq_messageBubbleLightGrayColor()
        
        let activityIndicator           = JSQMessagesMediaPlaceholderView.viewWithActivityIndicator()
        activityIndicator.frame         = imgView.frame
        imgView.addSubview(activityIndicator)
        
        let filter = AspectScaledToFillSizeWithRoundedCornersFilter(
            size: size,
            radius: 0
        )
        
        JSQMessagesMediaViewBubbleImageMasker.applyBubbleImageMaskToMediaView(self.imgView, isOutgoing: self.appliesMediaViewMaskAsOutgoing)
        
        imgView.af_setImageWithURL(url, filter: filter) { (
            response ) in
            let image = response.result.value
            if  image != nil{
                
                activityIndicator.removeFromSuperview()
                self.imgView.image = image
            }
        }
    }
    
    override func mediaView() -> UIView! {
        return imgView
    }
    
    override func mediaViewDisplaySize() -> CGSize {
        return imgView.frame.size
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

**Comment by saikrishnaburra** [comment]
Can we have user interaction for the individual elements such as button in the message ?

**Comment by apwelsh** [comment]
Yes. Create a custom media message and add buttons.    I created a selector handler that geta called by my buttons, and in message view when i create the message,i assign my IBAction function in message view as the media items's selector. And when the button is pressed, i call the selector.    So i know which message selected, i capture the tap event's position in the view and translate that to the displayed cells.
    
  
  

  
  
   This (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email)  is how I Email now
  
  
  
  
  

  
  
>

**Comment by saikrishnaburra** [comment]
Thanks @apwelsh how to get the coordinates at which the message is tapped ? any Idea?

**Comment by apwelsh** [comment]
using email, so sorry about the formatting.

I assign my selector as:

    [mediaitem addButtonTapTarget:self action:@selector(meetupAction:forEvent:)];

Then in my selector:

-(IBAction) meetupAction:(id)sender forEvent:(UIEvent *)event {
    UIButton *button = (UIButton *) sender;

    CGPoint origin = [button convertPoint:button.frame.origin toView:self.collectionView];
    NSIndexPath *indexPath = [self.collectionView indexPathForItemAtPoint: origin];



This may require tweaking, as I apparently deviated from my original design to one that no longer required this logic, so I just recreated really quick, and did not test if it is completely accurate. 

The logic is to get the button (sender) that was clicked, then using this UIControl, I call the [UIControl convertPoint: toView: ] method to convert the origin of the button to the collection view’s location coordinates, which I then use with [UICollectionView indexPathForItemAtPoint:] method to get the indexpath.

**Comment by saikrishnaburra** [comment]
I am unable to even click the button after adding to the view.

**Comment by leonjohnson** [comment]
@saikrishnaburra, if you're unable to tap on a subview you've added to a custom cell try: `self.tapGestureRecognizer.cancelsTouchesInView = false`

**Comment by saltwat5r** [comment]
Hi! Thanks for great project!

I have a problem with UIButton items in my custom cell. Cells' buttons doesn't call target actions.

**Comment by leonjohnson** [comment]
@saltwat5r Please post the code you've written

**Comment by saltwat5r** [comment]
@leonjohnson Here's a CustomMessageCell and JSQMessagesViewControllers' subclass cellForItemAtIndexPath method:
```swift
import UIKit
import JSQMessagesViewController

class CustomMessageCell: JSQMessagesCollectionViewCell {

    // MARK: IBOutlets
    @IBOutlet weak var btnLeft: UIButton!
    @IBOutlet weak var btnRight: UIButton!

    // MARK: IBActions
    @IBAction func leftButtonAction(_ sender: UIButton) {
        print("Left button action")
    }
    @IBAction func rightButtonAction(_ sender: UIButton) {
        print("Right button action")
    }

    // MARK: Implementation
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}


class ConversationViewController: JSQMessagesViewController {

  override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
      let message = messages[indexPath.item]

      if let message = message as? CustomMessage {
          let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CustomMessageCellIndetifier", for: indexPath) as! CustomMessageCell
          return cell
      } else {
          let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as! JSQMessagesCollectionViewCell
          return cell
      }
  }
}
```

**Comment by SanjayLoganathan** [comment]
Can anyone please upload Your xcode project of customizing cell. I am also interested in a customisation like this.As a beginner it will be helpful for me.
