### ISSUE TITLE
[HELP] Position of bubble for outgoing message

### ISSUE THREAD

**Issue by soyoh** [jessesquires/JSQMessagesViewController#1381]
Hi all!
Im implementing this in on of my projects (with Rubymotion, but anyway) and everything works perfect, but i found that the position of the bubble for outgoing message is not correct, even the avatar is displayed at the left of the screen, is there something i need to do??

so far, what i did is convert all ObjC to ruby from the example, so is the same (same overrites, etc, etc) so dont know what is wrong :/

Here is an screenshot to show what i mean:
<img width="372" alt="msg" src="https://cloud.githubusercontent.com/assets/147098/12172732/f90e7b74-b552-11e5-8d47-8926fd70e917.png">

the red bubble is the outgoing, it displays the correct one, but not the position.

any hints would be really appreciated, thank you!

**Comment by jessesquires** [comment]
Hey @soyoh :smile: 

Please see the following:
https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=%5Bmessage+bubble+wrong+side%5D+in%3Atitle+

**Comment by soyoh** [comment]
oh :flushed: 
thank you @jessesquires !
