### ISSUE TITLE
Typing Indicator Animated

### ISSUE THREAD

**Issue by oparinov** [jessesquires/JSQMessagesViewController#1382]
:muscle::sunglasses::facepunch:

It'd be great to have nice looking animated dots instead of a static image.

Something like that 
![screencast 2016-01-07 18-52-10](https://cloud.githubusercontent.com/assets/1903866/12178088/e3ff80b2-b56f-11e5-8397-0778e70e922a.gif)

**Comment by mhui** [comment]
This would be awesome

**Comment by thesleepycow** [comment]
Maybe you could use the animationImages property of UIImageView?

```
// these allow a set of images to be animated. the array may contain multiple copies of the same
@property (nullable, nonatomic, copy) NSArray<UIImage *> *animationImages; // The array must contain UIImages. Setting hides the single image. default is nil
```

**Comment by jessesquires** [comment]
Would be nice if someone wants to continue the work from #1509 and submit a fresh PR.

**Comment by radekcieciwa** [comment]
I would like to tackle that issue, but i'm not sure yet if i will use #1509 for that.

**Comment by jessesquires** [comment]
Another old attempt was here: #1524
