### ISSUE TITLE
automaticallyScrollsToMostRecentMessage and fetched results controller causes content to jump after updates

### ISSUE THREAD

**Issue by BeetLab** [jessesquires/JSQMessagesViewController#1385]
I've got a classic FRC and Core Data approach. Firstly, i populate JSQ controller with persistent data and apply  scrollToBottomAnimated(false). But, after refreshed data reloads collection view, it jumps to last added messages up, and in refresh procedure :

```
func addMessages()
{
    BL_ChatManager.addNewMessagesInDialog(containingDiscussionAboutPostWithID: self.postID, success: {[weak self] () -> Void in

        dispatch_async(dispatch_get_main_queue(), { () -> Void in
            self?.scrollToBottomAnimated(false)
        })
        }) { (errorCode) -> Void in
    }
}
```

I have to scroll it back again. What can cause this problem? Tested on ios 9.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
