### ISSUE TITLE
Create CHANGELOG.md

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1386]
Add content from release notes:

https://github.com/jessesquires/JSQMessagesViewController/releases

**Comment by jessesquires** [comment]
Follow the same pattern here:
https://github.com/jessesquires/JSQNotificationObserverKit/blob/develop/CHANGELOG.md

Just copy what's in the GH release notes to the changelog.

For early releases without notes, let have:

> Sorry, changelogs are not available for this release.

**Comment by mauruskuehne** [comment]
Can I access the markdown for the release notes? I don't have the "edit release" button for the releases in your repository and they weren't synced over to my fork. This would make it way easier to create the changelog :sweat_smile:

**Comment by jessesquires** [comment]
@mauruskuehne ah derp! no worries — i'll grab this one!
