### ISSUE TITLE
sent message added twice in JSQMessageViewController

### ISSUE THREAD

**Issue by amrit42087** [jessesquires/JSQMessagesViewController#1389]
I am using JSQMessageviewcontroller for creating a chat cliet using parse. I am sucessfull in achieving everything except "My sent message is being added twice in the jsqmessage array". Although I have checked if JSQMessage array already contains that message, it should not be added, but the condition is false in case of a sent message.

    import UIKit
    import JSQMessagesViewController
    import Parse

    class MessageViewController: JSQMessagesViewController {

    var chatWith : String?
    var chattingWith = false
    let incomingBubble =    JSQMessagesBubbleImageFactory().incomingMessagesBubbleImageWithColor(UIColor(red: 10/255,     green: 180/255, blue: 230/255, alpha: 1.0))
     let outgoingBubble =   JSQMessagesBubbleImageFactory().outgoingMessagesBubbleImageWithColor(UIColor.lightGrayColor())
     var messages = [JSQMessage]()
    var updateTimer = NSTimer()
    let updateDelay = 2.0
    var jsqMessages : [JSQMessage] = []

    override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view, typically from a nib.
    self.setup()

    updateTimer = NSTimer.scheduledTimerWithTimeInterval(updateDelay, target: self, selector: "update", userInfo: nil, repeats: true)

    }

    override func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
    }

    override func viewDidDisappear(animated: Bool) {

     updateTimer.invalidate()

    }
    func reloadMessagesView() {
    self.collectionView?.reloadData()
     }
     }

    //MARK - Setup
    extension MessageViewController {

    func setup() {
    self.senderId = PFUser.currentUser()?.objectId!
    self.senderDisplayName = PFUser.currentUser()?.username!

    }
    }

    //MARK - Data Source
    extension MessageViewController {

    override func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
      return self.messages.count
    }

    override func collectionView(collectionView: JSQMessagesCollectionView!,   messageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageData! {
       let data = self.messages[indexPath.row]
      return data
    }

    override func collectionView(collectionView: JSQMessagesCollectionView!, didDeleteMessageAtIndexPath indexPath: NSIndexPath!) {
        self.messages.removeAtIndex(indexPath.row)
    }

    override func collectionView(collectionView: JSQMessagesCollectionView!,    messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageBubbleImageDataSource! {
       let data = messages[indexPath.row]
       switch(data.senderId) {
       case self.senderId:
        return self.outgoingBubble
       default:
         return self.incomingBubble
      }
    }

    override func collectionView(collectionView: JSQMessagesCollectionView!, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageAvatarImageDataSource! {
        return nil
    }
    }

    //MARK - Toolbar
    extension MessageViewController {
    override func didPressSendButton(button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: NSDate!) {
       let message = JSQMessage(senderId: PFUser.currentUser()?.objectId!, senderDisplayName: PFUser.currentUser()?.username!, date: date, text: text)
       print("sent messages = \(message)")
      if !self.messages.contains(message) {
       self.messages += [message]
      }

      self.sendMessageToParse(message , date: date)
      self.finishSendingMessage()
     }

    override func didPressAccessoryButton(sender: UIButton!) {

    }

    }

    //MARK - Syncano
    extension MessageViewController {

    func sendMessageToParse(message: JSQMessage , date : NSDate) {

    let obj = PFObject(className: "Chat")
    obj.setObject((PFUser.currentUser()?.username)!, forKey: "username")
    obj.setObject(message.text!, forKey: "Text")
    obj.setObject(chatWith!, forKey: "To")
    obj.setObject(PFUser.currentUser()!, forKey: "user")
    obj.setObject(date, forKey: "dateCreatedOn")
    try! obj.save()

     }

    func update() {
    let query = PFQuery(className: "Chat")
    query.limit = 10
     query.includeKey("user")
    //        query.whereKey("To", equalTo: chatWith!)
     query.findObjectsInBackgroundWithBlock {
        (results: [PFObject]?, error: NSError?) -> Void in

        for i in results! {

            if i.objectForKey("username") as? String == PFUser.currentUser()?.username! {

                let message = self.jsqMessageFromParseMessage(i, senderId: (PFUser.currentUser()?.objectId!)!, senderDisplayName: i.objectForKey("username")! as! String)
                print("received message : \(message)")
                self.jsqMessageArray(message)
            }else {

                let message = self.jsqMessageFromParseMessage(i, senderId: i.objectForKey("To")! as! String, senderDisplayName: i.objectForKey("To")! as! String)
                self.jsqMessageArray(message)
            }

        }

        }

      }

     func jsqMessageFromParseMessage(message: PFObject , senderId : String , senderDisplayName : String) -> JSQMessage {
      let jsqMessage = JSQMessage(senderId: senderId, senderDisplayName: senderDisplayName, date: message["dateCreatedOn"] as! NSDate, text: message["Text"] as! String)
       return jsqMessage
    }

    func jsqMessageArray(jsqmessage : JSQMessage){

      if self.messages.contains(jsqmessage) {

      }else {
         //
         self.messages.append(jsqmessage)
         self.finishReceivingMessage()
         self.reloadMessagesView()

       }

    }
    }

**Comment by jessesquires** [comment]
Thanks @amrit42087 ! :smile: 

Questions here should be specific to the library. This sounds like problems in your implementation. StackOverflow would be the more appropriate place for this.

http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller

**Comment by ZvOlCuOk2009** [comment]
Here at least somebody writes on obj-c???
