### ISSUE TITLE
Invalid parameter not satisfying: cell.textView.text != nil

### ISSUE THREAD

**Issue by oscarvgg** [jessesquires/JSQMessagesViewController#1390]
Hi. I'm using a custom cell to display text and media messages. Pretty much the same items as the cells provided in the library, just different layout.

I don't know what I'm doing wrong, but I'm getting the following error `Invalid parameter not satisfying: cell.textView.text != nil` possibly originated at `line 493` in `JSQMessagesViewController.m` when there are text and media messages in the conversation. 

I think the problem is that the text view of the cell is being removed to insert the media view, thats fine, but I think that then it is re-using the cell for a text message, but there is no textview anymore. Looks like the library is not adding it back. Thats my guess.

Thanks for your help in advance.

**Comment by jessesquires** [comment]
Hey @oscarvgg :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)

**Comment by kenkita** [comment]
Hi I had a same problem and I could fix it by adding this, though I'm not sure this is the correct way to solve it.

1, You add outlet from the textview you set in the custom cell to the swift file of your custom cell, like you usually add labels. 
2. You delete the swift cord which is automatically added by the first step.
3. Make sure your connection between the textview and the swift file still remains.  

That's it!

**Comment by nexig** [comment]
Hey @kenkita 

Could you explain your anwser from second point ? I am not understand what you really mean "You delete the swift cord which is automatically added by the first step."

I have subclasses of outgoing and incomming message with xib files. Problem is when I have few messages with image and few text messages on chat and I start to scroll fast, my app crash.
Crash is in JSQMessageVieController.m in line 521. 

![image](https://cloud.githubusercontent.com/assets/10259698/20754514/8e0c6a64-b70b-11e6-8b24-26df879e6736.png)


Please help

**Comment by jasonn85** [comment]
I ran into this same problem.  I was failing to use separate cell reuse identifiers for media cells and text cells.  The stock JSQMessages cells use the same nibs, but media cells have their text views removed on first use.  If these same cells are then reused for text, the assertion fails.

Ensure that you are registering your custom cells for both cellReuseIdentifier and mediaCellReuseIdentifier and that you are setting outgoingMediaCelIIdentifier and incomingMediaCellIdentifier along with outgoingCellIdentifier and incomingCellidentifier in the view controller.
