### ISSUE TITLE
How can I show Date for all day same whatsapp not all 3 messages

### ISSUE THREAD

**Issue by FadelSultan** [jessesquires/JSQMessagesViewController#1392]
Hello 

First thank's for this project .

I want this history for all day same app what sap  I don't want any change for history for the day !

    var arrayDate = [String]()
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        let message = messages[indexPath.item]
        
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd" // superset of OP's format
        
        let DateDataBase = dateFormatter.stringFromDate(message.date)
        //        let date = dateFormatter.dateFromString(DateDataBase)
        
        print("\(DateDataBase)")
        if (!arrayDate.contains(DateDataBase))
        {
            print("count : \(arrayDate.count)")
            print("After : \(arrayDate.contains(DateDataBase))")
            arrayDate.append(DateDataBase)
            return JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate(message.date)
        }
        return nil
        
    }
    
    var arrayDate1 = [String]()
    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
        let message = messages[indexPath.item]
        
        
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd" // superset of OP's format
        
        let DateDataBase = dateFormatter.stringFromDate(message.date)
        print("\(DateDataBase)")
        print("message.date \(message.date)")
        if (!arrayDate1.contains(DateDataBase) )
        {
            
            print("After : \(arrayDate1.contains(DateDataBase))")
            arrayDate1.append(DateDataBase)
            return kJSQMessagesCollectionViewCellLabelHeightDefault
            
        }
        return 0.0
    }

**Comment by MurLuck** [comment]
//-------------------------------------------------------------------------------------------------------------------------------------------------
    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
//-------------------------------------------------------------------------------------------------------------------------------------------------
        let msg = self.messages[indexPath.item]
        var preMsg:TVChatMessageTemplate?
        if indexPath.item != 0{
            preMsg = self.messages[indexPath.item - 1]
        }

        
        if indexPath.item == 0{
            return kJSQMessagesCollectionViewCellLabelHeightDefault
        }else if indexPath.item - 1 > 0 && preMsg!.date.date != msg.date.date {
            let premsg = self.messages[indexPath.item - 1]
            let msg = self.messages[indexPath.item]
            if msg.date.timeIntervalSinceDate(premsg.date)/60 > 1{
                return kJSQMessagesCollectionViewCellLabelHeightDefault
            }
        }
        
        return 0.0
    }

//-------------------------------------------------------------------------------------------------------------------------------------------------
    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
//-------------------------------------------------------------------------------------------------------------------------------------------------
        let msg = self.messages[indexPath.item]
        var preMsg:TVChatMessageTemplate?
        if indexPath.item != 0{
            preMsg = self.messages[indexPath.item - 1]
        }
    
        if indexPath.item == 0{
            let date = JSQMessagesTimestampFormatter.sharedFormatter().relativeDateForDate(msg.date)
            return NSAttributedString(string: date)
        }else if indexPath.item - 1 > 0 && preMsg!.date.date != msg.date.date{
            let date = JSQMessagesTimestampFormatter.sharedFormatter().relativeDateForDate(msg.date)
            return NSAttributedString(string: date)
        }
        return nil
    }

**Comment by FadelSultan** [comment]
Thank's MurLuck but I can't make variable TVChatMessageTemplate in swift !!! 
how can I make it

**Comment by MurLuck** [comment]
post the new code you use will see what missing

**Comment by FadelSultan** [comment]
![screen shot 2016-01-15 at 6 28 12 pm](https://cloud.githubusercontent.com/assets/12224396/12356894/06b22b36-bbb6-11e5-84ab-17c033f5eb04.png)
this if attach !!!! 

but I select date with out time !!!!

**Comment by FadelSultan** [comment]
Thank you very much @MurLuck for help me 
now it's okay

**Comment by NikKovIos** [comment]
Just in case - the updated answer of @MurLuck 

```swift
// Date
override func collectionView(_ collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAt indexPath: IndexPath!) -> CGFloat {
    let i = indexPath.item
    let message = presenter.messages[i]
    let prevMessage: JSQMessage? = (i - 1 > 0) ? presenter.messages[i - 1] : nil
    
    guard let previousMessage = prevMessage else { return kJSQMessagesCollectionViewCellLabelHeightDefault }
    
    // Set a condition for stacking messages here
    if previousMessage.date != message.date
        && message.date.timeIntervalSince(previousMessage.date) / 60 > 1 {
        return kJSQMessagesCollectionViewCellLabelHeightDefault
    }
    
    return 0.0
}

override func collectionView(_ collectionView: JSQMessagesCollectionView!, attributedTextForCellTopLabelAt indexPath: IndexPath!) -> NSAttributedString! {
    return NSAttributedString(string: presenter.messages[indexPath.item].date.feedDateFormatString)
}
```

**Comment by dilipiOSDeveloper** [comment]
@NikKovIos  what is presenter in above answer

**Comment by NikKovIos** [comment]
@diliptiwari333 Class that holds the array. Its just a helper.

**Comment by dilipiOSDeveloper** [comment]
@NikKovIos  i want top label date only on first message of particular date and then all messages below that date.currently it is showing on every message, var messages = [JSQMessage]() this already have date and message displayed on chat page for sender or receiver
