### ISSUE TITLE
Distance from Bubble Image to Avatar

### ISSUE THREAD

**Issue by 1bannamgiauten** [jessesquires/JSQMessagesViewController#1393]
Can I change distance from Bubble Image to Avatar image?
![simulator screen shot jan 15 2016 9 01 07 am](https://cloud.githubusercontent.com/assets/16713961/12345271/2affc5b2-bb79-11e5-8249-e3d5e46ce6f0.png)

**Comment by MurLuck** [comment]
yes when u do cachedImageView = yourImageView 
advising to put it like this 
container with width size bigger by 10 
xPos of yourImageView 10 with width smaller by 10 

```
container.addSubview(yourImageView)
cachedImageView = container
```

**Comment by jessesquires** [comment]
Hey @1bannamgiauten :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
