### ISSUE TITLE
glitch when i create MediaItem with different size

### ISSUE THREAD

**Issue by lastObject** [jessesquires/JSQMessagesViewController#1394]
>like you have different height of JSQPhotoMediaItem object.
![simulator screen shot jan 15 2016 5 57 16 pm](https://cloud.githubusercontent.com/assets/14226783/12350471/473d6520-bbb2-11e5-8e18-fe1b477a7a75.png)
![simulator screen shot jan 15 2016 5 56 57 pm](https://cloud.githubusercontent.com/assets/14226783/12350472/4cc54ee0-bbb2-11e5-97d6-50905463a4ae.png)
![simulator screen shot jan 15 2016 5 57 07 pm](https://cloud.githubusercontent.com/assets/14226783/12350482/5610d0c8-bbb2-11e5-8041-c26a54253712.png)
![simulator screen shot jan 15 2016 5 57 09 pm](https://cloud.githubusercontent.com/assets/14226783/12350491/585eaf76-bbb2-11e5-8775-3eeda98a29b7.png)
![simulator screen shot jan 15 2016 5 57 12 pm](https://cloud.githubusercontent.com/assets/14226783/12350493/5aac43ec-bbb2-11e5-890e-3ec77163ee28.png)
![simulator screen shot jan 15 2016 5 57 11 pm](https://cloud.githubusercontent.com/assets/14226783/12350499/5c9072d2-bbb2-11e5-83bb-79c9fc85f987.png)
![simulator screen shot jan 15 2016 5 56 59 pm](https://cloud.githubusercontent.com/assets/14226783/12350502/608d3168-bbb2-11e5-80f2-878de6b3af33.png)

>the white view which has a gray border is set by my MediaItem frame, but when i set my mediaItem background as red, you can found the size is different

here is part of my code

In my MediaItem.m
![screen shot 2016-01-15 at 6 10 17 pm](https://cloud.githubusercontent.com/assets/14226783/12350654/4acc9c28-bbb3-11e5-8f82-a6059d0bd221.png)

![screen shot 2016-01-15 at 6 11 02 pm](https://cloud.githubusercontent.com/assets/14226783/12350673/6ae9988a-bbb3-11e5-8eb7-e016db500d78.png)

my problem is why some red area's Height not equal to viewBack's height

**Comment by lastObject** [comment]
actually it happened when my **MediaItem** has **different height**

**Comment by lastObject** [comment]
sori,  code above is wrong.

my one is, different size item with one kind of mediaItem.
like you have different height of photomediaItem. 

hope your guys can understand

**Comment by lastObject** [comment]
@jessesquires sori, all is my fault, forget to override hash method, now is so great, thx for your fanatics framework, n happy Chinese new year

**Comment by jessesquires** [comment]
Thanks for the update @lastObject ! :smile: Glad it's working!
