### ISSUE TITLE
How can I add UILabel in collectionView cellForItemAtIndexPath

### ISSUE THREAD

**Issue by FadelSultan** [jessesquires/JSQMessagesViewController#1397]
Hello very body here 

I want add Label in Messages 

how can I add it ?

override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        
        let message = messages[indexPath.row]
        
        let text = textMessage[indexPath.row]
        let user = users[indexPath.row]
        
        let userLength = NSString(string: user.username!).length
        let messageLength = NSString(string: text).length
//        let dateLength = 8
        
      let myMutableString = NSMutableAttributedString(
            string: text,
            attributes: [NSFontAttributeName:UIFont(
                name: "Arial",
                size: 16)!])
        
//        Color User
        myMutableString.addAttribute(NSForegroundColorAttributeName,
            value: UIColor(netHex: 0x225fa5),
            range: NSRange(
                location:0,
                length:userLength))
        
        
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.alignment = NSTextAlignment.Right
        
        if message.senderId == self.senderId
        {

            paragraphStyle.alignment = NSTextAlignment.Right
            
        }
        else
        {
            paragraphStyle.alignment = NSTextAlignment.Left
        }

        
        myMutableString.addAttribute(NSParagraphStyleAttributeName, value: paragraphStyle, range: NSRange(
            location:0,
            length:messageLength))
        
        cell.textView?.attributedText = myMutableString
        
//        cell.avatarImageView?.image = UIImage(named: "logo")
        return cell
        
    }

**Comment by MurLuck** [comment]
check here https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md

**Comment by jessesquires** [comment]
Thanks @MurLuck ! :smile: 

@FadelSultan - please check the `README`, docs, and open issues next time. :smile:
