### ISSUE TITLE
Incomplete text display in 4-inch Screen

### ISSUE THREAD

**Issue by bitnpc** [jessesquires/JSQMessagesViewController#1398]
With the situation of the same text, the 4-inch iPod with iOS 9.0.2 can only display about 3 words.
While the 4.7-inch iPhone 6 with iOS 9.2.0 can display normally.
I cannot upload the PNG files due to the poor Internet.
Hope can be solved.

**Comment by jessesquires** [comment]
Thanks @bitnpc ! :smile: 

Please [review the contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) and update your issue. Then we can re-open and discuss!
