### ISSUE TITLE
Timestamp label only displays for every third index

### ISSUE THREAD

**Issue by zedle** [jessesquires/JSQMessagesViewController#1399]
Can't seem to get the timestamp labels to show up for more than every third cell.

I changed the heightForCellTopLabelAtIndexPath delegate method to return kJSQMessagesCollectionViewCellLabelHeightDefault for every cell yet it still only shows up for every third cell.

Made the same change to the example project and the same behavior is present.

Tested on simulator for 9.2 and iPhone w/ 9.0.2.. Hopefully I'm not missing something obvious here.

**Comment by jessesquires** [comment]
hey @zedle :smile: 

there's another similar method that asks for the text. `attributedTextForCellTopLabel:....`

**Comment by zedle** [comment]
Was something obvious after all.. Thank you.
