### ISSUE TITLE
The elegant JSQMessages should add some state for JSQMessage

### ISSUE THREAD

**Issue by cx478815108** [jessesquires/JSQMessagesViewController#1402]
There is no doubt that it`s an elegant UI library for chatting. I really hope  JSQMessage(the instance  class) can add several states . ex JSQMessageStateSendFaliure ,JSQMessageStateSending, JSQMessageStateSendSuccess.
oh,it can be wonderful to see JSQVoiceMediaItem!!!

**Comment by jessesquires** [comment]
Thanks @cx478815108 ! :smile: 

We have some issues already opened to track this. See #516
