### ISSUE TITLE
Media messages bubble view is always pointing to the right

### ISSUE THREAD

**Issue by fede1608** [jessesquires/JSQMessagesViewController#1405]
![screen shot 2016-01-20 at 10 35 52](https://cloud.githubusercontent.com/assets/4108692/12450323/be928b7a-bf61-11e5-854f-a9187321d4e1.png)
![screen shot 2016-01-20 at 10 35 58](https://cloud.githubusercontent.com/assets/4108692/12450324/be930b40-bf61-11e5-98ef-c11bcef7aa4e.png)
![screen shot 2016-01-20 at 10 36 02](https://cloud.githubusercontent.com/assets/4108692/12450325/be971640-bf61-11e5-80ae-420e7aadb8da.png)

This method: collectionView(collectionView: JSQMessagesCollectionView!, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath!) is never called for all the media messages, and I couldn't find what might cause this. The senderId is correct too.

**Comment by fede1608** [comment]
I'm using this pod: pod 'JSQMessagesViewController'

**Comment by cx478815108** [comment]
.appliesMediaViewMaskAsOutgoing=YES | NO

**Comment by fede1608** [comment]
thanks for that, I must have missed it.
