### ISSUE TITLE
avatarImageView display

### ISSUE THREAD

**Issue by Qingzhaowang** [jessesquires/JSQMessagesViewController#1416]
Hello, thank you very much for your library!
In JSQMessagesCollectionViewCell.m, I want to move the avatarContainerView to the bottom of the cellTopLabel, not the bottom of the cell. Then I did
"  cell.avatarImageView!.mas_makeConstraints({ make in
                make.top.mas_equalTo()(cell.messageBubbleTopLabel!.mas_bottom).offset()
            })
"However, avatarImageView was stretched like below picture. What should I do?
![img_0297](https://cloud.githubusercontent.com/assets/16550476/12602828/5ab3db1e-c4e7-11e5-87bc-5eb826a089f5.jpg)

**Comment by LatteCat** [comment]
直接改那个 JSQMessagesCollectionViewCell.xib 呀！你用 Masonry 改真是自找麻烦，而且头像的控件本身就有约束，你又用的是 mas_makeConstrains，怎么看都应该是重新定义的呀！

**Comment by Qingzhaowang** [comment]
Thanks
