### ISSUE TITLE
mediaViewDisplaySize not being set?

### ISSUE THREAD

**Issue by uknowmeright** [jessesquires/JSQMessagesViewController#1418]
So I have a custom class for my message model which contains a media_ object that is of type JSQPhotoMediaItem?.

I add a UIImage to the image property and set isMediaMessage_ to true. then I try appending my message to my datasource and reloading the CollectionView. When I do this however it hangs up and brings me to this part of the framework:

```
if ([messageData isMediaMessage]) {
        finalSize = [[messageData media] mediaViewDisplaySize];
 }
```

The error is: unrecognized selector sent to instance 0x135f05d20

Here is my message model:

`class CustomJSQMessage : NSObject, JSQMessageData {
    
    var senderId_ : String!
    var senderDisplayName_ : String!
    var date_ : NSDate
    var isMediaMessage_ : Bool
    var media_ : JSQPhotoMediaItem? //JSQMessageMediaData? //
    var messageHash_ : UInt?
    var text_ : String
    var userIdOwner_: String?
    var userIdInquirer_: String?
    var messageOwnerType_: String?
    
    init(senderDisplayName: String?, isMediaMessage: Bool, hash: Int, text: String) {
        //self.senderId_ = senderId
        self.senderDisplayName_ = senderDisplayName
        self.date_ = NSDate()
        self.isMediaMessage_ = isMediaMessage
        self.messageHash_ = UInt(arc4random()) //messageHash()
        self.text_ = text
    }
    
    func senderId() -> String! {
        return senderId_;
    }
    
    func senderDisplayName() -> String! {
        return senderDisplayName_;
    }
    
    func date() -> NSDate! {
        return date_;
    }
    
    func isMediaMessage() -> Bool {
        return isMediaMessage_;
    }
    
    func messageHash() -> UInt {
        return UInt(messageHash_!);
    }

    func text() -> String! {
        return text_;
    }
    
    func userIdOwner() -> String! {
        return userIdOwner_;
    }

    func userIdInquirer() -> String! {
        return userIdInquirer_;
    }

    func messageOwnerType() -> String! {
        return messageOwnerType_;
    }
}`

anyone have any Idea why it cant find the correct size for my image? 
Thanks in advance!

**Comment by jessesquires** [comment]
Hey @uknowmeright :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
