### ISSUE TITLE
Custom BubbleSizeCalculator - Question/Potential bug

### ISSUE THREAD

**Issue by markdelf** [jessesquires/JSQMessagesViewController#1419]
I've created a custom bubble size calculator to change the size of some messages by extending JSQMessagesBubblesSizeCalculator and overriding the messageBubbleSizeForMessageData function.

All works well and I get a custom view size for some of my bubbles but I have noticed that if I trigger reloadData the size of the very first and very last bubble seems to go wrong. Commenting out the custom bubble size and there isn't this anomaly.

See screenshot attached and code below. Am I changing the bubble sizes in the right place?

```
@implementation JSQARXBubbleSizeCalculator
- (CGSize)messageBubbleSizeForMessageData:(id<JSQMessageData>)messageData
                              atIndexPath:(NSIndexPath *)indexPath
                               withLayout:(JSQMessagesCollectionViewFlowLayout *)layout
{    
    ChatMessage *msg = (ChatMessage *)messageData;
    CGSize size = [super messageBubbleSizeForMessageData:messageData atIndexPath:indexPath withLayout:layout];
    
   // return size; //this would fix the problem but I lose my custom sizes
    if (msg.useCustomBubble) {
         size.height = 108.0f;
    }
    return size;
}
```

The bubble in question below has useCustomBubble as false.

![screen shot 2016-01-29 at 10 06 15](https://cloud.githubusercontent.com/assets/370194/12673953/5c751fcc-c680-11e5-8b8d-db747a9aa044.png)

**Comment by brokeniceinteractive** [comment]
how do you use your custom class? post an example!

**Comment by markdelf** [comment]
Simply by setting it in viewDidLoad;

```
self.collectionView.collectionViewLayout.bubbleSizeCalculator = [JSQARXBubbleSizeCalculator new];
```

**Comment by jessesquires** [comment]
Thanks @markdelf ! :smile: 

Please see the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) and provide more information here.

Also, if you could fork and reproduce this in the demo project -- that would be great :+1:

**Comment by markdelf** [comment]
@jessesquires I've found the problem, I don't think it was not really related to the BubbleSizeCalculator.

Basically I had some logic in heightForCellTopLabelAtIndexPath which shows a date just once per day. The logic was quite flawed and caused chaos (was not consistently returning the correct value). The side effect was what we're seeing in the screenshot.

Hope I didn't waste any of your time with my question!

**Comment by jessesquires** [comment]
Thanks for the update @markdelf ! No worries! :smile:

**Comment by kuyazee** [comment]
how do I implement this on swift? I'm having trouble fixing the size of my messageBubbles. :|

**Comment by srinathp90** [comment]
subclass the JSQMessagesCollectionViewFlowLayout, and override messageBubbleSizeForItemAtIndexPath(indexPath: NSIndexPath!) method there you return the size for each index path.


And assigned it in chat view controller viewDidLoad:
self.collectionView.collectionViewLayout = <your custom class>()

**Comment by kuyazee** [comment]
oh thanks. I hope it works
