### ISSUE TITLE
Unpredictable bubble rendering

### ISSUE THREAD

**Issue by Cellard** [jessesquires/JSQMessagesViewController#1420]
Hi.
The application has TableViewController with list of dialogs and JSQMessagesViewController with messages. Every time I navigate from dialogs to messages, the bubbles are rendered the unpredictable way. 
Here is some pictures. What may be the reason?

![img_2508](https://cloud.githubusercontent.com/assets/1220316/12676172/319c15e6-c6a1-11e5-898d-182e4cdeafb6.jpg)
![img_2509](https://cloud.githubusercontent.com/assets/1220316/12676175/359822c0-c6a1-11e5-801c-3338540d95c9.jpg)
![img_2510](https://cloud.githubusercontent.com/assets/1220316/12676179/3861440a-c6a1-11e5-9ea0-73f36e01a5e5.jpg)
![img_2511](https://cloud.githubusercontent.com/assets/1220316/12676184/3d4a27a2-c6a1-11e5-9732-4413fb9b045f.jpg)
![img_2512](https://cloud.githubusercontent.com/assets/1220316/12676186/411eefa2-c6a1-11e5-98a0-96273995bce0.jpg)
![img_2513](https://cloud.githubusercontent.com/assets/1220316/12676189/416cc876-c6a1-11e5-9ced-de45c8811862.jpg)
![img_2514](https://cloud.githubusercontent.com/assets/1220316/12676188/416bb314-c6a1-11e5-8826-d346c0b61a0d.jpg)
![img_2515](https://cloud.githubusercontent.com/assets/1220316/12676187/4167251a-c6a1-11e5-8c35-29f88dbd0cb2.jpg)
![img_2516](https://cloud.githubusercontent.com/assets/1220316/12676190/416df80e-c6a1-11e5-83f5-d1b046f86472.jpg)

**Comment by jessesquires** [comment]
Hey @Cellard :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)

**Comment by jessesquires** [comment]
@Cellard -- My guess is that something is weird with your implementation, but if you think this is a bug, please let me know! And open a bug report following the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md)

If you can reproduce this in the demo, that would be most helpful.

**Comment by babihutan** [comment]
@Cellard 

I wonder if your hasher is jacked.  I had some similar problem, but massaged my hasher, and got moving forward.  In getting my project going at first, I initially took some shortcuts including setting my hasher to a single value, and then all the bubbles were the same size, the size of the first message.  Good luck!

d

**Comment by Cellard** [comment]
I have find the problem.

What I had. NSManagedObject (CoreData) class with @protocol JSQMessageData.
Class had method media witch returned JSQMessageMediaData object with asynchronously loaded image and proper mediaViewMask. This CoreData object I returned in messageDataForItemAtIndexPath;

Now I have. In messageDataForItemAtIndexPath I read my NSManagedObject and then create vanilla JSQMessage. And have no more problems.

:muscle::sunglasses::facepunch:

**Comment by jessesquires** [comment]
Awesome! Thanks for the update @Cellard! :muscle: :heart: :facepunch:
