### ISSUE TITLE
How to add additional button items

### ISSUE THREAD

**Issue by bottotl** [jessesquires/JSQMessagesViewController#1421]
```
/**
 *  The container view for the rightBarButtonItem.
 *
 *  @discussion 
 *  You may use this property to add additional button items to the right side of the toolbar content view.
 *  However, you will be completely responsible for responding to all touch events for these buttons
 *  in your `JSQMessagesViewController` subclass.
 */
@property (weak, nonatomic, readonly) UIView *rightBarButtonContainerView;

```
Can you show me how can I add additional button items to toolbar...(forgive my poor English).

**Comment by jessesquires** [comment]
Hey @bottotl  :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
