### ISSUE TITLE
Lost text of last message after use the lens.

### ISSUE THREAD

**Issue by OrWest** [jessesquires/JSQMessagesViewController#1423]
Lost text of last message after use the lens (long tap on textView in inputToolBar) in chat. Bug with small messages (text).
It's demo project, downloaded from repo 01.02.

**Lib version: 7.2.0
iOS version: 9.2.1
Device: iPhone 5**

![img_0133](https://cloud.githubusercontent.com/assets/12881398/12712135/0a748542-c8d7-11e5-8d76-af2a3682cfa0.PNG)
![img_0134](https://cloud.githubusercontent.com/assets/12881398/12712136/0aa0811a-c8d7-11e5-8bdb-e7178f5119d9.PNG)

**Comment by OrWest** [comment]
Any ideas? I can provide movie with this bug, if you want.

**Comment by Kayoto1** [comment]
Same happen to me

**Comment by OrWest** [comment]
Any moving?

**Comment by Lucashuang0802** [comment]
@OrWest Can you provide more info? I can't replicate the issue. Thx! 😄

**Comment by jessesquires** [comment]
@OrWest - I'm going to close this for now since we can reproduce it.

If you have anymore information, please update here and we can re-open. If you can setup steps to reproduce in our demo project, that would be most helpful. Thanks! 😄

**Comment by OrWest** [comment]
I think this bug relates to textField. So in actual iOS version this bug doesn't reproducible already.
