### ISSUE TITLE
Crash while scrolling

### ISSUE THREAD

**Issue by matteinn** [jessesquires/JSQMessagesViewController#1424]
Hi there!
I'm seeing the following crash when scrolling up a chat screen. This is happening randomly based on the actual chat content: fortunately I am able to always replicate it in a specific "chat room". The only way to avoid the crash is setting the showLoadEarlierMessagesHeader flag to NO. Any thoughts?

Thanks in advance!

<Warning>: *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UICollectionViewData.m:408
<Error>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'layout attributes for supplementary item at index path (<NSIndexPath: 0xc000000000000016>
{length = 2, path = 0 - 0}) changed from <JSQMessagesCollectionViewLayoutAttributes: 0x15fc8cbb0> index path: (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}
); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 375 32); zIndex = 10; to <JSQMessagesCollectionViewLayoutAttributes: 0x15fc749b0> index path: (<NSIndexPath: 0xc000000000000016>
{length = 2, path = 0 - 0}
); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 375 32); zIndex = -1; without invalidating the layout'

**Comment by matteinn** [comment]
As far as I have seen this crash is happening only if you call reloadData too often.

**Comment by IgorB10** [comment]
+1

**Comment by Sujit51** [comment]
+1

**Comment by ryanthon** [comment]
+1

**Comment by niks290192** [comment]
+1

**Comment by ippily** [comment]
+1

**Comment by ryanthon** [comment]
So I fixed this by just commenting out

`else {
    attributesItem.zIndex = -1;
}
`

in JSQMessagesCollectionViewFlowLayout.m.

**Comment by jadslim313** [comment]
+1

**Comment by algrid** [comment]
Could anyone try this PR? https://github.com/jessesquires/JSQMessagesViewController/pull/1868

**Comment by saltwat5r** [comment]
+1
