### ISSUE TITLE
Providing your own cell prototypes

### ISSUE THREAD

**Issue by brokeniceinteractive** [jessesquires/JSQMessagesViewController#1426]
About this FAQ:

> 2) Providing your own cell prototypes
> 
> This approach is more involved, but gives you greater flexibility. If you need to add or modify subviews of the cell, use this approach. (docs)
> 
> You need to provide your own cell subclasses, similar to the library's JSQMessagesCollectionViewCell, JSQMessagesCollectionViewCellIncoming, JSQMessagesCollectionViewCellOutgoing.
> On your JSQMessagesViewController subclass, set the following properties according to your classes:
> outgoingCellIdentifier
> outgoingMediaCellIdentifier
> incomingCellIdentifier
> incomingMediaCellIdentifier
> Register your cell classes/nibs with the collection view and the identifiers above
> Override -collectionView: cellForItemAtIndexPath:. Do not call super. Since you are providing your own cells, calling super will perform a bunch of unnecessary work.
> (Optional) For your model objects, implement JSQMessageData or subclass JSQMessage and extend to your needs.

Someone has an example tho show how it works... somethings like HelloWordJSQMessagesCollectionViewCellI

thanks!

**Comment by jessesquires** [comment]
Hey @brokeniceinteractive :smile: 

I'm cleaning up old issues and trying to finish the next release of the library. I'm sorry I don't have time to respond to all questions.

I'm going to close this issue, but the community should feel free to continue the discussion.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
