### ISSUE TITLE
Avoid using avatarImage

### ISSUE THREAD

**Issue by otymartin** [jessesquires/JSQMessagesViewController#1428]
I know this is a required delegate method `avatarImageDataForItemAtIndexPath`. however i was wondering if theres a way i can avoid displaying avatar images?
thnx

**Comment by jessesquires** [comment]
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md#remove-avatars

**Comment by glennposadas** [comment]
Link is broken, @jessesquires .

**Comment by EmirAzaiez** [comment]
For people who got broken link: https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md#remove-avatars
