### ISSUE TITLE
How to reload previous messages

### ISSUE THREAD

**Issue by bmoscao** [jessesquires/JSQMessagesViewController#143]
Hi all,

What's the best way to put something like "Load Earlier Messages" in iMessage?

Thanks

**Comment by gs-ronak** [comment]
Any update on this feature? I want to add this feature in my app to load paginated block of messages.

If this is not there in version, can you help me how to proceed?

Thanks

**Comment by wdcurry** [comment]
hey @gs-ronak, perhaps i am speaking out of turn, but this is more a StackOverflow kind of thing perhaps? If not, and i am speaking out of turn, the best way to muddle through these things is it work your own code as best you can, then post snippets and described why your's is not working. Jesse et al have so many tasks relating to a library like this that asking how to implement a basic feature without showing what you have already put into it, is just not fair. {offered fairly, without judgement ;) }

**Comment by harlanhaskins** [comment]
I ended up implementing it with a scrollViewDidScroll delegate method, and pushing a small banner at the top like Messenger does.
