### ISSUE TITLE
Cleanup Toolbar

### ISSUE THREAD

**Issue by otymartin** [jessesquires/JSQMessagesViewController#1430]
How could I clean up the toolbar.
**From this:
**<img width="379" alt="screen shot 2016-02-06 at 6 20 37 pm" src="https://cloud.githubusercontent.com/assets/2222881/12870013/ad1e70e8-ccfe-11e5-9f3c-3a1ebda7d20a.png">

**To this:**
<img width="748" alt="screen shot 2016-02-06 at 6 21 29 pm" src="https://cloud.githubusercontent.com/assets/2222881/12870015/b6d52e56-ccfe-11e5-9c73-739ce811bb5b.png">

I want to remove the border around input box and have the whole toolbar in white background.
Thanks

**Comment by jessesquires** [comment]
Hey @otymartin ! :smile: 

You'll have to provide a custom nib for the toolbar.

#925 should point you in the right direction

**Comment by otymartin** [comment]
Thanks @jessesquires :raised_hands:

**Comment by eliburke** [comment]
@otymartin You can also achieve this look by removing the border on the textview, setting the contentView's background white, and removing the left accessory. Then just set the right button to an image of your choosing.

<img width="384" alt="screen shot 2016-03-29 at 7 22 41 pm" src="https://cloud.githubusercontent.com/assets/2371768/14127133/aea51594-f5e3-11e5-9a2f-dc462a6bfd84.png">

```
    self.inputToolbar.contentView.leftBarButtonItem = nil;
    self.inputToolbar.contentView.textView.layer.borderWidth = 0;
    self.inputToolbar.contentView.backgroundColor = [UIColor whiteColor];
    self.inputToolbar.contentView.textView.placeHolder = @"Type a message...";
    [self.inputToolbar.contentView.rightBarButtonItem setImage:your_image forState:UIControlStateNormal];
```

**Comment by jessesquires** [comment]
thanks @eliburke ! :smile:
