### ISSUE TITLE
video sending problem 

### ISSUE THREAD

**Issue by esvikas** [jessesquires/JSQMessagesViewController#1435]
when i try to send video from local directory ,the video message only show loading indicator ,the video size is on 2second ,any idea?

**Comment by mauruskuehne** [comment]
How are you creating the video message object? I think this could be because of ```JSQVideoMediaItem.isReadyToPlay```. If you set this to ```YES```, the message should then display the image preview.

**Comment by jessesquires** [comment]
Yep! Thanks @mauruskuehne ! :smile:

**Comment by zerskie95** [comment]
In swift, with JSQVideoMediaItem(fileURL: videoURL, isReadyToPlay: true) the video sent and the preview is just black with play button but it doesn't play.
Any idea please?
