### ISSUE TITLE
outgoingMessagesBubble and incomingMessagesBubble on image dont change

### ISSUE THREAD

**Issue by paoloj7** [jessesquires/JSQMessagesViewController#1437]
Hello,
<img width="319" alt="schermata 2016-02-08 alle 20 43 40" src="https://cloud.githubusercontent.com/assets/17108668/12896950/f485b714-cea4-11e5-9e52-89441f2b246f.png">

The messageBubble with image is on correct position on the left, but dont change the arrow, it is on right, but should be on left as the message above it with text "Hey".
my code:
```
override func collectionView(collectionView: JSQMessagesCollectionView!, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageBubbleImageDataSource! {
        
        let factory = JSQMessagesBubbleImageFactory()
        if messages[indexPath.row].senderId == self.senderId {
           return factory.outgoingMessagesBubbleImageWithColor(UIColor.lightGrayColor())
        } else {
           return factory.incomingMessagesBubbleImageWithColor(UIColor.greenColor())
        }
        
    }
```
the senderId of the message with image is not equal at self.senderId.

Thank you.

**Comment by jessesquires** [comment]
hey @paoloj7 :smile:

please see previous questions:
https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+message+bubble+wrong+side+is%3Aclosed
