### ISSUE TITLE
is it possible to show a circularprogressview or hud inside JSQMessagesCollectionViewCell

### ISSUE THREAD

**Issue by sujith1406** [jessesquires/JSQMessagesViewController#1439]
hi is it possible to show a circular progressview inside the JSQMessageCollectionViewCell.I tried adding a hud(MBProgressHUD) in cell.messageBubbleContainerView in collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath method but its showing the image only.The hud is not shown at all.Please guide what would be the good way to accomplish this.I need to show this progressview as the image is uploaded while sending and while its downloading while receiving

**Comment by wdcurry** [comment]
With respect, questions like this are suited to StackOverflow or similar venues. This is simply a mater of using the HUD properly and there are many posts of this nature there.

**Comment by jessesquires** [comment]
Thanks all! :smile:
