### ISSUE TITLE
emoji is cutted

### ISSUE THREAD

**Issue by DKalachniuk** [jessesquires/JSQMessagesViewController#1440]
HI, When I'm trying to add a new emoji to the tectview it is cutted. Please help

![simulator screen shot 11 feb 2016 12 24 07](https://cloud.githubusercontent.com/assets/2156751/12975244/6ac36c98-d0ba-11e5-8615-00c33363a5ae.png)

**Comment by jessesquires** [comment]
Hey @DKalachniuk :smile: 

It looks like you've customized this view a lot. The library doesn't have this problem.

[StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) is more appropriate for this question.

**Comment by fresh83** [comment]
Same problem, all i did was set the font to coder's crux 25 and on all views and this happens. I think this is a very valid issue. Would appreciate any guidance on how one could solve it easily without having to abandon the entire library or spend hours understanding existing code.
