### ISSUE TITLE
showLoadEarlierMessagesHeader

### ISSUE THREAD

**Issue by KhaledAld** [jessesquires/JSQMessagesViewController#1441]
showLoadEarlierMessagesHeader not working with event 
didTapLoadEarlierMessagesButton

**Comment by jessesquires** [comment]
Hey @KhaledAld :smile: 

Please follow the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) when opening a new issue.

Thanks!
