### ISSUE TITLE
showTypingIndicator = NO animation

### ISSUE THREAD

**Issue by DKalachniuk** [jessesquires/JSQMessagesViewController#1442]
Hi again,
So when I'm doing

```
self.showTypingIndicator = YES;
 [self scrollToBottomAnimated:YES];
```
I can see smooth animation, 

but when I'm doing

```
 self.showTypingIndicator = NO;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
    [self.collectionView reloadData];
```

there is no animation for hiding it. Please advise

**Comment by mauruskuehne** [comment]
Thanks @DKalachniuk :grinning: 

I just played around with this and I came up with two ways to achieve this:

#### 1. performBatchUpdated
By doing everything inside of `performBatchUpdates`, the view will correctly scroll up, but the typing indicator will disappear immediately:

```Objective-C
[self.collectionView performBatchUpdates:^{
  self.showTypingIndicator = NO;
  [self.collectionView reloadData];
} completion:^(BOOL finished) {}];
```

#### 2. hide after scrolling
You could also do the scrolling yourself and then hide the typing indicator after the scrolling animation has finished. This approach shows the typing indicator until the end of the scrolling animation, but it scrolls a few pixels too far... :disappointed: 

```Objective-C
NSUInteger itemCount = [self.collectionView numberOfItemsInSection:0];
NSUInteger lastRow = MAX(0, itemCount - 1);
NSIndexPath *finalIndexPath = [NSIndexPath indexPathForItem:lastRow inSection:0];
			
// hide typing indicator after animation is done
[CATransaction setCompletionBlock:^{
  self.showTypingIndicator = NO;
}];
			
//scroll to the message before the typing indicator
[self.collectionView scrollToItemAtIndexPath:finalIndexPath atScrollPosition:UICollectionViewScrollPositionBottom animated:YES];			
```
(I took parts of the scrolling code from `JSQMessagesViewController.scrollToBottomAnimated:`)


I like the first approach much better :smile: I currently can't remember how the animation is in the Messages.app, so I'm not sure which one comes closer to the real app.

@jessesquires what do you think? Did I miss a simpler way to do this?

**Comment by DKalachniuk** [comment]
Thank you @mauruskuehne 
The first solution is perfect! 
Thank you again

**Comment by jessesquires** [comment]
:+1: 

I'm pretty sure you aren't supposed to call `reloadData` from within `performBatchUpdates:`.

Instead, you could reload section `0` (since JSQMessages is single-section)
