### ISSUE TITLE
FirebaseServerValue.Timestamp() to message top label 

### ISSUE THREAD

**Issue by Jackson0111** [jessesquires/JSQMessagesViewController#1444]
Hi, guys. This is a bit unrelated to JSQ issues, but I assume lots of people are using Firebase with JSQMessageViewController, so I'm hoping to find some help here. In my chat VC, each message has a timestamp - top label. I'm using observeEventType  .ChildAdded to load all messages which include all timestamps from Firebase server. The problem is Firebase always fires a placeholder timestamp (aka, local time) first, then replace it with a second call back which has the correct timestamp from the server. This behavior requires to load the message page twice to get correct timestamps, because the first time it only shows local time. Well, I have figured out a way to only display the correct timestamp. By using .ChildChanged, I can ignore the first timestamp and just retrieve the second one. However, this call back gives me future time, exactly one hour two minutes ahead, and I have no clue how to solve this. I have googled for days, but no luck. PLEASE, if someone is using Firebase with JSQMessageViewController, please help me out here. The following is my code:

To save timestamp:

`let timestamp = FirebaseServerValue.timestamp()
let newData = ["sender": "John", "timestamp": timestamp]
ref.childByAppendingPath("messages").childByAppendingPath(ref.authData.uid).setValue(newData)`

In JSQMessageViewController, to retrieve timestamp:

`handle =
 messagesRef.childByAppendingPath(chatId).queryLimitedToFirst(25).observeEventType(.ChildAdded, withBlock: { (snapshot) in
            
            let text = snapshot.value["message"] as! String
            
            let sender = snapshot.value["sender"] as! String
            
            let timestamp = snapshot.value["timestamp"] as! NSTimeInterval
            
            let date = NSDate(timeIntervalSince1970: timestamp/1000)
            
            // TESTING DATE
            let dateFormatter = NSDateFormatter()
            
            dateFormatter.AMSymbol = "AM"
            
            dateFormatter.PMSymbol = "PM"
            
            dateFormatter.dateFormat = "hh:mm, MM'/'dd'/'YY"
            
            let dateString = dateFormatter.stringFromDate(date)
            
            print(dateString)`

And the output is 

`03:37, 02/14/16`

but current time is:

`02:35, 02/14/16`

**Comment by jessesquires** [comment]
>/cc: @davideast :smile:

**Comment by Jackson0111** [comment]
Does `JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate(message.date)` return local time? @jessesquires

**Comment by Jackson0111** [comment]
@jessesquires ok... I just made the most ridiculous mistake in my whole life... It turns out that my computer time was off and I didn't realize that

**Comment by jessesquires** [comment]
Thanks @Jackson0111!
