### ISSUE TITLE
Add UILabel or nonButtonObject to Navigation Bar

### ISSUE THREAD

**Issue by otymartin** [jessesquires/JSQMessagesViewController#1446]
I want to add a UILabel on the left side of the Navigation Bar in my JSQMessagesViewController
I have failed miserably with this code (it doesnt show) and can't seem to find solutions on online.
`func leftNavLabel() {
        
        let leftNavLabel = UILabel()
        leftNavLabel.text = "😜"
        leftNavLabel.sizeToFit()
        leftNavLabel.font = UIFont(name: "HelveticaNeue-Bold", size: 16.0)
        
        let leftItem = UIBarButtonItem(customView: leftNavLabel)
        self.navigationItem.leftBarButtonItem = leftItem
    }`

Eventually, I want to add an animated icon on the right side aswell.

Much appreciated :)

**Comment by jessesquires** [comment]
Thanks @otymartin ! :smile: 

However, this doesn't sound specific to JSQMessages. Did you mean the `inputToolbar` ? If not, [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) would be a better place for this question.
