### ISSUE TITLE
Autolayout constraint for messageBubbleTopLabel resets while scrolling the collectionView

### ISSUE THREAD

**Issue by MohamedThabib** [jessesquires/JSQMessagesViewController#1450]
I am able to customise the JSQMessagesViewController as follows

![screen shot 2016-02-17 at 3 30 22 pm](https://cloud.githubusercontent.com/assets/11331904/13105901/75782022-d58b-11e5-8e0b-a0799261cd94.png)

In the above UI, next to the Incoming Message - "user name" I want to display the "Time stamp" for that I have created following constraint for the messagebubbleTopLabel (Red Color Background).

1. Leading Constraint to avatar Container = 6
2. Top Space Constraint message cell View = 0
3. Bottom Space Constraint to Message bubble container = 0
4.Width space Constraint = 183 and its relation is set to (Less than or Equal)  as shown in the below image

![screen shot 2016-02-17 at 3 27 29 pm](https://cloud.githubusercontent.com/assets/11331904/13106114/8b0f3244-d58c-11e5-8769-9aa35704bb65.png)

the "user name" and "time stamp" displayed perfectly as expected when view is loaded but as soon as when I scroll the Collection View the messageBubbleTopLabel reloads its constraints and appearing as shown in the below message

![screen shot 2016-02-17 at 3 44 01 pm](https://cloud.githubusercontent.com/assets/11331904/13106274/56c7ba5a-d58d-11e5-8036-b1d00cf946c5.png)

**Major Code Changes in code "JSQMessagesCollectionViewFlowLayout.m"**

- (void)jsq_configureFlowLayout //Method Name
{
    self.scrollDirection = UICollectionViewScrollDirectionVertical;
    self.sectionInset = UIEdgeInsetsMake(10.0f, 4.0f, 10.0f, 4.0f);
    self.minimumLineSpacing = 4.0f;
    
    _messageBubbleFont = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    
    if ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad) {
        _messageBubbleLeftRightMargin = 240.0f;
    }
    else {
        **_messageBubbleLeftRightMargin = 10.0f; //Changes to display bubble message in entire screen**
    }
    
    _messageBubbleTextViewFrameInsets = UIEdgeInsetsMake(0.0f, 0.0f, 0.0f, 2.0f); //Changes
    _messageBubbleTextViewTextContainerInsets = UIEdgeInsetsMake(0.0f, 0.0f, 7.0f, 0.0f); //Changes
    
    CGSize defaultAvatarSize = CGSizeMake(kJSQMessagesCollectionViewAvatarSizeDefault, kJSQMessagesCollectionViewAvatarSizeDefault);
    _incomingAvatarViewSize = defaultAvatarSize;
    _outgoingAvatarViewSize = defaultAvatarSize;
    
    _springinessEnabled = NO;
    _springResistanceFactor = 1000;
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(jsq_didReceiveApplicationMemoryWarningNotification:)
                                                 name:UIApplicationDidReceiveMemoryWarningNotification
                                               object:nil];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(jsq_didReceiveDeviceOrientationDidChangeNotification:)
                                                 name:UIDeviceOrientationDidChangeNotification
                                               object:nil];
}

**While scrolling even the media View is hidden**  
I have added the Video link for the reference
https://www.sendspace.com/file/zsodwg

I don't know what mistake I am making and where to set the label width based on text length. Could some one advise me to fix the issue. 

Thanks In Advance.

**Comment by psartzetakis** [comment]
Have you tried the following:

1.Add a Horizontal Spacing constraint between the cellTopLabel and the messageBubbleTopLabel 
![screen shot 2016-02-25 at 10 44 03](https://cloud.githubusercontent.com/assets/3639310/13317345/c936c7b4-dbac-11e5-9fe6-1355960b0cd2.png)
2. Apply the following priorities for the messageBubbleTopLabel
![screen shot 2016-02-25 at 10 46 16](https://cloud.githubusercontent.com/assets/3639310/13317402/087a2f7e-dbad-11e5-8236-29574f98e5c8.png)
3. Apply the following priorities for the cellTopLabel
![screen shot 2016-02-25 at 10 47 03](https://cloud.githubusercontent.com/assets/3639310/13317453/208beb3e-dbad-11e5-9dee-ff87d3677232.png)

I hope that helps :)

**Comment by MohamedThabib** [comment]
@psartzetakis Thanks for your inputs. I tried your solution but it dint work out. Still the issue exists.

**Comment by jessesquires** [comment]
thanks @MohamedThabib ! 😄 

It looks like your view is heavily customized and there's probably not much we can do in the library itself to accommodate any issues.
