### ISSUE TITLE
image shape for customized message bubbles

### ISSUE THREAD

**Issue by Jackson0111** [jessesquires/JSQMessagesViewController#1451]
I wish to use my own customized message bubble, however, I'm not sure if the content will be displayed correctly. Below is the image I want to use, is there a way to display messages in the big box instead of just on top of the whole image? Also, what can I do to make sure the box is correct layout according to the size of messages and images? 
![screen shot 2016-02-18 at 4 07 56 am](https://cloud.githubusercontent.com/assets/13260808/13138565/e8b6328a-d5f5-11e5-8efb-54e310c47eff.png)

**Comment by MacMeDan** [comment]
Ya this should be completely possible you just need to have make your imge conform to the JSQBubbleImage model. You can look at the documentation here. http://cocoadocs.org/docsets/JSQMessagesViewController/7.2.0/Classes/JSQMessagesBubbleImage.html then you just need to use your image in the JSQMessagesBubbleImageFactory that will calculate the size of the message and stretch your image to fit.

**Comment by jessesquires** [comment]
:+1: :heart:

**Comment by Jackson0111** [comment]
Thanks a lot! I will get on that and see what I can accomplish
