### ISSUE TITLE
'JSQMessagesBubbleImageFactory' has no member 'outgoingMessageBubbleImageViewWithColor'

### ISSUE THREAD

**Issue by EkambaramE** [jessesquires/JSQMessagesViewController#1452]
![screen shot 2016-02-18 at 9 01 02 pm](https://cloud.githubusercontent.com/assets/11871096/13148339/f21a0e72-d682-11e5-807b-11fd2402a37f.png)

Integrating in swift i'm getting above error

**Comment by jessesquires** [comment]
Thanks @EkambaramE ! :smile: 

Please search previous issues before opening new ones :smile: 

See #852
