### ISSUE TITLE
1) After load earlier messages, scroll showing at bottom 

### ISSUE THREAD

**Issue by kshrikant** [jessesquires/JSQMessagesViewController#1455]
Hello @jessesquires first of all i'm really thankful for such great library.With the help of this  i've  successfully implemented chat. I have two issues

 1) In load earlier messages i'm facing one small issue - after load earlier scrolling at bottom but i want it at top. How to show scrolling at top ?

	`override func collectionView(collectionView: JSQMessagesCollectionView, header headerView: JSQMessagesLoadEarlierHeaderView, didTapLoadEarlierMessagesButton senderButton: UIButton)
		{
		
			let temp  =  db.selectLastTwenty(messageIDFetched) // In temp earlier 20 messages
	   
			if temp.count > 0
			{
				messageIDFetched =  temp.first!.messageId!
			}
		
			var index = 0
		
			for item in temp
			{
			
					if item.messageType == "M"
					
					{
						let message: JSQMessage = JSQMessage(senderId: item.userName, displayName: item.userName, text: item.message)
						self.messages.insert(message, atIndex: index)
						self.finishReceivingMessageAnimated(true)
					}
					
	   				else if item.messageType == "I"
					{
						if let url  = NSURL(string: item.message!),
							data = NSData(contentsOfURL: url)
						{
							let imgToSend = UIImage(data: data)
							let photoMediaItem = JSQPhotoMediaItem(image: imgToSend)
							photoMediaItem.appliesMediaViewMaskAsOutgoing = false
							let photoMessage: JSQMessage = JSQMessage(senderId: item.userName, displayName: item.userName, media: photoMediaItem)
							self.messages.insert(photoMessage, atIndex: index)
							self.finishReceivingMessageAnimated(true)
						
						}
					
					}
					else if item.messageType == "V"
					{
						JSQSystemSoundPlayer.jsq_playMessageSentSound()
						let url  = NSURL(string: item.message!)
						let videoItem: JSQVideoMediaItem = JSQVideoMediaItem(fileURL: url, isReadyToPlay: true)
						videoItem.appliesMediaViewMaskAsOutgoing = false
						let photoMessage: JSQMessage = JSQMessage(senderId: item.userName, displayName: item.userName, media: videoItem)
						 self.messages.insert(photoMessage, atIndex: index)
						self.finishReceivingMessageAnimated(true)
					}
		  
				index++
			
			}
		
			self.reloadMessagesView()
		}

2) I want chat date (actual date on which chat is done) rather than current date.

         `override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString!
		{
			if indexPath.item % 3 == 0
			{
				let message: JSQMessage = self.messages[indexPath.item]
				print(message.date) // it shows the chat date not current date. 
				//But as a result in chat view its showing current date. Why ?
				
				return JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate(message.date)
			}
			return nil

		}
	
		override func collectionView(collectionView: JSQMessagesCollectionView, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath) -> CGFloat
		{
				if indexPath.item % 3 == 0
				{
				return kJSQMessagesCollectionViewCellLabelHeightDefault
			}
			return 0.0
		}`

Please help me how to fix this two issues ?

**Comment by MacMeDan** [comment]
You need to set `automaticallyScrollsToMostRecentMessage`  that should help with your scrolling issue.
As for your second issue it seems to me that either you are running the demo app to verify the `message.date` is today's date.  If it is in your own app that this is occurring then the problem lies in your `message object` you should be setting the date of your conversation when it is occurring and save it to your backend.

**Comment by jessesquires** [comment]
:+1: :heart:

**Comment by kshrikant** [comment]
Thank you..Both issues resolved :)

**Comment by jessesquires** [comment]
:tada:

**Comment by MacMeDan** [comment]
👏🏾😏 that is what I like to hear. 🤓
