### ISSUE TITLE
ld: framework not found JSQMessagesViewController

### ISSUE THREAD

**Issue by Lilac911** [jessesquires/JSQMessagesViewController#1456]
Hello!

After installing this library, I got this error. 
ld: framework not found JSQMessagesViewController
clang: error: linker command failed with exit code 1 (use -v to see invocation)
When I run the demo, it works fine. but with my project, it shows me this error.
I searched about this issue and didn't get the answer. I tried uninstall it and re install, same problem :(. 
I opened the workspace not the xcproj, same problem. I am using swift 2, so I uncommented use_frameworks!, same problem :(.
Any advice??

**Comment by Lilac911** [comment]
I fixed that by updating the pod to the recommended setting!! went to schema and built the pod then came back to workspace and built it, then fixed!! Thanx.

**Comment by felithub** [comment]
Hi there - I'm getting the same problem. Any chance you could elaborate upon this solution? I have tried updating the pod in terminal. I have also been to Product > Scheme > Build, but it was not obvious where you could rebuild the pod in the way you refer. Thanks.
