### ISSUE TITLE
file was built for x86_64 which is not the architecture being linked (i386)

### ISSUE THREAD

**Issue by Lilac911** [jessesquires/JSQMessagesViewController#1457]
JSQMessagesViewController.framework/JSQMessagesViewController, file was built for x86_64 which is not the architecture being linked (i386)
JSQSystemSoundPlayer.framework/JSQSystemSoundPlayer, file was built for x86_64 which is not the architecture being linked (i386)

I got these issues when building the library, what do they mean and how to fix them??

**Comment by jessesquires** [comment]
Hey @Lilac911 :smile: 

Please complete the issue template. 
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md
