### ISSUE TITLE
Support automatically scrolling to the last message if you are at the end already

### ISSUE THREAD

**Issue by lbanders** [jessesquires/JSQMessagesViewController#1458]
It would be nice to have the ability to let the JSQMessageViewController scroll automatically to new messages only if you are displaying the last message already.
## Scenario:
- You are scrolling the message list. If you do not disable **automaticallyScrollsToMostRecentMessage** the view will automatically scroll to the latest message when one arrives. This would be really annoying if you are browsing through old messages.
- If you open an attachment in a new view to see it full size, when you return and **automaticallyScrollsToMostRecentMessage** is true, you will automatically be scrolled to the end. I would like to the return the same position as I left. Of course you can use scrollToItemAtIndexPath, but this will not always get you the exact same view.
## Suggested solutions:

To solve the above mentioned scenarios there are many different solutions. I have a couple in mind I will suggest here.
### Solution 1

Remove the **automaticallyScrollsToMostRecentMessage** and instead introduce an **automaticScrollMode** option. 
This option could have following values
- None (Never scrolls automatically - like automaticallyScrollsToMostRecentMessage == false)
- ToBottomOnNewMessage (scrolls to the bottom when a new message arrives only)
- ToBottomOnNewMessageOnlyWhenAtLastMessage (scrolls to the bottom when a new messages but only if we are already at the last message)
- ToBottomAlways (like today when automaticallyScrollsToMostRecentMessage == true)
### Solution 2

Introduce a scrolling protocol/delegate to give you events when you scroll.
- didScrollToLastMessage(indexPath: NSIndexPath)

I do not think either solution rules out the other, and they could easily be added both for convenience.

**Comment by jessesquires** [comment]
Thanks @lbanders ! :smile: Great ideas!

I think having a new protocol/delegate will be the most modular. We could have:

```objective-c
- (BOOL)shouldScrollToNewlyReceivedMessageAtIndexPath:(NSIndexPath *)indexPath;
```

Before scrolling automatically, the library would query this method.

This would give clients the most flexibility. They could implement any of the behaviors that you describe above, and more. Not only that, they could implement any of these behaviors *conditionally* — *dynamically* given the current state/context of their program. (Instead of constantly swapping out enum values)

Further, the library could then provide some of these with behavior objects. For example, `JSQScrollBehaviorOnlyAtLastMessage`. These behaviors would implement the protocol above, so clients could just return these. (Similar to the existing bubble size calculators)

**Comment by lbanders** [comment]
I like the protocol you suggest @jessesquires , it is really nice and clean and provides some greater dynamics to the developer in my mind.

I will have a look at the behaviour and see how we can get about the one you suggest. 
If you like, you can assign me to the task. We plan on implementing it here.

**Comment by lbanders** [comment]
An additional improvement to this would be to notify the user of new messages given they do not want to scroll to the bottom.

This could be a delegate method called if `- (BOOL)shouldScrollToNewlyReceivedMessageAtIndexPath:(NSIndexPath *)indexPath;` returns false.

We could have:
`- (BOOL)shouldNotifyUserAboutNewlyReceivedMessageAtIndexPath:(NSIndexPath *)indexPath;`

**Comment by jessesquires** [comment]
>If you like, you can assign me to the task. We plan on implementing it here.

:tada: :+1: 

- Marked the issue as `in-progress` and for the `8.0_release`.
- Unfortunately, github doesn't let us assign issues until people have been added as core contributors. However, after this PR, I'd be happy to add you! :smile: 

>An additional improvement to this would be to notify the user of new messages given they do not want to scroll to the bottom.

Hm... this sounds like more of a client-oriented feature. Not something that would be included in the library. Maybe I'm not understanding correctly though? Either way, let's treat as a new issue for now. :smile:

**Comment by lbanders** [comment]
Perfect - that sounds great :) 

I will make a feature request for the other one as well and we can discuss it on that FR :)

**Comment by jessesquires** [comment]
:sunglasses: :+1:

**Comment by lbanders** [comment]
@jessesquires would you have come about how to detect whether I cell is actually visible in the collectionview?
You can of course ask for visible cells/indexpaths, but that list also shows items that are NOT visible as such - could be hidden beneath a keyboad. I am trying to figure out how to calculate that space that is actually available to display things on and then detect if a cell is visible there.
I have the detection code, just need to figure out the actual available view. Any input would be appreciable :)

**Comment by jessesquires** [comment]
@lbanders -- Hm, can you just check the collection view `contentOffset` and `contentInset`?

Those, compared with `bounds` should give you everything you need. (I think)

**Comment by lbanders** [comment]
Thanks @jessesquires - nailed it with `bounds` and `contententInset`. A PR will come shortly.

**Comment by jessesquires** [comment]
:tada: :+1:

**Comment by papay0** [comment]
Is that working?
I implemented the two functions from JSQMessagesViewControllerScrollingDelegate, but I can't figure out why it is not working :/

**Comment by papay0** [comment]
Is that working?
I implemented the two functions of `JSQMessagesViewControllerScrollingDelegate`, I set the delegate, but I can't figure out why it's still scroll to bottom every time :/

`isLastCellVisible` is always `true` whereas in reality it's not

**Comment by lbanders** [comment]
Hi Arthur

I actually did a bugfix, but it has not been merged to this pullrequest yet.
You can see the change on this commit
https://github.com/jessesquires/JSQMessagesViewController/pull/1489/commits/97185d0017a180b35e05bae2fd7ffa8179d26275
That should solve your issue :)

/Leif

**Comment by papay0** [comment]
😃👍
Thanks!
😃👍

**Comment by MHX792** [comment]
How to do this in Swift? I cannot find a function called `shouldScrollToNewlyReceivedMessageAtIndexPath` or the property `isLastCellVisible`.

Has this been removed from JSQMessagesViewController?

**Comment by lbanders** [comment]
Hello  We use it from Swift. The shouldScrollToNewlyReceivedMessageAtIndexPath    is a delegate metodth you need to implement if you want any say on whether to scroll to a newly received message or not.  Regarding the property I am not sure as of why you don't see it. Have you imported the JSQMessagesViewController in your class?  Best regards   Leif   

---Sent from Boxer | http://getboxer.com

On 17. juni 2016 kl. 23.31.42 GMT+4, MHX792 <notifications@github.com> wrote:How to do this in Swift? I cannot find a function called shouldScrollToNewlyReceivedMessageAtIndexPath  or the property isLastCellVisible .  Has this been removed from JSQMessagesViewController?  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MHX792** [comment]
Yes, it is imported:

![screen shot 2016-06-18 at 11 52 50](https://cloud.githubusercontent.com/assets/12123471/16170212/79ce85f6-354b-11e6-91a8-cf7dccd4e842.png)
![screen shot 2016-06-18 at 11 53 52](https://cloud.githubusercontent.com/assets/12123471/16170213/7ba6fe26-354b-11e6-9ce5-a42dadb83a26.png)

It also cannot find `JSQMessagesViewControllerScrollingDelegate` when I search for it in the workspace. The current demo project doesn't contain it either.

**Comment by tunidev** [comment]
seems interesting, what is the status of the this feature ? and can we expect v8 during this month ?

**Comment by papay0** [comment]
**isLastCellVisible:**

> This property is updated when the view finish scrolling.

Isn't it better to **set isLastCellVisible to false** directly when the last cell is not visible anymore?
Because in a Chat with a lot of users, it keeps scrolling down when I try to go up.

Why is it better to update `isLastCellVisible` only when the view finish scrolling? (use case?)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
