### ISSUE TITLE
layer SDK - iOS to Android or vice versa - Photos not working.

### ISSUE THREAD

**Issue by testerdev** [jessesquires/JSQMessagesViewController#1461]
We integrated JSQ with Layer (layer.com Atlas https://github.com/layerhq/Atlas-iOS) and appears there is a problem when sharing/sending photos between Android > iOS or iOS > Android.

The photos come blank on the iOS side when sent from Android  and appears as tiny thunbnails when sent from iOS to Android.

Any help or guidance would be appreciated.

**Comment by jessesquires** [comment]
Thanks @testerdev ! :smile: 

Unfortunately, this sounds like it does not have anything to do specifically with JSQMessages.
