### ISSUE TITLE
Audio message in JSQMessagesViewController

### ISSUE THREAD

**Issue by kshrikant** [jessesquires/JSQMessagesViewController#1462]
@jessesquires 
Recently i completed chat using JSQMessagesViewController and its working fine for Video, Image & Text. Now, I want to implement Audio message for existing JSQMessagesViewController. Is there anyone who implemented audio message for the same ?

I just got the link https://github.com/jessesquires/JSQMessagesViewController/issues/1049 in that there is file EXTJSQMediaMessage.swift but i didn't find it helpful.

Please help me how to implement this feature ?

**Comment by jessesquires** [comment]
Thanks @kshrikant ! :smile: 

#1049 is a feature that we would like to have, but do not have time for right now. We are accepting pull requests, though. You can follow the example of the other included media items.

Also, next time you open an issues, please use the provide template and be sure you follow our guidelines! :smile_cat: (I've copied them below)

--------------------------------------------------------------

#### Guidelines

* [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) is often the most appropriate place for questions and help.
* **Only ask questions that are _specific_ to this library.**

#### Checklist

- [ ] I have reviewed the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have searched issues for already asked [questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+). 
- [ ] I have reviewed [Migration Guide](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/migration.md) for migrating between major versions.
- [ ] **This is not a duplicate.**
