### ISSUE TITLE
Text positioning in bubbles

### ISSUE THREAD

**Issue by McFriend** [jessesquires/JSQMessagesViewController#1464]
Hi, text in bubbles is not in the center for me.
![textinbubble](https://cloud.githubusercontent.com/assets/15579237/13302248/f7f4f420-db59-11e5-9eeb-4a7ddd330545.png)

**Comment by jessesquires** [comment]
Thanks @McFriend ! :smile: 

Please use our issue template to update your issue. Thanks!
