### ISSUE TITLE
Chat box, keyboard problem

### ISSUE THREAD

**Issue by xiongcaixing1986** [jessesquires/JSQMessagesViewController#1466]
In iOS 9, the keyboard disappeared more difficult, and there is no drag gesture

**Comment by jessesquires** [comment]
thanks @xiongcaixing1986 ! :smile: 

closing this as a duplicate of #1063.

please make sure you follow our guidelines and complete the issue template next time.

**Comment by xiongcaixing1986** [comment]
thanks
