### ISSUE TITLE
MediaItem inside Bubble instead of beeing the whole bubble

### ISSUE THREAD

**Issue by maxiundtesa** [jessesquires/JSQMessagesViewController#1469]
Hello,
I want to have the mediaItems inside a messagebubble, just like whatsapp is doing.
I changed the JSQMessagesCollectionViewCellIncoming.xib and the JSQMessagesCollectionViewCellOutgoing.xib to achieve this with text messages, 
but I am not able to figure out how to change the mediaView to do the same.
It now looks like this:
![simulator screen shot 28 02 2016 14 40 32](https://cloud.githubusercontent.com/assets/17526240/13379603/62e5ca52-de2a-11e5-8fc7-84ee43a05191.png)

![incomingbubble](https://cloud.githubusercontent.com/assets/17526240/13379599/4005f1a6-de2a-11e5-94ba-a58c5870adcf.png)
I want, that if a message is a mediamessage, to delete the textfield and replace it with the mediaView. In the end, I would like to have the bubbleTopLabel, the cellBottomLabel and the mediaView inside the bubble, it should look like this afterwards:
![img_1592](https://cloud.githubusercontent.com/assets/17526240/13379608/7e3c1bf8-de2a-11e5-9d94-735af68d79c6.PNG)

Does somebody know how to do this?

This is my setMediaView method:
```
- (void)setMediaView:(UIView *)mediaView
{
    [self.textView removeFromSuperview];
    [mediaView setTranslatesAutoresizingMaskIntoConstraints:NO];
    mediaView.frame = self.messageBubbleContainerView.bounds;
    self.dateAbstandConstraint.constant = 5;
    [self.messageBubbleContainerView insertSubview:mediaView atIndex:1];
    [self.messageBubbleContainerView jsq_pinAllEdgesOfSubview:mediaView];
    _mediaView = mediaView;
  }
```

**Comment by jessesquires** [comment]
Hey @maxiundtesa :smile: 

This doc should help:
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md#need-customize-your-collection-view-cells
