### ISSUE TITLE
NSRangeException when coming from back button

### ISSUE THREAD

**Issue by aoguzhan** [jessesquires/JSQMessagesViewController#1474]
Hey,

I am having a strange issue. I ve implemented JSQMessages according to the demo project. And everything works great. But; I have a custom button for `rightBarButtonItem` which pushes different view to navigation stack. if i click that button, or click another tab button while `JSQMessagesViewController` is open, and press back button to go back to the messages view, it throws error like this:

`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 38 beyond bounds for empty array'`

and with exception breakpoint, i catch it here:

```
- (id<JSQMessageData>)collectionView:(JSQMessagesCollectionView *)collectionView messageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    return [self.messages objectAtIndex:indexPath.item];
}
```

it seems this error occurs because my `self.messages` is empty. But. it is also empty in other situations, like pushing message view from messages page. `self.messages` gets loaded after view will appeared or loaded. this is happening only if i try to open `messages view` from a `back` button.

am i missing something? or is this a bug?

thanks.

**Comment by aoguzhan** [comment]
@jessesquires or anyone else has any idea on this? thanks

**Comment by jessesquires** [comment]
Hey @aoguzhan :smile: -- sounds like an issue on your side.

Can you reproduce this in the demo project?
