### ISSUE TITLE
Custom changes on xib files and other questions

### ISSUE THREAD

**Issue by iad24** [jessesquires/JSQMessagesViewController#1475]
Sorry. Noob here. These are just a questions. I dont know where to put them and have them here instead.

1. Lets say I get JSQMessageVC using pods but then I need to add new views on the and some code change on the JSQMessagesCollectionViewCellIncoming files (these changes maybe only applicable to my app and may be irrelevant to others). How will I do that? Or need to copy the src code and include them in my project?

2. How to remove the smiley icon in the input toolbar keyboard? I dont want my app sending them

3. For some reasons, when I entered messages like "a.com" (or anything then .com), blank is displayed in the bubbles.

Thanks

**Comment by MacMeDan** [comment]
Check out this answer on stackoverflow :Custom cell for JSQMessages http://stackoverflow.com/a/35399408/5894123. In regards to your first question. 
The second question I don't know how you would do that besides implementing your own custom keyboard or just detecting emojis and throwing an error when the send button is pressed. Maybe others would have better suggestions. 
The third may be related to data detectors but might be a bug we need to look into it more. 

👷🏼 let us know if you resolve these and how your progress goes.
