### ISSUE TITLE
Navigation bar pushing up when keyboard opens

### ISSUE THREAD

**Issue by gmogames** [jessesquires/JSQMessagesViewController#1478]
Hello there,

I'm using the latest version of the library, and tested on iOS 9 and iOS 8.

I'm inside of a stack of ViewControllers all connected through a single UINavigationController. When pushing the Messages screen, everything looks fine, but when you tap to enter the message and the keyboard opens, my Navigation Bar is being pushed up, making it half visible. If you open the word suggestions toolbar above the keyboard, then the Nav bar moves further up.

~~But also, during this moving up, the messages on the screen get pushed down a bit. here is the screenshots:~~

![simulator screen shot mar 3 2016 14 34 43](https://cloud.githubusercontent.com/assets/1765046/13506821/e154cd36-e14d-11e5-9e56-71cfca43831b.png)
.
![simulator screen shot mar 3 2016 14 34 48](https://cloud.githubusercontent.com/assets/1765046/13506823/e1a6ed1e-e14d-11e5-9086-eead39a30bbe.png)
.
![simulator screen shot mar 3 2016 14 34 51](https://cloud.githubusercontent.com/assets/1765046/13506824/e253ac7a-e14d-11e5-8f3b-c2992293502d.png)

I did not do any different implementation then what is provided in the Demo, this is using all the default methods provided by the SDK (Message bubbles and avatar image).

Not really sure why this is happening, any help is highly appreciated.

Thanks

**Comment by gmogames** [comment]
Actually it seems that the messages were pushed down, but they were not, it's because the nav bar goes up giving the impression, so, my problem is only with the navigation bar scrolling up.

**Comment by gmogames** [comment]
Well,

After digging deep into this, I noticed that another developer had installed IQKeyboardManager in the project, which auto scrolls the view when a keyboard opens, and that was causing a conflict with the Messages view controller.
All I had to do is disable IQKeyboardManager for my Messages view controller class in my AppDelegate.

Thanks and sorry for adding more issues to your list

**Comment by BeauNouvelle** [comment]
Don't apologise, even though this is 8 months old, this post helped me out as I also have IQKeyboard manager installed and was seeing the same issue. 

A quick google search bought me here. Saved me a lot of time. 

So thank you
