### ISSUE TITLE
Intercepting touch events in cutom top view

### ISSUE THREAD

**Issue by jalone87** [jessesquires/JSQMessagesViewController#1480]
#### General information

- Library version(s): 7.2.0
- iOS version(s): 9.0.2 (same behaviour on all devices between with ios8+, lower version not tested)
- Devices/Simulators affected: all devices after iphone4s (5, 5s, 6, 6+,...)
- Reproducible in the demo project (Y/N):  N

#### Expected behavior

I need to set an additional bar below the navigation bar. To achieve this a subclass of JSQMessagesViewController instantiate and add a subview (through layout constraints) and self.topContentAdditionalInset is set as the height of the view. It should be then possible to intercept a tap on such view.

#### Actual behavior

The view is added correctly but **no touch event is ever intercepted on the additional top view**. I have tried with gesture recognizer, buttons, ecc either on the view, the subviews ecc.
The custom view touch events are correctly intercepted if it is added in other 'normal' view controllers but no trace when subview of JSQMessagesViewController. 

I am thinking to override UIWindow touch callback, but i'd like to avoid it.

**Comment by jessesquires** [comment]
@jalone87 maybe try calling `bringSubviewToFront:` ?

can you provide any more info on how you are adding this view?
