### ISSUE TITLE
How to display received/ attached images with text associated with them?

### ISSUE THREAD

**Issue by hemantkadam** [jessesquires/JSQMessagesViewController#1487]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md).
- [x] I have read the [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have reviewed the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

#### My question
I've recently started working on chat app using JSQMessagesViewController. I'm new to this lib but need to know if there's any way to display images with text on chat screen? If so how can i achieve it, if not is it going to be available is upcoming releases? 

Thank you.

**Comment by eliburke** [comment]
@hemantkadam Can you clarify what you are asking for? Perhaps a mockup would help, or a screenshot from another app? 
- Issue #681 has some screenshots and discussion on combining text and media. The short answer is... you can send them in succession, or you can create your own media type that combines the two. 
- There is also labeling of media, as in PR #1520 (a work in progress) 
- There is also INPUT of mixed types, as in PR #1516 (also a work in progress)

**Comment by eliburke** [comment]
@hemantkadam Sadly there isn't a team of paid developers working to make this look as great as WhatsApp 😜. Perhaps you can publish your MediaItem class for folks to collaborate on and improve.

**Comment by svtechnology** [comment]
You need to add some blur to the label background, change the colour to black and that should be a fine start at refinement. Even better would be what @eliburke suggested. Submit a PR and we can probably improve on what you already have.

**Comment by jessesquires** [comment]
:+1:

**Comment by gmansata6290** [comment]
@hemantkadam 

Can you provide me the sample which you have implemented please?

**Comment by hemantkadam** [comment]
@gmansata6290 I did as @eliburke suggested, created MediaItem class for Photo, Video and Audio.

**Comment by gmansata6290** [comment]
@hemantkadam so you have not implemented from [this](https://github.com/jessesquires/JSQMessagesViewController/issues/1739#issuecomment-246489889)

Because I have implmented from that guideline causing some issue. Can you help me out in this?

**Comment by gmansata6290** [comment]
@hemantkadam  Hemant thanks for your tips and I created MediaItem Class and It is working as expected. But the only thing what if I want lbl or textView and buttons? Can you just guide me?
