### ISSUE TITLE
link color

### ISSUE THREAD

**Issue by cbarbera80** [jessesquires/JSQMessagesViewController#1488]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md).
- [x] I have read the [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have reviewed the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

<details>
<summary><strong>Bug report</strong></summary>

#### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project (Y/N): 
- Link to a project that exhibits the issue (if possible):
- List any related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce the behavior

> ...

#### Crash log?

*Can you provide a crash log?*

>...

#### Screenshots or videos?

*Can you provide screenshots, GIFs, or videos showing the issue?*

> ...

</details>

<details>
<summary><strong>Question/Help</strong></summary>

#### My question

>...

</details>

<details>
<summary><strong>Feature Request</strong></summary>

#### My feature request

- Why should it be included in the library?
- What problems does it solve?
- Please provide design/implementation details, if possible.

> ...
</details>

**Comment by cbarbera80** [comment]
Hi, it is possible to change link color inside bubble?

**Comment by davepatterson** [comment]
Thanks @cbarbera80! :smile_cat: 

Yes, you can change the link color inside bubble images. This can be accomplished in `(UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath`. In this method, you would override the `cell.textView.linkTextAttributes`. For example, if you wanted to change the link color to red you would do the following:

    - (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
    {
        JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];
        cell.textView.linkTextAttributes = @{ NSForegroundColorAttributeName : [UIColor redColor],
                                              NSUnderlineStyleAttributeName : @(NSUnderlineStyleSingle | NSUnderlinePatternSolid) };
    }
