### ISSUE TITLE
Swift project

### ISSUE THREAD

**Issue by ivandiazmolina** [jessesquires/JSQMessagesViewController#1490]
Is available JSQMessagesViewController to Swift? I have found one (https://github.com/firebase/ios-swift-chat-example/tree/master/JSQMessagesViewController) but it is not complete like this

Thx and regards

**Comment by MacMeDan** [comment]
there is a pull request for one https://github.com/jessesquires/JSQMessagesViewController/pull/1491
also let me know if you have any other questions of using it. It is only a start and will grow with time. 👻 Good Luck.

**Comment by jessesquires** [comment]
:+1: 

also, @ivandiazmolina -- release 8.0 will be much more swift friendly :smile:
