### ISSUE TITLE
Adjust the bubble margin of the JSQMessagesCollectionViewCell

### ISSUE THREAD

**Issue by bofiaza** [jessesquires/JSQMessagesViewController#1498]
[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/Qo8PJ.png

I'm using tailed and tailless bubble image for the incoming and outgoing messages. The (code for the) cell for the outgoing and incoming are pretty much alike. But, as you can see in the image, the bubble for the tailless incoming message is slightly off to the left. How can I adjust this?

I'm still learning the library but any quick help is very much appreciated. Thanks!

**Comment by MacMeDan** [comment]
Hey @bofiaza I think what you are looking for is adjusting the  `_messageBubbleLeftRightMargin` I found it in the `JSQMessagesCollectionViewFlowLayout` line 73. 
Technically the bubbles are lining up edge to edge(of the tail) So you are going to want to make something that returns a different `_messageBubbleLeftRightMargin` based on wether or not it is tailed or not. This should help you get where you wanna go. 🛠👻

**Comment by bofiaza** [comment]
Hi @MacMeDan! Is there a way to adjust the `_messageBubbleLeftRightMargin` based on the indexPath? I mean, I don't see a delegate method for that.

**Comment by jessesquires** [comment]
hey @bofiaza :smile: 

currently `_messageBubbleLeftRightMargin` this is all or nothing. feel free to open a feature request issue, though. this could be implemented in v8.0

also, what you're seeing here for incoming bubbles is the spacing for the avatar. you can also disable this. see the FAQ for details.

**Comment by AdamZikmund** [comment]
this helped me `self.collectionView.collectionViewLayout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)`

**Comment by carloscrono** [comment]
The answer from @AdamZikmund worked fine. Now I am trying to set margins between bubbles. Top margin and bottom margin. Is there a way?

![iost_test](https://cloud.githubusercontent.com/assets/8271542/22377881/1f98fdea-e479-11e6-9a60-cd45cfd95794.png)

**Comment by acjh** [comment]
Adjust `minimumLineSpacing` in [JSQMessagesCollectionViewFlowLayout.m](https://github.com/jessesquires/JSQMessagesViewController/blob/cebe8763fafdb1b7ba3d41988892ffd8f6e24d97/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.m#L65) (See: [Apple API Reference](https://developer.apple.com/reference/uikit/uicollectionviewflowlayout/1617717-minimumlinespacing))

**Comment by carloscrono** [comment]
Thanks @acjh this worked

**Comment by otymartin** [comment]
@acjh @jessesquires 
How can I set different minimumLine spacing between a string of incomingbubbles and a string of outgoing bubbles?

**Comment by acjh** [comment]
`minimumLineSpacing` is for all rows or columns of a section.

For your case, you can override:
```swift
func collectionView(_ collectionView: JSQMessagesCollectionView,
                    layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout,
                    heightForCellTopLabelAt indexPath: IndexPath) -> CGFloat
```

Check if `message.senderName` at `indexPath.item` is different from that at `indexPath.item - 1`.

**Comment by otymartin** [comment]
Beautiful, thank you @acjh :)
