### ISSUE TITLE
Any way for a manual import, similar to the Firebase project?

### ISSUE THREAD

**Issue by dudduss** [jessesquires/JSQMessagesViewController#1501]
My project currently uses the Google Maps and Braintree APIs through cocoapods and if I add the use_frameworks! line to the project it will make it break unfortunately. Is there anyway to do a manual import of this project and have it work, because I tried that and I kept getting an unable to find module error? Is there a way also to use_frameworks for some pods and not for others, because that could solve it as well? Any other solutions to my issue would be a big help as well!

**Comment by jessesquires** [comment]
Sorry @dudduss ! `v8.0` of the library will fix this 😄 

Until then:

- You can add the project manually
- You can use git submodules
