### ISSUE TITLE
Changing the 'load earlier messages' button properties

### ISSUE THREAD

**Issue by kvndevils** [jessesquires/JSQMessagesViewController#1502]
## Question

Hi All,

Is it possible to change the loadButton properties like font & color using SWIFT?
I'm struggling to access it in JSQMessagesLoadEarlierHeaderView.

Thanks

**Comment by jessesquires** [comment]
Thanks @kvndevils ! 😄 

All of this is possible by overriding the collectionViewDataSource's supplementaryView methods. See the demo for an example.
