### ISSUE TITLE
Strange layout behavior on iPad when chat appears

### ISSUE THREAD

**Issue by betzerra** [jessesquires/JSQMessagesViewController#1503]
### General information
- Library version(s):7.2.0
- iOS version(s): iOS 9.2.1 (but probably any)
- Devices/Simulators affected: iPad Air 2 (but probably any)
- Reproducible in the demo project (Y/N): N
## Bug report

I'm experiencing this layout weird behavior on iPad (see video). 
Any clue what could be triggering this?
#### Screenshots or videos?

https://www.dropbox.com/s/kcmo9f7vdgy06ac/chat_ipad_bug.mov?dl=0

**Comment by Lucashuang0802** [comment]
@betzerra Do you think you can replicate the problem from the demo app? That's easier to address the problem. 😺

**Comment by jessesquires** [comment]
@betzerra - do you still see this issue on `v7.3.4` ?

**Comment by betzerra** [comment]
@Lucashuang0802 it'll take me some time to reproduce it since I don't know clearly what differences I have between that project and the demo project.

@jessesquires yup. Still happening on `v7.3.4`.

To be honest guys, don't worry about this too much. This is happening on an internal demo project that we have, the important project that is using this library works without any problems. I was just curious about what might be triggering this and making sure this won't happen anywhere else.

**Comment by jessesquires** [comment]
Thanks so much @betzerra ! 💯 

I think this will be resolved by #1601 anyway

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
