### ISSUE TITLE
Collection View is only loading two texts at a given time

### ISSUE THREAD

**Issue by dudduss** [jessesquires/JSQMessagesViewController#1504]
When I add multiple test messages, only two of them are displaying on screen. The other messages are clearly there becasue I can copy them, but the colors are simply not showing. When I scroll around, a new two texts appear, but it is still only two. Below show some examples.

<img width="374" alt="screen shot 2016-03-17 at 3 36 29 am" src="https://cloud.githubusercontent.com/assets/9653576/13843580/bfea1c10-ebf1-11e5-8056-0da179a9eabe.png">
<img width="377" alt="screen shot 2016-03-17 at 3 36 35 am" src="https://cloud.githubusercontent.com/assets/9653576/13843579/bfe9e786-ebf1-11e5-983b-e79ad6a79c5e.png">
<img width="380" alt="screen shot 2016-03-17 at 3 37 49 am" src="https://cloud.githubusercontent.com/assets/9653576/13843581/bfecb1dc-ebf1-11e5-8faf-c38620b24e15.png">

First screenshot shows when the screen first loads. second shows when I move it around. Third shows that the other messages do exist but are not visible. Any ideas on how to fix this? Also, how do I make the names appear? Is there a good guide to doing this in Swift?

Here is the code I'm using:

` var messages = [JSQMessage]()

    var incomingBubbleImageView = JSQMessagesBubbleImageFactory.incomingMessageBubbleImageViewWithColor(UIColor.jsq_messageBubbleLightGrayColor())
    var outgoingBubbleImageView = JSQMessagesBubbleImageFactory.outgoingMessageBubbleImageViewWithColor(UIColor.jsq_messageBubbleGreenColor())

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.sender = UIDevice.currentDevice().identifierForVendor?.UUIDString
        messages += [JSQMessage(text: "hello", sender: self.sender)]
        messages += [JSQMessage(text: "hello", sender: "other")]
        messages += [JSQMessage(text: "hello", sender: self.sender)]
        messages += [JSQMessage(text: "hello", sender: "other")]
        messages += [JSQMessage(text: "hello", sender: self.sender)]
        messages += [JSQMessage(text: "hello", sender: "other")]
        
        reloadMessagesView()
        
    }
`

**Comment by jasonlagaac** [comment]
Do you have any sample code or a sample project? :)

**Comment by dudduss** [comment]
This is the file that I'm currently experimenting with. Code all looks right, but I'm not sure where I'm messing up. 
[jsq folder.zip](https://github.com/jessesquires/JSQMessagesViewController/files/183292/jsq.folder.zip)

**Comment by jasonlagaac** [comment]
Here's some code that I have working based on your sample code :)

[Issue1504.zip](https://github.com/jessesquires/JSQMessagesViewController/files/191596/Issue1504.zip)

**Comment by jessesquires** [comment]
Thanks @jasonlagaac ! :smile:

**Comment by dudduss** [comment]
Hi,

Weirdly enough, your code sample uses different files than mine and when I try to copy over the files in the current Github, my project errors out for some reason. Any tips on how to properly manually import the most recent version of this project?
