### ISSUE TITLE
Not getting chat bubble using JSQMessageViewController in ios

### ISSUE THREAD

**Issue by abdulvy** [jessesquires/JSQMessagesViewController#1505]
I am not getting Chat Bubble in JSQMessageViewController but not able to get what to method to be add to get chat bubble in my chat page in IOS I am getting only Textbox and send button when I type text and click send not getting bubbles I am new please help me. 

	

//
//  ChatpageViewController.h
//  ChatApp
//
//  Created by VY's iMAC 01 on 17/03/16.
//  Copyright (c) 2016 VY's iMAC 01. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <JSQMessagesViewController/JSQMessages.h>
#import <JSQMessagesViewController.h>
#import "JSQMessagesCollectionViewFlowLayout.h"
#import "JSQMessages.h"
#import "JSQPhotoMediaItem.h"
#import "JSQLocationMediaItem.h"
#import "JSQVideoMediaItem.h"
#import "JSQMessagesMediaViewBubbleImageMasker.h"
#import "JSQMessagesAvatarImage.h"
#import "JSQMessagesAvatarImageFactory.h"
#import "JSQMessagesBubbleImage.h"
#import "JSQMessagesBubbleImageFactory.h"
#import "UIImage+JSQMessages.h"
#import "Chat.h"

@interface ChatpageViewController : JSQMessagesViewController<JSQMessagesCollectionViewDataSource,JSQMessagesCollectionViewDelegateFlowLayout,JSQMessagesCollectionViewCellDelegate,JSQMessageData,JSQMessageMediaData,JSQMessageAvatarImageDataSource,JSQMessageBubbleImageDataSource>
{
    NSMutableArray * fularray;
}
@property(nonatomic,strong)NSDictionary * receivedict;

@property (strong, nonatomic) IBOutlet UILabel *name;
@property (strong, nonatomic) IBOutlet UILabel *mobile;

@property (strong, nonatomic) JSQMessagesBubbleImage *outgoingBubbleImageData;
@property (strong, nonatomic) JSQMessagesBubbleImage *incomingBubbleImageData;

- (IBAction)cancelbtn:(id)sender;

@end

****************
.M FILe

//
//  ChatpageViewController.m
//  ChatApp
//
//  Created by VY's iMAC 01 on 17/03/16.
//  Copyright (c) 2016 VY's iMAC 01. All rights reserved.
//

#import "ChatpageViewController.h"
#import "DemoModelData.h"

@interface ChatpageViewController ()
{
    DemoModelData *demoData;
}

@end

@implementation ChatpageViewController
@synthesize receivedict,name,mobile;

-(void)viewWillAppear:(BOOL)animated
{
   self.collectionView.collectionViewLayout.springinessEnabled = YES;
}

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    
     fularray = [[NSMutableArray alloc] init];
       // Do any additional setup after loading the view.
   // [self.navigationController setNavigationBarHidden:NO animated:YES];
NSLog(@"%@",receivedict);
    name.text = [receivedict objectForKey:@"Name"];
    mobile.text =[receivedict objectForKey:@"Mobile"];
    demoData = [[DemoModelData alloc] init];
    JSQMessagesBubbleImageFactory *bubbleFactory = [[JSQMessagesBubbleImageFactory alloc] init];
    
    self.outgoingBubbleImageData = [bubbleFactory outgoingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleBlueColor]];
    self.incomingBubbleImageData = [bubbleFactory incomingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleLightGrayColor]];
}

- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    JSQMessage *message = [fularray objectAtIndex:indexPath.item];
    
    if ([message.senderId isEqualToString:self.senderId]) {
        return self.outgoingBubbleImageData;
    }
    
    return self.incomingBubbleImageData;
}
- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}
- (NSString *)senderId
{
    return [receivedict objectForKey:@"Mobile"];
}
- (NSString *)senderDisplayName
{  
    return [receivedict objectForKey:@"Name"];
}
- (NSDate *)date
{
    return 18/03/2016;
}
- (void)didPressSendButton:(UIButton *)button withMessageText:(NSString *)text senderId:(NSString *)senderId senderDisplayName:(NSString *)senderDisplayName date:(NSDate *)date
{
    
    [JSQSystemSoundPlayer jsq_playMessageSentSound];
    
    JSQMessage *message = [[JSQMessage alloc] initWithSenderId:senderId
                                             senderDisplayName:senderDisplayName
                                                          date:date
                                                          text:text];
    // [demoData.messages addObject:message];
    [self finishSendingMessageAnimated:YES];
    
    [fularray addObject:message];
    NSLog(@"%@",message);
}

- (IBAction)cancelbtn:(id)sender
{
    [self.navigationController popViewControllerAnimated:YES];
}
@end

I have mentioned my project file link bellow dropbox.com/s/41rwahp082g999g/ChatAppod.zip?dl=0

**Comment by jasonlagaac** [comment]
You're missing some stuff that should be implemented.

```
//
//  ChatpageViewController.m
//  ChatApp
//
//  Created by VY's iMAC 01 on 17/03/16.
//  Copyright (c) 2016 VY's iMAC 01. All rights reserved.
//

#import "ChatpageViewController.h"
#import "DemoModelData.h"

@interface ChatpageViewController ()
{
    DemoModelData *demoData;
}

@end

@implementation ChatpageViewController
@synthesize receivedict,name,mobile;




-(void)viewWillAppear:(BOOL)animated
{
    
    //self.collectionView.collectionViewLayout.springinessEnabled = YES;
}

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    
     fularray = [[NSMutableArray alloc] init];
       // Do any additional setup after loading the view.
   // [self.navigationController setNavigationBarHidden:NO animated:YES];
NSLog(@"%@",receivedict);
    name.text = [receivedict objectForKey:@"Name"];
    mobile.text =[receivedict objectForKey:@"Mobile"];
    demoData = [[DemoModelData alloc] init];
    JSQMessagesBubbleImageFactory *bubbleFactory = [[JSQMessagesBubbleImageFactory alloc] init];
    
    self.outgoingBubbleImageData = [bubbleFactory outgoingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleBlueColor]];
    self.incomingBubbleImageData = [bubbleFactory incomingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleLightGrayColor]];
    
    
    
    
    
}


- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    JSQMessage *message = [fularray objectAtIndex:indexPath.item];
    
    if ([message.senderId isEqualToString:self.senderId]) {
        return self.outgoingBubbleImageData;
    }
    
    return self.incomingBubbleImageData;
}

- (id<JSQMessageAvatarImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageDataForItemAtIndexPath:(NSIndexPath *)indexPath {
    return [JSQMessagesAvatarImageFactory avatarImageWithUserInitials:@"JL" backgroundColor:[UIColor blueColor] textColor:[UIColor whiteColor] font:[UIFont systemFontOfSize:12.0] diameter:30.0];
}

- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section {
    return [fularray count];
}

- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView {
    return 1;
}

- (id<JSQMessageData>)collectionView:(JSQMessagesCollectionView *)collectionView messageDataForItemAtIndexPath:(NSIndexPath *)indexPath {
    return fularray[indexPath.row];
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (NSString *)senderId
{
    return @"Test";
}


- (NSString *)senderDisplayName
{
    
    return @"Test";
}

- (NSDate *)date
{
    return 18/03/2016;
}

- (void)didPressSendButton:(UIButton *)button withMessageText:(NSString *)text senderId:(NSString *)senderId senderDisplayName:(NSString *)senderDisplayName date:(NSDate *)date
{
    
    [JSQSystemSoundPlayer jsq_playMessageSentSound];
    
    JSQMessage *message = [[JSQMessage alloc] initWithSenderId:senderId
                                             senderDisplayName:senderDisplayName
                                                          date:date
                                                          text:text];
    // [demoData.messages addObject:message];
    [self finishSendingMessageAnimated:YES];
    
    [fularray addObject:message];
    [self.collectionView reloadData];
    NSLog(@"%@",message);
}



- (IBAction)cancelbtn:(id)sender
{
    [self.navigationController popViewControllerAnimated:YES];
}





@end
```

**Comment by abdulvy** [comment]
jasonlagaac it is working fine.

**Comment by abdulvy** [comment]
How to bring Navigation Bar in this please

**Comment by jessesquires** [comment]
Thanks @jasonlagaac ! :smile:
