### ISSUE TITLE
Messagges View Controller not show pushing, but only modally

### ISSUE THREAD

**Issue by fabriziopera** [jessesquires/JSQMessagesViewController#1506]
### General information

- Library version(s): 7.2.0 (cocoapods)
- iOS version(s):9
- Devices/Simulators affected: all simulators, iphone 6 (only tested)
- Reproducible in the demo project (Y/N):  N
- List any related issues:

## Bug report

Hi, i'm include your library on my project, but i have one important problem.
My app is based on Tabbed application and in one of this tab i have a navigation controller, the rootViewController show a table list with many threads and i have been set a segue on table cell to show my JSQMessagesViewController subclass. The problem is when perform segue the viewController is loaded but not shown on navigationController. I've tried to pushing programmatically but is the same.

But if i change segue type to present modally the view controller is shown.

What's the problem?

Thanks.

Fabrizio Pera.

**Comment by jessesquires** [comment]
Hey @fabriziopera :smile: 

Sounds like a problem on your side. This works fine in the demo project.
