### ISSUE TITLE
Problem in getting Navigation Bar, I have tried getting Navigation Bar in my project But I am not getting it Please let me know what the methods need to be added to get it.

### ISSUE THREAD

**Issue by abdulvy** [jessesquires/JSQMessagesViewController#1507]
#import <UIKit/UIKit.h>
#import <JSQMessagesViewController/JSQMessages.h>
#import <JSQMessagesViewController.h>
#import "JSQMessagesCollectionViewFlowLayout.h"
#import "JSQMessages.h"
#import "JSQPhotoMediaItem.h"
#import "JSQLocationMediaItem.h"
#import "JSQVideoMediaItem.h"
#import "JSQMessagesMediaViewBubbleImageMasker.h"
#import "JSQMessagesAvatarImage.h"
#import "JSQMessagesAvatarImageFactory.h"
#import "JSQMessagesBubbleImage.h"
#import "JSQMessagesBubbleImageFactory.h"
#import "UIImage+JSQMessages.h"
#import "Chat.h"

@interface ChatpageViewController : JSQMessagesViewController<JSQMessagesCollectionViewDataSource,JSQMessagesCollectionViewDelegateFlowLayout,JSQMessagesCollectionViewCellDelegate,JSQMessageData,JSQMessageMediaData,JSQMessageAvatarImageDataSource,JSQMessageBubbleImageDataSource>
{
    NSMutableArray * fularray;
}
@property(nonatomic,strong)NSDictionary * receivedict;

@property (strong, nonatomic) IBOutlet UILabel *name;
@property (strong, nonatomic) IBOutlet UILabel *mobile;

@property (strong, nonatomic) JSQMessagesBubbleImage *outgoingBubbleImageData;
@property (strong, nonatomic) JSQMessagesBubbleImage *incomingBubbleImageData;

@end

********************************************************************************
#import "ChatpageViewController.h"
@interface ChatpageViewController ()
@end
@implementation ChatpageViewController
@synthesize receivedict,name,mobile;

//-(void)viewWillAppear:(BOOL)animated
//{
//    
//   // self.collectionView.collectionViewLayout.springinessEnabled = YES;
//}

- (void)viewDidLoad
{
    [super viewDidLoad];
       
     fularray = [[NSMutableArray alloc] init];
       // Do any additional setup after loading the view.
   // [self.navigationController setNavigationBarHidden:NO animated:YES];
NSLog(@"%@",receivedict);
    name.text = [receivedict objectForKey:@"Name"];
    mobile.text =[receivedict objectForKey:@"Mobile"];
    
   
    
    JSQMessagesBubbleImageFactory *bubbleFactory = [[JSQMessagesBubbleImageFactory alloc] init];
    
    self.outgoingBubbleImageData = [bubbleFactory outgoingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleBlueColor]];
    self.incomingBubbleImageData = [bubbleFactory incomingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleLightGrayColor]];  
}

- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    JSQMessage *message = [fularray objectAtIndex:indexPath.item];
    
    if ([message.senderId isEqualToString:self.senderId]) {
        return self.outgoingBubbleImageData;
    }
    
    return self.incomingBubbleImageData;
}

- (id<JSQMessageAvatarImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageDataForItemAtIndexPath:(NSIndexPath *)indexPath {
    return [JSQMessagesAvatarImageFactory avatarImageWithUserInitials:@"JL" backgroundColor:[UIColor blueColor] textColor:[UIColor whiteColor] font:[UIFont systemFontOfSize:12.0] diameter:30.0];
}

- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section {
    return [fularray count];
}

- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView {
    return 1;
}

- (id<JSQMessageData>)collectionView:(JSQMessagesCollectionView *)collectionView messageDataForItemAtIndexPath:(NSIndexPath *)indexPath {
    return fularray[indexPath.row];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (NSString *)senderId
{
    return [receivedict objectForKey:@"Mobile"];
}

- (NSString *)senderDisplayName
{
    
    return [receivedict objectForKey:@"Name"];
}

- (NSDate *)date
{
    return 18/03/2016;
}

- (void)didPressSendButton:(UIButton *)button withMessageText:(NSString *)text senderId:(NSString *)senderId senderDisplayName:(NSString *)senderDisplayName date:(NSDate *)date
{
    
    [JSQSystemSoundPlayer jsq_playMessageSentSound];
    
    JSQMessage *message = [[JSQMessage alloc] initWithSenderId:senderId
                                             senderDisplayName:senderDisplayName
                                                          date:date
                                                          text:text];
 
    
    
    [fularray addObject:message];
    [self.collectionView reloadData];
    [self finishSendingMessageAnimated:YES];
    NSLog(@"%@",message);
}

Myproject is saved in the link :https://www.dropbox.com/s/ozih8ko9836fmb2/chatapp.zip?dl=0

**Comment by abdulvy** [comment]
Since six days I have asked, No Answer, Please some one help me regarding this.

**Comment by jessesquires** [comment]
Thanks @abdulvy ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
