### ISSUE TITLE
xcode 7.3 keyboard above textfield

### ISSUE THREAD

**Issue by ADevelopStudio** [jessesquires/JSQMessagesViewController#1508]
xcode 7.3
Swift 2.2
Textfield stopped being "attached" to keyboard.
If start entering text - keyboard becomes above textfield, which continue lie on the bottom of view.
yesterday on Xcode 7.2 everything worked fine

**Comment by jessesquires** [comment]
Thanks @ADevelopStudio ! :smile:

**Comment by ADevelopStudio** [comment]
@jessesquires could you please let me know if it is possible to be fixed soon or not? 
basically, I am using your module for one of the projects where due date in 3 days :( and I was shocked when I saw that it stopped working... So, I just wanted to know If it's not so easy to fix - I will need to find something similar. Thanks!

**Comment by francocorreasosa** [comment]
Same problem here. I need to get this fixed 😢

**Comment by jessesquires** [comment]
Hey @ADevelopStudio -- can you post a screenshot?

**Comment by jessesquires** [comment]
Also, does this happen in the demo project?

**Comment by francocorreasosa** [comment]
Is there any advance with this? I have stuck my project because of this.

**Comment by francocorreasosa** [comment]
This is exactly what is happening:
![sc](https://openmerchantaccount.com/img2/fjhocuifhdisugfhfdlighfudg.gif)

**Comment by jessesquires** [comment]
are you calling `super` on all view lifecycle methods?

**Comment by francocorreasosa** [comment]
I was missing a `super`:
```
override func viewDidAppear(animated: Bool) {
    // missing super here
    self.collectionView?.collectionViewLayout.springinessEnabled = true
}
```
now is:
```
override func viewDidAppear(animated: Bool) {
    super.viewDidAppear(animated)
    self.collectionView?.collectionViewLayout.springinessEnabled = true
}
```

Thanks
