### ISSUE TITLE
Part of the text in the chat bubbles is hidden (iPhone 6s plus only)

### ISSUE THREAD

**Issue by zjszyms** [jessesquires/JSQMessagesViewController#1510]
Part of the text in the chat bubbles is hidden  (iPhone 6s plus only)

![1222](https://cloud.githubusercontent.com/assets/5733794/13978966/02b24eb4-f110-11e5-9623-7ef77598c3c7.png)

**Comment by zjszyms** [comment]
![1222](https://cloud.githubusercontent.com/assets/5733794/13978949/e2067e56-f10f-11e5-856c-ff4c1dee2742.png)

**Comment by jessesquires** [comment]
Thanks @zjszyms ! :smile: 

Please provide the additional information from the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md).

**Comment by zjszyms** [comment]
@jessesquires 

Library version(s):Develop branch
iOS version(s):iOS 9.2.1
Devices/Simulators affected:iPhone 6s plus only (Simulators is OK)
Reproducible in the demo project? (Y/N):Y

**Comment by cx478815108** [comment]
yeah,obviously i met  that bug also.iPhone6 9.3

**Comment by zjszyms** [comment]
Temporary solution is set :
`self.collectionView.collectionViewLayout.messageBubbleFont = [UIFont systemFontOfSize:17];`

**Comment by jessesquires** [comment]
Ah, if you are using a custom font, see: https://github.com/jessesquires/JSQMessagesViewController/issues/347#issuecomment-130533179
