### ISSUE TITLE
Bug : All scrollviews becomes crazy after push JSQMessagesViewController... 

### ISSUE THREAD

**Issue by AlphazellaLevallois** [jessesquires/JSQMessagesViewController#1512]
Having JSQMessagesViewController display after all my UIScrollView not have the right dimensions .. I do not understand why..?

**Comment by jasonlagaac** [comment]
Do you have any sample code/project that can illustrate the problem?

**Comment by srinivasanVaradan** [comment]
`



import Foundation
import JSQMessagesViewController
import DKImagePickerController

enum FBProfilePictureType:String
{
    case FB_LARGE_IMG = "normal",
         FB_SMALL_IMG  = "small",
         FB_LARGE_200_IMG = "large",
         FB_SQUARE_IMG  = "square"
}

enum MessageTypeEnum: String {
    case Text = "T",
    Picture = "P",
    Location = "L"
}

class ChatViewController: JSQMessagesViewController,UIActionSheetDelegate,UIImagePickerControllerDelegate,UINavigationControllerDelegate
{
    var navigationBar : UINavigationBar?
    var currentThread:MessageThread?
    var selectImageAsset :[DKAsset]?
    var imagesArray:[UIImage] = []
    var messageManager = MessagesManager()
    var ownerImageURL:String?
    var friendImageURL:String?
    
    var ownerFBId:String?
    var friendFBId:String?
    var ownerImage,friendImage:UIImage?
    
    
    
    override func viewDidLoad() {
        
        super.viewDidLoad()
        navigationBarSetup()
        // configure JSQMessagesViewController
        let defaultAvatarSize: CGSize = CGSizeMake(kJSQMessagesCollectionViewAvatarSizeDefault, kJSQMessagesCollectionViewAvatarSizeDefault)
        self.collectionView!.collectionViewLayout.incomingAvatarViewSize = defaultAvatarSize //CGSizeZero
        self.collectionView!.collectionViewLayout.outgoingAvatarViewSize = defaultAvatarSize //CGSizeZero
        self.collectionView!.collectionViewLayout.springinessEnabled = false
        self.showLoadEarlierMessagesHeader = false
        
        
        self.senderId = GroovonShareManager.sharedInstance.getGroovonUserId()
        
        if self.senderId == currentThread?.messageFromId
        {
            ownerFBId = currentThread?.socialMediaId4From ?? "0"
            friendFBId = currentThread?.socialMediaId4To ?? "0"
            // Owner Initiate the Thread
            ownerImageURL = GroovonUtility.getFBUserProfileUrlFromUserId(currentThread?.socialMediaId4From ?? "0" ,imageType:FBProfilePictureType.FB_LARGE_200_IMG.rawValue )
            friendImageURL = GroovonUtility.getFBUserProfileUrlFromUserId(currentThread?.socialMediaId4To ?? "0" , imageType:FBProfilePictureType.FB_LARGE_200_IMG.rawValue )
        }
        else
        {
            ownerFBId = currentThread?.socialMediaId4To ?? "0"
            friendFBId = currentThread?.socialMediaId4From ?? "0"
            
            // Friend Initiate the Thread
            ownerImageURL = GroovonUtility.getFBUserProfileUrlFromUserId(currentThread?.socialMediaId4To ?? "0" ,imageType:FBProfilePictureType.FB_LARGE_200_IMG.rawValue )
            friendImageURL = GroovonUtility.getFBUserProfileUrlFromUserId(currentThread?.socialMediaId4From ?? "0" , imageType:FBProfilePictureType.FB_LARGE_200_IMG.rawValue )
        }
        getOwnerAndFriendImages()
        self.senderDisplayName = ""
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
    }
    
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)

    }
    
    // ------------------------------------------------------------------------
    // MARK: - Standard CollectionView handling
    // ------------------------------------------------------------------------
    
    override func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        print(currentThread?.lstMessages?.count)
        return (currentThread?.lstMessages?.count)!
    }
    
    
    //MARK: CELL FOR ROW
    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell: JSQMessagesCollectionViewCell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        
        let data = currentThread?.lstMessages?.safeIndex(indexPath.row)
        
        //getMessageForId(indexPath.row)
        if data!.message!.characters.count > 0 && data!.awsUrl == nil
        {
            if data?.ownerId == self.senderId {
                cell.textView!.textColor = UIColor.whiteColor()
                
                
                let imgURL = GroovonShareManager.sharedInstance.getFacebookProfileImageUrl(ownerFBId!, imageView: cell.avatarImageView!)
                loadCircularImageFromURL(NSURL(string: imgURL)!,imageView: cell.avatarImageView!)
                
            } else {
                cell.textView!.textColor = UIColor.blackColor()
                let imgURL = GroovonShareManager.sharedInstance.getFacebookProfileImageUrl(friendFBId!, imageView: cell.avatarImageView!)
                loadCircularImageFromURL(NSURL(string: imgURL)!,imageView: cell.avatarImageView!)
            }
            cell.textView!.linkTextAttributes = [NSForegroundColorAttributeName : cell.textView!.textColor!,NSUnderlineStyleAttributeName : NSUnderlineStyle.StyleSingle.rawValue]
        }
        else
        {
            if let image = data!.image
            {
                cell.messageBubbleImageView.image = image
            }
            else
            {
                let URL = NSURL(string:data!.awsUrl!)
                loadImageFromURL(URL!,imageView: cell.messageBubbleImageView!,message:data!)
            }
        }
        return cell
    }
    
    // ------------------------------------------------------------------------
    // MARK: - JSQMessagesCollectionView handling
    // ------------------------------------------------------------------------
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, messageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageData! {
        return getMessageForId(indexPath.row)
    }
    
    //messageBubbleImageDataForItemAtIndexPath
    override func collectionView(collectionView: JSQMessagesCollectionView!, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageBubbleImageDataSource!
    {
        let message = getMessageForId(indexPath.row)
        let bubbleFactory = JSQMessagesBubbleImageFactory()
        if message.senderId == self.senderId {
            return bubbleFactory.outgoingMessagesBubbleImageWithColor(GROOVON_CHAT_OWNER_COLOR)
        }
        return bubbleFactory.incomingMessagesBubbleImageWithColor(GROOVON_CHAT_SENDER_COLOR)
    }
    
    //CellTopLabel
    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString!
    {
        let message = getMessageForId(indexPath.row)
        return JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate(message.date)
    }
    
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat
    {
        return kJSQMessagesCollectionViewCellLabelHeightDefault
    }
    
    
    
    // MessageBubbleTopLabel
    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString!{
        let message = getMessageForId(indexPath.row)
        if message.senderId == self.senderId {
            return nil;
        }
        if indexPath.row > 1 {
            let previousMessage = getMessageForId(indexPath.row - 1)
            if previousMessage.senderId == message.senderId {
                return nil
            }
        }
        return NSAttributedString(string: message.senderDisplayName)
    }
    
    // MessageBubbleTopLabel height
    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
        let message = getMessageForId(indexPath.row)
        if message.senderId == self.senderId {
            return 0;
        }
        if indexPath.row > 1 {
            let previousMessage = getMessageForId(indexPath.row - 1)
            if previousMessage.senderId == message.senderId {
                return 0
            }
        }
        return kJSQMessagesCollectionViewCellLabelHeightDefault
    }
    
    // avatarImageData
    //MARK: SET USER Profile Picture
    override func collectionView(collectionView: JSQMessagesCollectionView!, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageAvatarImageDataSource! {
        let message = getMessageForId(indexPath.row)

        var avatar = JSQMessagesAvatarImageFactory.avatarImageWithPlaceholder(UIImage(named: "PersonPlaceHolderImage"), diameter: 20)
        if message.senderId == self.senderId {
            //return current User Photo
            if let ownerImg = ownerImage
            {
                avatar = JSQMessagesAvatarImageFactory.avatarImageWithImage(ownerImg, diameter: 20)
            }
        }
        else
        {
            if let frndImg = friendImage
            {
                avatar = JSQMessagesAvatarImageFactory.avatarImageWithImage(frndImg, diameter: 20)
            }
        }
        return avatar
        
    }
    
    // CellBottomLabel
    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        return nil
    }
    
    // CellBottomLabel height
    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
        return 0
    }
    
    // ------------------------------------------------------------------------
    // MARK: - JSQMessagesCollectionView events
    // ------------------------------------------------------------------------
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, header headerView: JSQMessagesLoadEarlierHeaderView!, didTapLoadEarlierMessagesButton sender: UIButton!) {
      LogManager.sharedInstance.DLog("Should load earlier messages.")
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, didTapAvatarImageView avatarImageView: UIImageView!, atIndexPath indexPath: NSIndexPath!) {
        LogManager.sharedInstance.DLog("Tapped avatar!")
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, didTapMessageBubbleAtIndexPath indexPath: NSIndexPath!) {
        LogManager.sharedInstance.DLog("Tapped message bubble!")
        }
    
    
    
    
    //MARK: GET DATA FROM MESSAGE
    func getDataForId(id: Int) -> (Message, Int)
    {
        var data: Message!
        data = currentThread?.lstMessages?.safeIndex(id)
        return (data, (currentThread?.lstMessages?.count)!)
    }

    
    
    func getMessageForId(id: Int) -> JSQMessage {
        // Get the CloudKit Message data plus count
        let (data, count) = getDataForId(id)
        
        // Should never happen... just here to prevent a crash if it does happen.
        if count <= id {
            NSLog("Should never happen... just here to prevent a crash if it does happen");
            return JSQMessage(senderId: self.senderId, displayName: self.senderDisplayName, text: "")
        }
        
        // Create a JSQMessage based on the Message object from CloudKit
        var message: JSQMessage!
        
        // receiving or sending..
        let sender = data.ownerId
        let senderName = self.senderDisplayName
        
        var  createdAt = NSDate()
        if let date = data.createdDate
        {
            createdAt = GroovonUtility.getDateFromMilliseconds(date)
        }
        if data.message!.characters.count > 0 && data.awsUrl == nil
        {
            message = JSQMessage(senderId: sender, senderDisplayName: senderName,date: createdAt, text: data.message)
        }
        else
        {
            if let image = data.image
            {
                message = JSQMessage(senderId: sender, senderDisplayName: senderName, date: createdAt, media:JSQPhotoMediaItem(image: image))
            }
            else
            {
                message = JSQMessage(senderId: sender, senderDisplayName: senderName, date: createdAt, media:JSQPhotoMediaItem(image: nil))
            }
        }
        return message
    }
    
    func navigationBarSetup()
    {
        navigationBar = UINavigationBar(frame: CGRectMake(0, 0, self.view.frame.size.width, 60))
        navigationBar!.barTintColor = PROFILE_BORDER_COLOR
        navigationBar!.translucent = false
        let navigationItem = UINavigationItem()
        let logo = UIImage(named: "GroovonLogo")
        let imageView = UIImageView(image:logo)
        let back = UIImage(named: "BackButton")
        navigationItem.titleView = imageView
        let leftButton =  UIBarButtonItem(title: nil, style:   UIBarButtonItemStyle.Plain, target: self, action: "backButtonAction:")
        leftButton.image = back
        navigationItem.leftBarButtonItem = leftButton
        navigationItem.leftBarButtonItem?.tintColor = UIColor.grayColor()
        navigationBar!.items = [navigationItem]
        self.view.addSubview(navigationBar!)
        setConstraintsForNavigationBar()
    }

    func setConstraintsForNavigationBar()
    {
        let superView = self.view
        navigationBar?.snp_makeConstraints(closure: { (make) -> Void in
            make.width.equalTo(superView.snp_width)
            make.left.equalTo(superView.snp_left)
            make.height.equalTo(60)
            make.top.equalTo(0)
        })
    }
    
    func backButtonAction(button:UIButton)
    {
        self.navigationController?.popViewControllerAnimated(true)
    }
    
    // ------------------------------------------------------------------------
    // MARK: - User interaction
    // ------------------------------------------------------------------------
    
    override func didPressSendButton(button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: NSDate!) {
        JSQSystemSoundPlayer.jsq_playMessageSentSound()
        setMessage(text,orImage: nil)
        self.finishSendingMessageAnimated(true)
    }
    
    
    override func didPressAccessoryButton(sender: UIButton!) {
        selecImageFromDevice ()
    }
    
    func loadImageFromURL(URL:NSURL,imageView:UIImageView,message:Message) -> Void
    {
        imageView.setImageWithURL(URL, completed: { (rImage, error, cachetype, nsurl) -> Void in
            if rImage == nil {
                //self.setPlaceHolderImage(forImageView: imageView)
            }
            else
            {
                message.image = rImage
                imageView.image = rImage
                self.reloadCollectionView()
            }
            }, usingActivityIndicatorStyle: .Gray)
    }
    
    func loadCircularImageFromURL(URL:NSURL,imageView:UIImageView) -> Void
    {
        imageView.setImageWithURL(URL, completed: { (rImage, error, cachetype, nsurl) -> Void in
            if rImage == nil
            {
                imageView.image = JSQMessagesAvatarImageFactory.circularAvatarImage(UIImage(named: "FBFeedLogo"), withDiameter: 20)
            }
            else
            {
                imageView.image = rImage
                 GroovonUtility.setRoundedProfilePictureView(view: imageView)
            }
        }, usingActivityIndicatorStyle: .Gray)
    }

    
    
    
    func reloadCollectionView()
    {
        self.collectionView?.reloadData()
    }
    
    

    func selecImageFromDevice()
    {
        showImagePickerWithAssetType(.AllPhotos, allowMultipleType: false, sourceType: .Photo)
    }
    
    
    func showImagePickerWithAssetType(assetType: DKImagePickerControllerAssetType,
        allowMultipleType: Bool = false,
        sourceType: DKImagePickerControllerSourceType = .Photo) {
            
            let pickerController = DKImagePickerController()
            pickerController.assetType = assetType
            pickerController.showsCancelButton = true
            //pickerController.allowMultipleTypes = allowMultipleType
            pickerController.sourceType = [.Photo,.Camera]
            pickerController.singleSelect = false
            pickerController.maxSelectableCount = 1
            
            pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
                // print("didSelectAssets")
                self.selectImageAsset = assets
                
                for imageAsset in assets
                {
                    imageAsset.fetchImageWithSize(CGSize(width: 640, height: 640), completeBlock: { image, info in
                        self.imagesArray.append(image!)
                        self.setMessage(nil,orImage: self.imagesArray.first)
                    })
                }
            }
            self.presentViewController(pickerController, animated: true, completion: nil)
    }
    
    
    func setMessage(text:String?,orImage image:UIImage?)
    {
        var postDict: Dictionary<String,String> = Dictionary()
        postDict["ownerId"] = GroovonShareManager.sharedInstance.getGroovonUserId() ?? ""
        postDict["threadId"] = currentThread?.threadId ?? "0"
        let seconds:NSTimeInterval = NSDate.timeIntervalSinceReferenceDate()
        let milliseconds = seconds*1000;
        postDict["createdDate"] = milliseconds.description
        if let _text = text
        {
            postDict["message"] =  _text
            postDict["activitySubType"] = ""
            postMessageAPI(postDict,imageData: NSData())
        }
        else
        {
            postDict["message"] =  ""
            postDict["activitySubType"] = "Image"
            if let imageGot = image
            {
                let imageData = UIImagePNGRepresentation(imageGot)
                postMessageAPI(postDict,imageData: imageData)
            }
        }
    }
    
    
    
    
    //MARK: POST MESSAGE API
    
    func postMessageAPI(msgDictionary:Dictionary<String,String> , imageData:NSData?)
    {
        if NetworkReachability.isConnectedToNetwork()
        {
            GroovonUtility.showLoadingIndicator()
             messageManager.postMessage(msgDictionary, imageData: imageData!, completion: { (responseObj) -> () in
                self.parseResponse(responseObj)
            })
            { (error) -> () in
                LogManager.sharedInstance.DLog("Failed to Post Message")
            }
        }
        else
        {
             LogManager.sharedInstance.DLog("No Network Message")
        }
    }
    
    
    func parseResponse(response:ResponseModel)
    {
         GroovonUtility.hideLoadingIndicator()
         LogManager.sharedInstance.DLog(response.status)
         getMessagesList()
    }
    
    
    
    func getOwnerAndFriendImages()
    {
        ImageDownloadManager.sharedManager().AsynchronousImageDownloaderWithImageUrl(ownerImageURL, withCallBackBlock: { (receivedSize, expSize) -> Void in
            //
            }, completed: { (image, error) -> Void in
                self.ownerImage = image
        })
        
        ImageDownloadManager.sharedManager().AsynchronousImageDownloaderWithImageUrl(friendImageURL, withCallBackBlock: { (receivedSize, expSize) -> Void in
            //
            }, completed: { (image, error) -> Void in
                self.friendImage = image
        })
    }
    
    
    
    
    //MARK:Get Message List
    
    //MARK: API
    func getMessagesList() -> Void
    {
        let pageNum = "0"
        messageManager.getMessagesList(GroovonShareManager.sharedInstance.getGroovonUserId(), pageNo: pageNum, completion: { (responseObj:MessageInfo) -> () in
            self.parseListResponse(responseObj)
            },failure:{ (error:ErrorResponse) -> () in
                LogManager.sharedInstance.DLog("Failed to Get Message")
        })
    }
    func parseListResponse(response:MessageInfo) -> Void
    {
        let thread = response.lstMessageThreads?.filter({$0.threadId == currentThread?.threadId})
        currentThread = thread?.first
        self.collectionView?.reloadData()
    }
}

`

**Comment by jessesquires** [comment]
Thanks @AlphazellaLevallois ! Please update the issue with more info.
