### ISSUE TITLE
How to hide bubbles without hiding top label?

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1513]
I would like to hide a bubble and only use it's top label for custom text. How to do this?

Unfortunately this messes up the view:

    override func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        return CGSizeMake(0,0)
    }

**Comment by eliburke** [comment]
@MHX792 It sounds like you might want something like a "system message", right? 
This isn't currently supported out of the box, but here are some issues that cover ways to accomplish it: #598, #321, #215, #89. 
If you want to turn off avatars, or change the bubble masking, you will need to detect your custom label messages in messageBubbleImageDataForItemAtIndexPath and avatarImageDataForItemAtIndexPath i

**Comment by eliburke** [comment]
@MHX792 I'm guessing you opened #1521 to continue this issue?

**Comment by jessesquires** [comment]
Thanks @eliburke ! :smile:
