### ISSUE TITLE
JSQMessagesKeyboardControllerUserInfoKeyKeyboardDidChangeFrame returns nil in the userInfo dictionary

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1514]
I am trying to change a constraint when the keyboard is shown/hidden, but unfortunateley it crashes:

    override func viewDidLoad() {
        super.viewDidLoad()
 
        NSNotificationCenter.defaultCenter().addObserver(self, selector: Selector("keyboardWasShown:"), name:JSQMessagesKeyboardControllerNotificationKeyboardDidChangeFrame, object: nil)
    }
    
    func keyboardWasShown(notification: NSNotification) {
        let info = notification.userInfo!
        let keyboardFrame: CGRect = (info[JSQMessagesKeyboardControllerNotificationKeyboardDidChangeFrame] as! NSValue).CGRectValue() 
    // crashes because of 'fatal error: unexpectedly found nil while unwrapping an Optional value'
        
        UIView.animateWithDuration(0.1, animations: { () -> Void in
            self.bottomConstraint.constant = -(keyboardFrame.size.height + 41)
        })
    }

**Comment by MHX792** [comment]
Anybody a clue?

**Comment by jessesquires** [comment]
hey @MHX792 :smile: 

it looks like the key you are accessing in the dictionary is `JSQMessagesKeyboardControllerNotificationKeyboardDidChangeFrame`.

it should be `JSQMessagesKeyboardControllerUserInfoKeyKeyboardDidChangeFrame` instead
