### ISSUE TITLE
media MessageBubble

### ISSUE THREAD

**Issue by wanyue1215** [jessesquires/JSQMessagesViewController#1515]
when i received a media message , the messageBubble has wrong direction
<img width="249" alt="2016-03-26 11 24 03" src="https://cloud.githubusercontent.com/assets/15208431/14057784/55c1d412-f345-11e5-8ac0-c0c08602b102.png">

**Comment by rafus15** [comment]
Hi, how did you fixed this, i'm experiencing the same issue!
Thanks
