### ISSUE TITLE
Subclassing JSQMessageMediaData in Swift

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1517]
I am trying to create a custom message media data in Swift, but it keeps telling me:

`type 'CustomMedia' does not conform to protocol 'NSObjectProtocol'`

My code:

    class CustomMedia: JSQMessageMediaData {

    @objc func mediaView() -> UIView! {
        let mediaView = UIView()
        let label = UILabel(frame: CGRectMake(0, 0, 200, 21))
        label.center = CGPointMake(160, 284)
        label.textAlignment = NSTextAlignment.Center
        label.text = "I'am a test label"
        mediaView.addSubview(label)
        return mediaView
    }
    
    @objc func mediaViewDisplaySize() -> CGSize {
        let size = CGSizeMake(200, 21)
        return size
    }
    

    @objc func mediaPlaceholderView() -> UIView! {
        return nil
    }

    @objc func mediaHash() -> UInt {
        return UInt(0)
    }
    }

**Comment by MHX792** [comment]
Ok, seems like it has to inhert from `NSObject`. Solved.

**Comment by jessesquires** [comment]
Thanks @MHX792 ! :smile:
