### ISSUE TITLE
[NSNull _fastCStringContents:]

### ISSUE THREAD

**Issue by Lilac911** [jessesquires/JSQMessagesViewController#1518]
I am receiving the following error every time I try to type any letters or numbers into a text field.
[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x10d28faf0
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x10d28faf0'

What cause this problem ??

**Comment by jessesquires** [comment]
Thanks @Lilac911 ! :smile: 

This doesn't sound related to the library. Maybe there's an issue with your project? Can you provide any more information?
