### ISSUE TITLE
Add support for an accessory view to JSQMessagesCollectionViewCell

### ISSUE THREAD

**Issue by eliburke** [jessesquires/JSQMessagesViewController#1519]
<img width="326" alt="screen shot 2016-03-29 at 4 05 49 pm" src="https://cloud.githubusercontent.com/assets/2371768/14122318/459654d8-f5c9-11e5-8065-6e9fdf1c62ca.png">

@jessesquires I was playing around with adding a button next to some of my media views (similar to the "Forward" icon Facebook Messenger puts next to images), and I wondered if it was worth adding in the base implementation. I think the most flexible option would be a UIView with constraints to center it vertically and offset it left or right based on the left/right state of the cell, basically the opposite of the avatar container. That would allow folks to embed a status icon, button, or custom view. 

If anyone else cares, here is the code I used to create the above screenshot, just put it in cellForItemAtIndexPath and add a button action that uses the tag to determine which cell's button was tapped. Note that this hack will re-create the button each time it is rendered, so you'll need to do some additional work. 😜

```
    //if (msg.isMediaMessage) {
    UIButton * button = [UIButton buttonWithType:UIButtonTypeContactAdd];
    [button setTranslatesAutoresizingMaskIntoConstraints:NO];
    button.tag = indexPath.item;
    [cell.contentView addSubview:button];
    
    // Center Vertically
    NSLayoutConstraint *centerYConstraint = [NSLayoutConstraint constraintWithItem:button
                                                                         attribute:NSLayoutAttributeCenterY
                                                                         relatedBy:NSLayoutRelationEqual
                                                                            toItem:cell.messageBubbleContainerView
                                                                         attribute:NSLayoutAttributeCenterY
                                                                        multiplier:1.0
                                                                          constant:0.0];
    [cell.contentView addConstraint:centerYConstraint];
    
    NSLayoutConstraint *xConstraint;
    if ([self.senderId isEqualToString:msg.senderId]) {
        xConstraint = [NSLayoutConstraint constraintWithItem:button
                                                   attribute:NSLayoutAttributeRight
                                                   relatedBy:NSLayoutRelationEqual
                                                      toItem:cell.messageBubbleContainerView
                                                   attribute:NSLayoutAttributeLeft
                                                  multiplier:1.0
                                                    constant:-10];
    } else {
        xConstraint = [NSLayoutConstraint constraintWithItem:button
                                                   attribute:NSLayoutAttributeLeft
                                                   relatedBy:NSLayoutRelationEqual
                                                      toItem:cell.messageBubbleContainerView
                                                   attribute:NSLayoutAttributeRight
                                                  multiplier:1.0
                                                    constant:10];

    }
    [cell.contentView addConstraint:xConstraint];
    //}
```

**Comment by jessesquires** [comment]
Sounds good to me! :+1: 

I've put this in `8.0.0`.

**Comment by DBL-Lee** [comment]
@eliburke If I want to change this accessory based on message type, how could I get a reference from `cellForRowAtIndexPath` of the current accessory view so I could remove the previous one and add a new one?

**Comment by eliburke** [comment]
I guess I should have more explicitly said "this is a hack" -- I was just prototyping the functionality.

The best solution is probably to add a UIView to the xib for the incoming and outgoing cells, and add an outlet in your JSQMessageData subclass. Then in cellForRowAtIndexPath add a button to the new view. If you store the current button type in your JSQMessageData, you can use that to determine when it should be updated to a different style.  

You can of course skip the step of adding it to the xib, and just add a reference to the button in your JSQMessageData and remove / update it as needed.

 Or enumerate subviews looking for the accessory.

Lots of ways to skin this cat. 😜

**Comment by adubr** [comment]
@jessesquires, @eliburke do you need help with this? If you do I could try and make a PR with the best solution described above.

**Comment by eliburke** [comment]
@adubr PRs are always welcome of course, but I think we should discuss the feature a little more first. I think the cell XIBs are going away, so whatever is added will need to be placed in the cell programmatically, with appropriate constraints. 

Then we should figure out what goes there.
Is it only an accessory button as narrowly defined by Apple? 
Do we allow for a custom UIView? 
How much configuration is provided (left/right offset from the bubble, top, middle, bottom alignment)
Do we provide an additional protocol and is it mandatory (didTapCellAccessoryButton)
I imagine that @jessesquires will want to have an accessory factory that returns an accessory view given a data object.

**Comment by adubr** [comment]
> we should discuss the feature a little more first

Exactly, that's why I asked you first : )
I'm just diving into the project so please bear with my questions, there'll be a lot.
I think we should start with something very simple but extensible in the future.

1. If XIBs are going away, then the place for adding an accessory button should be a method in `JSQMessagesCollectionViewCell` which is called from `awakeFromNib` for the time being.
2. As far as I understand Apple has built their list of accessory kinds based on the most frequent actions a user would do. For our case the most common action is something like sharing or forwarding. I suppose there won't be a need for many other kinds. Anyway, there's a context menu. So I think for the first iteration just one type of the accessory should be enough. And no custom view for now.
3. I would prefer no configuration for this stage. `JSQMessagesCollectionViewCell` subview hierarchy is not configurable, is it?
4. Let's add an optional method `messagesCollectionViewCellDidTapAccessoryButton:` to `JSQMessagesCollectionViewCellDelegate`. Is it ok?
5. Do you mean something like `[JSQMessagesAccessoryViewFactory accessoryViewWithType:JSQMessagesAccessoryViewFactoryShareButton]`?

**Comment by jessesquires** [comment]
Hey @eliburke / @adubr 😄 

Let's keep this simple, but extensible:

1. If working on this now, let's work with the existing xibs. We can refactor later.
1. The accessory view should be a generic button. Clients should be able to provide an accessory image. We'll use the same image for all cells. (i.e., you cannot customize *per* cell)
1. Configuration: clients should be able to hide/show, but nothing more
1. **No** optional delegate methods. We can add a new protocol/delegate instead, specifically for the accessory view tapping
1. Not sure if we need a view factory, just a way for clients to provide the image that they want to use for the button

**Comment by adubr** [comment]
Hey @jessesquires 
thanks for reply : )

1. Sounds good to me.
2. 5. Should it be a method in `JSQMessagesCollectionViewDataSource`? Or you prefer a dedicated protocol? Should we make default image like this (`UIBarButtonSystemItemAction`)?  
![image](https://cloud.githubusercontent.com/assets/820352/16661647/97f1eeb6-447c-11e6-8e52-ab55b7c6a3fb.png)
3. Is it ok to define a new method in `JSQMessageData` for this purpose?
4. Ok

Do you have any specific coding style or other guidelines I should know before implementing this?

**Comment by adubr** [comment]
Oh, I see some info in the .github folder

**Comment by jessesquires** [comment]
Hey @adubr 

(2) dedicated protocol would be best. `UIBarButtonSystemItemAction` 👍 
(3) `JSQMessageData` is probably not the right place for this. This is really a UI configuration, so it should be separate from the model layer

**Comment by adubr** [comment]
@jessesquires,

usually when I develop something I try to follow [the boyscout rule](http://www.informit.com/articles/article.aspx?p=1235624&seqNum=6). This includes fixing spelling errors, renaming something (e.g. since `jsq_bubbleImageFromBundleWithName` doesn't really have anything to do with bubbles, `jsq_imageFromBundleWithName` looks like more concise name), extracting some methods (in order to make the code more readable and fulfil the SRP), etc.

May I do it here, or it's better to make only those changes which are actually required by the task?

**Comment by adubr** [comment]
I'm quite confused with `JSQMessagesCollectionViewDelegateFlowLayout` protocol. 

- It clearly does two things: (1) manages additional layout information and (2) responds to additional actions on items. There's a bunch of methods for both tasks. It's an apparent major violation of the SRP. Is there a reason for this? We can extract all user interaction related methods into a separate protocol (and add the accessory button callback there).
- All the methods there are `@optional`. This conflicts with what @jessesquires said above.

@eliburke / @jessesquires please help me out.

**Comment by jessesquires** [comment]
> May I do it here, or it's better to make only those changes which are actually required by the task?

Generally, I agree with the boyscout rule, but let's keep the PR focused on only necessary changes. We can definitely do a followup to refactor/rename

**Comment by jessesquires** [comment]
> I'm quite confused with JSQMessagesCollectionViewDelegateFlowLayout protocol.

Ha, yes. 😄 There are a lot of legacy (read: poor) design decisions here. A major goal of `v8.0` is to fix all of this (see #453). A lot of tasks are in-flight, so sorry for the confusion.

**Comment by jessesquires** [comment]
We probably want a new `accessoryDelegate` on the view controller. So we can avoid the flow layout issues for now.

**Comment by adubr** [comment]
Hey @jessesquires / @eliburke 

I've done the [PR](https://github.com/jessesquires/JSQMessagesViewController/pull/1719) for the task.
Waiting for your feedback :)
