### ISSUE TITLE
Combining photo media and text message

### ISSUE THREAD

**Issue by happiehappie** [jessesquires/JSQMessagesViewController#1530]
Guys, I'm seriously sorry if this is answered or it's really that I haven't browse enough, but is there really any way to combine photomediaitem with my JSQMessage? Like this?
![img_0052](https://cloud.githubusercontent.com/assets/6497131/14282096/6184d0c4-fb6f-11e5-8963-60dc99a9e2f9.jpg)

**Comment by svtechnology** [comment]
Extend the Photomediaitem and add those labels with constraints and that should work. You also need to add the padding and move the image rect. But yes, it's possible to get the same thing by subclassing. 

PS: interested in the bottle on your desk ;)

**Comment by svtechnology** [comment]
Also, sorry for the pseudo code only.

**Comment by happiehappie** [comment]
That's my boss' one. I tried for half a day and not much progress. How do I
manipulate the bubble to fit my label for example. Sorry. Cause I'm really
super lost.

**Comment by eliburke** [comment]
@svtechnology is right. You are going to have to create your own custom class. It really isn't hard to do. 
 
If you are struggling with making it to work, you need to be more specific with your questions. For example, if the bubble is the wrong size, you need to change mediaViewDisplaySize to fit it. 

Here's a starting point:  subclass JSQPhotoMediaItem. Add a property for your text. Override mediaViewDisplaySize (which determines the size of your cell) to return CGSize(210, 150). Override mediaView (which returns the contents of your cell) and have it return the following:
```
{
    CGRect viewFrame;
    viewFrame.size = [self.mediaViewDisplaySize];
    UIView * view = [UIView alloc] initWithFrame:viewFrame];
    view.backgroundColor = [UIColor orangeColor]; // so you can see it
    UIImageView * imageView = [UIImageView alloc] initWithImage:self.image];
    imageView.frame = CGRectMake(0,0,96,96);
    [view addSubview:imageView];
    UILabel * label = [UILabel alloc] initWithFrame:CGRectMake(110, 70, 100, 30)];
    label.text = self.text;
    [view addSubview:label];
    return view;
}
```
IIRC you are writing in swift but this is straightforward stuff. If you can make that work, try changing the size returned from mediaViewDisplaySize to see how your bubble is modified. Now continue and customize the layout however you want.

**Comment by jessesquires** [comment]
Also, if you need to adjust bubble sizes, you can provide a custom `bubbleSizeCalculator`

http://cocoadocs.org/docsets/JSQMessagesViewController/7.2.0/Classes/JSQMessagesCollectionViewFlowLayout.html#//api/name/bubbleSizeCalculator

**Comment by jessesquires** [comment]
Thanks all for the answers! :smile:

**Comment by marcuschoong** [comment]
@eliburke may i know how to override mediaViewDisplaySize by using the code you provided?

**Comment by eliburke** [comment]
@marcuschoong I'm not sure what you are doing wrong. Have you set a breakpoint and verified it isn't calling your override?

**Comment by marcuschoong** [comment]
@eliburke my problem was the media size was hardcoded the size at JSQMessagesBubblesSizeCalculator (messageBubbleSizeForMessageData), so i change the following code and the size can be adjust at custom class.

if ([messageData isMediaMessage]) {
        finalSize = [[messageData media] mediaViewDisplaySize];
//        finalSize = CGSizeMake(210.0f, 150.0f);
}

Now i was able to change the sizing but the uiview is not in bubble shape. May i know how to add the bubble into the uiview?

**Comment by eliburke** [comment]
You have a couple options. Take a look at #1168 and #1180

**Comment by marcuschoong** [comment]
@eliburke thanks for the reference. it's very useful to change the bubble if you need to use your custom image. 

however, the easier way is to use the default library if we do not need to change the bubble pattern.

For reference. i added the following in mediaView will show the default bubble shape.

> //show bubble shape
> playView.backgroundColor = [UIColor orangeColor];
> [JSQMessagesMediaViewBubbleImageMasker applyBubbleImageMaskToMediaView:playView isOutgoing:self.appliesMediaViewMaskAsOutgoing];
> self.cachedMediaView = playView;
