### ISSUE TITLE
Update demo project for AudioMediaItem

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1531]
Follow up from #1495 

We added a `-addAudioMediaMessage` method, :+1: 

Let's update the actionsheet to simulate sending an audio item.

Follow existing pattern for sending photo/location/video.

1. Tap :paperclip: icon
2. Tap "Send audio"

**Comment by jessesquires** [comment]
@eliburke — Be sure to pull the latest. I pushed a couple minor commits to cleanup some of the audio stuff.

Mostly just formatting, docs, and nullability.

See d2e4a06115666beb89f9730b11d93e42c0f00177 and 6873264627c740022b8308e72898f65d2ecb7e70

:smile: A few small notes:

- Always prefer `self.property` except inside `init` and `dealloc`
- I made `JSQAudioMediaViewAttributes` immutable and added a designated `init`. We should always aim for this. Unfortunately, the MediaItem subclasses have to be mutable.
- `NS_ASSUME_NONNULL_*` macros make nullability way simpler. These aren't used elsewhere in library yet, unfortunately, because their addition would be a breaking change for existing Swift code :cry:  We'll add them in 8.0 everywhere.

**Comment by eliburke** [comment]
@jessesquires Sorry I missed this task in the notification spam last week. 

Re your change to the init methods in [d2e4a6](https://github.com/jessesquires/JSQMessagesViewController/commit/d2e4a06115666beb89f9730b11d93e42c0f00177) I feel like that makes the default behavior more difficult to override. If someone simply wants to tweak the font or color, they have to pull in all that other stuff as well. And if we want to add more properties, it breaks the API. Why is it better?

**Comment by jessesquires** [comment]
No worries! :+1: 

>If someone simply wants to tweak the font or color, they have to pull in all that other stuff as well. 

Great point. Ok -- let's remove `readonly` from properties, and override the setters to `NSParameterAssert(value != nil)`.

>And if we want to add more properties, it breaks the API. Why is it better?

- Generally, I think preferring immutability is best. It greatly simplifies the programming and threading models. But, you make a good point that it negatively impacts usability here.
- API breakage: yes, this is always a concern. Generally, the plus side here (I think) is that this kind of pattern really forces you to think about new APIs before shipping, and forces you to really consider any breaking changes.

**Comment by jessesquires** [comment]
fixed in #1540

**Comment by eliburke** [comment]
After removing readonly, that cool new macro NS_ASSUME_NONNULL_BEGIN triggers nil warnings. If you feel strongly I'll add the asserts, but IMO it's unneeded bloat.

<img width="836" alt="screen shot 2016-04-12 at 9 44 12 pm" src="https://cloud.githubusercontent.com/assets/2371768/14480580/740a196e-00f8-11e6-9550-073f42c2b25a.png">

**Comment by jessesquires** [comment]
Can `audioCategory` be nil? 

If so, we can make it `@property (nonatomic, nullable) ...`

Otherwise, all non-nullable properties should assert
