### ISSUE TITLE
Scroll slow with some mediaPhotoItem

### ISSUE THREAD

**Issue by brokeniceinteractive** [jessesquires/JSQMessagesViewController#1532]
Hi, i have a problem with the scroll when in my chat there are some mediaPhotoItem, the scroll is slow and not fluid, i tried to async load the image but i have the same problem, any ideas?

**Comment by eliburke** [comment]
@brokeniceinteractive without a better explanation of the problem it's hard for anyone to diagnose. Does the problem occur with only images or are you mixing text and images? 
If you replace your async images with local copies loaded from your project is it still slow? 
Are you downloading your async images in the background using something like SDWebImage or AFNetworking?
Can you demonstrate the slowness using the Demo project?

**Comment by jessesquires** [comment]
Thanks @brokeniceinteractive ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:
