### ISSUE TITLE
how to create custom circular progress button on image ?

### ISSUE THREAD

**Issue by chinnuios** [jessesquires/JSQMessagesViewController#1533]
Hi, i need to create custom circular progress button on image (like whatsapp) ?? please tell me

**Comment by jessesquires** [comment]
Thanks @chinnuios ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
