### ISSUE TITLE
Different avatar sizes for each cell 💪😎👊

### ISSUE THREAD

**Issue by dhint4** [jessesquires/JSQMessagesViewController#1534]
Is it possible anymore to have different avatar sizes for each cell? Basically, anytime a message fails to send, I am wanting to place an exclamation mark on the right side of the cell like iMessage does in this photo:

![common-ios-9-problems-and-solutions10](https://cloud.githubusercontent.com/assets/9689335/14397979/42c46abc-fda6-11e5-88b1-9fa73b18e7be.jpg)

However, I do not want previous cells to align to the right side of the of the failed cell. I want previous cells to align with the right side of the failed avatar image.

Referenced from @mrojas in #491
![38b99f24-436c-11e4-8d23-b276c26ec085](https://cloud.githubusercontent.com/assets/9689335/14398059/da2ca914-fda6-11e5-9bb2-94b896407d40.png)

Does a method where we return an avatar's size for a particular item at an indexPath exist and I'm just not seeing it?

I have read #491 up and down multiple times and I can not seem to figure out how to make this work.

Any help would be appreciated!

**Comment by jessesquires** [comment]
Thanks @dhint4 ! :smile:

You didn't miss anything — unfortunately, this kind of behavior isn't supported right now.

We might get this in the 8.0 release though

**Comment by Daltron** [comment]
@jessesquires Thanks for the quick response. It's tremendously appreciated! 😄
