### ISSUE TITLE
How to change vertical spacing between cells?

### ISSUE THREAD

**Issue by DBL-Lee** [jessesquires/JSQMessagesViewController#1535]
I think this should be a stupid question but I cannot find relevant method or property in layout classes. What is the best way to change the vertical spacing between two cells?

**Comment by DBL-Lee** [comment]
I was thinking too much about constraints. It is just minimumlinespacing of the layout.

**Comment by jessesquires** [comment]
Thanks @DBL-Lee ! :smile:
