### ISSUE TITLE
Allow the user to provide a custom UIView for a message

### ISSUE THREAD

**Issue by ryangrimm** [jessesquires/JSQMessagesViewController#1536]
My current project has a need for custom views inside message bubbles. The most pressing need at the moment is to include a web view. I got the the pull request "Added HTML Media Message Type" (#917) working with the latest from develop and also fixed up a few of it's shortcomings. However, I ran up against a few underlying assumptions with media items.

One primary goal is to have the custom view be inside of the same colored bubbles as text based messages. However, the setMediaView method in JSQMessageCollectionViewCell removes the messageBubbleImageView from the view hierarchy (in fact it removes all of the views except for the latest mediaView).

Others seem to be very interested in customizing the content in the message bubbles as well. For example, issue #809 and #681 both want to display text and images inside the message bubble. Abstracting such requests seems challenging but allowing users to configure their own view layouts opens the door for them to service themselves.

My idea to solve this would be to create a new JSQCustomMediaItem that allows the user to provide their own custom UIView to render inside the message bubble.

**Comment by jessesquires** [comment]
Thanks @ryangrimm ! :smile: 

This is definitely a feature we're considering for v8.0. 

However, for now, you could simply include a message bubble view as part of your custom media view.

**Comment by ryangrimm** [comment]
I hadn't thought about using the message bubble view in a context like that. That probably would have gotten me far enough along for the time being. But, as you can see by the pull request I already spent the time to cook it up. At least it was fun in the process! Let me know if it looks like something that you'd like to fold into v8. Happy to make changes if you'd like me to.

**Comment by pprravinn** [comment]
i am using bar graphs programatically in my project so, is there any way to put a custom view into this library so i can put my graph code on it and show it on the the view  like addPhotoMediaMessage ??

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
