### ISSUE TITLE
Wrong size for custom mediaItem

### ISSUE THREAD

**Issue by brokeniceinteractive** [jessesquires/JSQMessagesViewController#1538]
Hi, i have 2 custom media items:

jsqStatusMediaItem - for message status, and it has this size:
`override func mediaViewDisplaySize() -> CGSize {
        return CGSize(width: UIScreen.mainScreen().bounds.width-10,height: 20)
}`

and jsqLoadingPhotoMediaItem - for photo with progress bar, this is the size:
`override func mediaViewDisplaySize() -> CGSize {
        // The white space around the messages
        return CGSizeMake(210, 150)
    }`

All works fine specially while i'm writing in the chat, every message that i append to the chat, has the correct size, but if i close and reopen the chat, sometimes the photoMediaItems get the size of status media items, only for certain message, not for all, as you can see in the picture:

![screen shot 2016-04-12 at 12 39 06](https://cloud.githubusercontent.com/assets/16253548/14457695/ae127fb2-00ac-11e6-898a-c32de4637ea0.png)

but for example i i back and reopen, sometimes has a correct size, sometimes no! 

Whats append? can you help me??????

**Comment by brokeniceinteractive** [comment]
#980 this is the solution!

**Comment by eliburke** [comment]
Thanks @brokeniceinteractive! 😄
