### ISSUE TITLE
How to fix incoming as well as the outgoing bubble on right side of JSQMessageViewController swift2

### ISSUE THREAD

**Issue by yadavanand** [jessesquires/JSQMessagesViewController#1539]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by yadavanand** [comment]
Also i am getting both the incoming as well as the outgoing bubble on right side of my view, can you please help me with that. 
![simulator screen shot 12-apr-2016 5 27 42 pm](https://cloud.githubusercontent.com/assets/8654980/14459237/58efd430-00d4-11e6-8284-6a9ef067e461.png)

**Comment by yadavanand** [comment]
One more thing if you could tell me how to access textFiled of JSQMessageViewController using swift2

**Comment by eliburke** [comment]
Hey @yadavanand  :smile:

Please see the following:
https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=%5Bmessage+bubble+wrong+side%5D+in%3Atitle+

As for the textView, it's exactly the same as Objective-C. From your JSQMessagesViewController subclass, just access inputToolbar.contentView.textView

**Comment by yadavanand** [comment]
@eliburke  :-)
Thank you for your reply with respect to above issues,i figured out the solution for it with help of reference given by you.

**Comment by yadavanand** [comment]
@eliburke One more thing i wanted to know if we can tell me how to detect a pull down in JSQMessageViewController.
