### ISSUE TITLE
Add Custom view instead of KeyBoard.

### ISSUE THREAD

**Issue by KushThakkar** [jessesquires/JSQMessagesViewController#1543]
How can display custom view instead of KeyBoard?

**Comment by svtechnology** [comment]
Hi KushThakkar,

This question of yours is more suited for SO (stackoverflow.com) than here since it is not related to the library.

Hint: Look into inputView and inputAccessoryView.

**Comment by jessesquires** [comment]
Thanks @KushThakkar and @svtechnology ! :smile:
