### ISSUE TITLE
Change UITextView Frame Dynamically.

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [jessesquires/JSQMessagesViewController#1544]
i don't want to use keyboard for messages i have a predefined textMessages that will be selected from table so how can i set UITextView frame above on that table?

**Comment by hemantkadam** [comment]
@ZetrixWeb-iOS Need more information on this. Probably some similar kind of app screenshot or your mock-up screens.

**Comment by jessesquires** [comment]
Thanks @ZetrixWeb-iOS ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:
