### ISSUE TITLE
Can we disable  scrollToBottomAnimated for particular instance in JSQMessageViewController

### ISSUE THREAD

**Issue by yadavanand** [jessesquires/JSQMessagesViewController#1545]
Can i prevent the view from scrolling down as per our requirement.
  self.scrollToBottomAnimated(true /false). false value also does not prevent view from scrolling down
This  #362 issue is not helping out
self.automaticallyScrollsToMostRecentMessage = NO
xcode7.3 quick help recommends to pass a boolean value which too is of not use .
Please help me i want prevent messages view to school to the bottom.

**Comment by eliburke** [comment]
@yadavanand can you clarify: are you asking how to prevent scrolling when the keyboard is shown? Or are you saying that self.scrollToBottomAnimated does not work for you?

Can you describe steps to reproduce your problem in the demo project? If I turn off self.automaticallyScrollsToMostRecentMessage it seems to behave correctly.

**Comment by yadavanand** [comment]
@eliburke The steps for my problem are as follows : 

1. I load messages in JSQMessageViewController  in batches of 15 messages (last 15 messages first and  then when i detect pull down i have to reload 15 more which are earlier than first 15  total of 30, then on 3rd pull down same thing is repeated and so on).
2. Entire process is working properly(Both pull down and reloading of messages).
3. The only problem is that how do i prevent/disable  my view from automatically scolling down.
4. self.automaticallyScrollsToMostRecentMessage method is not working in my case.

Could you please suggest something.

**Comment by eliburke** [comment]
@yadavanand if I understand you correctly, this doesn't sound like a problem with scrollToBottomAnimated-- it's the normal behavior of calling [self.collectionView reloadData]

How you solve it is going to depend on your data source, but will probably involve calling            `[self.collectionView scrollToItemAtIndexPath:messageIndex atScrollPosition:UICollectionViewScrollPositionCenteredVertically animated:YES];`

To determine your messageIndex you will need to figure out the index of the item that WAS at the top of the data array before you load new messages. Something like this this might work:
```
id obj = [self.yourDataArray firstObject];
// load your new data
// possibly invalidate the collection's layout
[self.collectionView reloadData];
NSIndexPath * messageIndex = [NSIndexPath indexPathWithIndex: [self.yourDataArray indexOfObject:obj]];
[self.collectionView scrollToItemAtIndexPath:messageIndex atScrollPosition:UICollectionViewScrollPositionCenteredVertically animated:YES];
```

**Comment by jaceklapinski** [comment]
Hi, 

I have same problem, i don't want to scroll to most recent messages so in ViewDidLoad i set:

self.automaticallyScrollsToMostRecentMessage = NO

then i read data from database and:

self.collectionView.reloadData()
let ip = NSIndexPath(forRow: self.indexOfFirstUnreadMessage!, inSection: 0)
self.collectionView.scrollToItemAtIndexPath(ip, atScrollPosition: .Top, animated: false)

And this works only when i open view first time, when i close it and open again JSQMessageViewController always scroll down not to index i want :( 

Can u please help ?

**Comment by yadavanand** [comment]
@jaceklapinski 
Try this in ViewDidLoad and change  atScrollPosition to CenteredVertically

self.automaticallyScrollsToMostRecentMessage = false
self.collectionView.reloadData() 
let ip = NSIndexPath(forRow: 5, inSection: 0) 
self.collectionView.scrollToItemAtIndexPath(ip, atScrollPosition: .CenteredVertically, animated: false)

this should work fine.

**Comment by jaceklapinski** [comment]
Hi, 

Thx!

But i can't do this in viewDidLoad -> i need to do this after i get data from firebase, and then this solution don't work 

Regards

**Comment by yadavanand** [comment]
@jaceklapinski  that's great, it's a pleasure!
