### ISSUE TITLE
Group avatar incoming like skype

### ISSUE THREAD

**Issue by pqhuy87it** [jessesquires/JSQMessagesViewController#1547]
![simulator screen shot apr 14 2016 4 43 12 pm](https://cloud.githubusercontent.com/assets/5575899/14524050/c75c934e-0260-11e6-9ff9-f0e8ed10f109.png)
![img_0099](https://cloud.githubusercontent.com/assets/5575899/14524066/d66beea2-0260-11e6-8018-a0787291da9a.PNG)
Can i group avatar incoming and when scrolling up, it lock on top like in skype ?

**Comment by eliburke** [comment]
@pqhuy87it you can do this yourself by checking previous messages in the collection's delegate methods:

- messageBubbleImageDataForItemAtIndexPath
- avatarImageDataForItemAtIndexPath
- attributedTextForCellTopLabelAtIndexPath
- attributedTextForMessageBubbleTopLabelAtIndexPath
- attributedTextForCellBottomLabelAtIndexPath

Here's an example from the Demo project:
```
    if (indexPath.item - 1 > 0) {
        JSQMessage *previousMessage = [self.demoData.messages objectAtIndex:indexPath.item - 1];
        if ([[previousMessage senderId] isEqualToString:message.senderId]) {
            return nil;
        }
    }
```

**Comment by pqhuy87it** [comment]
@eliburke thank you i grouped avatar incoming but when scrolling up avatar disappear, how can i lock it on top like skype ? 
![simulator screen shot apr 14 2016 8 36 52 pm](https://cloud.githubusercontent.com/assets/5575899/14529863/ab692d30-0280-11e6-9c53-6e16a105c04d.png)

**Comment by pqhuy87it** [comment]
with tableview i can custom header for resolving this
![simulator screen shot apr 14 2016 8 39 16 pm](https://cloud.githubusercontent.com/assets/5575899/14529977/19d9f0a6-0281-11e6-9abc-ab9519cb5cdd.png)

**Comment by eliburke** [comment]
@pqhuy87it The idea of using a custom header is good, but right now the whole collection uses just one section. According to #1546 multiple sections is a feature planned for the next major release. 

You could try using `[self.collectionView indexPathsForVisibleItems]` to get a list of visible cells and write some code to guarantee that you always show an Avatar.

**Comment by pqhuy87it** [comment]
@eliburke thank you for advice, i will try that way.
