### ISSUE TITLE
Group messages in the same bubble

### ISSUE THREAD

**Issue by simpleg** [jessesquires/JSQMessagesViewController#1548]
Hello,

I'm making an iOS tchat application using JSQMessagesViewController 7.2.0, and I'm looking for grouping messages in the same bubble, I found this old issue [https://github.com/jessesquires/JSQMessagesViewController/issues/203] talking about it.
But I'm totally lost on how I can do that.
I known it not really an issue, it's a help request, could you give me some hint on how to do that with UICollectionView.

Thanks in advance.
Jerome

**Comment by eliburke** [comment]
@simpleg For this version of the library, you have a couple of options:

- If you want to group messages in **the same bubble** you will probably need to create your own media item, manually combine messages, and lay them out in a UIView that you return. 
- If you want to have separate bubbles that appear close together, you remove the top / bottom labels for any cells that should appear grouped by overriding the various delegate methods. You can move them even closer together by changing the collectionView's flowLayout minimumLineSpacing
- If you want to have separate bubbles that are grouped and have distinctive shapes, you can create additional JSQMessagesBubbleImageFactory objects and return different bubble images for different index paths in messageBubbleImageDataForItemAtIndexPath

**Comment by simpleg** [comment]
Thank you for your answer I will try :)
