### ISSUE TITLE
Autocorrect bubble sometimes appears below keyboard when suggestions are closed

### ISSUE THREAD

**Issue by eliburke** [jessesquires/JSQMessagesViewController#1554]
When autocorrect suggestions bar is closed, and the input textView is 1-2 lines high, the floating autocorrect bubble appears below my toolbar and under the keyboard: 

![autocorrect](https://cloud.githubusercontent.com/assets/2371768/14677165/7144efe2-06de-11e6-8a25-ad89c2925ee3.gif)

I'm using the stock JSQMessagesComposerTextView, but I can't seem to reproduce this in the Demo project, so it's possible I'm doing something in my MessagesViewController to trigger it. Has anyone else encountered this problem?

**Comment by jessesquires** [comment]
Weird. Maybe this is an iOS bug?

**Comment by eliburke** [comment]
There's a lot of old information on StackOverflow, but most of it dates back to 2011-2013, leading me to think that there used to be a (more common) OS bug Apple fixed. 

Most of the proposed fixes involved disabling scroll or walking the view hierarchy to fiddle with the autocorrect view, but this [stackoverflow](http://stackoverflow.com/questions/1977249/how-to-move-uitextview-correction-suggestion-above-text) has a more recent suggestion to override textInputView and firstRectForRange. I'm going to try fiddling with those when I have a chance.

**Comment by Arslan007** [comment]
@eliburke  and @jessesquires 
I have faced the same issue but my issue was I was not giving app launch screens for iPhone 6 and iPhone 6+ and most wierd thing was it was only effecting only iOS9+ and iPhone 6 onwards. 
I hope it might helps you :)

Cheers!

**Comment by eliburke** [comment]
Holy smokes I think you're right @Arslan007! I just recently updated my app to use autolayout instead of UI scaling and sure enough, I can no longer reproduce the bug. That's good enough for me to pin the blame on iOS. Thanks for the tip! 🎉 😄
