### ISSUE TITLE
Cells resize after I open an URL

### ISSUE THREAD

**Issue by deyil** [jessesquires/JSQMessagesViewController#1555]
When I click on a link in a message bubble and then I return to my app, the cells stretch. Has anyone noticed this issue?
### General information
- Library version(s): 7.2.0
- iOS version(s): iOS 9.3
- Devices/Simulators affected: iPhone 6S Plus
#### Expected behavior

Cells should not resize when you open links

> ...
#### Actual behavior

Cells resize when you open links

> ...
#### Steps to reproduce

Open a link in a message bubble

> ...

![img_2123](https://cloud.githubusercontent.com/assets/872880/14684157/2cad073a-0737-11e6-9b8b-8eafc6078e79.PNG)
![img_2124](https://cloud.githubusercontent.com/assets/872880/14684158/2caf7e66-0737-11e6-9d7a-6d8cabd001a2.PNG)

**Comment by Lucashuang0802** [comment]
@deyil Hmm, can you have more info to replicate this like the contents? I can't replicate it by simply typing a random link like www.apple.com.

**Comment by deyil** [comment]
I cannot replicate it too in the latest version of the library.

**Comment by Lucashuang0802** [comment]
@deyil thx for your confirm. 😁

**Comment by deyil** [comment]
In latest version (7.3.4) issue seems to have returned. Tapping links in bubbles and opening them in Safari seems to resize bubble width. Can anyone else confirm? 
I have iOS 10.

**Comment by deyil** [comment]
I can replicate this issue from 7.3.0 to 7.3.4. Haven't tried previous versions.

**Comment by jessesquires** [comment]
Thanks @deyil !

**Comment by jessesquires** [comment]
@deyil  -- can you update your original comment in the issue with all of the correct details?

**Comment by deyil** [comment]
Yes! You can replicate this issue and in simulator not only in actual device.
If you have a text bubble with a link in it and you tap it, after opening to Safari, select to go back to JSQ app. This will result in message bubbles to resize (become bigger, as per attached images above).

(I have attached and a video also)

[jsq.mp4.zip](https://github.com/jessesquires/JSQMessagesViewController/files/532646/jsq.mp4.zip)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
