### ISSUE TITLE
Totally disorder displaying

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1556]
Have seen bellow screen few times. Cannot reproduce in purpose. No clue / idea why it happened. Has anyone seen same screen or have idea to check / fix? Thanks

![img_2395](https://cloud.githubusercontent.com/assets/1370755/14696974/30b84b96-07c3-11e6-809d-50093c39c6f1.PNG)

**Comment by jessesquires** [comment]
Thanks @nguyenpham ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:
