### ISSUE TITLE
Multiple attachments

### ISSUE THREAD

**Issue by ftp27** [jessesquires/JSQMessagesViewController#1557]
Are you planning implementing feature to support multiple attachments with text in single message? Or is this already in library or/and I can implement this feature myself (if so, please point out how is this achievable)

**Comment by eliburke** [comment]
@ftp27 In the future, please use the search feature to look at existing issues before opening new ones.  😜 This is discussed in issues #681 #809 #1487 #1536 and #1548. There is also PR #1520 for labeled messages, and #1537 for custom view messages. 

To answer your questions: this is not already available, but you can definitely implement it using custom mediaView cells. Start by reviewing the various issues and if you have more questions, ask away.

**Comment by ftp27** [comment]
Thanks for your quick reply,

I could use custom mediaView cells, but will they help me? I have a feeling these attachments must by placed as a preview above an input field. Am I right?

**Comment by eliburke** [comment]
I can't tell if you are asking about the layout of the mediaView, or the input of attachments into the input text view. If you want to allow the user to paste multiple images, look at #1516 for the paste support. 

Once you have the input, it's up to you to figure out how to serialize text+images into a combo message and render it into a mediaView.
