### ISSUE TITLE
Input toolbar does not show up

### ISSUE THREAD

**Issue by siliconprime-ninhvo** [jessesquires/JSQMessagesViewController#1558]
Hi
I add a contact selection bar at the top of the view controller (like iMessages). The input toolbar does not show up when i tap on the searchbar to search contacts! Can you help for this?

Thanks
Ninh

**Comment by jessesquires** [comment]
Thanks @siliconprime-ninhvo ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:
