### ISSUE TITLE
Best way to add a subview to collection view cell

### ISSUE THREAD

**Issue by DBL-Lee** [jessesquires/JSQMessagesViewController#1559]
What I want to do is when I send a message, it comes up as a collectionview cell with an activity indicator spinning beside the message bubble and when the message is finished sending, the activity indicator disappears if success or another button appears in place if failed.

What is the best way to do this?

I am thinking of adding subviews in `cellforrowatindexPath` but it seems not appearing. Is this because of the cell resizing issues cutting off just beside the message bubble?

Or should I subclass `jsqcollectionviewcell` to add this?

Thanks in advance.

**Comment by eliburke** [comment]
Check out #1519 and see if it helps

**Comment by DBL-Lee** [comment]
@eliburke Thank you very much! It's exactly what I was thinking of. I should add the subview to contentview of cell instead of directly to the cell.

**Comment by eliburke** [comment]
👍 glad to hear it was helpful.
