### ISSUE TITLE
Date not showing on top of chat Bubble!

### ISSUE THREAD

**Issue by NuelNikhil** [jessesquires/JSQMessagesViewController#1561]
It's my first attempt with iOS app development and it is a chat application. I found your beautiful library for Chat UI. Now I am able to set chat bubbles for messages but I don't see any date on top of my chat bubble.

What I Did

```
override func didPressSendButton(button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: NSDate!) {
        print("Date : \(date)")
        let message = JSQMessage(senderId: senderId, senderDisplayName: senderDisplayName, date: date, text: text)
        self.messages += [message]
        self.finishSendingMessage()
    }
```
I am using Swift and I don't know objective-c.I am getting my date in console but no in my viewcontroller. Do I need anything more for to get the Date on top of chat bubble ?

**Comment by happiehappie** [comment]
Did you leave space on the header for the date to be displayed? Your snippet didn't include that so... Just wondering

**Comment by NuelNikhil** [comment]
Sorry I didn't get that!... you mean any code ?

**Comment by happiehappie** [comment]
Did you implement

    collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat 

???

**Comment by NuelNikhil** [comment]
Nop...

**Comment by happiehappie** [comment]
So is it done now?

On Friday, 29 April 2016, Nuel Nikhil <notifications@github.com> wrote:

> Nop...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jessesquires/JSQMessagesViewController/issues/1561#issuecomment-215666307>
>


-- 
Best Regards,
Stanley

**Comment by jessesquires** [comment]
@NuelNikhil the method that @happiehappie is one you need to implement. see the demo project for an example 😄

**Comment by NuelNikhil** [comment]
OHHHHHKKK @jessesquires  and @happiehappie ...   😄

**Comment by NuelNikhil** [comment]
I tried the way you guys mentioned and I am getting the Space on top of message but no date is shown only a white space. I printed out the date and getting it in console like this  **2016-05-02 06:51:47 +0000
** b ut not showing on top of message... :(

**Comment by eliburke** [comment]
Did you also implement the function that prints the date label? I'm not sure what it is called in Swift, but something like: attributedTextForCellTopLabelAtIndexPath?

**Comment by NuelNikhil** [comment]
So how many functions  to implement? And I haven't implement what you have said... @eliburke

**Comment by eliburke** [comment]
This is a complex library. It really helps if you spend some time looking at code and documentation. If you are writing in Swift and don't have a good understanding of Objective C, you might want to clone #1491 and look at it.

**Comment by NuelNikhil** [comment]
@eliburke  you said it i am using swift and don't have idea about Objective C because I am a .net Developer and this is my first attempt with iOS. That's why I am getting confused of things...   anyway thank's for the comments. I will try ...

**Comment by NuelNikhil** [comment]
All Done ... Thanks @happiehappie  , @jessesquires  , @eliburke

**Comment by alejandrorbradford** [comment]
are you storing your messages on firebase? 


override func didPressSendButton(button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: NSDate!) {
        print("Date : \(date)")
        let message = JSQMessage(senderId: senderId, senderDisplayName: senderDisplayName, date: date, text: text)
        self.messages += [message]
        self.finishSendingMessage()
    }


cause I think this wont do it

**Comment by VergaraF** [comment]
Hey Nuel... do you mind sharing your solution?

I set up 
collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat

and

collectionView(collectionView: JSQMessagesCollectionView, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath) -> NSAttributedString? 

but I don't get it working :/

**Comment by NuelNikhil** [comment]
@VergaraF Okay... I was about to paste my code .. 👍

**Comment by carloscrono** [comment]
I am having same problem... Have you solved this?

**Comment by acjh** [comment]
@carloscrono Did you override both of these functions?
- [ ] `collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat`
- [ ] `collectionView(collectionView: JSQMessagesCollectionView, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath) -> NSAttributedString?`

**Comment by carloscrono** [comment]
Yes, but don't know what to write inside the functions :/

**Comment by acjh** [comment]
@carloscrono You can start with:
```swift
override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
    return kJSQMessagesCollectionViewCellLabelHeightDefault
}
```
```swift
override func collectionView(collectionView: JSQMessagesCollectionView, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath) -> NSAttributedString? {
    return NSAttributedString(string: self.messages[indexPath.item].date())
}
```

**Comment by carloscrono** [comment]
Ok, let me try @acjh since I am using swift 3 I have to do a little change in your code.

Thanks

**Comment by kirandasika98** [comment]
I am still not able to find the right solution to display this on Obj-C. I am overriding the following methods

```objective-c
- (CGFloat)collectionView:(JSQMessagesCollectionView *)collectionView layout:(JSQMessagesCollectionViewFlowLayout *)collectionViewLayout heightForMessageBubbleTopLabelAtIndexPath:(NSIndexPath *)indexPath {
    return 15.0f;
}

- (NSAttributedString *)collectionView:(JSQMessagesCollectionView *)collectionView attributedTextForCellTopLabelAtIndexPath:(NSIndexPath *)indexPath {
    JSQMessage *message = [self.messages objectAtIndex:indexPath.row];
    NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:message.senderDisplayName];
    NSMutableParagraphStyle *paragraph = [[NSMutableParagraphStyle alloc] init];
    paragraph.alignment = NSTextAlignmentLeft;
    [attributedString addAttribute:NSParagraphStyleAttributeName value:paragraph range:NSMakeRange(0, message.senderDisplayName.length)];
    [attributedString addAttribute:NSForegroundColorAttributeName value:[UIColor blackColor] range:NSMakeRange(0, message.senderDisplayName.length)];
    return attributedString;
}
```
