### ISSUE TITLE
Change title of header view UIButton when pressed.

### ISSUE THREAD

**Issue by khunshan** [jessesquires/JSQMessagesViewController#1562]
How can I change text to 'Fetching' and back to 'Load More' when fetched?

**Comment by eliburke** [comment]
@khunshan @GianniCarlo posted a great set of directions on customizing the JSQMessagesLoadEarlierHeaderView in issue #1129 

As for the mechanics of the changing the text, you can use the JSQMessagesLoadEarlierHeaderView delegate to detect button press, change the button title, start the fetch, and when you are done fetching, asynchronously change it back. If you aren't using asynchronous blocks, you may to capture a reference to the button or keep a reference to your custom JSQMessagesLoadEarlierHeaderView.
