### ISSUE TITLE
handleInteractivePopGestureRecognizer handle wrong in some situations

### ISSUE THREAD

**Issue by AidenWK** [jessesquires/JSQMessagesViewController#1565]
## Bug report
I notice the method 
`- (void)jsq_handleInteractivePopGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer`
in `JSQMessagesViewController.m`

UIGestureRecognizerStateEnded state handler is equal to UIGestureRecognizerStateFailed or UIGestureRecognizerStateCancelled
`[self.keyboardController beginListeningForKeyboard];
            if (self.textViewWasFirstResponderDuringInteractivePop) {
                [self.inputToolbar.contentView.textView becomeFirstResponder];
            }
            if ([UIDevice jsq_isCurrentDeviceBeforeiOS8]) {
                [self.snapshotView removeFromSuperview];
            }`

 
 

#### Expected behavior

when InteractivePopGestureRecognizer finished  should endListeningForKeyboard and resignFirstResponder

#### Actual behavior

some times inputToolBar.textView becomeFirstResponder
my situation is JSQMessagesViewController is a childViewController and not easy to control life cycle

**Comment by jessesquires** [comment]
Fixed by 752fd38aa8b899cbe2e21b6595de58920977bfc2
