### ISSUE TITLE
Scroll to bottom does not work properly

### ISSUE THREAD

**Issue by kshrikant** [jessesquires/JSQMessagesViewController#1566]
@jessesquires After going through  

https://github.com/jessesquires/JSQMessagesViewController/pull/644
https://github.com/jessesquires/JSQMessagesViewController/issues/256

I tried modifications told in issue 256 i.e. in `- (void)scrollToBottomAnimated:(BOOL)animated`

But i didn't find helpful. It might be previously resolved but i didn't have idea where i need to do changes. Please suggest me solution
#### Expected behavior

After textview did begin editing scrolling need to be at bottom.
#### Actual behavior

The scrolling is little but up  after begin editing.
#### Steps to reproduce

Initially there are 10 messages, after that when i started typing the scroll is little bit up instead of exactly bottom
#### Screenshot

![thumb_img_0333_1024](https://cloud.githubusercontent.com/assets/9281639/15065461/821e6bf8-137d-11e6-84d1-a5ac4f1067c3.jpg)

**Comment by kshrikant** [comment]
@jessesquires any idea ? where i can look into my code ? I want to resolve it please.

**Comment by mbalex99** [comment]
Did you put additional space on the content inset?

**Comment by doncorsean** [comment]
Seeing same behavior. When text field is resized i.e. LineBreak in textView everything is recalculated and appears correct.

**Comment by patniemeyer** [comment]
I am also having trouble with certain collections of messages breaking scrollToBottom.  I will try to narrow down the circumstances and suggest a fix when I get more time.   For the moment I am working around by setting the collectionview offset directly based on the view and content sizes.

        if self.collectionView.contentSize.height > self.collectionView.frame.height {
                self.collectionView.setContentOffset(
                    CGPointMake(0, self.collectionView.contentSize.height
                        - self.collectionView.frame.height + self.inputToolbar.bounds.height),
                    animated: animated)
        }

**Comment by alexwald** [comment]
+1

**Comment by viethdtadi** [comment]
Please fix this issue. I have same problem.

**Comment by tethridge** [comment]
I've noticed this issue is common when there are photos in the collection of messages.  It appears that photos can take more vertical space than when they are loading.  The view loads and the view is scrolled to the end, but if there were photos that hadn't yet loaded, then loading those photos causes the height of the scroll view to change.  This results in the user not seeing the latest messages, because it didn't scroll far enough.  

I think the solution would probably be to ensure that the photo messages don't change in size from the place holder to the final image.

**Comment by brianhu** [comment]
@patniemeyer's workaround worked for me. Here is Swift 3 version:
```
if self.collectionView.contentSize.height > self.collectionView.frame.height {
    self.collectionView.setContentOffset(
        CGPoint(x: 0, y: self.collectionView.contentSize.height
            - self.collectionView.frame.height + self.inputToolbar.bounds.height),
        animated: animated)
}
```

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
