### ISSUE TITLE
Decouple JSQMessagesToolbarContentView

### ISSUE THREAD

**Issue by IceFloe** [jessesquires/JSQMessagesViewController#1571]
@jessesquires Hi, how about decouple JSQMessagesToolbarContentView completely from controller? 

My main idea is remove all hard references from JSQMessagesViewController. And make this more in the delegate style. What do you think?

**Comment by jessesquires** [comment]
Hm... can you explain a bit more? 😊

**Comment by IceFloe** [comment]
For now it is hard to create completely custom toolbar. I suggest move it from JSQMessagesViewController and create toolbar like a component for it. This will not be easy, but I can try. :)

**Comment by jessesquires** [comment]
Ahh, I see. This would be very low priority right now. I wouldn't recommend attempting this until after v8.0 of the library. 😄

**Comment by IceFloe** [comment]
Ok, I will wait till 8.0 :)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
