### ISSUE TITLE
Add README for swift Example

### ISSUE THREAD

**Issue by MacMeDan** [jessesquires/JSQMessagesViewController#1573]
## Question or Feature Request

>  Add A ReadMe to the swift example.

More I am just making the task so I know what I need to do next.

**Comment by jessesquires** [comment]
should update this:

https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/getting_started.md

any other docs should go in `Documentation/`, too 😄

**Comment by MacMeDan** [comment]
sounds like a plan 🎧

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
