### ISSUE TITLE
How to enable disable send button if internet goes offline

### ISSUE THREAD

**Issue by srinathp90** [jessesquires/JSQMessagesViewController#1575]
Can anyone suggest how to disable send button if internet goes to offline and enable if internet available like whatsapp please suggest me.. @jessesquires @Ricardo1980

**Comment by wdcurry** [comment]
Research "Reachability" ..

**Comment by srinathp90** [comment]
@wdcurry  Disabled the send button when internet goes offline using reachability, But again send button enables when i start typing.

**Comment by davepatterson** [comment]
Assuming that you know how to find out the status of the internet, you can manually enable/disable the sendButton by setting it in `inputToolbar?.contentView?`. For example, if your send button is on the right, to enable it you would use `inputToolbar?.contentView?.rightBarButtonItem?.enabled = true`.

**Comment by srinathp90** [comment]
But the problem is  rightBarButtonItem enables once i start typing. That should not happen.

**Comment by davepatterson** [comment]
Well what you can do is override `JSQMessagesViewController`'s `textViewDidChange` method. In this method, as long as you don't call `super.textViewDidChange`, the status of the the sendButton will not update. So whenever you are ready for it to be enabled, you'll then just call `super.textViewDidChange` in the overridden `textViewDidChange` method.

**Comment by srinathp90** [comment]
Thank you.. it helps

**Comment by sebastianludwig** [comment]
Mmmhhh...I'd prefer an explicit solution like `self.inputToolbar.sendButtonEnabled = NO;` and change the implementation of `toggleSendButtonEnabled` to take that setting into account. And while we're on it, rename `toggleSendButtonEnabled` to `updateSendButtonEnabled` because it doesn't toggle. @jessesquires, are you up for a PR?

**Comment by SagarVarmaD** [comment]
Hi all 
I was trying to generate c# library, using Objective Sharpie Binding concept. i am facing some issues build errors

**Comment by sebastianludwig** [comment]
@SagarVarmaD please open a new issue
