### ISSUE TITLE
How to show "Someone left the conversation" text in JSQMessageviewcontroller

### ISSUE THREAD

**Issue by srinathp90** [jessesquires/JSQMessagesViewController#1580]
Hi i want to  show "Someone left the conversation" text and the date in JSQMessagesViewController Please help me. @jessesquires

**Comment by davepatterson** [comment]
I suggest notifying the other user in the `viewWillDisappear` method of `JSQMessagesViewController`.
```
override func viewDidDisAppear(animated: Bool) {
    // Input method that notifies user(s) in message thread that a user is leaving        
}
```

**Comment by jessesquires** [comment]
Thanks @srinathp90 !

`v8.0` of the library will support system messages 😄

**Comment by srinathp90** [comment]
👍
