### ISSUE TITLE
Keyboard ToolBar responsive Update

### ISSUE THREAD

**Issue by MartinQue** [jessesquires/JSQMessagesViewController#1581]
Considering most chat apps, other than the iMessage, their toolBars have other icons with functionaries on the right side and when user starts typing, the icons changes and updates to a send button. Could you possibly create this functionality? Even if optional? ...

**Comment by davepatterson** [comment]
Could you possibly post a screenshot of an example of this?

**Comment by cx478815108** [comment]
I think you can custom the keyboard toolbar by adding other views.you can post a screenshot.

**Comment by davepatterson** [comment]
Overriding `textViewDidChange` allows you to make updates after a user types. But remember to call `super.textViewDidChange` at the end of said method. This way you don't lose the toolbar updates that `JSQMesagesViewController` itself provides such as highlighting and enabling the `Send` button whenever there is text in `UITextView`.

```
override func textViewDidChange(textView: UITextView) {
    self.updateToolBarHoweverYouWant
     super.textViewDidChange(textView)
}
```

**Comment by jessesquires** [comment]
Thanks for the answer @davepatterson ! 😄
