### ISSUE TITLE
Don't highlight cell outside message bubble (when long press)

### ISSUE THREAD

**Issue by seidju** [jessesquires/JSQMessagesViewController#1583]
Hi everyone!
How can I disable bubble selection when I press outside message bubble? So, basically, now when you long press outside message bubble - it highlights (without menucontroller showing), and i want to remove that behavior.

Thanks for any help!

**Comment by jessesquires** [comment]
Thanks @seidju ! 😄 

Currently there's no workaround for this behavior. We can investigate this UI bug though.
