### ISSUE TITLE
textview not expanding

### ISSUE THREAD

**Issue by poorni008** [jessesquires/JSQMessagesViewController#1585]
i have added the observer also,but still my textview is not expanding.Don't know what the problem is.

**Comment by davepatterson** [comment]
Your textView is not expanding as you type? Is it possible that you post the code that you are using?

**Comment by poorni008** [comment]
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context
{
    if (context == kJSQMessagesKeyValueObservingContext) {
        
        
        if (object == self.messageTextView
            && [keyPath isEqualToString:NSStringFromSelector(@selector(contentSize))]) {
            
            CGSize oldContentSize = [[change objectForKey:NSKeyValueChangeOldKey] CGSizeValue];
            CGSize newContentSize = [[change objectForKey:NSKeyValueChangeNewKey] CGSizeValue];
            
            CGFloat dy = newContentSize.height - oldContentSize.height;
            NSLog(@"%f",dy);
            [self jsq_adjustInputToolbarForComposerTextViewContentSizeChange:dy];
            [self jsq_updateCollectionViewInsets];
            if (self.automaticallyScrollsToMostRecentMessage) {
                [self scrollToBottomAnimated:NO];
            }
        }
    }
}

**Comment by poorni008** [comment]
toolbar is expanding but textview is not expanding.

**Comment by jessesquires** [comment]
Thanks @poorni008 😄 

Can you update to 7.3 of the library and see if your issue is resolved?

We can't reproduce this in the demo....
