### ISSUE TITLE
Should the function "jsq_addObservers" be called earlier in time?

### ISSUE THREAD

**Issue by big-r81** [jessesquires/JSQMessagesViewController#1587]
## Question

The method `jsq_addObservers` (JSQMessagesViewController) is registered in `viewDidAppear`. 
Why isn't it registered earlier in `viewDidLoad` or `viewWillAppear`?

If `jsq_addObservers` would be registered in `viewDidLoad` or `viewWillAppear`
than it would be possible to set the text in the `textView` of the inputToolbar with the correct size of 
the `textView` before the View is shown.

To auto-size the `textView` I have to wait until the `viewDidAppear` method is called to have
the ability to auto-size the inputToolbar `textView`. This introduces a jolting animation because
the View is already shown.

Are there any reasons why `jsq_addObservers` is called so late in `viewDidAppear`?

**Comment by jessesquires** [comment]
hey @big-r81 -- there are some legacy reasons and iOS issues why it is this way.

however, this is something we can hopefully revisit for v8.0 of the library

**Comment by big-r81** [comment]
hey @jessesquires -- thank you for your fast response.

Is there any short / fast / beautiful workaround?

**Comment by jessesquires** [comment]
😁 not quite. moving this call right now will cause some other unexpected behaviors

**Comment by jessesquires** [comment]
Fixed by 752fd38aa8b899cbe2e21b6595de58920977bfc2
