### ISSUE TITLE
Write release notes for 7.3.0

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1592]
- [x] Write markdown release notes for 7.3.0 (use [7.2.0](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/7.2.0) as an example)
- [x] Update `CHANGELOG.md`

Issues closed are here: https://github.com/jessesquires/JSQMessagesViewController/issues?q=milestone%3A7.3.0+is%3Aclosed

**Comment by jessesquires** [comment]
@eliburke -- Would you like to help with this? It would be super helpful. Writing a markdown comment on this thread would be perfect. Then I can just paste into the GitHub release.

I think we can release this week. 🎉

**Comment by jessesquires** [comment]
Oh also, I changed this to 7.3 instead of 7.2.1 😅

**Comment by jessesquires** [comment]
beautiful! thanks so much @eliburke ! 🙌

**Comment by eliburke** [comment]
Missed one, added here and edited into my previous post:


:tada: **Improved custom cell menu support (#1281)**
Added override points for didReceiveMenuWillShowNotification, didReceiveMenuWillHideNotification
Thanks @keyeMyria!
