### ISSUE TITLE
avatarImageDataForItemAtIndexPath not getting called

### ISSUE THREAD

**Issue by vijaysanghavi** [jessesquires/JSQMessagesViewController#1596]
Working on chat module and found all methods of datasource are working but not `avatarImageDataForItemAtIndexPath` . Please see the video 

https://www.dropbox.com/s/ly1g6h9k3te2k5e/2016-05-24_19-17-01.mp4?dl=0

**Comment by eliburke** [comment]
@vijaysanghavi it is always a good idea to check the source code before you post a question. There are no paid support contracts here on gitlab! :smile:  

If you use XCode's search feature to find where _avatarImageDataForItemAtIndexPath_ is called you will see it is called in only one place:
```
if (needsAvatar) {
        avatarImageDataSource = [collectionView.dataSource collectionView:collectionView avatarImageDataForItemAtIndexPath:indexPath];
...
```

Looking a few lines earlier you will see:
```
    BOOL needsAvatar = YES;
    if (isOutgoingMessage && CGSizeEqualToSize(collectionView.collectionViewLayout.outgoingAvatarViewSize, CGSizeZero)) {
        needsAvatar = NO;
    }
    else if (!isOutgoingMessage && CGSizeEqualToSize(collectionView.collectionViewLayout.incomingAvatarViewSize, CGSizeZero)) {
        needsAvatar = NO;
    }
```

So, if the view size is zero, _avatarImageDataForItemAtIndexPath_ is never called. You can also find documentation of this behavior in the Demo project:

```
- (id<JSQMessageAvatarImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    /**
     *  Return `nil` here if you do not want avatars.
     *  If you do return `nil`, be sure to do the following in `viewDidLoad`:
     *
     *  self.collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeZero;
     *  self.collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero;
     *
     *  It is possible to have only outgoing avatars or only incoming avatars, too.
     */
```

So, make sure you set the avatarViewSize and the datasource method will be called.

**Comment by vijaysanghavi** [comment]
I am extremely sorry for posting such a silly issue. After posting this I found that I set the size to `CGSizeZero` which is why the method was not called. Could you please remove this

**Comment by eliburke** [comment]
@vijaysanghavi it's not a problem. My answer was a little cheeky because that's the mood I'm in today. I'm glad you fixed your bug.
