### ISSUE TITLE
Keyboard on top of inputToolBar

### ISSUE THREAD

**Issue by MaximShnirman** [jessesquires/JSQMessagesViewController#1597]
hello, i've been trying to find a solution most of the day and couldn't find an answer.
i've added LSQMessagesViewController to my project, as follows:
i have a view controller that has two tabs, lets call it tabvc, one of the tabs is the LSQMessagesViewController.
when tabvc reaches viewDidLoad it creates the LSQMessagesViewController like this:

   ```
chatVC = [DemoMessagesViewController messagesViewController];
chatVC.delegateModal = self;
UINavigationController *nc = [[UINavigationController alloc] initWithRootViewController:chatVC];
   
[nc willMoveToParentViewController:self];
[self addChildViewController:nc];
[self.viewChat addSubview:nc.view];
[nc didMoveToParentViewController:self];
```
* notice that DemoMessagesViewController is from the demo provided with the project.

everything seems to work fine - when i tap the chat tab i see the navigation bar like in the demo, i see all the messages and the input toolbar. the problem is that when i tap the textfield in the inputbar, the keyboard appears on top of the inputbar, and i can see that the collection view that holds the messages isn't changing its frame (if the messages were scrolled to the last, the keyboard just appears on top of them), also the text filed isn't expanding.  
i went through this ticket: https://github.com/jessesquires/JSQMessagesViewController/issues/366 that shows exactly my problem, at least in the images.

i do not override any method since its the same file as in the demo.

i think i might connected it wrong.... any help would be much appreciated!
thanks!

ios version: 9.3.1
xcode version: 7.3.1

**Comment by jessesquires** [comment]
Thanks @MaximShnirman ! 😄 

This definitely sounds like #366 . I would recommend looking at the demo project again to find what you're missing.

Also, if you haven't already, you should update to v7.3 of the library, released  yesterday.

**Comment by eliburke** [comment]
I was thinking the other possibility would be the fix from #1588 (which is included in the 7.3.0 release).

**Comment by MaximShnirman** [comment]
thanks for your answers! ill try updating and will let you know!

**Comment by MaximShnirman** [comment]
Thanks a lot! the update seems to fix it, cheers!
