### ISSUE TITLE
Regarding line spacing for textview

### ISSUE THREAD

**Issue by PrathmK** [jessesquires/JSQMessagesViewController#1598]
How can i alert the line Spacing of the text view.

**Comment by jessesquires** [comment]
thanks @PrathmK ! 😄 

all of the usual UIKit APIs are available. check out the docs for UITextView.

**Comment by PrathmK** [comment]
anyone who has done this, i tried by overiding ` (CGFloat)layoutManager:(NSLayoutManager *)layoutManager lineSpacingAfterGlyphAtIndex:(NSUInteger)glyphIndex withProposedLineFragmentRect:(CGRect)rect` the method in JSQMessagesCellTextView class but its not working. Any suggestions
