### ISSUE TITLE
Remove nibs, use programmatic layout

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1601]
- Better for maintenance 
- Better for PRs

This will fix these issues:
- #1340
- #1257
- #1844 
- #1212

**Comment by jessesquires** [comment]
⚠️ **NOTE:** not accepting PRs for this 😄

**Comment by MacMeDan** [comment]
@jessesquires I have started implementing this in all my personal projects and agree. We should probably move this same direction on messageKit. 💯

**Comment by eliburke** [comment]
Just curious-- are you guys talking about placement of views and controls? Constraints? I tend to build things in code (e.g. AudioMediaItem) but I think there's no debating that it makes it harder for people to understand what is going on and customize to suit themselves.

**Comment by jessesquires** [comment]
- Definitely removing the view controller nib, as it doesn't provide much value.
- Not sure about the toolbar.
- For cells, I will likely keep these.

**Comment by Lucashuang0802** [comment]
I think so far only `JSQMessagesViewController` is the case? #1670

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
