### ISSUE TITLE
Tab bar offset bug after updating pod to 7.3.0

### ISSUE THREAD

**Issue by Uki19** [jessesquires/JSQMessagesViewController#1602]
After i updated pod to 7.3.0 i got bug with tab bar. I have tabbar application and when i push my chat view controller (JSQMessagesViewController), i set hidesBottomBarWhenPushed so it hides my app tabbar and text input field should be on bottom. This worked properly in 7.2.0 version. Now i get slight delay with tabbar disappearance so when i push my chat view controller it looks like this(image bellow) and after 1 second text input is dropped down where it should be:

![img_3360](https://cloud.githubusercontent.com/assets/9538239/15572412/bf0df466-2340-11e6-98ec-5e1f08ad3cae.jpeg)

I've browsed some latest closed issues for 7.3.0 and i found this pull request #1588. This change produced this bug for me, as i already experienced this bug before and the reason behind it is when view is constrained to bottom layout guide instead of 0px to bottom of superview.

Is there a way to customize this constraint? I know i could hide/show tabbar in viewDidAppear/Disappear but that would make some complications in my case.

**Comment by jessesquires** [comment]
Thanks @Uki19 ! 😄 

Sorry for this regression. If you remove the changes to `viewWillLayoutSubviews` does it affect the behavior?

Also, is your tabbar transparent?

**Comment by Uki19** [comment]
@jessesquires No difference with `viewWillLayoutSubviews`. My tabbar is transparent (if you mean translucent) 😄 
Tabbar actually disappears properly, just textfield view(or whatever view is on bottom in this scenario) has delay. I forgot to mention that i am using JSQMessagesViewController inside container view, but i've tried all fixes on both chat view controller and its container view controller.
![146429675513694](https://cloud.githubusercontent.com/assets/9538239/15590178/8246b5da-2396-11e6-805b-51f4f964224d.gif)

**Comment by jessesquires** [comment]
fixed by #1623
