### ISSUE TITLE
Adding New Label inside Chat Screen

### ISSUE THREAD

**Issue by NuelNikhil** [jessesquires/JSQMessagesViewController#1603]
Hello ,  It' not about issue... But I would like to know If there any feature like in whatsapp i.e.,  When a new message comes there will be a label to show new messages...(unread messages) is there anything like in jsqmessagesviewcontroller ? or can I make one in jsqmessageviewcontroller ???

**Comment by eliburke** [comment]
@NuelNikhil there is not any feature like this built-in, but you can absolutely add one of your own design (or What'sApp's design!)
