### ISSUE TITLE
Chatbubbles of JSQPhotoMediaItem and JSQAudioMediaItem get mixed up

### ISSUE THREAD

**Issue by maxiundtesa** [jessesquires/JSQMessagesViewController#1610]
Hello,
I am having the issue that when I am having JSQPhotoMediaItems and JSQAudioMediaItems loaded up at the same time, it sometimes gets mixed up. This is only happening when both (Image and Audio) are present and when you scroll through the messages.

It looks like this:
Before Scrolling:
![image before](https://cloud.githubusercontent.com/assets/17526240/15628545/d70ec896-2503-11e6-9bf6-98c70f3dcd38.png)
After Scrolling:
![image after](https://cloud.githubusercontent.com/assets/17526240/15628548/ef5cae22-2503-11e6-922c-2f781ac8b199.png)

There are two more examples: 
![example1](https://cloud.githubusercontent.com/assets/17526240/15628551/023d40f6-2504-11e6-90c9-0d8e879bcb8e.png)
![example2](https://cloud.githubusercontent.com/assets/17526240/15628552/046df776-2504-11e6-9a76-84dc15bf8381.png)

If I am using only one of the mediatypes, it is working perfectly.
I am using iOS 9.3 and JSQ Version 7.3, it is happening on the Simulator and on the real device.

**Comment by jessesquires** [comment]
Thanks @maxiundtesa ! 😄 

This is likely a bug in what you are returning in `messageDataForItemAtIndexPath:`

See the demo for examples

**Comment by maxiundtesa** [comment]
Do you mean this method : `- (id<JSQMessageData>)collectionView:(JSQMessagesCollectionView *)collectionView messageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    return [self.demoData.messages objectAtIndex:indexPath.item];
}`?

Because I am using exactly the same just in swift: ` override func collectionView(collectionView: JSQMessagesCollectionView!,
                                 messageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageData! {
        return messages[indexPath.item]
    }`
