### ISSUE TITLE
[Help] Using JSQMessagesViewController for commenting feature

### ISSUE THREAD

**Issue by Steven4294** [jessesquires/JSQMessagesViewController#1611]
I'm trying to use this library to implement a commenting feature - similar to how Venmo does it (screenshot attached). I'm wondering if it even makes sense to use this library, given the amount of customization that would be required. I was wondering if this had been done before.

I would have to provide custom cells for the actual comments, as well as figure out a way to have the actual text post statically stay at the top of the view, as the user scrolls through the list of comments. Any advice as to how to proceed would be greatly appreciated.

![img_3634](https://cloud.githubusercontent.com/assets/8051383/15630458/bc23f64a-2509-11e6-8d6b-fb4dcfa7fa2d.PNG)

**Comment by jessesquires** [comment]
Thanks @Steven4294 ! 😄 

There are a lot of previously answered questions about customizing cells:
https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+custom+cells+in%3Atitle+is%3Aclosed

**Comment by Steven4294** [comment]
Yeah I saw that - I was wondering if there was any higher level advice you could offer. Was wondering it would be quicker to just build it on my own rather than using this, since all the customization would take longer to figure out.

**Comment by Steven4294** [comment]
like would it be possible to add a headerView (supplementary collection view) to the `JSQMessagesViewController` `@property collectionView`?
