### ISSUE TITLE
How to add subview via storyboard?

### ISSUE THREAD

**Issue by VasylKhmil** [jessesquires/JSQMessagesViewController#1624]
I've extended `JSQMessagesViewController`, and I'm trying to customize my controller by adding extra views from storyboard. Unfortunately it was not possible for me to do. Each subview is removed somewhere between `viewWillAppear:` and `viewDidAppear:` calls.

Do somebody know where is a problem?

**Comment by jessesquires** [comment]
Hey @VasylKhmil 😄 

So you won't be able to load a *storyboard*, but you could load custom `xib`s.

There's no reason you couldn't do this in the usual way via `viewDidLoad`

**Comment by Knyazik** [comment]
Facing the same problem. It's really bad, that it removes everything from controller
