### ISSUE TITLE
Displaying of more than one JSQLocationMediaItem at the same time breaks navigation bar push/pop animation

### ISSUE THREAD

**Issue by nyekimov** [jessesquires/JSQMessagesViewController#1632]
I've experienced issue with loading multiple JSQLocationMediaItems in a chat. I've added steps to reproduce, just assume that while showing the chat you receive multiple messages with location and try to display them, then go back and again to the chat several times and observe that at some point navigation bar stops pop/push animations (more JSQLocationMediaItems you have - it happens faster) 

```
    @implementation DemoMessagesViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
   ...
    __weak UICollectionView *weakView = self.collectionView;

    [self.demoData addLocationMediaMessageCompletion:^{
        [weakView reloadData];
    }];

    [self.demoData addLocationMediaMessageCompletion:^{
        [weakView reloadData];
    }];

    [self.demoData addLocationMediaMessageCompletion:^{
        [weakView reloadData];
    }];
}
```

The code below causes the issue, playing with dispatch_queues breaks the main UI.

```
 @implementation JSQLocationMediaItem

- (void)createMapViewSnapshotForLocation:(CLLocation *)location
                        coordinateRegion:(MKCoordinateRegion)region
                   withCompletionHandler:(JSQLocationMediaItemCompletionBlock)completion
{
  ...

    MKMapSnapshotter *snapShotter = [[MKMapSnapshotter alloc] initWithOptions:options];

    [snapShotter startWithQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)
              completionHandler:^(MKMapSnapshot *snapshot, NSError *error) {

                  ....
                  if (completion) {
                      dispatch_async(dispatch_get_main_queue(), completion);
                  }
              }];
}
```

Found second scenario, just send more than one location at a time, modify code, pop/push demochatview several times and send location message each time and observe that push/pop animation is broken. 

```
- (void)actionSheet:(UIActionSheet *)actionSheet didDismissWithButtonIndex:(NSInteger)buttonIndex
{
 ....

    switch (buttonIndex) {
      ....

        case 1:
        {
            __weak UICollectionView *weakView = self.collectionView;

            [self.demoData addLocationMediaMessageCompletion:^{
                [weakView reloadData];
            }];

            [self.demoData addLocationMediaMessageCompletion:^{
                [weakView reloadData];
            }];

            [self.demoData addLocationMediaMessageCompletion:^{
                [weakView reloadData];
            }];

        }
        ...
    }

    [JSQSystemSoundPlayer jsq_playMessageSentSound];

    [self finishSendingMessageAnimated:YES];
}
```

**Comment by jessesquires** [comment]
Thanks @nyekimov !

**Comment by jessesquires** [comment]
Can you explain what you mean by "breaks navigation bar push/pop animation" ?

Breaks in what way? Can you post a gif/video?

**Comment by nyekimov** [comment]
attaching zipped mp4 video with the issue happening in a simulator. Haven't found better way to demonstrate the issue.
 At the end you should observe that there is no more transition animations while pushing/popping a viewcontroller. 

[bug.mp4.zip](https://github.com/jessesquires/JSQMessagesViewController/files/296021/bug.mp4.zip)

**Comment by jessesquires** [comment]
Thanks @nyekimov !

One more thing -- any logs you can provide as well?

**Comment by nyekimov** [comment]
@jessesquires debugger is empty while executing these manipulations.

**Comment by agiusluke** [comment]
@jessesquires Just in case, this may help you. I have also noticed that apart from the navigation controller animation issues, the showing and hiding of the keyboard and basically all other animations in the app stop working. 

I will try to dig deeper into this soon.

**Comment by AndriyBas** [comment]
@jessesquires @nyekimov Had the same issue. The problem was with accessing UIKit in the background thread. Check my PR for the fix: https://github.com/jessesquires/JSQMessagesViewController/issues/1632

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
