### ISSUE TITLE
Bug in scrollToBottomAnimated

### ISSUE THREAD

**Issue by IceFloe** [jessesquires/JSQMessagesViewController#1640]
Hi @jessesquires, one small bug I have found in the scrollToBottomAnimated function, when we calculate maxHeightForVisibleMessage. We should also minus self.collectionView.contentInset.bottom.

Should be like this one

`CGFloat maxHeightForVisibleMessage =
    CGRectGetHeight(self.collectionView.bounds) -
    self.collectionView.contentInset.top -
    self.collectionView.contentInset.bottom -
    CGRectGetHeight(self.inputToolbar.bounds);`

In other way when we have keyboard opened and a big image come to us in chat it will not scroll to UICollectionViewScrollPositionBottom. What do you think, should I create pull request?

Second small bug in the 

`- (void)viewWillLayoutSubviews
{
    [super viewWillLayoutSubviews];

    if (!self.inputToolbar.contentView.textView.isFirstResponder) {
        [self jsq_setToolbarBottomLayoutGuideConstant:self.bottomLayoutGuide.length];
    }
}
`
This code will not work with 
`.hidesBottomBarWhenPushed = true`
Effect will be like jumping toolbar after view did appear. I am not sure for now how to fix this, but I can try.

**Comment by jessesquires** [comment]
Thanks @IceFloe ! 😄 

A pull request for the first issue would be great! 👍 

The second bug was fixed in `v7.3.1`

**Comment by jessesquires** [comment]
Be sure to submit the fix to the `release_7.3` branch 😊
