### ISSUE TITLE
Third-party input keyboard pops up, will keep out live chat content

### ISSUE THREAD

**Issue by 474404603** [jessesquires/JSQMessagesViewController#1643]
@jessesquires 

Third-party input keyboard pops up, will keep out live chat content.

### General information
- Library version(s):7.3.1
- iOS version(s):9.3.2
- Devices/Simulators affected: iphone6
- Reproducible in the demo project? (Yes/No): YES
- Related issues:

**Comment by jessesquires** [comment]
Thanks @474404603 !

> will keep out live chat content.

What do you mean by this?

Also, this might be fixed on `develop` with the recent keyboard handling changes

**Comment by Lucashuang0802** [comment]
@474404603 Can you probably give us more intent on your issue? That will be easier for us to help. 😃

**Comment by jessesquires** [comment]
Over a month old. Going to close due to inactivity. Will re-open if needed.

**Comment by 474404603** [comment]
[http://chuantu.biz/t5/22/1469498781x3738746559.png](url)
[http://chuantu.biz/t5/22/1469498842x3738746559.png](url)

sorry,This is third party ime pop-up state.Keyboard blots out the content。

**Comment by Lucashuang0802** [comment]
@474404603 It's on the latest develope branch?

**Comment by 474404603** [comment]
yes。
Library version(s):7.3.3
iOS version(s):9.3.2
Devices/Simulators affected: iphone6

**Comment by Lucashuang0802** [comment]
duplicate #1625.

**Comment by jessesquires** [comment]
let's track this at #1625 instead
