### ISSUE TITLE
Custom cell from nib

### ISSUE THREAD

**Issue by bitomule** [jessesquires/JSQMessagesViewController#1645]
## New issue checklist

- [x ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.3.2
- iOS version(s): 9.3.2

## Question or Feature Request

>  I'm trying to show a custom cell to show "system messages". I don't want to use a media item, just show a custom cell. Adding cellForItemAtIndexPath and sizeForItemAtIndexPath seems to work but now collection view total height is wrong. I get big empty spaces while scrolling.

Any idea on how to fix it? Am I doing something wrong?

I've:

- Registered custom cell in collection view
- Dequeue in cellForItemAtIndexPath when I need it
- Return custom height only for that cells and return super method height for default bubble cells

**Comment by bitomule** [comment]
I've managed to make it work using a custom JSQMessagesBubblesSizeCalculator and setting cell width to layout.collectionView.bounds.width. 

messageBubbleSizeForMessageData always return a 100px width

**Comment by eliburke** [comment]
@bitomule Glad you got it working! Would you care to post any of your source code or any additional information for others to use?

**Comment by bitomule** [comment]
Sure! I'ts on Swift. 

Hope I can help anyone trying to add a custom cell.

To handle custom size cells I just created a custom JSQMessagesBubblesSizeCalculator:

```
import Foundation
import JSQMessagesViewController

class MessageSizeCalculator:JSQMessagesBubblesSizeCalculator{
    override func messageBubbleSizeForMessageData(messageData: JSQMessageData!, atIndexPath indexPath: NSIndexPath!, withLayout layout: JSQMessagesCollectionViewFlowLayout!) -> CGSize {
        let defaultSize = super.messageBubbleSizeForMessageData(messageData, atIndexPath: indexPath, withLayout: layout)
        if let customMessageData = messageData.media?() as? CustomMessageItem{
            //Custom message
            return CGSize(width: layout.collectionView.bounds.width, height: MyCustomMessageCell.heightForMessage(customMessageData.message,width: layout.collectionView.bounds.width))
        }
        return defaultSize
    }
}
```

MyCustomMessageCell.heightForMessage is a class method that does height calculation based on message content and width. That was causing my white space issue as super returned width was always 100 and no the real view width once drawed (don't know why)


And used it on my chat view controller in viewDidLoad:

```collectionView.collectionViewLayout.bubbleSizeCalculator = MessageSizeCalculator()```

And in order to display that new custom cell I registered it (again, in viewDidLoad):

```collectionView.registerNib(UINib(nibName: "MyCustomCell", bundle: nil), forCellWithReuseIdentifier: "MyCustomCell")```

And returned it in cellForItemAtIndexPath:

```
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let message = chatDataSource.messageAtIndexPath(indexPath)
        if isCustomMessage{
            let cell = collectionView.dequeueReusableCellWithReuseIdentifier("MyCustomMessageCell", forIndexPath: indexPath) as! MyCustomCell
            cell.setupForMessage(message)
            return cell
        }
        return super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
    }
```

isCustomMessage is just a placeholder, I've a method to check if custom cell is required based on message.

Custom cell is an xib + class UICollectionViewCell subclass.

**Comment by sbkl** [comment]
@bitomule Would it be possible to get your code for the subclass of the JSQMessagesCollectionViewCell as well?

Thank you.

**Comment by bitomule** [comment]
It's not a JSQMessagesCollectionViewCell , just a collection view cell created in interface builder. I created a custom function to get the size.

**Comment by sbkl** [comment]
@bitomule thank you for your answer.

I managed to create a custom JSQMessagesCollectionViewCell.

Do you have the detail of cell.setupForMessage(message)?

When I load my custom cell, it erases the text inside the textView of the bubble.

**Comment by bitomule** [comment]
As I said is not a JSQMessagesCollectionViewCell, just a CollectionViewCell. In setupForMessage I set textfields and images of the cell based on message data. I'm sorry but not sure my cell can help debugging your custom JSQMessagesCollectionViewCell. 

I just set iboutlet's values.

**Comment by megimix** [comment]
[SwiftExampleSystemMessageCell.zip](https://github.com/jessesquires/JSQMessagesViewController/files/472036/SwiftExampleSystemMessageCell.zip)
I Implemented @bitomule solution on the the sample project (3th cell).
@jessesquires This approach should be added to the FAQ section as 3th custom cell option.

**Comment by jessesquires** [comment]
thanks @megimix ! would you like to submit a PR? 😄
