### ISSUE TITLE
Tap to remove keyboard

### ISSUE THREAD

**Issue by McFriend** [jessesquires/JSQMessagesViewController#1646]
I want to remove keyboard when user taps the screen. How shall I do it?
Thank you

**Comment by jessesquires** [comment]
Thanks @McFriend ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
