### ISSUE TITLE
When hardware (bluetooth) keyboard is connected, collection view contentInset.bottom is wrong

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1648]
1. Connect apple bluetooth keyboard on iPad
2. send messages
3. Note that `contentInset.bottom` and `scrollIndicatorInsets.bottom` are incorrect (too large)

**Comment by MacMeDan** [comment]
I looked into this but did not see anything wrong with the way it displayed. Are there any other steps to get it in the state in question or could we add a screen shot. I am on a iPhone 6s+

**Comment by jessesquires** [comment]
Ah, sorry. Tested on iPad. Might be iPad-only

**Comment by MacMeDan** [comment]
Ok Ill take a look on there then. 👍🏼

**Comment by Lucashuang0802** [comment]
😄  hey guys, just want to follow up some small issues a little bit. Do you guys think #1737 will fix it? Or, let's wait until @jessesquires to finish the review.

**Comment by jessesquires** [comment]
@Lucashuang0802 -- i don't think so. i don't think these are related

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
