### ISSUE TITLE
bubble height with arabic text is not calculated correctly

### ISSUE THREAD

**Issue by sherifomar** [jessesquires/JSQMessagesViewController#165]
sizeWithFont apparently has issues with non-latin character sets, arabic has many characters that hang below the baseline.

stackoverflow.com%2Fquestions%2F10224348%2Fcgsize-sizewithfont-not-returning-correct-height&ei=iwkBU8uFBIay2gW1p4CQAQ&usg=AFQjCNETlhTin0ykGD1TPfh3GoejgC4FzQ&sig2=L6z4RWFaVB4GyZQlSmiakg

Example
![screen shot 2014-02-16 at 2 17 44 pm](https://f.cloud.github.com/assets/3676710/2181019/0c2944b6-973f-11e3-9ce0-a402554a0d96.png)

The last line is pretty much hidden, the effect gets worse the more lines you have as each line's height is incorrect.

**Comment by AladinWay** [comment]
I have a similar problem, the size of the arabic font is not correct using : sizeWithFont or boundingRectWithSize , can you please just let me know how did you manage to fix the issue ? in which file is the solution ?

**Comment by sherifomar** [comment]
I think this was an iOS 6-only bug. which iOS version are you having the issue with?

**Comment by hemangshah** [comment]
@AladinWay @sherifomar - I am not using JSQMessagesViewController but I have the same issue to calculate the String height when it's Arabic string. Do you have a proper solution?

**Comment by roimulia** [comment]
@hemangshah Did you solved it?

**Comment by hemangshah** [comment]
@roimulia, Yes. But I have used MessageKit.
