### ISSUE TITLE
[8.0] Clean up included assets

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1650]
We should remove the audio and most bubble image assets. Only keep the default bubble images.

Goal: a lighter library, also `JSQSystemSoundPlayer` will be removed. (#1649)
1. Add subspec for audio assets
2. Add subspec for extra bubble assets
3. Add subspec for strings

**Comment by eliburke** [comment]
Do the assets get moved into the Demo project, or removed entirely? How does this affect test cases and testability? I suppose that we could auto-generate both for those purposes.

**Comment by jessesquires** [comment]
I want to move to this model:

1. Standalone framework project for the library
2. New top-level `Example/` directory. Shove the demo in there and link to the local pod.

> Do the assets get moved into the Demo project, or removed entirely?

They should be cocoapod subspecs. Admittedly, I still don't know *that* much about how subspecs work with regard to this

> How does this affect test cases and testability? 

It shouldn't

**Comment by Lucashuang0802** [comment]
I have been playing CocoaPods for a while. You guys can assign to me if that's okay. 😃

**Comment by jessesquires** [comment]
@Lucashuang0802 👍 Let's hold off on this until we make more progress on 8.0

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
