### ISSUE TITLE
Improve JSQMessagesAvatarImageFactory

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1657]
Make `JSQMessagesAvatarImageFactory` an instance with instance methods, instead of a bunch of class methods.

Same as #866 

init `JSQMessagesAvatarImageFactory` with a `diameter` and use this internally instead of passing as param

**Comment by jessesquires** [comment]
>/cc: @burntheroad 😉

**Comment by burntheroad** [comment]
Wow, thanks for noting me @jessesquires I'll take this 😀
