### ISSUE TITLE
Adding an imageView to the cell contentView/backgroundView

### ISSUE THREAD

**Issue by robertturrall** [jessesquires/JSQMessagesViewController#1658]
This is not exactly #275 but the problem is related and I fear that the answer will be subclassing.

I need to be able to add an imageView to the cell, to be displayed behind a media message (hence it's not solved by being able to display a media message). The image should cover the whole width of the cell contentView.

I've tried to remove/set to nil and then set and addSubview the imageView in collectionView: cellForItemAtIndexPath: in my viewController which subclasses JSQMessagesViewController.

This is not working as it needs to be set/unset within the context of reuse for the cells and clearly isn't this way.

Instead of subclassing everything from JSQMessagesViewController down to make sure that the necessary subclasses of JSQMessagesCollectionViewCellIncoming and JSQMessagesCollectionViewCellOutgoing are picked up to include the new imageView, is there any other way I can add this full-width imageView to the cell's background?

Thanks in advance for any help!

**Comment by eliburke** [comment]
@robertturrall I'm not sure I understand what you mean by "This is not working as it needs to be set/unset within the context of reuse for the cells and clearly isn't this way." -- did it work but you just don't think "correct"? Or is it not working at all?

If you subclass JSQMessagesViewController  and use a category to add an imageView property to the incoming and outgoing cells, you can override cellForItemAtIndexPath to initialize the property and add it to the underlying contentView. Use the view's layer zOrder to arrange below other subviews if necessary. 

If you don't want to update the imageView in cellForItemAtIndexPath, do it in willDisplayCell. It may also be necessary to update your imageView's frame, but I'm not sure.

**Comment by robertturrall** [comment]
@eliburke thanks for the suggestion. It makes a lot more sense than subclassing all the way down. Subclassing the incoming and outgoing cells and then casting to them in cellForItemAtIndexPath didn't work either as the original classes are being referenced at a later point and causing a crash.

What I meant by "This is not working as it needs to be set/unset within the context of reuse for the cells and clearly isn't this way." was that the image is being shown/not shown erratically on other cells and also "lost" upon scrolling - so clearly is not being correctly cleared and set on cell reuse.

I'll try the approach you suggest. It certainly makes sense!

**Comment by robertturrall** [comment]
@eliburke would you be able to elaborate on "you can override cellForItemAtIndexPath to initialize the property and add it to the underlying contentView"?

I've created categories for each of the incoming and outgoing cells, both holding an imageView property. These categories are then imported into my JSQMessagesViewController subclass.

In cellForItemAtIndexPath I then assign cell depending on whether the message is outgoing or incoming.

Then:

[cell.messageBackgroundImageView setImage:imageToUse];
[cell.contentView addSubview:cell.messageBackgroundImageView];
[cell.contentView sendSubviewToBack:cell.messageBackgroundImageView];

Causes a crash:

-[JSQMessagesCollectionViewCellIncoming messageBackgroundImageView]: unrecognized selector sent to instance 0x7fb405d4d9d0

because the original class does not declare messageBackgroundImageView and it is referenced somewhere.

As I wrote before, I fear I have to subclass further down the hierarchy than just JSQMessagesViewController. Am I missing something?

**Comment by robertturrall** [comment]
@eliburke figured out how to get the categories working but not seeing the imageview in the background at the moment. I'll carry on and see if I can figure it out. 

Here's an example of the implementation for one of the categories... does this look correct:

header:

```
#import <JSQMessagesViewController/JSQMessagesViewController.h>
#import <JSQMessagesViewController/JSQMessagesCollectionViewCellIncoming.h>

@interface JSQMessagesCollectionViewCellIncoming (BSBackgroundImageView)

@property (weak, nonatomic) IBOutlet UIImageView *messageBackgroundImageView;

@end
```
implementation:

```
#import "JSQMessagesCollectionViewCellIncoming+BSBackgroundImageView.h"
#import <objc/runtime.h>

static const void *ImageViewKey = &ImageViewKey;

@implementation JSQMessagesCollectionViewCellIncoming (BSBackgroundImageView)

- (void)setMessageBackgroundImageView:(UIImageView *)imageView
{
    objc_setAssociatedObject(self, ImageViewKey, imageView, OBJC_ASSOCIATION_ASSIGN);
}

- (NSString *)messageBackgroundImageView
{
    return objc_getAssociatedObject(self, ImageViewKey);
}

@end
```

**Comment by eliburke** [comment]
@robertturrall are you doing lazy loading? Do the cells always appear in the wrong place? Are they duplicated? Do they only sometimes show up in the wrong place? If you are not always using a background image, make sure you remove it for cells that don't use it. 
(maybe consider creating the imageView in cellForItem, and assigning it to nil or to an image in willDisplayCell)

**Comment by robertturrall** [comment]
@eliburke no lazy loading... the problem is that the images show on the correct cells, but also on other cells upon scrolling. Despite the image and imageView being nilled and removed in cellForItemAtIndexPath :

```
cell.messageBackgroundImageView = nil;
        [cell.messageBackgroundImageView removeFromSuperview];
```

What you describe is what I'm doing, but all in cellForItemAtIndexPath.

My assumption is that this is down to the use of addSubView here. The imageView is simply not being reliably removed and it's leaving artefacts on other cells upon reuse. With subclassing I could add the imageView within the cell class and control it's appearance/non-appearance better. It's just a pain that it won't work reliably otherwise!

**Comment by robertturrall** [comment]
I have also tried creating and assigning to the imageView in cellForItemAtIndexPath, and assigning it to nil or to an image in willDisplayCell for cases where the image should not be displayed (as a "failsafe") BUT this cannot work as the cell class passed into willDisplayCell is UICollectionViewCell. I can cast this to JSQMessagesCollectionViewCellOutgoing/JSQMessagesCollectionViewCellIncoming but despite the use of categories to add the imageView, the reference to any previously-assigned UIImage in cells is therefore not valid. 

Either way I see no possibility other than subclassing all the way down to JSQMessagesCollectionViewCell and adding far too many overrides to make this a feasible option. 

If anybody has any tried and tested ways to do this, please feel free to offer your thoughts. I'm moving on as this is taking too long. 

My fallback is to set the backgroundColor of the cell to the required image using [UIColor colorWithPatternImage:imageToUse] but I ideally need finer control and the ability to unset this without reloading the whole collectionView.

Thanks anyway @eliburke!

**Comment by eliburke** [comment]
@robertturrall I was able to make your feature work, although I did see some of the behavior you described along the way, leading me to believe you have a subtle bug in your code. 

Try adding the following code to the Demo project. For as many messages as I loaded, it did not fail, repeat, or otherwise appear incorrect. If you can break it in the demo, let me know and I'll look further.

DemoMessagesViewController.h after the last @end
``` 
@interface JSQMessagesCollectionViewCell (BSBackgroundImageView)
@property (strong, nonatomic) UIImageView *messageBackgroundImageView;
@end
```

DemoMessagesViewController.m outside "@implementation DemoMessagesViewController ... @end" 
```
#import <objc/runtime.h>
static const void *ImageViewKey = &ImageViewKey;
@implementation JSQMessagesCollectionViewCell (BSBackgroundImageView)
- (void)setMessageBackgroundImageView:(UIImageView *)imageView {
    objc_setAssociatedObject(self, ImageViewKey, imageView, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}
- (NSString *)messageBackgroundImageView {
    return objc_getAssociatedObject(self, ImageViewKey);
}
@end
```

DemoMessagesViewController.m in cellForItemAtIndexPath just before "return cell;"
```
    if (! cell.messageBackgroundImageView) {
        cell.messageBackgroundImageView = [[UIImageView alloc] initWithFrame:cell.contentView.bounds];
        cell.messageBackgroundImageView.contentMode = UIViewContentModeScaleAspectFill;
        [cell.contentView addSubview:cell.messageBackgroundImageView];
        [cell.contentView sendSubviewToBack:cell.messageBackgroundImageView];
    }
```

DemoMessagesViewController.m inside the @implementation
```
- (void)collectionView:(JSQMessagesCollectionView *)collectionView willDisplayCell:(nonnull UICollectionViewCell *)cell forItemAtIndexPath:(nonnull NSIndexPath *)indexPath {
    
    UIImage * image;
    switch (indexPath.item % 4) {
        case 0:
            image = [UIImage imageNamed:@"demo_avatar_cook"];
            break;
        case 1:
            break;
        case 2:
            image = [UIImage imageNamed:@"demo_avatar_jobs"];
            break;
        case 3:
            image = [UIImage imageNamed:@"demo_avatar_woz"];
            break;
    }
    ((JSQMessagesCollectionViewCell *)cell).messageBackgroundImageView.image = image;
}
```
