### ISSUE TITLE
Swift memory leaks

### ISSUE THREAD

**Issue by bitomule** [jessesquires/JSQMessagesViewController#1662]
I've subclassed JSQMediaItem to create a custom photo item and it causes it to be memory retained.

I create my item when I create JSQMessage:

`JSQMessage(senderId: String(self.sender.id), displayName: "\(self.sender.firstName) \(self.sender.lastName)", media: PhotoChatItem(message: self))`

Chat controller is released but PhotoChatItem is never released. I've just a simple empty subclass:

```
class PhotoChatItem:JSQMediaItem{

    init(message:MyMessage) {
        super.init(maskAsOutgoing: false)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

What can cause the memory issue?

Edit: I'm using Instruments to see allocation count and PhotoChatItem allocations number only grows.

**Comment by jessesquires** [comment]
Thanks @bitomule ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
