### ISSUE TITLE
The app crashes because of new "Delete" selector which is added in 7.3

### ISSUE THREAD

**Issue by halvini** [jessesquires/JSQMessagesViewController#1663]
When I select a text in my textInputView it offers me a new button I've never seen there before: "Delete".

If I press that button, the app crashes. Yesterday my app reported 1200 crashes because of this issue.

<img width="323" alt="screenshot 2016-06-09 17 33 17" src="https://cloud.githubusercontent.com/assets/16026223/15935687/6b28f340-2e68-11e6-80b6-e36110cfeab1.png">

`
2016-06-09 17:28:13.324 Secret Messenger[30587:7334460] -[JSQMessagesComposerTextView delete:]: unrecognized selector sent to instance 0x7a269800
2016-06-09 17:28:13.326 Secret Messenger[30587:7334460] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[JSQMessagesComposerTextView delete:]: unrecognized selector sent to instance 0x7a269800'
*** First throw call stack:
(
	0   CoreFoundation                      0x04545946 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x03d57a97 objc_exception_throw + 44
	2   CoreFoundation                      0x0454d5c5 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
	3   CoreFoundation                      0x044963e7 ___forwarding___ + 1047
	4   CoreFoundation                      0x04495fae _CF_forwarding_prep_0 + 14
	5   libobjc.A.dylib                     0x03d6d771 -[NSObject performSelector:withObject:] + 70
	6   UIKit                               0x02ebdc33 -[UICalloutBar buttonPressed:] + 355
	7   libobjc.A.dylib                     0x03d6d771 -[NSObject performSelector:withObject:] + 70
	8   UIKit                               0x02ebc39a -[UICalloutBarButton fadeAndSendAction] + 91
	9   Foundation                          0x01a1ab57 __NSFireDelayedPerform + 423
	10  CoreFoundation                      0x0449f8d6 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 22
	11  CoreFoundation                      0x0449f25d __CFRunLoopDoTimer + 1309
	12  CoreFoundation                      0x0445e6ba __CFRunLoopRun + 2090
	13  CoreFoundation                      0x0445dbcb CFRunLoopRunSpecific + 443
	14  CoreFoundation                      0x0445d9fb CFRunLoopRunInMode + 123
	15  GraphicsServices                    0x05f3924f GSEventRunModal + 192
	16  GraphicsServices                    0x05f3908c GSEventRun + 104
	17  UIKit                               0x02a308b6 UIApplicationMain + 1526
	18  Secret Messenger                    0x0011b708 main + 136
	19  libdyld.dylib                       0x0521aac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by halvini** [comment]
The auto-correction stopped working:

<img width="393" alt="screenshot 2016-06-09 17 37 23" src="https://cloud.githubusercontent.com/assets/16026223/15935800/e9550f6a-2e68-11e6-8f14-fa8dd911d990.png">

If my users make mistakes and then press the correct word, it does not work. Nothing actually happens.

My app is written on Swift. I have the last version of JSQ and it is integrated through CocoaPods.

**Comment by jessesquires** [comment]
Thanks for reporting @halvini !

We'll get on this 👍 

>/cc: @eliburke @GianniCarlo @MacMeDan, just FYI if anyone would like to help

**Comment by jessesquires** [comment]
Bug was introduced by #1281

**Comment by halvini** [comment]
There is one more issue in 7.3.1.

When my users chat and receive push-notifications from other apps, if they press them it also leads to crashes.

Unfortunately, I could not reproduce that on iPhone 6 iOS 9.3, but on iPhone 5 iOS 8.3 it definitely crashes.

**Comment by halvini** [comment]
I am actually about to revert to 7.2, as 7.3 first lead to many crashes on iOS 7, then these crashes....

I haven't had so many crashes since the launch of my app.

**Comment by GianniCarlo** [comment]
@jessesquires I found a quick solution to the delete crash, already created [pull request](https://github.com/jessesquires/JSQMessagesViewController/pull/1664). The other issue listed here about the spell check suggestion pressed not changing the text I haven't had time to check it out.

**Comment by GianniCarlo** [comment]
oh damn, I forgot to ignore my pods in swift x.x I'll fix that pull request ASAP

**Comment by GianniCarlo** [comment]
pull request fixed
