### ISSUE TITLE
Avatars strange size?

### ISSUE THREAD

**Issue by Steven4294** [jessesquires/JSQMessagesViewController#1672]
When you init a `JSQMessagesAvatarImage` with a `UIImage` that is not square, the resulting avatar stretches the content to fill the bubble. The bubble should behave as `UIContentModeApectFill`. Is there a quick fix to this?

**Comment by jessesquires** [comment]
Thanks @Steven4294 ! 😄 

You can use `JSQMessagesAvatarImageFactory` to crop your images.
