### ISSUE TITLE
Update Cell immediately

### ISSUE THREAD

**Issue by krymtn** [jessesquires/JSQMessagesViewController#1673]
How to update JSQMessagesCollectionViewCell bottomLabel currently, i set the data also replace to variable in my array but nothing changes.

The main part is access current cell. How can be ? 

/**
 *try this code and cell return null why ?
*/
JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[self collectionView:self.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:index inSection:0]];
        cell.cellBottomLabel.text = @"Sent";

and cell return null?

Thanks

//use update
 [self.collectionView performBatchUpdates:^{  
          [self.collectionView reloadItemsAtIndexPaths:@[[NSIndexPath indexPathForItem:index inSection:0]]];
        } completion:nil];

**Comment by GianniCarlo** [comment]
You should dequeue the cell from inside the `collectionView:cellForItemAtIndexPath:` function and do any customization to the cell from there. If you must do it from outside that function then use 
```objective-c
// you can cast your cell to either JSQMessagesCollectionViewCellOutgoing or JSQMessagesCollectionViewCellIncoming depending on your data source
UICollectionViewCell *cell = [self.collectionView cellForItemAtIndexPath:indexPath];
```
Compare how `cellForItemAtIndexPath:` is called there to how you're calling it. Let me know if that works for you

**Comment by krymtn** [comment]
I wrote like that you prefer
JSQMessagesCollectionViewCellOutgoing *cell = (JSQMessagesCollectionViewCellOutgoing *)[self collectionView:self.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:index inSection:0]];

but it crashed :(

 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: messageItem != nil'

**Comment by GianniCarlo** [comment]
Two things:
1.- Check your data source array if indeed you have a message at that index
2.- It's not exactly the same what I wrote
` [self.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:index inSection:0]];` 
!= 
`[self collectionView:self.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:index inSection:0]]`

mmmmm makes me think though, in practice there shouldn't be much difference. Check the first point first

**Comment by krymtn** [comment]
Gianni firstly thanks for your help,

Firstly i checked the datasource, its already okey when i sent to message but there was a strange stuff, 
When i coded first line, you said to me which is 

`JSQMessagesCollectionViewCellOutgoing *cell = (JSQMessagesCollectionViewCellOutgoing*)[self.collectionView cellForItemAtIndexPath:[NSIndexPath indexPathForItem:index inSection:0]];`

When i logged the cell, it returned (null) 

Btw, i logged the cellForItemAtIndexPath() method that is okey like that

Cell In CellForRow :<JSQMessagesCollectionViewCellIncoming: 0x7fa56c0898b0; baseClass = UICollectionViewCell; frame = (4 92; 367 78); clipsToBounds = YES; hidden = YES; opaque = NO; gestureRecognizers = <NSArray: 0x7fa56c156ab0>; layer = <CALayer: 0x7fa56c068370>>

**Comment by GianniCarlo** [comment]
Ok, so I went through the documentation for `UICollectionView`. Turns out, `cellForItemAtIndexPath` returns nil if that cell isn't visible, see [here for documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UICollectionView_class/index.html#//apple_ref/occ/instm/UICollectionView/cellForItemAtIndexPath:)

This can be proven in the demo project with:
```objective-c
UICollectionViewCell *cell = [self.collectionView cellForItemAtIndexPath: self.collectionView.indexPathsForVisibleItems.lastObject];
//cell won't be null
NSLog(@"cell %@", cell);
```
What I would advise, is that if you want to update a cell, first check if it's visible, otherwise it wouldn't matter as `cellForItemAtIndexPath` will get called before rendering your cell on the screen and there you should also have the logic to display if it's already sent or not

**Comment by krymtn** [comment]
I was excited when i read the last suggestion but it still returns (null). Let me tell you what i want to do. 

1) In my codes, when user send a text message , i allocate a JSQMessage object as 

`JSQMessage *jsqMessage = [[JSQMessage alloc] initWithSenderId:senderId
                                                senderDisplayName:@"Demo"
                                                             date:date
                                                             text:text];`
and add my mutableArray.(Array objects include jsqMessage and  (bool)isRead parameter) Its working fine. 

2) After that i'll receive a signal , user read my message. When i receive signal, i fetch the object all are okey and replace the isRead parameter to true. 

3) Cell index parameter is replaced object index. But i couldn't fetch the related cell , it returns null :/

**Comment by GianniCarlo** [comment]
mmmmmm are you absolutely sure that the collectionView is displaying your new message at the time the signal arrives? Can you reproduce it in the demo and send me a link of your fork to take a look?

**Comment by krymtn** [comment]
Solved! Thanks Gianni, need to NSNotification for trigger the view :)

Thanks for your help again
