### ISSUE TITLE
How to customize the date format in JSQMessgesViewController?

### ISSUE THREAD

**Issue by gmansata6290** [jessesquires/JSQMessagesViewController#1674]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.2.0
- iOS version(s): 8.0 or above
- Devices/Simulators affected: not really
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> Can anybody help me in customizing the datetime format in JSQMessagesViewController using Swift?
currently I m using the JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate() to format the date.
I want the DateTime to be in format if it is in current year i.e. 15 Jun 2:42 PM
If messages in previous years then format would be 15 Jun 2014 2:42 PM

**Comment by eliburke** [comment]
@gmansata6290 did you solve your problem? Can you post your solution for others?
Thanks!
