### ISSUE TITLE
Bubble message detect $value as link, and then changes color to black and stay in black

### ISSUE THREAD

**Issue by rmelian2014** [jessesquires/JSQMessagesViewController#1675]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.3.3
- iOS version(s): IOS 8.1.2, IOS 9.3
- Devices/Simulators affected: YES/YES
- Reproducible in the demo project? (Yes/No): YES
- Related issues: #1488,#1148,#956

## Bug report

When I write something like a message with a value like "$1,500", the bubble view mark as link when I long pressed the bubble view and change the color of this text "$1,500" to black color, and stay black until this cell is reloaded

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce
Change the color of own messages to white color
Open Demo
Click on push via storyBoard
Then add new message with any text and a value with '$' example "$1,800"
Then long press on bubble chat

#### Crash log? Screenshots? Videos? Sample project?

[Issue#1675 upload.zip](https://github.com/jessesquires/JSQMessagesViewController/files/321441/Issue.1675.upload.zip)

## Question or Feature Request

> ...

**Comment by rmelian2014** [comment]
I have this issue resolved on my fork, with commit bbec97a as soon as you approve this issue i will make pull request to fix it, regards

**Comment by rmelian2014** [comment]
@jessesquires  This issue will be reviewed?

**Comment by jessesquires** [comment]
Thanks @rmelian2014 ! 😄 

I just followed the steps and could not repro...

**Comment by rmelian2014** [comment]
You can't reproduce?, check this https://stackoverflow.com/questions/37867297/text-color-of-text-field-changes-for-some-words-when-long-pressed , maybe is already fixed on your new version?

**Comment by jessesquires** [comment]
Hm.. I tried this on `develop`. Which version was this in?

**Comment by rmelian2014** [comment]
This was originally founded on ver 7.3.3 but you need to change color of text to white

**Comment by Lucashuang0802** [comment]
Can you share the way how you change the text color to white? That will be convenient for replicating the issue. @rmelian2014 😄

**Comment by Lucashuang0802** [comment]
@rmelian2014 okay, I'm able to replicate it. See what I can do.

**Comment by jessesquires** [comment]
Thanks @Lucashuang0802 ! 👍 Let me know what you find
