### ISSUE TITLE
scrollToIndexPath does not work before the view appeared

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1677]
I have a custom cell called `unreadMessages`. I want to scroll to its `indexPath` when the view appeares in `viewDidLoad` or `viewWillAppear`. But `scrollToIndexPath` only works when placed in `viewDidAppear`.

**Comment by MHX792** [comment]
Actually... now I think that it's a better user experience when it scrolls to the unread messages after `viewDidAppear`. :D It feels more interactive. But I am still curious, why it isn't working.

**Comment by jessesquires** [comment]
Thanks @MHX792 ! 😄 

It's probably not working because the view isn't fully laid out at that point.

Perhaps you're loading too much data at once?

**Comment by MHX792** [comment]
No, it was because loading necessary data from the server in the background was not finished yet. It works now as expected.
