### ISSUE TITLE
Keyboarboard Controller moves Navigation Bar up

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1680]
I implemented the keyboard controller like so:

    func keyboardController(keyboardController: JSQMessagesKeyboardController!, keyboardDidChangeFrame keyboardFrame: CGRect) {
        self.isKeyboardVisible = keyboardController.keyboardIsVisible
    }
    
Now this happens, when the keyboard is shown:

![simulator screen shot 20 jun 2016 14 05 03](https://cloud.githubusercontent.com/assets/12123471/16193665/d22ccdc4-36f0-11e6-838a-18d5a9530a01.png)
![simulator screen shot 20 jun 2016 14 05 07](https://cloud.githubusercontent.com/assets/12123471/16193664/d228e484-36f0-11e6-84e8-16516a0aee41.png)

**Comment by jessesquires** [comment]
Thanks @MHX792 ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:
