### ISSUE TITLE
Cannot compile SwitfExample with the latest JSQMessagesViewController

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1681]
The example SwitfExample runs well with JSQMessagesViewController 7.2.0 after installing by Pod without version. However, when changing to the latest library by changing the Pod file:

#pod 'JSQMessagesViewController'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'

That example is failed with 20 errors. Please fix and always release with the latest libraries.

**Comment by MacMeDan** [comment]
will do.

**Comment by GianniCarlo** [comment]
@MacMeDan I created a pull request to fix this, let me know when you get the chance to check it out. I updated the Podfile to always pull from develop, what do you think about this last point?

**Comment by jessesquires** [comment]
fixed by #1686
