### ISSUE TITLE
Swift bug: Messages' widths are not consistent

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1682]
I have seen this issue with my program (in Swift) for a while. Thus I was very happy to see the new code SwiftExample. Unfortunately that code has the same issue with mine when widths of messages may be changed.

To reproduce: 
- image 1 is the screen of the device in portrait from the beginning
- image 2 is the screen after rotating the device into landscape then rotating back to portrait 

![simulator screen shot 20 jun 2016 10 56 55 pm](https://cloud.githubusercontent.com/assets/1370755/16195782/8eab8056-373e-11e6-9014-89534cd800ce.png)
![simulator screen shot 20 jun 2016 10 56 47 pm](https://cloud.githubusercontent.com/assets/1370755/16195781/8ea107e8-373e-11e6-9dfb-9b9c7d908211.png)

**Comment by nguyenpham** [comment]
I have just played with few different screen sizes on my simulator. Look like SwiftExample can run well in iPhone 4 - 5s but not any bigger ones. Could be screen size detection code problem?

Bellow is iPad screen:

![simulator screen shot 21 jun 2016 5 02 13 pm](https://cloud.githubusercontent.com/assets/1370755/16220873/dc56c0d8-37d2-11e6-9c3b-cac26b2dbd79.png)

**Comment by MacMeDan** [comment]
I just saw this also Very interesting.

**Comment by nguyenpham** [comment]
Thanks for the fix, I am so eager for that!

What is the main code for fixing that sizing problem? Is that two bellow lines in ViewDidLoad?

 `       self.collectionView?.setNeedsLayout()`
 `       self.collectionView?.layoutSubviews()`

My quick test in my app with above code seems not working. Will check further tonight.

**Comment by nguyenpham** [comment]
Good for now. It is turn out my app using older JSQMessagesViewController library - version 7.2. After updating into 7.3 and then adding two above lines, the sizing problem is fixed for my app. Look like the bug is fixed somewhere in versions > 7.2 - 7.3, plus your new fix in Swift.

Thanks all again :)

**Comment by jessesquires** [comment]
👍 🎉 closing as resolved
