### ISSUE TITLE
Use of undeclared type 'JSQMessagesCollectionView' in Swift

### ISSUE THREAD

**Issue by fiberzap** [jessesquires/JSQMessagesViewController#1683]
Hi,
I've been stuck on this error for a few days. I used to run into the same problem with JSQMessagesViewController but adding the following line:
import JSQMessagesViewController
to the offending code fixed the problem even though I already have JSQMessages.h in the bridging header.

But adding the line:
import JSQMessagesCollectionView
to the code produces the following error:
'No such module JSQMessagesCollectionView'

The bridging header is fine because there are other frameworks that works well in the project. The framework search paths have been added properly.
When I Option-Click on JSQMessageCollectionView on the code, it CAN successfully open to the correct header file, meaning that it is linked correctly.

I have no idea what is wrong. Any suggestion?

**Comment by jessesquires** [comment]
Thanks @fiberzap ! 😄 

Have you tried doing a clean build?

**Comment by fiberzap** [comment]
Hi Jesse,

Thanks for the reply. Yes, I have Googled and tried everything that I can find related to similar errors but nothing works.

Also, I found out that it doesn't work with JSQMessage either. Same problem.

Here are some of the things I've done:
1. use_frameworks! in podfile
2. Added bridging header and added the link to the Objective-C bridging header on both the project and target. Set 'Install Objective-C Compatibility Header' to Yes
3. Added both JSQMessages frameworks to "Compile Sources" and "Link Binary with Libraries" under Build Phases
4. Added the path to Framework Search Paths and Library Search Paths for both the project and the target, and made them recursive
5. Clean the project several times
6. Added the same paths, compile sources and link binary to the test targets
7. Reinstalled the pods
8. Changed the target device during build (it solved the problem with JSQMessagesViewController issue, for some reason)
9. Deleted Derived Data

It's puzzling in a number of ways:
- The other frameworks installed from Cocoapods and imported to the project work fine, except for JSQMessagesViewController.
- Supposedly importing <JSQMessagesViewController/JSQMessages.h> would import everything but I still had to import JSQMessagesViewController in Swift code to make it work. Unfortunately, it doesn't work for JSQMessagesCollectionView or JSQMessage
- Xcode can link the implementation correctly but it cannot compile. I'm not familiar with Objective-C syntax but everything seems to be in order.

I'm using Xcode 7.2.1. Thanks.

**Comment by MacMeDan** [comment]
Hey @fiberzap I don't think that you actually need to add it to your bridging header file. If your project is completely written in swift you can import it as a pod and reference it like normal. I would suggest getting rid of your bridging header, cleaning and even removing the pod do a `pod install` build. Then add the pod back and `pod install` again. also you may want to run a `pod update` because the laters version of pods no longer does that by default when you do a `pod install`. Let me know if that helps 🖖🏽

**Comment by rostopira** [comment]
@MacMeDan solution isn't working anymore. At least for Xcode 8

**Comment by MacMeDan** [comment]
That is strange. I don't know how else to help you without actually having your project and trying to build it myself but even if you did that It might work fine for me.

**Comment by mehmetsen80** [comment]
Hey MacMeDan,

I have similar problems and I need my Bridging header file for other Objective-C libraries such as Office365.

If I use use_framework! it works ok but I can't use it because otherwise Office365 breaks. The Objective-C libraries don't like the use_framework!

So I am stuck.. is there no way to link the JSQMessagesViewController through the Bridging header?

**Comment by apwelsh** [comment]
You can create your own bridging header file.    Then imoort that. But, i find it easier to modify my libraries to support use frameworks directive instead.    For this, I fork those projects that violate the frameworks standards.    I understand this is not an option for Office365, so the creation of your own bridging header is the beat solution.    XCode can do this for you, but i will need access to my XCode environment to confirm the exact steps.    This looks like what i have done in the past:    
  
    
  
  http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/
  

  
   This (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email)  is how I Email now
  
  
  
  
  

  
  
>

**Comment by MacMeDan** [comment]
@mehmetsen80 

You only need to use `use_framework!` if you are using cocoa pods that are written in swift. The `JSQMesssagesViewController` does not require it and can be imported just like any other ObjectiveC project. 

So yes you can include it through your Bridging header. Just be careful, What I have see with allot of people who have tried to switch from one to the other is that they will try to included through the Bridging header but have not fully removed all traces of the pod.  Then it errors out and they blame it on the Bridging header. I would suggest going as far as creating a new project and adding through there.

**Comment by MacMeDan** [comment]
You can also take the entire project build it and add it to your project. Not the solution I would use because it makes maintaining it completely on you and updating to the latest things the library offers requires you to delete it out and add the newer version in.

**Comment by ren-y** [comment]
I am using jsqmessagesviewcontroller in my app built using swift and has self hosted parse backend. I am facing an issue which is when I press send button the new message goes to the top of view controller instead of bottom.So the topmost message is newest and the one at bottom is oldest. Can someone help me in this regard?

**Comment by abhishekthanvi8** [comment]
After installing pod
Clean and rebuild worked for me to resolve this issue.
