### ISSUE TITLE
How update height of cells which have had their text changed in cellForItemAtIndexPath?

### ISSUE THREAD

**Issue by ryderjack** [jessesquires/JSQMessagesViewController#1684]
I'm removing a suffix on certain messages in cellForItemAtIndexPath as it should only be viewable by one of the users in the chat. Once it's removed the cell has already been drawn leading to the following: 
![simulator screen shot 21 jun 2016 20 04 31](https://cloud.githubusercontent.com/assets/10326229/16242710/ab195756-37eb-11e6-8255-009647397094.png)
 
Is there a way to force the cell to recalculate its height to remove that gap at the bottom?

cheers

**Comment by eliburke** [comment]
Give this a try:

```
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    context.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];
```

**Comment by ryderjack** [comment]
@eliburke no luck unfortunately, this is all I'm doing in cellForItem:

```
//remove suffix
cell.textView.text = [[msg text]stringByReplacingOccurrencesOfString:@"Tap to buy now" withString:@""];

JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
context.invalidateFlowLayoutMessagesCache = YES;
[self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];
```

**Comment by eliburke** [comment]
@ryderjack Ah I see. Your text height is calculated based on the underlying data, and you are "secretly" (to the framework) modifying it as it is displayed to the screen.

So-- can you change the underlying data? If not, can you change the COPY of the data you have in memory? If neither of those work, you may need to create a custom cell type.

**Comment by ryderjack** [comment]
Ah i see.. I'm now trying to change the message text as they're loaded however still seeing the same behaviour:
```
NSString *messageText = [messageOb objectForKey:@"message"];
                    
if ([[messageOb objectForKey:@"senderId"] isEqualToString:[PFUser currentUser].objectId]) {
      messageText = [[messageOb objectForKey:@"message"]stringByReplacingOccurrencesOfString:@"Tap to buy now" withString:@""];
 }
                    
message = [[JSQMessage alloc] initWithSenderId:[messageOb objectForKey:@"senderId"]  senderDisplayName:[messageOb objectForKey:@"senderName"] date:messageOb.createdAt text:messageText];
```

Where can I alter the message at an even earlier point? Is it the COPY of the data as you mention which is to blame?

**Comment by eliburke** [comment]
@ryderjack if you are modifying the message text before you ever create a JSQMessage object, the layout and spacing is determined by UITextView. If you see a strange gap in the bubble (like the one you showed at the start of this issue) maybe it is caused by a newline in your text string?

If this isn't your issue, we need to start fresh. Re-explain what you are doing (currently, not originally). Post the actual string that causes the problem, before and after your string editing. Post a current screen shot.

**Comment by ryderjack** [comment]
So, I'm using the messageController to facilitate the sending of offers to buy products. The buyer can send an offer message to the seller and when the seller sees that message they should be able to tap the offer to then confirm the offer based on the text contained within the offer message.

So far I have everything working except that I want the message to display a prompt only to the seller to "Tap to confirm the offer now". The buyer shouldn't see this message, only the seller.

I'm creating the message object then appending the text "Tap to confirm the offer now" to all offer messages in the didPressSendButton method before creating the message object and saving it to the backend:

```
messageString = [NSString stringWithFormat:@"%@\nTap to confirm the offer now", text];
JSQMessage *message = [[JSQMessage alloc] initWithSenderId:senderId
                                             senderDisplayName:senderDisplayName
                                                          date:date
                                                          text:messageString];
```

Then when I load the messages I'm doing a check whether the user seeing the message is the see or the seller. If the user is the buyer then they shouldn't see that part of the message so I remove all occurrences of the above string:

```
NSString *messageText = [messageOb objectForKey:@"message"];
 if (![[messageOb objectForKey:@"senderId"] isEqualToString:[PFUser currentUser].objectId]) {
                        messageText = [[messageOb objectForKey:@"message"]stringByReplacingOccurrencesOfString:@"Tap to confirm the offer now" withString:@""];
}
message = [[JSQMessage alloc] initWithSenderId:[messageOb objectForKey:@"senderId"]  senderDisplayName:[messageOb objectForKey:@"senderName"] date:messageOb.createdAt text:messageText];
```

If I don't remove the string that should only be seen by the seller, as expected, the entire message is viewable as per this image: 
![simulator screen shot 24 jun 2016 14 25 16](https://cloud.githubusercontent.com/assets/10326229/16338904/87e9dd04-3a17-11e6-9ac2-1a8dd6b04e1f.png)

However, when I do implement the above code to remove the string I see this gap:
![simulator screen shot 24 jun 2016 14 28 02](https://cloud.githubusercontent.com/assets/10326229/16338970/e6bde5dc-3a17-11e6-9c06-76610e421ed1.png)

Does this clarify your understanding of the problem @eliburke ? Thanks in advance!

**Comment by eliburke** [comment]
@ryderjack it does. And my answer is the same as before. Newlines. Check out your code:
`messageString = [NSString stringWithFormat:@"%@\nTap to confirm the offer now", text];`

 `messageText = [[messageOb objectForKey:@"message"] stringByReplacingOccurrencesOfString:@"Tap to confirm the offer now" withString:@""];`

You add a newline and your "confirm" text. Then you remove your text, but not the newline.

As a side note, have you considered an actual button instead of selecting the bubble?  #1537 lets you embed HTML. #1519 shows a way to add an accessory button outside the bubble.

**Comment by ryderjack** [comment]
Brilliant spot!! Apologies, completely missed that after checking!

Yes, I'll definitely check out using buttons on the cell, thanks again!

**Comment by eliburke** [comment]
You're welcome.

**Comment by AashishSapkota** [comment]
hey @ryderjack  How did you gave those time stamps and sent status. I also want to give the same, but when I try with cell.celltoplabel.text = "something" and cell.cellbuttomlabel = "Nothing displays"..
Literally nothing displays..Am I missing something. isn't it the default customizaation for JSQMessage?
I have been wondering around and ended up getting nothing..Please if you could help...

**Comment by AashishSapkota** [comment]
hey @ryderjack  How did you gave those time stamps and sent status. I also want to give the same, but when I try with cell.celltoplabel.text = "something" and cell.cellbuttomlabel = "Nothing displays"..
Literally nothing displays..Am I missing something. isn't it the default customizaation for JSQMessage?
I have been wondering around and ended up getting nothing..Please if you could help...

**Comment by ryderjack** [comment]
@AashishSapkota hey, here's some sample code which should help you:

```
NSInteger lastSectionIndex = [self.collectionView numberOfSections] - 1;
NSInteger lastItemIndex = [self.collectionView numberOfItemsInSection:lastSectionIndex] - 1;
NSIndexPath *pathToLastItem = [NSIndexPath indexPathForItem:lastItemIndex inSection:lastSectionIndex];
                    
[self collectionView:self.collectionView attributedTextForCellBottomLabelAtIndexPath:pathToLastItem];
[self collectionView:self.collectionView layout:self.collectionView.collectionViewLayout heightForCellBottomLabelAtIndexPath:pathToLastItem];
```

Basically, after loading the messages I call this at the end of the loadMessages method to calculate where the labels should appear. Then in the relevant methods such as attributedTextForCellBottomLabel... I do a check on the message's individual sent status which is then displayed.

Hope this helps!

**Comment by AashishSapkota** [comment]
Thank you so much for your help @ryderjack .
