### ISSUE TITLE
only show incomming avatar image view

### ISSUE THREAD

**Issue by esvikas** [jessesquires/JSQMessagesViewController#1685]
## New issue checklist

> ...is there possible to use only incomming avatar image view ,when i try to do that by setting 
![screen shot 2016-06-22 at 1 14 14 pm](https://cloud.githubusercontent.com/assets/8165263/16257984/5ac211e0-387b-11e6-9627-e8a3501fb09f.png) the avatar image size gap appers in JSQMessagesViewController, when i change outgoing image view to  collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSize.zero 
the app crash with error Invalid parameter not satisfying: diameter > 0

**Comment by eliburke** [comment]
@esvikas it looks like a bug in your posted code for avatarImageDataForItemAtIndexPath. You are setting **outgoingAvatarViewSize** to CGSize.zero and then using the value for your **incomingAvatar**.
