### ISSUE TITLE
Reloading the collection view multiple times leaves the chat screen blank

### ISSUE THREAD

**Issue by utkbansal** [jessesquires/JSQMessagesViewController#1687]
I intend to reload the collection view to update the delivery status of the messages. For that there is a notification listener

 `NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(ChatViewController.refreshList(_:)), name: "Message Sent", object: nil)
`

It calls the following function whenever a new message is delivered  -

```
unc refreshList(notification: NSNotification) {
        print("the message id sent is \(notification.object as? String)")
        
        let sentMessageID = notification.object as? String
        
        self.collectionView.reloadData()
    }
```

But the second time this function is called, the chat screen becomes blank

**Comment by jessesquires** [comment]
Thanks @utkbansal ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
