### ISSUE TITLE
How do I go about turning off URL support?

### ISSUE THREAD

**Issue by ahadsheriff** [jessesquires/JSQMessagesViewController#1689]
I have built a simple messaging app using jsqmessagesviewcontroller and I was wondering if there would be any way to disable a user from sharing a website url? Thanks

**Comment by jessesquires** [comment]
Thanks @ahadsheriff ! 😄 

I'm not sure what you mean. If you mean disabling a link in a message, you can do that by turning off data detectors in `UITextView`.
