### ISSUE TITLE
Pod file != Github version?

### ISSUE THREAD

**Issue by MartinSchultz** [jessesquires/JSQMessagesViewController#1690]
I have an issue that when I included the latest cocoa pod version 7.3.3, it is not the same version as the github repo version. For example in the class JSQMessagesAvatarImageFactory there is missing the initWithDiameter method which is used by the demos in the github demo project.

I've tried search here but didn't find anything. I also multiple times updated the pod file to see if I do something wrong. (podfile line: pod 'JSQMessagesViewController')

Is the cocoapods version just lacking behind? If so, when will it get updated?

Thanks
Martin

**Comment by jessesquires** [comment]
Thanks @MartinSchultz ! 😄 

This is typical, and expected. CocoaPods does not pull from the latest on GitHub by default. It uses tagged releases and semantic versioning. Generally speaking, projects are under continuous development and cut releases regularly — very much like app development. For example, your users aren't running the version of your app that *you have on your machine*, they are running whatever you submitted to Apple most recently.

You can find releases [here](https://github.com/jessesquires/JSQMessagesViewController/releases)

Version `8.0` of the library is currently underway. See the announcement at the top of the [README](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md) to learn more.

If you *want* the latest code on `develop`, CocoaPods can do this. This is also [explained](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md#cocoapods-recommended) in the README. However, this is not recommended.
