### ISSUE TITLE
I am adding an media Item in chat messages but getting some layout issue.

### ISSUE THREAD

**Issue by niteshtak** [jessesquires/JSQMessagesViewController#1699]
I am trying to add media message in chatViewController but I am getting very weird layout issue.
Please see the attachment below for more clear idea.
![img_0508](https://cloud.githubusercontent.com/assets/8844612/16378114/841e0e70-3c9c-11e6-8da2-dd49c0440757.PNG)

How can I remove this extra space below photo message.?
Please help me with this issue !! :(

**Comment by jessesquires** [comment]
Thanks! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:

**Comment by niteshtak** [comment]
Why you closed this issue, I still have this problem :(

**Comment by eliburke** [comment]
@niteshtak you haven't provided any information that would help us help you. We aren't detectives, we're programmers. If you have actually looked through all 1600 issues on github, you would find one of two possibilities:
1) you found someone else who had this problem, and you looked at the solution
2) you did not find ANYONE else with this problem, but the library is used by thousands of people, and therefore it is very likely a bug in your code, and you have provided nothing but a screenshot. 

I will continue my response in your new issue. In the future, please don't create duplicate issues. These can be re-opened if you just provide the necessary information.
