### ISSUE TITLE
Detection of custom links on messages

### ISSUE THREAD

**Issue by rmelian2014** [jessesquires/JSQMessagesViewController#1707]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation:💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information
I need a easy way to detect customs links on messages, links like:
 #user4568 or any other kind of custom link, so this can be implemented?

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request
I need a easy way to detect customs links on messages, links like:
 #user4568 or any other kind of custom link, so this can be implemented?
> ...

**Comment by jessesquires** [comment]
Thanks @rmelian2014 !

A couple of things:

1. You could use custom attributed strings and any available APIs on `UITextView`
2. For `v8.0` of the library, we're planning on adopting TTTAttributedLabel, which would allow this out-of-the-box
