### ISSUE TITLE
Input toolbar does not resize when switching back to JSQMVC

### ISSUE THREAD

**Issue by ryderjack** [jessesquires/JSQMessagesViewController#1709]
After entering some text in the textview the height of the input changes correctly so all the text is viewable which is great:

![simulator screen shot 7 jul 2016 14 48 36](https://cloud.githubusercontent.com/assets/10326229/16655411/19ca1d9e-4452-11e6-826a-0845d6a046f1.png)

However, when a different tab is selected and then the user comes back to the JSQMVC tab the height of the input tool bar collapses like so:

![simulator screen shot 7 jul 2016 14 48 41](https://cloud.githubusercontent.com/assets/10326229/16655440/4373f57a-4452-11e6-93df-32cecd8e483c.png)

I'm not doing anything fancy in viewDid/WillAppear either and couldn't reproduce in the demo project as there's no tabs involved.

Do I need to manually force the textView to recalculate it's height upon the view appearing?

Cheers

**Comment by michaelkirk** [comment]
We had the same issue which resulted in this related issue: https://github.com/jessesquires/JSQMessagesViewController/issues/1587

**Comment by Lucashuang0802** [comment]
@ryderjack I'm still trying to understand the issue. Do you think you can replicate from the demo app? @jessesquires perhaps you have some ideas what's going on with this one? 😄

**Comment by jessesquires** [comment]
@Lucashuang0802 yeah the issue is if you want to pre-load the text view with text, it doesn't resize like it does while you type.

concerning what's currently on `develop` we have a small regression #1751.

**Comment by Anders123fr** [comment]
I have the same issue when pushing a new view controller, and when popping back, the input toolbar collapses

**Comment by ryderjack** [comment]
@Anders123fr still no fix here

**Comment by Lucashuang0802** [comment]
Probably a similar issue with #1812. Were you guys able to fix it by assigning the text content again like this `self.inputToolbar.contentView.textView.text` in either `viewDidLoad` or `viewWillAppear:`?

**Comment by Anders123fr** [comment]
I am pretty sure that was one of the first things i tried, and unfortunately it didn't work

**Comment by ryderjack** [comment]
Still no fix for me
