### ISSUE TITLE
IOS 9 Crash -[JSQMessagesCollectionViewFlowLayoutInvalidationContext invalidateFlowLayoutMessagesCache]: unrecognized selector sent to instance 0x7fc4b244de80'

### ISSUE THREAD

**Issue by alexyesiam** [jessesquires/JSQMessagesViewController#1711]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[JSQMessagesCollectionViewFlowLayoutInvalidationContext invalidateFlowLayoutMessagesCache]: unrecognized selector sent to instance 0x7fc4b244de80'

**Comment by jessesquires** [comment]
Thanks @alexyesiam ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:

**Comment by jessesquires** [comment]
Looks like you might be calling this method on the class, not an instance?
