### ISSUE TITLE
Make a screen chat with more views.

### ISSUE THREAD

**Issue by pqhuy87it** [jessesquires/JSQMessagesViewController#1714]
Hi, i want to make a screen chat like this 
![chat screen](https://cloud.githubusercontent.com/assets/5575899/16712266/2d67c084-46ac-11e6-9212-9e607ca4b38e.jpg)
i see in sample files in ChatViewController we have to inheritance JSQMessagesViewController so how can i custom a screen with more views not only chat view ?

**Comment by jessesquires** [comment]
Thanks @pqhuy87it ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
