### ISSUE TITLE
changing MessagesBubbleImage

### ISSUE THREAD

**Issue by bikram109** [jessesquires/JSQMessagesViewController#1716]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...
can we change the MessagesBubbleImage to some thing like this  
<img width="286" alt="screen shot 2016-07-11 at 12 49 28 pm" src="https://cloud.githubusercontent.com/assets/16533240/16722452/6a8f1a2e-4766-11e6-913f-b2e73c228b14.png">

**Comment by jessesquires** [comment]
Thanks @bikram109 ! 😄 

This is possible, see the demo project, or previous questions about this.
