### ISSUE TITLE
Some strings with special unicode characters cause wrong bubble size

### ISSUE THREAD

**Issue by JohnEstropia** [jessesquires/JSQMessagesViewController#1717]
## New issue checklist
- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
### General information
- Library version(s): 7.3.3
- iOS version(s): 9.x
- Reproducible in the demo project? (Yes/No): Yes
## Bug report

Some strings with special unicode characters cause wrong bubble size computation.
Here's one sample:

```
(੭ु´͈ ᐜ `͈)੭ु⁾⁾ 12345
```

<img src="https://cloud.githubusercontent.com/assets/3029684/16727099/6216c8e0-479a-11e6-83bf-d052525a8819.PNG" width=250 />

Copying the cell produces the original text:
<img src="https://cloud.githubusercontent.com/assets/3029684/16727127/8a4db5f8-479a-11e6-9eae-70a45b650e3e.PNG" width=250 />
<img src="https://cloud.githubusercontent.com/assets/3029684/16727132/8e6e5ed0-479a-11e6-9851-063f43e6e5fe.PNG" width=250 />

iOS 7 and iOS 8 seems to have no problem. Looks like an OS bug, but JSQMessagesViewController should be able to work around it
#### Expected behavior

The bubble size should have enough size to render the whole text.
#### Actual behavior

The bubble size is smaller than expected, so part of the text gets cut off
#### Steps to reproduce

Copy this text and paste to the demo app:

```
(੭ु´͈ ᐜ `͈)੭ु⁾⁾ 12345
```

**Comment by jessesquires** [comment]
Thanks @JohnEstropia ! 😄

**Comment by Lucashuang0802** [comment]
@JohnEstropia If that's related to the bubble size, should it at least see 123 perhaps 4?

**Comment by JohnEstropia** [comment]
@Lucashuang0802 It's wrapped by-word, so the next word falls to the next line

**Comment by Lucashuang0802** [comment]
Right, it looks like a bug here. Cuz it's working for the system app and
other chatting apps. Thx.

**Comment by Lucashuang0802** [comment]
Looks like the issue got fixed from 7.3.4, @jessesquires perhaps you can confirm it?

**Comment by jessesquires** [comment]
@Lucashuang0802 ... um, I don't think so.. ?

**Comment by Lucashuang0802** [comment]
@jessesquires I don't know how I get to this point. lol. Will check again later.
![simulator screen shot jul 22 2016 10 05 56 am](https://cloud.githubusercontent.com/assets/3754490/17065027/7f77f578-4ff4-11e6-84d0-c869ee820768.png)

**Comment by jessesquires** [comment]
Maybe there's an issue with @JohnEstropia's implementation then?

If we can't repro this in the demo, then let's close.

**Comment by JohnEstropia** [comment]
I just reproduced this with the current develop branch (7.3.4). I'd upload a screenshot, but it's the exact same one as the one I first posted.

The problem is that `boundingRectWithSize:options:attributes:context:` itself produces incorrect results.

**Comment by JohnEstropia** [comment]
Maybe try adding the `NSStringDrawingUsesDeviceMetrics` option? It seems to look better but I'm not sure about other side effects of that flag.

**Comment by Lucashuang0802** [comment]
@jessesquires Looks like it's working if we replace `NSStringDrawingUsesFontLeading` with `NSStringDrawingUsesDeviceMetrics`. Adding is working as well.

**Comment by jessesquires** [comment]
Replace? We should probably use both... ?

**Comment by Lucashuang0802** [comment]
Thx for the hint @JohnEstropia 🙂

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
