### ISSUE TITLE
Demo's Custom Action Menu is not positioned correctly

### ISSUE THREAD

**Issue by mwgray** [jessesquires/JSQMessagesViewController#1722]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.3.2
- iOS version(s): 9
- Devices/Simulators affected: iPhone 6s Plus
- Reproducible in the demo project? (Yes/No): Yes 
- Related issues:

#### Expected behavior

> Action menu tail should be above message balloon
![good](https://cloud.githubusercontent.com/assets/9472766/16823918/7340a018-491c-11e6-9fb3-4c16e4d160b3.png)

#### Actual behavior

> Action menu tail is centered to view
![bad](https://cloud.githubusercontent.com/assets/9472766/16823917/733f62f2-491c-11e6-95e6-698ec98180a7.png)

#### Steps to reproduce

> Run the demo, open custom action

**Comment by happiehappie** [comment]
Is this really fixed yet? I am on version 7.3.4 and I still faced this issue.
<img width="376" alt="screen shot 2016-10-17 at 10 30 33 am" src="https://cloud.githubusercontent.com/assets/6497131/19423622/c555ad2a-9454-11e6-9c4e-ad2aea56b316.png">
