### ISSUE TITLE
self.inputToolbar.contentView.leftBarButtonItem Enable to Access Permission for Microphone Use (iOS 10 Feature)

### ISSUE THREAD

**Issue by pprravinn** [jessesquires/JSQMessagesViewController#1724]
Hello Sir, 
 i am Using This Library in my Application where  i have implemented code which automatically reply on user typing and to get output on send button, now i have to implement new iOS 10 Speech.Framework which will allow to take audio inputs and give the text results .. i have to implement this feature on [self.inputToolbar.contentView.leftBarButtonItem] i have implemented speech.framework code in my application it requires 2 permission 1.Speech framework and another is to access 2.Microphone usage  i can access permission for Speech Framework but i enable to access the permission for the Microphone please revert me soon beacuse it perfectly worked on normal view   please reply. 

###General information

- Library version(s): 
- iOS version(s): iOS 10

**Comment by jessesquires** [comment]
Thanks @pprravinn ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
