### ISSUE TITLE
New incoming message hiding behind text toolbar on chat screen 

### ISSUE THREAD

**Issue by ketan2409** [jessesquires/JSQMessagesViewController#1726]
Hi i have implemented JSQMessagesViewController in my project and it's working great but the only issue i am facing is whenever i get a new incoming message, it's hidden behind the new message toolbar on chat screen, how do i fix this issue?
i need to scroll to see that message.

**Comment by alexeyhippie** [comment]
All new messages?

**Comment by ketan2409** [comment]
Yes, if i am chating with someone, new message won't appear automatically
i need to scroll to read those messages.New message are not getting updated.

**Comment by alexeyhippie** [comment]
Did you set automaticallyScrollsToMostRecentMessage to YES?

**Comment by ketan2409** [comment]
Yes i have set     self.automaticallyScrollsToMostRecentMessage = YES;

**Comment by alexeyhippie** [comment]
Ok, then when you get new message, but after you update your data source for messages collection view, do you call
`[self finishSendingMessageAnimated:YES]`?

**Comment by ketan2409** [comment]
no i am not calling this method. Is this the reason why i am facing this issue??
Where shall i use this method??
And i am facing issue while receiving message and not while sending

**Comment by alexeyhippie** [comment]
Sorry, wrong method. I meant this one
`[self finishReceivingMessageAnimated:]`

> Where shall i use this method??
When you get new message, right after update your data source

**Comment by ketan2409** [comment]
No worries, 
ok thanks man, let me check if this works

**Comment by ketan2409** [comment]
Thanks alot @alexeyhippie issue solved. You saved me man :)

**Comment by alexeyhippie** [comment]
Sure, no problem : )

**Comment by jessesquires** [comment]
thanks @alexeyhippie ! 😄
