### ISSUE TITLE
JSQMessages not support iOS 7?

### ISSUE THREAD

**Issue by huynhbao** [jessesquires/JSQMessagesViewController#1727]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by Lucashuang0802** [comment]
I do think they support iOS 7. If you check the deployment target of the ***JSQMessages***, it's `7.0`.

**Comment by jessesquires** [comment]
The current version supports iOS 7.

`v7.x.x` of the library is the last release for iOS 7.

`v8.0` will be iOS 8+
