### ISSUE TITLE
Error when I add Library JSQMessages for project iOS 7

### ISSUE THREAD

**Issue by huynhbao** [jessesquires/JSQMessagesViewController#1729]
Library JSQMessages requires iOS 8 and later in Xcode 7.3.1
I have used JSQMessages **v7.3.2** (with pod command **pod 'JSQMessagesViewController'**), Swift 2.2
Image error here:
http://i.imgur.com/VMBJolR.jpg
Is there a way to run JSQMessages for iOS 7 and later?
Please help me! Thank you!

**Comment by jessesquires** [comment]
Hey @huynhbao 😄 

You can't use dynamic frameworks below iOS 8. This is not specific to JSQMessages.
