### ISSUE TITLE
How to show multiple lines in cellButtomLabel?

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1730]
I tried it with `return NSAttributedString(string: "1st \n2nd")` but with no luck. Even though the height is at 40, only "1st" is shown.
Is this even possible?

**Comment by MacMeDan** [comment]
I believe that you need to set the `numberOfLines` for that label. 

I was able to accomplish it in the demo project by going to 
`cellForItemAtIndexPath`
and adding
`cell.cellBottomLabel.numberOfLines = 0;`
by setting it to 0 it should adjust based on the amount of text entered. Alternatively you can specify how many lines you want but it will cut them off if the text exceeds it. 

![Example Project](https://cloud.githubusercontent.com/assets/6182351/16903913/5841632c-4c48-11e6-86b4-be84fa25feda.png)

**Comment by jessesquires** [comment]
@MacMeDan - we should make `.numberOfLines = 0` the default for all of those labels.

what to submit a PR?

**Comment by MacMeDan** [comment]
Ya I can do that and that is what I was thinking when i looked into this. 😃
