### ISSUE TITLE
Missing JSQSystemSoundPlayer for CocoaPods on Github

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1738]
### General information

- Library version(s): 7.3.3

## Bug report

I have been playing betweem current release version 7.3.3 and develop branch from github. I notice that when changing the library JSQSystemSoundPlayer will be removed.

My pod file is using:
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'

Here is what pod install printed out:

```
Analyzing dependencies
Pre-downloading: `JSQMessagesViewController` from `https://github.com/jessesquires/JSQMessagesViewController.git`, branch `develop`
Removing JSQSystemSoundPlayer
Downloading dependencies
Installing JSQMessagesViewController 7.3.3 (was 7.3.3)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

```

**Comment by nguyenpham** [comment]
Oh, I see. So he has removed it in purpose. However, my app crashed without JSQSystemSoundPlayer even I don't use that library in my code. Will check later.

**Comment by Lucashuang0802** [comment]
@nguyenpham If you are able compile, then I think this issue can be closed. @jessesquires

**Comment by jessesquires** [comment]
Release `7.3.3` != `develop`

What's on `develop` is in-progress work and I would not recommend using it.

`v8.0` of the library will be removing this dependency.

**Comment by jessesquires** [comment]
#1649 has details
