### ISSUE TITLE
[Custom Cells] Inputting buttons and labels 

### ISSUE THREAD

**Issue by Andrew05** [jessesquires/JSQMessagesViewController#1739]
I am trying to create custom bubbles to create tasks with a simple button and a label. The label is for the user to know the task and the button is to check off that they have completed it. 

I have read nearly every issue tagged with [custom cell] and I am still very confused on how to implement this. I have tried multiple ways including creating an xib with a button in it and trying to make a mediaBubble with a view inside it but none of these solutions has worked out.

This is the code that I have 

     class IncomingCustomBubbleView : JSQMessagesCollectionViewCellIncoming {
    
    @IBOutlet weak var button: UIButton!
    
    @IBOutlet weak var view: UIView!
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        NSLog("initWithCoder \(self)")
        NSBundle.mainBundle().loadNibNamed("IncomingCustomBubble", owner: self, options: nil)
        self.addSubview(view)
           }
       }

     class OutGoingCustomBubbleView : JSQMessagesCollectionViewCellOutgoing {
           @IBOutlet weak var button: UIButton!
    
    @IBOutlet weak var view: UIView!
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        NSLog("initWithCoder \(self)")
        NSBundle.mainBundle().loadNibNamed("OutgoingCustomBubble", owner: self, options: nil)
        self.addSubview(view)
           }  
      }

I am linking these to separate xib files with buttons in them.

Any help would be greatly appreciated.

**Comment by MHX792** [comment]
Just curious: did you solve it? If yes, can you share your answer? Would be great!

**Comment by Andrew05** [comment]
@MH792 No I still have not solved this issue yet.

**Comment by jessesquires** [comment]
Thanks @Andrew05 !

You'll also need to register these cells with the collection view, and configure them in `cellForItemAtIndexPath:`

**Comment by NoLiuxin** [comment]
did you solve it? If yes, can you share your answer? Would be great!

**Comment by MHX792** [comment]
@Andrew05 yea, would be great!

**Comment by MHX792** [comment]
@Andrew05 any updates on it? Sharing is caring... ;)

**Comment by jasonwcfan** [comment]
I've found the solution for subclassing `JSQMessagesViewCollectionViewCellIncoming` and `JSQMessagesViewCollectionViewCellOutgoing`. I'm going to annotate @jessesquires 's instructions with my own additions, his in bold. I'm calling the custom subclasses `CustomMessagesCollectionViewCell`, `CustomMessagesCollectionViewCellIncoming` and `CustomMessagesCollectionViewCellOutgoing`, replace them with your own class names as necessary. Also this is in swift but the solution should be the same in Obj-c

1. **You need to provide your own cell subclasses, similar to the library's `JSQMessagesCollectionViewCell`, `JSQMessagesCollectionViewCellIncoming`, `JSQMessagesCollectionViewCellOutgoing`.**

    * `CustomMessagesCollectionViewCellIncoming` and `CustomMessagesCollectionViewCellOutgoing` both inherit from `CustomMessagesCollectionViewCell`
    * For the incoming custom cells, add these three methods and do the same for the outgoing custom cell, replacing "Incoming" with "Outgoing" and `NSTextAlignment.Left` with `NSTextAlignment.Right`. Final class should look something like this: (assuming you haven't made any additional changes to the custom class)

    ```
    class CustomMessagesCollectionViewCellIncoming: CustomMessagesCollectionViewCell {
        override func awakeFromNib() {
            super.awakeFromNib()
            self.messageBubbleTopLabel.textAlignment = NSTextAlignment.Left
            self.cellBottomLabel.textAlignment = NSTextAlignment.Left
        }
    
        override class func nib() -> UINib {
            return UINib(nibName: "CustomMessagesCollectionViewCellIncoming", bundle: nil)
        }
    
        override class func cellReuseIdentifier() -> String {
            return "CustomMessagesCollectionViewCellIncoming"
        }
    }
     ```
    * What I've noticed is that other people were using `NSStringFromClass(self)` to return the class name, however this actually returns the path. i.e. you get `Project.CustomMessagesCollectionViewCellIncoming` rather than `CustomMessagesCollectionViewCellIncoming`, so xcode cannot locate the appropriate nib based on the name if you named your xib without the `Project` qualifier. In this case, it's better to either hard code the name of the class as a string or rename your xib to include your project name before the class name. No idea why Xcode doesn't just handle this automatically

2. **On your `JSQMessagesViewController` subclass, set the following properties according to your classes:**
    - **`outgoingCellIdentifier`**
    - **`outgoingMediaCellIdentifier`**
    - **`incomingCellIdentifier`**
    - **`incomingMediaCellIdentifier`**

    * To be completely clear, this or something like it is what you have to add to the viewDidLoad() method of your `CustomMessagesViewController` class. 
    ```
    self.outgoingCellIdentifier = CustomMessagesCollectionViewCellOutgoing.cellReuseIdentifier()
    self.outgoingMediaCellIdentifier = CustomMessagesCollectionViewCellOutgoing.mediaCellReuseIdentifier()
        
    self.collectionView.registerNib(CustomMessagesCollectionViewCellOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingCellIdentifier)
    self.collectionView.registerNib(CustomMessagesCollectionViewCellOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingMediaCellIdentifier)
        
    self.incomingCellIdentifier = CustomMessagesCollectionViewCellIncoming.cellReuseIdentifier()
    self.incomingMediaCellIdentifier = CustomMessagesCollectionViewCellIncoming.mediaCellReuseIdentifier()
        
    self.collectionView.registerNib(CustomMessagesCollectionViewCellIncoming.nib(), forCellWithReuseIdentifier: self.incomingCellIdentifier)
    self.collectionView.registerNib(CustomMessagesCollectionViewCellIncoming.nib(), forCellWithReuseIdentifier: self.incomingMediaCellIdentifier)
    ```
3. **Register your cell classes/nibs with the collection view and the identifiers above**
    * To do this, you have to first create new xibs for your custom cells. Create a new xib in your project called `CustomMessagesCollectionViewCellIncoming.xib`. View it as source code (Open As -> Source Code) and copy and paste the source code for `JSQMessagesCollectionViewCellIncoming.xib` over. Replace the part `customClass="JSQMessagesCollectionViewCellIncoming">` with `customClass="CustomMessagesCollectionViewCellIncoming" customModule="MyProject" customModuleProvider="target">`. Replace `MyProject` with your project name. Create another xib for your custom outgoing cell and do the same.
4. **Override `-collectionView: cellForItemAtIndexPath:`. Do not call `super`. Since you are providing your own cells, calling `super` will perform a bunch of unnecessary work.**
    * Use `cellForItemAtIndexPath` as you normally would
5. **(Optional) For your model objects, implement `JSQMessageData` or subclass `JSQMessage` and extend to your needs.**

Hopefully this is comprehensive enough to explain how to create your own custom cells with @jessesquires fantastic library, assuming you don't want to create every messages as a media item.

**Comment by jessesquires** [comment]
Thanks @jasonwcfan  ! 👍 💯 

Would you want to submit a PR that adds this to the FAQ?

https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md

**Comment by jasonwcfan** [comment]
Would love to, created pull request adding a link to the above comment in the FAQ.

**Comment by gmansata6290** [comment]
![simulator screen shot 26-sep-2016 6 43 41 pm](https://cloud.githubusercontent.com/assets/12854378/18839039/33853e98-8427-11e6-971e-a17ae0ea455b.png)

I want to create a custom cell (chat bubble) which resembles the generic JSQ Bubble/Cell. I managed to create a simple box as you can see but not able to fit the content inside the chat like bubble. Any advise on how I can do that?

`class MyCustomCellWithButtonsIncomingCell: JSQMessagesCollectionViewCellIncoming
{
    var button : UIButton?
    var msgLbl : UILabel?
    
    override init(frame: CGRect)
    {
        super.init(frame: frame)
        
        self.messageBubbleTopLabel?.textAlignment = NSTextAlignment.Right
        self.cellBottomLabel?.textAlignment = NSTextAlignment.Right
        
        button = UIButton(frame: CGRect(x: 0, y: self.contentView.frame.size.height - 30, width: self.contentView.frame.size.width / 2, height: 30))
        button!.setTitle("Button 1", forState: .Normal)
        button!.backgroundColor = UIColor.purpleColor()
        self.contentView.addSubview(button!)
        
        msgLbl = UILabel(frame: CGRect(x: 0, y: 0, width: self.contentView.frame.size.width, height: self.contentView.frame.size.height - 30))
        msgLbl!.textAlignment = .Center
        msgLbl!.textColor = UIColor.whiteColor()
        msgLbl!.numberOfLines = 0
        msgLbl!.lineBreakMode = .ByWordWrapping
        msgLbl!.backgroundColor = UIColor.orangeColor()
        msgLbl!.sizeToFit()
        self.contentView.addSubview(msgLbl!)
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
    }
    
    override class func cellReuseIdentifier() -> String
    {
        return "MyCustomCellWithButtonsIncomingCell"
    }
    
    override func layoutSubviews()
    {
        msgLbl!.frame = CGRect(x: 0, y: 0, width: self.contentView.frame.size.width, height: self.contentView.frame.size.height - 30)
    }
}`

**Comment by mateo-kozomara** [comment]
Does this approach still work? Im getting just blank white rectangles for custom cells for some reason

**Comment by CJSim** [comment]
@jasonwcfan  Followed your instructions. Just curious about CustomCollectionViewCell. There is no detail instructions provided. If we create CustomCollectionViewCell and inherit it in CustomCollectionViewCellIncoming than how can we able to access         

self.messageBubbleTopLabel.textAlignment = NSTextAlignment.Left
self.cellBottomLabel.textAlignment = NSTextAlignment.Left

Please help me with this. Thanks
