### ISSUE TITLE
Showing tool bar over the screen

### ISSUE THREAD

**Issue by sahabe1** [jessesquires/JSQMessagesViewController#1745]
Please see the error log
-[UIWindow endDisablingInterfaceAutorotationAnimated:] called on <UITextEffectsWindow: 0x17fe1680; frame = (0 0; 320 480); opaque = NO; autoresize = W+H; layer = <UIWindowLayer: 0x17fe19d0>> without matching -beginDisablingInterfaceAutorotation. Ignoring.
![img_4133](https://cloud.githubusercontent.com/assets/1065015/17021917/ae1b3cd2-4f68-11e6-8d75-840c53eb5ffe.PNG)

**Comment by jessesquires** [comment]
Should be fixed on develop by #1063
