### ISSUE TITLE
Keyboard covers messages and some time (rarely) the keyboard is shown on screen but inputToolbar is hidden behind the keyboard.

### ISSUE THREAD

**Issue by firozkhursheed** [jessesquires/JSQMessagesViewController#1746]
- Library version(s): 7.2.0
- iOS version(s): 9.3

## Bug report
1. Keyboard covers messages and 
2. Some time (rarely) the keyboard is shown on screen but inputToolbar is hidden behind the keyboard.

#### Steps to reproduce
1. Go to JSQMessages subclass. Every thing is normal.
2. Tap on textfield of inputToolBar.
3. Hit the back button and segue back (UINavigationController).
4. Again go to JSQMessages subclass this time the keyboard covers the messages with inputToolBar on top on keyboard(rarely inputToolBar goes behind keyboard).

#### Crash log? Screenshots? Videos? Sample project?
![img_0132](https://cloud.githubusercontent.com/assets/4920594/17021866/524c2bd2-4f68-11e6-8526-4345e2086dfe.jpg)
-------------------------------
![img_0134](https://cloud.githubusercontent.com/assets/4920594/17021925/c4ce3e70-4f68-11e6-9f68-e8d11ca1110f.jpg)

I have tried resignFirstResponder in viewWillDisappear, but it does not work.
Thanks.

**Comment by jessesquires** [comment]
Thanks @firozkhursheed ! Please update to `7.3.4` and see if the issue still persists 😄

**Comment by firozkhursheed** [comment]
Updated to 7.3.4 but it doesn't fixed the problem.

**Comment by jessesquires** [comment]
Ah.. how many messages are there? 

Is this the same as #256 ?

**Comment by firozkhursheed** [comment]
I have tried with messages count from 1 to 30 and auto scroll works, the problem come when one popToRootViewControllerAnimated while the textfield of inputToolBar is on focus(keyboard is shown on screen) and comes back to JSQMessages subclass, this time keyboard overlaps some messages (6 one line messages from bottom) as if the keyboard was not supposed to be active. 

If one drags the messages screen to close the keyboard before pop operation and then repeat the above steps and get back to JSQMessages subclass this time keyboard is disabled and the everything is at it's proper place.

**Comment by jessesquires** [comment]
I think this might be fixed on `develop` with the improved keyboard handling.

Would you be able to try that? 

There are some breaking changes, you can check the CHANGELOG: https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CHANGELOG.md#800

**Comment by jessesquires** [comment]
Should be fixed by closing #1063
