### ISSUE TITLE
Media message sometimes keep loading with SDWebImage

### ISSUE THREAD

**Issue by alberttai1** [jessesquires/JSQMessagesViewController#1752]
### General information

- Library version(s): 7.3.4
- iOS version(s): 9.3
- Devices/Simulators affected: iPhone and Simulator both affected 
- Reproducible in the demo project? (Yes/No): Yes if SD web is used 
- Related issues:

### Expected behavior
When sending media images or receiving I should have the images eventually load (there's a loading animation on the images). After it loads, I should easily see it next time I go on without loading since it's cached. 

### Actual behavior
When receiving media images, sometimes it loads right away but sometimes if it tries to load it will load indefinitely. I know it is done downloading because if I trigger a reload of collection view either through messaging something or going back to main view and coming back to the same viewcontroller it will show up. If I close my app and restart it, the pictures I have finished downloading should show up instead it will show up as loading again for indefinitely. It only happens to the ones most recent, the old ones are all okay. 

### Steps to reproduce
- Use SD image to download images for media bubbles
- Send images possibly on a slower internet where it takes more than a few milliseconds to load

### Crash log? Screenshots? Videos? Sample project?
The way I did this was I would receive a message containing a url and I download it and return back a JSQMessage that contains a media bubble. I tried reloading the collectionview at that index or reloading entire collectionview with a completion block in SD web but it ends up with a endless loop. 

I'm not sure if this is currently a fault of SDweb or JSQMessageController. I have tried using Kingfisher as an image caching and downloading with relatively the same results. 

Here's the code:
```swift
    override func collectionView(collectionView: JSQMessagesCollectionView!, messageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageData! {
        let message = self.messages[indexPath.item]
        
        if (message.body!.rangeOfString ("An image https://x.com/uploads/") != nil) {

            let types: NSTextCheckingType = .Link
            
            let detector = try? NSDataDetector(types: types.rawValue)
            
            guard let detect = detector else {
                let JSQTypeMessage = JSQMessage(senderId: message.from, senderDisplayName: message.from, date: message.date, text: message.body)
                
                return JSQTypeMessage
            }
            
            let matches = detect.matchesInString(message.body!, options: .ReportCompletion, range: NSMakeRange(0, message.body!.characters.count))
            
            var stringUrl:NSURL?
            
            stringUrl = matches[0].URL!
            
            let tempImageView = UIImageView(image: nil)
            tempImageView.sd_setImageWithURL(stringUrl, completed: nil)
            
            let photoImage = JSQPhotoMediaItem(image: tempImageView.image)
            
            // This makes it so the bubble can be incoming rather than just all outgoing.
            if !(message.from == self.senderId) {
                photoImage.appliesMediaViewMaskAsOutgoing = false
            }
            
            let message = JSQMessage(senderId: message.from, displayName: self.senderDisplayName, media: photoImage)
            return message
        }
        
        let JSQTypeMessage = JSQMessage(senderId: message.from, senderDisplayName: message.from, date: message.date, text: message.body)
        
        return JSQTypeMessage
    }
```

**Comment by jessesquires** [comment]
Thanks @alberttai1 ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

We can't provide support for `SDWebImage`, only `JSQ` 😊 Sorry!

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)

**Comment by alberttai1** [comment]
Thanks @jessesquires I'll post on there. I just wasn't sure if it was a JSQ problem since it has a loading view for media as well (which I'm not totally sure how to use).

**Comment by abhishekthanvi8** [comment]
@alberttai1 did you solved this issue ever.?

**Comment by alberttai1** [comment]
I believe we did, it's quite fuzzy cause we paused the image sharing feature for the time being

**Comment by abhishekthanvi8** [comment]
any workaround for this? I have wasted 4 days on this issue not getting anywhere  @alberttai1
