### ISSUE TITLE
Video Media Items not playing.

### ISSUE THREAD

**Issue by MacMeDan** [jessesquires/JSQMessagesViewController#1754]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 4.4.3
- iOS version(s): only Tested on 6S+ iOS9.3.2 actual device
- Devices/Simulators affected: Yes
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

## Bug report
  Selecting a Video does not play the video. 
### Expected behavior
 The video would play

### Actual behavior
  The console just logs that a message bubble has been tapped.

### Steps to reproduce
  Run Demo Project select video media item. 

I don't know if this is by design or not. I assume not due to the audio messages working correctly. I also would assume that this feature is not the highest priority. But I figured I would submit this so it could be tracked. It is both the Objective C examples and Swift Example not playing.

**Comment by jessesquires** [comment]
Ha 😄 

Yeah, the videos in the demo are just dummy place holders.

I suppose we could improve this later on, but let's punt on this for now.

**Comment by MacMeDan** [comment]
Awesome thought that might be the case.
