### ISSUE TITLE
The Share.png is missing.

### ISSUE THREAD

**Issue by MacMeDan** [jessesquires/JSQMessagesViewController#1755]
`2016-07-23 14:34:58.882 JSQMessages[35344:1239993] Could not load the "share.png" image referenced from a nib in the bundle with identifier "com.hexedbits.JSQMessages"`

Seams that the share.png image did not make it into the image.assets folder in the project. I assume this would be related to #1719 

Looking further into it it does seem like it is there just inside of the Assets Bundle. But the demo projects are not able to find it.

It happens on all devices and simulators.

**Comment by jessesquires** [comment]
Swift demo project only, I assume? 

The ObjC demo was fine the other day...

**Comment by GianniCarlo** [comment]
I can confirm that ObjC demo is affected too on branch develop

**Comment by MacMeDan** [comment]
Ya as I was looking into it I found the `share.png` in the bundle. Could not find a reason for the error.

**Comment by MacMeDan** [comment]
TIL how to fix this bug :)
