### ISSUE TITLE
date and time don't displayed

### ISSUE THREAD

**Issue by trikiano** [jessesquires/JSQMessagesViewController#1756]
I use the example of Swift. but the cell that displays the date does not appear

thnx

**Comment by jessesquires** [comment]
Thanks @trikiano ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:
