### ISSUE TITLE
swift date and time don't displayed

### ISSUE THREAD

**Issue by trikiano** [jessesquires/JSQMessagesViewController#1758]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
General information

    Library version(s):
    iOS version(s): 9.3
    Devices/Simulators affected: Iphone5
    Reproducible in the demo project? (Yes/No): No
    Related issues:

### Bug information

I use the example of Swift. but the cell that displays the date does not appear

thnx

**Comment by jessesquires** [comment]
@trikiano - the swift demo project has been updated
