### ISSUE TITLE
Some bubbles look squashed in both Obj-C and Swift demo

### ISSUE THREAD

**Issue by GianniCarlo** [jessesquires/JSQMessagesViewController#1761]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): `develop`
- iOS version(s): 9.3.3
- Devices/Simulators affected: iPhone 6s
- Reproducible in the demo project? (Yes/No):  YES

## Bug report
Some bubbles look squashed

### Expected behavior
For all the bubbles with just one line of text to have the same height

### Actual behavior
Some have a reduced height, you can tell too by looking at the avatar which gets cut on top

### Steps to reproduce
Open the demo on either Obj-C or Swift and start typing really short messages

### Screenshot

![img_1843](https://cloud.githubusercontent.com/assets/14112819/17086023/0a72feca-51ad-11e6-8f6f-cfd49285a37e.png)

**Comment by jessesquires** [comment]
hey @GianniCarlo -- i just ran the demo from `master`/`release_7.3` and couldn't reproduce this....

**Comment by GianniCarlo** [comment]
@jessesquires  wops, forgot to mention, branch develop

**Comment by jessesquires** [comment]
👍

**Comment by Lucashuang0802** [comment]
@jessesquires Hmm, I believe it's related to the change I did for #1717. The `NSStringDrawingUsesDeviceMetrics` flag.

**Comment by jessesquires** [comment]
@Lucashuang0802 if we can't find a fix, we should revert and re-open #1717

**Comment by Lucashuang0802** [comment]
@jessesquires Let me see what I can find.

**Comment by rmelian2014** [comment]
Big problem when you remove `NSStringDrawingUsesDeviceMetrics` the issue #1717 is reopen again but with `NSStringDrawingUsesDeviceMetrics` , then is open this issue instead

**Comment by jessesquires** [comment]
Yes. But this is more serious than #1717. If a "fix" causes a regression, then it isn't a fix.

**Comment by Lucashuang0802** [comment]
@rmelian2014 exactly, I will see whether it has other solutions. Otherwise, we would probably revert #1717 since that one affects in an obvious way.
