### ISSUE TITLE
Create Custom Bubble Swift

### ISSUE THREAD

**Issue by RonGafni** [jessesquires/JSQMessagesViewController#1762]
Hey, 

Its not an issue, I'm trying to create new bubble. is it possible? like this: 

<img width="725" alt="screen shot 2016-07-25 at 10 06 38 pm" src="https://cloud.githubusercontent.com/assets/4218260/17113661/5e6148c2-52b4-11e6-9e55-cf8594057346.png">

Hope it ok the way I ask. 

Thank you very much!!

**Comment by Lucashuang0802** [comment]
Duplicate with #1721

**Comment by jessesquires** [comment]
Thanks @RonGafni !

Please see the existing questions about this and the FAQ.

**Comment by apryiomka** [comment]
Hi team, I am trying to implement my custom bubble image. What is the correct image format? I provide custom image, but i get rectangular:
![screen shot 2016-12-01 at 8 59 53 pm](https://cloud.githubusercontent.com/assets/11861671/20823483/2dfee080-b809-11e6-9cb9-a1cc70c43922.png)

**Comment by apryiomka** [comment]
This is the swift code for the image:
`incomingBubble = JSQMessagesBubbleImageFactory(bubbleImage: UIImage(named: "bubble"), capInsets: UIEdgeInsetsZero).incomingMessagesBubbleImageWithColor(UIColor.brownColor())`
