### ISSUE TITLE
JSQMessagesCollectionViewFlowLayoutInvalidationContext.context unavailable in Swift 2.2

### ISSUE THREAD

**Issue by vshahpledge** [jessesquires/JSQMessagesViewController#1763]
#### Expected behavior

Should be able to call JSQMessagesCollectionViewFlowLayoutInvalidationContext.context in swift

#### Actual behavior

Can't call JSQMessagesCollectionViewFlowLayoutInvalidationContext.context in swift

#### Steps to reproduce

Try to paste this into a swift file: 
`let context = JSQMessagesCollectionViewFlowLayoutInvalidationContext.context`
It should give an error

### Screenshots

<img width="1785" alt="screen shot 2016-07-26 at 10 49 26 am" src="https://cloud.githubusercontent.com/assets/11280161/17145145/c02d3fd8-531e-11e6-8831-3bbc4e2433bb.png">

### Other Info: 

Xcode 7.3.1
Swift 2.2

**Comment by jessesquires** [comment]
Thanks @vshahpledge !

This is a syntax error. You need `()`.

```swift
let ctx = JSQMessagesCollectionViewFlowLayoutInvalidationContext.context()
```

**Comment by vshahpledge** [comment]
Whoops! Thanks for getting back to me so quickly. Also, thanks for making this awesome project.

**Comment by vshahpledge** [comment]
Another problem:

<img width="1757" alt="screen shot 2016-07-26 at 11 40 41 am" src="https://cloud.githubusercontent.com/assets/11280161/17146912/e6aee72c-5325-11e6-93b0-81e41a0fb864.png">

**Comment by vshahpledge** [comment]
@jessesquires I thought I tried that before...I got another error after doing what you suggested:

<img width="1757" alt="screen shot 2016-07-26 at 11 40 41 am" src="https://cloud.githubusercontent.com/assets/11280161/17146912/e6aee72c-5325-11e6-93b0-81e41a0fb864.png">

**Comment by vshahpledge** [comment]
@jessesquires  I thought I tried that before...I got another error after doing what you suggested:

<img width="1757" alt="screen shot 2016-07-26 at 11 40 41 am" src="https://cloud.githubusercontent.com/assets/11280161/17146912/e6aee72c-5325-11e6-93b0-81e41a0fb864.png">

**Comment by vshahpledge** [comment]
Can someone please reopen this issue?

**Comment by jessesquires** [comment]
hey @vshahpledge - not sure why the above suggestion doesn't work.

this should:

```
let ctx = JSQMessagesCollectionViewFlowLayoutInvalidationContext()
```

**Comment by vshahpledge** [comment]
@jessesquires Cool, I was following your directions in #1163 when I ran into this issue. 

This is an odd bug, it's happened with one of my core data generated classes as well where the objective-c property doesn't exist on the swift side even though similarly typed properties work just fine. 

Thanks again!
