### ISSUE TITLE
After clicking on send button, keyboard should not be hided (Similar to WhatsApp)

### ISSUE THREAD

**Issue by gmansata6290** [jessesquires/JSQMessagesViewController#1766]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

### Crash log? Screenshots? Videos? Sample project?

How should I prevent keyboard being hided after sending the message?

**Comment by jessesquires** [comment]
Thanks @gmansata6290 ! :smile:

I don't understand what you mean.

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:

**Comment by gmansata6290** [comment]
@jessesquires After typing my message when I click on send button on JSQMessageViewController the keyboard automatically gets hided so I just want to prevent this behaviour. I don't want to hide keyboard after sending a message. How can I prevent or what is the better approach to do that?

Library version(s): 7.3.4
iOS version(s): 8.0 or above
Devices/Simulators affected: yes both
Reproducible in the demo project? (Yes/No): yes
Related issues: Keyboard

**Comment by jessesquires** [comment]
@gmansata6290 -- there must be something wrong in your implementation. pressing the send button in the demo does not dismiss the keyboard...

**Comment by gmansata6290** [comment]
Thanks @jessesquires I got the it.
