### ISSUE TITLE
is it possible to add a Link Preview ?

### ISSUE THREAD

**Issue by sreeji44** [jessesquires/JSQMessagesViewController#1769]
Hi first of this is just awesome Library.

When i add Link to message it default the Link is underlined and while clicking it goes to appropriate pages. But While adding Link is possible to add Link Preview of that link?.
Hope you understand :)

**Comment by jessesquires** [comment]
Thanks @sreeji44 ! 😄 

Right now this is not supported, but you could add this yourself by implementing a custom media item.
