### ISSUE TITLE
Can't Seem to Resize a subclass of JSQPhotoMediaItem after image cache download in JSQMessagesViewController

### ISSUE THREAD

**Issue by saqibdb** [jessesquires/JSQMessagesViewController#1770]
I have a custom subclass of JSQPhotoMediaItem, I am using a UILabel and UIImageView inside a UIView for custom message bubble view. Now I am also caching images download using kingFisher. I can set the size in the mediaViewDisplaySize() when constructor for that is called, but I need to call this again when image cache is done so that the view is adjusted with size of the image after the image download, just like this :
![screenshot at jul 29 08-51-39](https://cloud.githubusercontent.com/assets/5718485/17239988/c26706a2-5581-11e6-84f6-ff4e29a2d37c.png)
But the problem is I just cant seem to recall the mediaViewDisplaySize() to resize the bubble, so i called the constructor again but now I cannot seem to change the frame size for the bubble view, here is the screenshot :
![screenshot at jul 29 08-54-31](https://cloud.githubusercontent.com/assets/5718485/17239998/cd8e526a-5581-11e6-9880-8a00e5f058d1.png)
My problem is I need to call mediaViewDisplaySize() after image cache is completed and I also need to somehow change the frame of the bubble on runtime which is not being done with this code
`override func mediaViewDisplaySize() -> CGSize {
    if mainImage == nil {
        return backgroundView.frame.size
    }
    let max:CGFloat = 230.0
    let width = mainImage.size.width
    let height = mainImage.size.height
    if width < height{
        return CGSize(width: max * width / height, height: max)
    }else{
        return CGSize(width: max, height: max * height / width)
    }`

**Comment by jessesquires** [comment]
Thanks @saqibdb ! 😄 

I think  #842 has your answer.
