### ISSUE TITLE
How can I resize the view?

### ISSUE THREAD

**Issue by VergaraF** [jessesquires/JSQMessagesViewController#1771]
I would like to add a label on top of my screen, but it seems that the label is right under the view. I tried modifying view's frame to move it few pixels down, with no luck.
How can I achieve such thing? 

Thank you!

**Comment by jessesquires** [comment]
Thanks @VergaraF ! 😄 

See the following: http://cocoadocs.org/docsets/JSQMessagesViewController/7.3.4/Classes/JSQMessagesViewController.html#//api/name/topContentAdditionalInset
