### ISSUE TITLE
Keyboard dragging to close on iOS8 does not work as expected

### ISSUE THREAD

**Issue by luukd** [jessesquires/JSQMessagesViewController#1772]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.3.4
- iOS version(s): iOS 8.4, iOS 8.3 (not tested on other 8.x versions)
- Devices/Simulators affected: iPhone 5 simulator, iPhone 4s device
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: #1181 (

## Bug report
Dragging down the on screen keyboard doesn't work as expected on iOS 8. When you start dragging, the keyboard stays completely visible until you reach the bottom of the screen. It disappears at once when reaching the bottom.

### Expected behavior
The expected behaviour would be that the top border of the keyboard would move along with your finger as you drag down.

### Actual behavior
The keyboard doesn't move at all until you reach the bottom of the screen.

### Steps to reproduce
1. Open chat in demo app on iOS 8
2. Tab the textfield to activate the on screen keyboard
3. Try to drag the key board down to the bottom of the screen

### Crash log? Screenshots? Videos? Sample project?
iOS 8 (keyboard should follow cursor):
![jsqmessagesviewcontroller_keyboard_ios8 4](https://cloud.githubusercontent.com/assets/1858881/17243728/91f21974-557e-11e6-9d88-2ba6528ee65b.gif)

iOS 9 (expected behaviour):
![jsqmessagesviewcontroller_keyboard_ios9 3](https://cloud.githubusercontent.com/assets/1858881/17243734/9712b756-557e-11e6-951f-e064d9212194.gif)

**Comment by jessesquires** [comment]
Thanks @luukd ! 😄 

/cc: @Lucashuang0802 -- can we repro this?

**Comment by Lucashuang0802** [comment]
Hey @luukd @jessesquires, I am actually not able to replicate the problem. I try iPhone5 and iPhone6 on iOS 8.4. Perhaps it's the misunderstanding of our fingers and the touch screen? 😄 
 
![iphone5-480](https://cloud.githubusercontent.com/assets/3754490/17258719/18b46f22-557d-11e6-9f41-331df3fd5cbe.gif)
![iphone6-480](https://cloud.githubusercontent.com/assets/3754490/17258720/18b82fa4-557d-11e6-9b06-2c5ae30cd396.gif)

**Comment by jessesquires** [comment]
👍

**Comment by luukd** [comment]
@Lucashuang0802 Are you sure that you've tested with iOS 8.4? Your iPhone 5 simulator screenshot says iOS 9.3 in the title bar and I think the iPhone 6s simulator in your second screenshot cannot run iOS 8.4.

I did some additional testing and found out that the issue only occurs on the release_7.3 branch. It's working fine on the develop branch.

**Comment by Lucashuang0802** [comment]
Must be my mistake, thanks for the catch. Glad you point it out.

**Comment by jessesquires** [comment]
Thanks @luukd !

Since this isn't super critical, marking as a fixed bug for v8.0
