### ISSUE TITLE
My app keeps crashing when I add Photo Message

### ISSUE THREAD

**Issue by thehorbach** [jessesquires/JSQMessagesViewController#1773]
Hello.

I build a chat app using JSQMessagesViewController powered by Firebase. My text bubbles are being are working perfectly fine, however after I add a photo message and it has been displayed, I try to add a new text message and the app crashes on "finishSendingMessage()".

Please help :)

![screen shot 2016-07-29 at 14 12 21](https://cloud.githubusercontent.com/assets/16654641/17265121/1445cef8-55a1-11e6-9d00-bdfe918d9e34.png)

![screen shot 2016-07-29 at 13 58 14](https://cloud.githubusercontent.com/assets/16654641/17265122/145be030-55a1-11e6-8316-eefdaa81fa3d.png)

![screen shot 2016-07-29 at 13 56 57](https://cloud.githubusercontent.com/assets/16654641/17265123/1461d026-55a1-11e6-911d-0f33d3cfd70b.png)

**Comment by jessesquires** [comment]
Thanks! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)

**Comment by PrithiviMelio** [comment]
I too having this problem
