### ISSUE TITLE
How to reduce space between cells?

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1776]
Hi, 
I would like messages from the same sender to be closer to each other. Even if the sublabel is hidden the space is too big IMO. Since the `collectionView` is not section based, is this even possible?

**Comment by Lucashuang0802** [comment]
Perhaps you can take advantage of this delegate method: `- (CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionView *)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section`

Possible duplicate issue: #978
