### ISSUE TITLE
Bubble cut off when send text

### ISSUE THREAD

**Issue by azharfauzandz** [jessesquires/JSQMessagesViewController#1779]
I have a problem when i send a new message. The buble is cutted off. I used custom media cell  from [https://github.com/jessesquires/JSQMessagesViewController/issues/1380]

this is the screenshot 

<img width="321" alt="screen shot 2016-08-01 at 1 34 59 pm" src="https://cloud.githubusercontent.com/assets/17307673/17285849/9c59b444-57ef-11e6-99f0-4961b44b9e73.png">

anyone can help me? Thanks

**Comment by Lucashuang0802** [comment]
@azharfauzandz Can you provide more context how to get to this point like codes or can you replicate it from the demo app? That will be helpful.

**Comment by jessesquires** [comment]
Thanks @azharfauzandz !

It looks like you've implemented custom bubbles, so we can't provide much support here.

You can using the `JSQMessagesBubbleSizeCalculating` API to adjust your bubble sizes.
