### ISSUE TITLE
MessageBubbleTopLabel

### ISSUE THREAD

**Issue by grosch** [jessesquires/JSQMessagesViewController#1781]
Is there a way to make the messageBubbleTopLabel be left aligned on the screen instead of centered for the bubbles on the left side of the screen?

**Comment by jessesquires** [comment]
Hey @grosch 😄 

You can do this by customizing the cell in `cellForItemAtIndexPath: ..`

**Comment by grosch** [comment]
OK, I was confused by having to use the attributedTextForCell_LabelAtIndexPath methods.  I guess I can just nuke those entirely :)

**Comment by jessesquires** [comment]
Ah yes -- sorry for the confusion 😊 

v8.0 will make this more clear, hopefully

**Comment by Spettacolo83** [comment]
I tried this:
`cell.messageBubbleTopLabel.textAlignment = NSTextAlignmentRight; // For my messages`
But does not work!
Any suggestion?
