### ISSUE TITLE
Hello! Prompt please: I am in my application that would create a chat room, i using wonderful framework "JSQMessagesViewController". But I have a problem

### ISSUE THREAD

**Issue by ZvOlCuOk2009** [jessesquires/JSQMessagesViewController#1782]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by jessesquires** [comment]
Thanks! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:

**Comment by ZvOlCuOk2009** [comment]
Hello! I use FireBase database and try to create an interface, as demonstrated in the test video. I have a list of contacts, I want to be able to when you click the "chat" button on the contact cell, move into messenger and obschatsya with this contact. If i click on the next button contact, it has already opened a messenger with the current contact. And I Now all contacts write messages to one messenger
(video below
[triper test.zip](https://github.com/jessesquires/JSQMessagesViewController/files/399028/triper.test.zip)
)

**Comment by ZvOlCuOk2009** [comment]
Hi Jesse!

Please tell me! I use to create chat a framework YSKMessazhesvievKontroller and Firevase.I need to build in such a way that the functionality would be when you click on another cell I moved the conversation with that friend. If I click on the cell next friend, respectively, I turn to the conversation with the second friend. Tell me how can I implement such functionality? Because I have a user and all of his friends wrote in a chat room and all can read and I want to do that all could obschatsya separately… As shown in the screen shots..

**Comment by ZvOlCuOk2009** [comment]
I'm sorry, I use frameworks : JSQMessageViewController and FireBase...
