### ISSUE TITLE
Chat bubble doubling when swiping right to go back to the main view.

### ISSUE THREAD

**Issue by jheazzzar** [jessesquires/JSQMessagesViewController#1783]
Please check this video, It's all here. https://www.youtube.com/watch?v=nY-Mgw5FtxU&feature=youtu.be

**Comment by Lucashuang0802** [comment]
@jheazzzar Can you post the code you wrote how you add message data? What I can think of is the logic of adding message data sits at either `viewWillAppear:` or `viewDidAppear:`. That's how you can this strange behavior. Let us know. 😄

**Comment by jheazzzar** [comment]
I referred to this tutorial by David East from firebase. 

https://www.raywenderlich.com/122148/firebase-tutorial-real-time-chat
