### ISSUE TITLE
collection view display error when I use JSQMessagesViewController as a navigationCotroller's rootViewController

### ISSUE THREAD

**Issue by Wu-Dong-Hui** [jessesquires/JSQMessagesViewController#1785]
Like the code below, something weird happen

```
    let chat = ChatController()（ChatController is a subclass of JSQMessagesViewController）
    chat.hidesBottomBarWhenPushed = true
    navigationController?.pushViewController(chat, animated: true)
```

![simulator screen shot 2016 8 5 1 46 56](https://cloud.githubusercontent.com/assets/8233494/17427425/216475d6-5b13-11e6-838b-ea66a61cf23d.png)
**# As you see, some cells were covered by navigation bar, but when the textView in the inputToolBar begin editing, it gonna be ok and never be wrong until the view controller be destroyed, what I missed?  Thanks!**

It's ok by the below code:)

```
    let chat = ChatController()（ChatController is a subclass of JSQMessagesViewController）
    let nav = UINavigationController(rootViewController: chat)
    presentViewController(nav, animated: true, completion: nil)
```

**Comment by Lucashuang0802** [comment]
Hey @Wu-Dong-Hui, weCan't address the problem by seeing this code. Can you give us more information? Possible issue I can think of: http://stackoverflow.com/questions/18967859/ios7-uiscrollview-offset-in-uinavigationcontroller 😄

**Comment by Wu-Dong-Hui** [comment]
Thanks for @Lucashuang0802  , but I had tried the solution of issue on stackoverflow you provide, it did not work. And I almost did nothing in **ChatController**（ChatController is a subclass of JSQMessagesViewController）but only added some cells.

You can see the SwiftExample you provided ：
if I modify code like this（in InitalTableViewController）, the same problem occur
![123](https://cloud.githubusercontent.com/assets/8233494/17546501/1894309e-5f15-11e6-977e-8322ceeca663.png)

![simulator screen shot 2016 8 10 3 56 35](https://cloud.githubusercontent.com/assets/8233494/17546559/608fcd36-5f15-11e6-808d-fd9b936871e5.png)

**Comment by Lucashuang0802** [comment]
@Wu-Dong-Hui, I think this issue is replicable from sample app. Thanks!

**Comment by MacMeDan** [comment]
There is a pull request to fix this but the fix is 
`override func viewDidLayoutSubviews() {
        if let navigationBarRect = self.navigationController?.navigationBar.frame {
            let y = navigationBarRect.size.height + navigationBarRect.origin.y
            self.collectionView?.contentInset = UIEdgeInsetsMake( y, 0, 0, 0)
        }
    }`

**Comment by Wu-Dong-Hui** [comment]
Thanks, @MacMeDan , I resolve it refer to your suggestion


override func viewDidLayoutSubviews() {
        if let navigationBarRect = self.navigationController?.navigationBar.frame {
            let top = navigationBarRect.size.height + navigationBarRect.origin.y
            let bottom = inputToolbar.frame.size.height
            self.collectionView?.contentInset = UIEdgeInsets(top: top, left: 0, bottom: bottom, right: 0)
            self.collectionView?.scrollIndicatorInsets = UIEdgeInsets(top: top, left: 0, bottom: bottom, right: 0)
        }
    }

**Comment by Lucashuang0802** [comment]
I change `self.navigationController.navigationBar.translucent` to `NO` in `viewDidLoad` and it's working now. It's the iOS 7 that made the navigation bar translucent and its default value is `YES`.

**Comment by jessesquires** [comment]
👍

**Comment by jessesquires** [comment]
(didn't mean to close, sorry)

**Comment by jessesquires** [comment]
This will probably be fixed by #1601

**Comment by wayne1203** [comment]
Thank you @Wu-Dong-Hui 
The code it's work to fix the problem. But I got another problem

![noscrolltobottom](https://cloud.githubusercontent.com/assets/8578341/19885707/086eadb6-a05b-11e6-944c-e82f0d0deb15.gif)

I used "finishSendingMessage" / "finishReceivingMessage" when message received or sent
Only the last message can scroll to the bottom

Sorry for my bad English..
Thank you

**Comment by wayne1203** [comment]
I used the code provided by @MacMeDan (viewDidLayoutSubviews)   I got some problem in scrolling #1886

**Comment by royanlea** [comment]
@ Lucashuang0802 , Thanks, I fix it in your way.

**Comment by fareast555** [comment]
I'm sure this is out there somewhere, but for me, using the additionalContentInset property listed in the .h file of the JSQMessagesViewController did the trick.

    CGFloat insetHeight = self.navigationController.navigationBar.frame.size.height + 40;
    self.additionalContentInset = UIEdgeInsetsMake(insetHeight,0,0,0);

LOVE this messaging view controller, by the way. Building it into an app now and it works insanely well. Can't thank you enough, JS! Beers are on me if you ever make it to Bangkok!

**Comment by jessesquires** [comment]
Thanks @fareast555 ! 💯 

Going to close this as resolved based on the answer from @fareast555.

**Comment by fareast555** [comment]
Glad I could help. One tiny thing for people who might come across this thread who are still using the earlier version ~> 7.3.4 -- not sure if the additionalContentInset property is on the older version not. If not, then change that version in your cocoa pod file to the one in the FAQ: 

pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'

This newest development branch actually has a  TON of features beyond what was on ~> 7.3.4

**Comment by nebillo** [comment]
This is to provide an update on this issue, as I believe it's still valid in the last dev branch.
None of the above solutions proposed are real solutions but just workaround:

- Setting the additionalContentInsets property to the same value of the top layout guide, will cause the content on screen to have a double merging once the keyboard comes up. This should always be kept at zero (unless you need to apply an offset).
- Setting the navigation bar to opaque will do the trick but this comes with the cost of introducing a UI inconsistency in the app, which for our needs we can't consider a solution.

After a little digging, we found the issue was about the collection view contentInset property not being set to follow the system value.
A workaround for this issue was to override the following method and discard any extra top margin so that we could leverage the value set by UIKit.
`- (void)jsq_setCollectionViewInsetsTopValue:(CGFloat)top bottomValue:(CGFloat)bottom
{
    // overriding this method to fix an issue with super class not setting correct top offset for collection view.
    // the system automatically sets the top margin for the collection view, so we need to make sure we always use that.
    UIEdgeInsets insets = UIEdgeInsetsMake(self.collectionView.contentInset.top, 0.0f, bottom, 0.0f);
    self.collectionView.contentInset = insets;
    self.collectionView.scrollIndicatorInsets = insets;
}
`

Unless you need to support an extra top layout margin, this will work just fine for most of the needs.
In my opinion the current implementation of the SDK is not supporting this behaviour correctly, so instead of shipping broken code I would suggest removing the capabilities of adding a custom content inset unless someone can provide a better implementation for this.

**Comment by BesatZardosht** [comment]
Finally I found a better solution for this issue:

```
- (void)jsq_updateCollectionViewInsets
{
    CGFloat topHeight = (self.navigationController) ? self.navigationController.navigationBar.frame.size.height + 20: self.topLayoutGuide.length;
    [self jsq_setCollectionViewInsetsTopValue:topHeight + self.topContentAdditionalInset
                                  bottomValue:CGRectGetMaxY(self.collectionView.frame) - CGRectGetMinY(self.inputToolbar.frame)];
}
```

**Comment by Wu-Dong-Hui** [comment]
thanks




On 07/07/2017 02:38, Besat Zardosht wrote:

Finally I found a better solution for this issue:

- (void)jsq_updateCollectionViewInsets
{
    CGFloat topHeight = (self.navigationController) ? self.navigationController.navigationBar.frame.size.height + 20: self.topLayoutGuide.length;
    [self jsq_setCollectionViewInsetsTopValue:topHeight + self.topContentAdditionalInset
                                  bottomValue:CGRectGetMaxY(self.collectionView.frame) - CGRectGetMinY(self.inputToolbar.frame)];
}
