### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by lijiee** [jessesquires/JSQMessagesViewController#1789]
In my APP Its have group chat and single chat ,when I watched old chat history in group room ,the cell is dismiss,but in single chat room no this program

**Comment by MacMeDan** [comment]
is it possible to add a Video of this happening so we can more fully understand what you are describing?
 You can easily record your phones screen by 
1. Plugging it into your mac opening the application 'Quick Time Player'  
2. Create a new Screen recording
3. Select your phone as the screen source by clicking the small down arrow next to the record button
![ScreenShot of what I am talking about](https://cloud.githubusercontent.com/assets/6182351/17633632/80f402c8-608b-11e6-8e3e-6b8167fa3a3b.png)

If that is not possible if you run the simulator and press (Command⌘ + Shift⇧ + S) it will take screen shots of the simulator. Add those to this issue with descriptions and we will see if we can help.

That will help us help you. Thanks for your help. 😼

**Comment by Lucashuang0802** [comment]
Thanks! 😄

Please provide all the information in the issue template so we can help! 
And don't forget to read our contribution guidelines. 😊
