### ISSUE TITLE
insert another type of bubble programatically (System message bubble)

### ISSUE THREAD

**Issue by tunidev** [jessesquires/JSQMessagesViewController#1794]
- [X] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.3.4
- iOS version(s): 9
 
### Expected behavior

 User can insert a third type of bubble programatically. We have incoming and outcoming bubble. But I need to insert at some point another type of bubble programatically. a system message bubble. the use case will be when the user receive a call or miss a call from the other user I add a bubble in the chat conversation. Please see the attachment from Facebook. Any suggestion from where to start and what should I change in the code ? 

![facebook](https://cloud.githubusercontent.com/assets/4885143/17649896/b82f2a96-623f-11e6-9b50-31465248181a.png)

**Comment by jessesquires** [comment]
Thanks @tunidev !

This feature is being tracked at #321 and is planned for the 8.0 release.
