### ISSUE TITLE
Create several separate conversations

### ISSUE THREAD

**Issue by ZvOlCuOk2009** [jessesquires/JSQMessagesViewController#1797]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by ZvOlCuOk2009** [comment]
Please! I'm trying to create an application in which there is a table of user's friends. User by clicking on friend cell, must move to the conversation with that friend is. When you click on the cell next friend, the user must move the conversation already with the second friend. I now have all users write in a common database, where all can read the message. I use the framework and JSQMessagesViewController and FireBase.
 Prompt as me identify the conversations?  Screenshots attach to greater understanding of the problem

Thanks!

![2016-08-15 10 07 31](https://cloud.githubusercontent.com/assets/11560122/17693308/d5fd2308-63a6-11e6-9a16-baace2c786cb.png)
![2016-08-15 10 07 58](https://cloud.githubusercontent.com/assets/11560122/17693307/d5f8df00-63a6-11e6-8932-6ad1c9cac194.png)

**Comment by ryantan** [comment]
JSQMessagesViewController deals with presenting your messages, it does not manage how you organise your message data. To achieve what you have in mind, think of how you can feed different messages to the controller when viewing different conversations.

Specifically, the functions feeding messages to the controller and the functions delivering new messages to fierbase needs to be aware of which conversation the user is interacting with.

**Comment by jessesquires** [comment]
Thanks @ryantan ! 👍

**Comment by ZvOlCuOk2009** [comment]
if I create a conversation based on the two user IDs, I can achieve this?
