### ISSUE TITLE
Custom bubble with UIBezierPath size

### ISSUE THREAD

**Issue by RonGafni** [jessesquires/JSQMessagesViewController#1798]
### General information
- Library version(s): 7.3.4
- iOS version(s): 9.3
- Devices/Simulators affected: iPhone 6s
- Reproducible in the demo project? (Yes/No): 
- Related issues:

Hey, I'm trying to create a bubble with three corner radius.

create the corner radius and apply to textview:

```
    let path: UIBezierPath!

    if fetchedMessage.submitted_by != senderId {

         path = UIBezierPath(roundedRect: customCell.textView.bounds, byRoundingCorners: [.TopLeft,.BottomLeft,.BottomRight], cornerRadii: CGSize(width: 8,height: 8))

        customCell.textView.backgroundColor = UIColor().hexColorString(GOMessageGreen)

    }else{
        path = UIBezierPath(roundedRect: customCell.textView.bounds, byRoundingCorners: [.TopRight,.BottomLeft,.BottomRight], cornerRadii: CGSize(width: 8,height: 8))
        customCell.messageBubbleContainerView.backgroundColor = UIColor().hexColorString(GOMessageBlue)


    }


    let maskLayer = CAShapeLayer()
    maskLayer.path = path.CGPath
    maskLayer.frame = customCell.bounds;

    customCell.textView.layer.mask = maskLayer
```

return nil to bubble image: 

`incomingBubbleImageView = nil
        outgoingBubbleImageView = nil`

and this is what i get: 

![img_3695](https://cloud.githubusercontent.com/assets/4218260/17735605/db6139c0-648b-11e6-8a8f-aeac7e1d93ae.PNG)

(for the message below its contain a lot of "check" word....)

**Comment by RonGafni** [comment]
Someone? Please..

**Comment by eliburke** [comment]
@RonGafni You didn't ask a question. And it looks like you succeeded in creating a bubble with a three corner radius! 😄 

If I assume your complaint is about the alignment of the text inside your bubble, you can try adjusting the insets. In ObjectiveC they are
```
    UIEdgeInsets bubbleTextInsets = UIEdgeInsetsMake(3, 6, 5, 2);
    self.collectionView.collectionViewLayout.messageBubbleTextViewTextContainerInsets = bubbleTextInsets;
    UIEdgeInsets bubbleFrameInsets = UIEdgeInsetsMake(0, 0, 0, 0);
    self.collectionView.collectionViewLayout.messageBubbleTextViewFrameInsets = bubbleFrameInsets;
```

**Comment by RonGafni** [comment]
Not working..

**Comment by RonGafni** [comment]
Anyone?

**Comment by eliburke** [comment]
@RonGafni I'm happy to try and help but you are going to have to meet half way. You did not clarify your question, and you didn't bother to provide feedback on what happened when you changed the insets? Did it do nothing? Did it change but not the way you wanted? Nobody here wants to play 20 questions.
What have you tried so far? Have you debugged into the library's layout code? Can you use images instead of doing it with a mask?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
