### ISSUE TITLE
Bubble with extra bottom empty space

### ISSUE THREAD

**Issue by kallahir** [jessesquires/JSQMessagesViewController#1799]
I'm using the lib in a Swift project and I saw that in the Objective-C example, that comes with the lib, the problem is also present.

I'm simulating the error in iPhone 6s simulator and cellphone and it's the same on both.

![bug](https://cloud.githubusercontent.com/assets/4400692/17762816/4dda4466-64ea-11e6-9644-1be68e936a63.png)
![bug_exemplo](https://cloud.githubusercontent.com/assets/4400692/17762814/4da3cd6e-64ea-11e6-93e9-c91c2844237a.png)

If you want to reproduce all you have to do is send a message with more than 1 line as seen in the images above.

The strange thing is when I move the view the spaces disappear.

Does anyone know how to help me?

EDIT: This bug was somehow inserted from one version to the other, I had an example project here with an older version of the lib that the senderId was still an attribute and the problem wasn't present. The version is from december 2014.

**Comment by kallahir** [comment]
I did some tests and when I put an observer to the keyboard with the following code:

```
        @objc private func keyboardUp(notification: NSNotification){
        let userInfo:NSDictionary = notification.userInfo!
        let keyboardFrame:NSValue = userInfo.valueForKey(UIKeyboardFrameEndUserInfoKey) as! NSValue
        let keyboardRectangle = keyboardFrame.CGRectValue()
        self.collectionView?.contentInset.bottom = keyboardRectangle.height + 2.0
        
        dispatch_async(dispatch_get_main_queue(), {
            self.scrollToBottomAnimated(false)
            self.collectionView?.collectionViewLayout.invalidateLayout()
        });
    }
```

I'm able to avoid this empty space problem and I already move they screen according to the keyboard correctly, but I start getting the following error:

`
2016-08-21 02:23:01.347 Msger[1126:476300] -[UIWindow endDisablingInterfaceAutorotationAnimated:] called on <UITextEffectsWindow: 0x125e58c70; frame = (0 0; 375 667); opaque = NO; autoresize = W+H; layer = <UIWindowLayer: 0x125e56b50>> without matching -beginDisablingInterfaceAutorotation. Ignoring.
`

I saw that someone else reported this problem but what is happening to me is that when i scroll up fast the view kind of broke and scrolls down automatically and I get the error in the console output.

The other thing that I noticed that is happening and isn't just in my app but in the example app as well is that when I have a message with just one line the render occurs smooth but when it has more than one line it flashes and looks like its rendering everything again.

I hope that my investigation helps!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
