### ISSUE TITLE
How to increase font of individual messages?

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1800]
Hi,
like WhatsApp I would like to increase the font size when there is only one emoji sent. My code:

            let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
            
            if message.text.isEmoji {
                cell.textView?.font = UIFont.systemFontOfSize(60)
            }

            return cell

This is what it looks like: 

![screen shot 2016-08-23 at 13 38 36](https://cloud.githubusercontent.com/assets/12123471/17889050/f11656ce-6936-11e6-87ef-85aafe822d29.png)

Apparently the size calculation is not correct. How to fix this?

**Comment by jessesquires** [comment]
Hey @MHX792 ! 😄 

Unfortunately, this isn't completely supported by default. You'll need to:

1. override `cellForItemAtIndexPath:` (like you've done above)
2. implement your own `JSQBubbleSizeCalculator` to adjust the bubble sizes for your emoji cells.

**Comment by MHX792** [comment]
Thanks for you answer @jessesquires!

Can you give me any hints on how to use `JSQMessagesBubbleSizeCalculator`? The [docs](http://cocoadocs.org/docsets/JSQMessagesViewController/7.3.0/Classes/JSQMessagesBubblesSizeCalculator.html) are unfortunately quite unclear about this.

**Comment by jessesquires** [comment]
Ah, you can provide your own `SizeCalculator` object by conforming to the protocol:

http://cocoadocs.org/docsets/JSQMessagesViewController/7.3.0/Protocols/JSQMessagesBubbleSizeCalculating.html
