### ISSUE TITLE
How to use latest version of JSQSystemSoundPlayer pod

### ISSUE THREAD

**Issue by itman85** [jessesquires/JSQMessagesViewController#1802]
I used pod JSQMessagesViewController and when i check pod out dated, i saw that 
`- JSQSystemSoundPlayer 2.0.1 -> 2.0.1 (latest version 4.4.0)`

Thanks.

**Comment by jessesquires** [comment]
Hi @itman85 ! 😄 

That's right, JSQMVC uses an older version of JSQSystemSoundPlayer — there's no functional differences between `2.0.1` and `4.4.0`, just some renaming/refactoring of the public API.

JSQMVC 8.0 will fix this.
