### ISSUE TITLE
Changing position of inputToolBar to same position where it stays when keyboard is up.

### ISSUE THREAD

**Issue by mukul3062** [jessesquires/JSQMessagesViewController#1803]
I want to add smileys popover at the same position where the keyboard stay when the keyboard is up. I read the issue #94 but they give the alternate solution. I am adding one popover smiley.

![simulator screen shot aug 25 2016 11 09 53 am](https://cloud.githubusercontent.com/assets/14835141/17958097/b22aa404-6ab4-11e6-96e6-7d5810669946.png)

**Comment by jessesquires** [comment]
Thanks @mukul3062 ! 😄 

What exactly is your question? 😅

**Comment by mukul3062** [comment]
First thing:- I want to change the position of inputToolBar. So that when I open the smiley popover then inputToolBar goes up and smileys popOver lies below that inputToolBar. Formally, I want to change the keypad with my popOver smiley.

Second thing:- I also don't want to hide the messages behind the popOver. 

Anyway, great work by you.
Thank you.

**Comment by jessesquires** [comment]
>I want to change the position of inputToolBar 

If you look at `JSQMessagesViewController.m`, you should be able to override the methods that change the frame.

> I want to change the keypad with my popOver smiley.

To my knowledge, this would require a custom keyboard extension.

>  I also don't want to hide the messages behind the popOver.

Similarly, you'll want to override the `collectionView.contentInsets` when the keyboard appears.

**Comment by mukul3062** [comment]
Thanks
