### ISSUE TITLE
Change Font of textView in JSQMessagesCellTextView

### ISSUE THREAD

**Issue by hoanganhbk94** [jessesquires/JSQMessagesViewController#1804]
I want to custom font of textview in message. Detail,  I want change white color to red color. Help me!!!

**Comment by mukul3062** [comment]
If you want to change the font of text in bubble then try this  `self.collectionView?.collectionViewLayout.messageBubbleFont = UIFont (name: "LDFComicSans", size: 12)!`

**Comment by mukul3062** [comment]
For changing text font in input textView use this `self.inputToolbar.contentView?.textView?.font = UIFont (name: "LDFComicSans", size: 12)!`

**Comment by jessesquires** [comment]
Thanks @mukul3062 ! 😄

**Comment by mukul3062** [comment]
Welcome jessesquires, You are great :smile:. Great work. Please help me on issue #1803 if u get time.

**Comment by hoanganhbk94** [comment]
@mukul3062 @jessesquires thanks for your help but i want to change text color instead of terxt font. Help me!!!

**Comment by jessesquires** [comment]
You can do this by overriding `cellForItemAtIndexPath:` 😄
