### ISSUE TITLE
black screen visible as you drag keyboard down to dismiss

### ISSUE THREAD

**Issue by JustinM1** [jessesquires/JSQMessagesViewController#1805]
![Uploading JSQMessage.png…]()
![Uploading JSQMessage.png…]()

Using xcode 8 beta, swift 3, on physical 5S device with up to date ios 9 version. 

when you are dragging down to dismiss keyboard, the collection view stays with the keyboard but the collectionView is blocked by a black screen the size of the keyboard when it is up. Also, the inputToolbar stays in the same position. Any way to remove the black screen so it looks cleaner as you dismiss keyboard?  I tried attaching an image but was having some issues so I hope its visible

thanks!

**Comment by JustinM1** [comment]
I was able to figure out what was causing the issue. I made a test project and replicated it on there as well. Anytime I had my VC conform to JSQMessageKeyboardControllerDelegate, even if I didn't set the keyboardcontroller delegate = self, I would run into the issues. I don't know why I'm having trouble uploading images but I was able to replicate on both projects by simply adding the JSQMessagesKeyboardControllerDelegate to my VC. With or without assigning myself as delegate and with or without adding code inside the keyboardDidChangeFrame function.

**Comment by Lucashuang0802** [comment]
Hey, @JustinM1. I think `JSQMessageKeyboardControllerDelegate` is removed from the latest release. `develop` branch as well. Can we know which version of the library are you using? That will be helpful for us to address the issue. 😃

**Comment by JustinM1** [comment]
I unfortunately don't recall and have been updating versions regularly. It was the most up to date version at the time of my original post. The problem only happened when the view controller conformed to JSQMessageKeyboardControllerDelegate so if its removed I think we can close this issue. If there is anything else you need just let me know.

Justin
