### ISSUE TITLE
endEditing function doesn't work

### ISSUE THREAD

**Issue by Tulleb** [jessesquires/JSQMessagesViewController#1806]
### General information

- Library version(s): develop branch
- iOS version(s): 10.0
- Devices/Simulators affected: Device
- Reproducible in the demo project? (Yes/No): Didn't try but I guess --> yes
- Related issues: #211
- Swift 3, Xcode 8 Beta 6.

## Bug report
`self.view.endEditing(true)` doesn't seem to have any effect.

### Expected behavior
The keyboard should hide.

### Actual behavior
The keyboard doesn't hide.

### Steps to reproduce
Add `self.view.endEditing(true)` code in a function and call it after a short duration with perform:selector:with:afterDelay.

**Comment by Lucashuang0802** [comment]
Hi, @Tulleb. I strongly suggest that you replicate the problem in our demo project. As different programs have different logic and ways to do things. We can't provide too much help if you put this `Didn't try but I guess`. LOL. 😄

**Comment by jessesquires** [comment]
Also, there's a big difference between calling `self.view.endEditing(true)` directly and using `perform:selector:with:afterDelay`.

@Tulleb -- how exactly are you using this?

**Comment by Tulleb** [comment]
@Lucashuang0802 I understand what you say. Sorry I should have precise that my program is almost a copy of the demo project (but in Swift 3.0).
If you are willing to help, I guess you can also add this simple line in your own code and see if you have the same issue? Or just replace the "Didn't try but I guess" by a "yes" after laughing so hard :)
Thanks!

@jessesquires I did try the `perform:selector:with:afterDelay`: doesn't work neither... **And I tried in the demo project this time.**

**Comment by jessesquires** [comment]
1. i don't recommend using `performSelector:...`
2. you can tell the `textInputView` to `resignFirstResponder`

**Comment by Tulleb** [comment]
@jessesquires I miss read your answer, sorry.

I've been trying to use it with and without `performSelector:...` in the demo project. It's not working.
I just wanted to point this out. I am using `resignFirstResponder` to keep hiding the keyboard.

**Comment by jessesquires** [comment]
should be fixed in `v8.0`
