### ISSUE TITLE
Message bubbles alignment issue: bubbles jump on 4.7" screens

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQMessagesViewController#1807]
I encounter an irregular behaviour where the bubbles are not aligned to the edges but have an offset. After receiving a new message the offsets are removed.

This is what it looks like:
![screen shot 2016-08-29 at 13 49 03](https://cloud.githubusercontent.com/assets/12123471/18049191/5d91b4bc-6def-11e6-9f4f-4809f9da07d7.png)

This is what it should look like:
![screen shot 2016-08-29 at 13 32 40](https://cloud.githubusercontent.com/assets/12123471/18049200/68234a8a-6def-11e6-947f-db0029f8c747.png)

This bug does not appear on screens smaller than 4.7".

**Comment by MHX792** [comment]
I put this in `viewWillAppear` and it solved it:

```
        self.collectionView.layoutIfNeeded()
        self.collectionView.performBatchUpdates({
            self.collectionView.reloadData()
            }, completion: nil)

```

But why did it happen in the first place?

**Comment by MHX792** [comment]
Ok, I assume the problem occured because I have a custom cell that is loaded form `nib`. Its size is declared in `sizeForItemAtIndexPath` method:

`        if message.isSystemMessage {
            return CGSizeMake(self.collectionView!.frame.width, 44)
        } `

The alignment error occured maybe because the `collectionView.frame.width` had not the correct size when `sizeForItemAtIndexPath` was called first. I changed it to:

`        if message.isSystemMessage {
            return CGSizeMake(UIScreen.mainScreen().bounds.width, 44)
        }`

It seems to work now.

**Comment by MHX792** [comment]
The problem still occurs. And sometimes the cell top label has an offset too. Also: the code above makes the view appear very laggy when it gets pushed on the navigation stack. So I think it is not a good workaround. How to fix it?

**Comment by Lucashuang0802** [comment]
@MHX792 do you still see this issue on 7.3.4? If you are able to replicate it in the sample app, that would be great. 😃

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
