### ISSUE TITLE
Incorrect top offset when pushing a chat controller on the navigation controller stack

### ISSUE THREAD

**Issue by clawoo** [jessesquires/JSQMessagesViewController#1808]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 8.0 (develop branch)
- iOS version(s): iOS 9.3
- Devices/Simulators affected: Both
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: 

## Bug report

The first few bubbles end up behind the navigation bar when the messages controller is being pushed on a navigation stack as opposed to being presented in a modal and there are not enough messages to fill an entire screen. Tapping on the textview and then resigning the first responder fixes this issue.

As a temporary fix I'm calling in `viewDidLoad`:

`[self jsq_setCollectionViewInsetsTopValue:0 bottomValue:CGRectGetHeight(self.inputToolbar.frame)];`

Tracing this bug led me to believe the problem stems from the fact that self.topLayoutGuide.length is 0 until the controller is actually displayed. 

Setting the `additionalContentInset` which triggers a` jsq_updateCollectionViewInsets()` makes things worse because at that point the input toolbar is been moved to the input accessory view and its frame is `(0, 0, screenWidth, screenHeight)` so the following computation for the bottom inset results into `screenHeight + additionalContentInset.bottom` (i.e., 568) instead of what was originally intended:

`CGRectGetMaxY(self.collectionView.frame) - CGRectGetMinY(self.inputToolbar.frame) + self.additionalContentInset.bottom;`

### Expected behavior

The first message should be placed below the navigation bar and not behind it. The bottom offset should be the height of the input toolbar.

### Actual behavior

The first message is displayed behind the navigation bar and scrolling up and releasing just hides it again.

### Steps to reproduce

Open the Objective C demo project and in loadFakeMessages() remove all the messages except the first two. Also comment out addPhotoMediaMessage / addAudioMediaMessage.

Run the app and notice that the "Load earlier messages" and the date header end up behind the nav bar. Tapping on the textview and then resigning the first responder fixes this issue.

This issue is reproducible on the Swift project as well if replacing the `presentViewController` with a `self.navigationController.pushViewController`

### Crash log? Screenshots? Videos? Sample project?

What it looks like: 
![simulator screen shot aug 29 2016 6 31 06 pm](https://cloud.githubusercontent.com/assets/380846/18056970/cb8c3bb4-6e16-11e6-911e-954fa7560bc2.png)

What's supposed to look like:
![simulator screen shot aug 29 2016 6 31 11 pm](https://cloud.githubusercontent.com/assets/380846/18056971/cb8d5ddc-6e16-11e6-8039-725ccc8fcfc2.png)

**Comment by Lucashuang0802** [comment]
Thanks @clawoo!

This feature is being tracked at #1785. You can comment from there if you have any ideas or fixes. 😄
