### ISSUE TITLE
How to customise cells for Swift to add timestamp

### ISSUE THREAD

**Issue by Atlas2014** [jessesquires/JSQMessagesViewController#1809]
Hi guys, I've read all the closed issues on how to add custom cells but am having trouble figuring out the process for Swift.

I would like to achieve a layout similar to this

![51e8fc0a-6dec-11e5-9df5-b21670eadc25](https://cloud.githubusercontent.com/assets/10011128/18050240/0187d3be-6e20-11e6-93cb-678d0eda100a.png)

where a timestamp element shows up next to every bubble and also the date shows up in the center for every first message for every day.

I understand from comments from @GianniCarlo a that one approach could be to subclass JSQMessagesCollectionViewCellIncoming and JSQMessagesCollectionViewCellOutgoing and copy the existing JSQMessagesCollectionViewCellOutgoing.xib and JSQMessagesCollectionViewCellIncoming.xib to use as templates but am unclear about how to go about it in Swift. 

Could anyone lend some tips on achieving this with Swift? Possibly with some code examples of how to  use custom subclasses for JSQMessagesCollectionViewCellIncoming and JSQMessagesCollectionViewCellOutgoing to display the timestamp next to the bubbles to get me started.

My sub-class code so far is:

```
class messageViewOutgoing: JSQMessagesCollectionViewCellOutgoing {
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)        
    }
}

class messageViewIncoming: JSQMessagesCollectionViewCellIncoming {
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)        
    }
}
```

And in my JSQMessagesViewController subclass I have:

```
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {

    let message = self.messages[indexPath.item]

    if message.senderId == self.senderId {

        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! messageViewOutgoing

        return cell

    } else {

        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! messageViewIncoming

        return cell
    }
}
```

**Comment by GianniCarlo** [comment]
@Atlas2014 you need to register your new xib with your new labels in your collectionView in `viewDidLoad` something along the lines of

```
self.incomingCellIdentifier = MySubclassCellIncoming.cellReuseIdentifier();
            self.collectionView.registerNib(MySubclassCellIncoming.nib(), forCellWithReuseIdentifier: self.incomingCellIdentifier)
self.outgoingCellIdentifier = MySubclassCellOutgoing.cellReuseIdentifier();
            self.collectionView.registerNib(MySubclassCellOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingCellIdentifier)
```

The same for the media identifier I would think. Then you should be able to access them in `cellForItemAtIndexPath` and alter the timestamp label however you wish

**Comment by Atlas2014** [comment]
@GianniCarlo thank you for your quick reply. I tried adding the below in viewDidLoad

```
        self.incomingCellIdentifier = messageViewIncoming.cellReuseIdentifier();
        self.collectionView.registerNib(messageViewIncoming.nib(), forCellWithReuseIdentifier: self.incomingCellIdentifier)
        self.outgoingCellIdentifier = messageViewOutgoing.cellReuseIdentifier();
        self.collectionView.registerNib(messageViewOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingCellIdentifier)
```


And tried copying JSQMessagesCollectionViewCellOutgoing.xib and JSQMessagesCollectionViewCellIncoming.xib straight from the Pod and renamed them to messageViewOutgoing.xib and messageViewIncoming.xib and have changed their class to messageViewOutgoing and messageViewIncoming under the Custom Class section.

But am getting the following error: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle.

Sorry if I'm missing something super obvious I'm still getting the hang of Xcode and Swift.

**Comment by GianniCarlo** [comment]
@Atlas2014  try adding the same lines but for the media identifiers and try again

```
self.incomingMediaCellIdentifier = MySubclassCellIncoming.mediaCellReuseIdentifier();
            self.collectionView.registerNib(MySubclassCellIncoming.nib(), forCellWithReuseIdentifier: self.incomingMediaCellIdentifier)
self.outgoingMediaCellIdentifier = MySubclassCellOutgoing.mediaCellReuseIdentifier();
            self.collectionView.registerNib(MySubclassCellOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingMediaCellIdentifier)
```

let me know how it goes

**Comment by Atlas2014** [comment]
@GianniCarlo I added the lines below for media identifiers but still get the "Could not load NIB in bundle" Exception.

```
        self.incomingMediaCellIdentifier = messageViewIncoming.mediaCellReuseIdentifier();
        self.collectionView.registerNib(messageViewIncoming.nib(), forCellWithReuseIdentifier: self.incomingMediaCellIdentifier)
        self.outgoingMediaCellIdentifier = messageViewOutgoing.mediaCellReuseIdentifier();
        self.collectionView.registerNib(messageViewOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingMediaCellIdentifier)
```

Does Xcode automatically generate the nib from the xib?

**Comment by GianniCarlo** [comment]
mmmmmm can you post the entire stack trace? can you confirm if in your .xib(s), in the section `Target Membership` your app is selected? (you can find it in the File Inspector in the right panel)

**Comment by Atlas2014** [comment]
sure no probs, thanks for helping with this. I checked and both messageViewOutgoing.xib and messageViewIncoming.xib have my app ticked in Target Membership.


```
[Timeline]: Timeline: { "Request Start Time": 494189531.290456, "Initial Response Time": 494189531.356099, "Request Completed Time": 494189531.356784, "Serialization Completed Time": 494189531.357412, "Latency": 0.0656430125236511 secs, "Request Duration": 0.0663279891014099 secs, "Serialization Duration": 0.000627994537353516 secs, "Total Duration": 0.0669559836387634 secs }
2016-08-29 11:52:11.374 Projectx3[1171:18131] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/XI/Library/Developer/CoreSimulator/Devices/F61D6A6D-95C3-40E8-A66E-FDCDD75D6EDE/data/Containers/Bundle/Application/A1442E16-A03F-4AE6-AF46-34F3F0562D00/Projectx3.app> (loaded)' with name 'Projectx3.messageViewIncoming''
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106d66d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010929edeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106d66cbd +[NSException raise:format:] + 205
	3   UIKit                               0x00000001080eac89 -[UINib instantiateWithOwner:options:] + 499
	4   UIKit                               0x00000001085ab553 -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 716
	5   UIKit                               0x00000001085abebc -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 169
	6   JSQMessagesViewController           0x00000001065b4cd3 -[JSQMessagesViewController collectionView:cellForItemAtIndexPath:] + 1427
	7   Projectx3                           0x0000000106329901 _TFC9Projectx327MessageDetailViewController14collectionViewfTCSo16UICollectionView22cellForItemAtIndexPathCSo11NSIndexPath_CSo20UICollectionViewCell + 1857
	8   Projectx3                           0x0000000106329c0f _TToFC9Projectx327MessageDetailViewController14collectionViewfTCSo16UICollectionView22cellForItemAtIndexPathCSo11NSIndexPath_CSo20UICollectionViewCell + 79
	9   UIKit                               0x000000010859a08f -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:] + 483
	10  UIKit                               0x000000010859dd96 -[UICollectionView _updateVisibleCellsNow:] + 4988
	11  UIKit                               0x00000001085a2575 -[UICollectionView layoutSubviews] + 258
	12  UIKit                               0x0000000107ddd980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
	13  QuartzCore                          0x000000010e241c00 -[CALayer layoutSublayers] + 146
	14  QuartzCore                          0x000000010e23608e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	15  UIKit                               0x0000000107dcd205 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1129
	16  Projectx3                           0x000000010632fb77 _TFFC9Projectx327MessageDetailViewController14viewWillAppearFSbT_U_FGV9Alamofire8ResponsePs9AnyObject_CSo7NSError_T_ + 9751
	17  Alamofire                           0x0000000106493a27 _TTRXFo_oGV9Alamofire8ResponsePs9AnyObject_CSo7NSError__dT__XFo_iGS0_PS1__S2___dT__ + 151
	18  Alamofire                           0x000000010649232d _TFFFC9Alamofire7Request8responseuRxS_22ResponseSerializerTyperFT5queueGSqPSo17OS_dispatch_queue__18responseSerializerx17completionHandlerFGVS_8Responsewx16SerializedObjectwx11ErrorObject_T__DS0_U_FT_T_U_FT_T_ + 797
	19  Alamofire                           0x0000000106490b74 _TPA__TFFFC9Alamofire7Request8responseuRxS_22ResponseSerializerTyperFT5queueGSqPSo17OS_dispatch_queue__18responseSerializerx17completionHandlerFGVS_8Responsewx16SerializedObjectwx11ErrorObject_T__DS0_U_FT_T_U_FT_T_ + 164
	20  Alamofire                           0x000000010644c487 _TTRXFo__dT__XFdCb__dT__ + 39
	21  libdispatch.dylib                   0x000000010a9ddd9d _dispatch_call_block_and_release + 12
	22  libdispatch.dylib                   0x000000010a9fe3eb _dispatch_client_callout + 8
	23  libdispatch.dylib                   0x000000010a9e61ef _dispatch_main_queue_callback_4CF + 1738
	24  CoreFoundation                      0x0000000106cc00f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	25  CoreFoundation                      0x0000000106c81b99 __CFRunLoopRun + 2073
	26  CoreFoundation                      0x0000000106c810f8 CFRunLoopRunSpecific + 488
	27  GraphicsServices                    0x000000010e104ad2 GSEventRunModal + 161
	28  UIKit                               0x0000000107d22f09 UIApplicationMain + 171
	29  Projectx3                           0x00000001063351e2 main + 114
	30  libdyld.dylib                       0x000000010aa3292d start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by GianniCarlo** [comment]
mmmmm it should be working, do you have any link to a repo where I can test your project? If it's not possible, the first place to look for the error is in `[JSQMessagesViewController collectionView:cellForItemAtIndexPath:]` see if the line where it hangs gives any indication as to why it's not registering the nib for your incoming view cells

**Comment by Atlas2014** [comment]
It isn't on a repo unfortunately. By [JSQMessagesViewController collectionView:cellForItemAtIndexPath:] would that be:

```
    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        
        let message = messages[indexPath.item]
        
        if message.senderId == self.senderId {
            
            let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! messageViewOutgoing
            
            cell.timeLabel.text = NSDateFormatter().stringFromDate(message.date)
            
            return cell
            
        } else {
            
            let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! messageViewIncoming
            
            cell.timeLabel.text = NSDateFormatter().stringFromDate(message.date)
            
            return cell
        }
        
    }
```

Unfortunately I can't upload this project but maybe I can recreate the problem in a new one and send it to you?

**Comment by GianniCarlo** [comment]
I mean the line inside the pod `[JSQMessagesViewController collectionView:cellForItemAtIndexPath:]`. Yes if you can recreate it and send it to me I can help out 👍

**Comment by Atlas2014** [comment]
Awesome! thanks mate. I'll try put one together. But I'm not sure where the line is for [JSQMessagesViewController collectionView:cellForItemAtIndexPath:]

Should it be in the viewcontroller swift file?

**Comment by Atlas2014** [comment]
Hi @GianniCarlo I've setup a project based on the Swift example which recreates the Exception error.

https://drive.google.com/open?id=0B67fYTTiFGecbGZtNnRRMkFOOHM

**Comment by Atlas2014** [comment]
Hi @GianniCarlo I've updated the link to new project example. The old one was having some problems with the pod setup

https://drive.google.com/open?id=0B67fYTTiFGecOV9TQlBkTHh0OGc

**Comment by GianniCarlo** [comment]
Ok, I'll check it out

**Comment by GianniCarlo** [comment]
@Atlas2014 ok I got it working, the problem lies in `mediaCellReuseIdentifier`, `cellReuseIdentifier` and `nib` (not sure about this last one). The implementation for Objective-C works fine. But in Swift, `NSStringFromClass([self class]);` instead of returning `< your class name as string >` it returns: `< your app name >.< your class name >`.

So the solution when you are in Swift is to override `cellReuseIdentifier` and `mediaCellReuseIdentifier` in your subclasses. Just to be sure override `nib` too and give it the same treatment. I changed your class name from `messageViewOutgoing` and `MessageViewOutgoing`.

The subclasses ended up as following:

```swift
class MessageViewIncoming: JSQMessagesCollectionViewCellIncoming {
    
    @IBOutlet weak var timeLabel: UILabel!
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    override class func nib() -> UINib {
        return UINib (nibName: "MessageViewIncoming", bundle: NSBundle.mainBundle())
    }
    
    override class func cellReuseIdentifier() -> String {
        return "MessageViewIncoming"
    }
    
    override class func mediaCellReuseIdentifier() -> String {
        return "MessageViewIncoming_JSQMedia"
    }
}

class MessageViewOutgoing: JSQMessagesCollectionViewCellOutgoing {
    @IBOutlet weak var timeLabel: UILabel!
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override class func nib() -> UINib {
        return UINib (nibName: "MessageViewOutgoing", bundle: NSBundle.mainBundle())
    }
    
    override class func cellReuseIdentifier() -> String {
        return "MessageViewOutgoing"
    }
    
    override class func mediaCellReuseIdentifier() -> String {
        return "MessageViewOutgoing_JSQMedia"
    }

}
```

PS. In the first sample you sent me the subclasses in the xib files weren't set correctly

**Comment by GianniCarlo** [comment]
There's probably a better way to do this and still use the class to get the string, but for functionality sake that works 😁

**Comment by Atlas2014** [comment]
Thanks @GianniCarlo ! that did the trick. It seems to be working with the subclasses now but I still can't seem to get the timeLabel to show. 

Not sure if I've implemented it correctly but my xib looks like this with timeLabel linked up under the subclasses:

@IBOutlet weak var timeLabel: UILabel!

![timelabel](https://cloud.githubusercontent.com/assets/10011128/18087167/55aca46c-6ee6-11e6-9284-62d8c4b33a1c.jpg)

**Comment by Atlas2014** [comment]
@GianniCarlo my mistake it's working! I didn't have the constraints setup so it wasn't showing up in relation to the bubble. :grin: Thanks for all your help getting the classes working for Swift, you've been a huge help!

**Comment by GianniCarlo** [comment]
Glad you got it working 👍👍👍

**Comment by Nallamsetty** [comment]
i tried the same code as u followed but i got the error like this

Could not cast value of type 'JSQMessagesCollectionViewCellOutgoing' (0x370fdc) to 'MyProject.MessageViewOutgoing'

**Comment by dartkinselok** [comment]
@Nallamsetty you've forgot to change Nib classes in right inspector's panel from JSQ's default to new Subclasses (MessageIncoming/OutgoingView)

**Comment by Nide27** [comment]
Hey, I have a little problem.
I can't link the label to my subclass can somebody help me? 😁
