### ISSUE TITLE
Can't play audio file when using custom Message class

### ISSUE THREAD

**Issue by tunidev** [jessesquires/JSQMessagesViewController#1810]
- [X] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.3.4
- iOS version(s): 9
 
## Bug report
The play button of audio messages is not fire

### Expected behaviour   
Audio plays hen tap on the play button

I have checked the issue #1705. 

I have a `Message` class that conforms to `JSQMessageData`  :

```
extension Message: JSQMessageData {
 .....
    func isMediaMessage() -> Bool {
        switch self.dataType {
        case .Audio, .Image, .Video:
            return true
        default:
            return false
        }
    }
 
    func media() -> JSQMessageMediaData! {
        let item = JSQAudioMediaItem(data: self.attachementData)
        item.audioData = self.attachementData
        item.delegate = self
        return item
    }
}
 
```

now in `    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
`

I am downloading the audio file:

```
if message.isMediaMessage() {
            guard let url = message.attachement else {return cell}  
          if message.attachementData == nil {
                      let data = NSData(contentsOfURL: audioURL) 
                        message.attachementData = data 
                        dispatch_async(dispatch_get_main_queue(),{ [weak self] () -> () in
                            if let strongSelf = self {
                                strongSelf.collectionView.reloadData()
                            }
                       })  
                }
            }
```
 
everything working fine EXPECT playing the audio.

Debug:
+ Audio file is working fine when played in computer
+ Player displayed correctly with the audio duration :

<img width="183" alt="screen shot 2016-08-30 at 16 31 55" src="https://cloud.githubusercontent.com/assets/4885143/18093205/59b6d878-6ecf-11e6-9630-79f7b38a5669.png">

+ Nothing received in : `didChangeAudioCategory protocol`
+ The most important is : `onPlayButton` is not fired when tapping the play button of the audio cell !

**Comment by eliburke** [comment]
@tunidev great bug report! The details make it much easier to help. 
Since onPlayButton is not firing, I think that's the most likely culprit for the audio not playing. It appears as though you have a valid audio file loaded into the control. What is your view hierarchy like? Are there any subviews or overlays on top of your JSQMessages subclass that could be intercepting touches?

**Comment by tunidev** [comment]
@eliburke thank you for your replay and your suggestion. Here is the screenshot of my view hierarchy  and the play button is highlighted in the stack. The special think about the app is that I am using https://github.com/romaonthego/RESideMenu and Menu, but I think that this has not any relation with the issue 
<img width="542" alt="screen shot 2016-08-30 at 18 35 14" src="https://cloud.githubusercontent.com/assets/4885143/18098099/faf7c9d4-6ee0-11e6-9a12-5d166aa5d5aa.png">

**Comment by tunidev** [comment]
Note that I can select text in text message cells and and display the menu "copy" in cells

**Comment by tunidev** [comment]
When I try to use `JSQMessage` it works, but not with my custom `Message` class that conforms to `JSQMessageData`  what can go wrong when going that road ?

**Comment by tunidev** [comment]
I have reproduce the issue with the swift example, I have just used a custom class that conforms to  `JSQMessageData`  the audio does not work anymore in that case, maybe I did not use a custom class correctly. the project attached below

[SwiftExample.zip](https://github.com/jessesquires/JSQMessagesViewController/files/445829/SwiftExample.zip)

**Comment by tunidev** [comment]
I see that it's the same as #1705 it;s about holding a string reference to `JSQAudioMediaItem` : 

    var audioMediaItem:JSQAudioMediaItem?

and in media() we return the item:

    func media() -> JSQMessageMediaData! {
        let att = JSQAudioMediaViewAttributes()
        att.showFractionalSeconds = true
        att.tintColor = UIColor.tl_blueColor()
        self.audioMediaItem =  JSQAudioMediaItem(data: self.attachementData, audioViewAttributes: att)
        self.audioMediaItem!.appliesMediaViewMaskAsOutgoing = true
        return self.audioMediaItem
    }
