### ISSUE TITLE
JSQMessagesAssets.bundle not loading when using JSQMessagesViewController as framework

### ISSUE THREAD

**Issue by danielpetroianu** [jessesquires/JSQMessagesViewController#1811]
### General information
- Library version(s): 7.3.4
- Reproducible in the demo project? (Yes/No): NO
## Bug report

JSQMessagesAssets.bundle is not in JSQMessagesViewController.framework . 
I'm using cocoapods 1.0.1 with `use_frameworks!` and when showing the JSQMessagesViewController the param assert `NSParameterAssert(minimumBubbleWidth > 0);` from `-[JSQMessagesBubblesSizeCalculator initWithCache:minimumBubbleWidth:usesFixedWidthBubbles:]` rises an exception because `+[NSBundle(JSQMessages) jsq_messagesAssetBundle]` returns nil .

The `JSQMessagesAssets.bundle` isn't in the product .app/Frameworks/JSQMessagesViewController.framework

If manually adding the JSQMessagesAssets.bundle to the JSQMessagesViewController.framework from the Utilities menu (Target Membership) it works, the bundle is copied.

Not sure if this is a cocoapods issue or a podspec issue.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
