### ISSUE TITLE
Input toolbar height does not update after setting text 

### ISSUE THREAD

**Issue by ImperoIT** [jessesquires/JSQMessagesViewController#1812]
I'm trying to set an initial value for the textview in the input toolbar in viewDidLoad but its height doesn't update correctly:

self.inputToolbar.contentView.textView.text = lastMessage;
Any idea how to fix this?

I have tried #955 but its not working

**Comment by Lucashuang0802** [comment]
Hi @ImperoIT. I am able to make it work by adding this line `self.inputToolbar.contentView.textView.text = @"it's a really long text that it's height enough to have multiple lines. hahaha";` in `viewDidLoad`. Can you tell us what kind of situations that are not working for your case?

![simulator screen shot sep 10 2016 4 05 06 pm](https://cloud.githubusercontent.com/assets/3754490/18414027/5db53290-7770-11e6-8d22-6ca3a107f173.png)
