### ISSUE TITLE
How can i resize the JSQ message VC. I would like to add a view above but the problem is the the view is hiding the me messages. If I give it a constraint that would work. thank you in advance

### ISSUE THREAD

**Issue by pprevalon** [jessesquires/JSQMessagesViewController#1813]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by pprevalon** [comment]
Hello Jesse i submitted the question earlier and it is now  closed without an answer can you let me know thank you

**Comment by jessesquires** [comment]
Thanks @pprevalon ! 😄 

Sorry about that. See the docs and other issues for `topContentAdditionalInset`.

http://cocoadocs.org/docsets/JSQMessagesViewController/7.3.4/Classes/JSQMessagesViewController.html#//api/name/topContentAdditionalInset
