### ISSUE TITLE
Multiple bubble styles in same chat

### ISSUE THREAD

**Issue by Jeyhey** [jessesquires/JSQMessagesViewController#1814]
In my chat app the user can send messages in different bubble styles. The bubbles differ in their shape. Is there a way to implement this? I tried to find a solution with no avail.

Is there a callback function where I can define the message mask individually for each message? Or how would I implement this?

**Comment by jessesquires** [comment]
Hey @Jeyhey ! 😄 

You want to override `cellForItemAtIndexPath:` and/or `messageBubbleImageDataForItemAtIndexPath:`

http://cocoadocs.org/docsets/JSQMessagesViewController/7.3.4/Protocols/JSQMessagesCollectionViewDataSource.html#//api/name/collectionView:messageBubbleImageDataForItemAtIndexPath:

**Comment by Jeyhey** [comment]
Thanks Jesse
