### ISSUE TITLE
How to avoid text selection inside bubble

### ISSUE THREAD

**Issue by TheEngineerz** [jessesquires/JSQMessagesViewController#1815]
How i can avoid this type of selection .Sometimes when i select the bubble text automatically selected.
![screen shot 2016-09-05 at 7 19 03 pm](https://cloud.githubusercontent.com/assets/5149947/18252021/19272d86-73a6-11e6-970f-a7b7265f1810.png)
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by tunidev** [comment]
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
         
        let message = self.viewModel.messages[indexPath.item] // get the message object

        if !message.isMediaMessage() {
            cell.textView.selectable = false
            cell.textView.userInteractionEnabled = false 
        }
    }

this is how I do it ...

**Comment by jessesquires** [comment]
thanks @tunidev !
