### ISSUE TITLE
How to show message date in JSQMessagesViewController

### ISSUE THREAD

**Issue by umeshjavastar** [jessesquires/JSQMessagesViewController#1816]
I am trying to make a chat app and I am using JSQMessagesViewController library. My Chat View show all the messages with their date and time but I am facing some little bit of problem with this library. My problem is I wanna show message date only Once. Suppose: Yesterday date contains 10 messages and today date contains 15 messages

and I wanna show Only single date of these messages as not repeat dates for every messages 
![19272d86-73a6-11e6-970f-a7b7265f1810](https://cloud.githubusercontent.com/assets/12446459/18263144/3f7e648e-7425-11e6-9721-071a8cf59299.png)

**Comment by jessesquires** [comment]
Thanks @umeshjavastar ! 

See the docs and demo project. You can override the `dataSource` and `delegate` methods for the `cellTopLabel`.

http://cocoadocs.org/docsets/JSQMessagesViewController/7.3.4/Protocols/JSQMessagesCollectionViewDataSource.html#//api/name/collectionView:attributedTextForCellTopLabelAtIndexPath:

**Comment by NikKovIos** [comment]
Check this https://github.com/jessesquires/JSQMessagesViewController/issues/1392#issuecomment-367594318
