### ISSUE TITLE
Adding Kerning

### ISSUE THREAD

**Issue by charmingtoad** [jessesquires/JSQMessagesViewController#1817]
I've used ```collectionView.collectionViewLayout.messageBubbleFont = UIFont.systemFontOfSize(17.0)``` to change the font of the bubble text, and the bubble size updates accordingly (yay!).  I'd also like to change the kerning of the text. Is there a built-in way to do this so the bubble size updates to match?

## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

**Comment by jessesquires** [comment]
Hey @charmingtoad ! 😄 

This is something we're working on for `v8.0`. For now, you can use the `JSQMessagesBubbleSizeCalculating` API to implement your own bubble size calculations if you need to.

http://cocoadocs.org/docsets/JSQMessagesViewController/7.3.4/Protocols/JSQMessagesBubbleSizeCalculating.html
