### ISSUE TITLE
textview doesn't pop up when I write viewdidappear in the chat controller

### ISSUE THREAD

**Issue by jadslim313** [jessesquires/JSQMessagesViewController#1818]
hi,

I hope there isn't a duplicate of this, I tried looking.

So this bug only appears on the phones not the simulator.

I tried it with my code and with your swift version of the code, since I'm no good at objective c.
I ran this code on the iphone 5s.

but when you add viewdidappear to the class, the text view does not pop up anymore.

is this something that we're just going to have to live with?

**Comment by jessesquires** [comment]
Thanks! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:

**Comment by sreeji44** [comment]
@jadslim313 hey use super for viewdidappear 
 override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(true)

**Comment by jessesquires** [comment]
thanks @sreeji44 !
