### ISSUE TITLE
Text bubble only allow two string characters then create a new line break and repeat another 2 character

### ISSUE THREAD

**Issue by pprevalon** [jessesquires/JSQMessagesViewController#1821]
Text bubble only allow 2character then create a new line break for the next 2 characters. this will happen randomly.

#
![imag0385](https://cloud.githubusercontent.com/assets/19171619/18399527/6e5feac6-769f-11e6-9272-7afaadd6e9ef.jpg)

`import UIKit
import JSQMessagesViewController
import MobileCoreServices
import AVKit
import Firebase
import Braintree

class messagesViewController: JSQMessagesViewController {
    //braintree info
    
    var braintreeClient: BTAPIClient?
    var clientToken = String()
    var formInfo = [String: AnyObject]()
    
    
    
    // this is the id of the post id number
    var previousViewMessageId:String!
    ////
    
    let incomingBubble = JSQMessagesBubbleImageFactory().incomingMessagesBubbleImageWithColor(UIColor(red: 10/255, green: 180/255, blue: 230/255, alpha: 1.0))
    let outgoingBubble = JSQMessagesBubbleImageFactory().outgoingMessagesBubbleImageWithColor(UIColor.lightGrayColor())
    var messages = [JSQMessage]()
    //ref to retrieve message
    var messageRef:FIRDatabaseReference! //
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        //braintreeSetup()
        navBar()
        // tappedMyPayButton()
        
        self.messageRef = fireBaseAPI().childRef("version_one/frontEnd/post/\(previousViewMessageId)")
        
        let currentUser = fireBaseAPI().currentUserId()
        self.senderId = currentUser
        self.senderDisplayName = ""
        let ref = fireBaseAPI().ref()
        let messagRef = ref.child("version_one/frontEnd/post/\(previousViewMessageId)messages")
        
        // messagRef.childByAutoId().setValue("first Message")
        
        
        
        
        messagRef.observeEventType(.ChildAdded, withBlock: {snapshot in
            //if let dict = snapshot.value as? String {
            //}

            
            
        })
        
        
        observerveMessages()
        
        
        
    }
    
}

extension messagesViewController {
    
    override func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return self.messages.count
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, messageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageData! {
        let data = self.messages[indexPath.row]
        
        
        return data
    }
    
    
    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        
        return cell
        
    }
    override func collectionView(collectionView: JSQMessagesCollectionView!, didDeleteMessageAtIndexPath indexPath: NSIndexPath!) {
        self.messages.removeAtIndex(indexPath.row)
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageBubbleImageDataSource! {
        
        let bubbleFactory = JSQMessagesBubbleImageFactory()
        
        let message = messages[indexPath.item]
        
        if message.senderId == self.senderId {
            
            
            
            return bubbleFactory.outgoingMessagesBubbleImageWithColor(UIColor(r: 43, g: 216, b: 225))
        }else{
            
            return bubbleFactory.incomingMessagesBubbleImageWithColor(UIColor(r: 125, g: 125, b: 125))
            
        }
        

        
        
        
                //let data = messages[indexPath.row]
                //switch(data.senderId) {
                //case self.senderId:
                    //return self.outgoingBubble
                //default:
                    //return self.incomingBubble
                //}
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageAvatarImageDataSource! {
        
        return nil
    }
}

//MARK - image

extension messagesViewController:UIImagePickerControllerDelegate,UINavigationControllerDelegate {
    
    override func didPressSendButton(button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: NSDate!) {
        //from previous version
        //        let message = JSQMessage(senderId: senderId, senderDisplayName: senderDisplayName, date: date, text: text)
        //        self.messages += [message]
        //        self.finishSendingMessage()
        
        ////
        
        let newMessage = messageRef.child("messages")
        
        let messageData = ["text":text,"senderId":senderId,"senderDisplayName":senderDisplayName, "mediaType":"TEXT"]
        
        newMessage.childByAutoId().setValue(messageData)
        
        
        self.finishSendingMessage()
        
        
    }
    //
    func observerveMessages(){
        let obRef = fireBaseAPI().childRef("version_one/frontEnd/post/\(previousViewMessageId)/messages")
        obRef.observeEventType(.ChildAdded, withBlock: {snapshot in
            //
            
            
            if let dict = snapshot.value as? [String:AnyObject]{
                let mediaType = dict["mediaType"] as! String
                let senderId = dict["senderId"] as! String
                let senderName = dict["senderDisplayName"] as! String
                
                
                switch mediaType {
                case "TEXT":
                    let text = dict["text"] as? String
                    
                    self.messages.append(JSQMessage(senderId: senderId, displayName: senderName, text: text))
                    
                    
                case "PHOTO":
                    let fileUrl = dict["fileUrl"] as! String
                    let url = NSURL(string: fileUrl)
                    let data = NSData(contentsOfURL: url!)
                    let picture = UIImage(data: data!)
                    let photo = JSQPhotoMediaItem(image: picture!)
                    
                    self.messages.append(JSQMessage(senderId: senderId,displayName: senderName, media: photo))
                    
                    if self.senderId == senderId {
                        photo.appliesMediaViewMaskAsOutgoing = true
                        
                    }else{
                        photo.appliesMediaViewMaskAsOutgoing = false
                    }
                    
                    
                case "VIDEO":
                    let fileUrl = dict["fileUrl"] as! String
                    let video = NSURL(string: fileUrl)
                    let videoItem = JSQVideoMediaItem(fileURL: video, isReadyToPlay: true)
                    self.messages.append(JSQMessage(senderId: senderId,displayName:senderName,media: videoItem))
                    
                    if self.senderId == senderId {
                        videoItem.appliesMediaViewMaskAsOutgoing = true
                        
                    }else{
                        videoItem.appliesMediaViewMaskAsOutgoing = false
                    }
                    
                default :
                    print("Unknown data")
                }
                self.collectionView.reloadData()

            }
            
            
        })
        
    }
    
    override func didPressAccessoryButton(sender: UIButton!) {
        
        
        let sheet = UIAlertController(title: "Media Messages", message: "Please select an images", preferredStyle: .ActionSheet)
        let cancel = UIAlertAction(title: "Cancel", style: .Cancel) { (alert) in
            
            
        }
        let photoLibrary = UIAlertAction(title: "Photo Library", style: .Default) { (alert) in
            self.getMediafrom(kUTTypeImage)
            
        }
        let VideoLibrary = UIAlertAction(title: "Video Library", style: .Default) { (alert) in
            
            self.getMediafrom(kUTTypeMovie)
        }
        
        sheet.addAction(photoLibrary)
        sheet.addAction(VideoLibrary)
        sheet.addAction(cancel)
        
        self.presentViewController(sheet, animated: true, completion: nil)
        
        //        let imagePicker = UIImagePickerController()
        //        imagePicker.delegate = self
        //        self.presentViewController(imagePicker, animated: true, completion: nil)
        //
        
    }
    
    func getMediafrom(type:CFString){
        let mediaPicker = UIImagePickerController()
        mediaPicker.delegate = self
        mediaPicker.mediaTypes = [type as String]
        
        self.presentViewController(mediaPicker, animated: true, completion: nil)
        
        
        
    }
    // Display video message
    override  func collectionView(collectionView: JSQMessagesCollectionView!, didTapMessageBubbleAtIndexPath indexPath: NSIndexPath!) {
        
        let message = messages[indexPath.item]
        if message.isMediaMessage {
            
            if let mediaItem = message.media as? JSQVideoMediaItem{
                
                
                
                let player = AVPlayer(URL: mediaItem.fileURL)
                let playerViewController = AVPlayerViewController()
                playerViewController.player = player
                
                self.presentViewController(playerViewController, animated: true, completion: nil)
                
            }
        }
        
    }
    func sendMedia(picture:UIImage?,video: NSURL?){
        
        
        let filePath = "frontEnd/users/\(fireBaseAPI().currentUserId()!)/images/\(NSDate.timeIntervalSinceReferenceDate())/"
        
        if let picture = picture{
            
            let data = UIImageJPEGRepresentation(picture, 0.1)
            let metaData = FIRStorageMetadata()
            metaData.contentType = "image/jpg"
            FIRStorage.storage().reference().child(filePath).putData(data!, metadata: metaData) { (metaData, error) in
                if error != nil {
                    print(error)
                    return
                }
                
                let fileUrl =  metaData?.downloadURLs![0].absoluteString
                let newMessage = self.messageRef.child("messages")
                
                
                let messageData = ["fileUrl":fileUrl,"senderId":self.senderId,"senderDisplayName":self.senderDisplayName, "mediaType":"PHOTO"]
                
                newMessage.childByAutoId().setValue(messageData)
                
                
                
            }
            
            
        }else if let video = video{
            
            let data = NSData(contentsOfURL: video)
            let metaData = FIRStorageMetadata()
            metaData.contentType = "video/mp4"
            FIRStorage.storage().reference().child(filePath).putData(data!, metadata: metaData) { (metaData, error) in
                if error != nil {
                    print(error)
                    return
                }
                
                let fileUrl =  metaData?.downloadURLs![0].absoluteString
                let newMessage = self.messageRef.child("messages")
                
                let messageData = ["fileUrl":fileUrl,"senderId":self.senderId,"senderDisplayName":self.senderDisplayName, "mediaType":"VIDEO"]
                
                newMessage.childByAutoId().setValue(messageData)
                
                
                
            }
            
            
        }
        
    }
    
    //photothe
    func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject]) {
        
        if let picture = info[UIImagePickerControllerOriginalImage] as? UIImage{
            //   let photo = JSQPhotoMediaItem(image: picture)
            ////  messages.append(JSQMessage(senderId: senderId,displayName: senderDisplayName,media: photo))
            sendMedia(picture,video:nil)
            
        }else if let video = info[UIImagePickerControllerMediaURL] as? NSURL {
            //            let videoItem = JSQVideoMediaItem(fileURL: video, isReadyToPlay: true)
            //            messages.append(JSQMessage(senderId: senderId,displayName:senderDisplayName,media: videoItem))
            
            sendMedia(nil, video: video)
        }
        
        
        
        
        
        
        self.dismissViewControllerAnimated(true, completion: nil)
        collectionView.reloadData()
        
    }
    
}
extension messagesViewController{

    func dismissVc(){
        self.dismissViewControllerAnimated(true, completion: nil)
    }
    //button setup
    
}

`

**Comment by MacMeDan** [comment]
Could you provide your code or relevant code snippets? That would help in addressing this issue.

**Comment by pprevalon** [comment]
code was added thank you

**Comment by MacMeDan** [comment]
would you also mind adding your message object. I had an issue when I did not implement the hash for each message.

**Comment by pprevalon** [comment]
ok

**Comment by MacMeDan** [comment]
So I tried to take all of your code and put it in the swift example project. I commented anything referring to firebase and it looks fine to me. I adjusted a few things but nothing I Identified as the reason for the newlines ever few characters.

**Comment by pprevalon** [comment]
I agree, i could not find a reason either this only happen on ipad also not iphone.

**Comment by MacMeDan** [comment]
class ChatViewController: JSQMessagesViewController {

    let incomingBubble = JSQMessagesBubbleImageFactory().incomingMessagesBubbleImageWithColor(UIColor.jsq_messageBubbleBlueColor())
    let outgoingBubble = JSQMessagesBubbleImageFactory().outgoingMessagesBubbleImageWithColor(UIColor.lightGrayColor())
    var messages = [JSQMessage]()

    private var displayName: String!
    override func viewDidLoad() {
        super.viewDidLoad()
 }
//I removed everthing in your view did load

override func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return self.messages.count
    }

    override func collectionView(collectionView: JSQMessagesCollectionView, messageDataForItemAtIndexPath indexPath: NSIndexPath) -> JSQMessageData {
        let data = self.messages[indexPath.row]

        return data
    }


    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell

        return cell

    }
    override func collectionView(collectionView: JSQMessagesCollectionView, didDeleteMessageAtIndexPath indexPath: NSIndexPath) {
        self.messages.removeAtIndex(indexPath.row)
    }

    override func collectionView(collectionView: JSQMessagesCollectionView, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath) -> JSQMessageBubbleImageDataSource {

        let bubbleFactory = JSQMessagesBubbleImageFactory()

        let message = messages[indexPath.item]

        if message.senderId == self.senderId() {

            return bubbleFactory.outgoingMessagesBubbleImageWithColor(UIColor.jsq_messageBubbleBlueColor())
        }else{

            return bubbleFactory.incomingMessagesBubbleImageWithColor(UIColor.jsq_messageBubbleBlueColor())

        }
    }
// Used default colors because it seems you have an extension for getting your colors


// Then the rest of this is just what is in the example project with the repetitive functions commented out.
func setupBackButton() {
        let backButton = UIBarButtonItem(title: "Back", style: UIBarButtonItemStyle.Plain, target: self, action: #selector(backButtonTapped))
        navigationItem.leftBarButtonItem = backButton
    }
    func backButtonTapped() {
        dismissViewControllerAnimated(true, completion: nil)
    }
    
    func receiveMessagePressed(sender: UIBarButtonItem) {
        /**
         *  DEMO ONLY
         *
         *  The following is simply to simulate received messages for the demo.
         *  Do not actually do this.
         */
        
        /**
         *  Show the typing indicator to be shown
         */
        self.showTypingIndicator = !self.showTypingIndicator
        
        /**
         *  Scroll to actually view the indicator
         */
        self.scrollToBottomAnimated(true)
        
        /**
         *  Copy last sent message, this will be the new "received" message
         */
        var copyMessage = self.messages.last?.copy()
        
        if (copyMessage == nil) {
            copyMessage = JSQMessage(senderId: AvatarIdJobs, displayName: getName(User.Jobs), text: "First received!")
        }
            
        var newMessage:JSQMessage!
        var newMediaData:JSQMessageMediaData!
        var newMediaAttachmentCopy:AnyObject?
        
        if copyMessage!.isMediaMessage() {
            /**
             *  Last message was a media message
             */
            let copyMediaData = copyMessage!.media
            
            switch copyMediaData {
            case is JSQPhotoMediaItem:
                let photoItemCopy = (copyMediaData as! JSQPhotoMediaItem).copy() as! JSQPhotoMediaItem
                photoItemCopy.appliesMediaViewMaskAsOutgoing = false
                
                newMediaAttachmentCopy = UIImage(CGImage: photoItemCopy.image!.CGImage!)
                
                /**
                 *  Set image to nil to simulate "downloading" the image
                 *  and show the placeholder view5017
                 */
                photoItemCopy.image = nil;
                
                newMediaData = photoItemCopy
            case is JSQLocationMediaItem:
                let locationItemCopy = (copyMediaData as! JSQLocationMediaItem).copy() as! JSQLocationMediaItem
                locationItemCopy.appliesMediaViewMaskAsOutgoing = false
                newMediaAttachmentCopy = locationItemCopy.location!.copy()
                
                /**
                 *  Set location to nil to simulate "downloading" the location data
                 */
                locationItemCopy.location = nil;
                
                newMediaData = locationItemCopy;
            case is JSQVideoMediaItem:
                let videoItemCopy = (copyMediaData as! JSQVideoMediaItem).copy() as! JSQVideoMediaItem
                videoItemCopy.appliesMediaViewMaskAsOutgoing = false
                newMediaAttachmentCopy = videoItemCopy.fileURL!.copy()
                
                /**
                 *  Reset video item to simulate "downloading" the video
                 */
                videoItemCopy.fileURL = nil;
                videoItemCopy.isReadyToPlay = false;
                
                newMediaData = videoItemCopy;
            case is JSQAudioMediaItem:
                let audioItemCopy = (copyMediaData as! JSQAudioMediaItem).copy() as! JSQAudioMediaItem
                audioItemCopy.appliesMediaViewMaskAsOutgoing = false
                newMediaAttachmentCopy = audioItemCopy.audioData!.copy()
                
                /**
                 *  Reset audio item to simulate "downloading" the audio
                 */
                audioItemCopy.audioData = nil;
                
                newMediaData = audioItemCopy;
            default:
                assertionFailure("Error: This Media type was not recognised")
            }
            
            newMessage = JSQMessage(senderId: AvatarIdJobs, displayName: getName(User.Jobs), media: newMediaData)
        }
        else {
            /**
             *  Last message was a text message
             */
            
            newMessage = JSQMessage(senderId: AvatarIdJobs, displayName: getName(User.Jobs), text: copyMessage!.text)
        }
        
        /**
         *  Upon receiving a message, you should:
         *
         *  1. Play sound (optional)
         *  2. Add new JSQMessageData object to your data source
         *  3. Call `finishReceivingMessage`
         */
        
        self.messages.append(newMessage)
        self.finishReceivingMessageAnimated(true)
        
        if newMessage.isMediaMessage {
            /**
             *  Simulate "downloading" media
             */
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(1 * Double(NSEC_PER_SEC))), dispatch_get_main_queue()) {
                /**
                 *  Media is "finished downloading", re-display visible cells
                 *
                 *  If media cell is not visible, the next time it is dequeued the view controller will display its new attachment data
                 *
                 *  Reload the specific item, or simply call `reloadData`
                 */
                
                switch newMediaData {
                case is JSQPhotoMediaItem:
                    (newMediaData as! JSQPhotoMediaItem).image = newMediaAttachmentCopy as? UIImage
                    self.collectionView!.reloadData()
                case is JSQLocationMediaItem:
                    (newMediaData as! JSQLocationMediaItem).setLocation(newMediaAttachmentCopy as? CLLocation, withCompletionHandler: {
                        self.collectionView!.reloadData()
                    })
                case is JSQVideoMediaItem:
                    (newMediaData as! JSQVideoMediaItem).fileURL = newMediaAttachmentCopy as? NSURL
                    (newMediaData as! JSQVideoMediaItem).isReadyToPlay = true
                    self.collectionView!.reloadData()
                case is JSQAudioMediaItem:
                    (newMediaData as! JSQAudioMediaItem).audioData = newMediaAttachmentCopy as? NSData
                    self.collectionView!.reloadData()
                default:
                    assertionFailure("Error: This Media type was not recognised")
                }
            }
        }
    }
    
    // MARK: JSQMessagesViewController method overrides
    override func didPressSendButton(button: UIButton, withMessageText text: String, senderId: String, senderDisplayName: String, date: NSDate) {
        /**
         *  Sending a message. Your implementation of this method should do *at least* the following:
         *
         *  1. Play sound (optional)
         *  2. Add new id<JSQMessageData> object to your data source
         *  3. Call `finishSendingMessage`
         */
        
        let message = JSQMessage(senderId: senderId, senderDisplayName: senderDisplayName, date: date, text: text)
        self.messages.append(message)
        self.finishSendingMessageAnimated(true)
    }
    
    override func didPressAccessoryButton(sender: UIButton) {
        self.inputToolbar.contentView!.textView!.resignFirstResponder()
        
        let sheet = UIAlertController(title: "Media messages", message: nil, preferredStyle: .ActionSheet)
        
        let photoAction = UIAlertAction(title: "Send photo", style: .Default) { (action) in
            /**
             *  Create fake photo
             */
            let photoItem = JSQPhotoMediaItem(image: UIImage(named: "goldengate"))
            self.addMedia(photoItem)
        }
        
        let locationAction = UIAlertAction(title: "Send location", style: .Default) { (action) in
            /**
             *  Add fake location
             */
            let locationItem = self.buildLocationItem()
            
            self.addMedia(locationItem)
        }
        
        let videoAction = UIAlertAction(title: "Send video", style: .Default) { (action) in
            /**
             *  Add fake video
             */
            let videoItem = self.buildVideoItem()
            
            self.addMedia(videoItem)
        }
        
        let audioAction = UIAlertAction(title: "Send audio", style: .Default) { (action) in
            /**
             *  Add fake audio
             */
            let audioItem = self.buildAudioItem()
            
            self.addMedia(audioItem)
        }
        
        let cancelAction = UIAlertAction(title: "Cancel", style: .Cancel, handler: nil)
        
        sheet.addAction(photoAction)
        sheet.addAction(locationAction)
        sheet.addAction(videoAction)
        sheet.addAction(audioAction)
        sheet.addAction(cancelAction)
        
        self.presentViewController(sheet, animated: true, completion: nil)
    }
    
    func buildVideoItem() -> JSQVideoMediaItem {
        let videoURL = NSURL(fileURLWithPath: "file://")
        
        let videoItem = JSQVideoMediaItem(fileURL: videoURL, isReadyToPlay: true)
        
        return videoItem
    }
    
    func buildAudioItem() -> JSQAudioMediaItem {
        let sample = NSBundle.mainBundle().pathForResource("jsq_messages_sample", ofType: "m4a")
        let audioData = NSData(contentsOfFile: sample!)
        
        let audioItem = JSQAudioMediaItem(data: audioData)
        
        return audioItem
    }
    
    func buildLocationItem() -> JSQLocationMediaItem {
        let ferryBuildingInSF = CLLocation(latitude: 37.795313, longitude: -122.393757)
        
        let locationItem = JSQLocationMediaItem()
        locationItem.setLocation(ferryBuildingInSF) {
            self.collectionView!.reloadData()
        }
        
        return locationItem
    }
    
    func addMedia(media:JSQMediaItem) {
        let message = JSQMessage(senderId: self.senderId(), displayName: self.senderDisplayName(), media: media)
        self.messages.append(message)
        
        //Optional: play sent sound
        
        self.finishSendingMessageAnimated(true)
    }
    
    
    //MARK: JSQMessages CollectionView DataSource
    
    override func senderId() -> String {
        return User.Wazniak.rawValue
    }
    
    override func senderDisplayName() -> String {
        return getName(User.Wazniak)
    }
    
//    override func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
//        return messages.count
//    }

//    override func collectionView(collectionView: JSQMessagesCollectionView, messageDataForItemAtIndexPath indexPath: NSIndexPath) -> JSQMessageData {
//        return messages[indexPath.item]
//    }

//    override func collectionView(collectionView: JSQMessagesCollectionView, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath) -> JSQMessageBubbleImageDataSource {
//        
//        return messages[indexPath.item].senderId == self.senderId() ? outgoingBubble : incomingBubble
//    }

    override func collectionView(collectionView: JSQMessagesCollectionView, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath) -> JSQMessageAvatarImageDataSource? {
        let message = messages[indexPath.item]
        return getAvatar(message.senderId)
    }

    override func collectionView(collectionView: JSQMessagesCollectionView, attributedTextForCellTopLabelAtIndexPath indexPath: NSIndexPath) -> NSAttributedString? {
        /**
         *  This logic should be consistent with what you return from `heightForCellTopLabelAtIndexPath:`
         *  The other label text delegate methods should follow a similar pattern.
         *
         *  Show a timestamp for every 3rd message
         */
        if (indexPath.item % 3 == 0) {
            let message = self.messages[indexPath.item]
            
            return JSQMessagesTimestampFormatter.sharedFormatter().attributedTimestampForDate(message.date)
        }
        
        return nil
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath) -> NSAttributedString? {
        let message = messages[indexPath.item]
        
        // Displaying names above messages
        //Mark: Removing Sender Display Name
        /**
         *  Example on showing or removing senderDisplayName based on user settings.
         *  This logic should be consistent with what you return from `heightForCellTopLabelAtIndexPath:`
         */
        if defaults.boolForKey(Setting.removeSenderDisplayName.rawValue) {
            return nil
        }
        
        if message.senderId == self.senderId() {
            return nil
        }

        return NSAttributedString(string: message.senderDisplayName)
    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout, heightForCellTopLabelAtIndexPath indexPath: NSIndexPath) -> CGFloat {
        /**
         *  Each label in a cell has a `height` delegate method that corresponds to its text dataSource method
         */
        
        /**
         *  This logic should be consistent with what you return from `attributedTextForCellTopLabelAtIndexPath:`
         *  The other label height delegate methods should follow similarly
         *
         *  Show a timestamp for every 3rd message
         */
        if indexPath.item % 3 == 0 {
            return kJSQMessagesCollectionViewCellLabelHeightDefault
        }
        
        return 0.0
    }

    override func collectionView(collectionView: JSQMessagesCollectionView, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout, heightForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath) -> CGFloat {
        
        /**
         *  Example on showing or removing senderDisplayName based on user settings.
         *  This logic should be consistent with what you return from `attributedTextForCellTopLabelAtIndexPath:`
         */
        if defaults.boolForKey(Setting.removeSenderDisplayName.rawValue) {
            return 0.0
        }
        
        /**
         *  iOS7-style sender name labels
         */
        let currentMessage = self.messages[indexPath.item]
        
        if currentMessage.senderId == self.senderId() {
            return 0.0
        }
        
        if indexPath.item - 1 > 0 {
            let previousMessage = self.messages[indexPath.item - 1]
            if previousMessage.senderId == currentMessage.senderId {
                return 0.0
            }
        }
        
        return kJSQMessagesCollectionViewCellLabelHeightDefault;
    }
    
}

**Comment by MacMeDan** [comment]
So I would assume you are just not implementing one of the methods that is here.

**Comment by MacMeDan** [comment]
ahh It is only on the ipad?

**Comment by MacMeDan** [comment]
Simulator or not?

**Comment by pprevalon** [comment]
not simulator

**Comment by MacMeDan** [comment]
mk Let me see if its the same for me.

**Comment by MacMeDan** [comment]
and what model Ipad?

**Comment by pprevalon** [comment]
im on Ipad 2, with the latest firmware I thought about that, but i didnt think the model would cause an issue like that. I will try and run it on ipad simulator.

**Comment by pprevalon** [comment]
It looks like this happen only when retrieving messages while VC is presenting the last two messages were sent after the vc was presented


![imag0388](https://cloud.githubusercontent.com/assets/19171619/18403011/60a38454-76b0-11e6-8d01-f4d95a70f002.jpg)

**Comment by MacMeDan** [comment]
Interesting🤔. Then may be it would be solved if you had a completion block on your fetching of the messages and reload the table after it is successful.

**Comment by jessesquires** [comment]
Going to go ahead and close this but feel free to keep discussing! 😄
