### ISSUE TITLE
How to send document file ?

### ISSUE THREAD

**Issue by commando24** [jessesquires/JSQMessagesViewController#1822]
how to send document file using JSQMessageViewController?

**Comment by Lucashuang0802** [comment]
Hi @commando24. `JSQMediaItem.h` and `JSQMessageMediaData.h` might be something you want to take a look. In `JSQMessageMediaData.h` protocol, the property of `mediaData` might be the point to reach to what you want. From UI, It might have a way to visually make it work.

**Comment by Lucashuang0802** [comment]
Sorry, forget to mention one point. There is no direct way to send document files right now. But, I believe we are able to do that by using existing classes. 😃
