### ISSUE TITLE
Update Swift example project to Xcode 8 GM Swift 3.0 syntax

### ISSUE THREAD

**Issue by gerbiljames** [jessesquires/JSQMessagesViewController#1824]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 7.3.4
- iOS version(s): All
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): Yes (Swift)
- Related issues: N/A

### Expected behavior
The Swift example project should compile and run under Xcode 8 GM without 'Use Legacy Swift Language Version' being set to yes.

### Actual behavior
Many compile errors.

### Steps to reproduce
Attempt to build the Swift example project in Xcode 8 GM

**Comment by Lucashuang0802** [comment]
Per comment here: https://github.com/jessesquires/JSQMessagesViewController/issues/1608#issuecomment-231757563. I don't think it's an issue until XCode 8 get released officially.

**Comment by NemOry** [comment]
I can't wait till JSQMessagesViewController will work with Swift 3. Great tool!

**Comment by swiftnative** [comment]
thanks for the great library. Are there plans for a swift3 version? if so, any guess at the timeframe? Thanks!

**Comment by alejandrorbradford** [comment]
this isn't working on Swift 3 nor 2.3?

**Comment by MacMeDan** [comment]
Sorry guys I will see if I have some time too look into updating the swift example this week. 🤗

**Comment by MacMeDan** [comment]
Or also anyone can do this 😁

**Comment by gerbiljames** [comment]
@MacMeDan Done already! PR at #1825.

**Comment by MacMeDan** [comment]
nice @gerbiljames

**Comment by jessesquires** [comment]
merged PR
