### ISSUE TITLE
Timestamp increased by 2 hours

### ISSUE THREAD

**Issue by Pacyjent** [jessesquires/JSQMessagesViewController#1826]
I'm using cocoapods and I think that this issue came up after subclassing BubbleSizeCalculator.
![screen shot 2016-09-12 at 10 44 18](https://cloud.githubusercontent.com/assets/16843337/18429969/adf0247e-78d6-11e6-8104-9f5a0ffc6ab8.png)

Thanks for reply.

**Comment by jessesquires** [comment]
Thanks! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:

**Comment by Pacyjent** [comment]
I'll try to provide some more informations later, in short it's on OS X 10.11.6, Xcode 7.3 (7D175) and 9.3.5 (13G36) 5S and simulator of iPhone 6 on 9.3 (13E230) and latest commit from develop branch. I don't need to help with this, I'll make it on my own, but I only want to share this weird bug. Maybe it's something with time zone but when I start project with your framework everything works fine.

**Comment by Lucashuang0802** [comment]
@Pacyjent It' actually quite difficult for us to address the issue you have. Perhaps can you replicate it in the demo project? That will be helpful. 😃
