### ISSUE TITLE
Crash didpresSend Func

### ISSUE THREAD

**Issue by Laynay** [jessesquires/JSQMessagesViewController#1830]
## New issue checklist

- [O] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [O] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [O] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): last
- iOS version(s): iOS 10
- Devices/Simulators affected: all (using iPhone 6s)

## Bug report

Hi, I have an error while i'm sending a message to firebase, i understand the problem but i don't know why it is:

My code:  override func didPressSend(_ button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: Date!) {
        
        let newMessageRef = messageRef.child(roomId).childByAutoId()
        let mes = ["text": text, "senderId": senderId, "senderName": senderDisplayName, "MediaType": "text"]
        newMessageRef.setValue(mes)
        
        self.finishSendingMessage()
        
    }

My error: 

2016-09-16 16:01:37.323  *** Terminating app due to uncaught exception 'InvalidFirebaseData', reason: '(setValue:) Cannot store object of type _SwiftValue at senderName. Can only store objects of type NSNumber, NSString, NSDictionary, and NSArray.'
*** First throw call stack:
(
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Thank you.

**Comment by jmstone617** [comment]
You should cast your `String` objects to `NSString` objects, such as `senderId as NSString`

**Comment by Laynay** [comment]
Thank you, i resolved!

**Comment by Laynay** [comment]
Thank you, i resolved.
