### ISSUE TITLE
Is avatarImageWithImageURL no longer available?

### ISSUE THREAD

**Issue by tnahvu** [jessesquires/JSQMessagesViewController#1831]
I've noticed that a sample app from Sendbird has avatarImageWithImageURL method in the JSQMessagesAvatarImageFactory.h file, but I don't see that method after installing via cocoapod.  

I do see these methods in JSQMessagesAvatarImageFactory.h
avatarImageWithPlaceholder:
avatarImageWithImage:
circularAvatarImage:
circularAvatarHighlightedImage:
avatarImageWithUserInitials:

I need to update profile image via url from Sendbird User object.  I'm also using SDWebImage but want to check in here before messing with SDWebImage and JSQMessageVC together.

Thanks

**Comment by Lucashuang0802** [comment]
If you don't see `avatarImageWithImageURL`, it's indeed deprecated I believe. You can always check out release notes here: https://github.com/jessesquires/JSQMessagesViewController/releases. As for your change, you can  do the following to get the `UIImage` and input to `avatarImageWithImage:`:
```
NSURL *url = [NSURL URLWithString:path];
NSData *data = [NSData dataWithContentsOfURL:url];
UIImage *img = [[UIImage alloc] initWithData:data];
```
😃

**Comment by tnahvu** [comment]
My concern with this solution is performance...but I think I have come up with a solution that works for my situation.  Thanks!
