### ISSUE TITLE
Is it possible to ignore blank lines and stop the toolbar expanding?

### ISSUE THREAD

**Issue by kekearif** [jessesquires/JSQMessagesViewController#1832]
Hey. Is there any method to ignore blank lines when typing a message and stop the toolbar from expanding upwards? For example taping return 3 times will expand the toolbar even if text isn't present. I want to disable this. However If I type a word and then hit return three times this is okay.

**Comment by Lucashuang0802** [comment]
There is no direct way to support it right now but there is a couple way you can do it from `JSQMessagesComposerTextView.m`.
- disabling the `self.heightConstraint` on LOC107 so it won't actually affect the height
- remove notification by calling `jsq_removeTextViewNotificationObservers` so it won't actually update but it will have side effects that result in placeholder remaining.
