### ISSUE TITLE
Wrong bubble size (v 7.3.4., Swift, iOs 10)

### ISSUE THREAD

**Issue by halvini** [jessesquires/JSQMessagesViewController#1835]
## Bug report

The message bubble size is wrong on iOs 10:
![jsq_bug](https://cloud.githubusercontent.com/assets/16026223/18662504/59e408c0-7f23-11e6-91b7-665cd0fe3ff9.png)

I tried setting the leftRightMargin too and it didn't work at all:
`var leftRightMargin: CGFloat = 50
        self.collectionView!.collectionViewLayout.messageBubbleLeftRightMargin = leftRightMargin
`
### Expected behavior

There should be a margin of at least 20-50 points between the edge of the screen and the bubble.
### Steps to reproduce

It started happening since the iOs 10 update, XCode 8.

**Comment by halvini** [comment]
Any news regarding this issue?

I had to step down to JSQ 7.2.0 which is more stable, but the new iOs 10 emojis make the bubbles cut some text all the time. That means there is wrong sizing in bubbles.

How can I fix at least that in 7.2.0?

**Comment by Lucashuang0802** [comment]
@halvini were you able to replicate in the demo project?

**Comment by rslim087g** [comment]
its happening to me to, i was able to fix it by putting reloaddata in viewdidappear. which fixes it visually.. which is really ugly...

does anybody have any other ideas??

**Comment by rslim087g** [comment]
I don't know if this will work for you, but I added this at the bottom of my chat controller

> class Message: JSQMessage {
>     // add extra functionality that you need
>     override func messageHash() -> UInt {
>         let messageHash = UInt(arc4random()) //messageHash()
>         return UInt(messageHash)
>     }
> }

and it fixed everything.

**Comment by halvini** [comment]
@Lucashuang0802 I haven't replicated it in the demo project. I just reverted back to 7.2.0 after many attempts of fixing the issue.

**Comment by rubensneto** [comment]
@halvini Based on [this](https://github.com/jessesquires/JSQMessagesViewController/issues/1075#issuecomment-120508541) question, I came up with something that worked for me.
1 - Create a subclass of `JSQMessagesCollectionViewFlowLayout`  with following code:

```
class MessagesCollectionViewFlowLayout: JSQMessagesCollectionViewFlowLayout {
    override func messageBubbleSizeForItem(at indexPath: IndexPath!) -> CGSize {
        
        var superSize = super.messageBubbleSizeForItem(at: indexPath)
        
        let screenSize = UIScreen.main.bounds
        let screenWidth = screenSize.width
        let desiredBubbleWidth = screenWidth / 3 * 2
        
        if superSize.width > desiredBubbleWidth {
            superSize = CGSize(width: desiredBubbleWidth, height: superSize.height)
        }
 
        return superSize
    }
}
```

2 - In your `chatViewController`, inside `viewDidLoad`, set your subclass as the collection view layout:

`self.collectionView.collectionViewLayout = MessagesCollectionViewFlowLayout()`

I hope it helps.
Cheers

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
