### ISSUE TITLE
Modificate messageBubbleTopLabel problem

### ISSUE THREAD

**Issue by Laynay** [jessesquires/JSQMessagesViewController#1837]
## New issue checklist

- [o] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [o] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [o] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): lastest
- iOS version(s): IOS 10
- Devices/Simulators affected: iPhone 6s
- Reproducible in the demo project? (Yes/No): N/d
- Related issues:N/D

Hi, I have a problem with a messageBubbleTopLabel, I can not find how I can change it, for example: the color, font and position, after the previous message. I would serve for senderName.

Where and how can I make these changes, thank you all!

**Comment by MacMeDan** [comment]
You are going to want to check out this method.
 `override func collectionView(collectionView: JSQMessagesCollectionView?, attributedTextForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
//Logic here
}`

This is where you can change the text for the `topLabel` and you can add any attributes that you would like I.E. Color, font

I don't know off the top of my head where positioning for that is.

You also will need to implement this method

` override func collectionView(collectionView: JSQMessagesCollectionView?, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout?, heightForMessageBubbleTopLabelAtIndexPath indexPath: NSIndexPath!)`

and change the logic if you want to show or hide the top label in different situations IE multiple messages from the same user in a row.

I hope that this helps you head in the right direction. Let me know if you need more help or have more questions. 🖖🏽

**Comment by Laynay** [comment]
Do you know the code for modificate the font or something there?

Thank you a lot for your help!

**Comment by MacMeDan** [comment]
Ya you can do it with the attributes 
setup your attributes and then add them to your font.
     `let string = "Attributed String"
       let fontAttribute = [ NSFontAttributeName: UIFont(name: "Chalkduster", size: 18.0)! ]
       let attributedString = NSAttributedString(string: string, attributes: fontAttribute) `

You also can put multiple attributes in that array, configuring multiple attributes at once. 
like this:
` let fontAttribute = [ NSFontAttributeName: UIFont(name: "Chalkduster", size: 18.0)!, NSForegroundColorAttributeName: UIColor.blueColor() , NSUnderlineStyleAttributeName: NSUnderlineStyle.StyleSingle.rawValue ]`

There is a ton you can do with Attributed Strings. Hope that helps 🤘

**Comment by Laynay** [comment]
Really thank you!

**Comment by MacMeDan** [comment]
Happy to help 🎉
