### ISSUE TITLE
custom bubble which tail not at the corner

### ISSUE THREAD

**Issue by zhouzhongguang** [jessesquires/JSQMessagesViewController#1839]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

how to customise a bubble use custom image like following image the tail is not on the corner.

![chat_icon_bubble_min_incomming_file 2x](https://cloud.githubusercontent.com/assets/10241716/18744266/baee7c72-80ef-11e6-8496-93e3f170911b.png)

And when the message text is more than one line, it  stretchabled like this 
![2016-09-22 6 11 18](https://cloud.githubusercontent.com/assets/10241716/18744360/3c2e300c-80f0-11e6-81aa-7b46d5a1fe0a.png)

I try it use following codes in cellForItemAtIndexPath:

```
JSQMessagesBubbleImageFactory *bubbleFactory = [[JSQMessagesBubbleImageFactory alloc] initWithBubbleImage:[UIImage imageNamed:@"chat_icon_bubble_min_outgoing"] capInsets:UIEdgeInsetsMake(1.0f, 1.0f, 1.0f, 6.0f)];
        JSQMessagesBubbleImage *bubbleImageDataSource;

        if ([messageRecord.messageSenderUserId isEqualToString:self.senderId]) {
            bubbleImageDataSource = [bubbleFactory outgoingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleLightGrayColor]];
        } else {
            bubbleImageDataSource = [bubbleFactory incomingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleGreenColor]];
        }
        cell.messageBubbleImageView.image = [bubbleImageDataSource messageBubbleImage];
        cell.messageBubbleImageView.highlightedImage = [bubbleImageDataSource 
```
But the bubbleImage showing this 
![2016-09-22 6 17 21](https://cloud.githubusercontent.com/assets/10241716/18744494/d26b6404-80f0-11e6-9705-a99df72556f6.png)

Could anyone lend some tips on achieving this?

**Comment by eliburke** [comment]
I'm pretty sure the problem is your linsets. Look at your source image. The full radius of the corners needs to be captured in the capInsets that you pass to JSQMessagesBubbleImageFactory. Read about [UIImage resizableImageWithCapInsets:] if you want to know more about how it works.

**Comment by zhouzhongguang** [comment]
Thank you for your reply, after learn more about [UIImage resizableImageWithCapInsets:] , I reset the capInsets to UIEdgeInsetsMake(30.0f, 10.0f, 6.0f, 10.0f) and everything is OK. Perfect!

Thank you very much!
![simulator screen shot 2016 9 22 11 32 13](https://cloud.githubusercontent.com/assets/10241716/18754901/d0dcb968-811c-11e6-9f57-9a85506aa60d.png)

**Comment by eliburke** [comment]
I'm glad it helped! 😄

**Comment by apryiomka** [comment]
What is the correct image format? I am trying to implement custom bubble image and it is not working. I get rectangular with the specified color.

**Comment by ikyh** [comment]
@zhouzhongguang Hey I did exactly the same way you did but in swift 3. But I am getting something like this:
![msgbubble](https://user-images.githubusercontent.com/29946749/33547966-b310fe6a-d90b-11e7-965a-7be697d68026.png)

Can you please help me out with this. Thanks in advance : )

**Comment by jitesh-sharma** [comment]
After reset the capInsets, all is going good but in rare cases some of collectioncell bubble overlap the bottom view. And also clip the bubble imageview in XIb. But still facing this issue in some cells. Please see below image.
![simulator screen shot - iphone 8 - 2018-01-19 at 10 32 50](https://user-images.githubusercontent.com/25661009/35135586-2f1a529c-fd04-11e7-8213-0428796f7647.png)
