### ISSUE TITLE
JSQMediaItem disappears while scrolling

### ISSUE THREAD

**Issue by bitnpc** [jessesquires/JSQMessagesViewController#1840]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: _YES___
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
### General information
- Library version(s):7.3.4
- iOS version(s):iOS 10
- Devices/Simulators affected:YES
- Reproducible in the demo project? (Yes/No): YES
- Related issues:None
## Bug report

The mediaView in JSQMediaItem disappears when running in iOS 10 devices.
Both in simulators and iPhones.
### Expected behavior

Show without disappearing
### Actual behavior

Disappearing from screen.
### Steps to reproduce
1. build and run. 

2.Setting -> Load extra messages.

3.Back and push via storyboard or programatically.
### Crash log? Screenshots? Videos? Sample project?

<img width="375" alt="problem" src="https://cloud.githubusercontent.com/assets/4088941/18772289/39ffb214-8178-11e6-9bfd-ca204a0ff756.png">
<img width="366" alt="viewdebug" src="https://cloud.githubusercontent.com/assets/4088941/18772292/40238dd2-8178-11e6-95cc-715940f37ede.png">

**Comment by Lucashuang0802** [comment]
@bitnpc Unfortunately, I have tried a couple times and could not replicate it. Can you check it again or did you miss any steps? It tried on iPhone `iPhone 6s plus(10.0)`.

**Comment by Lucashuang0802** [comment]
@bitnpc It's indeed a bug. I did not find it here but from the investigation in #1842. Gonna mark it as a bug.

**Comment by LamourBt** [comment]
I having something similar, but not while scrolling if you send consecutive media you would not be able to see them, you would see one but not the others. 
![screen shot 2016-09-26 at 10 14 04 am](https://cloud.githubusercontent.com/assets/14245117/18837625/6c846f66-83d2-11e6-804c-003857a66318.png)

**Comment by algrid** [comment]
It looks like the problem is in this piece of code in DemoModelData.m:
```
    /**
     *  Setting to load extra messages for testing/demo
     */
    if ([NSUserDefaults extraMessagesSetting]) {
        NSArray *copyOfMessages = [self.messages copy];
        for (NSUInteger i = 0; i < 4; i++) {
            [self.messages addObjectsFromArray:copyOfMessages];
        }
    }
```
A shallow copy of messages is created and then appended to self.messages. Media messages contain mediaView - we end up with same mediaView for several cells.

**Comment by lastObject** [comment]
did you override hash?

**Comment by bitnpc** [comment]
@lastObject 
No, I didn't modify anything. It's the demo data that needs deep copied.

**Comment by sudhamab** [comment]
Hi we are facing this too. Could you please share a snippet of code that we can use to fix this in the mean time? Our users are facing this and we are hoping to fix it asap. Your help would be much appreciated.

**Comment by algrid** [comment]
@sudhamab Just make sure that you're always creating new message objects, not copying existing ones and you shouldn't get such problems.

**Comment by gmansata6290** [comment]
I am using swift. And I m not using any copy function also. Within the for loop only creating local objects and appending to array of JSQMessage. 

for message in dbMessages
{
         messages.append(JSQMessage(senderId: message.from, senderDisplayName: "", date:      NSDate(timeIntervalSince1970: message.create_time/1000), text: message.message))
}

will this cause an issue?

**Comment by algrid** [comment]
@gmansata6290 The original issue is with media items. In your code you're creating text messages only - you just have no images to disappear :)

If you still have some problems then this might be a separate issue.

**Comment by Huang-Libo** [comment]
I encounter this issue in the demo..

**Comment by gmansata6290** [comment]
Any solution to this issue? because my app is live and app users are facing this issue. please help me out in this. Your help would be a much appreciated.

**Comment by sudhamab** [comment]
@jessesquires, any suggestions on how to deal with this? Its affecting our users and would sincerely appreciate if this bug can be resolved and a patch be released. Cant seem to trace the root cause

**Comment by sudhamab** [comment]
Hi guys, just wanted to check if you had any luck with this issue. Our goal has always been to have a Fast, Easy and Reliable app and Chat is integral to our service. Would appreciate some direction, so one's we fix this, we will be ballers! :)

**Comment by gmansata6290** [comment]
Hi guys, so i solved this issue. You were right. This issue was mainly  due to the hash generation in my custom media item. My custom media item was having pre formatted html(NSAttributed String) in the textView. And I was actually considering the hashValue of the view. This was creating the issue. So I converted the html(NSAttributed String) into a string and took it's hashValue and it works well.

Thanks to @jessesquires and others working on this library for all the amazing effort you guys have put in to make it so customizable.  

Regards,
Ghanshyam

**Comment by Lucashuang0802** [comment]
@gmansata6290, thanks for confirming the issue. Please do not hesitate to continue here if you still find anything related. Awesome! 👍 💯

**Comment by gmansata6290** [comment]
@Lucashuang0802 sorry to say but the issue i was facing that is working good so far by applying hash. But still SwiftExample from develop branch still persist this issue. You can just replicate this issue by loading any conversation with more than 15-20 messages and if you scroll up and down you will see that PhotoMediaItem and AudioMediaItem disappears.
