### ISSUE TITLE
[iOS 10] Bubble text: last line truncated

### ISSUE THREAD

**Issue by Uscher1** [jessesquires/JSQMessagesViewController#1842]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
### General information
- Library version(s): 7.3.4
- iOS version(s): 10.0.1
- Devices/Simulators affected: 5S/6S/Simulator
- Reproducible in the demo project? (Yes/No): YES - with text provided below
- Related issues: none
## Bug report

For some special text strings, e.g.
@"Wunderschönen Guten Morgaaaahhhn 😝 - hast du gut geschlafen ☺️😘"
@"Guten Morgen. Ja, ziemlich gut, mal sicher länger wie du. 😉 Einen superschönen Tag wünsche ich dir. ☀️"
the last text line in the bubble is truncated (missing).
### Expected behaviour

Full text should be visible.
### Actual behaviour

Last text line is missing, but a blank space is shown.
### Steps to reproduce

Add sample text above to demo project in file DemoModelData.m or use file attached and change extension.
[DemoModelData.txt](https://github.com/jessesquires/JSQMessagesViewController/files/491577/DemoModelData.txt)
You will see result as shown below.
### Screenshot

![simulator screen shot 25 sep 2016 12 38 23](https://cloud.githubusercontent.com/assets/6658564/18814756/2babdf52-831d-11e6-85c5-dab2fb527302.png)

**Comment by Lucashuang0802** [comment]
I have tried the code and it's indeed a bug.

**Comment by Lucashuang0802** [comment]
![simulator screen shot sep 25 2016 10 31 05 pm](https://cloud.githubusercontent.com/assets/3754490/18823523/d01e6508-836f-11e6-84d9-a180d096dc83.png)

**Comment by LamourBt** [comment]
I having something similar, but not while scrolling if you send consecutive media you would not be able to see them, you would see one but not the others.

![screen shot 2016-09-26 at 10 14 04 am](https://cloud.githubusercontent.com/assets/14245117/18837515/03477a7a-83d2-11e6-8000-2232685f4103.png)

**Comment by Liampronan** [comment]
I ran into this issue as well and think it's related to how some emojis are rendered. Below's a few examples with some of the emojis I've found that trigger it  -- these emojis (e.g., ‼️, ⁉️, ☀️) seem to be a bit below the vertical center of the bubble and have caused the above-described bug (while the emojis that layout in the center do not seem to cause the bug). Will report back if I come across a fix...

![simulator screen shot sep 29 2016 10 16 40 pm](https://cloud.githubusercontent.com/assets/4316904/18981370/7d85fe3e-8692-11e6-9fa5-b999fdf60dff.png)

**Comment by Liampronan** [comment]
seems to be a bug in iOS 10 displaying some emojis -- here are two relate issues which describe a workaround:
https://github.com/facebook/AsyncDisplayKit/issues/2304

https://github.com/master-nevi/ClippedEmoji (see 'Current Workaround')

also, relevant radar: https://openradar.appspot.com/radar?id=4998540401049600

**Comment by brunsman** [comment]
Now using this as a workaround: 

Create your own JSQMessagesBubbleSizeCalculating (just copy the existing JSQMessagesBubblesSizeCalculator) and set this self created calculator as your bubbleSizeCalculator:

```
self.collectionView.collectionViewLayout.bubbleSizeCalculator = self.myBubbleSizeCalculator;
```

In `myBubbleSizeCalculator.messageBubbleSizeForMessageData` replace
```
CGRect stringRect = [[messageData text] boundingRectWithSize:CGSizeMake(maximumTextWidth, CGFLOAT_MAX)
  options:(NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading)
  attributes:@{ NSFontAttributeName : layout.messageBubbleFont }
  context:nil];
```

with

```
CGRect stringRect;
BOOL isIOS10OrGreater = [[NSProcessInfo processInfo] isOperatingSystemAtLeastVersion:(NSOperatingSystemVersion){.majorVersion = 10}];
if (isIOS10OrGreater) {
  NSDictionary *attributes = @{NSFontAttributeName: layout.messageBubbleFont};
  NSMutableAttributedString *string = [[NSMutableAttributedString alloc] initWithString:[messageData text] attributes:attributes];
  [string fixAttributesInRange:NSMakeRange(0, string.length)];
  [string enumerateAttribute:NSFontAttributeName inRange:NSMakeRange(0, string.length) options:0 usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
    UIFont *font = (UIFont *)value;
    if ([font.fontName isEqualToString:@".AppleColorEmojiUI"]) {
      [string addAttribute:NSFontAttributeName value:[UIFont fontWithName:@"AppleColorEmoji" size:font.pointSize] range:range];
    }
  }];
  stringRect = [string boundingRectWithSize:CGSizeMake(maximumTextWidth, CGFLOAT_MAX)
    options:(NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading)
    context:nil];
} else {
  stringRect = [[messageData text] boundingRectWithSize:CGSizeMake(maximumTextWidth, CGFLOAT_MAX)
    options:(NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading)
    attributes:@{ NSFontAttributeName : layout.messageBubbleFont }
    context:nil];
}
```
It's not perfect, but at least all text is displayed.

**Comment by Uscher1** [comment]
Thank you for this workaround. It's not truncated anymore, but the border below has become bigger.

![img_1349](https://cloud.githubusercontent.com/assets/6658564/19039872/f7cfeabe-8981-11e6-9fa3-7ad5e36f1a34.jpg)

**Comment by michaelkirk** [comment]
Crappy fix, which seems to leave less extraneous spacing than @brunsman's fix. 

...though I seriously doubt the robustness of this solution:

```
@interface OMGMessagesBubblesSizeCalculator : JSQMessagesBubblesSizeCalculator
@end

@implementation OMGMessagesBubblesSizeCalculator
    CGSize size = [super messageBubbleSizeForMessageData:messageData atIndexPath:indexPath withLayout:layout];
    BOOL isIOS10OrGreater = [[NSProcessInfo processInfo] isOperatingSystemAtLeastVersion:(NSOperatingSystemVersion){.majorVersion = 10}];
    if (isIOS10OrGreater) {
        // Super hack!
        size.height += 3.0f;
    }
    return size;
@end
```

**Comment by michaelkirk** [comment]
Stepping through the debugger, I've verified that @brunsman's fix addes ~11px of height to the bounding rect in the case of the string: @"Wunderschönen Guten Morgaaaahhhn 😝 - hast du gut geschlafen ☺️😘"

```
(lldb) po originalStringRect
(origin = (x = 0, y = 0), size = (width = 249.38720703125, height = 64.287109375))

(lldb) po stringRect
(origin = (x = 0, y = 0), size = (width = 248.38720703125, height = 75.8125))
```

Looking into this, my understanding of the source of the bug is that we can't correctly compute the bounding rect of text using the new `.AppleColorEmojiUI` font. @brunsman's fix thus replaces any occurrence of `AppleColorEmojiUI` with the old `AppleColorEmoji ` font. This seems like a smart fix (thanks @brunsman!).

Though this leaves us in a situation where are bubbles are still using the `AppleColorEmojiUI` font, in a rectangle built for the old `AppleColorEmoji` font. Leaving the extra space.

If you want to completely revert to using the old font, I recommend you also override the use of the font in your MVC, e.g. the kludgey version looks something like:

```
- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView
                  cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    UICollectionViewCell *cell = [super collectionView:(JSQMessagesCollectionView *)collectionView
                  cellForItemAtIndexPath:(NSIndexPath *)indexPath];

    // replace instances of broken emoji font with old and trusty emoji font.
    NSDictionary *attributes =  @{ NSFontAttributeName : self.collectionView.collectionViewLayout.messageBubbleFont };
    NSMutableAttributedString *string = [[NSMutableAttributedString alloc] initWithString:[message text] attributes:attributes];
    [string fixAttributesInRange:NSMakeRange(0, string.length)];
    [string enumerateAttribute:NSFontAttributeName inRange:NSMakeRange(0, string.length) options:0 usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
        UIFont *font = (UIFont *)value;
        if ([font.fontName isEqualToString:@".AppleColorEmojiUI"]) {
            DDLogDebug(@"Detected broken emoji font at location: %lu, for length: %lu", (unsigned long)range.location, (unsigned long)range.length);
            [string addAttribute:NSFontAttributeName value:[UIFont fontWithName:@"AppleColorEmoji" size:font.pointSize] range:range];
        }
    }];

    cell.textView.attributedText = string;
    return cell;
}
```

**Comment by SS0424** [comment]
Who has a new solution？
![2016-11-21 10 57 31](https://cloud.githubusercontent.com/assets/13725793/20469262/7f416220-afd9-11e6-8ad8-9fd27d9c9047.png)

**Comment by williamgp** [comment]
Its not just an iOS 10 issue.  I'm seeing the same issue (last line being truncated) in iOS 9.3.5

**Comment by Anant89** [comment]
**Last text line is missing, but a blank space is shown.**
I got a solution 

1. Find in your project "_additionalInset".
2. just give _additionalInset = 7;

Problem solve.
last line text will show, there is no truncated.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
