### ISSUE TITLE
The "Load Earlier Messages" button is hidden

### ISSUE THREAD

**Issue by 3990995** [jessesquires/JSQMessagesViewController#1843]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): develop
- iOS version(s): iOS 10
- Devices/Simulators affected: device iphone6s
- Reproducible in the demo project? (Yes/No): yes
- Related issues:none

## Bug report
first message hide half...
### Steps to reproduce
run demo , Load Earlier Messages button is hide,scroll bottom the hide too.

then textview become first,then scroll bottom the Load Earlier Messages button is show....

### Crash log? Screenshots? Videos? Sample project?
![img_2295](https://cloud.githubusercontent.com/assets/1081005/18857667/818a742a-8498-11e6-94e5-a04a96cc86a6.PNG)
![img_2296](https://cloud.githubusercontent.com/assets/1081005/18857750/193f79c8-8499-11e6-900f-31d53e753c95.PNG)
![img_2297](https://cloud.githubusercontent.com/assets/1081005/18857754/1ca8563e-8499-11e6-8a7b-8dcd1677c382.PNG)

**Comment by Lucashuang0802** [comment]
@3990995 You can track the same issue on #1785. 😃
