### ISSUE TITLE
Language not supported, how do I change language for send button / textview placeholder? 

### ISSUE THREAD

**Issue by kiwo12345** [jessesquires/JSQMessagesViewController#1846]
How do I change language for send button / textview placeholder ?
I need Swedish language, and its not supported. I made a [pull request](https://github.com/jessesquires/JSQMessagesViewController/pull/1847#issuecomment-250512113) to add it

## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by Lucashuang0802** [comment]
You can provide your localization just like the sample does. You can check out the `Localizable.strings` under `JSQMessagesDemo` folder. 😃

**Comment by kiwo12345** [comment]
@Lucashuang0802 I added this PL :) https://github.com/jessesquires/JSQMessagesViewController/pull/1847
