### ISSUE TITLE
Empty space at the beginning, at the bottom 

### ISSUE THREAD

**Issue by ignacio-chiazzo** [jessesquires/JSQMessagesViewController#1850]
I have a Viewcontroller that's a container view, the JSQMessageViewController lies in this controller. The problem that I am getting is that at the beginning when I enter to the app, there is a space between the first message and the top of the view, (the JSQMVC navigation bar is hidden ). It seems to be related to this issue #1158 
### General information
- Library version(s): 7.2.0
- iOS version(s): Swift 2.2
- Devices/Simulators affected: All that I've used, iPhone 5,6 and some iPods 
- Related issues:  [https://github.com/jessesquires/JSQMessagesViewController/issues/1158](Issue).

![screen shot 2016-10-04 at 1 30 31 pm](https://cloud.githubusercontent.com/assets/11672878/19083013/dcb2793a-8a36-11e6-8d80-d710ad56701b.png)

![screen shot 2016-10-04 at 1 31 59 pm](https://cloud.githubusercontent.com/assets/11672878/19083079/28681272-8a37-11e6-9860-ab03019ce1c7.png)

**Comment by ignacio-chiazzo** [comment]
@Lucashuang0802 There is a solution for this issue? or a quick workaround?

**Comment by algrid** [comment]
@ignacio-chiazzo Could you try this PR?
https://github.com/jessesquires/JSQMessagesViewController/pull/1866
I changed inset calculations a bit.

**Comment by Lucashuang0802** [comment]
hey @ignacio-chiazzo, it's closed because we believe it was fixed. But, you are more than welcomed to report again if you found it un-fixed. 😃

**Comment by ignacio-chiazzo** [comment]
@Lucashuang0802  In the  version 7.2.0 is not working, How can I fix it?

**Comment by Lucashuang0802** [comment]
Based on #1158, I don't have enough information to tell which version has the fix. Perhaps you can try 7.3.4 or `develop`? Please note, `develop` branch should always for development. 😃

**Comment by jessesquires** [comment]
Thanks @ignacio-chiazzo ! 

Can you update to `7.3.4` and see if you still have this issue?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
