### ISSUE TITLE
topContentAdditionalInset updates after some delay.

### ISSUE THREAD

**Issue by firozkhursheed** [jessesquires/JSQMessagesViewController#1851]
- [ Done ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
### General information
- iOS version(s): 10.0
- Devices/Simulators affected: Both
- Reproducible in the demo project? (Yes/No):  No
## Bug report

I have added a custom view on JSQMessagsesViewController subclass and using topContentAdditionalInset to provide space to that view on top. JSQMessagsesViewController is embeded in navigation controller. For the first time when user enters JSQMessagsesViewController the custom view is present but after one pops out and again goes to JSQMessagsesViewController the custom view is not present but appears after some delay. I'm setting the custom view and topContentAdditionalInset in viewDidLoad(). 
So the problem is the custom view is already there but topContentAdditionalInset updates after some time once the JSQMessagsesViewController is visible.

The above problem is only with iOS 10.
It works properly in iOS 9 and 8.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
