### ISSUE TITLE
Bug in 7.3.4: 2nd line of a message with an emoji character is not being shown

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1852]
### General information
- Library version(s): 7.3.4
- iOS version(s): 10
- Devices/Simulators affected: iPhone 6 plush
- Reproducible in the demo project? (Yes/No): yes
## Bug report

The message string "Hello, can I get a small latte with one for takeaway? ☕️" is shown only the first line but not the second one.
### Steps to reproduce

Run demo code (Objective-C). Enter a string with an emoji character of coffee in the end:
Hello, can I get a small latte with one for takeaway? ☕️

![img_3079](https://cloud.githubusercontent.com/assets/1370755/19097340/a9932a86-8aef-11e6-8fff-3fce9778fc99.PNG)

**Comment by nguyenpham** [comment]
The current version in development works fine with above message

**Comment by Lucashuang0802** [comment]
@nguyenpham thanks for letting us know. I am going to close this issue but feel free to comment on it if you find it replicable. 😃

**Comment by jessesquires** [comment]
Hm... let's investigate this with 7.3.4. We may need to release 7.3.5

**Comment by jessesquires** [comment]
See:

https://github.com/master-nevi/ClippedEmoji

Not sure if this is the bug we are seeing here or not.

**Comment by nguyenpham** [comment]
I guess it is not that error (ClippedEmoji) since only few emojis (such as coffee, wine glass...) but not all can make this bug.

**Comment by nguyenpham** [comment]
Now I can reproduce this bug on the latest library (develop branch):

![img_0165](https://cloud.githubusercontent.com/assets/1370755/20204404/7d0cdaa6-a823-11e6-968f-734637dba536.PNG)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
