### ISSUE TITLE
Supporting gif

### ISSUE THREAD

**Issue by AshkanImmortal** [jessesquires/JSQMessagesViewController#1853]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

### Crash log? Screenshots? Videos? Sample project?

Does this library support Giphy, Or has any plan to support?

**Comment by Lucashuang0802** [comment]
@AshkanImmortal. There is no direct support for using GIF in this library. However, you can still customize a Giphy UIView by using `JSQMessagesCollectionViewCell`.

**Comment by jessesquires** [comment]
Thanks @AshkanImmortal !

We'll track this feature request at #1869
