### ISSUE TITLE
Bug in date format?

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1854]
### General information

- Library version(s): current development
- iOS version(s): 10
- Devices/Simulators affected: iPhone 7
- Reproducible in the demo project? (Yes/No): yes

## Bug report
I am so confused about the first date line: Dec 30, 1 10:04 AM. Is the year missing / incorrect or in a special format?

![simulator screen shot 5 oct 2016 10 05 25 pm](https://cloud.githubusercontent.com/assets/1370755/19111175/d9bd9098-8b49-11e6-9423-72ecc35b9828.png)

**Comment by algrid** [comment]
In demo data [NSDate distantPast] is used as message date. It's December 30, 1 BC. So everything is ok with date format. Just a bit weird choice of demo data timestamps.

**Comment by Lucashuang0802** [comment]
thanks @algrid.
