### ISSUE TITLE
GIF File Support in Chat ?

### ISSUE THREAD

**Issue by ThillaiganeshChan** [jessesquires/JSQMessagesViewController#1856]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by ThillaiganeshChan** [comment]
Does JSQMessagesViewController, supports sending and receiving GIF files ? Does it show animated GIF in Chat view?

**Comment by Lucashuang0802** [comment]
Thanks for submitting an issue. Let's track it together on #1853. 😃

**Comment by jessesquires** [comment]
Thanks @ThillaiganeshChan !

We'll track this feature request at #1869
