### ISSUE TITLE
Does JSQMessage support text and image in a same message bubble ?

### ISSUE THREAD

**Issue by tw-safad** [jessesquires/JSQMessagesViewController#1858]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by Lucashuang0802** [comment]
@tw-safad That should be a solid YES. For more information, you can check out `JSQMessagesCollectionViewCell.h` and `- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` in `DemoMessagesViewController.m`. 😃

**Comment by tw-safad** [comment]
@Lucashuang0802  we are looking for image and text send both as one message . Is that possible ???

**Comment by GianniCarlo** [comment]
@tw-safad create a new media type which contains a `UIImageView` and a `UILabel` or `UITextView` maybe. There are many issues which explain how to create a new media type. The other thing you can do, when selecting an image to send, put it inside the input field, so you can add text alongside it, and then send two separate messages, one with the image and the other with the remaining text

**Comment by jessesquires** [comment]
Tracking at #681
