### ISSUE TITLE
When using RTL langage, Text at top and bottom of bubble staying at the same place when the bubble is inverting side

### ISSUE THREAD

**Issue by jerembab** [jessesquires/JSQMessagesViewController#1859]
When my device is in Left To Right (LTR) : 
![screen shot 2016-10-07 at 16 12 31](https://cloud.githubusercontent.com/assets/19578724/19190944/e7e20bda-8ca8-11e6-9b1d-1d4b75898292.png)

When I try in RTL I manage to invert the bubble by changing the incomingBubble and outgoing bubble but my texts under the bubble and at the bottom remained at the same place.. 
![screen shot 2016-10-07 at 15 42 59](https://cloud.githubusercontent.com/assets/19578724/19191242/43d98f34-8caa-11e6-9d7c-d72c24be36f2.png)

How can I taking these texts to the right place??

**Comment by ron137** [comment]
+1

**Comment by jessesquires** [comment]
Thanks @jerembab ! 👍 

Possible issues:

- the labels are using explicit `.textAlignment`
- the labels are not using `leading` / `trailing` constraints (but `left` / `right`)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
