### ISSUE TITLE
When reappear jsqmessageviewcontroller scroll view scroll to top alone.

### ISSUE THREAD

**Issue by RonGafni** [jessesquires/JSQMessagesViewController#1861]
Hey, 

When I'm load messages for the first time the scroll view is on bottom. after I go back and show again the message the scroll view scroll automatically to top. 

How can I maintain the scroll's position for each screen when I'm come back to the message? 

Thanks

**Comment by Lucashuang0802** [comment]
Thanks! 😄

Please provide all the information in the issue template so we can help!
And don't forget to read our contribution guidelines. 😊

**Comment by jessesquires** [comment]
Thanks @RonGafni !

There are APIs to scroll to the bottom. You can also use the usual collection view and scroll view APIs.

Was there a specific problem with any of these approaches?

**Comment by apwelsh** [comment]
I cannot get them to work.  And if I scroll to the botton them tap the text input box tontype a message it scrolls back to the top as I type.  Perhaps we are experiencing the same issue.
