### ISSUE TITLE
Crash after return from UIImagePickerController

### ISSUE THREAD

**Issue by anbangz** [jessesquires/JSQMessagesViewController#1862]
Swift 2.3
iPhone 6s as a test device
JSQMessagesViewController (7.3.4)

Hey, I'm experiencing a very strange issue. Most aspects are working as expected, but in the one specific case where there are already messages in my JSQMessage array, and I use an UIImagePickerController (.Camera), and within the camera interface, I go from Portrait to Landscape orientation, take a photo, and then return to the JSQMessagesViewController, XCode gives me this error:
<img width="1183" alt="screen shot 2016-10-08 at 6 52 39 pm" src="https://cloud.githubusercontent.com/assets/10663023/19217009/786f39cc-8d88-11e6-96e0-5650cbb2fd0d.png">

This is only reproducible if the orientation of the device is flipped (portrait -> landscape, landscape-> portrait) in the UIImagePickerView, and if THERE ARE ALREADY JSQMessages in my `var messages = [JSQMessage]()` array. If this array is empty before UIImagePickerController is presented, there is no error.

Additional Info:
I'm using Firebase as my data source, with Amazon S3 as my storage service for photos.

**Comment by Lucashuang0802** [comment]
@anbangz can you replicate the same crash in the demo project?

**Comment by jessesquires** [comment]
Thanks @anbangz ! 😄 

My first thought is that the the library isn't the root cause here. However, we would need a lot more info from you to determine that. 😄
