### ISSUE TITLE
Toolbar Textview incorrectly decreases in size for any line deletion after it reaches maximum size

### ISSUE THREAD

**Issue by LowAmmo** [jessesquires/JSQMessagesViewController#1864]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: :muscle::sunglasses::facepunch:
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
### General information
- Library version(s): 7.3.4
- iOS version(s): 9.3 & 10.0
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No): 
- Related issues:
### Expected behavior

Expect the text view to maintain full size until less than the maximum size is needed
### Actual behavior

Text view decreases size as soon as a line is removed, instead of flexing to only decrease in size when less lines are needed.
### Steps to reproduce
1. Compose a message to send with more lines than can be displayed
2. Text view expands as expected
3. Delete the last line
4. Text view decreases in size - even though there are still more than enough lines to fill the space.
### Crash log? Screenshots? Videos? Sample project?

Video of issue - 
[Bug.zip](https://github.com/jessesquires/JSQMessagesViewController/files/522987/Bug.zip)
## Resolution

Working on finalizing a fix that I will put out for pull request

**Comment by DamascenoRafael** [comment]
Hey, same problem here. It ends up being easier to occur if you set `inputToolbar.maximumHeight`. Any news? Thanks.

**Comment by LowAmmo** [comment]
@DamascenoRafael  - I saw the same thing.  I'm guessing it's only a problem when you set the maximumHeight, because when it grows to take up the whole screen, the calculation seem to handle that okay.

I'm just waiting for one of the Approved Reviewers to +1 my PR - #1914 .  But, if nothing else, you could do the same thing we did and just ship with the forked version with the fix in it, for now...

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
