### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by davidseek** [jessesquires/JSQMessagesViewController#1867]
I have checked the Docus and other Issues, but couldn't find updated information.
I'm waiting only for JSQMessagesViewController to update my project to Swift 3. 
Any news when a release version for Swift 3 will be published?

Best regards

**Comment by Lucashuang0802** [comment]
Hey @danhbear. #1825 is the PR for updating to Swift 3. We will merge the codes shortly. Thanks. 😄
