### ISSUE TITLE
 JSQMessageController going out of the desired bounds of the view

### ISSUE THREAD

**Issue by uknowmeright** [jessesquires/JSQMessagesViewController#1874]
## General information
- Library version(s): 7.3.4
- iOS version(s): 10.0
- Devices/Simulators affected: iphone 5, Iphone 6s Emulator
- Reproducible in the demo project? (Yes/No): No
## What happened?

I am getting a strange bug where JSQMessageController seems to be going out of the desired bounds of the view:

![img_0108](https://cloud.githubusercontent.com/assets/7127078/19498361/6ace61ca-955e-11e6-8722-1d8d8bda5814.jpg)

The send button is cut off, and the messages on the right are all cut off. 
I have tried doing what some similar issues suggested and the controls bounds in viewDidLayoutUbviews() 

`
override func viewDidLayoutSubviews() {
        self.collectionView?.contentInset = UIEdgeInsetsMake( 80, 0, 0, 50) // UIEdgeInsets(top: 40, left: 0, bottom: 0, right: 0)
        self.collectionView?.scrollIndicatorInsets = UIEdgeInsets(top: 80, left: 0, bottom: 0, right: 50)
    }
`

But this does nothing to help and makes absolutely no difference.

Any Ideas or suggestions? I searched all over the issues and couldn't find a duplicate,

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
