### ISSUE TITLE
Leaving Chat while playing audio makes JSQAudioMediaItem to crash

### ISSUE THREAD

**Issue by relatedcode** [jessesquires/JSQMessagesViewController#1877]
## General information
- Library version(s): 7.3.4
- iOS version(s): 10.0
- Devices/Simulators affected: both
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: n/a
## What happened?

When I leave the Chat view while playing an audio message, the JSQAudioMediaItem crashes.

The only change I made in demo project is: I have changed the jsq_messages_sample.m4a file to a longer (7 sec) one.

**Comment by relatedcode** [comment]
As far as I see the JSQAudioMediaItem dealloc is not triggered if the audioPlayer is still playing.

I hope this helps, however I cannot resolve the situation...

**Comment by relatedcode** [comment]
As far as I see the JSQAudioMediaItem dealloc is not triggered if the audioPlayer is still playing.

I hope this helps, however I cannot resolve the situation...

**Comment by algrid** [comment]
Looks like some kind of black magic with NSTimer retain cycle...

**Comment by algrid** [comment]
@relatedcode Could you try this PR - https://github.com/jessesquires/JSQMessagesViewController/pull/1879 ?

**Comment by relatedcode** [comment]
@algrid This PR (#1879) seems ok for me now. The JSQAudioMediaItem dealloc is triggered, the ongoing audioPlayer stops playing. No crash. Can be merged. :)

**Comment by eliburke** [comment]
Good catch @algrid, @relatedcode. 
The PR looks good, but I'm not a fan of adding a new top-level class for this one special case. 
There is another suggested solution using [dispatch_after](http://stackoverflow.com/a/20239674/1758224). Would you be interested in submitting a patch using that technique?

**Comment by jessesquires** [comment]
Thanks @relatedcode @algrid ! 👍 

I agree with @eliburke -- any other possible solutions here?

Also, `-invalidateTimer` should break the cycle

**Comment by algrid** [comment]
@eliburke @jessesquires Added an alternative PR based on dispatch_after. But frankly speaking I'd prefer the first one :)

**Comment by andaluz** [comment]
I fixed this bug as I had this problem too.
In audioPlayerDidFinishPlaying of class JSQAudioMediaItem, the following happens, if you stop the timer before setting the state of progressView it crashes, because progressView = nil. I thought to guard this issue by adding an if(self.progressView) but it crashes even on the if-statement, which is very weird, because self != nil (according to the debug view).

So finally I put
[self stopProgressTimer];
at the end of the method and the crash was fixed.

This is my first time sending a patch, so I'm not sure if this the right way to do it.

[0001-Fix-issue-1877.txt](https://github.com/jessesquires/JSQMessagesViewController/files/622138/0001-Fix-issue-1877.txt)

**Comment by 0xALEX** [comment]
I still have this crash. I fixed it by exposing stop method of audio player and stopping all playback on viewWillDisappear.
- (BOOL)isPlaying {
	return self.audioPlayer.isPlaying;
}
- (void)play {
	[self startProgressTimer];
	[self.audioPlayer play];
}
- (void)stop {
	[self stopProgressTimer];
	[self.audioPlayer stop];
}

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
