### ISSUE TITLE
Is it possible to make a custom cell

### ISSUE THREAD

**Issue by oyacodewell** [jessesquires/JSQMessagesViewController#1881]
Hello, is it possible to make a a custom cell such as the one on the picture. I really need to add the star rating below the avatar. I already have a custom control for it and I just need to add it. 
Thanks,

![public chat - user rating](https://cloud.githubusercontent.com/assets/23053936/19685612/cb4c363a-9abd-11e6-8e32-03f7878cb487.png)

**Comment by jessesquires** [comment]
Thanks @oyacodewell!

Please see the FAQ:
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md

**Comment by wdcurry** [comment]
and a gentle note: this is such a busy library, that any and all questions that do not relate to the actual library itself should be tossed over to StackOverflow...  ;)

**Comment by oyacodewell** [comment]
Thanks,
Ill check the FAQ carefully.
