### ISSUE TITLE
[Customize Cell] Attributed text on message

### ISSUE THREAD

**Issue by eironeia** [jessesquires/JSQMessagesViewController#1882]
I'm trying to find a way to make the text of the cell attributed to simulate a bubble like whatsapp with senderName inside the bubble attributed with bold and maybe with some color. I've find through all the issues but nothings seems is exactly what I'm finding. Could someone show me how to do it? Or share some code?

I've read that in version 8 this problem will be fixed easy, and will be a easy method to do it, but when version 8 will be released, that's the point.

**Comment by Lucashuang0802** [comment]
You should be able to do that by looking at `JSQMessagesLabel`. Actually, it's from `UILabel` but `JSQMessagesLabel` should be the class you should work on:
```
// the underlying attributed string drawn by the label, if set, the label ignores the properties above.
@property(nullable, nonatomic,copy)   NSAttributedString *attributedText NS_AVAILABLE_IOS(6_0);  // default is nil
```

**Comment by Lucashuang0802** [comment]
You should be able to do that by looking at `JSQMessagesLabel`. Actually, it's from `UILabel` but `JSQMessagesLabel` should be the class you should work on:
```
// the underlying attributed string drawn by the label, if set, the label ignores the properties above.
@property(nullable, nonatomic,copy)   NSAttributedString *attributedText NS_AVAILABLE_IOS(6_0);  // default is nil
```

**Comment by Lucashuang0802** [comment]
You should be able to do that by looking at the property `attributedText` from `JSQMessagesLabel`. Actually, it's from `UILabel` but `JSQMessagesLabel` should be the class you work on:
```
// the underlying attributed string drawn by the label, if set, the label ignores the properties above.
@property(nullable, nonatomic,copy)   NSAttributedString *attributedText NS_AVAILABLE_IOS(6_0);  // default is nil
```
