### ISSUE TITLE
Bottom Content inset is set to  44 pixel 

### ISSUE THREAD

**Issue by tw-safad** [jessesquires/JSQMessagesViewController#1884]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
## General information
- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:
## What happened?

Hi ,

We are trying to set content inset to some pixel when orientation changes . After it sets the collection view content inset is overridden by 44 pixel as a bottom inset . Could you please tell us how to set our own content inset for collection view ?

**Comment by tw-safad** [comment]
@algrid Thanks for the response . I dont find additionalContentInset property of JSQMessagesViewController in the current version (7.3.4)

**Comment by Lucashuang0802** [comment]
Hey, @tw-safad. We changed #1268. You might want to try `develop` branch. As we always said, you should pay more attention to it as it's for development. :smiley:
