### ISSUE TITLE
Some problem with scroll to bottom (finishSendingMessage/finishReceivingMessage)

### ISSUE THREAD

**Issue by wayne1203** [jessesquires/JSQMessagesViewController#1886]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 8.0.0
- iOS version(s): 9.0 - 10.0
- Devices/Simulators affected: 
- Reproducible in the demo project? (Yes/No): 
- Related issues: #1785 

## What happened?
I used the code provided by @Wu-Dong-Hui in #1785 
But I got the problem with scroll to bottom function

![086eadb6-a05b-11e6-944c-e82f0d0deb15](https://cloud.githubusercontent.com/assets/8578341/19889306/2c0c47a6-a06f-11e6-87d3-5aaff59706de.gif)

"finishSendingMessage" / "finishReceivingMessage"  when message received or sent
Only the last message can scroll to the bottom

Sorry for my bad English..
Thank you

**Comment by Lucashuang0802** [comment]
hey @wayne1203, thanks for creating an issue. If you are sure that's the same problem. Let's close it and track it from #1785. 😃

**Comment by wayne1203** [comment]
I think that is not the exactly same issue.
It's OK, I will comment it on #1785 again.
Thank you
