### ISSUE TITLE
how to change the value of y of avatarContainerView to be 0

### ISSUE THREAD

**Issue by 2360219637** [jessesquires/JSQMessagesViewController#1887]
how to change the value of y of avatarContainerView to be 0? I want to make user'avatar be top,how can i do?

**Comment by MacMeDan** [comment]
Hey @2360219637 I am confused on what you are going for here. Is there an image or anything you could attach showing what you mean.

**Comment by MacMeDan** [comment]
So I guess the answer to your question is: You can do it by creating you own custom view where you make the constraints in a way that allows you to have the avatar above your message.

I would suggest looking at the project and checking out the `JSQMessagesCollectionViewCellIncoming.xib`

copying it and giving it a unique name. Then moving the elements around. Depending on what you do you may need to subclass the `JSQMessagesCollectionViewCellIncoming.h` and `.m` files also.

I hope that helps 🤘
