### ISSUE TITLE
Add feature for limiting number of characters in a textmessage

### ISSUE THREAD

**Issue by emmanuelay** [jessesquires/JSQMessagesViewController#1888]
It would be very helpful to have an option to limit the maximum number of characters in a message. 

If I was to implement it today I'd need access to the UITextViewDelegate in JSQMessagesComposerTextView, which is buried very deep into the structure of the component.
It would be nice to be able to set this value in a high level component.

**Comment by jessesquires** [comment]
Thanks @emmanuelay !

`JSQMessagesViewController` publicly declares conformance to `UITextViewDelegate`. You should be able to override any of these methods in your view controller. 😄
