### ISSUE TITLE
InputToolbar not showing when JSQMessagesViewController subclass used as ChildViewController

### ISSUE THREAD

**Issue by alessioarsuffi** [jessesquires/JSQMessagesViewController#1889]
First of all, thanks for this amazing project 👍 

## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: 💪😎👊
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 7.3.4 develop branch
- iOS version(s): 9.3
- Devices/Simulators affected: YES
- Reproducible in the demo project? (Yes/No): YES
- Related issues: 

## What happened?

I am subclassing JSQMessagesViewController and trying to use it as childViewController;
everything seems working well but the problem is that i'm unable to see InputToolbar;

<img width="1159" alt="screen shot 2016-11-03 at 14 42 08" src="https://cloud.githubusercontent.com/assets/3455711/19968212/eec2673e-a1d3-11e6-8fc0-d81628efa5fc.png">

I created an UIViewController called ExampleViewController,
than in:

    - (void)viewDidLoad {
    [super viewDidLoad];
    
    //DemoMessagesViewController *vc = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"DemoVC"];
    
    DemoMessagesViewController *vc = [[DemoMessagesViewController alloc] init];
    
    [self addChildViewController: vc];
    vc.view.frame = self.view.frame;
    [self.view addSubview: vc.view];
    [vc didMoveToParentViewController:self];
    }

and the input bar is not showing;

so i found this at line 162 of JSQMessagesViewController.m

    [self.inputToolbar removeFromSuperview];

if i comment this line the input bar is showing:

<img width="342" alt="screen shot 2016-11-03 at 14 52 40" src="https://cloud.githubusercontent.com/assets/3455711/19968539/450dba20-a1d5-11e6-9830-06a2f8eb0fe5.png">

 but i receive this error when tapping on it: 

    2016-11-03 14:46:42.753 JSQMessages[10481:3480173] *** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<UICompatibilityInputViewController: 0x16d39180> should have parent view controller:<DemoMessagesViewController: 0x16d8a2e0> but requested parent is:<UIInputWindowController: 0x17375400>'
    *** First throw call stack:
    (0x21451b0b 0x20c0edff 0x21451a51 0x25ad1131 0x262e08b5 0x262e1373 0x25a3f275 0x262e1171 0x262da387 0x25afb5af 0x25a573cf 0x25ab80cb 0x25ab83e1 0x25bef855 0xbdfcd 0x25bef6d3 0x25beeca7 0x25f9a81b 0x25bd2a53 0x25a62e95 0x25f9bb7f 0x25a236d7 0x25a1fc49 0x25a60d81 0x25a60533 0x25a30dd5 0x25a2f379 0x214139e7 0x214135d7 0x2141193f 0x213601c9 0x2135ffbd 0x2297caf9 0x25a99435 0xaa473 0x2100c873)
    libc++abi.dylib: terminating with uncaught exception of type NSException

any suggestion is much appreciated thanks :)

if needed i will update my example project :)

**Comment by algrid** [comment]
@alessioarsuffi I was able to get it working like this:
```
@implementation SampleVC {
    DemoMessagesViewController *vc;
}

- (void)viewDidLoad {
    [super viewDidLoad];

    vc = [[DemoMessagesViewController alloc] init];
    
    [self addChildViewController: vc];
    vc.view.frame = self.view.frame;
    [self.view addSubview: vc.view];
    [vc didMoveToParentViewController:self];
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [vc becomeFirstResponder];
}
```
It's a bit late to call ``` [vc becomeFirstResponder]``` in ```viewDidAppear``` but it doesn't work for some reason if called before that.

inputToolbar is used as inputAccessoryView for JSQMessagesViewController

**Comment by alessioarsuffi** [comment]
Thanks @algrid, will try this soon and let you know ;)

**Comment by alessioarsuffi** [comment]
Thanks @algrid, at the moment this seems working, but it cause inputToolbar to overlay bubbles:

![img_0037](https://cloud.githubusercontent.com/assets/3455711/20094741/e590127e-a5a2-11e6-9c24-81dbac13102a.PNG)

collectionView bounds are excluding inputToolbar bounds, do you know why?

**Comment by algrid** [comment]
@alessioarsuffi Hmm, I don't have this problem with the current develop branch. Do you use the develop branch?

**Comment by alessioarsuffi** [comment]
@algrid yes, i'm on latest develop commit. Maybe it's caused from "Hides bottom bars on push" property set to YES into storyboard?

**Comment by alessioarsuffi** [comment]
@algrid, don't know why, but using:

    additionalContentInset = UIEdgeInsetsMake(0, 0, 60.0, 0)

seems to solve this problem; if you want can close this, thanks 👍

**Comment by jessesquires** [comment]
Thanks all! 🎉

**Comment by gizmeondev** [comment]
@alessioarsuffi where do u put the below code?
`additionalContentInset = UIEdgeInsetsMake(0, 0, 64.0, 0)`
I'm also facing the same issue.
