### ISSUE TITLE
Just want to increase size of Media Cell 

### ISSUE THREAD

**Issue by TheEngineerz** [jessesquires/JSQMessagesViewController#1890]
If i just want to increase the size of media image bubble then how i can do it. like in image below
![screen shot 2016-11-03 at 7 45 29 pm](https://cloud.githubusercontent.com/assets/5149947/19970738/c376e4da-a1fe-11e6-852f-f86d8e318cdd.png)

**Comment by apwelsh** [comment]
I have been looking at these extensively, and from my experience you cannot unless you extend the JSPPhotoMediaItem and override the mediaViewDisplaySize method to return the desired size.

**Comment by Lucashuang0802** [comment]
Hey, @apwelsh. That's correct actually. A temporary solution is to change your desired size from `JSQMediaItem`:
```
- (CGSize)mediaViewDisplaySize
{
    if ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad) {
        return CGSizeMake(315.0f, 225.0f);
    }
    
    return CGSizeMake(210.0f, 150.0f);
}
```

As for providing customization, I think that's not a bad idea but I don't think that will be priority for this stage. @jessesquires wdyt?

**Comment by eliburke** [comment]
@TheEngineerz as @Lucashuang0802 suggests, override mediaViewDisplaySize to get a custom size. If you prefer not to subclass, you can also swizzle in alternate behavior ([described in more detail here](https://github.com/jessesquires/JSQMessagesViewController/issues/1180#issuecomment-236431032))

Here's the code I use in my app. It gives square images a fixed thumbnail size, and adjusts the frame for portrait and landscape images to match thumbnails on their smaller dimension. 
```
#import <objc/runtime.h>

// swizzle in our modified method of calculating the thumbnail size
@implementation JSQPhotoMediaItem (mediaSize)

+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [SwizzUtils swizzle:[self class] originalSelector:@selector(mediaViewDisplaySize) swizzledSelector:@selector(my_mediaViewDisplaySize)];
    });
}

- (CGSize)my_mediaViewDisplaySize {
    
    CGSize thumbSize = CGSizeMake(kAppThumbnailBound, kAppThumbnailBound );
    if (self.image.size.height > 0 && self.image.size.width > 0) {
        CGFloat aspect = self.image.size.width / self.image.size.height;
        if (self.image.size.width > self.image.size.height) {
            thumbSize = CGSizeMake(kAppThumbnailBound, kAppThumbnailBound / aspect);
        } else {
            thumbSize = CGSizeMake(kAppThumbnailBound * aspect, kAppThumbnailBound);
        }
    }
    
    return thumbSize;
}

@end
```
