### ISSUE TITLE
collection view reload

### ISSUE THREAD

**Issue by pprevalon** [jessesquires/JSQMessagesViewController#1892]
I have a a subview on top of the collection view. whenever I press the send button the subview also reload how can i prevent that view from reloading everytime the send button is pressed?  I do have self.finishSendingMessage(animated: true) at the end of the didsend function. I know this is whats causing the reload but I want the reload to avoid the my specified subview.

**Comment by Lucashuang0802** [comment]
@pprevalon, the question does not seem to relate to the library. May I know what is your `subview` and what is it for?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
