### ISSUE TITLE
delay on appearing message placeholder text and send button

### ISSUE THREAD

**Issue by yarodevuci** [jessesquires/JSQMessagesViewController#1894]
When Going to JSQMessagesViewController it is presenting message placeholder text and send button after it was loaded with a slight delay
is it possible to fix that?

**Comment by MacMeDan** [comment]
You could render the view before you present it. Or have all the messages already available before you present the view. Like the Demo app. Since all the messages are composed on the `initalViewController` then the view is presented all the data is there and there is no delay for the send button.

**Comment by yarodevuci** [comment]
@MacMeDan How can you render the view before I present it? Even if I have no messages I still see the delay for toolbar placeholder and send button

**Comment by MacMeDan** [comment]
Are you using he programmatic approach or storyboard?

**Comment by yarodevuci** [comment]
@MacMeDan I tried both, and having the same issue. I am using iOS 8.4. I tried other OS versions but same effect. Also I tried going to the screen without loading any messages at all and still observing the issue. I have attached the demo gif
Currently I set up this way. I have storyboard, that is subclassed to `JSQMessageViewController` and to navigate to it I use this code:
```
let jqvc = self.storyboard?.instantiateViewController(withIdentifier: "jqvc")
navigationController?.pushViewController(jqvc!, animated: true)
```
Please, if you have any idea why it is happening let me know! Thank you
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13408859/21509248/0c6e4c66-cc3c-11e6-93d9-2cca28d32ba2.gif)
