### ISSUE TITLE
Problem when making input toolbar be higher

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1895]
## General information

- Library version(s): 7.3.4
- iOS version(s): 10.x
- Reproducible in the demo project? (Yes/No): Yes

## What happened?

I want to set input tool bar higher than normal. In the class DemoMessagesViewController I have added the bellow line into viewDidLoad (right after [super viewDidLoad]):

      self.inputToolbar.preferredDefaultHeight = 150;

The inputToolbar shows correctly, higher than before.

The problem is that some messages now are hidden permanently behind that toolbar (they will be bounced back to be hidden even user scrolls up).

For current developing JSQMessagesViewController preferredDefaultHeight has no effect at all.

Is it a bug or am I missing some thing?

![img_0160](https://cloud.githubusercontent.com/assets/1370755/20165655/4d486378-a763-11e6-874a-cac6b5b4d445.PNG)

**Comment by algrid** [comment]
Btw, currently in develop branch preferredDefaultHeight doesn't seem to work at all - it's used to change toolbarHeightConstraint but toolbarHeightConstraint is always nil.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
