### ISSUE TITLE
change JSQPhotoMediaItem of JSQMessage after loading messages ?

### ISSUE THREAD

**Issue by neerajneeruz** [jessesquires/JSQMessagesViewController#1897]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 
- iOS version(s): iOS 10.1.1
- Devices/Simulators affected: Device
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by neerajneeruz** [comment]
Is it possible to change the media item of a JSQMessage at any time if i required ? I have a senario like i need to insert an JSQPhotoMediaItem item message with a sample image and need to change the media item after some time or after the real image get downloaded from the server.

**Comment by magicmikek** [comment]
Check out this tutorial: https://www.raywenderlich.com/140836/firebase-tutorial-real-time-chat-2

**Comment by Lucashuang0802** [comment]
@neerajneeruz Yes, you can always change it. For your scenario, we have a full description about it on method: `- (instancetype)initWithImage:(nullable UIImage *)image;`. Here you go:
```
/**
 *  Initializes and returns a photo media item object having the given image.
 *
 *  @param image The image for the photo media item. This value may be `nil`.
 *
 *  @return An initialized `JSQPhotoMediaItem`.
 *
 *  @discussion If the image must be dowloaded from the network, 
 *  you may initialize a `JSQPhotoMediaItem` object with a `nil` image. 
 *  Once the image has been retrieved, you can then set the image property.
 */
```
