### ISSUE TITLE
Adding a view to bottom of CollectionView

### ISSUE THREAD

**Issue by JTambunt** [jessesquires/JSQMessagesViewController#1899]
I was wondering If there was a way to add this orange view to the bottom of the CollectionView:
Would this be a custom CollectionViewCell?

<img width="472" alt="screen shot 2016-11-11 at 8 33 11 pm" src="https://cloud.githubusercontent.com/assets/11169193/20234698/29e9243a-a84e-11e6-89cd-d7c051b4726c.png">

Any suggestions are welcome!

**Comment by JTambunt** [comment]
After doing more research, it seems that what I am trying to do is implement a "System" Message. #321 I will try to make a custom JSQPhotoMediaItem. If anyone has advice on this, please share!

**Comment by Lucashuang0802** [comment]
@JTambunt I would suggest you go with a custom `CollectionViewCell` so you have more flexibility to insert the orange message anywhere you want. Perhaps one day the requirement changes. You will never know.

**Comment by Lucashuang0802** [comment]
Feel free to continue here if you have more questions 😃
