### ISSUE TITLE
DequeReusableCell unknown Identifier

### ISSUE THREAD

**Issue by magicmikek** [jessesquires/JSQMessagesViewController#1900]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s): 7.3.4
- iOS version(s):1 0
- Devices/Simulators affected: all
- Related issues:

## What happened?

I'm trying to expand the Image in the Messagebubble to full screen view. As I override the following method: 

<img width="806" alt="screen shot 2016-11-12 at 21 03 40" src="https://cloud.githubusercontent.com/assets/7288679/20240559/8dcb8de4-a91b-11e6-9342-f4d773e6688e.png">

I get this error:
_'could not dequeue a view of kind: UICollectionElementKindCell with identifier JSQMessagesCollectionViewCell_JSQMedia - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'_

**Comment by algrid** [comment]
@magicmikek Why are you calling ```dequeueReusableCell```? To get the cell with bubble that was tapped you need ```collectionView.cellForItem(at indexPath: IndexPath)```.

**Comment by MacMeDan** [comment]
Dear @magicmikek,

Your approach is valid and @algrid makes a good point you actually want the image data for that specific cell. Since this method gives us the `indexPath` it makes it easy. Forget the cell and just go for the data 

```swift 

        let messageData = messages[indexPath.item]
```

Then check to see if it is a media message and if it is copy the media data 
```swift 
        if (messageData as AnyObject).isMediaMessage() {
            let messageMediaData = (messageData as AnyObject).media
```

Check and see if we can cast it as a `JSQPhotoMediaItem` This is where you could also check for other media types like video and do the same thing. 

```swift 
            if let image = messageMediaData as? JSQPhotoMediaItem {
```

Then this is where you would do what ever you want to display the image full screen. Just for example i'm going to make it full screen but nothing special and add it as a subview. You definitely don't have to do it this way.
```swift 
                let imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height))
                imageView.image = UIImage(cgImage: image.image!.cgImage!)
                view.addSubview(imageView)
```

So putting it all together in a single function would look like this : 

```swift
override func collectionView(_ collectionView: JSQMessagesCollectionView, didTapMessageBubbleAt indexPath: IndexPath) {
        let messageData = messages[indexPath.item]
        if (messageData as AnyObject).isMediaMessage() {
            let messageMediaData = (messageData as AnyObject).media
            if let image = messageMediaData as? JSQPhotoMediaItem {
                let imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height))
                imageView.image = UIImage(cgImage: image.image!.cgImage!)
                view.addSubview(imageView)
            }
        }
    }


You could definitely do more to avoid the implicitly unwrapped optionals but its pretty semi safe 🙃. Keep up the good work and let me know if you have more questions. 👾
