### ISSUE TITLE
input textfield disappear after calling for UIImagePickerController 

### ISSUE THREAD

**Issue by jerembab** [jessesquires/JSQMessagesViewController#1901]
## General information

- Library version(s):
- iOS version(s): 9
- Devices/Simulators affected: all devices (iphone 4s - 6s /+) 
- Reproducible in the demo project? (Yes/No): 
- Related issues:

## What happened?
I use the classic imagePickerController to change the group's image in my chat:
```
    func imagePickerController(picker: UIImagePickerController, didFinishPickingImage image: UIImage!, editingInfo: [NSObject : AnyObject]!) {
        imageOfEvent.image = image
        let ImageName = "\(theEvent!.eventID).jpg"
        let ImagePath = fileInDocumentsDirectory(ImageName)
        self.dismissViewControllerAnimated(true, completion: nil)   
    }
```
After that, if I try to send a message the keyboard is opening but the inputTextField is not appearing...
I also try to reload the view after changing the photo , that doesn't work either...

![screen shot 2016-11-14 at 09 16 02](https://cloud.githubusercontent.com/assets/19578724/20256378/d737ee06-aa4b-11e6-96b4-504f98a76678.png)

**Comment by jerembab** [comment]
@jessesquires  , is it a already known bug ?

**Comment by Lucashuang0802** [comment]
@jerembab thanks for reporting. Are you able to replicate it on the demo project?

**Comment by jerembab** [comment]
@Lucashuang0802 Hi , I am not sure about how to do that, if you can explain me , I'll try ...
Its really related to the imagePicker because I am calling for it in 2 places  (changing photo of chat room (like whatsApp) and when adding photos to an room album photo)

**Comment by yangmie** [comment]
Hi, @jerembab  

I also met the same bug!
Have you found how to fix it? 
Thanks!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
