### ISSUE TITLE
Audio Message display wrong after reloading

### ISSUE THREAD

**Issue by magicmikek** [jessesquires/JSQMessagesViewController#1902]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s):7.3.4
- iOS version(s):10.x
- Devices/Simulators affected:all

## What happened?

 Since there was an issue with the media placeholder for the JSQAudioMediaItem, I found out that it returned a `height = 0` for the `mediaPlaceholderView`. I fixed this and now it returns the default `height = 40` and actually shows a proper loading View for the JSQAudioMediaItem. Unfortunately as soon as I set the audio file and reload the collectionview something odd happens. Check out the pictures:
![simulator screen shot 9 nov 2016 16 32 49](https://cloud.githubusercontent.com/assets/7288679/20143797/59ef4f84-a668-11e6-9283-99d6400692e7.png)
![simulator screen shot 9 nov 2016 16 32 54](https://cloud.githubusercontent.com/assets/7288679/20143810/6660b280-a668-11e6-94bf-2ee4f084f5b7.png)
<img width="715" alt="screen shot 2016-11-14 at 16 56 55" src="https://cloud.githubusercontent.com/assets/7288679/20271552/6f6e6ddc-aa8b-11e6-82c7-e68b24fe0e2d.png">

**Comment by jessesquires** [comment]
cc @eliburke

**Comment by eliburke** [comment]
@magicmikek can you please create a fork of whatever version of the repo you are using, apply your JSQAudioMediaItem changes, and verify that the demo project shows this problem? Commit that and post the repo link, and then I'll check it out and see if I can diagnose what's going wrong.

**Comment by SaraQiam** [comment]
@magicmikek I'm having the same issue, did you mange to resolve this?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
