### ISSUE TITLE
Ability to change the placeholder insets

### ISSUE THREAD

**Issue by portellaa** [jessesquires/JSQMessagesViewController#1907]
## General Information

- Library version: 7.3.4
- iOS version(s): iOS 8+
- Devices/Simulators affected: Any
- Reproducible in the demo project? (Yes/No): Yes, if you change the font
- Related issues: Not directly related, but could help fix #1133 

## What happened?

I'm using a custom font which has a lower baseline. Any letter that goes below the baseline, for example: g, p, ... is cut when drawn.
Also, i want to change where the the placeholder is drawn if i increase the textView height.

**Comment by jessesquires** [comment]
Hey @portellaa -- this should be possible to customize. Search existing issues for customizing the toolbar.

**Comment by portellaa** [comment]
Hey @jessesquires 

I searched for it, and i didn't found it 😕 
And so, i created a PR with this. #1908

**Comment by jessesquires** [comment]
Ah, sorry @portellaa ! I misunderstood.

Thanks for the PR! 😄
