### ISSUE TITLE
[Custom Cell] Having problems implementing custom class.

### ISSUE THREAD

**Issue by OyaSaid** [jessesquires/JSQMessagesViewController#1909]
# New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## What happened?
I am trying to add a view below the avatar image. I have read the FAQ and the Documentation and done everything according to the [instructions][2] but it still doesn't seem to work. Can you please help me out?

I have created 3 custom classes, subclasses of the classes: 

 - JSQMessagesCollectionViewCell
 - JSQMessagesCollectionViewCellIncoming 
 - JSQMessagesCollectionViewCellOutgoing

ChatCell, sublcass of the JSQMessagesCollectionViewCell

    @interface QChatCell : JSQMessagesCollectionViewCell
    
    @end
    @implementation QChatCell

    @end

ChatCellIncoming, subclass of the ChatCell. I have created a xib file (QChatCellIncoming.xib) for this as well which is a copy of the JSQMessagesCollectionViewCellIncoming xib file:

    @interface QChatCellIncoming : QChatCell
    
    @end

    @implementation QChatCellIncoming
    
    - (void)awakeFromNib {
        [super awakeFromNib];
        [self.messageBubbleTopLabel setTextAlignment:NSTextAlignmentLeft];
        [self.cellBottomLabel setTextAlignment:NSTextAlignmentLeft];
    }
    
    + (UINib *)nib {
        return [UINib nibWithNibName:@"QChatCellIncoming" bundle:nil];
    }
    
    + (NSString *)cellReuseIdentifier {
        return @"QChatCellIncoming";
    }
    @end

ChatCellOutgoing, subclass of the ChatCell. I have created a xib file (QChatCellOutgoing.xib) for this as well which is a copy of the JSQMessagesCollectionViewCellOutgoing xib file:

    @interface QChatCellOutgoing : QChatCell
    
    @end

    @implementation QChatCellOutgoing
    
    - (void)awakeFromNib {
        [super awakeFromNib];
        [self.messageBubbleTopLabel setTextAlignment:NSTextAlignmentRight];
        [self.cellBottomLabel setTextAlignment:NSTextAlignmentRight];
    }
    
    + (UINib *)nib {
        return [UINib nibWithNibName:@"QChatCellOutgoing" bundle:nil];
    }
    
    + (NSString *)cellReuseIdentifier {
        return @"QChatCellOutgoing";
    }
    @end

In the Chat Controller Class in View Did Load I do this:

    self.outgoingCellIdentifier = [QChatCellOutgoing cellReuseIdentifier];
    self.outgoingMediaCellIdentifier = [QChatCellOutgoing mediaCellReuseIdentifier];
    
    [self.collectionView registerNib:[QChatCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingCellIdentifier];
    [self.collectionView registerNib:[QChatCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingMediaCellIdentifier];
        
    self.incomingCellIdentifier = [QChatCellIncoming cellReuseIdentifier];
    self.incomingMediaCellIdentifier = [QChatCellIncoming mediaCellReuseIdentifier];
        
    [self.collectionView registerNib:[QChatCellIncoming nib] forCellWithReuseIdentifier:self.incomingCellIdentifier];
    [self.collectionView registerNib:[QChatCellIncoming nib] forCellWithReuseIdentifier:self.

incomingMediaCellIdentifier];

And in the cellForItemAtIndexPath function Ive done this:

    - (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
        JSQMessagesCollectionViewCell *cell;
        
        if ([self incoming:messages[indexPath.item]]) {
            cell = [collectionView dequeueReusableCellWithReuseIdentifier:self.incomingCellIdentifier forIndexPath:indexPath];
            [cell.textView setTextColor:COLOR_CHAT_INCOMING_TEXT];
            return cell;
        }
        else {
            cell = [collectionView dequeueReusableCellWithReuseIdentifier:self.outgoingCellIdentifier  forIndexPath:indexPath];
            [cell.textView setTextColor:COLOR_CHAT_OUTGOING_TEXT];
            return cell;
        } 
    }

When I go to the chat screen, the app crashes with the following error. It does the same for the avatarContainerView in the QChatCellIncomming xib. I checked the xib file I cant find "TtC5Q_Fix17QChatCellOutgoing" anywhere in the project and the avatarContainerView is correctly connected :

    Unknown class _TtC5Q_Fix17QChatCellOutgoing in Interface Builder file.
    *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UICollectionViewCell 0x7f821cd42a80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key avatarContainerView.'

  [1]: https://github.com/jessesquires/JSQMessagesViewController
  [2]: https://github.com/jessesquires/JSQMessagesViewController/issues/1739

**Comment by MacMeDan** [comment]
Hey @OyaSaid 

Just as a side note you probably do not need to do this subclass if you are not actually doing anything different 
```swift
@interface QChatCell : JSQMessagesCollectionViewCell

@end
@implementation QChatCell

@end
```

you can just: 
```swift
@interface QChatCellIncoming : JSQMessagesCollectionViewCell
```

**Comment by MacMeDan** [comment]
The actual issue is probaby rooted in this 
>ChatCellIncoming, subclass of the ChatCell. I have created a xib file (QChatCellIncoming.xib) for this as well which is a copy of the JSQMessagesCollectionViewCellIncoming xib file:

By doing that ie (copying the file) You may have missed changing the `Class`. I have made this mistake many times before and the error message is quite misleading. 😤

So if you open up Xcode and open your  `QChatCellIncoming.xib` select the cell itself in the `interface builder` 

![screen shot 2016-11-18 at 3 53 34 pm](https://cloud.githubusercontent.com/assets/6182351/20449611/b5af60fc-ada7-11e6-9e9d-9b7400398eac.png)

Then look at the right panel IE(Utilities Panel) select the "identity Inspector" looks like this:
![screen shot 2016-11-18 at 3 56 46 pm](https://cloud.githubusercontent.com/assets/6182351/20449606/b1cf141e-ada7-11e6-936d-3c9a9ad4bd78.png)

And Change your class from JSQMessagesCollectionViewCellIncoming
![screen shot 2016-11-18 at 3 53 46 pm](https://cloud.githubusercontent.com/assets/6182351/20449608/b4065fb2-ada7-11e6-859e-7516b3f0593d.png)

To your class name `QChatCellIncoming` Now your UI knows which code is backing it and doesn't get confused 😨.

Then clean and run and it should solve that issue. 

Let me know if you have more issues 🖖🏽.

**Comment by OyaSaid** [comment]
Hello MacMeDan,
The cells in the xibs are both QChatCellIncoming and QChatCellOutgoing accordingly.
Also, I know that at the moment there is nothing different. I was trying to get it to work first without any new things before adding my own view.

Thanks,
Oya

**Comment by MacMeDan** [comment]
Ya @OyaSaid will do. 

That no good that you still cannot get it running. Let us know if there is anymore information that narrows down where this may be located and maybe someone else has run into the same thing. 🖖🏽

**Comment by GianniCarlo** [comment]
@OyaSaid that error which you mentioned usually happens when you have a 'dangling' connection from one of your `IBOutlets`. 

When I say dangling, I mean that with the previous class it was well connected, but when pasted, it usually maintains some sort of reference to the previous class when the new class doesn't have that connection/property.

Can you put your cells in the sample app and reproduce it?

**Comment by MacMeDan** [comment]
Ahh yes I thought I had seen it before. If you open your connections inspector on the right tab you can see if you have any that are broken. here is a screen shot of mine. If the dot on the right is a dash. that means it is broken and should be deleted and reconnected to what you expect. 

![screen shot 2016-11-21 at 9 05 40 am](https://cloud.githubusercontent.com/assets/6182351/20490073/f180a8d8-afc9-11e6-8610-f176a3e9f358.png)

**Comment by OyaSaid** [comment]
Hey ,
All the connections are intact. Here is a screenshot from the incoming cell. I tried reconnecting them just in case. It didn't fix the problem.
![screen shot 2016-11-21 at 5 22 28 pm](https://cloud.githubusercontent.com/assets/3874256/20490757/4fed809a-b00f-11e6-9677-c117da198aef.png)
Also here is the Identity inspector
![screen shot 2016-11-21 at 5 22 41 pm](https://cloud.githubusercontent.com/assets/3874256/20490779/62480c74-b00f-11e6-8e46-01711fb24c4f.png)

One thing I find weird is that the module is none in the interface builder and in the source code is set as  <collectionViewCell opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" reuseIdentifier="QChatCellIncoming" id="4lh-CK-yVn" customClass="QChatCellIncoming" customModule="Q_Fix" customModuleProvider="target">

**Comment by MacMeDan** [comment]
Did you also check the `JSQMessagesCollectionViewIncomingCell.xib`

**Comment by MacMeDan** [comment]
also I have some time right now to look at your project if you want to push it to a branch on github.

**Comment by OyaSaid** [comment]
I will make a sample project with only the chat and send you message. I would appreciate it  if you can check it out when you have the time.

Thanks

**Comment by OyaSaid** [comment]
@MacMeDan  Here is the test project. It would be great if you can check it out.
Thanks
https://github.com/OyaSaid/ChatExampleJSQ

**Comment by MacMeDan** [comment]
will do @OyaSaid

**Comment by MacMeDan** [comment]
Alright @OyaSaid I think I have found it. So after pulling down your branch and getting the project setup I got the error you were seeing. Poking around everything was looking correct and looking at the error it was giving me it was saying that it could not find the `CellIn` inside of the interface builder file. So I went to the CellIn.xib and deleted the class and Typed `CellIn` Again into the Class field. Made sure that it autocompleted and hit enter. Ran the project and it works. You had it correctly it was actually just Xcode that could not find the reference. 

1. So to fix just go to CellIn.xib
2. Select the Cell
3. Check the property inspector
4. Delete the Class 
5. Retype the Class `CellIn`
6. Make sure it autocompletes 
7. Hit `Enter`
8. Build and Run


I know it seems like you may have already done it and in fact you have the correct thing in that field. Xcode is just confused and not looking up the correct Class. Let me know if you need more help. I will also commit my changes to your project so if you get stuck you can continue. 

Here is a screen shot of it running on my phone. 

![img_0623](https://cloud.githubusercontent.com/assets/6182351/20676284/7216e32c-b54c-11e6-83e0-10c109431c2c.PNG)


Let me know if you get it to work and good luck☘️. 🖖🏽👾 
Also let me know if you have more questions.

**Comment by OyaSaid** [comment]
Oh my god thanks. I get the same screen now as you. But one question. As you can see in the code I add avatars and everything. Before I tried the custom cells the avatars and text were showing but now as you can see it does not even if the connections are all there. Why is that happening? How can I fix that? I tried by disconnecting and reconnecting the controls but that didn't fix the problem.

**Comment by MacMeDan** [comment]
You probably just need to set the size of the avatar so the whole collection view knows how big they are. Let me take a look and see if there is an example, I know what it is in swift but ObjectiveC I have to look up 🙃.

**Comment by MacMeDan** [comment]
So it looks like you just need to add something like this in your 'viewDidLoad` of your `viewController`

```ObjectiveC
    /**
     *  You can set custom avatar sizes
     */
    if (![NSUserDefaults incomingAvatarSetting]) {
        self.collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeZero;
    }
```


but don't use `CGSizeZero`
