### ISSUE TITLE
automaticallyScrollsToMostRecentMessage works so flickery with master/details app

### ISSUE THREAD

**Issue by nguyenpham** [jessesquires/JSQMessagesViewController#1910]
## General information

- Library version(s): current developing
- iOS version(s): 10.x
- Reproducible in the demo project? (Yes/No): Yes

## What happened?
When JSQMessagesViewController appears, automaticallyScrollsToMostRecentMessage auto scrolls the content to the end. It works smoothly on single view apps (such as Demo apps). However on master/details app (using split view), that scroll is not smooth any more. The content firstly is shown from the top, then jumped to the bottom. It is so flicker and irritate users.

I have tried already some ways such as adding scrollToBottom(animated: false) but no help.

I have modified Swift demo into Master/Details one and attached bellow as well as a short clip when it is working:

[JSQMessagesViewController.zip](https://github.com/jessesquires/JSQMessagesViewController/files/596247/JSQMessagesViewController.zip)

[flicker.mov.zip](https://github.com/jessesquires/JSQMessagesViewController/files/596356/flicker.mov.zip)

**Comment by SlavaBreath** [comment]
Same issue

**Comment by ko0f** [comment]
Here's a workaround - start with (swift code ahead) `collectionView!.alpha = 0`, then upon `viewWillAppear` fade the collectionView in, after it flicked invisibly. 

```
        if !collectionViewShown {
            collectionViewShown = true
            UIView.animate(withDuration: 0.1, delay: 0.2, options: [], animations: { [unowned self] in
                self.collectionView!.alpha = 1
                }, completion: nil)
        }
```

Looks good.

**Comment by ivanharmat** [comment]
@ko0f this actually works pretty well for me. Thanks

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
