### ISSUE TITLE
Simple way to change the text color to black

### ISSUE THREAD

**Issue by Prince009** [jessesquires/JSQMessagesViewController#1912]
please help :(

**Comment by algrid** [comment]
Do you mean this?
```
cell.textView.textColor = [UIColor blackColor];
```
Take a look at ```- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath``` method in DemoMessagesViewController.

**Comment by Prince009** [comment]
Thanks @algrid
