### ISSUE TITLE
Chat bubble getting clipped for custom Mediaitem

### ISSUE THREAD

**Issue by mukyasa** [jessesquires/JSQMessagesViewController#1913]
Hello Team,

Sorry for trouble, Thank you for this awesome library, I am currently facing one big issue

The chat bubble is getting clipped , Also it also get clipped when i bring ma app from background to foregorund.

![861b10a0-fb65-407e-866f-8f545694810a](https://cloud.githubusercontent.com/assets/7480780/20422173/b262a74c-ad8e-11e6-875e-fa5e434a4f63.jpg)

Below i have shared the code , thnks

`class JSQTimeStamp : JSQMediaItem {

    var mSG = ""
    let timestampLbl : UILabel = {
        let label = UILabel()
        label.opaque = true
        label.font = UIFont.preferredFontForTextStyle(UIFontTextStyleCaption2)

        return label
        
    }()
    
    let textView : UITextView = {
        let textView = UITextView()
        textView.dataDetectorTypes = .Link
        textView.scrollEnabled = false
        textView.opaque = true
        textView.textAlignment = NSTextAlignment.Left//isOperator == true ? NSTextAlignment.Right : NSTextAlignment.Left
        textView.font = UIFont.preferredFontForTextStyle(UIFontTextStyleBody)//UIFont(name: "OpenSans", size: 16)
        textView.editable = false
        textView.backgroundColor = UIColor.clearColor()
        return textView
        
    }()
   
    let baseView : UIView = {
        //Base
        let view = UIView()
        view.opaque = true
        return view
    }()
    
    let bubbleImageView: UIImageView = {
        let imageView = UIImageView()
        imageView.image = Configuration.grayBubbleImage
        imageView.tintColor = UIColor(white: 0.90, alpha: 1)
        return imageView
    }()
    
    var hashMsgValue : UInt!
    

    override init!(maskAsOutgoing: Bool) {
        super.init(maskAsOutgoing: maskAsOutgoing)

    }
    
    override func mediaHash() -> UInt {
        return hashMsgValue
    }
    

    
    init(withMessage msg: String, stamp: String ,isOperator: Bool , hash : Int) {
        super.init()
        hashMsgValue = UInt(hash)
        appliesMediaViewMaskAsOutgoing  = (isOperator == true)
        
        mSG = msg
        let size = super.mediaViewDisplaySize()
        
        

        textView.text = msg + "\n"
        textView.frame = CGRectMake(0, 0, size.width, size.height)
       
        if(isOperator == true){
            textView.textContainerInset = UIEdgeInsets(top: 8, left: 8, bottom: 0, right: 14)
            

            bubbleImageView.tintColor = UIColor(hexString: "3498DB")
            bubbleImageView.image = Configuration.blueBubbleImage
            timestampLbl.textColor = UIColor.whiteColor()
            textView.tintColor = UIColor.whiteColor()
            textView.textColor = UIColor.whiteColor()

        }else{
            textView.textContainerInset = UIEdgeInsets(top: 8, left: 14, bottom: 0, right: 8)
            bubbleImageView.tintColor = UIColor(hexString: "e5e5e5")
            bubbleImageView.image = Configuration.grayBubbleImage
            timestampLbl.textColor = UIColor.lightGrayColor()
            textView.textColor = UIColor.blackColor()
        }

        
        customise(size)
      
        baseView.addSubview(textView)
        baseView.addSubview(timestampLbl)
        
        bubbleImageView.frame = baseView.frame
        baseView.insertSubview(bubbleImageView, atIndex: 0)
        

    }
    
    func customise(size : CGSize){
        let textSize = textView.sizeThatFits(CGSizeMake(textView.frame.size.width, CGFloat.max))
        textView.frame = CGRectMake(0, 0, size.width, textSize.height)
        if(size.width > (textSize.width)){
            textView.frame = CGRectMake(0, 0, textSize.width, textSize.height)
            
            baseView.frame = CGRectMake(0, 0, textSize.width + 55 , textSize.height )
            if((textSize.width + 55) > size.width){
                baseView.frame = CGRectMake(0, 0, size.width , textSize.height )
                
            }
        }else{
            baseView.frame = CGRectMake(0, 0, size.width , textSize.height)
            
        }
        if(self.appliesMediaViewMaskAsOutgoing){
            timestampLbl.frame = CGRectMake(CGRectGetWidth(baseView.frame) - 70, CGRectGetHeight(baseView.frame)  - 20, 55 , 15)
            
        }else{
            timestampLbl.frame = CGRectMake(CGRectGetWidth(baseView.frame) - 65, CGRectGetHeight(baseView.frame)  - 20, 55 , 15)
            
        }
        
        
       
    }
    
    override func mediaView() -> UIView! {
        
        return baseView
    }
    
    override func mediaViewDisplaySize() -> CGSize {

        return baseView.frame.size//size.width > textSize.width ? textSize : CGSizeMake(size.width, textSize.height)//textView.frame.size
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
}`

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
