### ISSUE TITLE
Preview in Interface Builder

### ISSUE THREAD

**Issue by LucasVanDongen** [jessesquires/JSQMessagesViewController#1915]
I'm a quite heavy Interface Builder user because I like to be able to see what my view code or markup will look like before even starting the app. It's also super useful to see what translations do to your layout. Also it's good way to sort of document things as you can see what you will get from every class even when it's a code-only view class.

Since JSQMessagesViewController is a complete ViewController instead of a separate control there's seems to be no real way to pre-render it in Interface Builder, so basically I'm looking at an empty screen in my storyboard. There's also no way to quickly check how font changes, color changes, size changes etcetera reflect in my UI.

I would like to be able to do the following:
- Render the basic interface (new message controls) so I don't have an empty view controller in my storyboard
- If it renders, it would probably be possible too to also seed it with mock data through prepareForInterfaceBuilder so I can see chat bubbles as well that would reflect all my changes in code

It seems that the current massive view controller approach will prevent me from doing this, but perhaps I've overlooked a possibility? If not, I read in other tickets that the next version will probably be more decoupled from the ViewController. Would it allow me to render it in Interface Builder or would it still be too hard wired to a ViewController?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
