### ISSUE TITLE
Pressing return on device keyboard freezes JSQMessagesViewController

### ISSUE THREAD

**Issue by yarodevuci** [jessesquires/JSQMessagesViewController#1926]
If I press "return" twice it freezes JSQMessagesViewController without any output for error or warning to console. Anyone else experiences same thing ?

**Comment by MacMeDan** [comment]
I have not seen this but you can overwrite the `return` buttons functionality and make it behave the way you want.

**Comment by yarodevuci** [comment]
@MacMeDan it happens on iOS 8.4
Tested iOS 10 and pressing return does what it supposed to do. Is iOS 8.4 supported ?

**Comment by jessesquires** [comment]
Thanks @yarodevuci ! :smile:

Please provide all the information in the [issue template](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/ISSUE_TEMPLATE.md) so we can help! 
And don't forget to read our [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). :blush:

**Comment by yarodevuci** [comment]
@jessesquires 

    Library version(s): Latest
    iOS version(s): 8.4
    Devices/Simulators affected: Yes
    Reproducible in the demo project? (Yes/No): Yes
    Related issues: Freeze and crash

**Comment by loongman** [comment]
Same here with iOS 8.1.2.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
