### ISSUE TITLE
iOS 10 ToolBar + TabBar keyboard issue

### ISSUE THREAD

**Issue by SlavaBreath** [jessesquires/JSQMessagesViewController#1927]
- [√ ] I have read all of the [`README`]
- [√ ] I have reviewed the [contributing guidelines]
- [√ ] I have searched [existing issues]

## General information

- Library version(s): 7.3
- iOS version(s): iOS 10.1.1 (also valid for 10.2 beta)
- Devices/Simulators affected: iPhones only
- Reproducible in the demo project? (Yes/No): Not tested (requires swift 3 migration to test)
- Related issues: Did not found

## What happened?

Since update to iOS 10 and/or after migration to Swift 3 a bug with wrong toolbar constraint constant appeared. I have a tab bar, inside of it SplitViewController, where detail view is my JSQMessageViewController. Everything works fine unless I start a pop animation and then cancel it. While animation is in action, toolbar is moving down under keyboard, but when I cancel it, it suddenly jumps up above keyboard, so there is a white space is between keyboard and toolbar. I inspected a size of white space, it's the same size with tab bar. I attached a screenshot with final state of this issue. Any ideas?
![screen shot 2016-11-28 at 13 28 23](https://cloud.githubusercontent.com/assets/5702421/20667079/316358dc-b570-11e6-8f7d-db110850081d.png)

**Comment by yarodevuci** [comment]
Попробуй спрятать таб бар когда переходишь через пуш в методе init
Try to hide tab bar when you push view controller in init method

**Comment by SlavaBreath** [comment]
Думал так уже сделать, да, но хотелось бы все-так вариант такой, чтобы таб бар остался

**Comment by yarodevuci** [comment]
@SlavaBreath ну тогда не знаю. это только в IOS 10 такой баг?

**Comment by SlavaBreath** [comment]
@yarodevuci да, только iOS 10. Во виемя анимации почему-то неправильный фрейм коавиатуры присылается

**Comment by SlavaBreath** [comment]
A lot of debugging hours raised interesting thing in all this.

I found that keyboard frame has nothing to do with it. It's collectionView frame who's corrupted. But the most interesting thing is that it's frame is corrupted only when keyboard is on screen and I start and cancel back pan gesture. If start and cancel the same gesture with keyboard hidden, everything is just fine.

I'll investigate further, but let's pay our attention (I hope, I'm not one in the battlefield) to contextView in JSQMessagesKeyboardController which is the collectionView itself.

Hope this will help.

**Comment by jpatinop** [comment]
Any solution? I have same problem!!!

**Comment by jpatinop** [comment]
Ok, personally I had a pod from a third party, so I turn off only for the chat view an all works perfectly, the third party plugin was IQKeyboardManager, it was interfering with the input tool bar..

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
