### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by davidseek** [jessesquires/JSQMessagesViewController#1929]
Maybe a stupid question. But I was thinking about taking the chat from my app and have a "desktop messenger". Is it possible to take the JSQMVC for that? It says iOS all the time, so I was wondering.

And if not. Why? Just out of curiosity

**Comment by chrisballinger** [comment]
It uses iOS specific UI APIs everywhere. UICollectionView, UIView, etc. Another similar library with macOS support would be great though.

**Comment by davidseek** [comment]
didn't even realized, that UICV and UIView are iOS specific. haven't really thought about macOS stuff before. just thought.  same company. all apple. same IDE. same language. so should work... but mmmkayyy. well. then I'll have a look at the alternatives... but would be nice tho

**Comment by julien-c** [comment]
There is no UIKit in mac OS (yet?)

**Comment by apwelsh** [comment]
MacOS uses Cocoa.    UIkit for iOS is simillar but not the same.    To implement UIKit on MacOS, take a look at Chameleon, from http://chameleonproject.org
  

  
Based on the objective of the project, in theory, it should be an easy port.
  
    
  
  
  

  
   This (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email)  is how I Email now
  
  
  
  
  

  
  
>
