### ISSUE TITLE
JSQMessage Bubble Display Name Struggle

### ISSUE THREAD

**Issue by askaale** [jessesquires/JSQMessagesViewController#1931]
Hi there.

This is a small 'problem' I've been struggling with for a couple of hours now - and I am pretty sure many people may be looking for the same thing. So basically, I am displaying the sender name of the receiver. However, I don't want to display the name on every single text that the person sends. For example, if he/she sends a a message consecutively, I just want it to display the name on top of the first message. I'll provide a screenshot of my chat here:

![githubpic](https://cloud.githubusercontent.com/assets/20369568/20818789/59825c1a-b830-11e6-820f-182250c69745.png)

In other words, I just want it to display the name of the user on the very 'first' message he/she sends. I have now spent countless of hours trying to solve this issue, in the attributedTextForMessageBubbleTopLabelAt with no luck. I have tried to check if the senderId of the previous message is equal to the previous senderId - and then somehow find out if it can be shown or not. But, this has resulted in many, many failed attempts with optional errors, index out of range, and just simply not working solutions. Could anyone please point me in the right direction here? I would really appreciate it!

This is the code I have right now: 

```
 let message = messages[indexPath.item]
        
        switch message.senderId {
            
        case FIRAuth.auth()!.currentUser!.uid:
            return nil
            break
            
        default:
            
            
            guard let senderDisplayName = message.senderDisplayName else {
                assertionFailure()
                return nil
            }
            
            let paragraphStyle = NSMutableParagraphStyle()
            paragraphStyle.alignment = NSTextAlignment.left
            
            let attributedString = NSAttributedString(string: message.senderDisplayName,
                                                      attributes: [
                                                        NSParagraphStyleAttributeName: paragraphStyle,
                                                        NSBaselineOffsetAttributeName: NSNumber(value: 0)
                ])
            
            return attributedString
            break
            
            
            
            
        }


```

**Comment by eliburke** [comment]
You just need figure out if the label should be shown in both `heightForMessageBubbleTopLabelAtIndexPath` and again in `attributedTextForMessageBubbleTopLabelAtIndexPath`, using the same logic. If indexPath.item is 0, always show the label. When it is non-zero, check against the previous message. 

For example, here is Objective C code from my project:
````
    JSQMessage *message = [_conversation.messages objectAtIndex:indexPath.item];

    // for two person conversations, or if the sender is ourselves, show no label
    if ([_conversation.participantContacts count] <= 2 || [message.senderId isEqualToString:self.senderId]) {
        return 0.0f;
    }

    // If the previous message has the same sender, don't display another label
    if (indexPath.item > 0) {
        JSQMessage *previousMessage = [_conversation.messages objectAtIndex:indexPath.item - 1];
        if ([[previousMessage senderId] isEqualToString:message.senderId]) {
            return 0.0f;
        }
    }

    // return height, or return label string, according to which function was called.
````

**Comment by jessesquires** [comment]
Thanks @askaale !

Let's us know if this helps!

**Comment by askaale** [comment]
@eliburke Thank you so much, this solved my problem! However, I changed one thing; `previousMessage.senderId == message.senderId -> previousMessage.senderId != message.senderId`

Now it works perfectly. Thank you so much, you really made my day. Also, thank you @jessesquires! :-)
