### ISSUE TITLE
Showing the top and bottom labels when a bubble message is tapped

### ISSUE THREAD

**Issue by nico75005** [jessesquires/JSQMessagesViewController#1932]
I would like to do like Facebook messenger app, when you tap on a message, it will show you information about whether or not the message has been sent/seen, the time when it was sent.

For that I want to use the `cellTop` and `cellBottom` labels. What I have done so far is when I tap on a message, I get the `indexPath` and save it in a variable `tappedIndexPath` and then I reload the `collectionView`.

In the methods `heightForCellTopLabelAt` and `heightForCellBottomLabelAt`, if `tappedIndexPath` is nil, then I return nil, if not, then I return a certain height. 

In the methods `attributedTextForCellTopLabelAt`and `attributedTextForCellBottomLabelAt`, I return what I want to display in the labels.

When I said I reload the `collectionView` in `didTapMessageBubbleAt`, I meant I'm using `collectionView.reloadData()`.
The problem is that there is no animation. So I thought I would use `collectionView.reloadItems(at: [indexPath])` but then the animation doesn't look nice at all.

So my question is, am I doing it right or is there a better way?

Thanks.

- Library version(s): 7.3.4
- iOS version(s): 10.1

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
