### ISSUE TITLE
Custom bubble image shown as rectangular 

### ISSUE THREAD

**Issue by apryiomka** [jessesquires/JSQMessagesViewController#1933]
I have read the guideline as well as the issues:
#1762, #1721,#1839,#1451 and many others. The suggestion is to use JSQMessagesBubbleImageFactory  to specify your own image. This is exactly what i do, but the image appears rectangular. I couldn't find any guideline on what the image format should be. Is it a problem with the image or some additional configuration is required?

`outgoingBubble = JSQMessagesBubbleImageFactory(bubbleImage: UIImage(named: "bubble"), capInsets: UIEdgeInsets(top: 22.0, left: 23.0, bottom: 45.0, right: 66.0)).incomingMessagesBubbleImageWithColor(UIColor.cyanColor())`

and

`override func collectionView(collectionView: JSQMessagesCollectionView, messageBubbleImageDataForItemAtIndexPath indexPath: NSIndexPath) -> JSQMessageBubbleImageDataSource {        return messages[indexPath.item].senderId == self.senderIdLocal() ? outgoingBubble : incomingBubble
    }`

![screen shot 2016-12-01 at 8 59 53 pm](https://cloud.githubusercontent.com/assets/11861671/20823785/342e808e-b80c-11e6-8a08-5e10a26ba516.png)

And the image slices that i use

![screen shot 2016-12-01 at 9 46 37 pm](https://cloud.githubusercontent.com/assets/11861671/20824234/b59a1c66-b80f-11e6-9261-f177f3bb34e1.png)

**Comment by eliburke** [comment]
@apryiomka not only is it square, but it isn't cyan. Your bubble image isn't being used at all. Try setting a breakpoint in messageBubbleImageDataForItemAtIndexPath to verify it is being called, and check outgoingBubble to make sure it is initialized and valid.

**Comment by jessesquires** [comment]
👍 

Not specific to JSQ, so going to close, but feel free to continue the discussion. 😄
