### ISSUE TITLE
Wrong message position when screen is horizontal

### ISSUE THREAD

**Issue by panyaspy** [jessesquires/JSQMessagesViewController#1934]
- Library version(s): lastest
- iOS version(s): 10.1
- Devices/Simulators affected: iPhone 7 , iPhone 6 , iPhone 6s ,iPhone 6sPlus , iPhone 5s , iPhone 5 and SE

wrong message position when switching screen from portrait to landscape

**Comment by jessesquires** [comment]
Thanks @panyaspy !

Closing as dupe of #989
