### ISSUE TITLE
Too many images in chat result in Memory leak and crash

### ISSUE THREAD

**Issue by yarodevuci** [jessesquires/JSQMessagesViewController#1936]
Hi,
I noticed if adding images to `JSQMessage` array then I receive a **memory warning**, very laggy scroll and **crash** after. I am loading those images locally from Realm DB.
Can someone tell me what is the correct way to handle the case if there is too many images? 
Here is the code that I use: 

```
        let realm = try! Realm()
        let savedMessages = realm.objects(SavedMessage.self)
        for item in savedMessages {
            if item.isMedia {
                DispatchQueue.main.async(execute: {
                    let image = UIImage(data: item.imageData)
                    let photoItem = JSQPhotoMediaItem(image: image)
                    photoItem.appliesMediaViewMaskAsOutgoing = false
                    self.addMedia(photoItem, senderID: item.sender_id)
                })
            } else {
                self.addMessage(withId: item.sender_id, name: item.senderName, date: item.createdAt.toDate, text: item.text)
            }
            self.finishReceivingMessage()
        }
```

**Comment by nguyenpham** [comment]
Do you use real size images (say ones from camera)? A normal app usually can load into memory few real size images only. For me, for showing images in chatting I use thumb images with small sizes (under 500px). You may use smaller ones if need to load more images.

**Comment by yarodevuci** [comment]
I use thumbnails size 120x 120

**Comment by shravanteegala** [comment]
Iam faceing  same issue.
plz help me . how can I fix the memory leaks when I send the more images.
