### ISSUE TITLE
How to get the user interaction enabled for the messages view in jsq messages view contorller ? @jessesquires

### ISSUE THREAD

**Issue by saikrishnaburra** [jessesquires/JSQMessagesViewController#1938]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by jessesquires** [comment]
Thanks @saikrishnaburra ! 😄 

`userInteraction` should be enabled by default.

**Comment by saikrishnaburra** [comment]
where should i enable this....if its for the view returned in MediaView() in JSQMediaitem.....i have already enabled. but not working
