### ISSUE TITLE
AttributedString support is not present in latest developement branch

### ISSUE THREAD

**Issue by sandeepspoton** [jessesquires/JSQMessagesViewController#1941]
if you see the commit  https://github.com/jessesquires/JSQMessagesViewController/blob/a9748f9d991736fdcb73034cfb8fd4ecce91d064/JSQMessagesDemo/DemoModelData.m
 it has AttributedString support but in latest development branch i am not able to find it.

**Comment by jessesquires** [comment]
Thanks @sandeepspoton !

This is on the roadmap for 8.0
