### ISSUE TITLE
General file cell type

### ISSUE THREAD

**Issue by kaiduanx** [jessesquires/JSQMessagesViewController#1946]
It looks like there is no cell type to present a general file type except audio/video.

For example I would like the cell shows

Image of file type (For PDF, World, PPT, Excel)
File name, size

When user click the cell, the file is opened with corresponding viewer.

Is this on the roadmap?

## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

**Comment by jessesquires** [comment]
Hey @kaiduanx !

This is definitely out-of-scope work for awhile. However, you can provide custom cells.
