### ISSUE TITLE
JSQMessagesLoadEarlierHeader is hidden and not selectable

### ISSUE THREAD

**Issue by avaan** [jessesquires/JSQMessagesViewController#1947]
- Library version(s): --  7.3
- iOS version(s): -- 10.1
- Devices/Simulators affected: Iphone 6
- Reproducible in the demo project? (Yes/No):  Yes

## What happened?

In chat window when I scroll up I can see "Load Earlier Messages" header, but I am not able to select it bcoz once I stop scrolling it moves top and hides.

**Comment by apwelsh** [comment]
I have noticed this in the demo app as well.    I was planning to look into this for my app, bit it is low priority to me.    Hooefully somwone has addressed this and we can share in the knowledge.    If nit, i will likely get around to researching this myself in the next month...
  

  
Armand
    
  
  

  
  
   This (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email)  is how I Email now
  
  
  
  
  

  
  
>

**Comment by avaan** [comment]
@apwelsh thanks for your response. I will also check from my side.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
