### ISSUE TITLE
[Custom Cell] Crashes on Media file

### ISSUE THREAD

**Issue by OyaSaid** [jessesquires/JSQMessagesViewController#1948]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

Hello again,

I am using a custom cell and I have this code here.

```objective-c
self.outgoingCellIdentifier = [QChatCellOutgoing cellReuseIdentifier];
self.outgoingMediaCellIdentifier = [QChatCellOutgoing mediaCellReuseIdentifier];

[self.collectionView registerNib:[QChatCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingCellIdentifier];
[self.collectionView registerNib:[QChatCellOutgoing nib] forCellWithReuseIdentifier:self.outgoingMediaCellIdentifier];
    
self.incomingCellIdentifier = [QChatCellIncoming cellReuseIdentifier];
self.incomingMediaCellIdentifier = [QChatCellIncoming mediaCellReuseIdentifier];
    
[self.collectionView registerNib:[QChatCellIncoming nib] forCellWithReuseIdentifier:self.incomingCellIdentifier];
[self.collectionView registerNib:[QChatCellIncoming nib] forCellWithReuseIdentifier:self.incomingMediaCellIdentifier];
```

Everything works great but when I try to add an image it crashes with error:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'view reuse identifier in nib (QChatCellOutgoing) does not match the identifier used to register the nib (QChatCellOutgoing_JSQMedia)'`

Can you please help me how to fix this?

Thanks

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
