### ISSUE TITLE
How to change the text color of message?

### ISSUE THREAD

**Issue by serikFF** [jessesquires/JSQMessagesViewController#1950]
- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

I saw https://github.com/jessesquires/JSQMessagesViewController/issues/202, https://github.com/jessesquires/JSQMessagesViewController/issues/470 issues, but they didn't help me. How can I change message textColor in swift 3?

**Comment by petoye** [comment]
You can change textColor in cellForItemAtIndexPath like this ->

cell.textView!.textColor = UIColor.black (or anything you want)

**Comment by serikFF** [comment]
I'm trying to use this code: 
    func collectionView(_ collectionView: JSQMessagesCollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.cellForItem(at: indexPath) as! JSQMessagesCollectionViewCell
        
        cell.textView!.textColor = UIColor.black
        
        return cell
    }


And it doesn't work((

**Comment by petoye** [comment]
let cell = super.collectionView(collectionView, cellForItemAt: indexPath)
                as! JSQMessagesCollectionViewCell

**Comment by serikFF** [comment]
func collectionView(_ collectionView: JSQMessagesCollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as! JSQMessagesCollectionViewCell
        
        cell.textView!.textColor = UIColor.black
        
        return cell
    }

Doesn't work, even in SwiftExample project

**Comment by petoye** [comment]
`override func collectionView(_ collectionView: UICollectionView,
                                 cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
}
`

**Comment by serikFF** [comment]
thanks! it works

**Comment by petoye** [comment]
Glad you got it working! Please close the issue now!
