### ISSUE TITLE
Keyboard events not fired when nested in a UITabBarController

### ISSUE THREAD

**Issue by LucasVanDongen** [jessesquires/JSQMessagesViewController#1951]
- Library version(s): 7.3.4
- iOS version(s): iOS 10.1.1
- Devices/Simulators affected: Both
- Reproducible in the demo project? : Not tested 
- Related issues:  https://github.com/jessesquires/JSQMessagesViewController/issues/94

## What happened?

I have JSQMessagesViewController working in iOS 10 / Xcode 8.1 / Swift 3 both nested in a UITabBarController in a UINavigationController and just embedded a UINavigationController, but when the keyboard comes up in the nested version it doesn't move the input bar because the keyboard events somehow are not triggered so the keyboard covers the input field. I think this is a bug as it should pick up the keyboard event regardless of the fact that it's embedded in another tab bar controller or not. I also use the chat directly (without a tab bar) for more general chats and that works as advertised.

I've got this working by exposing the internal method jsq_handleKeyboardNotification via the header, then calling it when I get a keyboard event:

Setup:

        NotificationCenter.default.addObserver(self, selector: #selector(logKeyboard), name: NSNotification.Name.UIKeyboardWillHide, object: nil)
        
        //NotificationCenter.default.addObserver(self, selector: #selector(logKeyboard), name: NSNotification.Name.UIKeyboardDidChangeFrame, object: nil)
        
        NotificationCenter.default.addObserver(self, selector: #selector(logKeyboard), name: NSNotification.Name.UIKeyboardWillShow, object: nil)

In callback:

    func logKeyboard(notification: NSNotification) {
        chatViewController.keyboardController.jsq_handleKeyboardNotification(notification as Notification!, completion: nil)

This solution definitely has some issues, like not hiding the keyboard on scroll and other subtle issues. However I'm sure I can get the requirement implemented.

Why we want to have this
---------------------------

I agree it's less than ideal UX. However this specific chat lives in a context, we're discussing a bill that has more options in the tab bar. The navigation bar is already taken. The idea is to switch between information in the bill and the chat screen to discuss this. Hiding the tab bar would make that impossible.

**Comment by MchlG** [comment]
I am having a similar issue when nested in a UITabBarController. I actually have a Main view, nested in a UITabBarController and then my JSQMessagesViewController is inside a container view which is in the Main view. 

When the keyboard is expanded after typing, the "send" button is unresponsive. If i dismiss the keyboard, then I am able to use the send button on the input toolbar. The problem only occurs when the keyboard is expanded.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
