### ISSUE TITLE
input toolbar disappears behind keyboard when losing focus

### ISSUE THREAD

**Issue by DanielCreagh** [jessesquires/JSQMessagesViewController#1954]
How do I prevent the input toolbar from disappearing behind the keyboard when it loses focus e.g. when I want to type some text into another field.

I understand this is desired behaviour for certain kinds of chat client but not all. There should be a way of disabling this behaviour and setting the location of the input field manually.

(using version 7.3.0)

Thanks! :-D

**Comment by jessesquires** [comment]
Hey @DanielCreagh ! 

This was fixed in 7.3.4 -- please see if updating fixes your issue! 😄
