### ISSUE TITLE
Slack style where all messages are on the left

### ISSUE THREAD

**Issue by cerupcat** [jessesquires/JSQMessagesViewController#1955]
Is there a way to make it so all messages are on the left (as if they are all outgoing)? I can currently get it almost there by setting the senderId and senderDisplayName to a blank string. This will make all messages appear as outgoing. However, as soon as I sent a message, the send animation will put the message on the right side styled as the sender.

Without forking the library, would there be animate the sent message on the left (like an incoming message) rather than the right?

**Comment by MacMeDan** [comment]
All you have to do is make the`SederId` a string that is never an actual `SenderID` 
so set the current sender id to something and then create a different ID to call in the 
    override func didPressSend(_ button: UIButton, withMessageText text: String, senderId: String, senderDisplayName: String, date: Date) {

**Comment by jessesquires** [comment]
Going to keep this open as a feature request to consider for 8.0.

The library should accommodate this without resorting to hacky things like that.

**Comment by MacMeDan** [comment]
Sounds good 👍🏼

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
