### ISSUE TITLE
ATS compliance gspe19.ls.apple.com

### ISSUE THREAD

**Issue by yoovraj** [jessesquires/JSQMessagesViewController#1956]
## New issue checklist

- [o] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [o] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [o] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.2
- iOS version: ios10
- Devices/Simulators: both
- Reproducible in the demo project? (Yes/No): YES
- Any related issues:

## What happened?
When checking for maps information, the library connects to following servers on http.
I guess according to the ATS guide from apple, all the communications should be on https.
- gspe21.ls.apple.com
- gspe19.ls.apple.com

Also the domain to which it connects is not ATS compliant yet.
https://forums.developer.apple.com/message/201161

Currently it is running without any problem while loading the maps, but i am afraid if that would continue to work next year when apple makes it compulsory to use ATS compliant domains.

Regards,
Yoovraj Shinde

**Comment by jessesquires** [comment]
Thanks @yoovraj !

We'll look into this.

**Comment by yoovraj** [comment]
Thank you @jessesquires

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
