### ISSUE TITLE
JSQMessagesVideoThumbnailFactory.h file not found

### ISSUE THREAD

**Issue by tethridge** [jessesquires/JSQMessagesViewController#1957]
## General information

- `JSQMessagesViewController` version: Latest master from github on 12/15/2016
- iOS version: 10.2
- Devices/Simulators: all
- Reproducible in the demo project? (Yes/No): Yes
- Any related issues: No

## What happened? 

Swift example project will not build.  Error received in XCode is on line 23 of JSQVideoMediaItem.m.

#import "JSQMessagesVideoThumbnailFactory.h" // file not found

The example project should build without needing any modification.  BTW, the Objective C project builds fine.

**Comment by jefmwols** [comment]
We are having this same issue.  Is there a workaround?

**Comment by alimashuri** [comment]
Solved by pod install in swiftexample project  👍

**Comment by Premal-Khetani** [comment]
WE have the same issue if we install pod we are not able to find the JSQMessagesVideoThumbnailFactory file as well the "[[JSQVideoMediaItem alloc] initWithFileURL:videoURL isReadyToPlay:YES thumbnailImage:[UIImage imageNamed:@"Test"]];" method in JSQVideoMediaIItem.h file.

**Comment by Lucashuang0802** [comment]
@tethridge can you confirm if it's still an issue?  Looks like @alimashuri solved it by doing `pod install` again.

**Comment by tethridge** [comment]
That fixes the issue.
