### ISSUE TITLE
Text clear when append message

### ISSUE THREAD

**Issue by girishghoda** [jessesquires/JSQMessagesViewController#1958]
- `JSQMessagesViewController` version: latest pod
- iOS version:
- Devices/Simulators: iphone 5c
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?
My app have chat view and i used your library ,its cool library.
My issue is that i get message throew fcm, when fcm come i save that message in core data and fetch in chat view and append message use with message.append.
Issue is that when append message and at that time i type something in textinput is clear automatically.
Please help
Thank you

**Comment by coli88** [comment]
I'm having the same issue. Did you find a solution to this?

**Comment by girishghoda** [comment]
no

**Comment by hemantkadam** [comment]
Sorry @girishghoda but I didnt get your question, can you explain it one more time may be with some screenshot.

**Comment by girishghoda** [comment]
My app have chat view which used your library view

1 Any user send me message 
2 Message come from fcm notification
3 I save that message in core data (table)
4 fetch all message from table and reload tableview with method name > message.append
5 Issue is that when i write any message in textinput, at that time appending all message with use message.append method , message is clear in textinput

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
