### ISSUE TITLE
Input Tool bar broken constrains?

### ISSUE THREAD

**Issue by jpatinop** [jessesquires/JSQMessagesViewController#1959]
## General information

- `JSQMessagesViewController` version:  8.0.0
- iOS version: 10.1.1
- Devices/Simulators: Both
- Reproducible in the demo project? (Yes/No):  NO

## What happened?
I`m implementing the JSQMessages to my app, but when I press intro or I input a long text the input bar missing the constrains and start to go up like in the picture I attached, and never returns to its place.
![unknown-5](https://cloud.githubusercontent.com/assets/6492810/21280564/be2c9358-c3b4-11e6-976b-be72aa34242d.jpg)
... I´m not sure where to look to fix the problem, any body know how to fix it?

Thank you!!!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
