### ISSUE TITLE
Private vs group chats

### ISSUE THREAD

**Issue by jackpaster** [jessesquires/JSQMessagesViewController#1960]
@jessesquires First off, I love this project and what it can do. I will donate 5$ if you could help answer this question. Does jsqmessagesviewcontroller support both private and group chats. I have an app and I want it to be so that a user can have a private discussion with a particular user or an open discussion with the whole community. These will be two separate view controllers of course. Thanks and I hope to hear back from you.

**Comment by jessesquires** [comment]
Hey @jackpaster !

Yep! This is easy to do. There's nothing about that library that limits this. You can have 1:1 chats or group chats. All you need to do is configure the data source appropriately. Checkout the example project. 😄
