### ISSUE TITLE
Input Tool bar goes down out of screen during active call

### ISSUE THREAD

**Issue by TheEngineerz** [jessesquires/JSQMessagesViewController#1961]
How this error produced

1. Open chat screen (Everything works fine)
2. Connect the call 
3. Open chat screen again (Everything works fine)
4. Start typing in text field  (Everything works fine)
5. Resign the keyboard  (Error occurs)
4. Again start typing and resign the keyboard (Everything works fine)

My issue occurs only the first time when i resign the keyboard after opening the chat view controller during call
![img_4028 png](https://cloud.githubusercontent.com/assets/5149947/21353767/5b3ad526-c6bf-11e6-82ba-26c8f0fe3e40.png)

**Comment by MacMeDan** [comment]
This is an issue with the OS there is not a whole lot that we can do. You can file a radar with apple but that is about it.

**Comment by jessesquires** [comment]
I think this is fixed for 8.0 but not sure. Leaving open to check.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
