### ISSUE TITLE
JSQMessagesViewController - no such module  

### ISSUE THREAD

**Issue by jasonstatus** [jessesquires/JSQMessagesViewController#1963]
I've just inherited a chat app using Swift 3 and after I clean & build, Xcode says: no such module JSQMessagesViewController

Here are some of the things I've done:
    use_frameworks! in podfile
    Cleaned the project several times
    Reinstalled the pod 'JSQMessagesViewController'

Any advice?

**Comment by ngoclamnguyen** [comment]
Hi

Do you add this line in the Podfile

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'JobPoolChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobPoolChat

pod 'JSQMessagesViewController'


If you already added this line in the Podfile, maybe you should follow this instruction:

1. open Terminal, drag your project folder to Terminal after command cd
$ cd $YOUR_PROJECT_DIRECTORY
2. pod deintegrate
3. pod install

Hope this helps, :D.

**Comment by jessesquires** [comment]
Thanks @ngoclamnguyen !

**Comment by jasonstatus** [comment]
Hey sorry for the delay, its the holidays... Yes i tried the above suggestions and am still having trouble...

**Comment by ngoclamnguyen** [comment]
ok, maybe be you should following these instruction in this thread.
Hope some answers help your issue.

[http://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there](url)

**Comment by jasonstatus** [comment]
It returns a 404..

**Comment by ngoclamnguyen** [comment]
well, that's strange. You should copy that url and paste it to the browser. I have no idea why click on it cause the 404 error
