### ISSUE TITLE
Input Toolbar Weird Extra Height

### ISSUE THREAD

**Issue by rhenz** [jessesquires/JSQMessagesViewController#1964]
Hi,

Any idea why the background of inputToolbar has extra height? Please see screenshot. Thanks.

![screen shot 2016-12-23 at 1 51 15 am](https://cloud.githubusercontent.com/assets/7302529/21435049/74b1bc6e-c8b2-11e6-8684-79b071ee82c6.png)

**Comment by Lucashuang0802** [comment]
Thanks! 😄

Please provide all the information in the issue template so we can help!
And don't forget to read our contribution guidelines. 😊

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
