### ISSUE TITLE
[Default cell customization] 

### ISSUE THREAD

**Issue by AashishSapkota** [jessesquires/JSQMessagesViewController#1965]
## New issue checklist

- [yes ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ yes] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [yes ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: v2.0.2
- iOS version: ios 8 + 
- Devices/Simulators: 
- Reproducible in the demo project? (Yes/No): yes
- Any related issues: I just want to give value to the default available label, but unable to..

## What happened?
 I just want to give value to the default **celltoplabel.text** and **cellbuttomlabel.text** just to display at their default position. But I'm not getting any results in UI. Aren't these two labels the default one? 
Please show me a direction, i'm not getting anywhere..:(

**Comment by ngoclamnguyen** [comment]
Hi AashishSapkota

I amnot sure I understand your question well. But, did you add these following delegate methods in your JSQMessagesViewController subclass

- (CGFloat) collectionView: (JSQMessagesCollectionView *) collectionView
                    layout: (JSQMessagesCollectionViewFlowLayout *) collectionViewLayout heightForCellTopLabelAtIndexPath: (NSIndexPath *) indexPath
{
    return 0.0f;
}

- (CGFloat) collectionView: (JSQMessagesCollectionView *) collectionView
                    layout: (JSQMessagesCollectionViewFlowLayout *) collectionViewLayout heightForMessageBubbleTopLabelAtIndexPath: (NSIndexPath *) indexPath
{
    return 0.0f;
}

- (CGFloat) collectionView: (JSQMessagesCollectionView *) collectionView
                    layout: (JSQMessagesCollectionViewFlowLayout *) collectionViewLayout heightForCellBottomLabelAtIndexPath: (NSIndexPath *) indexPath
{
    return kJSQMessagesCollectionViewCellLabelHeightDefault;
}

if so, check the return value. If 0.0f, those label cannot be displayed.
You can you default height value: kJSQMessagesCollectionViewCellLabelHeightDefault

**Comment by AashishSapkota** [comment]
Oh! wow @ngoclamnguyen , that was what I needed. Thank you so much 👍
