### ISSUE TITLE
JSQMessagesViewAccessoryButtonDelegate.h not found in pod 7.3.4

### ISSUE THREAD

**Issue by yangboz** [jessesquires/JSQMessagesViewController#1967]
## New issue checklist
After pod install.

- `JSQMessagesViewController` version:7.3.4
- iOS version:10.2
- Devices/Simulators:6
- Reproducible in the demo project? (Yes/No): No
- Any related issues:

## What happened?
DemoMessagesViewController.m:20:9: 'JSQMessagesViewAccessoryButtonDelegate.h' file not found

**Comment by asifSdSol** [comment]
Is someone working on it?

**Comment by yangboz** [comment]
@asifSdSol Workaround:https://github.com/yangboz/DeepDetectMessager/tree/master/ChatBotJSQMessager/AIChatBots/JSQMessagesViewController

**Comment by alessioarsuffi** [comment]
@asifSdSol, @yangboz i've forked this repo and pushed a version 7.3.5 on cocoapods;
      
    pod "AAJSQMessagesViewController"

hope this helps :)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
