### ISSUE TITLE
Container View JSQMessagesViewContoller Not Showing

### ISSUE THREAD

**Issue by PrithiviMelio** [jessesquires/JSQMessagesViewController#1968]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by PrithiviMelio** [comment]
http://i.stack.imgur.com/7OOPV.png

**Comment by PrithiviMelio** [comment]
Container View JSQMessagesViewContoller Input tool bar Not Showing

**Comment by thegreatkingbear** [comment]
It looks like the development version has this issue.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
