### ISSUE TITLE
Possibility of having only buttons as input?

### ISSUE THREAD

**Issue by joshuaTTL** [jessesquires/JSQMessagesViewController#1969]
Hi, I have been a big fan for a long time and I am now having a pretty odd situation where I want to have only buttons for users as input and hide the input textfield. I know how to hide the whole toolbar but that makes the buttons disappear as well... Is there a possible way to do this? Thanks so much!

**Comment by ngoclamnguyen** [comment]
Hi joshuaTTL

I don't get it. You mean that you want to hide the textview like this

    self.inputToolbar.contentView.textView.hidden = YES;

In that case, how user input chat texts.

**Comment by jessesquires** [comment]
Thanks @ngoclamnguyen ! 😄
