### ISSUE TITLE
[Feature Request] Scroll to bottom floating button(like whats app)  to reach most recent messages

### ISSUE THREAD

**Issue by masterravi** [jessesquires/JSQMessagesViewController#1972]
## New issue checklist

- [✓ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [✓ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [✓ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:10.0
- Devices/Simulators: iphone 7 plus (simulator)
- Reproducible in the demo project? (Yes): 
- Any related issues:No

## What happened?
Hi ,

I know that we already have scroll to bottom feature   that's available and implemented successfully on my project also so please consider it as (feature request ).

I need a **floating button(like whatsapp have this feature)** that can be used to scroll to bottom when user load old messages and kind of 100 messages already loaded and user want to scroll back to bottom of message list.

Or please  let me know how can I implement this in my project using JSQChatViewController.

Thanks 

Ravindra Shekhawat

**Comment by ngoclamnguyen** [comment]
Hi Ravindra Shekhawat

Inside JSQMessagesViewController.m has these following codes.

NSIndexPath *lastCell = [NSIndexPath indexPathForItem: ([self.collectionView numberOfItemsInSection: 0] - 1) inSection: 0];
    
    [self.collectionView scrollToItemAtIndexPath: lastCell
                                atScrollPosition: UICollectionViewScrollPositionBottom
                                        animated: YES];

You should add those codes to your IBAction of your floating button.

Hope this help. :D

**Comment by masterravi** [comment]
@ngoclamnguyen  ,

I never wrote single line in objective - C .I am basically Android Developer but learned swift as per requirement .

Can you please  help me how to implement same code on swift.

@jessesquires  : Please consider it as feature request and if I will be able to implement it from my side will surely let you know guys .

**Comment by ngoclamnguyen** [comment]
no problem man , :D

Here is for swift 2.2
`@IBAction func floatingButtonPressed(sender: UIButton)
{
var lastCell = NSIndexPath(forItem: (self.collectionView!.numberOfItemsInSection(0) - 1), inSection: 0)
self.collectionView!.scrollToItemAtIndexPath(lastCell, atScrollPosition: .Bottom, animated: true)
}`

Here is for swift 3
`@IBAction func floatingButtonPressed(_ sender: UIButton)
{
var lastCell = IndexPath(item: (self.collectionView!.numberOfItems(inSection: 0) - 1), section: 0)
self.collectionView!.scrollToItem(at: lastCell, atScrollPosition: .bottom, animated: true)
}`

Hope that helps you, :D

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
