### ISSUE TITLE
Double tap gesture added to collection view does not work on bubbles

### ISSUE THREAD

**Issue by pardypanda** [jessesquires/JSQMessagesViewController#1973]
## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 9.3.5
- Devices/Simulators: iPhone 5S
- Reproducible in the demo project? (Yes/No):  Yes
- Any related issues: No

## What happened?

I'm adding singleTap and doubleTap gestures to MyJSQMessagesViewController as follows:

        // Setup Double Tap gesture
        doubleTapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didDoubleTapOnView))
        doubleTapGestureRecognizer.numberOfTapsRequired = 2
        doubleTapGestureRecognizer.delaysTouchesBegan = true
        doubleTapGestureRecognizer.delegate = self
        
        
        // Setup Single Tap gesture
        singleTapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didSingleTapOnView))
        singleTapGestureRecognizer.numberOfTapsRequired = 1
        singleTapGestureRecognizer.delegate = self
        singleTapGestureRecognizer.requireGestureRecognizerToFail(doubleTapGestureRecognizer)

        // Setup Double Tap gesture
        if ((self.collectionView.gestureRecognizers?.contains(doubleTapGestureRecognizer)) != nil) {
            self.collectionView.removeGestureRecognizer(doubleTapGestureRecognizer)
        }
        self.collectionView.addGestureRecognizer(doubleTapGestureRecognizer)
        
        // Setup Single Tap gesture
        if ((self.collectionView.gestureRecognizers?.contains(singleTapGestureRecognizer)) != nil) {
            self.collectionView.removeGestureRecognizer(singleTapGestureRecognizer)
        }
        self.collectionView.addGestureRecognizer(singleTapGestureRecognizer)

Double Tap selector gets called correctly everywhere on the View except when user does it on the chat bubbles. 

I'm also using the following delegate methods to log touch events:
didTapMessageBubbleAtIndexPath
didTapCellAtIndexPath
didTapAvatarImageView

For all 3 functions, I'm getting correct log. But these only work for single tap. 

How can I handle double tap on chat bubbles?

**Comment by pardypanda** [comment]
@jessesquires 
Alright, I've fixed it by modifying source code. 

When I looked into JSQMessagesCellTextView, I noticed that doubleTaps were being ignored on UITextView to prevent the Cut/Copy/Paste dialog from showing up, as such:

    - (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer
    {
        //  ignore double-tap to prevent copy/define/etc. menu from showing
        if ([gestureRecognizer isKindOfClass:[UITapGestureRecognizer class]]) {
            UITapGestureRecognizer *tap = (UITapGestureRecognizer *)gestureRecognizer;
            if (tap.numberOfTapsRequired == 2) {
                return NO;
            }
        }
        
        return YES;
    }

    - (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
    {
        //  ignore double-tap to prevent copy/define/etc. menu from showing
        if ([gestureRecognizer isKindOfClass:[UITapGestureRecognizer class]]) {
            UITapGestureRecognizer *tap = (UITapGestureRecognizer *)gestureRecognizer;
            if (tap.numberOfTapsRequired == 2) {
                return NO;
            }
        }
        
        return YES;
    }



However, this would mean that any other gesture recogniser with numberOfTapsRequired = 2 that was added to UITextView or it's parent views would also be ignored.

However, there is a way to allow custom gesture recognisers with numberOfTapsRequired = 2 to be detected while at the same time ignoring the default iOS double tap gesture recogniser on UITextView. 

Following are the changes required:

    - (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer
    {
        //  ignore double-tap to prevent copy/define/etc. menu from showing
        if ([gestureRecognizer isKindOfClass:[UITapGestureRecognizer class]]) {
            UITapGestureRecognizer *tap = (UITapGestureRecognizer *)gestureRecognizer;
            if (tap.numberOfTapsRequired == 2) {
                if([gestureRecognizer isMemberOfClass:[UITapGestureRecognizer class]]) {
                    return YES;
                } else {
                    return NO;
                }
            }
        }
        
        return YES;
    }

    - (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
    {
        //  ignore double-tap to prevent copy/define/etc. menu from showing
        if ([gestureRecognizer isKindOfClass:[UITapGestureRecognizer class]]) {
            UITapGestureRecognizer *tap = (UITapGestureRecognizer *)gestureRecognizer;
            if (tap.numberOfTapsRequired == 2) {
                if([gestureRecognizer isMemberOfClass:[UITapGestureRecognizer class]]) {
                    return YES;
                } else {
                    return NO;
                }
            }
        }
        
        return YES;
    }


The above change to return YES for isMemberOfClass for UITapGestureRecognizer will work for custom implementations of UITapGestureRecognizer with numberOfTapsRequired = 2  and ignore the default iOS response for double tap gesture recognizer

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
