### ISSUE TITLE
How to use JSQMessagesViewController ?Thank you very much

### ISSUE THREAD

**Issue by Huctor** [jessesquires/JSQMessagesViewController#1975]
Hello,

I use swift and I have tried to usr cocoapods to install "JSQMessagesViewController", but it doesn't work...
I add " pod 'JSQMessagesViewController' " in the Podfile, but it aways show "#import <JSQMessagesViewController/JSQMessages.h> not found", I have searched this in internet, I can not find an clear answer...
Could you give me a clear steps to install "JSQMessagesViewController", Thank you.

Now I try to install JSQMessagesViewController by manual, I downloaded the two sdk from https://github.com/jessesquires/JSQMessagesViewController and https://github.com/jessesquires/JSQSystemSoundPlayer. Then I added the two sdk in my project, but it show "ld: symbol(s) not found for architecture arm64", I didn't find an answer in internet.

Could you give me some steps or simple to install and use JSQMessagesViewController?

Thank you very much.

**Comment by MacMeDan** [comment]
Have you used cocoa pods before?

**Comment by haroonalpha** [comment]
i add this : pod 'JSQMessagesViewController' it works fine for me.

**Comment by apwelsh** [comment]
Also, it works best for swift to edit the podfile, and turn on the use frameworks line.  When usin frameworks, swift does not need a bridging header defined.  If you leave this feature off, you will need to create a bridging header file (a .h include file) that handles the imports you need to use the objective c library.
