### ISSUE TITLE
Invalid constraints errors when using dynamic height for the cell's top label

### ISSUE THREAD

**Issue by fraggjkee** [jessesquires/JSQMessagesViewController#1976]
- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: YES
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information
- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.2
- Devices/Simulators: iPhone 6 64GB
- Reproducible in the demo project? (Yes/No): No
- Any related issues: Haven't found anything related

## What happened?

Xcode prints the following errors when I scroll through the long chat history:

> [LayoutConstraints] Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
> (
>     "<NSAutoresizingMaskLayoutConstraint:0x174481b80 h=--& v=--& UIView:0x100974490.height == 38   (active)>",
>     "<NSLayoutConstraint:0x1744804b0 JSQMessagesLabel:0x10099e690.height == 20   (active)>",
>     "<NSLayoutConstraint:0x174480960 JSQMessagesLabel:0x10099e940.height == 20   (active)>",
>     "<NSLayoutConstraint:0x174481ea0 JSQMessagesLabel:0x1009a1aa0.height == 0   (active)>",
>     "<NSLayoutConstraint:0x174481fe0 V:|-(0)-[JSQMessagesLabel:0x10099e690]   (active, names: '|':UIView:0x100974490 )>",
>     "<NSLayoutConstraint:0x1744820d0 V:[JSQMessagesLabel:0x10099e690]-(0)-[JSQMessagesLabel:0x10099e940]   (active)>",
>     "<NSLayoutConstraint:0x174482170 V:[JSQMessagesLabel:0x10099e940]-(0)-[UIView:0x100982a50]   (active)>",
>     "<NSLayoutConstraint:0x174482300 V:[JSQMessagesLabel:0x1009a1aa0]-(0)-|   (active, names: '|':UIView:0x100974490 )>",
>     "<NSLayoutConstraint:0x174482350 V:[UIView:0x100982a50]-(0)-[JSQMessagesLabel:0x1009a1aa0]   (active)>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x174480960 JSQMessagesLabel:0x10099e940.height == 20   (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
> The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

I think this problem is related to the cell's `topLabel` and corresponding delegate methods. So if I either do not implement them or return nil / 0.0f values the log is clean. Another option to get rid of these errors is to return constant `height` value from the `heightForCellTopLabelAtIndexPath` method.

Here's my code:

```
- (NSAttributedString *)collectionView:(JSQMessagesCollectionView *)collectionView attributedTextForCellTopLabelAtIndexPath:(NSIndexPath *)indexPath
{
    if (path.item % 3 == 0) {
        MYPChatMessage *message = [self.messages objectAtIndex:path.item];
        return [[JSQMessagesTimestampFormatter sharedFormatter] attributedTimestampForDate:message.date];
    }
    
    return nil;
}

- (CGFloat)collectionView:(JSQMessagesCollectionView *)collectionView
                layout:(JSQMessagesCollectionViewFlowLayout *)collectionViewLayout heightForCellTopLabelAtIndexPath:(NSIndexPath *)indexPath
{
    if (path.item % 3 == 0) {
        return kJSQMessagesCollectionViewCellLabelHeightDefault;
    }
    
    return 0;
}
```

**Comment by torreylyons** [comment]
Note that this bug is also present when the using dynamic height for the message bubble's top label. With a fixed (zero height, nil string) cell top label but a variable message bubble top label I get an identical error in the console log.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
