### ISSUE TITLE
Typing Indicator display logic re: custom footers

### ISSUE THREAD

**Issue by crrobinson14** [jessesquires/JSQMessagesViewController#1977]
I'm trying to create a custom section footer and, for my app, the best approach is subclassing `JSQMessagesTypingIndicatorFooterView` as described in #995, #826, etc. I have a subclass that overrides `nib` and `reuseIdentifier`, and the footer displays how and where I want - but then it disappears! This happens about a half second after my data loads, not long after my final call to `finishReceivingMessage`.

It's obvious there's logic controlling the display of the typing indicator, but nothing I've tried will get it to display again. Debugging the view hierarchy confirms it's actually gone, not hidden. Calling `[self setShowTypingIndicator:YES];` doesn't work, even if I try doing it delayed, like dispatching it 1s into the future.

What's weird is if I SCROLL, the footer immediately shows up. I just can't seem to get it to show programmatically.

I've tried stepping through this logic but I'm coming up dry. Any pointers?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
