### ISSUE TITLE
Unable to keep different text color for incoming and outgoing message bubble

### ISSUE THREAD

**Issue by ashu1702** [jessesquires/JSQMessagesViewController#1978]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by ashu1702** [comment]
Found it in earlier issues. Sorry

**Comment by jessesquires** [comment]
No worries @ashu1702 ! 😄 

Could you note the issue here in case others find this?

**Comment by otymartin** [comment]
@ashu1702 please not the issue.. trying to solve the same problem, thanks :)
