### ISSUE TITLE
Toolbar dismissing when open a pop up view

### ISSUE THREAD

**Issue by matheusjkweber** [jessesquires/JSQMessagesViewController#1980]
## New issue checklist

- [x] I have read the [`README`]
- [x] [Contributing guidelines]
- [x] I have searched [existing issues]

## General information

- `JSQMessagesViewController` version: 8.0
- iOS version: 9.2
- Devices/Simulators: 
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?
When open a pop up view with other fields, the toolbar is dismissed and never go back.

The pop up view has another input control and it get the focus, jsq is removing the superview from its inputToolbar.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
