### ISSUE TITLE
LocationMediaItem stuck on loading

### ISSUE THREAD

**Issue by Florensvb** [jessesquires/JSQMessagesViewController#1981]
Hey guys,

so I've just tried implementing the LocationMediaItem in my Xamarin.iOS app using JSQMessagesViewController. Everything worked out fine, only problem is that the collectionview cell which is supposed to show the location is stuck on loading forever and the map is never actually being displayed. 
Here's some code how i make the locationMediaItem in C#:
```
var locationMediaItem = new LocationMediaItem(new CLLocation(latitude, longitude));

	if (ChatDB.Messages[indexPath.Row].user_id == SenderId)
	{
		locationMediaItem.AppliesMediaViewMaskAsOutgoing = true;
		return JSQMessagesViewController.Message.Create(ChatDB.Messages[indexPath.Row].user_id, User.Instance.name, locationMediaItem);
	}
```

Here is an image of what I mean:
![img_5354](https://cloud.githubusercontent.com/assets/7792052/21896184/bccba846-d8e5-11e6-94c9-27c5e67f75e6.PNG)

Hope you guys can help me out,

Thanks Jesse Squires for making this amazing library! Big thumbs up!

**Comment by TheEngineerz** [comment]
@Florensvb Did you find any solution ?

**Comment by Florensvb** [comment]
@TheEngineerz No unfortunately not yet.

**Comment by dangnguyenhuu** [comment]
here is may code in swift 
```
            let location = CLLocation(latitude: Double(texts[0])!, longitude: Double( texts[1])!)
            let JSQlocation = JSQLocationMediaItem()
            
            JSQlocation.setLocation(location, withCompletionHandler: {
                self.collectionView.reloadData()
            })
```
maybe you need some thing like " self.collectionView.reloadData() " in clourse

**Comment by ajpinedam** [comment]
Code in Xamarin.IOS:

    `var itemLocationItem = new LocationMediaItem ();`
     `itemLocationItem.SetLocation (new CLLocation (lat, long), HandleLocationMediaItemCompletionBlock);`

And the completion handler:
    `void HandleLocationMediaItemCompletionBlock ()
     {
         this.CollectionView.ReloadData ();
      }`

**Comment by Florensvb** [comment]
Both the code from dangnguyenhuu and ajpinedam helped me solve this issue. I did not know I had to attach a completionhandler in order to refresh the collectionView.

**Comment by deore123** [comment]
@Florensvb  Can you Please tell me which pod I have to install for sharing location in chatView of JSQMessageViewController? I possible can you share your code?
