### ISSUE TITLE
Sort cells

### ISSUE THREAD

**Issue by Elshad** [jessesquires/JSQMessagesViewController#1982]
Is there have any function or property for sorting bubbles-cells?

**Comment by jessesquires** [comment]
Hey @Elshad !

Not sure what you mean? If you sort your data source, then cells will display in that order. 😄

**Comment by Elshad** [comment]
Sorry for my bad English. I mean when we add date to bubble, does it cause sorting by date?

**Comment by jessesquires** [comment]
Nope, you determine the order 😄
