### ISSUE TITLE
Which version should I use for my new project? v8.0 or v7.3.x

### ISSUE THREAD

**Issue by vietstone** [jessesquires/JSQMessagesViewController#1983]
Sorry, but I'm not familiar with this library. So my question is Which version (8.0 or 7.3.x) should I use for my new project? My project is in Xcode 8, Swift 3.
Thank you. You can close the issue immediately.

**Comment by jessesquires** [comment]
Hey @vietstone 😄 

8.0 is still under development. You should use the latest official release.

https://github.com/jessesquires/JSQMessagesViewController/releases

**Comment by vietstone** [comment]
yes, thank you :D
