### ISSUE TITLE
Avatar image disappears in custom cells

### ISSUE THREAD

**Issue by woogii** [jessesquires/JSQMessagesViewController#1985]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: YES
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: ios10 
- Devices/Simulators: Both
- Reproducible in the demo project? (Yes/No): Yes

## What happened?

Thanks to the FAQ document, I was able to implement a custom cell in my JSQMessagesViewController's subclass . Everything seems to work fine but avatar image.  
When I run my app, avatar images don't appear on the screen. I didn't apply any constraints in my custom cells and constraint values of custom cells are exactly same as those of JSQMessagesCollectionViewCellOutgoing, JSQMessagesCollectionViewCellIncoming.  I wrote code in my viewcontroller like below. 

```

lazy var incomingAvatarImageView: JSQMessagesAvatarImage = self.setupIncomingAvartar()

override func viewDidLoad() {
    // I want to show incomingAvatarImageView only
    collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSize.zero
    collectionView.collectionViewLayout.incomingAvatarViewSize = CGSize(width: kJSQMessagesCollectionViewAvatarSizeDefault, height:kJSQMessagesCollectionViewAvatarSizeDefault )
}

private func setupIncomingAvartar() -> JSQMessagesAvatarImage {
    return JSQMessagesAvatarImageFactory.avatarImageWithImage(avatarImage, diameter: 30)
}

override func collectionView(collectionView: JSQMessagesCollectionView!, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageAvatarImageDataSource! {
    
    let message = messages[indexPath.row]
    // I want to show incomingAvatarImageView only
    if message.senderId != self.senderId {
      return incomingAvatarImageView
    } else {
      return nil
    }
  }
```

This is a screenshot image of my simulator. 

![simulator screenshot](https://cloud.githubusercontent.com/assets/9043226/22137551/1a917b4c-df1f-11e6-88ea-a8b12f3b1a3d.png)

I debugged the view hierarchy and found out that Avatar container view and Avatar imageView were not properly laid out. This is a screenshot of Avatar container view's constraints info. 

![ui_debug_screenshot_small](https://cloud.githubusercontent.com/assets/9043226/22137913/495596dc-df21-11e6-841b-848fb3638b8b.png)

I couldn't find out any solution and have no idea how to solve this issue. Should I subclass the JSQMessagesCollectionViewFlowLayout to properly layout AvatarImage? Could anyone give me advice?

**Comment by ngoclamnguyen** [comment]
I have same issue. I already tried the way in this thread.
https://github.com/jessesquires/JSQMessagesViewController/issues/1739

The avatar images will disappear, If I set the custom classes in Identity Inspector are my Custom Class of my custom incoming, outgoing cell xib files.
But they  show off when I set the custom classes in Identity Inspector are JSQMessagesCollectionViewCellIncoming, JSQMessagesCollectionViewCellOutgoing respectively.
That's weird but useful.

<img width="259" alt="screen shot 2017-01-27 at 7 42 54 pm" src="https://cloud.githubusercontent.com/assets/16101163/22371366/659e53a8-e4c9-11e6-8734-3201c288d5a6.png">

You should try that. Hope that helps you. :D

**Comment by woogii** [comment]
Thanks for your comment. But when I changed the custom class names of custom incoming, outgoing cell xib files in Identity Inspector, my application crashed with an error. (libc++abi.dylib: terminating with uncaught exception of type NSException). Are there any extra settings you did for making custom cells work?

**Comment by ngoclamnguyen** [comment]
Did you follow the instruction in this thread???
https://github.com/jessesquires/JSQMessagesViewController/issues/1739

the answer of @jasonwcfan

**Comment by mucahittekin** [comment]
the problem is from the JSQMessagesCollectionViewCell.m line 202
`  if ([self isKindOfClass:[JSQMessagesCollectionViewCellIncoming class]]) {
        self.avatarViewSize = customAttributes.incomingAvatarViewSize;
    }
    else if ([self isKindOfClass:[JSQMessagesCollectionViewCellOutgoing class]]) {
        self.avatarViewSize = customAttributes.outgoingAvatarViewSize;
    }`

if you define custom cell this lines ignores because of your custom class is not kind of JSQMessagesCollectionViewCellIncoming or JSQMessagesCollectionViewCellOutgoing

**Comment by woogii** [comment]
Yes, I followed all the necessary steps that are described in FAQ. 
As you can see in the screenshot below, I was able to add UILabels to both custom incoming and outgoing cells. 

![img_5221_small](https://cloud.githubusercontent.com/assets/9043226/22378284/76c0b94e-e4f8-11e6-89b3-90278abbc285.png)

Like you said, I undid the step 3 but it crashed.  These are my source code related to custom cells.

 
```
    self.outgoingCellIdentifier = CustomMessagesCollectionViewCellOutgoing.cellReuseIdentifier()
    self.outgoingMediaCellIdentifier = CustomMessagesCollectionViewCellOutgoing.mediaCellReuseIdentifier()
    
    self.collectionView.register(CustomMessagesCollectionViewCellOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingCellIdentifier)
    self.collectionView.register(CustomMessagesCollectionViewCellOutgoing.nib(), forCellWithReuseIdentifier: self.outgoingMediaCellIdentifier)
    
    self.incomingCellIdentifier = CustomMessagesCollectionViewCellIncoming.cellReuseIdentifier()
    self.incomingMediaCellIdentifier = CustomMessagesCollectionViewCellIncoming.mediaCellReuseIdentifier()
    
    self.collectionView.register(CustomMessagesCollectionViewCellIncoming.nib(), forCellWithReuseIdentifier: self.incomingCellIdentifier)
    self.collectionView.register(CustomMessagesCollectionViewCellIncoming.nib(), forCellWithReuseIdentifier: self.incomingMediaCellIdentifier)
```

```
class CustomMessagesCollectionViewCellOutgoing: CustomMessagesCollectionViewCell {
  
  @IBOutlet weak var readStatusLabel: UILabel!
  @IBOutlet weak var timeStampLabel: UILabel!
   
  override func awakeFromNib() {
    
    super.awakeFromNib()
    self.messageBubbleTopLabel.textAlignment = NSTextAlignment.right
    self.cellBottomLabel.textAlignment = NSTextAlignment.right
  }
  
  override class func cellReuseIdentifier() -> String {
    return "CustomMessagesCollectionViewCellOutgoing"
  }
  
  override class func nib() -> UINib {
    return UINib(nibName: "CustomMessagesCollectionViewCellOutgoing", bundle: nil)
  }
  
  override class func mediaCellReuseIdentifier() -> String {
    return "CustomMessagesCollectionViewCellOutgoing_JSQMedia"
  }
  
}
```

```
class CustomMessagesCollectionViewCellIncoming: CustomMessagesCollectionViewCell {
  
  @IBOutlet weak var timeStampLabel: UILabel!
  
  override func awakeFromNib() {
    super.awakeFromNib()
    self.messageBubbleTopLabel.textAlignment = NSTextAlignment.left
    self.cellBottomLabel.textAlignment = NSTextAlignment.left

  }
  
  override class func cellReuseIdentifier() -> String {
    return "CustomMessagesCollectionViewCellIncoming"
  }
  
  override class func nib() -> UINib {
    return UINib(nibName: "CustomMessagesCollectionViewCellIncoming", bundle: nil)
  }
  
  override class func mediaCellReuseIdentifier() -> String {
    return "CustomMessagesCollectionViewCellIncoming_JSQMedia"
  }
}
```

**Comment by ngoclamnguyen** [comment]
The answer of @mucahittekin  is right. @woogii your JSQMessageViewController subclass need these function too. Here is my solution.

`func collectionView(collectionView: JSQMessagesCollectionView, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath) -> AnyObject JSQMessageAvatarImageDataSource {
        var message = self.messages.objectAtIndex(indexPath.item)
        var previousMessage = nil
        var nextMessage = nil
        if indexPath.item > 0 {
            previousMessage = self.messages.objectAtIndex(indexPath.item - 1)
        }
        if (indexPath.item + 1) < self.messages.count {
            nextMessage = self.messages.objectAtIndex(indexPath.item + 1)
        }
        var isFirstMessage = self.isFirstMessage(message, andPrevious: previousMessage)
        if isFirstMessage {
            var imageUrl = nil
            imageUrl = self.isOutgoingMessage(message) ? self.currentUser.photoURL : self.recipient.photoURL
            var avatarImageView = UIImageView()
            avatarImageView.sd_setImageWithURL(imageUrl, placeholderImage: UIImage(named: "profile_holder"))
            return JSQMessagesAvatarImageFactory.avatarImageWithImage(avatarImageView.image, diameter: kJSQMessagesCollectionViewAvatarSizeDefault)
        }
        return nil
    }
    
    func collectionView(collectionView: JSQMessagesCollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        var messageItem = collectionView.dataSource.collectionView(collectionView, messageDataForItemAtIndexPath: indexPath)
        NSParameterAssert(messageItem != nil)
        var isOutgoingMessage = self.isOutgoingMessage(messageItem)
        var isMediaMessage = messageItem.isMediaMessage()
        var cellIdentifier = nil
        if isMediaMessage {
            cellIdentifier = isOutgoingMessage ? self.outgoingMediaCellIdentifier : self.incomingMediaCellIdentifier
        } else {
            cellIdentifier = isOutgoingMessage ? self.outgoingCellIdentifier : self.incomingCellIdentifier
        }
        var cell = collectionView.dequeueReusableCellWithReuseIdentifier(cellIdentifier, forIndexPath: indexPath) as! JPCCustomCollectionViewCell
        cell.delegate = collectionView
        if !isMediaMessage {
            cell.textView.attributedText = NSAttributedString(string: messageItem.text(), attributes: [NSFontAttributeName: collectionView.collectionViewLayout.messageBubbleFont])
            cell.textView.linkTextAttributes = [NSForegroundColorAttributeName: lightBlueColor, NSUnderlineStyleAttributeName: (NSUnderlineStyleSingle | NSUnderlinePatternSolid)]
            NSParameterAssert(cell.textView.text != nil)
            var bubbleImageDataSource = collectionView.dataSource.collectionView(collectionView, messageBubbleImageDataForItemAtIndexPath: indexPath)
            cell.messageBubbleImageView.image = bubbleImageDataSource.messageBubbleImage()
            cell.messageBubbleImageView.highlightedImage = bubbleImageDataSource.messageBubbleHighlightedImage()
        } else {
            var messageMedia = messageItem.media()
            cell.mediaView = messageMedia.mediaView() ?? messageMedia.mediaPlaceholderView()
            NSParameterAssert(cell.mediaView != nil)
        }
        var needsAvatar = true
        if isOutgoingMessage && CGSizeEqualToSize(collectionView.collectionViewLayout.outgoingAvatarViewSize, CGSizeZero) {
            needsAvatar = false
        } else if !isOutgoingMessage && CGSizeEqualToSize(collectionView.collectionViewLayout.incomingAvatarViewSize, CGSizeZero) {
            needsAvatar = false
        }
        var avatarImageDataSource = nil
        if needsAvatar {
            avatarImageDataSource = collectionView.dataSource.collectionView(collectionView, avatarImageDataForItemAtIndexPath: indexPath)
            if avatarImageDataSource != nil {
                var avatarImage = avatarImageDataSource.avatarImage()
                if avatarImage == nil {
                    cell.avatarImageView.image = avatarImageDataSource.avatarPlaceholderImage()
                    cell.avatarImageView.highlightedImage = nil
                } else {
                    cell.avatarImageView.image = avatarImage
                    cell.avatarImageView.highlightedImage = avatarImageDataSource.avatarHighlightedImage()
                }
                cell.avatarImageView.layer.cornerRadius = CGRectGetWidth(cell.avatarImageView.frame) / 2
                cell.avatarImageView.layer.masksToBounds = true
                cell.avatarImageView.backgroundColor = ultraLightGrayColor
            }
        }
        cell.cellTopLabel.attributedText = collectionView.dataSource.collectionView(collectionView, attributedTextForCellTopLabelAtIndexPath: indexPath)
        cell.messageBubbleTopLabel.attributedText = collectionView.dataSource.collectionView(collectionView, attributedTextForMessageBubbleTopLabelAtIndexPath: indexPath)
        cell.cellBottomLabel.attributedText = collectionView.dataSource.collectionView(collectionView, attributedTextForCellBottomLabelAtIndexPath: indexPath)
        var bubbleTopLabelInset = (avatarImageDataSource != nil) ? 60.0f : 15.0f
        if isOutgoingMessage {
            cell.messageBubbleTopLabel.textInsets = UIEdgeInsetsMake(0.0f, 0.0f, 0.0f, bubbleTopLabelInset)
        } else {
            cell.messageBubbleTopLabel.textInsets = UIEdgeInsetsMake(0.0f, bubbleTopLabelInset, 0.0f, 0.0f)
        }
        cell.textView.dataDetectorTypes = UIDataDetectorTypeAll
        cell.backgroundColor = UIColor.clearColor()
        cell.layer.rasterizationScale = UIScreen.mainScreen().scale
        cell.layer.shouldRasterize = true
        self.dismissKeyboardAndStickerViewWhenTapInCollectionViewCell(cell)
        return cell
    }
    
    func isFirstMessage(current: JPCMessage, andPrevious previous: JPCMessage) -> Bool {
        NSParameterAssert(current.senderId() != nil)
        return previous.senderId().isEqualToString(current.senderId()) ? false : true
    }
    
    func isLastMessage(current: JPCMessage, andNext next: JPCMessage) -> Bool {
        NSParameterAssert(current.senderId() != nil)
        return next.senderId().isEqualToString(current.senderId()) ? false : true
    }`

**Comment by ngoclamnguyen** [comment]
what the heck is happening with source code format, :(

**Comment by mucahittekin** [comment]
Maybe we need a pull request to make public 
`@property (assign, nonatomic) CGSize avatarViewSize;` 
in JSQMessagesCollectionViewCell so we can easily do this solution:
in our CustomCell class
`override func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
        super.apply(layoutAttributes)
        
        let customAttributes = layoutAttributes as! JSQMessagesCollectionViewLayoutAttributes
        if self is CustomOutgoingCell {
            avatarViewSize = customAttributes.outgoingAvatarViewSize
        }else if self is CustomIncomingCell {
            avatarViewSize = customAttributes.incomingAvatarViewSize
        }
    }`

**Comment by mucahittekin** [comment]
@ngoclamnguyen :)
check out https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by ngoclamnguyen** [comment]
thanks man, I've got it. But sometimes it's crazy, :D

**Comment by woogii** [comment]
Thank you both @ngoclamnguyen, @mucahittekin. @mucahittekin's suggestion sounds good as it can be an easy solution. Changing custom class name in storyboard still does not work and leads to a crash of my app.

**Comment by ryderjack** [comment]
Also having this issue - my avatar images have disappeared since implementing custom cells after following @jasonwcfan 's great instructions! 

Also checked out #1909 but unfortunately no solution for me yet..

**Comment by dangnguyenhuu** [comment]
Hi, Im also facing same problem. Is there any solution?

**Comment by hammad** [comment]
Anyone found a solution? my avatars also disappeared after using custom cells. Though I just copied the xib files from the pod resources of JSQMessagesViewController and attached them to my custom classes.

**Comment by hammad** [comment]
Ok I found the solution thanks to @mucahittekin comment about "JSQMessagesCollectionViewCell.m line 202"

**Solution:** instead of subclassing your custom class from JSQMessagesCollectionViewCell, subclass it from either of the classes JSQMessagesCollectionViewCellIncoming or JSQMessagesCollectionViewCellOutgoing and your avatars will start appearing.

**Comment by woogii** [comment]
@hammad  Thank you for your comment. It works like a charm. :)

**Comment by jessesquires** [comment]
thanks all!

**Comment by saltwat5r** [comment]
I think that replacing `JSQMessagesCollectionViewCellIncoming` class with protocol would be better approach. Currently I can't have common base class for Incoming and Outgoing messages, which inherits from JSQMessagesCollectionViewCell and be Incoming or Outgoing.
