### ISSUE TITLE
Show delete menu action for certain cells?

### ISSUE THREAD

**Issue by dylanshine** [jessesquires/JSQMessagesViewController#1993]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.0
- Devices/Simulators: iPhone 7

I haven't been able to find an example of this, but how do you allow the delete menu action item to appear for certain cells. In my case, I only want message cells that have been sent by the current user to show the delete action. I guess this question applies to all native and custom menu item actions.

Thank you :)

**Comment by acjh** [comment]
Implement something like:

```swift
override func collectionView(_ collectionView: UICollectionView, canPerformAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?) -> Bool {
    if action == #selector(delete(_:)) {
        return self.messages[indexPath.item].senderDisplayName() == self.senderDisplayName
    }
    return super.collectionView(collectionView, canPerformAction: action, forItemAt: indexPath, withSender: sender)
}
```

**Comment by dylanshine** [comment]
@acjh Ty so much!
