### ISSUE TITLE
InputToolbar does not follow keyboard, Input bar getting hide when i start to write in IOS10

### ISSUE THREAD

**Issue by manjujain17** [jessesquires/JSQMessagesViewController#1994]
![simulator screen shot 26-jan-2017 5 37 10 pm](https://cloud.githubusercontent.com/assets/25365540/22330964/daeae71a-e3ee-11e6-8ff1-45f1ed2b21a8.png)

## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by dustinspengler** [comment]
i noticed that if i moved `self.collectionView.collectionViewLayout.springinessEnabled = true` to my `viewWillAppear` function instead of `viewDidAppear` I no longer had this problem.
