### ISSUE TITLE
How to add Header/Custom View to JSQMessagesViewController?

### ISSUE THREAD

**Issue by glennposadas** [jessesquires/JSQMessagesViewController#1995]
Hi, I couldn't find any information on this repo on how to post questions. Do you have Gitter? Or should questions be posted on Stackoverflow? I see question here in Issues section. Anyways, I posted this question on Stackoverflow already, but it seems no one is answering. 

http://stackoverflow.com/questions/41906757/how-to-add-header-custom-view-to-jsqmessagesviewcontroller

Thanks.

**Comment by dtochetto** [comment]
See: https://github.com/jessesquires/JSQMessagesViewController/issues/901

**Comment by MacMeDan** [comment]
You can change anything you like but here is how to do it very simply programatically.

call `addViewOnTop()` this in your `viewDidLoad`

    func addViewOnTop() {
        let selectableView = UIView(frame: CGRect(x: 0, y: 60, width: self.view.bounds.width, height: 40))
        selectableView.backgroundColor = .red
        let randomViewLabel = UILabel(frame: CGRect(x: 20, y: 10, width: 100, height: 16))
        randomViewLabel.text = "RandomView"
        selectableView.addSubview(randomViewLabel)
        view.addSubview(selectableView)
    }
