### ISSUE TITLE
Scroll to bottom does not work properly when collectionView has more than one section

### ISSUE THREAD

**Issue by daedalus87** [jessesquires/JSQMessagesViewController#1997]
Scroll to bottom does not work properly when collectionView has more than one section because JSQMessagesViewController supposes that there is only one section.

ScrollToBottom method always scrolls to the last cell of section 0. It does not support multiple sections.

**Comment by ngoclamnguyen** [comment]
Of course, it is. If you looking at JSQMessagesViewController.m (or JSQMessagesViewController.swift), you'll realize that scrollToBottomAnimated and scrollToIndexPath methods only works well on 0th section.
Why do you need more section???

**Comment by daedalus87** [comment]
Hi, because I want to group my messages by a custom criteria.

For example, grouped by date:

[March 17] (section 0) (custom section header)
[message 1]
[message 2]
[message 3]

[Apr 2] (section 1) (custom section header)
[message 4]
[message 5]

.. and so on.

**Comment by ngoclamnguyen** [comment]
In that case, you just have to modified these method on your JSQMessagesViewController subclass

```objective-c
- (CGFloat) collectionView: (JSQMessagesCollectionView *) collectionView
                    layout: (JSQMessagesCollectionViewFlowLayout *) collectionViewLayout heightForCellTopLabelAtIndexPath: (NSIndexPath *) indexPath
{
    return 0.0f;
}

- (CGFloat) collectionView: (JSQMessagesCollectionView *) collectionView
                    layout: (JSQMessagesCollectionViewFlowLayout *) collectionViewLayout heightForMessageBubbleTopLabelAtIndexPath: (NSIndexPath *) indexPath
{
    return 0.0f;
}

- (CGFloat) collectionView: (JSQMessagesCollectionView *) collectionView
                    layout: (JSQMessagesCollectionViewFlowLayout *) collectionViewLayout heightForCellBottomLabelAtIndexPath: (NSIndexPath *) indexPath
{
    JPCMessage *message = [self.messages objectAtIndex: indexPath.item];
    JPCMessage *previousMessage = nil;
    JPCMessage *nextMessage = nil;
    
    // Hien thi label thoi gian o tin nhan dau tien cua user (trong 1 nhom message cua user)
    if (indexPath.item > 0)
    {
        previousMessage = [self.messages objectAtIndex: indexPath.item - 1];
    }
    
    // Hien thi label thoi gian o tin nhan cuoi cung cua user (trong 1 nhom message cua user)
    if ((indexPath.item + 1) < self.messages.count)
    {
        nextMessage = [self.messages objectAtIndex: indexPath.item + 1];
    }
    
    return [self configureCellLabelHeightAtIndexPath: indexPath
                                  withCurrentMessage: message
                                     previousMessage: previousMessage
                                         nextMessage: nextMessage];
}

#pragma mark - Incoming, Outcoming CellBottomLabel Configuration Method

- (CGFloat) configureCellLabelHeightAtIndexPath: (NSIndexPath *) indexPath
                             withCurrentMessage: (JPCMessage *) current
                                previousMessage: (JPCMessage *) previous
                                    nextMessage: (JPCMessage *) next
{
    // Hien thi chieu cao cua Cell Bottom Label cho message dau tien
    //    BOOL isFirstMessage = [self isFirstMessage: current andPrevious: previous];
    // Hien thi chieu cao cua Cell Bottom Label cho message cuoi cung
    BOOL isLastMessage = [self isLastMessage: current andNext: next];
    
    // Neu la tin nhan cuoi cung cua user thi cho hien thi CellBottomLabel
    // Default la: kJSQMessagesCollectionViewCellLabelHeightDefault
    // force: 13.2f
    // (trong 1 nhom message cua user)
    if (isLastMessage)
    {
        return 13.2f;
    }
    
    // Nguoc lai chieu cao cua CellBottomLabel la 0.0f
    return 0.0f;
}
```

Just modify the height, text, background color, ... of your needed label (top, bottom, or message bubble top label) for 'separating' your messages group.

If you still want to do as your choice, you must override these methods
+ finishReceivingMessage / finishReceivingMessageAnimated
+ scrollToBottomAnimated
+ scrollToIndexPath
in your JSQMessagesViewController subclass. It is a bit of trouble to do that. Be careful.

**Comment by daedalus87** [comment]
Thanks for your suggestion.

I find quite simple to override scrollToBottomAnimated and scrollToIndexPath to support multiple sections (finishReceivingMessage/finishReceivingMessageAnimated are not needed) because I only need to change 2 or 3 lines in the JSQMessagesViewController class. The other good reason to override that methods is that I don't need to implement indexpath calculations that mess my code.

I've submitted a [PR](https://github.com/jessesquires/JSQMessagesViewController/pull/1998) with the necessary changes to support it.

**Comment by ngoclamnguyen** [comment]
man, changing directly the JSQMessagesViewController class is final option. I don't really recommend that work. It's cruel, you should find other ways to solve your problem.

**Comment by jessesquires** [comment]
Thanks @ngoclamnguyen !
