### ISSUE TITLE
Slim down the Library

### ISSUE THREAD

**Issue by ferdinand95** [jessesquires/JSQMessagesViewController#2001]
First of all: Thanks for making this awesome library!

I'm using the latest version for my project. Although the wide range of functionality is great, I'm purely using it for a text-based chat.
I'm noticing that the performance of the Collection View while scrolling isn't perfect and there is a slight lag from time to time.
I'm not using avatars, not using the labels for the user names and I'm purely using text-bubbles.

Is there a provided way to slim the library down to increase performance or should I just comment out parts I don't need and remove the Image Views from the XIB of the CollectionViewCell?

I searched through past posts but couldn't find something related.

Thanks! :)

**Comment by jessesquires** [comment]
Thanks @ferdinand95 ! 😄 

You can opt-out of most of these things and can provide custom cells if you want.

v8.0 of the library aims to address this further, too.
