### ISSUE TITLE
collectionView.keyboardDismissMode = .none is not working 

### ISSUE THREAD

**Issue by mosluce** [jessesquires/JSQMessagesViewController#2002]
## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.2(14C89)
- Devices/Simulators: iPhone SE, iPhone 7 plus, iPhone 6s(simulators)
- Reproducible in the demo project? (Yes/No):  No
- Any related issues: #1192

## What happened?
My code
![2017-02-02 11 07 48](https://cloud.githubusercontent.com/assets/1487051/22535722/ded9609c-e937-11e6-9b0f-64611e87cd71.png)

and run, but keyboard still be hide when I swiped down

**Comment by mosluce** [comment]
I tried to reproduce in the demo project. It's working, but not in my project.
![2017-02-02 3 28 34](https://cloud.githubusercontent.com/assets/1487051/22541070/01b4c314-e95f-11e6-8f6e-2e3faaad1e5a.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
