### ISSUE TITLE
Dynamic photo size.

### ISSUE THREAD

**Issue by vyudi** [jessesquires/JSQMessagesViewController#2005]
## New issue checklist

- [X] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version: All version
- Devices/Simulators: All devices
- Reproducible in the demo project? (Yes/No): Yes
- Any related issues:

## What happened?

If I have a lot of images with different sizes, the bubbles repeat the size of the other image.

I see :
*bubbleSizeCalculator;
*mediaViewDisplaySize

But I have the same result.

**Comment by vyudi** [comment]
![captura de tela 2017-02-06 as 16 43 25](https://cloud.githubusercontent.com/assets/4665545/22661156/78791b7e-ec8b-11e6-9e57-2380f0a20c87.png)

**Comment by vyudi** [comment]
![captura de tela 2017-02-06 as 16 44 39](https://cloud.githubusercontent.com/assets/4665545/22661184/9936f91c-ec8b-11e6-95a8-2fa7f1f636f8.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
