### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by mhtranbn** [jessesquires/JSQMessagesViewController#2006]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?

Many thanks  for boss, can you support for swift 3. Current Example Swift problem. @hexedbits

**Comment by jessesquires** [comment]
Thanks @mhtranbn !

We'll be providing better Swift support in the 8.0 release.

**Comment by yarodevuci** [comment]
@jessesquires Really? When are you planning on 8.0 release?

**Comment by AmeerChand** [comment]
have you provide swift 3 support.
