### ISSUE TITLE
Messages not appending properly

### ISSUE THREAD

**Issue by chand97** [jessesquires/JSQMessagesViewController#2007]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.2

![messages app](https://cloud.githubusercontent.com/assets/25543597/22624046/f7af6970-eb91-11e6-8166-3b9b579aa4d0.gif)

## What happened?

Whenever I try to append a message to JSQMessages array it doesn't appear at the end of the collectionView

My code for retrieving messages:

```
func retrieveMessages() {

    let messagesRef = databaseRef.child("messages")
    var senderID : String!
    var recieverID : String!
    var message : JSQMessage!

   messagesRef.observe(.value, with: { (snapshot) in

   if let dictionary = snapshot.value as? [String : AnyObject] {

    self.messages.removeAll()

    for each in dictionary {

        let mediaType = each.value["mediaType"] as! String
        let text = each.value["text"] as! String
        let senderDisplayName = each.value["senderDisplayName"] as! String
         senderID = each.value["senderID"] as! String
         recieverID = each.value["reciverID"] as! String
        let time = each.value["time"] as! Int
        message = JSQMessage(senderId: senderID, displayName: senderDisplayName, text: text)

        if senderID == FIRAuth.auth()?.currentUser?.uid {

            if recieverID == self.userUID {

                self.messages.append(message)
                self.collectionView.reloadData()
            }

          }

        }

    }
```

My code for sending messages:

```
override func didPressSend(_ button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: Date!) {

    JSQSystemSoundPlayer.jsq_playMessageSentSound()
    finishSendingMessage(animated: true)

    let newMessage = messagesRef.childByAutoId()
    let currentTime = Date()
    let currentTimePassed = currentTime.timeIntervalSince1970
    let timeInt = Int(currentTimePassed)
    let messageData = ["text" : text, "senderID" : senderId, "senderDisplayName" : senderDisplayName, "mediaType" : "TEXT", "reciverID" : userUID, "time" : timeInt] as [String : Any]
    newMessage.setValue(messageData)
}
```

**Comment by acjh** [comment]
You are rebuilding `self.messages` each time, instead of only appending the new messages.
See this example: https://github.com/firebase/ios-swift-chat-example/blob/master/FireChat-Swift/MessagesViewController.swift#L33

**Comment by chand97** [comment]
Can you please tell me what adjustments do I need to make to my code

**Comment by acjh** [comment]
1. Replace `.value` with `.childAdded`
2. Remove `self.messages.removeAll()`

**Comment by chand97** [comment]
When I change my code to the following I get " fatal error: unexpectedly found nil while unwrapping an Optional value (lldb) " 

```
func retrieveMessages() {
        
        let messagesRef = databaseRef.child("messages")
        var senderID : String!
        var recieverID : String!
        var message : JSQMessage!
        
       messagesRef.observe(.childAdded, with: { (snapshot) in
        
       if let dictionary = snapshot.value as? [String : AnyObject] {
        
          for each in dictionary {
            
            let mediaType = each.value["mediaType"] as! String
            let text = each.value["text"] as! String
            let senderDisplayName = each.value["senderDisplayName"] as! String
             senderID = each.value["senderID"] as! String
             recieverID = each.value["reciverID"] as! String
            let time = each.value["time"] as! Int
            message = JSQMessage(senderId: senderID, displayName: senderDisplayName, text: text)
            
            if senderID == FIRAuth.auth()?.currentUser?.uid {
                
                if recieverID == self.userUID {
                    
                    self.messages.append(message)
                    self.collectionView.reloadData()
                }
                
              }
            
            }
            
        }

        self.finishReceivingMessage(animated: true)
        self.collectionView.reloadData()
        
        
       }, withCancel: nil)
    }
```

**Comment by acjh** [comment]
Which line does that error occur on? Try printing `dictionary` to see what it contains.

**Comment by chand97** [comment]
It occurs on the mediaType line

**Comment by acjh** [comment]
Maybe `dictionary` is already a single message.

**Comment by chand97** [comment]
This is what I get in my console:

![error-1](https://cloud.githubusercontent.com/assets/25543597/22626638/0106493e-ebd4-11e6-9337-c66b79d093f1.png)
![error-2](https://cloud.githubusercontent.com/assets/25543597/22626641/09fccf0e-ebd4-11e6-9f3a-51633034a05e.png)
![error-3](https://cloud.githubusercontent.com/assets/25543597/22626642/0b0a18ac-ebd4-11e6-9c5e-922d5ae995f6.png)

**Comment by acjh** [comment]
So instead of `for each in dictionary`, do `mediaType = dictionary["mediaType"] as! String`.

**Comment by chand97** [comment]
Thanks a lot acjh it finally works!

**Comment by chand97** [comment]
Now I am not able to receive messages which have been sent by other users.This is my code for retrieving messages:

```
func retrieveMessages() {
        
        let messagesRef = databaseRef.child("messages")
        var senderID : String!
        var recieverID : String!
        var message : JSQMessage!
        
       messagesRef.observe(.childAdded, with: { (snapshot) in
        
       if let dictionary = snapshot.value as? [String : AnyObject] {
   
        let mediaType = dictionary["mediaType"] as! String
        let text = dictionary["text"] as! String
        let senderDisplayName = dictionary["senderDisplayName"] as! String
        senderID = dictionary["senderID"] as! String
        recieverID = dictionary["reciverID"] as! String
        let time = dictionary["time"] as! Int
        message = JSQMessage(senderId: senderID, displayName: senderDisplayName, text: text)
        
            if senderID == FIRAuth.auth()?.currentUser?.uid {
                
                if recieverID == self.userUID {
                    
                    self.messages.append(message)
                    self.collectionView.reloadData()
                }
                
              }
            
            }
```
        
        self.finishReceivingMessage(animated: true)
        self.collectionView.reloadData()
        
        
       }, withCancel: nil)
    }

![firebase-1](https://cloud.githubusercontent.com/assets/25543597/22644351/0719de0c-ec84-11e6-8fa8-e9d43373a0af.png)
![firebase-2](https://cloud.githubusercontent.com/assets/25543597/22644354/075ea4ec-ec84-11e6-9949-d4038bdfa133.png)
![id s](https://cloud.githubusercontent.com/assets/25543597/22644353/075b6d72-ec84-11e6-9afb-413985b445ac.png)
![messages](https://cloud.githubusercontent.com/assets/25543597/22644352/075b02a6-ec84-11e6-9449-e1ef935a96ab.png)

**Comment by acjh** [comment]
Remove these 2 conditions for appending messages:
- `if senderID == FIRAuth.auth()?.currentUser?.uid {`
- `if recieverID == self.userUID {`

**Comment by chand97** [comment]
But now I get these messages for all users..

**Comment by acjh** [comment]
You may want:
```swift
if (senderID == FIRAuth.auth()?.currentUser?.uid) || (recieverID == self.userUID) {
```

**Comment by chand97** [comment]
No it doesn't help...messages sent by me are appearing on all users

**Comment by acjh** [comment]
Or just:
```swift
if recieverID == self.userUID {
```

**Comment by chand97** [comment]
I have already checked out that...My messages still appear on all users

**Comment by acjh** [comment]
How about:
```swift
if recieverID == FIRAuth.auth()?.currentUser?.uid {
```

**Comment by chand97** [comment]
Now its only showing messages sent by other user on all users

**Comment by acjh** [comment]
Well, what do you want to show?

**Comment by chand97** [comment]
Messages sent by me to a specific user only appears on that user and messages sen by another user to me only appear on my chat view

![users](https://cloud.githubusercontent.com/assets/25543597/22646755/c6979eee-ec8f-11e6-8e23-d9bb9aa646ac.png)

**Comment by chand97** [comment]
SenderID is my UID where as recieverID is the ID of the person whom I am sending the message the userUID is also the ID of the person who will receive the message...I am getting userID from the usersTableView

**Comment by acjh** [comment]
Then you may need:
```swift
let currentUser = FIRAuth.auth()?.currentUser?.uid
let otherUser = self.userUID
if (senderID == currentUser && recieverID == otherUser) ||
   (senderID == otherUser && recieverID == currentUser) {
```

**Comment by chand97** [comment]
Thanks a lot Aaron,my app works perfectly fine
