### ISSUE TITLE
MediaView Bubble Mask Distorted

### ISSUE THREAD

**Issue by dreeanic** [jessesquires/JSQMessagesViewController#2008]
Hello,

I'm having an issue applying a mask to the media items I subclassed. What I'm doing is this, in cellForItemAtIndexPath:

```
let bubbleImage = UIImage(named: "msgBgTail")
if let factory = JSQMessagesBubbleImageFactory(bubbleImage: bubbleImage, capInsets: UIEdgeInsetsZero) {
    let masker = JSQMessagesMediaViewBubbleImageMasker(bubbleImageFactory: factory)
    if isOutGoing {
        masker.applyOutgoingBubbleImageMaskToMediaView(mediaView)
    } else {
        masker.applyIncomingBubbleImageMaskToMediaView(mediaView)
    }
} else {
    //Apply the default mask
    JSQMessagesMediaViewBubbleImageMasker.applyBubbleImageMaskToMediaView(mediaView, isOutgoing: isOutGoing)
}
```

This looks great on first load, but when the data is reloaded (eg, when receiving a new message) the mask seems to be applied a fraction of a second later, enough time to visually see a rectangle transforming into the bubble mask shape.
I'm wrapping the reload in an UIView.performWithoutAnimation. This takes care of the text sliding into the correct position (I'm adding custom text insets) but the mask is still bad to look at.

I thought about subclassing JSQMessagesBubbleImageFactory, but I'm not sure how to use it to achieve a smooth behavior. Can you give me any insight into this?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
