### ISSUE TITLE
override preferredStatusBarStyle

### ISSUE THREAD

**Issue by quangas** [jessesquires/JSQMessagesViewController#2009]
Is there a way to override this and set it to lightContent instead of default black in the controller only?

i.e inside `ChatViewController : JSQMessagesViewController`

```
override func preferredStatusBarStyle() -> UIStatusBarStyle {
        return UIStatusBarStyle.lightContent
    }
```

**Comment by acjh** [comment]
@quangas It would be nice if you can share how you solved this, for others who encounter this in the future.

**Comment by quangas** [comment]
Apologies, here is what I did. Since I have the ChatViewController extending JSQMessagesViewController as a UINavigationController, I simply did the following in `viewDidLoad`:

`self.navigationController?.navigationBar.barStyle = UIBarStyle.black`

In the ViewController that segues to ChatViewController I already had the following:

```
override var preferredStatusBarStyle : UIStatusBarStyle {
        return UIStatusBarStyle.lightContent
}
```

So the statusBarStyle seems to comes through to the ChatViewController as well.
