### ISSUE TITLE
CollectionView cell flicking

### ISSUE THREAD

**Issue by kuldeep13990** [jessesquires/JSQMessagesViewController#2011]
when i try to add new data in existing array and than i call performBatchUpdates, it loads new data but the existing data flicking..

i try to invalidate layout with context but nothing happened.

CGFloat bottomOffset = self.collectionView.contentSize.height - self.collectionView.contentOffset.y;
NSArray *newData = media;
        [self.searchCollectionView performBatchUpdates:^{
            int resultsSize = (int)[popularPostArr count]; //data is the previous array of data
            [popularPostArr addObjectsFromArray:newData];
            NSMutableArray *arrayWithIndexPaths = [NSMutableArray array];
            
            for (int i = resultsSize; i < resultsSize + newData.count; i++) {
                [arrayWithIndexPaths addObject:[NSIndexPath indexPathForRow:i
                                                                  inSection:0]];
            }
            [self.searchCollectionView insertItemsAtIndexPaths:arrayWithIndexPaths];
        } completion::^(BOOL finished) {
                        if (isChangeContentSize) {
                            self.collectionView.contentOffset = CGPointMake(0, self.collectionView.contentSize.height - bottomOffset);
                        }
                        else {
                            isChangeContentSize = true;
                        }];

Thanks in advance..

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
