### ISSUE TITLE
JSQMessageAvatarImageDataSource example

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [jessesquires/JSQMessagesViewController#2013]
## New issue checklist

- [✓ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ✓] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ✓] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 9.3.5
- Devices/Simulators: Device (iPhone 5)
- Reproducible in the demo project? (Yes/No): No
- Any related issues: No

I'm trying to get avatar images to show up in group chats. My Participant model class has a property to hold a URL to their profile image. In the docs it says

> Your avatar model objects should conform to the `JSQMessageAvatarImageDataSource` protocol.

I'm not sure what it means by avatar model objects. Do you mean my participant objects have to conform to `JSQMessageAvatarImageDataSource`?

I'd appreciate any clarification on this.

**Comment by acjh** [comment]
Create an avatar: [.../SwiftExample/SwiftExample/DemoConversation.swift#L60](https://github.com/jessesquires/JSQMessagesViewController/blob/458f0fc9ca1622e8411bd29aa4eba9377e00e350/SwiftExample/SwiftExample/DemoConversation.swift#L60)
```swift
let image = UIImage(named:"demo_avatar_jobs")!
let avatar = JSQMessagesAvatarImageFactory().avatarImage(withImage: image)
```

Return the avatar in: [.../SwiftExample/SwiftExample/ChatViewController.swift#L349](https://github.com/jessesquires/JSQMessagesViewController/blob/458f0fc9ca1622e8411bd29aa4eba9377e00e350/SwiftExample/SwiftExample/ChatViewController.swift#L349)
```swift
override func collectionView(_ collectionView: JSQMessagesCollectionView,
    avatarImageDataForItemAt indexPath: IndexPath) -> JSQMessageAvatarImageDataSource?
```

**Comment by Isuru-Nanayakkara** [comment]
Thanks @acjh! Some of my avatar images are URLs. Is there a way to load avatars asynchronously?

**Comment by jessesquires** [comment]
Thanks @acjh ! 💯

**Comment by palmitoto** [comment]
Could you answer to @Isuru-Nanayakkara las question : Is there a way to load avatars asynchronously? Thanx

**Comment by terflogag** [comment]
I'm also interest by loading avatar asynchronously... :)

**Comment by klipnov** [comment]
1)I load default images for the avatar in `avatarImageDataForItemAt`
2)download all the required images
3)after each image is downloaded call `collectionView.reloadData()`
4)this will reload `avatarImageDataForItemAt`. This time the avatar is ready to be used 👍 

@palmitoto 
@terflogag
