### ISSUE TITLE
message toolbar is disappearing when calling UIControllerSheet

### ISSUE THREAD

**Issue by yarodevuci** [jessesquires/JSQMessagesViewController#2014]
Hi @jessesquires 
I would like to know if there is any way to prevent hiding input message toolbar from hiding when UIAlert is called

JSQMessagesViewController version: 7.3.4
iOS version: 10 and 8 same thing
Reproducible in the demo project? (Yes)

**Comment by yarodevuci** [comment]
Anyone had same issue??

**Comment by nileshjaiswal16** [comment]
I have same issue please let me know if u will find solution.
