### ISSUE TITLE
Tapping InputToolbar causes Keyboard to resign

### ISSUE THREAD

**Issue by otymartin** [jessesquires/JSQMessagesViewController#2016]
@jessesquires 

I couldnt find a related issue despite all the keyboard/toolbar issues.

My problem is that while fast typing, you are hitting all over the `inputToolBar` and many times this causes it to resign the keyboard. I noticed the sample app doesnt have this behaviour so is there maybe a way to turn it off?

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10
- Devices/Simulators: 7
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
