### ISSUE TITLE
[Costum Cell] How to costum the bubble so we can have send time inside the bubble

### ISSUE THREAD

**Issue by sacrificar** [jessesquires/JSQMessagesViewController#2018]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version: 9.0
- Devices/Simulators: Devices
- Reproducible in the demo project? Yes
- Any related issues: I want to resize the textview inside the bubble with constraint in XIB but the constraint is replaced by other constraint

## What happened?
I want to create a custom view like this
![flow_goalie_chat](https://cloud.githubusercontent.com/assets/8979317/23115381/0b5f47ce-f777-11e6-925f-95b14c17992e.jpg)

Then I try to change it in custom XIB file. But some how, the constraint for textview that I put on the XIB was replaced by default constraint. How to handle this in Objective-C?

This is the XIB 
![screen shot 2017-02-20 at 2 37 18 pm](https://cloud.githubusercontent.com/assets/8979317/23115910/43d68844-f77a-11e6-9f6b-b43898b74d6d.png)

**Comment by HuppDevelopers** [comment]
Hi,
Please update me too..
I also want same feature.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by ikyh** [comment]
@sacrificar Hi.. Did you get the solution?  Please revert.
