### ISSUE TITLE
UI jerks when loading earlier messages 

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [jessesquires/JSQMessagesViewController#2019]
## New issue checklist

- [✓] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [✓] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [✓] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 9.3.5
- Devices/Simulators: Device (iPhone 5)
- Reproducible in the demo project? (Yes/No): Yes
- Any related issues:

## What happened?

I'm using the `top-infinitescrolling` branch of [SVPullToRefresh](https://github.com/gabro/SVPullToRefresh/tree/top-infinitescrolling) in conjunction with `JSQMessagesViewController` to load earlier messages as you scroll up. Below is the relevant code.

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    
    automaticallyAdjustsScrollViewInsets = false
    
    collectionView.addInfiniteScrolling(actionHandler: {
        self.loadChatHistory()
    }, direction: UInt(SVInfiniteScrollingDirectionTop))
}

fileprivate func loadChatHistory() {
    var oldMessages: [JSQMessage] = []
    for i in 1 ... 15 {
        let msg = JSQMessage(senderId: "2", senderDisplayName: "Tony", date: Date(), text: "Reply \(i)")!
        oldMessages.append(msg)
    }
    
    collectionView.infiniteScrollingView.startAnimating()
    
    CATransaction.begin()
    CATransaction.setDisableActions(true)
    
    let oldBottomOffset = self.collectionView.contentSize.height - self.collectionView.contentOffset.y
    collectionView.performBatchUpdates({
        
        let lastIndex = oldMessages.count - 1
        var indexPaths: [IndexPath] = []
        for i in 0...lastIndex {
            indexPaths.append(IndexPath(item: i, section: 0))
        }
        
        for message in oldMessages {
            self.messages.insert(message, at: 0)
        }
        self.collectionView.insertItems(at: indexPaths)
        
        // invalidate layout
        self.collectionView.collectionViewLayout.invalidateLayout(with: JSQMessagesCollectionViewFlowLayoutInvalidationContext())
        
    }, completion: { finished in
        self.collectionView.layoutIfNeeded()
        self.collectionView.contentOffset = CGPoint(x: 0, y: self.collectionView.contentSize.height - oldBottomOffset)
        CATransaction.commit()
        
        self.collectionView.infiniteScrollingView.stopAnimating()
    })
}
```

The loading older messages part works fine. But there is a noticeable jerk/flash in the UI whenever it happens ([See gif](https://i.imgur.com/EwYhTyQ.gifv)). I uploaded a demo project [here](https://www.dropbox.com/s/37yyhlwig4h1kgv/LoadChatHistory.zip?dl=0) as well.

**Comment by sbuzoianu** [comment]
Isuru,

do you have some improvement on this case? I have the same problem with flashing when put on previous messages loaded from [JSQMessages] on collectionView. I think it's a collectionView problem on this case.

**Comment by satizh-j** [comment]
Hey Isru , first of all thanks for providing the demo. the UI jerk is happening because of the for loop. you have to run calculations/extensive calculations in the background to avoid it. please try the below code. 

`    fileprivate func loadChatHistory() {
        
        
        
        DispatchQueue.main.async(execute: {
        
        var oldMessages: [JSQMessage] = []
        for i in 1 ... 15 {
            let msg = JSQMessage(senderId: "2", senderDisplayName: "Tony", date: Date(), text: "Reply \(i)")!
            oldMessages.append(msg)
        }
        
        self.collectionView.infiniteScrollingView.startAnimating()
        
        CATransaction.begin()
        CATransaction.setDisableActions(true)
        
        let oldBottomOffset = self.collectionView.contentSize.height - self.collectionView.contentOffset.y
        self.collectionView.performBatchUpdates({
            
            let lastIndex = oldMessages.count - 1
            var indexPaths: [IndexPath] = []
            for i in 0...lastIndex {
                indexPaths.append(IndexPath(item: i, section: 0))
            }
            
            for message in oldMessages {
                self.messages.insert(message, at: 0)
            }
            self.collectionView.insertItems(at: indexPaths)
            
            // invalidate layout
            self.collectionView.collectionViewLayout.invalidateLayout(with: JSQMessagesCollectionViewFlowLayoutInvalidationContext())
            
        }, completion: { finished in
            self.collectionView.layoutIfNeeded()
            self.collectionView.contentOffset = CGPoint(x: 0, y: self.collectionView.contentSize.height - oldBottomOffset)
            CATransaction.commit()
            
            self.collectionView.infiniteScrollingView.stopAnimating()
        })
        
        })
        
    }`

**Comment by ChildishTimbino** [comment]
I'm not the OP, but I'm trying to implement the same thing. I'm using Swift 3/Xcode 8, and can't seem to import the SVPullToRefresh framework. I added the pod, but nothing is showing up when I try to import. Any ideas why this is happening?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
