### ISSUE TITLE
 'avatarImage' cannot be used on instance of type 'JSQMessagesAvatarImageFactory'

### ISSUE THREAD

**Issue by eliteproxy7** [jessesquires/JSQMessagesViewController#2020]
When i try to set up an avatar image i get 

ChatViewController.swift:159:16: Static member 'avatarImage' cannot be used on instance of type 'JSQMessagesAvatarImageFactory'

`    override func collectionView(_ collectionView: JSQMessagesCollectionView!, avatarImageDataForItemAt indexPath: IndexPath!) -> JSQMessageAvatarImageDataSource! {
         let message = messages[indexPath.item]     
        return getAvatar(message.senderId)
    }
    
  
   
    
func getAvatar(_ id: String) -> JSQMessagesAvatarImage{

        return JSQMessagesAvatarImageFactory().avatarImage(withPlaceholder: UIImage(named:"Dummy_Photo")!)
    }`

**Comment by cresouls** [comment]
I laso have the same issue. Have you solved it?

**Comment by ChinmayDB** [comment]
use JSQMessagesAvatarImageFactory.avatarImage(withPlaceholder: UIImage(named:"Dummy_photo")!,diameter:1)

**Comment by Lucashuang0802** [comment]
thanks, @ChinmayDB. 👍 💯 🎉
