### ISSUE TITLE
No code signature found after install pod

### ISSUE THREAD

**Issue by amirch123** [jessesquires/JSQMessagesViewController#2022]
After I installed a pod into my project, I am getting error saying
NO CODE SIGNATURE FOUND 
and the project is not implemented.
I found an article related to the issue. The article suggests that need to be include some code signing bypass to the pod file as below

```
    post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
   end
 end
```
I am using Xcode(8.1).

The remarkable thing is, I do not have a developer account.

But it does not solve my problem. What solution would you recommend?

**Comment by Lucashuang0802** [comment]
Thanks, @amirch123. This does not seem to be related to the library. 😃
