### ISSUE TITLE
Margins not adjusting after hiding Avatars when using a custom JSQMessagesCollectionViewFlowLayout

### ISSUE THREAD

**Issue by marsman12019** [jessesquires/JSQMessagesViewController#2024]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10
- Devices/Simulators: iPhone 7 Simulator
- Reproducible in the demo project? (Yes/No):  No
- Any related issues: N/A

## What happened?

I've followed the instructions exactly for hiding Avatars (setting the `incoming` and `outgoingAvatarViewSize` to `.zero`, and returning `nil` in an overwritten `avatarImageDataForItemAt`), but when I use a custom `JSQMessagesCollectionViewFlowLayout` (even if there are no overridden functions defined within it) there are considerable margins remaining where the avatars would be displayed in my app.

Thoughts on how to clear that up?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
