### ISSUE TITLE
Input toolbar reappears over action sheet

### ISSUE THREAD

**Issue by scotteg** [jessesquires/JSQMessagesViewController#2025]
- Version: **7.3.4**
- iOS version: **10.2**
- Devices/Simulators: **iPhone 7 device, all iPhone simulators**
- Reproducible in the demo project?: **Yes**

If input toolbar's text view is first responder when an action sheet is presented, the input toolbar reappears after the action sheet is presented, on top of the action sheet.

Reproducible in demo project:
https://github.com/scotteg/JSQMessagesViewController/tree/input-toolbar

![simulator screen shot feb 25 2017 4 49 30 am](https://cloud.githubusercontent.com/assets/1337867/23330538/dafb7452-fb15-11e6-9881-babc5c94fa6c.png)

![simulator screen shot feb 25 2017 4 49 33 am](https://cloud.githubusercontent.com/assets/1337867/23330540/df32a4d2-fb15-11e6-9000-0772df43db2e.png)

**Comment by scotteg** [comment]
![jsqmessagesviewcontroller-input-toolbar](https://cloud.githubusercontent.com/assets/1337867/23330645/98a8872c-fb18-11e6-8a16-8697ff406a31.gif)

**Comment by scotteg** [comment]
![jsqmessagesviewcontroller-input-toolbar](https://cloud.githubusercontent.com/assets/1337867/23330652/c60a10aa-fb18-11e6-83a1-661cc0030653.gif)

**Comment by otymartin** [comment]
@scottcc did you ever fix this? Im experiencing the same despite resigning textview as first responder before presenting UIAlertController

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
