### ISSUE TITLE
Message in the Input tool bar disappears when I leave the chat view and return 

### ISSUE THREAD

**Issue by vic2tee4u** [jessesquires/JSQMessagesViewController#2026]
When typing a message and I leave the chatview (in my app, I go back to recent chats). when I return , all the text disappears. Also When a new message is received , the current text I am inputting disappears too.

Has anyone encountered this or is able to solve it?

**Comment by nileshjaiswal16** [comment]
I Have same issue if u will find any solution then please let me know.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
