### ISSUE TITLE
Great Tutorial Objective-C

### ISSUE THREAD

**Issue by asifSdSol** [jessesquires/JSQMessagesViewController#2027]
As it is clearly written in the documentations. 

"Ray Wenderlich has a great tutorial, written by David East. (For 7.x releases)"

But it is in the swift, any tutorial in Objective-C.

**Comment by jessesquires** [comment]
Thanks @asifSdSol ! 😄 

The provided demo project is in ObjC

**Comment by hempoudyal** [comment]
Hi @asifSdSol can i have the demo project. Thanks!
