### ISSUE TITLE
JSQMediaItem corner radius

### ISSUE THREAD

**Issue by antons81** [jessesquires/JSQMessagesViewController#2028]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version: 10.2
- Devices/Simulators: 10.2 iPhone 7
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?

Hello All, how I could provide custom radius to JSQMediaItem?

  let incoming  = UIImage(named: "incoming")
        let factory = JSQMessagesBubbleImageFactory(bubble: incoming, capInsets: .zero)
        let masker = JSQMessagesMediaViewBubbleImageMasker(bubbleImageFactory: factory)
        masker?.applyIncomingBubbleImageMask(toMediaView: imgView)
        

       //JSQMessagesMediaViewBubbleImageMasker.applyBubbleImageMask(toMediaView: imgView, isOutgoing: self.appliesMediaViewMaskAsOutgoing)

but it's still big corner radius

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
