### ISSUE TITLE
How you would make Call To Action responses. So basically a question with multiple answers int the form of buttons to click?

### ISSUE THREAD

**Issue by btripp** [jessesquires/JSQMessagesViewController#2029]
I am making a chat bot and I want a way for my bot to present a users a question and multikple answers to choose from. 

## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by jessesquires** [comment]
Thanks @btripp ! :smile: 

This doesn't seem specific to the library. StackOverflow is a more appropriate place to ask this question. :blush:

I'm going to close this issue, but the community should feel free to continue the discussion here.

### Other ways to get help:

* Ask on [StackOverflow](http://stackoverflow.com/questions/tagged/jsqmessagesviewcontroller) with the `jsqmessagesviewcontroller` tag
* See the [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/FAQ.md)
* Search [previous questions](https://github.com/jessesquires/JSQMessagesViewController/issues?utf8=✓&q=label%3A%22questions+%26+help%22+)
