### ISSUE TITLE
Changing size of send button

### ISSUE THREAD

**Issue by SebastianKumor** [jessesquires/JSQMessagesViewController#2031]
I am increasing size of input toolbar with ` self.inputToolbar.preferredDefaultHeight` and I would also like to increase height of the send button. I am using send button with a custom image that doesnt stretch with the input toolbar and stays the default size. It also stays on the bottom of the bar and its not centred. I am looking for something like this but for height `self.inputToolbar.contentView.rightBarButtonItemWidth` thx for any help.

**Comment by rodrigoreis22** [comment]
I'm struggling with this too.. did you find a solution @SebastianKumor  ?

**Comment by SebastianKumor** [comment]
@rodrigoreis22 not really, I just went with the size that is default. But if you find a way how to do it please let me know.

**Comment by HuppDevelopers** [comment]
I did it with storyboard.
go to demo file, you will file named with JSQMessagesToolbarContentView.
in xib file you can change its size.
I did it and it works for me.

**Comment by Lucashuang0802** [comment]
@HuppDevelopers, thanks for the info. 💯 👍

**Comment by TheEngineerz** [comment]
@Lucashuang0802 this was not the proper solution and you closed the issue this is not fair.

**Comment by Lucashuang0802** [comment]
Hi @TheEngineerz, it is not an uncommon case to fork the project and change for your own need. Each project has different requirements and the best we can do is to provide something generic and something easy.

As for your case, I agree with you on a more extensible solution. However, we currently do not have such thing in the roadmap. Let's say we do have it, it might take a while to provide as none of us get paid to contribute to this project. We do it for fun and for the passion of this project. So, the fast and easy solution is to fork it and change your desired size. 

Whoever comments someone here, they are trying to be helpful. So, I really suggest supporting those who are trying.
