### ISSUE TITLE
How to set the bubble clear background but with border in Swift 3.0?

### ISSUE THREAD

**Issue by alanting850420** [jessesquires/JSQMessagesViewController#2032]
https://raw.githubusercontent.com/jessesquires/JSQMessagesViewController/develop/Screenshots/screenshot3.png

Here's my Code, But it didn't work like the sample picture
How to set the bubble clear background but with border in Swift 3.0,  like the sample picture?

let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as! JSQMessagesCollectionViewCell
        let msg = messages[indexPath.row]
        let maskPath: UIBezierPath = UIBezierPath(roundedRect: cell.textView.bounds, byRoundingCorners: ([.bottomLeft, .bottomRight]), cornerRadii:CGSize(width: 10.0, height: 10.0))
        var maskLayer = CAShapeLayer()
        maskLayer.frame = cell.textView.bounds
        maskLayer.path = maskPath.cgPath
        cell.textView.layer.mask = maskLayer
        cell.textView.layer.masksToBounds = true
        if msg.senderId! == senderId {
            cell.textView.layer.mask =  maskLayer
            cell.textView.layer.borderColor = ButtonNoneColor.cgColor
        }else{
            cell.textView.layer.borderColor = ButtonClickColor.cgColor
        }
        cell.textView.linkTextAttributes = [NSForegroundColorAttributeName: cell.textView.textColor ?? UIColor.white]
        cell.textView.layer.borderWidth = 2
        cell.textView.textColor = UIColor.black
        cell.textView.clipsToBounds = true
return cell

**Comment by dongyuan** [comment]
You can just simply do 
```
let incomingBubble = JSQMessagesBubbleImageFactory(bubble: UIImage.jsq_bubbleRegularStroked(), capInsets: .zero).incomingMessagesBubbleImage(with: UIColor.blue)
....
....

    override func collectionView(_ collectionView: JSQMessagesCollectionView?, messageBubbleImageDataForItemAt indexPath: IndexPath!) -> JSQMessageBubbleImageDataSource? {
        return messages[indexPath.item].senderId == AvatarIdWoz ? outgoingBubble : incomingBubble
    }
    

```
you can also use your own image for it. check the image used in above sample from below link:
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle/Images/bubble_stroked%403x.png

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
