### ISSUE TITLE
How to increase height of the bubble for emojis?

### ISSUE THREAD

**Issue by jsifalda** [jessesquires/JSQMessagesViewController#2033]
Hello Guys, i would like to get some help on topic of increasing font size for emojis. 
I want to increase font size of a message in case the text contains only emojis. 
In this function: collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) 
I setup font size like this: 
cell.textView.font = UIFont.systemFontOfSize(80)

However, this is what will happen:
![screen shot 2017-03-06 at 8 46 35 pm](https://cloud.githubusercontent.com/assets/1549390/23612575/84726fc8-02ae-11e7-9919-8dd715ae6656.png)
and after a few seconds it get aligned like this:
![screen shot 2017-03-06 at 8 46 46 pm](https://cloud.githubusercontent.com/assets/1549390/23612603/9d4a374c-02ae-11e7-9744-7bb460caec7f.png)

I have checked related issues but still not able to figure out the solution. 

Thank you very much for pointing me into the right direction.

**Comment by jessesquires** [comment]
Thanks @jsifalda ! 😄 

This is a current limitation in the framework, which dictates that all messages must be the same font size.

Most likely, this won't make it on the roadmap for upcoming releases. 😞
