### ISSUE TITLE
Data detectors not working in iOS9

### ISSUE THREAD

**Issue by dreeanic** [jessesquires/JSQMessagesViewController#2034]
I'm using custom cells, subclassing JSQMessagesCollectionViewCell. The links in the textView are working as expecting on iOS 10, but nothing happens when tapping on a link in iOS 9. Adding a gesture recogniser to the cell will trigger that one instead of being intercepted and the url opening.

Inspecting the cell in willDisplayCell I'm seeing for the textview: editable is false, selectable is true, userInteraction is true, dataDetectorTypes.contains(.All) is true.

Did this ever happen to anyone else? What could be wrong?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
