### ISSUE TITLE
Frame incorrect within UIPageViewController

### ISSUE THREAD

**Issue by Tinyik** [jessesquires/JSQMessagesViewController#2038]
<img width="377" alt="screen shot 2017-03-11 at 11 29 44 pm" src="https://cloud.githubusercontent.com/assets/10971026/23829915/a42953a6-06b2-11e7-83e9-99785561e7af.png">

**Comment by Tinyik** [comment]
Update: Issue could be solved by resetting the frame of view.

**Comment by Lucashuang0802** [comment]
@Tinyik, thanks for confirming. Closing this issue. 👍
