### ISSUE TITLE
How to show inputToolbar again after if hides when custom Video is played

### ISSUE THREAD

**Issue by TheEngineerz** [jessesquires/JSQMessagesViewController#2041]
Every thing works fine in your library @jessesquires  . i added one more thing in my app which.

When i tap on specific message then youtube player is appreared and when i start playing the video then inputtoolbar hides. why ?

![img_0704](https://cloud.githubusercontent.com/assets/5149947/23906957/65eccffa-08f1-11e7-9a06-901542823c89.jpg)

Now is there any way to show the input toolbar again without screen changing.. ?

![img_0705](https://cloud.githubusercontent.com/assets/5149947/23906970/7043389a-08f1-11e7-8f6d-0735969679e9.jpg)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
