### ISSUE TITLE
Any advice on how to handle a widget with a UITextView inside it?

### ISSUE THREAD

**Issue by betzerra** [jessesquires/JSQMessagesViewController#2042]
## General information

- `JSQMessagesViewController` version:
- iOS version: 10.2.1
- Devices/Simulators: device
- Reproducible in the demo project? (Yes/No): No
- Any related issues: -

## What happened?
I'm doing a heavy customization on JSQMessagesViewController, including custom cells that have UITextView inside it. Everything looked ok on the simulator and then I tried it on a device. See this [bug video](https://www.dropbox.com/s/fcvej3cby2cyxz4/widget_free_form_bug_001.mov?dl=0).

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
