### ISSUE TITLE
YTPlayerView.h File Not Found

### ISSUE THREAD

**Issue by deborahelizabethpadilla** [jessesquires/JSQMessagesViewController#2046]
I installed `pod 'JSQMessagesViewController'` and am receiving this error twice, in different frameworks. The first error lies in the JSQSystemsSoundPlayer and the other in GTSessionFetcher. In JSQSystemsSoundPlayer, I'm also getting the error`Parse Issue - Could Not Build Module UIKit`. I'm not sure if this is related or not. 

I've tried referencing [this first question](http://stackoverflow.com/questions/37805293/ytplayerview-h-file-not-found-when-using-youtube-player-ios-helper-in-swift) and [this second question](http://stackoverflow.com/questions/20163812/could-not-build-module-uikit), but neither have resolved. 

CocoaPods is fully updated, as well as my pods, I tried reintegrating/etc and deleting manually from my folder in finder to reinstall. Nothing is working. Any ideas? Thanks in advanced!

**Comment by jessesquires** [comment]
Hey @deborahelizabethpadilla ! 😄 

This doesn't look related to JSQMessages. No `YTPlayerView.h` file exists in this project.

Can you provide any more information? It may be best to ask on StackOverflow instead.

**Comment by deborahelizabethpadilla** [comment]
Hey @jessesquires ! Thanks for responding :-)

Certain files from other pods must have slipped into this framework somehow. I purposely uninstalled every pod in my project, to reinstall, so I'd have a fresh approach going forward. I'll ask on StackOverFlow since this seems to be separate from the framework. Would uninstalling `pod 'JSQMessagesViewController'` to then reinstall, corrupt any header files?
