### ISSUE TITLE
Delete Message from Firebase

### ISSUE THREAD

**Issue by chand97** [jessesquires/JSQMessagesViewController#2048]
Well I am trying to delete messages from Firebase and I have done the UIMenuItem part of adding the delete item in the menu but I am facing difficulties in deleting the message from Firebase as JSQMessage doesn't have any messageID property.This my code for sending messages to Firebase:

```
    let newMessage = messagesRef.childByAutoId()
            let currentTime = Date()
            let currentTimePassed = currentTime.timeIntervalSince1970
            let timeInt = Int(currentTimePassed)
            let messageData = ["text" : text, "senderID" : senderId, "senderDisplayName" : senderDisplayName, "mediaType" : "Text", "reciverID" : userUID, "time" : timeInt, "messageID" : newMessage.key] as [String : Any]
            newMessage.setValue(messageData)
```

**Comment by apwelsh** [comment]
My suggestion is to maintain your firebase data in a collection. Use that collection to create the JSQMessagehs.  When you delete a message, you can determine the index.  That index will relate back to the same index position of you firebase data collection, which will allow you the get your necessary ID to send to Firebase.

**Comment by chand97** [comment]
Well that is actually how I fixed my problem by storing the messageIDs in an array

**Comment by chand97** [comment]
I am able to remove text and location messages but not photo, video and audio messages.Here is my code for deleting messages:

```
 let message = messages[indexPath.item]
        let messageMedia = message.media
        
        if action == #selector(ChatViewController.deleteMessage) {
            
            if message.isMediaMessage == false {
                
                messagesRef.child(messagesID[indexPath.item]).removeValue(completionBlock: { (error, ref) in
                    
                    if error != nil{
                        
                        print(error!.localizedDescription)
                        
                    }else {
                        
                        self.messages.remove(at: indexPath.item)
                        self.messagesID.remove(at: indexPath.item)
                        self.collectionView.deleteItems(at: [indexPath])
                        collectionView.reloadData()
                    }
                })

                
            }else if messageMedia is JSQLocationMediaItem {
                
                messagesRef.child(messagesID[indexPath.item]).removeValue(completionBlock: { (error, ref) in
                    
                    if error != nil{
                        
                        print(error!.localizedDescription)
                        
                    }else {
                        
                        self.messages.remove(at: indexPath.item)
                        self.messagesID.remove(at: indexPath.item)
                        self.collectionView.deleteItems(at: [indexPath])
                        collectionView.reloadData()
                    }
                })
                
            }

        }else {
            
            let imageRef = FIRStorage.storage().reference().child((FIRAuth.auth()?.currentUser?.uid)!).child(messagesID[indexPath.item])
            imageRef.delete(completion: { (error) in
                
                if error != nil {
                    
                    print("no succcess")
                    print(error!.localizedDescription)
                    
                }else {
                    
                    self.messagesRef.child(self.messagesID[indexPath.item]).removeValue(completionBlock: { (error, ref) in
                        
                        if error != nil{
                            
                            print(error!.localizedDescription)
                            
                        }else {
                            
                            self.messages.remove(at: 0)
                            self.messagesID.remove(at: 0)
                            self.fileURLs.remove(at: 0)
                            print(self.messagesID,self.messages,self.fileURLs)
                            self.collectionView.deleteItems(at: [indexPath])
                            collectionView.reloadData()
                        }
                    })
                }
                
            })
        }

```

**Comment by MacMeDan** [comment]
As an alternative you don't actually have to use the defined `JSQMessageObject`  you can define your own and just conform to the `JSQMessageData` protocol. Then you can add any exstra data you would like. I did it like this in my project.

    import JSQMessages

    class Message: NSObject, JSQMessageData {
      var text_: String?
      var senderId_: String?
      var date_: Date
      var senderDisplayName_: String?
      var isOutBound_: Bool
      var fistName: String?
      var lastName: String?
      var prefferedName: String?
      var employeeID: String?
    
      init(text: String?, senderId: String?, senderDisplayName: String?, isOutBound: Bool, firstName: String?, lastName: String?, prefferedName: String?, date: Date, employeeID: String?) {
        self.text_ = text
        self.senderId_ = senderId
        self.isOutBound_ = isOutBound
        self.date_ = date
        self.senderDisplayName_ = senderDisplayName
        self.fistName = firstName
        self.lastName = lastName
        self.employeeID = employeeID
        self.prefferedName = prefferedName
      }
    
      func text() -> String? {
          return text_
      }
    
      func isOutbound() -> Bool {
          return isOutBound_
      }
    
      func senderId() -> String? {
          return senderId_
      }
    
      func date() -> Date {
          return date_
      }
    
      func senderDisplayName() -> String? {
          return senderDisplayName_
      }
    
      func isMediaMessage() -> Bool {
          return false
      }
    
      func messageHash() -> UInt {
          return UInt(self.hash)
      }
    }

That way you don't make an indexing error and delete the wrong message. You can add you id and any other data you would like directly to your object and pass that around. 


Let me know if this helps and if there is anything else we can do to help 🤘

**Comment by chand97** [comment]
First of all what are the isOutBound and messageHash properties used for (are they related to indexing) and secondly am I deleting my data correctly from FIRStorage?

**Comment by MacMeDan** [comment]
isOutBound is to determine if it is an outbound message or inbound because you use different cells, colors and layout for each. The `messageHash` I think is used for the `springinessEnabled` and probably to determine how the bubble should layout around the message. But I could be wrong on that.

**Comment by chand97** [comment]
I get an error when I create a new class and import JSQMessages it says 'no such module JSQMessages'. What can I do to fix the problem?

**Comment by MacMeDan** [comment]
Clean your Derived data and rebuild. `Command Shift K` is the short cut. If that does not solve it I would suggest commenting out all pod in your `pod file` doing a `pod install` then add them back do a clean `Command Shift K` and build again.

**Comment by apwelsh** [comment]
What does your import statement look like for JSQMessage, and is your podfile configured to use frameworks or not?

If you have use frameworks turned on (I highly reccomend you do), the import statement I use is to import the framework as follows:

@import JSQMessagesViewController;

If you would rather only import specific headers, for frameworks based projects, import it as:

#import <JSQMessagesViewController/JSQMessage.h>

I dont know of a JSQMessages.h, i assume this is a shorthand for either one of the two i provided imports for.

**Comment by chand97** [comment]
I still can't import JSQMessage but I have created the following class:

```
import JSQMessagesViewController

class Message: NSObject,JSQMessageData {
    
    var text_: String?
    var senderId_: String?
    var date_: Date?
    var senderDisplayName_: String?
    var messageID: String!
    var storageID: String?

    init(senderId: String!, displayName: String!, text: String?) {
        
        self.senderId_ = senderId
        self.senderDisplayName_ = displayName
        self.text_ = text
    }
    
    init(text: String?, senderId: String?, senderDisplayName: String?, date: Date, messageID: String?, storageID: String?) {
        self.text_ = text
        self.senderId_ = senderId
        self.date_ = date
        self.senderDisplayName_ = senderDisplayName
        self.messageID = messageID
        self.storageID = storageID
    }
    
    func text() -> String? {
        return text_
    }
    
    func senderId() -> String? {
        return senderId_
    }
    
    func date() -> Date {
        return date_!
    }
    
    func senderDisplayName() -> String? {
        return senderDisplayName_
    }
    
    func isMediaMessage() -> Bool {
        return false
    }
    
    func messageHash() -> UInt {
        return UInt(self.hash)
    }
}
```

When I create a new message  and append it to a JSQMessage array the following error shows up:

Cannot convert value of type 'Message' to expected argument type 'JSQMessage'

```
let message = Message(senderId: senderID, displayName: senderDisplayName, text: text)
self.messages.append(message)
```

The append line is highlighted in red. What should I do to fix this problem?

**Comment by MacMeDan** [comment]
You need to change your messages type from `var messages = [JSQMessage]()` to `var messages = [Messages]()` So that you can utilize the new properties that you want to use.
