### ISSUE TITLE
No setter method 'setSenderid:'

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2049]
No setter method 'setSenderid:' for assignment to property.
No setter method 'setSenderDisplayName:' for assignment to property.

**Comment by MacMeDan** [comment]
From the demo they are defined as constants:

  
    static NSString * const kJSQDemoAvatarIdSquires = @"053496-4509-289";
    static NSString * const kJSQDemoAvatarDisplayNameSquires = @"Jesse Squires";
  
    - (NSString *)senderId {
        return kJSQDemoAvatarIdSquires;
    }

    - (NSString *)senderDisplayName {
        return kJSQDemoAvatarDisplayNameSquires;
    }

In my personal projects we have an `ID` attached to the `userObject` and that is what we used and then their name for the `senderDisplayName`
