### ISSUE TITLE
NSInternalInconsistencyException', reason: 'ERROR: required method not implemented: -[JSQMessagesViewController senderId]'

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2050]
'NSInternalInconsistencyException', reason: 'ERROR: required method not implemented: -[JSQMessagesViewController senderId]'

in Objective-C.
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by alessioarsuffi** [comment]
you need to implement senderId method from your JSQMessagesViewController subclass :)

**Comment by MacMeDan** [comment]
answered in #2049
