### ISSUE TITLE
Changing JSQMessagesInputToolbar's frame with UIKeyboard notification.

### ISSUE THREAD

**Issue by myksb1223** [jessesquires/JSQMessagesViewController#2051]
Hello~ I've been studying objective-c using JSQMessages project.

While I studied, I have a question about JSQMessageInputToolbar's frame when UIKeyboard is shown(hidden).
Because I learned that UIKeyboardShow(Hide) notification is needed to change frame of view, I tried to find code with UIKeyboardShow notification. But I can't see any code about it.
I just found code about changing CollectionView frame when UIKeyboard is shown. 
`- (void)jsq_didReceiveKeyboardWillChangeFrameNotification:(NSNotification *)notification`

How to change JSQMessagesInputToolbar's frame when UIKeyboardShow(Hide) in JSQMessages project?

Thank you for reading!

**Comment by dangnguyenhuu** [comment]
@myksb1223 you can find it in JSQMessagesKeyboardController.m

**Comment by jessesquires** [comment]
thanks @dangnguyenhuu !
