### ISSUE TITLE
How to allow enter key to press send button?

### ISSUE THREAD

**Issue by Shaare** [jessesquires/JSQMessagesViewController#2052]
- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.2
- Devices/Simulators: iPhoneSE
- Reproducible in the demo project? (Yes/No): Yes.
- Any related issues:

**Comment by Lucashuang0802** [comment]
@Shaare, I guess that will help you solve the problem: https://stackoverflow.com/questions/703754/how-to-dismiss-keyboard-for-uitextview-with-return-key

**Comment by Lucashuang0802** [comment]
If so, you will lose the ability to go to a new line. So, that's why the default behavior is to go to a new line.
