### ISSUE TITLE
Select a bubble programmatically

### ISSUE THREAD

**Issue by amirch123** [jessesquires/JSQMessagesViewController#2054]
Hello
I want to programmatically select a bubble and that bubble is highlighted.
For example:bubble number 3 is highlighted
Do you have any suggestions?
Thankful

**Comment by apwelsh** [comment]
I believe you have a few options, you can use reflections to change the tint of the selected cell on select and unselect.  Use a custom cell that provides direct support for the feauture, or see jf you can modify the cell selection state of the table to enable highlighting of the cell.  Personally, I have not done either of the three, but I would look at the source to see what is possible.
