### ISSUE TITLE
How to put image URL in image view

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2056]
How to put image url instead of image. in custom cell image view

**Comment by MacMeDan** [comment]
We are discussing it right now on stackoverflow [here](http://stackoverflow.com/questions/43145413/assigning-avatars-from-url-string-in-jsqmessagescontroller/43151822?noredirect=1#comment73410776_43151822) let me know if you have more questions an I will try to see what I can do to help.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
