### ISSUE TITLE
carriage returns in messages

### ISSUE THREAD

**Issue by hesomWela** [jessesquires/JSQMessagesViewController#2059]
- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.3
- Devices/Simulators: Iphone 7
- Reproducible in the demo project? (Yes/No): No
- Any related issues:

## What happened?

How do I add carriage returns to the messages? I have tried \r\n, but it just displays those characters in the message. I am looking to do something like this:
<img width="235" alt="screen shot 2017-03-28 at 10 18 52 am" src="https://cloud.githubusercontent.com/assets/21125432/24410026/f930a7ba-139f-11e7-9b20-b6f3e624da25.png">

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
