### ISSUE TITLE
Navigation top bar right item

### ISSUE THREAD

**Issue by xero88** [jessesquires/JSQMessagesViewController#2060]
Hi,

is there a way to custom the top bar ? I want simply to add an right item (a profile item).

How to do that ?

Thx you !

**Comment by apwelsh** [comment]
Turn in the Navigation controller, and add it there.

**Comment by manjuhere** [comment]
>       self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemStop target:self action:@selector(closePressed:)];
>       self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"ic_attach_file_white"] style:(UIBarButtonItemStylePlain) target:self action:@selector(attachFile)];

Do the above in viewDidLoad / viewWillAppear / viewDidAppear method of your JSQMessagesViewController subclass. It's there in the demo project as well... take a look!

**Comment by Lucashuang0802** [comment]
thanks, @apwelsh, and @manjuhere. 👍 💯
