### ISSUE TITLE
jsq_didReceiveDeviceOrientationDidChangeNotification constantly clears the message bubble size cache

### ISSUE THREAD

**Issue by hughlang** [jessesquires/JSQMessagesViewController#2061]
## New issue checklist

- [X] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [X] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [X] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: Customized copy of code probably 12 months old
- iOS version: 10.2.1
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): Probably
- Any related issues:

## What happened?
I noticed that JSQMessagesBubblesSizeCalculator.m prepareForResettingLayout is constantly getting called because jsq_didReceiveDeviceOrientationDidChangeNotification is getting triggered by a supposed screen orientation change. And this results in clearing the sizes cache. 

My app does not allow screen rotation but this gets triggered frequently during app usage (scrolling chat view, etc). While I am using a heavily customized (hacked legacy code), I can see that this might still be an issue with the current code.  

```
2017-03-31 12:43:30.979703 Genie[3063:912451] Callstack: (
	0   Genie                               0x00000001000dcea4 -[JSQMessagesBubblesSizeCalculator prepareForResettingLayout:] + 104
	1   Genie                               0x00000001000eacfc -[JSQMessagesCollectionViewFlowLayout jsq_resetLayout] + 72
	2   Genie                               0x00000001000e95a0 -[JSQMessagesCollectionViewFlowLayout jsq_didReceiveDeviceOrientationDidChangeNotification:] + 68
```

References: 
* https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Layout/JSQMessagesBubblesSizeCalculator.m
* https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.m

Personally, I removed the call to jsq_resetLayout and it works. Optionally, you can remove the next line, but since invalidateFlowLayoutMessagesCache is never set to true, it is not an issue for me. However, I'm sure a real fix would take into account screen rotation.

**Comment by hughlang** [comment]
Also note that the sizes cache gets emptied every time the app enters the background and that is the standard behavior of NSCache. I was also having problems with my own NSCache usage and found that it is necessary to implement NSDiscardableProtocol on my cacheable objects. 
* http://stackoverflow.com/questions/13163480/nscache-and-background/13579963#13579963
* https://developer.apple.com/reference/foundation/nsdiscardablecontent

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
