### ISSUE TITLE
Chat message bubble extends past end of screen

### ISSUE THREAD

**Issue by Cykey** [jessesquires/JSQMessagesViewController#2062]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.2
- Devices/Simulators: iPhone 5s simulator
- Reproducible in the demo project? (Yes/No): Unsure
- Any related issues:

## What happened?

When I have a cell that has lots of text, the cell gets cropped weirdly at the end of the screen. I have *not* customized the cell in any way other than changing colors.

See attached picture: 
<img width="324" alt="screenshot 2017-04-02 10 38 17" src="https://cloud.githubusercontent.com/assets/545502/24588145/bc57f146-1790-11e7-847c-2cbe1ffafebb.png">

**Comment by jessesquires** [comment]
Thanks @Cykey !

This is a known issue, the work around is to invalidate the layout before the view appears.

See the answer at #985
