### ISSUE TITLE
change the image bubble size??

### ISSUE THREAD

**Issue by woowhoo** [jessesquires/JSQMessagesViewController#2065]
How can i change the image bubble size??

let customAttributes = self.collectionView.layoutAttributesForItem(at: indexPath) as! JSQMessagesCollectionViewLayoutAttributes

customAttributes.messageBubbleContainerViewWidth = UIScreen.main.bounds.width * 0.8
cell.apply(customAttributes)

The code above just move the bubble to the left..which means that the container size increase but the image size is still the same

I have tried to change "mediaView and messageBubbleImageView" but still can't do change the size of image view in bubble

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
