### ISSUE TITLE
highlight bubble

### ISSUE THREAD

**Issue by amirch123** [jessesquires/JSQMessagesViewController#2066]
hello
How Do I  highlight bubble programmatically.
For example, highlight bubble  number 3

thnaks

**Comment by salil0505** [comment]
A really quick and dirty solution that I use is just to change the cell.backgroundColor to something else than the default.

**Comment by Lucashuang0802** [comment]
Thanks, @salil0505 for your comment.

**Comment by Lucashuang0802** [comment]
@amirch123, Thanks! 😄

Please provide all the information in the issue template so we can help!
And don't forget to read our contribution guidelines. 😊
