### ISSUE TITLE
edit menu not positioned correctly for media

### ISSUE THREAD

**Issue by michaelkirk** [jessesquires/JSQMessagesViewController#2068]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ x I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: https://github.com/jessesquires/JSQMessagesViewController/commit/45fdac769d7354ad19e5990dadbfee285a2e45ee
- iOS version: 10.3
- Devices/Simulators: iPhone 7, Sim 6s, probably affects all others as well.
- Reproducible in the demo project? Yes
- Any related issues: https://github.com/jessesquires/JSQMessagesViewController/issues/1722

## What happened?

Edit menu is not positioned correctly for media cells.

<img width="487" alt="screen shot 2017-04-11 at 11 39 32 am" src="https://cloud.githubusercontent.com/assets/217057/24918114/363b78d4-1ead-11e7-8e7b-04439adf5424.png">

It should be centered over the cell as it is for text messages.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
