### ISSUE TITLE
Why UICollectionView instead of UITableView?

### ISSUE THREAD

**Issue by apwelsh** [jessesquires/JSQMessagesViewController#2070]
Everything I have read online (from Apple and through development best practices) says to avoid UICollectionView, if UITableView is sufficient because UICollectionView is much heavier, and is slower performing.

What was the motivation for the use of the collection view instead of the table view?

I don't need the horizontal layout capabilities of a collection view, so everywhere in my code I used a UITableView.  And i can say without a doubt, all my Table views are much more responsive than this tool's collection table.  

I dont know how much of this is due to the use of a collection view instead of a table view, and how much is due to this control's data handling techniques of the collection of cells.  

I am hoping to understand this better.  Nothing more.  If I could learn more, I would appreciate it.  Thanks.

**Comment by grantkemp** [comment]
why don't you port it? @apwelsh  sounds like a good idea.

**Comment by apwelsh** [comment]
Given that UICollectionView is newer that UITableView, I am seeking enlightenment.  I suspect the collection view was chosen to address a certain limitation of table view.

**Comment by grantkemp** [comment]
Looking at the UI - I don't see why a Custom Tableview is not possible. Where did you see Apple say its much more performant?

**Comment by chrisballinger** [comment]
Older versions used UITableView (v4 and lower), and I think the choice to switch to UICollectionView in [v5.0.0](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/5.0.0) was somewhat arbitrary to try the new API and not based on specific limitations of UITableView.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
