### ISSUE TITLE
Cells missing when its not visible

### ISSUE THREAD

**Issue by pedroviana** [jessesquires/JSQMessagesViewController#2073]
Hi @jessesquires, first of all thanks for the great job here, its awesome!

I am working days to solve this issue but got nothing, please take a look at my scenario:

My cells are disappearing when its get out of visible cells, my hash delegates are called but nothing is draw, but when I set automaticallyScrollsToMostRecentMessage to false and keep the first messages visible when all cells is loaded nothing disappears everything works fine, I checked my hashes and media hashes and everything its unique, do you have any idea of whats could be wrong?

When my media finish loading I invalidate the layout like this:
`let context = JSQMessagesCollectionViewFlowLayoutInvalidationContext()
        context.invalidateFlowLayoutDelegateMetrics = true
        context.invalidateFlowLayoutAttributes = true
        context.invalidateFlowLayoutMessagesCache = true
        self.collectionView.collectionViewLayout.invalidateLayout(with: context)
self.finishReceivingMessage(animated: true)`

- JSQMessagesViewController version: 7.3.4
- iOS version: 10 and 9
- Devices/Simulators: Device and Simulator 10 and 9
- Reproducible in the demo project? (Yes/No): No

![scrolling-first-cells-disappear](https://cloud.githubusercontent.com/assets/285674/25072417/26cee610-22a4-11e7-9e7c-6604b156b3af.png)
![no-scroll-cells-work-fine](https://cloud.githubusercontent.com/assets/285674/25072418/27216cb4-22a4-11e7-8c57-4a7420df768a.png)
<img width="523" alt="views-hierarchy" src="https://cloud.githubusercontent.com/assets/285674/25072422/32210160-22a4-11e7-85f5-558cbf7fd503.png">

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by sbhhbs** [comment]
@pedroviana Hi, i've encountered with issue myself and haven't found a solution. Did you find a solution?

**Comment by pedroviana** [comment]
Hi @sbhhbs, its been a while I solve this and couldn't found the fix but as I remember it was the hashes ids of the messages I changed for something else and fix the issue, sorry for not helping more.
