### ISSUE TITLE
Chat text slightly off center

### ISSUE THREAD

**Issue by tamoyal** [jessesquires/JSQMessagesViewController#2074]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.2.1
- Devices/Simulators: iPhone 6
- Reproducible in the demo project? (Yes/No): I can't tell
- Any related issues: 

## What happened?

Does anyone else think text in chat bubble is slightly vertically off-center for one line text? Just a little bit too high? The grey bubble is from the demo project and the orange from my project.

<img width="186" alt="screen shot 2017-04-16 at 1 09 25 pm" src="https://cloud.githubusercontent.com/assets/46859/25073160/0d13444e-22a6-11e7-84a7-6916861d4727.png">

![img_0220](https://cloud.githubusercontent.com/assets/46859/25073170/32af4ca2-22a6-11e7-9c10-370c0a363a08.PNG)

**Comment by apwelsh** [comment]
Now that you mention it. I wont be able to unsee it.  I'm surprised my OCD didnt catch it before (okay, more the OC less the D)

**Comment by almassapargali** [comment]
I have this issue too.

**Comment by Marquis103** [comment]
anybody have any luck with this?

**Comment by glennposadas** [comment]
Lmao. My designer noticed it too. For me it's fine. But wanna subscribe to this thread to receive replies from the devs for the fix.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
