### ISSUE TITLE
Add DisplayName in the textView

### ISSUE THREAD

**Issue by mrhaxic** [jessesquires/JSQMessagesViewController#2077]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version: 10
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?

For any one want to add username/displayername in the first line of `textView` use below attributedText

```
    CGFloat boldTextFontSize = 14.0f;
    NSRange range1 = [msg.text rangeOfString:self.senderDisplayName];
    NSMutableAttributedString *attributedText = [[NSMutableAttributedString alloc] initWithString:msg.text];
    [attributedText setAttributes:@{NSFontAttributeName:[UIFont systemFontOfSize:14.0f],NSForegroundColorAttributeName:[UIColor whiteColor]} range:NSMakeRange(0, msg.text.length)];
    [attributedText beginEditing];
    [attributedText setAttributes:@{NSFontAttributeName:[UIFont boldSystemFontOfSize:boldTextFontSize],NSForegroundColorAttributeName : [UIColor whiteColor]}
                            range:range1];
    [attributedText endEditing];
    cell.textView.attributedText = attributedText;


```

**Comment by Lucashuang0802** [comment]
thanks @mrhaxic for the PR. 👍 💯
