### ISSUE TITLE
Crashes when scroll to top after sending multiple messages

### ISSUE THREAD

**Issue by martynpekala** [jessesquires/JSQMessagesViewController#2078]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.2
- iOS version: each one
- Devices/Simulators: iPhone 5,6,7
- Reproducible in the demo project? (Yes/No): Yes
- Any related issues:

## What happened?
If your screen is moved by showing messages scrolling back to the top causes the crash. It always happens when I scroll to specific position.

**Comment by rostopira** [comment]
Same thing with version 7.3.4

**Comment by Lucashuang0802** [comment]
@martynpekala, thanks for submitting an issue. Can you provide all steps to replicate it in the demo project? That would help us address the issue accurately. 😃

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
