### ISSUE TITLE
JSQMessageViewController not showing message bubbles

### ISSUE THREAD

**Issue by itsvishal7** [jessesquires/JSQMessagesViewController#2080]
## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?

[JSQ.zip](https://github.com/jessesquires/JSQMessagesViewController/files/937830/JSQ.zip)
green messages are the ones that i have stored in the phone, but the message with gray bubble is the on that i am loading through api request, after loading i am creating JSQMessage and append it to the array of JSQMessage and calling finishRecievingMessages().
But the message is not visible on the screen until and unless i am manually dragging the screen.
This does not happen one when the no. of text messages are exceeds the number which can fit into the screen.
In the image i have called finishSendingMessage(), i have tried both methods, it is not working
![screen shot 2017-04-20 at 1 33 26 am](https://cloud.githubusercontent.com/assets/21201487/25199731/6e590836-2569-11e7-86d5-a5dacfea8e86.png)

**Comment by Lucashuang0802** [comment]
Thanks! 😄

Please provide all the information in the issue template so we can help!
And don't forget to read our contribution guidelines. 😊

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
