### ISSUE TITLE
Input toolbar stay at bottom affer reopen app from background !!! ??

### ISSUE THREAD

**Issue by thanhhai16** [jessesquires/JSQMessagesViewController#2081]
First, thank you for an amazing libraries to use.

i got this problem for almost a week :( 
my jsqmessagecontroller work fine, but the inputtoolbar
sometime it not show up, just stay at bottom, but it just sometime
however, the main problem is whenever i reopen app, after chat(keyboard appear) then when app is reopen, only the keyboard there, not the input toolbar, just like that

![screen shot 2017-04-20 at 6 31 24 pm](https://cloud.githubusercontent.com/assets/21291118/25228703/a48bf9b6-25f7-11e7-8194-a2fecb4a787d.png)

I really need help now :(

**Comment by thanhhai16** [comment]
![screen shot 2017-04-20 at 6 32 42 pm](https://cloud.githubusercontent.com/assets/21291118/25228738/c76774ce-25f7-11e7-90c9-c198923c7133.png)
it normal at first like this

**Comment by apwelsh** [comment]
I added IQKeyboardManager tfor solve this without havingto add any code.

**Comment by thanhhai16** [comment]
@apwelsh can you show me how to do it pls ? i'm going to blow out :(

**Comment by apwelsh** [comment]
Stop XCode, Add IQKeyboardManager to your podfile, run "pod install", open the project's .xcworkspace file, and then clean Cmd-Shift-K, and Run Cmd-R.

This solution requires no code changes.  Once the library is added to your project, it just works.  It's sole purpose is to shift you UIViewConctroller up to fully display the input field that current has the focus. And when the keyboard disappears, it pit the ViewController back where it belongs.

**Comment by thanhhai16** [comment]
@apwelsh tks you a lot, do i need this : 
`import IQKeyboardManagerSwift

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

      IQKeyboardManager.sharedManager().enable = true

      return true
    }
}`

**Comment by thanhhai16** [comment]
@apwelsh after added IQKeyboardManager, it work, but now look like this 
![18090597_1385916808131248_1884569931_o](https://cloud.githubusercontent.com/assets/21291118/25249927/eca61eac-263d-11e7-9961-d23de4ec74e3.jpg)

Can you help me ?

**Comment by thanhhai16** [comment]
@apwelsh and aslo my navigation gone ??

**Comment by apwelsh** [comment]
I have my status bar background set to an opaque color.

 About the implementation. I did not realize you were using Swifty which is a different library. I do not remember adding anything to my app delegate to make it work but I will look at it later when I get home and confirm.

**Comment by apwelsh** [comment]
Yes this is normal, the whole view is raised up out-of-the-way we can get to your input box. If you swipe the keyboard back down out of the way your navigation reappears. 

If you want to have final control over how to control scrolls up and down you might want to consider one of the other keyboard managers which you can find on cocoa pods website. What I like about this one it is codeless. I did review others that were not, but I decided that I like this one the best

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
