### ISSUE TITLE
didPressSend() gives empty snapshot warning

### ISSUE THREAD

**Issue by kiwo12345** [jessesquires/JSQMessagesViewController#2082]
When I call `didPressSend()` I get the warning: **Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.**

In my `didPressSend()` function I call these

```
self.addMessage("1", text: text)
JSQSystemSoundPlayer.jsq_playMessageSentSound()
finishSendingMessage(animated: true)
if notifEnabled == false {
self.performSegue(withIdentifier: "enableNotificationSegue", sender: self)
}
```
I think the error comes from this line:
`self.performSegue(withIdentifier: "enableNotificationSegue", sender: self)`

This will open a new modal VC where the user can accept notifications. So is there any way to check when the animation for message bubbles has finished? So I can run the `performSegue()` once the animation has finished

**Comment by Lucashuang0802** [comment]
@kiwo12345, are you able to replicate this warning in the demo project? That would be helpful to address the problem. 😃

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
