### ISSUE TITLE
Attributed string in message

### ISSUE THREAD

**Issue by SebastianKumor** [jessesquires/JSQMessagesViewController#2083]
So I was going trough all the issues and there was supposed to be a  new release 8.0 with an option to have an attributed text in the message bubble. Any news about that ? Is there any other way how to achieve it ? I need to underline specific words in every message bubble. Thanks

## General information

- `JSQMessagesViewController` version: latest pod
- iOS version: 10
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by apwelsh** [comment]
Use the custom cell option, or use the mediaitem cell option and create your own text message this way.  I create my own media items for stuff like this now, and it works great.  The most challenging thing will be calculating the cell size, but this is easy enough too.

**Comment by mrhaxic** [comment]
is it useful? #2077

**Comment by SebastianKumor** [comment]
@mrhaxic  thx for response, Im gonna have a look at it

**Comment by Lucashuang0802** [comment]
thanks @mrhaxic. Can you please confirm @SebastianKumor, that would help us manage the Issue column. 😃

**Comment by Lucashuang0802** [comment]
@SebastianKumor please feel free to continue if that did not work out. 😄

**Comment by SebastianKumor** [comment]
@Lucashuang0802  sorry for late response, I ended up creating my own custom cells and that worked well for me.
