### ISSUE TITLE
Use of undeclared type 'JSQMessagesViewController'. Xcode 8.3.1 - Swift 3.0

### ISSUE THREAD

**Issue by gursimran14041** [jessesquires/JSQMessagesViewController#2084]
Hi. I am using JSQMessagesViewController in one of my iOS applications. I recently converted my project from Swift 2.3 to Swift 3.0 as I updated to Xcode 8.3. 
JSQMessagesViewController worked fine with Swift 2.3 but after the conversion my project won't compile and is stuck showing the error:
`/Users/.../MessagesViewController.swift:53:31: Use of undeclared type 'JSQMessagesViewController'`

**Installation Environment**:
- Xcode v8.3.1
- Swift v3.0
- Installed using CocoaPods v1.2
- JSQMessagesViewController v7.3.4

**Code snippet where error is occurring**
![image](https://cloud.githubusercontent.com/assets/13811237/25315305/eace77a2-2870-11e7-9e5e-30d805c24e3f.png)

**I have already tried the following methods but they didn't work**
- Clean and rebuild project.
- Deleting the ~/Library/Developer/Xcode/DerivedData folder and rebuild.
- Adding `import JSQMessagesViewController` in the swift file that is supposed to use it, as mentioned in #916. But this causes the error `No such module 'JSQMessagesViewController'`
![image](https://cloud.githubusercontent.com/assets/13811237/25315395/f2b79e98-2871-11e7-9aed-768debdf2909.png)
- The above is mentioned in #1683. I also tried all the possible solutions mentioned in issue #1683 but no luck.
- I have also referred to issues #988 and #837 but still no luck.
- I am currently importing JSQMessagesViewController in bridging header as `@import JSQMessagesViewController;`. I have also tried doing `#import "JSQMessagesViewController.h"` but it didn't work either.

> **EDIT_1**

**Other helpful information about the project**
- `use_frameworks!` flag is turned ON in Podfile.

I would appreciate if you could look into this as soon as possible.

**Comment by apwelsh** [comment]
Donyou have use frameworks defined in your podfile?

**Comment by gursimran14041** [comment]
`use frameworks!` flag is turned ON in podfile.
Anyways the flag is required for frameworks written in Swift. JSQMessagesViewController is written in Objective-C

**Comment by Lucashuang0802** [comment]
@gursimran14041, there is kind of a workaround to make the project compile. For all your Swift dependencies, you can go with Carthage. For the rest, you can stay with CocoaPods.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
