### ISSUE TITLE
cannot set cellBottomLabel text alignment for media messages

### ISSUE THREAD

**Issue by coolcool1994** [jessesquires/JSQMessagesViewController#2086]
I edited .xib file for cellBottomLabel to get Read receipt work for the regular text bubbles. But there is no .xib file for me to edit for the media messages. So I am able to display read receipt even for media messages, but the text alignment is off. I want it to be set towards the right 42 points from the edge of the screen.
- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    

    JSQMessage *msg = [self.messages objectAtIndex:indexPath.item];
    
    
    if (!msg.isMediaMessage) {

    } else {
        if ([msg.senderId isEqualToString:self.senderId]) {
            CGFloat screenWidth = CGRectGetWidth([UIScreen mainScreen].bounds);
            //trying to make read message for media messages to work
            cell.messageBubbleTopLabel.textInsets = UIEdgeInsetsMake(0, screenWidth - 42, 0, 0);
            cell.cellBottomLabel.textAlignment = NSTextAlignmentRight;
        }
    }
    return cell;
}

![simulator screen shot may 1 2017 7 20 32 pm](https://cloud.githubusercontent.com/assets/23645054/25598562/b77b3726-2ea3-11e7-8201-bfd5bb20de3d.png)

**Comment by coolcool1994** [comment]
I found out why. In the JSQMessagesCollectionViewCellOutgoing.xib constraint for the bottom label is set incorrectly for the mediaItem like photos. The trailing constraint was set to the TextView! If you set this to Bubble Image view, it still doesn't work. You need to set it to the Avatar image to get it to work.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
