### ISSUE TITLE
iOS: How to customise JSQMessagesCollectionview?

### ISSUE THREAD

**Issue by umair07** [jessesquires/JSQMessagesViewController#2087]
New issue checklist

 

- [x] I have read the README, documentation, and FAQ.
- [x]  Contributing guidelines confirmation: ____
- [x]  I have searched existing issues and this is not a duplicate

General information

JSQMessagesViewController version: 7.3.4
iOS version: 10.3
Devices/Simulators: simulator
Reproducible in the demo project? (Yes/No): Yes

I want to customise the JSQMessagesCollectionview. I want to add some padding in bottom view so that scroll view starts from some bottom margin.

I need this because my view is overlapping. Here the screenshot:
![simulator screen shot 2 may 2017 10 28 03](https://cloud.githubusercontent.com/assets/11897265/25605716/5406c60a-2f26-11e7-8a3a-3825ecbb4cfa.png)

The second thing I want to customise the time stamp. I want to add a functionality just like Facebook. Here is the scenario:

1. Show date and time. For messages sent in under a minute, use "Just Now" instead of the actual timestamp.
2. For messages sent on the same day, use Today, time. For example: Today, 4:47 PM.
3. For messages sent yesterday, use Yesterday, Time. For example: Yesterday, 5:01 AM.
4. For everything else, use standard format: Date, Time. For example: April 12, 2017, 4:01 PM.

I want to customise the timestamp label and I want to add the "just now" text there. is it possible?

Can I change the time place in view? I want to show the time stamp below the bubble?

I am using the latest version of the library.

Thanks in advance. Please help if you can?

**Comment by mding5692** [comment]
Also interested in how anyone handled this, right now, its not working so well as I'm dynamically changing the 

override func collectionView(_ collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellTopLabelAt indexPath: IndexPath!) -> CGFloat {
 
Maybe do the same for heightForCellBottomLabelAt

and I've been working on the date but its really just figuring out using something like below:

    // Used for figuring out if person is recently active or not
    var figureLastActiveTime: String {
        var lastActiveTime = ""
        // Have to times by negative 1 to turn the number positive
        let differenceBetweenNowAndLastActive = self.timeIntervalSinceNow * -1
        
        // Figures out time difference
        if differenceBetweenNowAndLastActive <= 60.0 { // States it as right now if within a minute
            lastActiveTime = "Active now"
        } else if differenceBetweenNowAndLastActive < 3600.0 { // States minutes if within an hour
            
            let minDifference = (Int(differenceBetweenNowAndLastActive) / 60) % 60
            lastActiveTime = "Active \(minDifference)m ago"
            
        } else if differenceBetweenNowAndLastActive < 86400.0 { // States hours if within a day
            
            let hrsDifference = Int(differenceBetweenNowAndLastActive) / 3600
            
            if hrsDifference == 1 {
                lastActiveTime = "Active \(hrsDifference)hr ago"
            } else {
                lastActiveTime = "Active \(hrsDifference)hrs ago"
            }
            
        } else {    // States amount in days if more than a day
            
            let daysDifference = Int(differenceBetweenNowAndLastActive) / 86400
            if daysDifference == 1 {
                lastActiveTime = "Active \(daysDifference) day ago"
            } else {
                lastActiveTime = "Active \(daysDifference) days ago"
            }
            
        }
        return lastActiveTime
    }

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by Hamza10Imran** [comment]
I have followed raywenderlich tutorials in which they used JSQMessageViewController , i have followed them correctly but when i override the method to send button it shows me error to overide the send button method in subclass , hence i had overrides it but its giving me this error , Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error! required method not implemented in subclass. Need to implement -[JSQMessagesViewController didPressSendButton:withMessageText:senderId:senderDisplayName:date:]'  . How to resolve this?

**Comment by chrisballinger** [comment]
Sorry @Hamza10Imran this library is deprecated, see the above post by Jesse. I suggest you direct future development efforts here: https://github.com/MessageKit/MessageKit

Thanks!
