### ISSUE TITLE
[Question] Sharing Documents files - PDF, docx

### ISSUE THREAD

**Issue by n1tesh** [jessesquires/JSQMessagesViewController#2089]
## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 8.0
- iOS version: 10
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?

Does this support PDF, DOCX, etc. ?
If then please help me out in implementing it.

**Comment by apwelsh** [comment]
My recommendation is to render the document into an image (like the PDF icon for psf file) and add an event handler to capture the touch event.    When touched, open a menu asking the user what to open it in....        
  
  
  
  
  

  
  
>

**Comment by n1tesh** [comment]
@apwelsh But JSQMessage does not directly support document files ?

Also I have one more question. How to show a tick(seen satus) image below cell ?

**Comment by apwelsh** [comment]
The library is a tool, not a complete solution. I struggled a little bit too, until I looked at the source.    To add a tick mark, you would create either a media item cell that does this for you, or you can create a new cell by extending one of the supplied cells, and modifying it to do what you want.    
  
  
  
  
  

  
  
>

**Comment by Lucashuang0802** [comment]
thanks, @apwelsh.
