### ISSUE TITLE
inputToolbar Edit height error

### ISSUE THREAD

**Issue by cowboyfzl** [jessesquires/JSQMessagesViewController#2090]
#
## General information

- `JSQMessagesViewController` version: 7.3.X
- iOS version: 10.3
- Devices/Simulators: All
- Reproducible in the demo project? (Yes/No):  No
- Any related issues: 
![simulator screen shot 2017 5 5 11 46 50](https://cloud.githubusercontent.com/assets/11885608/25733113/939bfa42-3188-11e7-8e87-28df0c143b34.png)

## What happened?
When I set the inputToolbar to a fixed heigh，And enter text over the toolbar height and let it roll，And then gradually delete the text，inputToolbar height will immediately reduce，Instead of reducing the rolling distance first, then reduce the height!

After I checked the source code
In `JSQMessagesViewController.m` The 981 line
 ` - (BOOL)jsq_inputToolbarHasReachedMaximumHeight`
 in `self.topLayoutGuide.length`Always = 20.0
 `self.topContentAdditionalInset` Always = 0
 
So the Boolean value returned is always false

Maybe the problem is here,I hope great  guy  can fix this problem, thank you

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
