### ISSUE TITLE
Accessory button gone?

### ISSUE THREAD

**Issue by mateo-kozomara** [jessesquires/JSQMessagesViewController#2091]
What happened to the cell.accessoryButton? I downloaded the zip of the repo and the button is still there, but when i tried installing from cocoapods accessoryButton is no longer present (installed version 7.3.4 via cocoapods).

In which version was this removed?

**Comment by Lucashuang0802** [comment]
@mateo-kozomara is it replicable in the demo project?

**Comment by Lucashuang0802** [comment]
@mateo-kozomara I have checked the demo project, it does not seem to have this problem on the `develop` branch. Can you confirm?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
