### ISSUE TITLE
messageBubbleContainerView layout issue in demo app and same in my App in latest pod.

### ISSUE THREAD

**Issue by abhisheksingh1** [jessesquires/JSQMessagesViewController#2092]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` 7.3.4:
- iOS version: 10.3
- Devices/Simulators: iPhone 5s(10.3)
-  Reproducible in the demo project? (Yes/No): Yes
-  Any related issues: Same happening in my App as well before it was working fine.

## What happened?

- When I am moving to the messaging screen by selecting "Push programatically(1.png)" in demo and in my app corner of some messages is not in round and some are in round shape(2.png).
- When I am sending new message then it is showing with different layout(default in old)(3.png).
- When app is running and moving to background and comming to foreground then all messageBubbleContainerView layout is getting changed(default)[4.png].

**Also I figure out few important  points -** 

- This issue happens only with IOS 10 and above devices during pushing to DemoMessagesViewController with animation is true, If animation is false then it works fine.
- presentViewController is working fine for all the devices
- I also run the demo App in IOS 8.3 simulator and it works fine for both Pushing and presenting to DemoMessagesViewController

_Are there any solution or suggestion for this case?_

Thank U so much for providing this awesome library. 

![1](https://cloud.githubusercontent.com/assets/9801636/25748930/7f02f7d8-31ca-11e7-8027-7392d2b432c0.png)
![2](https://cloud.githubusercontent.com/assets/9801636/25749196/4f9986c8-31cb-11e7-916b-d6a93801e196.png)
![3](https://cloud.githubusercontent.com/assets/9801636/25748929/7f01dcfe-31ca-11e7-9b7b-80c36a50eb5d.png)
![4](https://cloud.githubusercontent.com/assets/9801636/25748932/7f150888-31ca-11e7-9315-d47d3a428150.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
