### ISSUE TITLE
Toolbar Disappear when using image picker for photo send.

### ISSUE THREAD

**Issue by nileshjaiswal16** [jessesquires/JSQMessagesViewController#2093]
My bottom toolbar disappear when using image picker for selecting photo from gallery.Help please regarding this.
![img_2971](https://cloud.githubusercontent.com/assets/28454197/25758342/d69c0fa4-31eb-11e7-9df6-7ccdb39ad219.PNG)
![Uploading IMG_2972.PNG…]()

**Comment by Lucashuang0802** [comment]
@nileshjaiswal16 When presenting, the system will present and replace the current view controller that makes the presenting view controller the top of the view controller stack. It is an expected behavior.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
