### ISSUE TITLE
sender side OutgoingBubbleImageMaskToMediaView alignment issue

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2094]
![screen shot 2017-05-07 at 10 46 43 am](https://cloud.githubusercontent.com/assets/13646977/25778136/a89449dc-3312-11e7-8475-4b53924824e5.png)

**Comment by TDem** [comment]
Try to set 'appliesMediaViewMaskAsOutgoing' property, when you create photo item.

Something like this:

`JSQPhotoMediaItem *photoItem = [[JSQPhotoMediaItem alloc] initWithImage:[UIImage imageNamed:@"goldengate"]];`
    
`photoItem.appliesMediaViewMaskAsOutgoing = NO;`

 `JSQMessage *photoMessage = [JSQMessage messageWithSenderId:kJSQDemoAvatarIdSquires
                                                   displayName:kJSQDemoAvatarDisplayNameSquires
                                                         media:photoItem];`

   ` [self.messages addObject:photoMessage];`

**Comment by Lucashuang0802** [comment]
thanks @TDem.

@shravanteegala, did the solution work for you?

**Comment by Lucashuang0802** [comment]
`appliesMediaViewMaskAsOutgoing` should get you solve the problem. Please feel free to continue if it does not work out. thanks again @TDem. 👍 💯
