### ISSUE TITLE
Two-Word Messages Shows Only One Word

### ISSUE THREAD

**Issue by alhadhrami** [jessesquires/JSQMessagesViewController#2095]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.3.1
- Devices/Simulators: iPhone 6s
- Reproducible in the demo project? (Yes/No): I don't know
- Any related issues: None I could find

## What happened?
I am using Apple's Speech Recognition API to recognize user input using microphone and displaying the text as message bubbles.

When recognizing a two-word phrase, the text is recognized correctly, and when a new bubble is inserted with the given phrase, only the first word appears.

The language used is Arabic.

NOTE: one word and many words appear normal. Only two words don't appear correctly.

## Example:
 - User says: "السلام عليكم"
 - Recognized text (copied while debugging): "\u{e2}السلام عليكم"
 - Text appeared in new bubble: "السلام  "

### Debugging the recognized text

<img width="823" alt="debug" src="https://cloud.githubusercontent.com/assets/11816239/25781942/a56e5452-3351-11e7-8d2d-2d4c81116aed.png">

### Result of inserting bubble with that text

<img width="910" alt="message" src="https://cloud.githubusercontent.com/assets/11816239/25781941/a56d9030-3351-11e7-992a-0bad26377169.png">

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
