### ISSUE TITLE
How to remove separator between collectionView and input toolbar?

### ISSUE THREAD

**Issue by rodrigoreis22** [jessesquires/JSQMessagesViewController#2097]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.3
- Devices/Simulators: 10.3
- Reproducible in the demo project? (Yes/No): Yes
- Any related issues: No

## What happened?
I'm using JSQMessagesViewController (7.3.4) and I couldn't find a way to remove the line that divides the collectionView and the input toolbar.
<img width="377" alt="screen shot 2017-05-08 at 4 28 03 pm" src="https://cloud.githubusercontent.com/assets/3405709/25822750/06639d30-3410-11e7-8af1-3c69810a74b9.png">

Where's this line added? I've tried setting the border of input toolbar to 0, but it didn't work.

**Comment by mding5692** [comment]
its in JSQMessagesViewController.xib:

![screen shot 2017-06-15 at 2 11 34 pm](https://user-images.githubusercontent.com/9067177/27195382-92e90984-51d4-11e7-953a-485e48e6d802.png)

**Comment by Lucashuang0802** [comment]
thanks, @mding5692. 💯
