### ISSUE TITLE
hidden top of collection view

### ISSUE THREAD

**Issue by TDem** [jessesquires/JSQMessagesViewController#2098]
Hi, can you please help me out with the following issues. When I tried to implement your code in my application, **first messages where hidden under navigation bar**(when you open from push via storyboard and push programmatically). Rotating phone or opening soft keyboard solves this issue.

**Comment by apwelsh** [comment]
When do you render the navigation menu?    I am curious if this has to do with a view's didLoad willDisplay, and didDisplay functions.    
  
  
  
  
  

  
  
>

**Comment by TDem** [comment]
I don't render navigation menu myself. I've just opened demo example and found that, when I open view using push presentation, "Load earlier messages" and date are hidden under navigation menu. 
Here images for better understanding :
![simulator screen shot may 10 2017 22 04 17](https://cloud.githubusercontent.com/assets/7361684/25909370/cb6f5492-35ce-11e7-9479-0a7bb2da5857.png)

![simulator screen shot may 10 2017 22 04 17_2](https://cloud.githubusercontent.com/assets/7361684/25909417/eb9ebf78-35ce-11e7-892e-4a0874706910.png)

**Comment by Engandend** [comment]
self.showLoadEarlierMessagesHeader = NO;   ？

**Comment by shravanteegala** [comment]
Hi,
I am faceing same issue please help me..

**Comment by Lucashuang0802** [comment]
Did `self.navigationController.navigationBar.translucent = NO;` fix the problem?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
