### ISSUE TITLE
Incompatibility with App Extensions Due to Use of UIApplication.shared

### ISSUE THREAD

**Issue by paulstringer** [jessesquires/JSQMessagesViewController#2099]
## New issue checklist

- [✅] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [✅] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [✅] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

-`JSQMessagesViewController` version: All
- iOS version: all
- Devices/Simulators: all
- Reproducible in the demo project? (Yes/No): No
- Any related issues:

## What happened?

- When linking with a App Extension target, compiler errors occur related to usage of UIApplication which is [unavailable in App Extensions](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW2). This results in JSQMessagesView being unusable in Extensions. 

Examining the usage of UIApplication shows that it's being used by `JSQMessagesBubbleImageFactory`. Further investigation shows that an alternative Extension Safe approach would be to use the alternative `UIView.effectiveUserInterfaceLayoutDirection`.

An investigation was done by changing the BubbleFactory default initialiser to use `UIView().effectiveUserInterfaceLayoutDirection` in the Swift Example. An arabic language was added to the example and then when switching between Right to Left and Left to Right languages showed that the current behaviour was preserved.

The benefit would be that by implementing the alternative JSQMessagesViewController would be safe to implement the APPLICATION_EXTENSION_API_ONLY=YES setting giving it broader use in not only Application but also Extensions.

I propose a pull request be submitted for version 8.0 for consideration for this release.

_Investigation SwiftExample left to right (English) with Extension Compatibility_
![Swift Example left to right (English) with Extension Compatibility](https://cloud.githubusercontent.com/assets/4324816/25935370/cfa9ad2c-361a-11e7-8d15-69cee76a9ba4.png)
_Investigation SwiftExample left to right (English) with Extension Compatibility_
![Swift Example right to left (Arabic) with Extension Compatibility](https://cloud.githubusercontent.com/assets/4324816/25935371/cfc6940a-361a-11e7-9688-609fe786e20e.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
