### ISSUE TITLE
How to set MUC (Multi User Chat)  GroupChat to this message UI.

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2105]
Hi.
its a Excellent for Chat UI. i added this one Chating one t one. its working perfectly.
But . How I Add MUC like Group Chat this UI.
Please help me.

**Comment by apwelsh** [comment]
It supports multi-user chat exactly like one-on-one chat.    If the sender id of the message mayches the sender id of the chat view controller, then the message is a sent message.    All other messages are received    messages.    I happen to like using the avatar on incoming messages to distinguish the various users.    Additionally, you should be able to include the sender's handle (screen name) in the message prefix or suffix area to make it easier to identify the various users of incoming messages.    Its up to you how you organize your data.    For instance, you may want each sender in their own section, or all in one section. The framework is already there, its up to you to devide how leverage it to implement your solution.    
  
  
  
  
  

  
  
>

**Comment by Lucashuang0802** [comment]
thanks, @apwelsh. It has been really helpful. 👍

**Comment by saroar** [comment]
is there any code we can check thanks
