### ISSUE TITLE
How i put send button disable mode .if app goes to offline .in Chat

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2106]
How i put send button disable mode .if app goes to offline .
and enable it comes to online

I am those problem.

please help me.

**Comment by mding5692** [comment]
See this : https://stackoverflow.com/questions/25398664/check-for-internet-connection-availability-in-swift

and if its offline, just change sendButton to nil or hidden = true and then toggle once online

**Comment by Lucashuang0802** [comment]
Thanks, @mding5692. 

@shravanteegala  Normally, it should have an observer(notification, block etc) for observing going offline and back online. So, you can adjust the send button based on the connection change.
