### ISSUE TITLE
Cartfile support is not working properly.

### ISSUE THREAD

**Issue by salyasev** [jessesquires/JSQMessagesViewController#2109]
Adding github "jessesquires/JSQMessagesViewController" to Cartfile 
Run `carthage update` and got a message
"Dependency"JSQMessagesViewController has no shared framework schemes for any of the platforms: iOS"

But I see that feature is closed - https://github.com/jessesquires/JSQMessagesViewController/pull/1987

**Comment by Lucashuang0802** [comment]
Please keep track on #1216.
