### ISSUE TITLE
How to show/hide keyboard programmatically?

### ISSUE THREAD

**Issue by henrikjn** [jessesquires/JSQMessagesViewController#211]
Is there any way to Show/Hide the keyboard from the implementation? 

I am using a NavigationController and want to display the keyboard as soon as the view shows.

**Comment by devilbags** [comment]
What about hiding the keyboard by touching other places on the screen?

**Comment by gcarlo89** [comment]
@devilbags you could resign first responder in `collectionView:didTapCellAtIndexPath:touchLocation` or in `collectionView:didTapMessageBubbleAtIndexPath:`

**Comment by stanislavfeldman** [comment]
Actually it is enough to add
```
- (void)collectionView:(JSQMessagesCollectionView *)collectionView didTapCellAtIndexPath:(NSIndexPath *)indexPath touchLocation:(CGPoint)touchLocation {
    [self.view endEditing:YES];
}

- (void)collectionView:(JSQMessagesCollectionView *)collectionView didTapMessageBubbleAtIndexPath:(NSIndexPath *)indexPath {
    [self.view endEditing:YES];
}
```
