### ISSUE TITLE
JSQAudioMediaItem download audio before playing

### ISSUE THREAD

**Issue by nelzaatari** [jessesquires/JSQMessagesViewController#2114]
Good Day,

any idea how to implement downloading the audio file from a remote url before playing it just like whatsapp, 

i appreciate your help

Regards,
Noureddine

**Comment by Lucashuang0802** [comment]
@nelzaatari, please take a look `JSQAudioMediaItem` class. At the bottom, there is a convenient method possibly fitting your need: `- (void)setAudioDataWithUrl:(nonnull NSURL *)audioURL;`.

Hope it helps.
