### ISSUE TITLE
JSQMessagesTypingIndicatorFooterView changing the image used for typing indicator

### ISSUE THREAD

**Issue by mding5692** [jessesquires/JSQMessagesViewController#2116]
I was wondering if I could add my image instead of the typing indicator image that was used in the xib file. I've tried using a xib file but everything doesn't work as per the closed issues I've already seen in Swift 3.

**Comment by mizerable99** [comment]
L

**Comment by mding5692** [comment]
I copy and pasted the xib file using terminal from JSQMessages Pod and then changed the name and also added my identifier using storyboard

Also overridden the nib() function as seen in previous issues

Then added to collectionView using below method:
https://stackoverflow.com/questions/38929586/uicollectionview-footer-in-swift
