### ISSUE TITLE
single outgoing message loads on the left

### ISSUE THREAD

**Issue by RDerrow** [jessesquires/JSQMessagesViewController#2117]
## New issue checklist

- [x ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version: 9.3
- Devices/Simulators: Physical iPhone 6
- Reproducible in the demo project? (No): 
- Any related issues: none

## What happened?

I have an outgoing message (the first outgoing message sent, in this case) that loads towards the left of the screen as opposed to the right; however all of the other messages, both outgoing and incoming, load perfectly fine.

![img_0868](https://cloud.githubusercontent.com/assets/15151024/26758047/3fa86746-4898-11e7-8032-dafc034033d8.PNG)

**Comment by mding5692** [comment]
You should probably dump your code here too so we can examine it

**Comment by RDerrow** [comment]
I fixed the issue. I was setting the senderId in the wrong place, so when the first message was sent by the user the message was not considered to be the current user and was placed on the wrong side.
