### ISSUE TITLE
installing JSQMessagesController without CocoaPods

### ISSUE THREAD

**Issue by duilovska** [jessesquires/JSQMessagesViewController#2118]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?

Is it possible to use JSQMessagesController without CocoaPods?

Step by step what I have done:

I cloned project from GitHub
Copied downloaded project folder to my project folder
Opened the new downloaded folder, and dragged the JSQMessages.xcodeproj into the Project Navigator of my application's Xcode project
the same I've done with JSQSystemSoundPlayer
I added #import <JSQMessagesViewController/JSQMessages.h> to bridging header (here comes an error "file not found")
And it shows me an error when I'm trying to import JSQMessagesController: "No such module"

**Comment by duilovska** [comment]
Is it possible to use JSQMessagesController without CocoaPods?

Step by step what I have done:

1. I cloned project from GitHub
2. Copied downloaded project folder to my project folder
3. Opened the new downloaded folder, and dragged the JSQMessages.xcodeproj into the Project Navigator of my application's Xcode project
4. the same I've done with JSQSystemSoundPlayer
5. I added #import <JSQMessagesViewController/JSQMessages.h> to bridging header (here comes an error "file not found")

And it shows me an error when I'm trying to import JSQMessagesController: "No such module"

**Comment by apwelsh** [comment]
You can certainly add the project in that way, but the imports would need to be changed.    The intended solution for manually adding it is to add it as a framework. I am no XCode expert.    I believe the way you do this is to open the JSQMessagesViewController as an XCode project, and to build it as a framework.    Then you can just add the built framework to your project.    This is the fastest way to build your code too, as you would only build the frameworks when they need to change, and you project build only builds your own code, and then the linker links in the frameworks.    
  
  
  

    
  
It does not apoear that the library is written in such a way to be built into a framework, but a quick google search on creating xcode frameworks should show you how to create such a project.
  
  
>

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
