### ISSUE TITLE
Only last 25 messages loaded in chat

### ISSUE THREAD

**Issue by tHull90** [jessesquires/JSQMessagesViewController#2119]
I'm finishing up a group chat app made with JSQMessagesViewController and I noticed that in a chat with more than 25 messages, only the last 25 appear in the chat.

This is my `observeMessages` function:

    private func observeMessages() {
        messageRef = roomRef!.child("messages")
        let messageQuery = messageRef.queryLimited(toLast:25)
        
        // Observe method to listen for new messages being written to Firebase
        newMessageRefHandle = messageQuery.observe(.childAdded, with: { (snapshot) -> Void in
            
            let messageData = snapshot.value as! Dictionary<String, String>
            
            if let id = messageData["senderId"] as String!, let name = messageData["senderName"] as String!, let text = messageData["text"] as String!, text.characters.count > 0 {
                
                
                self.addMessage(withId: id, name: name, text: text)
                
                self.finishReceivingMessage()
            } else if let id = messageData["senderId"] as String!,
                let photoURL = messageData["photoURL"] as String! {
                
                if let mediaItem = JSQPhotoMediaItem(maskAsOutgoing: id == self.senderId) {
                    
                    self.addPhotoMessage(withId: id, key: snapshot.key, mediaItem: mediaItem)
                    
                    if photoURL.hasPrefix("gs://") {
                        self.fetchImageDataAtURL(photoURL, forMediaItem: mediaItem, clearsPhotoMessageMapOnSuccessForKey: nil)
                    }
                }
            } else {
                //print("Error! Could not decode message data")
            }
        })
        
        // Observer to listen for changes to existing messages. Used to be notified when a photo has been stored to the Firebase Storage, so we can update the message data
        updatedMessageRefHandle = messageRef.observe(.childChanged, with: { (snapshot) in
            let key = snapshot.key
            let messageData = snapshot.value as! Dictionary<String, String>
            
            if let photoURL = messageData["photoURL"] as String! {
                // The photo has been updated
                if let mediaItem = self.photoMessageMap[key] {
                    self.fetchImageDataAtURL(photoURL, forMediaItem: mediaItem, clearsPhotoMessageMapOnSuccessForKey: key)
                }
            }
        })
    }

Is this normal behavior? I'm using Swift 3 if it makes a difference. Thanks for any insight!

**Comment by mding5692** [comment]
Maybe its got to do with using firebase

**Comment by ChildishTimbino** [comment]
@mding5692 My mistake, I thought that would load 25 at a time (until all the messages are loaded). A few questions if you're familiar with using JSQ with Firebase - if I remove that limit from the query, would that severely slow down the app, loading all the messages at once? How do people usually do it? Always add pagination/infinite scrolling? From what I've seen it's kind of difficult to add that.

**Comment by apwelsh** [comment]
Yeah, there is a disconnect with firebase in observing changes and loading all data.  If you want to load all the data, you must perform a query for all the records.  Then you can listen for added/changed/deleted events, and perform actions on them.  But, depending on how you write your code/query, you could end up receiving duplicates (and often do) if you dont use carefully crafted queries.  If you dint care about the initial load of all messages adding o e message at a time, just skip the initial query, and listen for child-added events, adding the results.  On initial load, you have no local state, so the whole thread is downloaded and added to your local collection.
I happen to preload everything, to bypass animations, then I listen for child-added and for each one, I animate the addition of the message.  Bur, if the message is already in my local collection, I throw the message away.

**Comment by ChildishTimbino** [comment]
I'm not sure I understand completely - with your approach, do you load all the messages in the chat? Or does that load messages as needed (as the user scrolls up/back in time)? I don't know what the best solution here is - either keep it loading only the last 25 messages, which isn't ideal because the messages before that are gone - or load the entire chat, and for a huge group chat possibly spanning months, that will undoubtedly cause problems won't it?

**Comment by mding5692** [comment]
For my app, which loads all messages I only use .childAdded, I think it works best

However once your app messages reaches a certain size, it could slow down, I recommend pagination after that. I do a count, if my count reaches 100, I create another key under my chatroomKey for another page

**Comment by Lucashuang0802** [comment]
It does not seem to be related to the library, I'm closing this out. But feel free to continue the conversation on this thread! 😃
