### ISSUE TITLE
How can I customize UI of this to look like Snapchat ? Need suggestions & ideas. Please help.

### ISSUE THREAD

**Issue by iMemon** [jessesquires/JSQMessagesViewController#2120]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: I have reviewed the contributing guidelines. Confirmation: 💪 😎 👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?

I have a requirement to change UI similar to snapchat instead of iMessage. Please guide me what can I do, I have used this in many projects so I have some idea of the code. Here is a quick look of snapchat UI which I want to achieve.

![screen shot 2017-06-08 at 11 47 23 am](https://user-images.githubusercontent.com/6410833/26915911-76f998d0-4c41-11e7-8be7-c078bffb5740.png)

The main differences (noted by me) are:
- No bubbles
- Vertical line on the left of messages, joining all consecutive messages of sender
- Sender name on the top
- Both sender and receiver messages are on left-side.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
