### ISSUE TITLE
Need help with Creating a Reply to Message bubble using JSQ

### ISSUE THREAD

**Issue by gmansata6290** [jessesquires/JSQMessagesViewController#2121]
@jessesquires I have been working on the "reply to a message" option in my app, as in whatsapp and other chat apps.  I have completed most of the UI part, upto the point where I show the preview of the message to reply as shown in the image below. 

The problem I am facing is while dynamically calculating the height and the width of the content from my reply. My reply could be multi line text or img or location and I need to account for the height & width of the original message message plus my reply. 

Can you please guide me to or point me to what I need to change so I can achieve this?

Note : I have generated a bubble with reply msg but I can only assign a fixed bubble size using CustomJSQMediaItem, but now I need to make it dynamic.

![simulator screen shot 08-jun-2017 3 37 22 pm](https://user-images.githubusercontent.com/12854378/26923533-faa584aa-4c5f-11e7-9b66-d18b62ea7927.png)

Desired Result for me would be something like this
![screenshot_20170608-135414_01](https://user-images.githubusercontent.com/12854378/26922470-d5e304b0-4c5c-11e7-9685-32a89be62072.png)

**Comment by gmansata6290** [comment]
I solved out the problem with the JSQMediaItem only

**Comment by JDModi** [comment]
Hello @gmansata6290  i need one Help from you . i am new in iOS . i want to make Custom chat layou . please help me.

**Comment by shraddha-patel-1891** [comment]
Hello @gmansata6290 
can you please tell me how to use JSQMediaItem for creating reply bubble?
I tried many solutions but not display like whats app so can you please help me?
or
message send on server as  text or media message?

**Comment by bibscy** [comment]
@gmansata6290 Do you have any code showing how you built the UI for replying inside the bubble. I don't know where to start from. Could you explain the functionality if you don't have any code? 
Many thanks
