### ISSUE TITLE
first messages where hidden under navigation bar.

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2122]
when i enter the chat view first time its works but again enter that chatView chattext view hides partially by status bar.
please show below screen shot.
![screen shot 2017-06-08 at 4 32 21 pm](https://user-images.githubusercontent.com/13646977/26925777-b4eee75e-4c68-11e7-93cc-ee7da75f40da.png)

**Comment by Lucashuang0802** [comment]
Duplicated with #2123
