### ISSUE TITLE
First message is overlapped by Navigation bar,scroll to top.

### ISSUE THREAD

**Issue by shravanteegala** [jessesquires/JSQMessagesViewController#2123]
when i send message it shows correctly first time.but i went back and come again it shows to 
scroll view scroll to top. so my first message view overlapped by navigation bar.
please help me.
![simulator screen shot 08-jun-2017 8 10 15 pm](https://user-images.githubusercontent.com/13646977/26935157-da78706a-4c88-11e7-8ba5-284ba6f1d4fc.png)

**Comment by mding5692** [comment]
@shravanteegala If you create it using a UINavigationBar class, then do this:

`topContentAdditionalInset = navigationBar.frame.height` 

in your viewDidAppear()

It leaves enough space for your navigationbar at the top of collectionView, if you need more just change the height to like:

`topContentAdditionalInset = navigationBar.frame.height * 1.2`

**Comment by shravanteegala** [comment]
I didn't find  topContentAdditionaInset property ?

**Comment by mding5692** [comment]
Are you using JSQMessageViewController? just type topContentAdditionalInset in your viewDidLoad and you will see it

**Comment by mding5692** [comment]
To demonstrate that this works, I will show you my chat:

![screen shot 2017-06-20 at 8 17 32 pm](https://user-images.githubusercontent.com/9067177/27361480-97bdd37a-55f5-11e7-9197-6a5381588f7f.png)

**Comment by shravanteegala** [comment]
![screen shot 2017-06-21 at 2 16 31 pm](https://user-images.githubusercontent.com/13646977/27375283-4c5a81ca-568c-11e7-929f-ec0692992f77.png)

**Comment by mding5692** [comment]
Did you subclass JSQMessageViewController? what is BBJSQMessageViewController, it should say JSQMessageViewController and declaring the class should look like this:

![screen shot 2017-06-21 at 9 31 37 pm](https://user-images.githubusercontent.com/9067177/27413399-1ca662e0-56c9-11e7-8997-2af916173315.png)

**Comment by shravanteegala** [comment]
Yes I subclass the BBJSQMessageViewController:JSQMessageViewController.

**Comment by mding5692** [comment]
weird, not too sure then, im using IOS Swift, cant help more then, sorry

**Comment by acjh** [comment]
@shravanteegala How about `self.additionalContentInset.top`?

**Comment by Lucashuang0802** [comment]
@shravanteegala did `self.navigationController.navigationBar.translucent = NO;` fix the problem?

**Comment by shravanteegala** [comment]
Thank you.
