### ISSUE TITLE
The inputToolbar will dismiss on ios11 

### ISSUE THREAD

**Issue by sagiters19** [jessesquires/JSQMessagesViewController#2125]
When i update device to ios11 for testing. I found that The inputToolbar will dismiss.
Is this ios11 problem?

**Comment by Lucashuang0802** [comment]
@sagiters19 is it replicable in the demo project? Please provide steps if so. It will be so helpful to address the problem. 😃

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
