### ISSUE TITLE
Image Not Uploaded

### ISSUE THREAD

**Issue by JDModi** [jessesquires/JSQMessagesViewController#2126]
![Uploading Screen Shot 2017-06-14 at 11.57.56 AM.png…]()

**Comment by Lucashuang0802** [comment]
@JDModi, it does not seem to follow our guideline to submit an issue. Please modify your question. 😃

**Comment by Lucashuang0802** [comment]
Thanks! 😄

Please provide all the information in the issue template so we can help!
And don't forget to read our contribution guidelines. 😊
