### ISSUE TITLE
JSQMediaLocation is not loading for incoming message JSQMessagesViewController 

### ISSUE THREAD

**Issue by bilalinbox06** [jessesquires/JSQMessagesViewController#2127]
hi, I have problem with JSQMediaLocation item. it is not showing map snapshot for incoming message (just showing loader) but works fine for outgoing message. if anyone can help me it will be really appreciated. Thanks

**Comment by Lucashuang0802** [comment]
@bilalinbox06  is there a way to replicate that in the demo app? If so, can you provide it? That will help address the problem. 😃

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
