### ISSUE TITLE
JSQMessagesComposerTextView's pasteDelegate property conflicts with iOS 11's new pasteDelegate

### ISSUE THREAD

**Issue by antipex** [jessesquires/JSQMessagesViewController#2128]
iOS 11 introduces a new `pasteDelegate` property on `UITextView`, which conflicts with the `pasteDelegate` property in `JSQMessagesComposerTextView`, causing a crash. This property will need to be renamed so JSQMessagesViewController will work with iOS 11.

More info:
- https://developer.apple.com/documentation/uikit/uitextpasteconfigurationsupporting
- https://developer.apple.com/documentation/uikit/uitextpasteconfigurationsupporting/2887494-pastedelegate

**Comment by Lucashuang0802** [comment]
@jessesquires, you can assign this to me and provide a naming. 😃

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by lukas2** [comment]
Thanks for this issue, guys. Solved my problem. Small note: This only crashes for me on iOS Devices running iOS 10 or 9. Probably iOS 11 has a check that prevents the access violation there.

**Comment by Katafalkas** [comment]
Is it merged? to some branch? how can I install JSQ with this fix?
