### ISSUE TITLE
How to add counter label to textView input??

### ISSUE THREAD

**Issue by luongnhatlam** [jessesquires/JSQMessagesViewController#2129]
Hello guys, I'm finding the way to add the counter label to textView input! My purpose is to limit the number of text that user can type in and they can see it! But I don't know to add it to textView input

**Comment by mding5692** [comment]
Create a UILabel and place it near where the textView is and keep it hidden until someone types into the textView

**Comment by luongnhatlam** [comment]
@mding5692 thank guy, but I mean the label will be inside the textview! How to do that??

**Comment by Lucashuang0802** [comment]
@luongnhatlam, @mding5692's solution is not totally wrong except he did not mention what's the hierarchy of label and text view. Visually, it will meet what you are asking for. If you really want to put a label inside the text view. You can `addSubview` to make it happen.

Hope it helps.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
