### ISSUE TITLE
Add button to bubble

### ISSUE THREAD

**Issue by amirch123** [jessesquires/JSQMessagesViewController#2131]
<img width="326" alt="459654d8-f5c9-11e5-8065-6e9fdf1c62ca" src="https://user-images.githubusercontent.com/25988633/27261466-c147d5cc-5458-11e7-8b91-b3223c6eeeab.png">

Hello
I need add button like this picture(In swift)
plz help me
Thanks

**Comment by eliburke** [comment]
@amirch123 check out issue #1519 and commit f238eccbf6d1b25d6e75895d71824b8b08e0d8d8 

You need to add the JSQMessagesViewAccessoryButtonDelegate protocol, implement `+- (void)messageView:(JSQMessagesCollectionView *)view didTapAccessoryButtonAtIndexPath:(NSIndexPath *)path` and set self.collectionView.accessoryDelegate

To override the button image it appears that you need to either call `setAccessoryButtonImage` in your cell setup, or if you have subclassed the cell, you can override `configureAccessoryButton`

I haven't used it myself so I can't be more specific, but that should be enough breadcrumbs to get you where you need to be.

**Comment by amirch123** [comment]
@eliburke 
Thank you
