### ISSUE TITLE
to set the bubble container's top = bubble top label's bottom + ___

### ISSUE THREAD

**Issue by wustzhy** [jessesquires/JSQMessagesViewController#2133]
when i set " the bubble container's top = bubble top label's bottom + 10 " , unexpectedly, found that the text in the messageBubbleContainerView is no longer be vertically center. So , please give me help to correctly set the space between bubble container's top and bubble top label's bottom.

![image.png](http://upload-images.jianshu.io/upload_images/2684540-ccab77eba1cea366.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by apwelsh** [comment]
The message bubbles use constraints.    Did you directly set the properties for the frames, or did you change the constraint?
  

  
  

  
  
>

**Comment by wustzhy** [comment]
![image](https://user-images.githubusercontent.com/20319474/27309768-71f7d1e4-5588-11e7-839e-8c85a3c62ee5.png)
I set the constraint in xib .Did I do wrongly?  Or I need to do sth else to not make effect upon the bubble container's content. Thanks for your reply!

**Comment by wustzhy** [comment]
@VincentSit @jessesquires  please help me above, thank you very much. Have you try that way above? Did you face the same issue?

**Comment by VincentSit** [comment]
@wustzhy Sorry, I'm afraid I could not help you, I have two years no attention to this project.

**Comment by MacMeDan** [comment]
I would assume this is due to the fact that these can vary in height from one message to the next. I'll take a look and see if there is a good place to change this.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
