### ISSUE TITLE
can I dynamic cell size height?

### ISSUE THREAD

**Issue by pig12301230** [jessesquires/JSQMessagesViewController#2134]
I am using UrlEmbeddedView to parse url's ogData.
and I hope I can do it like Facebook messenger style. 
<img width="240" alt="2017-06-21 12 48 48" src="https://user-images.githubusercontent.com/17565171/27345240-87d5834c-561b-11e7-98b5-2c48d6f21871.png">

to show my message and url's ogdata like image, but I don't know height before I parse the url. 
because cells mediaViewDisplaySize()  are different. 
so when I scroll the view,  and collectionview reuse the cell, it will make wrong cell height 
How can I resize the cell height by mediaView Size?

**Comment by pig12301230** [comment]
<img width="354" alt="2017-06-26 1 05 14" src="https://user-images.githubusercontent.com/17565171/27518159-a6224b7a-5a0b-11e7-94f8-526f7f23c87f.png">
it's correct size but if I scroll to top and back it will like this.
<img width="368" alt="2017-06-26 1 08 01" src="https://user-images.githubusercontent.com/17565171/27518180-f228524e-5a0b-11e7-9fd3-0357ac07c691.png">

**Comment by Lucashuang0802** [comment]
@pig12301230 is it possible that the image size got changed to cause this issue?

**Comment by pig12301230** [comment]
@Lucashuang0802 
but I think that is  cell height cause image size changed.
like this 
![2017-06-26 1 49 40](https://user-images.githubusercontent.com/17565171/27526137-681ee32c-5a76-11e7-8048-5463ce5a30b6.png)

when I get cell height it will follow constraints. but the size of height is wrong

**Comment by pig12301230** [comment]
is it possible that my custom mediaItem mediaViewDisplay() height is dynamic? so when I reuse the cell it'll use other mediaview height? 
![2017-06-26 1 49 40](https://user-images.githubusercontent.com/17565171/27534139-919532fc-5a98-11e7-9234-88cca9c9b97b.png)
-- 
<img width="354" alt="2017-06-26 1 05 14" src="https://user-images.githubusercontent.com/17565171/27534145-95386ba4-5a98-11e7-9625-c7e40da95db7.png">

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
