### ISSUE TITLE
Custom UIView for cell

### ISSUE THREAD

**Issue by marcuschoong** [jessesquires/JSQMessagesViewController#2135]
I would like to change the message cell to dynamic UI base on server respond. (Maybe add UIButton and UILabel to UIView and populate to cell), understand that jessesquires was release the code that can pass in the custom UI with some easier way and i know there is many question regarding the custom cell provided but i can't understand how to implement in code. 

Possible can guide me the step by step what should be code in program in order to achieve the custom uiview for cell?

Thank you.

Regards
Marcus

**Comment by marcuschoong** [comment]
I added new files called JSQRatingMediaItem which copy from JSQPhotoMediaItem like the following : 

JSQRatingMediaItem.h
> #import "JSQMediaItem.h"
> 
> @interface JSQRatingMediaItem : JSQMediaItem <JSQMessageMediaData, NSCoding, NSCopying>
> 
> @property (copy, nonatomic) UIView *ratingView;
> 
> - (instancetype)initWithUIView:(UIView *)ratingView;
> 
> @end

JSQRatingMediaItem.m
> #import "JSQRatingMediaItem.h"
> 
> @interface JSQRatingMediaItem ()
> 
> @property (strong, nonatomic) UIView *cachedUIView;
> 
> @end
> 
> @implementation JSQRatingMediaItem
> 
> - (instancetype)initWithUIView:(UIView *)ratingView
> {
>     self = [super init];
>     if (self) {
>         _ratingView = [ratingView copy];
>         _cachedUIView = nil;
>     }
>     return self;
> }
> 
> - (void)clearCachedMediaViews
> {
>     [super clearCachedMediaViews];
>     _cachedUIView = nil;
> }
> 
> -(void) setRatingView:(UIView *)ratingView{
>     _ratingView = [ratingView copy];
>     _cachedUIView = nil;
> }
> 
> - (void)setAppliesMediaViewMaskAsOutgoing:(BOOL)appliesMediaViewMaskAsOutgoing
> {
>     [super setAppliesMediaViewMaskAsOutgoing:appliesMediaViewMaskAsOutgoing];
>     _cachedUIView = nil;
> }
> 
> #pragma mark - JSQMessageMediaData protocol
> 
> - (UIView *)mediaView
> {
>     if (self.ratingView == nil) {
>         return nil;
>     }
>     
>     if (self.cachedUIView == nil) {
>         CGSize size = [self mediaViewDisplaySize];
> //        UIImageView *imageView = [[UIImageView alloc] initWithImage:self.image];
> //        imageView.frame = CGRectMake(0.0f, 0.0f, size.width, size.height);
> //        imageView.contentMode = UIViewContentModeScaleAspectFill;
> //        imageView.clipsToBounds = YES;
> //        [JSQMessagesMediaViewBubbleImageMasker applyBubbleImageMaskToMediaView:imageView isOutgoing:self.appliesMediaViewMaskAsOutgoing];
>         
>         UIView* containerView = [[UIView alloc] init];
>         containerView.frame = CGRectMake(0.0f, 0.0f, size.width, size.height);
>         UILabel *label =  [[UILabel alloc] initWithFrame: CGRectMake(0, 0, 50, 50)];
>         label.text = @"vendor name";
>         [containerView addSubview:label];
>         
>         self.cachedUIView = containerView;
>     }
>     
>     return self.cachedUIView;
> }
> 
> @end

at my ViewController that is subclass JSQMessagesViewController, i added following code in 

> - (id<JSQMessageData>)collectionView:(JSQMessagesCollectionView *)collectionView messageDataForItemAtIndexPath:(NSIndexPath *)indexPath


> JSQRatingMediaItem *photoItem = nil;
>         
>         UIView* containerView = [[UIView alloc] init];
>         containerView.frame = CGRectMake(0.0f, 0.0f, 315.0f, 100.0f);
>         UILabel *label =  [[UILabel alloc] initWithFrame: CGRectMake(0, 0, 50, 50)];
>         label.text = @"vendor name";
>         [containerView addSubview:label];
>         
>         photoItem = [[JSQRatingMediaItem alloc] initWithUIView:containerView];
>         
>         // 没有此行代码则气泡的箭头方向会错误哦
>         photoItem.appliesMediaViewMaskAsOutgoing = NO;
>         // 构造JSQMessage对象
>         md = [[JSQMessage alloc] initWithSenderId:entity.name senderDisplayName:entity.name date:entity.date media:photoItem];

I hit error during initWithUIView:containerView in following line : 
> @implementation JSQRatingMediaItem
> 
> - (instancetype)initWithUIView:(UIView *)ratingView
> {
>     self = [super init];
>     if (self) {
>         _ratingView = [ratingView copy];  <--- error
>         _cachedUIView = nil;
>     }
>     return self;
> }

the error msg is like the following : 
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x7fe88b40e380> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _needsContentsFormatUpdate.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f9c434b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010eb8121e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f9c4299 -[NSException raise] + 9
	3   Foundation                          0x000000010e69126f -[NSObject(NSKeyValueCoding) setValue:forKey:] + 291
	4   UIKit                               0x00000001118c380d -[UIView(CALayerDelegate) setValue:forKey:] + 173
	5   talkm_visitor_sdk                   0x000000010e36a05a -[NSObject(RMCopyable) copyWithZone:] + 538
	6   talkm_visitor_sdk                   0x000000010e3582f6 -[JSQRatingMediaItem initWithUIView:] + 134
	7   talkm_visitor_sdk                   0x000000010e31afb8 -[ChatViewController collectionView:messageDataForItemAtIndexPath:] + 3992
	8   talkm_visitor_sdk                   0x000000010e32abf1 -[JSQMessagesCollectionViewFlowLayout messageBubbleSizeForItemAtIndexPath:] + 161
	9   talkm_visitor_sdk                   0x000000010e32acf7 -[JSQMessagesCollectionViewFlowLayout sizeForItemAtIndexPath:] + 71
	10  talkm_visitor_sdk                   0x000000010e312533 -[JSQMessagesViewController collectionView:layout:sizeForItemAtIndexPath:] + 131
	11  UIKit                               0x000000011218a0ff -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 3033
	12  UIKit                               0x000000011218b887 -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 127
	13  UIKit                               0x0000000112184a02 -[UICollectionViewFlowLayout collectionViewContentSize] + 66
	14  talkm_visitor_sdk                   0x000000010e30ef34 -[JSQMessagesViewController scrollToIndexPath:animated:] + 420
	15  talkm_visitor_sdk                   0x000000010e30ed79 -[JSQMessagesViewController scrollToBottomAnimated:] + 265
	16  talkm_visitor_sdk                   0x000000010e30ec11 -[JSQMessagesViewController finishReceivingMessageAnimated:] + 385
	17  talkm_visitor_sdk                   0x000000010e317f18 __45-[ChatViewController initWithNibName:bundle:]_block_invoke.7 + 312
	18  talkm_visitor_sdk                   0x000000010e39bb4e -[NSMutableArrayObservable notifyObserverNew:whithExtra:] + 206
	19  talkm_visitor_sdk                   0x000000010e39b2ba -[NSMutableArrayObservable add:needNotify:] + 170
	20  talkm_visitor_sdk                   0x000000010e39b1f3 -[NSMutableArrayObservable add:] + 67
	21  talkm_visitor_sdk                   0x000000010e357a1e -[MessagesProvider putMessage:withData:] + 126
	22  talkm_visitor_sdk                   0x000000010e2b7ad4 +[ChatHelper addChatMessageData:withTime:playAudio:showNotify:msgType:withrecivedMessagesObserver:] + 516
	23  talkm_visitor_sdk                   0x000000010e28fc01 +[ChatTransDataEventImpl addChatMessageData:withTime:playAudio:showNotify:typeu:] + 225
	24  talkm_visitor_sdk                   0x000000010e28fa1c -[ChatTransDataEventImpl onTransBuffer:withUserId:andContent:andTypeu:] + 1164
	25  talkm_visitor_sdk                   0x000000010e3c67b2 -[LocalUDPDataReciever handleProtocal:] + 1613
	26  talkm_visitor_sdk                   0x000000010e3c3705 -[LocalUDPSocketProvider udpSocket:didReceiveData:fromAddress:withFilterContext:] + 183
	27  talkm_visitor_sdk                   0x000000010e3cbac5 __72-[GCDAsyncUdpSocket notifyDidReceiveData:fromAddress:withFilterContext:]_block_invoke + 51
	28  libdispatch.dylib                   0x0000000113dd9980 _dispatch_call_block_and_release + 12
	29  libdispatch.dylib                   0x0000000113e030cd _dispatch_client_callout + 8
	30  libdispatch.dylib                   0x0000000113de38d6 _dispatch_main_queue_callback_4CF + 406
	31  CoreFoundation                      0x000000010f9884f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	32  CoreFoundation                      0x000000010f94df8d __CFRunLoopRun + 2205
	33  CoreFoundation                      0x000000010f94d494 CFRunLoopRunSpecific + 420
	34  GraphicsServices                    0x0000000115169a6f GSEventRunModal + 161
	35  UIKit                               0x00000001117ff964 UIApplicationMain + 159
	36  talkm_visitor_sdk                   0x000000010e37dc1f main + 111
	37  libdyld.dylib                       0x0000000113e4f68d start + 1
	38  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Lucashuang0802** [comment]
Thanks @marcuschoong!

Please see the FAQ:
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md
