### ISSUE TITLE
Activity indicator not showing up on specific messages

### ISSUE THREAD

**Issue by chand97** [jessesquires/JSQMessagesViewController#2136]
The activity indicator dosent show up on all messages as seen in the attached picture.This is my code for retrieving messages:

```
let randomString = dictionary["randomString"] as! String
                    self.messagesID.append(messageID)
                    self.messagesTime.append(time)
                    self.messagesRead.append(recipt)
                    let fileUrl = dictionary["fileURL"] as! String
                    let url = URL(string: fileUrl)
                    let audio = JSQAudioMediaItem()
                    audio.audioData = nil
                    if senderID != FIRAuth.auth()?.currentUser?.uid {
                        
                        audio.appliesMediaViewMaskAsOutgoing = false
                    }
                    
                    do {
                        
                        self.fileURLs.append(randomString)
                        
                        DispatchQueue.global(qos: .default).async {
                            
                            let data = try? Data(contentsOf: url!)
                            
                            if data != nil {
                                
                                DispatchQueue.main.async {
                                    
                                    audio.audioData = data
                                    self.collectionView.reloadData()
                                }
                            }
                        }
                        
                    }catch {
                        
                        print(error.localizedDescription)
                        
                    }
                    let audioMessage = JSQMessage(senderId: senderID, displayName: senderDisplayName, media: audio)
                    self.messages.append(audioMessage!)
                    self.collectionView.reloadData()

```

![simulator screen shot 21-jun-2017 7 14 27 pm](https://user-images.githubusercontent.com/25543597/27388806-ffda0f26-56b5-11e7-9c58-01cb42b132f7.png)

Any help is appreciated.

**Comment by mding5692** [comment]
@chand97 
Do you mean typing indicator?

**Comment by chand97** [comment]
Nope as you see the top most message does have an activity indicator but the last ones dont

**Comment by Lucashuang0802** [comment]
@chand97 is there a way to replicate that in the demo app? If so, can you provide it? That will help address the problem. 😃

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
