### ISSUE TITLE
Typing Indicator size too small 

### ISSUE THREAD

**Issue by mding5692** [jessesquires/JSQMessagesViewController#2138]
Hi, I've customized the typing indicator and added my own image using a xib file.

But the typing indicator that appears is too small and it looks like theres a big left margin pushing it so that it looks like its in the middle. 

Is there a way to change the sizing of the typing indicator or affect that row margin on the bottom of the collectionView?

**Comment by Lucashuang0802** [comment]
Thanks! 😄

Please provide all the information in the issue template so we can help!
And don't forget to read our contribution guidelines. 😊

**Comment by mding5692** [comment]
Closed as moved to issue #2140
