### ISSUE TITLE
How to change text "Load Earlier Messages"

### ISSUE THREAD

**Issue by geekstars** [jessesquires/JSQMessagesViewController#2139]
## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by Lucashuang0802** [comment]
@geekstars, the string value can be found by the Xcode search. It looks like you need to modify all localization files (JSQMessages.strings etc). 😃

**Comment by ribhuchawla** [comment]
How can I change text dynamically? For eg. change text to "Loading..." or "Failed to fetch" ?
