### ISSUE TITLE
Scrolling issue When keyboard not opened First time.

### ISSUE THREAD

**Issue by madBureaToT** [jessesquires/JSQMessagesViewController#2142]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by madBureaToT** [comment]
When i Open JSQMessageView Ctr first time, then it Scroll infinite, But when i open keyboard then That issue doesn't have it more.
I have checked for this solution everywhere in opened Bug/ closed bug but don't get it.

![screen shot 2017-06-26 at 4 44 09 pm](https://user-images.githubusercontent.com/29482904/27536876-bab52476-5a8e-11e7-9f9e-33d01eee00a1.png)

This is the Screenshot that depict my Problem.

**Comment by MacMeDan** [comment]
How are you introducing this screen. IE Programmatically or Storyboard. Do you have it nested in a `UINavigationController` and would you provide the code snipbit that does that. It will help in addressing this issue.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
