### ISSUE TITLE
change color cellBottomLabel

### ISSUE THREAD

**Issue by amirch123** [jessesquires/JSQMessagesViewController#2144]
![simulator screen shot jun 27 2017 11 34 21 am](https://user-images.githubusercontent.com/25988633/27574828-066d2bd6-5b2d-11e7-98f1-2a65818eee97.png)

hello
i need to change color cellBottomLabel in swift(example)
plz help me
tnx

**Comment by pig12301230** [comment]
using this?
```
 cell.cellBottomLabel.backgroundColor = UIColor.red
```

**Comment by amirch123** [comment]
@pig12301230 tnx so mutch
