### ISSUE TITLE
chat bubbles are only on the left aligned

### ISSUE THREAD

**Issue by ghost** [jessesquires/JSQMessagesViewController#2146]
incoming and outgoing messages are felt aligned

**Comment by acjh** [comment]
How did you setup your incoming and outgoing bubbles?

**Comment by Christoffer-Woost** [comment]
I used the factory method like this 

`outgoingBubble = JSQMessagesBubbleImageFactory().outgoingMessagesBubbleImage(with: .jsq_messageBubbleBlue())
        incomingBubble = JSQMessagesBubbleImageFactory().incomingMessagesBubbleImage(with: .lightGray)`

and return them in messageBubbleImageDataForItemAt depending on the user who sent it

**Comment by acjh** [comment]
Did you set `senderId` correctly?

**Comment by Christoffer-Woost** [comment]
I think there is the problem, I set the senderId with a string and a line later senderId is an optional string

**Comment by acjh** [comment]
But is it `nil`?

**Comment by Christoffer-Woost** [comment]
no

**Comment by Christoffer-Woost** [comment]
solved it, it was a mismatch wit an optional integer
