### ISSUE TITLE
New UIlabel in bottom of JSQMessagesViewController.xib doesn't display

### ISSUE THREAD

**Issue by marcuschoong** [jessesquires/JSQMessagesViewController#2147]
## General information

- `JSQMessagesViewController` version:
- iOS version: iOS 10.1.1
- Devices/Simulators: iphone6s
- Reproducible in the demo project? (Yes/No): Yes
- Any related issues:

## What happened?
I'm try to add a new uilabel in bottom of JSQMessagesViewController.xib eg "Welcome" but its doesn't appear in the chat screen. May i know whether i missing anything?

Please help.

**Comment by Lucashuang0802** [comment]
@marcuschoong, please include sufficient information so that we could be helpful. 😃

**Comment by marcuschoong** [comment]
<img width="246" alt="screen shot 2017-07-03 at 9 34 57 am" src="https://user-images.githubusercontent.com/26889594/27775276-343c15fe-5fd3-11e7-84de-d0c114f65a31.png">

Hi, i added a uilabel on JSQMessageViewController.xib as per attached above and didn't change/add anything on coding. when run on the simulator/device its doesn't appear the uilabel, screen shot like the following.

<img width="371" alt="screen shot 2017-07-03 at 9 36 08 am" src="https://user-images.githubusercontent.com/26889594/27775311-76ac00de-5fd3-11e7-84e1-27faf0bbd3cb.png">

Do i need to add anything on coding in order to display the uilabel?

**Comment by Lucashuang0802** [comment]
@marcuschoong have you tried view debugging to check if it is being added or it is a layout tweak due to constraint issue to cause 0 on width/height?

**Comment by marcuschoong** [comment]
@Lucashuang0802 thanks for your suggestion. i'm able to display the uilabel by add in new constraint to the uilabel, but it will auto navigate when the screen is load.

following is the initial screen.
![welcome](https://user-images.githubusercontent.com/26889594/27846445-fe610410-6169-11e7-90b7-3397dcd339d8.png)

following is the screen after 2 second. the InputToolBar will auto navigate to cover the uilabel i added.
![autonav](https://user-images.githubusercontent.com/26889594/27846453-080d915e-616a-11e7-8608-1d2b9b043778.png)

do you have any idea?

**Comment by marcuschoong** [comment]
problem solve by setting JSQMessagesViewController.heightFromBottom

**Comment by Lucashuang0802** [comment]
@marcuschoong thanks for confirming.
