### ISSUE TITLE
Tag User and Reply Message

### ISSUE THREAD

**Issue by pabloruan0710** [jessesquires/JSQMessagesViewController#2149]
This Library have support for tag user and Replay message equal Whatsapp?

![replay](https://user-images.githubusercontent.com/8368140/27749286-57269bba-5da9-11e7-9efb-53f2149ce7ec.jpg)

And Tag user

![tag](https://user-images.githubusercontent.com/8368140/27749349-a16e7a08-5da9-11e7-9415-eb92c4ea0590.jpg)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
