### ISSUE TITLE
Inputtoolbar is represent in whole screen (iPad)

### ISSUE THREAD

**Issue by PGandhi30** [jessesquires/JSQMessagesViewController#2151]
- `JSQMessagesViewController` version:
- iOS version: 9.3
- Devices/Simulators: Simulators (iPad Pro)
- Reproducible in the demo project? (Yes/No): YES
- Any related issues: inPuttoolbar

I had createad new viewController and i added DemoMessagesViewController

 (In given Example) as a childcontroller in new viewController.

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    DemoMessagesViewController *demo = [[UIStoryboard storyboardWithName:@"Main" bundle:nil]instantiateViewControllerWithIdentifier:@"DemoVC"];

    UINavigationController *navController = [[UINavigationController alloc]initWithRootViewController:demo];
    
    navController.navigationBarHidden = YES;
    CGRect frame = self.view.frame;
    frame.origin.x = 500;
    frame.size.width = [UIScreen mainScreen].bounds.size.width - 500;
    navController.view.frame = frame;
    self.view.backgroundColor = [UIColor blueColor];
       
    [self.view addSubview:navController.view];
}

input toolbar is display fit to screen. see the below image.

![simulator screen shot jul 3 2017 4 41 52 pm](https://user-images.githubusercontent.com/29861353/27792832-202372a6-6019-11e7-9e59-721b4de2420e.png)

What the solution for inputtoolbar fit in dynamic frame of viewController?

**Comment by hammy-dev-world** [comment]
I am facing the same issue, has anyone found the workaround?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
