### ISSUE TITLE
JSQMessagecontroller Memory issue

### ISSUE THREAD

**Issue by bhoomesh950** [jessesquires/JSQMessagesViewController#2154]
## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?
i have installed jsqmessageViewController through pod . it is a good framework but i have found some memory issues .
1.if i open the jsqChatViewcontroller it increasing the memory ( ex : 2mb ) ( two text messages and 2 images ) and again  i pop the jsqchatviewcontroller the issues is, that previously allocated memory is not deallocating. if i open the JSQchatviewviewController it again allocates 2mb if i come back (pop the JSQChatviewcontroler)  it not delloc the previous one. if i open the jsqChatViewcontroller 10 times it allocates 10*2 =20Mb of memory it it was not deallocating it continuously increasing  until i suspend the app. the same thing happening your github demo build also. thanks in advance .
![12](https://user-images.githubusercontent.com/20543788/28006423-dafcafe0-656c-11e7-90a4-002e9191466b.png)
it is from instruments
![233](https://user-images.githubusercontent.com/20543788/28006436-eb55a6c6-656c-11e7-8697-fd8a0a8cd307.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
