### ISSUE TITLE
Is JSQMessanger stil maintained?  When the version 8 become stable?

### ISSUE THREAD

**Issue by expertalex** [jessesquires/JSQMessagesViewController#2156]
After 1 year monitoring and using JSQMessenger i realize that this project is not actively maintained. 
It is true? If so inform to the user. If not why there are so drastic difference in time between commits.

Regards

**Comment by BasanthVerma** [comment]
I had the same question. Following..

**Comment by BasanthVerma** [comment]
I think we should close this and follow https://github.com/jessesquires/JSQMessagesViewController/issues/1336

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
