### ISSUE TITLE
Share/Forward Media Message 

### ISSUE THREAD

**Issue by haroonalpha** [jessesquires/JSQMessagesViewController#2157]
i have google it alot? my question is there any feature of picture/ video sharing (forwarding to others). i have gone through the sample and i ses 'accessry button' beside any media message which should be enabled through setting. this can be share button? if yes! then how? 
how can i implement?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
