### ISSUE TITLE
Absolute Kudos!

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#2158]
Jesse you are a class act, and thank you for ALL the effort you have freely offered over the years. I for one, while quiet, will miss you. The library helped me, and while my first app has yet to take off as hoped, one day it may. When that happens, i will look you up and offer financial compensation.

drew..

**Comment by Daltron** [comment]
Jesse, you have indeed been a huge help and inspiration to the iOS open source community. Not only did you create the most widely successful UI library used in iOS, but you improved, maintained, and commented on about all issues that users had for nearly 4 years. That is an absolutely DAUNTING task and I completely understand your reasoning for finally waving the white flag. So for all of us who have learned something from this library and will continue to learn from it, THANK YOU!  I wish the best of luck to you with your future endeavors! 🎉 🎉 🎉

**Comment by jessesquires** [comment]
@wdcurry @Daltron 

Thank you both so much 😊 Means a lot.

![](https://media.giphy.com/media/kc5vzGoqdct5C/giphy-downsized.gif)

**Comment by freak4pc** [comment]
@jessesquires Good luck with your future endeavors and other passions and projects you have :) 
I think anyone that is developing iOS applications for over 5-6 years now was at some point dependent on your library. JSQMessageViewController is a pure example of how OSS benefits developers and developer communities from rewriting and reinventing the wheel, and the impact it had early on (and probably through this day) is definitely something to be proud of. 

All the luck and happiness with anything you do :)

Good luck! 💯 🎉

**Comment by bhartsb** [comment]
Thank you for the Library Jesse!  It is a cornerstone of my app Pindragon.  I'm just about to finally release it.   Good luck with whatever comes next.

**Comment by SD10** [comment]
Thank you for all the time and energy you've selflessly devoted to this project 👍. Maintaining a large open source project over the course of half a decade is no easy feat and your dedication is respected greatly. Thank you for being an inspiration to me as a developer 😃

**Comment by jessesquires** [comment]
Thanks again everyone! ❤️ Your kind words mean a lot.

![](https://media.giphy.com/media/100QWMdxQJzQC4/giphy-downsized.gif)
