### ISSUE TITLE
Hi,when i use longpress active the UIMenuController,the avatar in the cell become dark with the cell.how could make the bubble dark only? thanks

### ISSUE THREAD

**Issue by zhuyuqiu** [jessesquires/JSQMessagesViewController#2162]
## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by Saruul-Ulzii** [comment]
Hello, at first, this library has depreciated. No longer support, helps and issue tracks. Just we can find from issues, i am using it anyway, searching from all issues and stackoverflow.
