### ISSUE TITLE
Set Content Mode for Imageview in Media Item

### ISSUE THREAD

**Issue by DevCSI** [jessesquires/JSQMessagesViewController#2164]
I have some Small images like stickers coming from API and has issue on it while loading into Image View, it get stretched so need Solution for it..  How to set Content mode of Image view ?

I have attached 2 images one is how images looks in Website and another is how same image looks in JSQ in iPhone
![screen shot 2017-08-18 at 11 41 34 am](https://user-images.githubusercontent.com/31122908/29446581-9076a48c-840a-11e7-877f-2891031e1600.png)
![screen shot 2017-08-18 at 11 42 33 am](https://user-images.githubusercontent.com/31122908/29446582-90c69488-840a-11e7-8807-f67f21c987d0.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
