### ISSUE TITLE
How to set borderColor with custom JSQPhotoMediaItem

### ISSUE THREAD

**Issue by MrCoderMSH** [jessesquires/JSQMessagesViewController#2165]
![simulator screen shot 2017 8 18 5 43 11](https://user-images.githubusercontent.com/13232963/29453590-bc98725c-843c-11e7-9136-4f806fb51faa.png)

`import Foundation
import AlamofireImage

class AsyncPhotoMediaItem: JSQPhotoMediaItem {
    var asyncImageView: UIImageView!
    var url : URL?

    override init!(maskAsOutgoing: Bool) {
        super.init(maskAsOutgoing: maskAsOutgoing)
    }

    init(withURL url: URL? = nil, isGoing: Bool) {
        super.init()
        appliesMediaViewMaskAsOutgoing = true

        self.url = url

        asyncImageView = UIImageView()
        asyncImageView.frame.size = mediaViewDisplaySize()
        asyncImageView.contentMode = .scaleAspectFill
        asyncImageView.clipsToBounds = true
        asyncImageView.backgroundColor = UIColor.jsq_messageBubbleLightGray()

        let factory = JSQMessagesBubbleImageFactory()
        if isGoing {
            JSQMessagesMediaViewBubbleImageMasker(bubbleImageFactory: factory).applyOutgoingBubbleImageMask(toMediaView: asyncImageView)
        } else {
            JSQMessagesMediaViewBubbleImageMasker(bubbleImageFactory: factory).applyIncomingBubbleImageMask(toMediaView: asyncImageView)
        }

        asyncImageView.image = #imageLiteral(resourceName: "discuss_placeholder_image")

        if let url = url {
            asyncImageView.af_setImage(withURL: url)
        }
    }

    override func mediaView() -> UIView! {
        return asyncImageView
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func loadUrl(_ tempUrl: URL?) {
        url = tempUrl
        if (url != nil) {
            asyncImageView.af_setImage(withURL: url!)
        }
    }
}`

Now, I'm using that mehtod to load image with url, but , when the picture fill of white color, user can't find the picture's layers, I wan't in this custom JSQPhotoMediaItem make a layer with colorful messageBubble, so I want to konw how to resolve this problem. thak you~

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
