### ISSUE TITLE
 appliesMediaViewMaskAsOutgoing align image 

### ISSUE THREAD

**Issue by ahmedAlmasri** [jessesquires/JSQMessagesViewController#2166]
- `JSQMessagesViewController` version: 7.3.5
- iOS version: 10.3
- Devices/Simulators: Devices and  Simulators
- Reproducible in the demo project? (Yes/No):  NO
- Any related issues:

## What happened?

set appliesMediaViewMaskAsOutgoing  true or file image align right 

![simulator screen shot aug 25 2017 10 33 03 pm](https://user-images.githubusercontent.com/14888785/29729759-2f86a33e-89e6-11e7-9bbd-e5270c7b5f24.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
