### ISSUE TITLE
Forward command to menu shown when long press on a cell

### ISSUE THREAD

**Issue by vinayTree** [jessesquires/JSQMessagesViewController#2168]
## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?
I need add forward commands to menu shown when long press on a cell. I tried many ways but i don't know how to add it can anyone help me with forward option in menu, where i want to forward text message like copy and delete.

**Comment by vinayTree** [comment]
hi i got solution for it sorry if i have taken your time

**Comment by ghost** [comment]
Could you please ellaborate on your solution
