### ISSUE TITLE
 JSQMessagesComposerTextView was deallocated while key value observers were still registered with it

### ISSUE THREAD

**Issue by hiren1995** [jessesquires/JSQMessagesViewController#2170]
I have an error while loading messages:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x15ec64600 of class JSQMessagesComposerTextView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x15dee6a30> (
<NSKeyValueObservance 0x15f628f20: Observer: 0x162e46a00, Key path: contentSize, Options: <New: YES, Old: YES, Prior: NO> Context: 0x1002bfa10, Property: 0x15ddcc350>
)'

can anyone know whats the reason?

**Comment by svtechnology** [comment]
I don't think you are going to receive an answer here. This project is deprecated and I would recommend you use a different framework (Chatto or MessageKit).

**Comment by ulaserdegor** [comment]
@hiren1995 hi.  Did you solve the problem?

**Comment by hiren1995** [comment]
@ulaserdegor yup I solved that...
this error occurred when I was trying for notification observers...
I simply added the remove observer method to viewDidAppear

**Comment by ulaserdegor** [comment]
@hiren1995 oh greate! but what is observer method ?

**Comment by hiren1995** [comment]
@ulaserdegor  NSNotification observer class is used for live chat means when you send some message and the person replies you you get an notification for that and in appDelegate we create a local notification and  in viewDidLoad of our chat screen we use addNotification observer and catch that notification and in the body of that notification we get the message send by the other person so we append that message to message array of JSQMessages and reload the collection view so that we see that message in our chat screen...this way live chat is achieved
