### ISSUE TITLE
Crash on iOS 10 when built with Xcode 9

### ISSUE THREAD

**Issue by acrookston** [jessesquires/JSQMessagesViewController#2176]
## New issue checklist

- [x] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: 💪😎👊
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.5
- Xcode version: 9.0.1
- iOS version: 10.x
- Devices/Simulators: Simulator 10.3.1
- Reproducible in the demo project? (Yes/No): Yes
- Any related issues: No

## What happened?

We're seeing a crash that appeared originally in 7.2.0 and subsequently in 7.3.5 when the application (and library) was built with Xcode 9. Affecting users on iOS 10 the app would crash when a user tries to paste something into the input field.

When opening the project, Xcode 9 produced a warning message about synthesizing the `pasteDelegate` and the example project would crash when run on iOS 10 simulator via Xcode 9.

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18c3751b8 __exceptionPreprocess
1  libobjc.A.dylib                0x18adac55c objc_exception_throw
2  CoreFoundation                 0x18c37c268 __methodDescriptionForSelector
3  CoreFoundation                 0x18c379270 ___forwarding___
4  CoreFoundation                 0x18c27280c _CF_forwarding_prep_0
5  [APPLICATION]                   0x10062c51c -[JSQMessagesComposerTextView paste:] (JSQMessagesComposerTextView.m:161)
6  UIKit                          0x19283074c -[UICalloutBar buttonPressed:]
7  UIKit                          0x19282fa80 -[UICalloutBarButton fadeAndSendAction]
8  Foundation                     0x18ce7246c __NSFireDelayedPerform
9  CoreFoundation                 0x18c3231d8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
10 CoreFoundation                 0x18c322eec __CFRunLoopDoTimer
11 CoreFoundation                 0x18c3227a8 __CFRunLoopDoTimers
12 CoreFoundation                 0x18c3203a4 __CFRunLoopRun
13 CoreFoundation                 0x18c24e2b8 CFRunLoopRunSpecific
14 GraphicsServices               0x18dd02198 GSEventRunModal
15 UIKit                          0x1922957fc -[UIApplication _run]
16 UIKit                          0x192290534 UIApplicationMain
17 [APPLICATION]                   0x10014e180 main (main.m:13)
18 libdispatch.dylib              0x18b2315b8 (Missing)
```

I have a fix which will resolve this issue immediately.

cc @chrisballinger (was told by Jessie to include you)

**Comment by chrisballinger** [comment]
Thanks! I'm maintaining this repo for "critical bug fixes only" and this definitely qualifies. I imagine there will be a flood of complaints for iPhone X constraints issues pretty soon, which I haven't really looked into yet. 

Would appreciate any PRs that address major iPhone X issues. The network graph is too large to see what others are doing so I think it's helpful to still accept certain PRs even if this library won't see another tagged release.
