### ISSUE TITLE
there is some distance between toolbar and keyboard!

### ISSUE THREAD

**Issue by YaoJuan** [jessesquires/JSQMessagesViewController#2181]
## General information

- `JSQMessagesViewController` version:
- iOS version: iOS11
- Devices/Simulators: both of them
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

## What happened?
when i ran my apps and make toolbar become first response.there is some distance between toolbar and keyboard!
![bug](https://user-images.githubusercontent.com/16183272/32602121-913ee3f2-c50a-11e7-8fdc-9db337f41fdc.png)

**Comment by chrisballinger** [comment]
This library is unsupported, please look into alternatives like [MessageKit](https://github.com/MessageKit/MessageKit). Thank you!
