### ISSUE TITLE
textView contentOffset after paste

### ISSUE THREAD

**Issue by Liqiankun** [jessesquires/JSQMessagesViewController#2182]
## General information

- `JSQMessagesViewController` version: develop(7.3.5)
- iOS version: IOS 11
- Devices/Simulators: iPhone 8
- Reproducible in the demo project? (Yes/No): YES

## What happened?
![simulator screen shot - iphone 8 - 2017-11-29 at 18 52 49](https://user-images.githubusercontent.com/11532418/33371905-d03695fc-d4c1-11e7-9723-775167b11553.png)

## What should happen?
![simulator screen shot - iphone 8 - 2017-11-29 at 19 02 31](https://user-images.githubusercontent.com/11532418/33372144-92705888-d4c2-11e7-95d2-946b3e6f8463.png)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
