### ISSUE TITLE
Crash when paste in swift example project

### ISSUE THREAD

**Issue by daicatrungisme1** [jessesquires/JSQMessagesViewController#2185]
## General information

- `JSQMessagesViewController` version: develop 7.3.5
- iOS version:10.0.3
- Devices/Simulators: iphone 6s
- Reproducible in the demo project? (Yes/No): No

## What happened?

when i click copy and paste in chat swift example  app crash log:
2017-12-14 15:31:40.730319+0700 SwiftExample[1971:525528] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[JSQMessagesComposerTextView pasteDelegate]: unrecognized selector sent to instance 0x1580a2400'
![image](https://user-images.githubusercontent.com/32670658/33983594-4fb2a0ba-e0e7-11e7-9a1a-f5161292d93e.png)

**Comment by adematalay** [comment]
Take a look to MR #2187

**Comment by RinatYahin** [comment]
Hey guys!
I understand that library is deprecated, but is it possible to merge changes and make a new release?
Thanks in advance.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
