### ISSUE TITLE
Manual Localisation

### ISSUE THREAD

**Issue by GodriXx** [jessesquires/JSQMessagesViewController#2188]
## New issue checklist

- [ ✓] I understand that this library is ⚠️ [deprecated](https://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/) ⚠️ and is **only** accepting pull requests for critical bug fixes.
- [ ✓] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md)
- [ ✓] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.5
- iOS version: 9.0 ++
- Devices/Simulators: Both 
- Reproducible in the demo project? (Yes/o): 
- Any related issues: No

## What happened?

Hello everyone, and thank you for this wonderful library, sadly it's deprecated,

I don't have an issue with JSQ, it's working perfectly, actually, I'm fixing bugs on an existing old app that uses JSQ, my issue is that I would like to manually change JSQ's language, as the app got it's own language setting, the whole is translated except for JSQ,

I know that JSQ change language automatically depending on system language, but I would like to apply my own localisation to it,

I managed to change JSQ language with setAccessibilityLanguage, this made some interface changes to the right language, but didn't translate date on conversation views, 

So, is there any way to make JSQ localisation follow app language ? 

Thank you

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
