### ISSUE TITLE
How to Display Multiple media sending upload proceed using jsqmessage view controller?

### ISSUE THREAD

**Issue by shraddha-patel-1891** [jessesquires/JSQMessagesViewController#2192]
Hello,

I am making chat app using XMPP and JSQ message view controller.Now I am sending multiple media like first send video and at that time of uploading process of a video, I am sending image than video upload process label hide an image upload process label display.so how can I display both media process(video and image)like chat secure app?

anyone have a solution then please help me.

thank you.

**Comment by Nurka11** [comment]
@shraddha-patel-1891 Have you solved this problem?

**Comment by shraddha-patel-1891** [comment]
@Nurka11 
No have not got any solution you have then please share.

**Comment by Nurka11** [comment]
@shraddha-patel-1891 
`class JSQCustomMessage: JSQMessage {
    
    var mediaItems: [JSQMessageMediaData] = []
    
    init(senderId: String, senderDisplayedName: String, mediaItems: [JSQMessageMediaData]) {
        
        let data = NSMutableData()
        let archiver = NSKeyedArchiver(forWritingWith: data)
        archiver.finishEncoding()
        let coder = NSKeyedUnarchiver(forReadingWith: data as Data)
        
        super.init(coder: coder)!
        
        self.mediaItems = mediaItems
        
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    var mediaItemsFor: [JSQMessageMediaData] {
        return mediaItems
    }
    
    override var isMediaMessage: Bool {
        return true
    }
    
}
` maybe something like this
