### ISSUE TITLE
How to add image of message read or not like whats app?

### ISSUE THREAD

**Issue by shraddha-patel-1891** [jessesquires/JSQMessagesViewController#2200]
Hello,
we are making chat application and now required to add message read and unread image like whats app.
we tried may solution but not working any one.
so anyone has an idea for add image for message status then please help me.
Thank you.

**Comment by HardikKardani** [comment]
You need to add custom image in JSQMessagesCollectionViewCellOutgoing view. after that once you get status of the message you need to refresh image in JSQMessageViewController.

**Comment by shraddha-patel-1891** [comment]
@hardik 
I added but now bottom label time and read unread message image add in a chat bubble.so any idea about this?

**Comment by HardikKardani** [comment]
@shraddha-patel-1891 

Yes you need to make change in bubble size calculation method and need to do some changes in .xib file. 

review my attached image.
![img_1216](https://user-images.githubusercontent.com/10094783/45688954-5add8b80-bb70-11e8-891a-295b064ccdd5.jpg)

**Comment by shraddha-patel-1891** [comment]
@HardikKardani 
i tried a change in .xib file but app crash 
so please help me for that.for bubble size calculation changes apply in which file?
