### ISSUE TITLE
Pre Populate TextView

### ISSUE THREAD

**Issue by justdan0227** [jessesquires/JSQMessagesViewController#2204]
How do you pre populate the textview when the view first loads.  I want to save any text that was in the field and then restore it when they return to the view?

**Comment by LilMoke** [comment]
Hello, did you ever find out how to do this?  Thanks for any help!!

**Comment by LilMoke** [comment]
I know this is deprecated but I need to update our app until we find a replacement for JSQ.

I saw a post and it said that after version 4 or 5 I should be able to set the textView and then do the following:

NotificationCenter.default.post(name: UITextView.textDidChangeNotification, object: self.inputToolbar.contentView.textView)

to have the textView resize with the new text.  However, that call does not seem to work.  I was hoping you could just tell me how to set the text and re-size the view so it shows correctly.

Any help would be appreciated.

Best,
Tony



On May 29, 2019, at 1:40 PM, Jesse Squires <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2204<https://github.com/jessesquires/JSQMessagesViewController/issues/2204>.
