### ISSUE TITLE
Edit mode: deleting / selecting messages in bulk

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#235]
Edit mode: deleting / selecting messages in bulk

**Comment by Marindrew** [comment]
@jessesquires are you planning to implement this feature?
I am currently trying to implement it, do you have any ideas on what would be the most efficient way to do so?

Thank you so much for the library!

**Comment by boardmaster357** [comment]
Any update on this feature?  Is there any easy way to add swipe to delete to the current library?

**Comment by chintan100** [comment]
Any update on Edit Mode for multiple selection and deletion yet?

**Comment by svtechnology** [comment]
This will be an awesome feature to have. I know we would like to keep the library minimal but bulk selection (including media items) should be a part of it.

**Comment by skeeet** [comment]
Here is my attempt to implement it.

**Comment by ignacio-chiazzo** [comment]
Is there an update of this issue?

**Comment by skeeet** [comment]
@ignacio-chiazzo I've moved away from JSQMessagesViewController to in-house built component and have no plans to put more effort into it.

**Comment by ignacio-chiazzo** [comment]
@skeeet What a pity, could you share a solution to this, or share your fork of this repo to the public?

**Comment by skeeet** [comment]
@ignacio-chiazzo pull request above (#1593) contains all info you need.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
