### ISSUE TITLE
Infinite scrolling / pagination

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#236]
Infinite scrolling / pagination

**Comment by kartikthapar** [comment]
It seems like this requires a more application specific implementation depending on the kind of data model you are using. However a primary API to just call for add more messages when 'previous' messages are ready would be nice.

**Comment by wdcurry** [comment]
In my mind, it is simpler than that: simply fire off an event and let us handle it all, just as it is now, with the "load earlier messages" event. We can already manage it on our own, we simply need to hook from the UI, and this requires no knowledge of implementation. As now, we are responsible for hiding the control/event if required.

**Comment by kartikthapar** [comment]
So as far as I understand, it's a simple `UIScrollViewDelegate§` event right? My concern was more about how people would like to have infinite scrolling implemented – `UIScrollViewDelegate`, pull to refresh, etc. It just feels like a developer specific implementation but so can be said about a few other things available in the framework; so I guess its ok. : grimacing:

**Comment by wdcurry** [comment]
"pull to refresh" is an unfortunate carry-over from the early moment of the event's inception. It makes sense in a certain subset of use-cases for sure, but not all. ;) .. Even something akin to "ViewPull" is more apt. Regarding the library, it just makes sense to give this the scope that the current Load Earlier behaviour has. Something we can activate and deactivate from the same scope level given its' nature.

**Comment by kartikthapar** [comment]
Hmm makes sense.

**Comment by jessesquires** [comment]
Decision:

After some thought, I've determined that this is very client-specific and beyond the scope of this library.

**Comment by darrarski** [comment]
Just FYI, if you still looking for solution that allows pagination, check out my open source project:
https://github.com/darrarski/Messages-iOS
Perhaps it will help you implementing it.
