### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#237]
Things that need to be localized:
- "Send" button
- "Load earlier messages" button
- "New Message" placeholder text

**Comment by qaysdwekat** [comment]
Dutch
"Send" = "إرسال"
"Load earlier messages" = "تحميل الرسائل السابقة"
"New Message" = "رسالة جديدة"

**Comment by jessesquires** [comment]
Thanks @qaysdwekat !

Would you mind opening a new issue for the Arabic translation, or submitting a PR? :smile:

**Comment by chanil1218** [comment]
Korean
"Send" = "전송"
"Load earlier messages" = "이전 메시지 불러오기"
"New Message" = "새로운 메시지"

**Comment by harlanhaskins** [comment]
Making a PR for this now

**Comment by saltwat5r** [comment]
In Polish I think that

`"Load earlier messages" = “Wcześniejsze wiadomości”;`

would sound better ;)

> It sound very technocratic…
> 
> "Load earlier messages" = “Otwórz wcześniejsze wiadomości”;
> 
> or
> 
> "Load earlier messages" = “Pobierz wcześniejsze wiadomości”;
> 
> sounds a bit nicer in my opinion.

**Comment by bfricho** [comment]
Slovak:

"New Message" = "Nová správa"
"Send" =  "Odoslať"

Thx 👍🏻

**Comment by jessesquires** [comment]
### For anyone just now finding this thread — if you want to add a new language, please submit a PR.
