### ISSUE TITLE
Scroll to bottom fails until contentSize is at least a certain height

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#256]
1. begin with empty view
2. send 1-line messages
3. messages don't auto-scroll once they reach input toolbar
4. after a few more messages, collectionView scrolls appropriately

**Comment by alexeyhippie** [comment]
Hey guys, 

Current solution seems to not working for me - it still not scroll it to bottom when messages reach it.
How to reproduce on Demo:
1) set empty view. 
2) add messages one by one (I added a button on view for that with method):
```
 - (IBAction)receiveFakeTapped:(UIButton *)sender {
    NSMutableArray *userIds = [[self.demoData.users allKeys] mutableCopy];
    [userIds removeObject:self.senderId];
    NSString *randomUserId = userIds[arc4random_uniform((int)[userIds count])];
    
    NSArray *textes = @[@"Short one",
                        @"A bit longer one, two lines on i5s",
                        @"3 lines text on iPhone 5S - takes three lines of some text"
                        ];
    
    JSQMessage *newMessage = [JSQMessage messageWithSenderId:randomUserId
                                                 displayName:self.demoData.users[randomUserId]
                                                        text:textes[arc4random_uniform((int)[textes count])]];
    
    [self.demoData.messages addObject:newMessage];
    [self finishReceivingMessageAnimated:YES];
}
```
 3) See how it goes under input view and further. 

Sorces version 7.3.3 (cloned from develop branch)
Xcode 7.3.1
Tested on 
- iPhone 5s Simulator iOS9.3
- iPhone 6s Simulator iOS9.3, 
- iPhone 6 Simulator iOS8.4,
- iPhone 5s iOS 9.3

**Comment by alexeyhippie** [comment]
so solution I found is calculate actual content offset until UIKit is able to scroll it by itself. Some kind of mix of @jessesquires original fix and @dereck009 current solution. 

In a `- (void)scrollToIndexPath:(NSIndexPath *)indexPath animated:(BOOL)animated`method of JSQMessagesViewController
    
    CGFloat collectionViewContentHeight = [self.collectionView.collectionViewLayout collectionViewContentSize].height;
    CGFloat collectionViewHeight = CGRectGetHeight(self.collectionView.bounds);
    BOOL isContentTooSmall = (collectionViewContentHeight < collectionViewHeight + 10.f);

    if (isContentTooSmall) {
        //  workaround for the first few messages not scrolling
        //  when the collection view content size is too small, `scrollToItemAtIndexPath:` doesn't work properly
        //  this seems to be a UIKit bug, see #256 on GitHub

        CGFloat contentWindow = collectionViewHeight - self.collectionView.contentInset.top - self.collectionView.contentInset.bottom - self.topContentAdditionalInset;
        CGFloat offsetH = MAX(0.f, collectionViewContentHeight - contentWindow) - self.collectionView.contentInset.top - self.topContentAdditionalInset;
        [self.collectionView setContentOffset:CGPointMake(0.f, offsetH) animated:YES];
        
        return;
    }
    
See also that I extended ContentTooSmall zone by 10 points:
`BOOL isContentTooSmall = (collectionViewContentHeight < collectionViewHeight + 10.f);`
For some reasons sometimes (but quite often on these test messages) when there appears first message that is out of ContentTooSmall zone and goes further to `scrollToItemAtIndexPath:` method, it scrolls to top.

**Comment by jessesquires** [comment]
@alexeyhippie - want to submit a PR?

**Comment by tunidev** [comment]
@jessesquires the bug still exist in 7.3.4, just use the demo project and in the demo conversation just `conversation = [message6, message7, message8, message]` last message is text with one line, just to be able to add new messages line by line and the collection view will not scroll while receiving the first two messages outside the screen, it scroll only with the third message. and @alexeyhippie code seems the fix the issue

**Comment by patniemeyer** [comment]
As a workaround I have added a value observer on the collection view's contentSize property and use it to invoke scrollToBottomAnimated after it has been updated.  This seems to solve the problem.

**Comment by Slessi** [comment]
Overriding `scrollToIndexPath:animated:` to this fixes it for me. (Basically always using the existing fix without making any checks)

```objective-c
- (void)scrollToIndexPath:(NSIndexPath *)indexPath animated:(BOOL)animated
{
    if ([self.collectionView numberOfSections] <= indexPath.section) {
        return;
    }

    if ([self.collectionView numberOfItemsInSection:indexPath.section] == 0) {
        return;
    }

    CGFloat collectionViewContentHeight = [self.collectionView.collectionViewLayout collectionViewContentSize].height;

    [self.collectionView scrollRectToVisible:CGRectMake(0.0, collectionViewContentHeight - 1.0f, 1.0f, 1.0f)
                                    animated:animated];
}

```

**Comment by tamoyal** [comment]
This issue also still exists for me. Any chance we can get it reopened?
