### ISSUE TITLE
Message send to deallocated instance (jsq_handleInteractivePopGestureRecognizer:)

### ISSUE THREAD

**Issue by cswelin** [jessesquires/JSQMessagesViewController#257]
Great job thus far on the recent changes, everything seems to be coming together nicely.

When a JSQMessagesViewController is further in the navigation controller hierarchy example:
```
JSQMessagesViewController
UIViewController
UIViewTableViewcontrlller
UINavigationController
```

if you swipe back to pop off the MessagesController, then swipe back on more time to pop off the UIViewController a crash will occur:

``*** -[JSQDemoViewController jsq_handleInteractivePopGestureRecognizer:]: message sent to deallocated instance 0x92f1990```

from my investigation. the function

```
- (void)jsq_addActionToInteractivePopGestureRecognizer:(BOOL)addAction
{
    if (self.navigationController.interactivePopGestureRecognizer) {
        [self.navigationController.interactivePopGestureRecognizer removeTarget:nil
                                                                         action:@selector(jsq_handleInteractivePopGestureRecognizer:)];
        
        if (addAction) {
            [self.navigationController.interactivePopGestureRecognizer addTarget:self
                                                                          action:@selector(jsq_handleInteractivePopGestureRecognizer:)];
        }
    }
}
```
when called from the viewDidDisappear doesn't actually remove the target action as the navigationController is nil by this point.

The demo app works fine, since popping and pushing a messages controller will remove the old instance then readd.

To replicate add a intermediate view controller after UITableVIewController.

**Comment by jessesquires** [comment]
@realsurfer - maybe this is an issue with retaining/releasing your view controllers?

**Comment by realsurfer** [comment]
Hi, how would I go about testing this? Isn't the swipe functionality just built in behavior of the navigation controller? Clicking the back button does not crash the app.
Thanks!

**Comment by jessesquires** [comment]
@realsurfer - Which version of the library are you on?

Can you post a demo project that shows this?

**Comment by realsurfer** [comment]
@jessesquires sorry for the late reply. I am using 6.1.3 in my app right now. The issue seems to still exist. I will try and create some kind of demo. Otherwise, is there anyway I can debug this in my current app?

**Comment by jessesquires** [comment]
still can't repro this on develop. since no other users have reported this, going to re-close.

**Comment by realsurfer** [comment]
@jessesquires I will install the latest version and see if I can replicate this. I'll let you know!

**Comment by realsurfer** [comment]
This issue is still there in 7.0.1. I will try and create a demo.

**Comment by realsurfer** [comment]
I finally solved it. The mistake was on my end. I saw that jsq_addActionToInteractivePopGestureRecognizer wasn't being called on disappear.

I added [super viewWillDisappear:animated]; and now it works without crashing :)

Sorry for taking your time on this issue!

**Comment by brunogama** [comment]
I am having the same issue related when using the swipe gesture to call the RefrostedViewController component.
