### ISSUE TITLE
Landscape and Scrolling position

### ISSUE THREAD

**Issue by hohl** [jessesquires/JSQMessagesViewController#260]
Scrolling position is not correct when changing the devices orientation **while the keyboard is focused**.

**Comment by GianniCarlo** [comment]
The updated functions for handling rotation stuff from iOS 8+ are:
```objective-c
-(void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator{
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
    //do stuff before rotation, or save state of whatever
}

-(void)traitCollectionDidChange:(UITraitCollection *)previousTraitCollection{
    [super traitCollectionDidChange:previousTraitCollection];
    //rotation has finished
    //do custom stuff (e.g. set frame of custom navigation buttons, scroll collectionview)
}
```

You can check your current device orientation with `[[UIDevice currentDevice] orientation]`

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
