### ISSUE TITLE
Background color/image for JSQMessagesViewController

### ISSUE THREAD

**Issue by ghost** [jessesquires/JSQMessagesViewController#284]
Please add this feature.
changing of `setBackgroundColor:` in `jsq_configureCollectionView`
or adding `UIImageView` as subview has no effects.

**Comment by jaimeslr** [comment]
Hello jesse, the JSQPhotoMediaItem can be initialized with an UIImage but if the image is still not cached and you need to download it first which is the best approach? I have'nt found a method like initializeWithURL which would be great.

**Comment by jessesquires** [comment]
Had other questions about this. I realized the issue. See #727

**Comment by raghunath44** [comment]
i want to change the background colour of DemoMessageViewController.If i write self.view.backgroundcolor = [uicolor redcolor];  in viewDidLoad of DemoMessageViewController. its not working...

**Comment by eliburke** [comment]
@raghunath44 try this:
   `self.collectionView.backgroundColor = [UIColor redColor];`

You may want to learn about XCode's "Debug View Hierarchy" feature. It shows the layers of views, and would have revealed that your red background was covered up by the collection view.
