### ISSUE TITLE
Track keyboard frame from KeyboardController delegate

### ISSUE THREAD

**Issue by v-ken** [jessesquires/JSQMessagesViewController#287]
First off, thanks for this awesome project =)

Is there a way to track the keyboard frame?
There is this protocol `JSQMessagesKeyboardControllerDelegate` but it seems to be only used privately. I need to track the keyboard frames in order to animate my views accordingly.

Thanks!

**Comment by zwang** [comment]
@jessesquires  do you mind explaining how this works as your comment above? I tried to use this to solve the last problem (avoiding modify original source file to extend `JSQMessagesKeyboardControllerDelegate` behavior) I mentioned here: https://github.com/jessesquires/JSQMessagesViewController/issues/1351 

    @interface JSQMessagesViewController (MyPrivateExtension) <JSQMessagesKeyboardControllerDelegate>
    @end

Thank you.
