### ISSUE TITLE
RubyMotion Demo

### ISSUE THREAD

**Issue by robj** [jessesquires/JSQMessagesViewController#295]
I have created this demo for any RubyMotion developers interested in the project. (V5)

https://github.com/robj/jsqmtvc_motion

**Comment by elzggr** [comment]
Hi, @robj  the link seems to be broken.
Is there a new link for this project?

Thanks

**Comment by holgersindbaek** [comment]
@robj Hi Rob. I'm about to implement with Rubymotion as well. A demo project would be really nice. Do you have a lank to it that's not  broken?

**Comment by antoineherzog** [comment]
Hi!
@robj is it broken ?
Kind regards,
Antoine

**Comment by dgilperez** [comment]
+1

**Comment by eliduke** [comment]
Any word from @robj about a non-broken link? HALP!!
