### ISSUE TITLE
Avatar is always at left 

### ISSUE THREAD

**Issue by sharp** [jessesquires/JSQMessagesViewController#299]
Avatar is always at left even if the message is outgoing

**Comment by dethell** [comment]
In your viewDidLoad you need to set the senderId and senderDisplayName:

    self.senderId = whateverYourUniqueSenderIdIs
    self.senderDisplayName = whateverYourSenderDisplayNameIs

I have a variable in my AppDelegate that represents the current user so I just set the senderId to the currentUser.id.stringValue and the senderDisplayName to currentUser.firstName in the case of my model.
