### ISSUE TITLE
Change the collectionView frame in JSQMessageViewController subclass

### ISSUE THREAD

**Issue by mvalti** [jessesquires/JSQMessagesViewController#300]
Hi. 

I try to change the collectionView frame, but only in nib I could do it, with changing the vertical space constraint.  Can I make this work in a JSQMessageViewController subclass? In my app, the collectionView frame height must always be 250 px on top off the screen and do not respond for any keyboardFrame change.

**Comment by alexkrzyzanowski** [comment]
It looks like the third solution by @jessesquires is the best one.
