### ISSUE TITLE
Load earlier messages without scrolling

### ISSUE THREAD

**Issue by themire** [jessesquires/JSQMessagesViewController#307]
I've implemented the "Load earlier messages" button and it's working fine.

On receiving more messages from the server I'm calling `[self.collectionView reloadData];` whether it's the first or subsequent page. 

I'm wondering is there a way to prevent scrolling on loading the 2nd page, so that the messages are loaded above where you're currently viewing.

You would want some way of adding the messages to the collection without doing a full `reloadData` I'm guessing?

**Comment by federicocappelli** [comment]
Best solution if you use core data:
with NSNumber * _earlierMessagesLoaded;

```
#pragma mark - NSFetchedResultsController

- (void)controllerDidChangeContent:(NSFetchedResultsController *)controller
{
    if([_earlierMessagesLoaded integerValue]>0)
    {
        [self.collectionView scrollToItemAtIndexPath:[NSIndexPath indexPathForItem:[_earlierMessagesLoaded integerValue]-1 inSection:0] atScrollPosition:UICollectionViewScrollPositionTop animated:NO];
        _earlierMessagesLoaded = nil;
    }
    else
        [self finishReceivingMessageAnimated:NO];
}
```
