### ISSUE TITLE
How to disable / enable input and button for async messaging?

### ISSUE THREAD

**Issue by kenn** [jessesquires/JSQMessagesViewController#309]
When I send a message, I'd like to disable both input text and send button until the server responds ok. That way, if there was a network error, it's easy for the user to re-send the same content.

But if I set `self.inputToolbar.contentView.textView.editable = NO`, it will hide the keyboard. Is there a way to disable edit, but not hide the keyboard? Or is there a better way?

``` objc
- (void)didPressSendButton:(UIButton *)button
           withMessageText:(NSString *)text
                    sender:(NSString *)sender
                      date:(NSDate *)date
{
    // Disable the UI
    button.enabled = NO;
    self.inputToolbar.contentView.textView.editable = NO; // This will make it resign active

    // Build message
    Message *message = [Message new];
    message.text = text;
    ...

    [Message commit:message success:^{
        button.enabled = YES;
        self.inputToolbar.contentView.textView.editable = YES;

        [self.messages addObject:message];
        [self finishSendingMessage];
    } failure:^{
        [UIAlertView showAlertViewWithTitle:@"Error" message:@"Oops, failed to send the message. Please retry!"];
        button.enabled = YES;
        self.inputToolbar.contentView.textView.editable = YES;
    }];
}
```

**Comment by LucasAdam** [comment]
I am having this "issue" aswell. I like to disable the textview for editing until I get an OK(message sent) response from my backend. But doing so dismisses the keyboard and therefore brings an annoying experience. Any idea how I could achieve this ?

**Comment by gumbypp** [comment]
I found something that doesn't disable the textview, but it prevents the send button from being enabled while an async message is outstanding. Just override the following delegate method from JSQMessagesViewController (in Swift):

    override func textViewDidChange(_ textView: UITextView) {
        if (textView != self.inputToolbar.contentView.textView) {
            return
        }
        
        // set this flag while waiting for a response
        if (sendingMessage) {
            // never enable the send button while sending a previous message
            return
        }
        
        self.inputToolbar.toggleSendButtonEnabled()
    }
