### ISSUE TITLE
Scroll to bottom on initial load

### ISSUE THREAD

**Issue by kenn** [jessesquires/JSQMessagesViewController#310]
Is it possible to scroll to bottom on initial load, without visible motion?

If I put `scrollToBottomAnimated:NO` in `viewDidAppear`, first the top appeared then jumped to the bottom. If I put in `viewWillAppear` it did nothing.

**Comment by jackytwh** [comment]
Hi @kenn , though its a long-time-ago issue. May i know how did you solve the visible motion on init load finally?

**Comment by kenn** [comment]
It was a long time ago indeed and I can't comment on that, sorry.
