### ISSUE TITLE
Provide Insert/Delete/Reload/Move Methods

### ISSUE THREAD

**Issue by dominik-ziegler** [jessesquires/JSQMessagesViewController#315]
The current implementation of `sq_finishSendingOrReceivingMessage` uses `[self.collectionView reloadData]` to update the collection view. Dies causes the collection view to reload on every new message, which looks weird if there are a lot of new messages. You can reprocude this by quickly pressing the "receive" button.

It would be better to provide an interface to the following methods in `CollectionView`:

```
- (void)insertItemsAtIndexPaths:(NSArray *)indexPaths;
- (void)deleteItemsAtIndexPaths:(NSArray *)indexPaths;
- (void)reloadItemsAtIndexPaths:(NSArray *)indexPaths;
- (void)moveItemAtIndexPath:(NSIndexPath *)indexPath toIndexPath:(NSIndexPath *)newIndexPath;
```

**Comment by mzekrallah** [comment]
Hi. This feature is really needed in this great library. It will make it a lot smoother and much more performant. Is there any plan for this on the roadmap ?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
