### ISSUE TITLE
Disable/Remove input toolbar for one-way messaging

### ISSUE THREAD

**Issue by ghost** [jessesquires/JSQMessagesViewController#320]
I need to setup a one-way messaging system in my app and am hoping to use this library. Is it possible to remove the input toolbar completely? So that on the user-end of this app, they can receive but not send messages?

**Comment by polaski** [comment]
I came across the same problem and went through the same steps and got the same results. It crashes when i try to do what was suggested in #446  I was wondering why no one has brought up the option of just setting hidden to YES? It seems to work for me and no crashes either. My code looks like 

            self.inputToolbar.contentView.textView.editable = NO;
            self.inputToolbar.hidden = YES;

**Comment by allaire** [comment]
`[self.inputToolbar removeFromSuperview];` makes the text in my bubbles appear with only 1 or 2 characters per line.
