### ISSUE TITLE
Support for "system" messages

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#321]
1. Implement new "system message" cell prototype 
2. Provide appropriate API for dealing with this, where `sender` is `@"JSQMessagesSystemSender"`

**Comment by trungnguyen1791** [comment]
Hi Jesses.
I've done that all 4 steps. It seem work, but i have one question that how i can make this message alway center align in view like "time label" ( don't care about avatar size).

Thanks. Eric

**Comment by matthijsotterloo** [comment]
@trungnguyen1791 Have you managed to fix this? I'm running in to the same problem and can't find a way to solve this issue. Any suggestions @jessesquires

**Comment by zigdanis** [comment]
I'm looking for solution to center align this system messages too. I was going to use bubbles with zero content size and popuate system message text to the cell top label. @jessesquires Is that appropriate way?

**Comment by trungnguyen1791** [comment]
@matthijsotterloo  Currently i managed it manually in "CellForItemAtIndexPath" using this "systemMsg.messageLabel.textInsets".

For example. My avatar size is (30,30). So i will check when avatar is enable or not then configure the corresponding textInsets value .

if (avatarEnable) {
       systemMsg.messageLabel.textInsets = UIEdgeInsetsMake(0, 15, 0, 0);
}else {
       systemMsg.messageLabel.textInsets = UIEdgeInsetsMake(0, -17, 0, 0);
}

**Comment by plenio** [comment]
@trungnguyen1791:
Have you managed to implement system messages? 
Is there a branch somewhere I could use? 
I am new to this kind of thing, so sorry for asking stupid questions.

**Comment by MHX792** [comment]
Does anyone have a solution for how to implement @jessesquires's answer in Swift for system messages?

**Comment by hermannkuschke** [comment]
@zigdanis that worked perfectly for me so go for it!

**Comment by ryderjack** [comment]
Looking to implement these status messages but having a few issues creating a new Media Item class - would anyone be willing to post some code examples? Cheers!

**Comment by bernikowich** [comment]
Hi guys. I've implemented system message using JSQMessage subclass:
```
class SystemMessage: NSObject, JSQMessageData {
    
    var systemMessage = ""
    
    func senderId() -> String! {
        return "1337"
    }
    
    func senderDisplayName() -> String! {
        return ""
    }
    
    func date() -> Date! {
        return Date()
    }
    
    func isMediaMessage() -> Bool {
        return true
    }
    
    func messageHash() -> UInt {
        return UInt(self.systemMessage.hash)
    }
    
    func media() -> JSQMessageMediaData! {
        return SystemMessageData()
    }
    
    convenience init(withSystemMessage message: String) {
        self.init()
        self.systemMessage = message
    }
    
}

class SystemMessageData: NSObject, JSQMessageMediaData {
    
    func mediaView() -> UIView! {
        return UIView()
    }
    
    func mediaViewDisplaySize() -> CGSize {
        return CGSize(width: 1, height: 0)
    }
    
    func mediaPlaceholderView() -> UIView! {
        return UIView()
    }
    
    func mediaHash() -> UInt {
        return 0
    }
}
```
After that, when you implement delegate methods, return 0 height for `bubble-top` and return correct values for `cell-top`. You'll see system messages similar to timestamps.

**Comment by bernikowich** [comment]
At the same time I can implement JSQMessage update with enum for (Text, Media, System) types. This will allow system messages out of the box.

**Comment by dtochetto** [comment]
@bearclough Small fix:

    func messageHash() -> UInt {
        return UInt(abs(self.systemMessage.hash))
    }

Just in case hash return a negative value. 
Your class works perfect!

**Comment by aliuzunoglu** [comment]
Guys is there an easy way to add system message like adding timestamp?
@bernikowich have you got an example code for system message?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
