### ISSUE TITLE
Max height for JSQMessagesComposerTextView

### ISSUE THREAD

**Issue by mrojas** [jessesquires/JSQMessagesViewController#323]
It would be nice if JSQMessagesComposerTextView had a property "maxHeight" or "maxLines", which is used to determine how tall the input field can grow.
Currently there is not limit, so if you type a huge message the text view takes the entire screen.

JSQMessagesComposerTextView is already observing UITextView notifications, so it could be done like described here: http://corecocoa.wordpress.com/2013/11/09/auto-growing-uitextview-using-auto-layout/

If "maxLines" is prefered, we can use the UIFont method to determine the line height.

Do you think this would be useful for other users?

**Comment by samyakjain** [comment]
I tried everything but input text field height doesn't increase when a longer text is typed in. How can i solve this issue? I am on ios  9.

**Comment by thesleepycow** [comment]
Hi! I'm getting the same issue as @samyakjain, how can i increase the height of the input toolbar? thanks!

**Comment by samyakjain** [comment]
@thesleepycow I guess you forgot to call the method in baseview , call [super ...]

**Comment by thesleepycow** [comment]
@samyakjain sorry but i don't quite understand what you mean.. I'm trying in swift with this code
> 		self.inputToolbar?.maximumHeight = 500

**Comment by samyakjain** [comment]
i have done it in objective-c , you might be overriding this function,
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)

make sure you call     
[super observeValueForKeyPath:keyPath ofObject:object change:change context:context];

**Comment by thesleepycow** [comment]
oh! it's working now. Thank you very much!

**Comment by samosys-ror** [comment]
hello @samyakjain in which class and place i will call this method [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
