### ISSUE TITLE
Questions and advice for backend implementation

### ISSUE THREAD

**Issue by kevinnguy** [jessesquires/JSQMessagesViewController#329]
Hey @jessesquires and everyone, just wanted to say how incredible this framework is and keep up the great work!

I want to ask a few questions on how to implement the backend of a messaging/chat app. I am currently using Rails for my backend and I do not know how the iOS client should be listening to new incoming messages. The three implementations I know of are: push notification, polling, and socketing. 

What is the recommended protocol to use, especially for an iOS client in this situation? Any links or frameworks would definitely help! Thanks guys!

**Comment by xiaoyifan** [comment]
Hey @jessesquires , thx for the remarkable lib! Just get started on integrating this library and going to use Parse to add a messaging function to the app. We can upload message to server when a message is sent, and fetch the message from cloudbase when user open the view. But there's a problem, how can I implement the effect to know someone is typing message by Parse? and thoughts would be appreciated!
<img width="316" alt="screen shot 2015-07-10 at 2 28 13 am" src="https://cloud.githubusercontent.com/assets/9085563/8613297/6ea50f10-26ab-11e5-93dc-f0652712389d.png">
