### ISSUE TITLE
How can i create a border around my chat bubble.

### ISSUE THREAD

**Issue by harshitaahuja** [jessesquires/JSQMessagesViewController#332]
I am using a simple chat bubble but i want a border with different color.But as using strechable image it is masked with color all over even if i take a image with border.
I thought i can color it all over first with border color and then leaving boundry rect with bubble color. But i dont think it is a good idea?

I tried doing that in function
- (UIImage *)jsq_imageMaskedWithColor:(UIColor *)maskColor.

Can you suggest a better way or better place to do that.

**Comment by jessesquires** [comment]
hey @harshitaahuja - this is now **much** easier with the new images provided in the [image category](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Categories/UIImage%2BJSQMessages.h).

you can initialize a [JSQMessagesBubbleImageFactory](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Factories/JSQMessagesBubbleImageFactory.h) with any of these new assets

**Comment by bizibizi** [comment]
can you give an example how to add stroke to filled bubble cell?

**Comment by nathanielescribano** [comment]
looking to do the same thing. using bubble_stroked and setting a color on it, sets the border color. it would be nice to set both the border color and the filled bubble color. in other words, it would be nice to set the border color, the filled bubble color, and the background color differently. Any suggestions? thanks!

**Comment by jessesquires** [comment]
@nathanielescribano - unfortunately the library won't be able to help with this out-of-the-box. you'd have to do some customization on your end.

but, doing this is really is pretty trivial:

1. generate your `UIImage`s
2. give your custom images to the data source

Now, how you accomplish (1) is up to you, and it might be challenging, but it is possible.

**Comment by antoniotinto** [comment]
@jessesquires is this still the quickest way to add borders to the bubble?
Thanks!

**Comment by eliburke** [comment]
@antoniotinto the library does not provide a way to independently set the bubble border and bubble color. You can have a colored bubble, or a colored outline, or you will need to do some additional work. 

Take a look at JSQMessagesBubbleImageFactory (which you will need to subclass, or manually create your own JSQMessagesBubbleImage objects).

**Comment by rance-attack** [comment]
a simple-dirty way to do this.. however it ignores the bubble image provided in the initializer.
```
- (JSQMessagesBubbleImage *)outgoingMessagesBubbleImageWithColor:(UIColor *)color borderColor:(UIColor *)borderColor
{
    return [self jsq_messagesBubbleImageWithColor:color borderColor:borderColor flippedForIncoming:NO];
}

- (JSQMessagesBubbleImage *)incomingMessagesBubbleImageWithColor:(UIColor *)color borderColor:(UIColor *)borderColor
{
    return [self jsq_messagesBubbleImageWithColor:color borderColor:borderColor flippedForIncoming:YES];
}

- (JSQMessagesBubbleImage *)jsq_messagesBubbleImageWithColor:(UIColor *)color borderColor:(UIColor *)borderColor flippedForIncoming:(BOOL)flippedForIncoming
{
    NSParameterAssert(color != nil);
    
    UIImage *image = [UIImage jsq_bubbleRegularImage];
    UIImage *strokedImage = [UIImage jsq_bubbleRegularStrokedImage];
    UIImage *coloredImage;
    UIImage *coloredStrokedImage;
    
    coloredImage = [image jsq_imageMaskedWithColor:color];
    coloredStrokedImage = [strokedImage jsq_imageMaskedWithColor:borderColor];
    
    UIImage *normalBubble = [self addImage:coloredImage withImage:coloredStrokedImage];
    
    color = [color jsq_colorByDarkeningColorWithValue:0.12f];
    coloredImage = [image jsq_imageMaskedWithColor:color];
    coloredStrokedImage = [strokedImage jsq_imageMaskedWithColor:borderColor];
    
    UIImage *highlightedBubble = [self addImage:coloredImage withImage:coloredStrokedImage];
    
    if (flippedForIncoming) {
        normalBubble = [self jsq_horizontallyFlippedImageFromImage:normalBubble];
        highlightedBubble = [self jsq_horizontallyFlippedImageFromImage:highlightedBubble];
    }
    
    normalBubble = [self jsq_stretchableImageFromImage:normalBubble withCapInsets:self.capInsets];
    highlightedBubble = [self jsq_stretchableImageFromImage:highlightedBubble withCapInsets:self.capInsets];
    
    return [[JSQMessagesBubbleImage alloc] initWithMessageBubbleImage:normalBubble highlightedImage:highlightedBubble];
}

- (UIImage *)addImage:(UIImage *)image1 withImage:(UIImage *)image2
{
    UIImage *result;
    
    UIGraphicsBeginImageContext(image1.size);
    {
        [image1 drawAtPoint:CGPointZero];
        [image2 drawAtPoint:CGPointZero];
        result = UIGraphicsGetImageFromCurrentImageContext();
    }
    UIGraphicsEndImageContext();
    
    return result;
}
```

**Comment by gmansata6290** [comment]
@jessesquires, @eliburke 

I have used the inbuilt function jsq_bubbleRegularStrokedImage() to create the StrokedBubbleImage but I can't see the content inside the bubble. Can somebody help me out in this? I have attached the sample demo (Please look into Swift Example) code to reproduce this issue. And I just want to apply this StrokedBubbleImage to only my JSQCustomMediaItem. CustomMediaItem can be generated by clicking on "Send Photos" from Attachment Pin.

![simulator screen shot 18-oct-2016 3 16 21 pm](https://cloud.githubusercontent.com/assets/12854378/19472926/e15ac422-9546-11e6-9f49-9133bad7e39a.png)

[JSQMessagesViewController-develop.zip](https://github.com/jessesquires/JSQMessagesViewController/files/535900/JSQMessagesViewController-develop.zip)

**Comment by julien-c** [comment]
@gmansata6290 Your text is probably white

**Comment by gmansata6290** [comment]
Thanks @julien-c yes it was the case for default JSQ Bubble. The Red Stroke Bubble is a customMediaItem created by me. 

![simulator screen shot 18-oct-2016 4 40 55 pm](https://cloud.githubusercontent.com/assets/12854378/19475452/e7bf64fc-9551-11e6-81d7-22fe33e514aa.png)

but in the view hierarchy i can see the text clearly with black color and red background.

![screen shot 2016-10-18 at 4 47 08 pm](https://cloud.githubusercontent.com/assets/12854378/19475585/8a2bcb0e-9552-11e6-876f-2fde31d21968.png)

can you help me out in this ?

**Comment by eliburke** [comment]
@gmansata6290 I'm pretty sure that @julien-c is right. You can't safely assume that your NIB settings are making it through to the cell untouched. There is a lot of programmatic adjustment that occurs within JSQMessages before your cells are put on the screen. Try setting an explicit color for cell.textView.textColor in your cellForItemAtIndexPath or willDisplayCell delegate method. 

As for the bubble mask.. there are at whole lot of ways to get those screwed up. You should have a JSQMessagesBubbleImage for each direction:
````
_incomingBubble = [bubbleFactory incomingMessagesBubbleImageWithColor:[UIColor appChatBubbleIncoming]];
_outgoingBubble = [bubbleFactory outgoingMessagesBubbleImageWithColor:[UIColor appChatBubbleOutgoing]];

````
Start by taking a look at `messageBubbleImageDataForItemAtIndexPath`. Mine retrieves the chat object for a given index, and then looks to see if its sender is the same as the local sender. 
````
if ([chatData.senderId isEqualToString:self.senderId])
        return _outgoingBubble;
else return _incomingBubble;
````

**Comment by gmansata6290** [comment]
@eliburke Thanks for your response. After @julien-c  response, I have added currentCell.textView?.textColor = UIColor.blackColor() in cellForRowAtIndexPath still I am facing the same issue. As for bubbleMask I have incomingBubble and outgoingBubble as you have mentioned.

**Comment by eliburke** [comment]
@gmansata6290 take another look at your code. You are calling `incomingMessagesBubbleImageWithColor` twice. One of them should be `outgoingMessagesBubbleImageWithColor` and the image will be flipped for you.

As for your text, if you are using a custom media item you have probably done something wrong with the layout. It could be the outlets, or the text has is placed outside of the view's frame, or it has a 0 width or height, or it is covered up under something else, or....? Your best option is to use the view inspector to try and figure out how you have misplaced the views. If that doesn't work, try adding a subview in cellForItemAtIndexPath with a fixed size and color to verify that it is shown.

**Comment by gmansata6290** [comment]
Thanks @eliburke. You are right. I got the flipped image. But for strokedBubbleImageMasking issue 1) I have created my customMediaItem programmatically. 
2) As you can see in the 2nd screenshot it is clearly showing the text with the black color while debugging the view. Even if you select the text copy and paste the actual text is getting selected.
3) I have checked with view Inspector nothing is covered up on the mediaView.
4) As per your guidance I have added a view in cellForItemAtIndexPath with yellowColor and below is the result I got.

![simulator screen shot 18-oct-2016 8 06 45 pm](https://cloud.githubusercontent.com/assets/12854378/19482380/98451120-956e-11e6-9189-63d8f52e470a.png)


![screen shot 2016-10-18 at 8 08 31 pm](https://cloud.githubusercontent.com/assets/12854378/19482403/ad4bcad2-956e-11e6-8ce0-4cab9bb65eea.png)

**Comment by eliburke** [comment]
@gmansata6290 haha ok yeah it took me a while to shake the cobwebs loose on this one.

Here's the deal. When the bubble mask is used for text messages, it is first combined with a rectangle of the chosen color. This creates an outline (for the stroked mask) or a filled bubble of color. This is then used as the background for your text. 

When the bubble mask is used for media views, the media view itself is combined with the mask image. Any portion of the mask that is clear will not show any of your mediaView. Because you are using the stroked mask, you get only an outline of your custom view. Switch to the regular filled bubble mask and you should see your whole custom view.

**Comment by gmansata6290** [comment]
Thanks so much @eliburke  ! Really appreciate your prompt replies and your last explanation gave us clarity. We finally decided to not use the bubble mask since we were still not able to apply the stroke on the bubble image even after using the regular filled bubble mask, but we just applied the stroked borders to the elements in our custom view, thus making it look like what we wanted, but minus the message tail. 

We are ok with that for now since it serves our purpose.

**Comment by TheEngineerz** [comment]
@julien-c @gmansata6290  If i want to create same borders for media messages then what should i do?

**Comment by gmansata6290** [comment]
@TheEngineerz you just want to create media message with transparent background with borders? if yes then here is the solution. You have to create a CustomMediaItem with your custom view, just apply the borderWidth and borderColor to your CustomView. But don't apply JSQBubbleMask to your CustomView why? because https://github.com/jessesquires/JSQMessagesViewController/issues/332#issuecomment-254614782.  But here you wont see the bubble with tail.
