### ISSUE TITLE
How to disable/remove attachment button?

### ISSUE THREAD

**Issue by ghost** [jessesquires/JSQMessagesViewController#338]
Is it possible to remove the attachment button (media) from the toolbar? Couldn't find anything in documentation or brief reviewing of source files.

**Comment by jayherron** [comment]
Thanks for the help on this one. I had the same question like 4 mins ago

**Comment by jessesquires** [comment]
👍

**Comment by rosaliadupont** [comment]
how do you enable the the attachment button?

**Comment by ded** [comment]
@rosaliadupont it's enabled by default. so you shouldn't have to do anything

**Comment by deore123** [comment]
@jessesquires Hi, I want to implement audio sharing and location sharing in my app. Can you please tell me how to achieve these task? I really appreciate your help.

**Comment by Sid6022** [comment]
@jessesquires m trying to hide that button using this code
` inputToolbar.contentView.rightBarButtonItem.isHidden = true` 
is this perfect ?
