### ISSUE TITLE
Give the Load Earlier Message view an animatable property.

### ISSUE THREAD

**Issue by klivin** [jessesquires/JSQMessagesViewController#345]
Would also be nice to expose the appearance of Load Earlier Message view (font, color, height, etc) in the JSQMessagesCollectionView API.

**Comment by wdcurry** [comment]
Thanks Jesse, this little note rocks.

**Comment by jessesquires** [comment]
![img](http://media.giphy.com/media/ujGfBmVppmgEg/giphy.gif)

**Comment by wdcurry** [comment]
your gif-wit is endless ;)
