### ISSUE TITLE
showTypingIndicator not appearing

### ISSUE THREAD

**Issue by gibo** [jessesquires/JSQMessagesViewController#352]
The typing indicator does not appear when set to YES, there seems to be space made for it, but it does not render.

This bug can be reproduced using the demo application by modifying the function `receiveMessagePressed`, insert a `return` statement after:

```
self.showTypingIndicator = !self.showTypingIndicator;
```

Now the user needs to press the '...' buttton in the top right.

The typing indicator should appear the first time it is pressed, but it does not.

**Comment by gmansata6290** [comment]
@jessesquires 
You guys have done a great job by providing this as a open source library. I really appreciate the work you and your team has done. I have used this library in my app. My app is live. So I just wanted to add this feature in my app as well. But I tried out in swift it didn't work. Then I looked in the sample also.

I just want to know ShowTypingIndicator feature is working in Objective - C example, but not in the Swift example. Can you help me out in this?
