### ISSUE TITLE
Add additional button to input toolbar

### ISSUE THREAD

**Issue by Kudo** [jessesquires/JSQMessagesViewController#358]
Hi,

I need to add additional button to the left button (i.e. there are two left buttons).

Original my idea is to subclass `JSQMessagesViewController`, however the inputToolbar property is private the .m implementation.  It seems not be a good idea to do subclass and customize only inputToolbar view.
Do you have any other hints how if I can do this?

Thanks in advanced especially the modulized and clean code which teach me a lot.
Kudo

**Comment by zwang** [comment]
HI Kudo, do you mind sharing your approach for this? I am thinking about doing the same thing too. What I am thinking right now is to introduce an array of left buttons instead of one left button. It seems modifying the original source code is unavoidable. 

Thanks.

**Comment by eliburke** [comment]
I'm pretty sure this is possible now. See #1068. It has an example of adding two buttons on the left side. You just have to use your own selectors instead of handling JSQMessagesViewController:didPressAccessoryButton:

**Comment by zwang** [comment]
Nice, I saw the containerView today too thought it was doable. @eliburke  thank you very much for pointing me to the right solution. :+1:
