### ISSUE TITLE
Hide keyboard when collectionView is tapped

### ISSUE THREAD

**Issue by virl** [jessesquires/JSQMessagesViewController#360]
Hide keyboard when collectionView is tapped. Just add TapGestureRecognizer to collectionView:

```
UITapGestureRecognizer* tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleCollectionTapRecognizer:)];
	[self.collectionView addGestureRecognizer:tapRecognizer];
```

with following action:

```
- (void) handleCollectionTapRecognizer:(UITapGestureRecognizer*)recognizer
{
	if(recognizer.state == UIGestureRecognizerStateEnded)
	{
		if([self.inputToolbar.contentView.textView isFirstResponder])
			[self.inputToolbar.contentView.textView resignFirstResponder];
	}
}
```

Also please introduce viewController's option for that (enabled by default).

**Comment by dingquan** [comment]
I've added code provided by @virl and I'm seeing a strange behavior.
if my collection view is empty. tap gesture is always recognized and it works fine.
if my collection has messages (so a bunch of views on top of the collection view), I need to tap twice to dismiss the keyboard. but when I put a break point in my gesture recognizer handler code to see what's going on, the the problem disappears, tap always dismisses the keyboard. very confused...

**Comment by virl** [comment]
@dingquan I added that code long ago. Since then I'm using SlackTextViewController — it's more customizable/non-intrusive and allows you to use your own UITableView.

**Comment by dingquan** [comment]
@virl Thanks for the info. Can SlackTextViewController be used in combination with JSQMessagesViewController? Or it replaces JSQMessagesViewController? What about other features in JSQMessagesViewController provides (avatars and such)?

**Comment by jessesquires** [comment]
With 752fd38aa8b899cbe2e21b6595de58920977bfc2 merged, using `.keyboardDismissMode` is the preferred method for dismissing keyboard.

Closing this. Clients can implement this manually if they wish.

**Comment by mcaldas** [comment]
@virl @dingquan also interested in using SlackTextViewController with JSQMessagesViewController, any way to combine?

**Comment by shravanteegala** [comment]
Hi,
Iam facing same  problem.
Can you give  me in Objective-C. sample.

**Comment by shravanteegala** [comment]
in ViewDidLoad:

UITapGestureRecognizer *tapGestureRegnizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(dismissKeyboard:)];
    tapGestureRegnizer.delegate = self;
    
    [self.collectionView addGestureRecognizer:tapGestureRegnizer];
    ----------------------------------------------

handler:

- (void)dismissKeyboard:(UITapGestureRecognizer *)tp{
    
    if(tp.state == UIGestureRecognizerStateEnded)
    {
        if([self.inputToolbar.contentView.textView isFirstResponder])
            [self.inputToolbar.contentView.textView resignFirstResponder];
    }
    
}




- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    
    return true;
}
