### ISSUE TITLE
Upon finishReceivingMessage scroll to bottom only if previously last message were seen

### ISSUE THREAD

**Issue by virl** [jessesquires/JSQMessagesViewController#363]
I think we need method like receiveMessage: instead of finishReceivingMessage.

Also collectionView should not scroll to bottom when new message is received if previously (before receiving it) last message was not seen. It will allow for uninterrupted reading of messages in heat of discussion.

**Comment by gfzabarino** [comment]
I was just around seeking if there were any comments of how to prevent `reloadData` from being called and use index path related methods to insert / update / remove. I saw #315 and that brought me here.
I must 👍 to the above message's behavior description. I just opened Facebook messenger and reproduced the mentioned behavior and it just feels so natural.
For example, in my application where I'm using JSQ, I tried going to see older messages, and then tapping on the text view scrolled to the last message. If I would have been a real user, going so far back in message's history, and then that 'work' was thrown away, I bet I would be pissed.
Having said that, @jessesquires this is an awesome library. I think this suggestion in particular should go to a prioritized ToDo list, as it is indeed a very nice behavior if you experience it. Of course doing this could break compatibility with some tweaks made by some client projects, so I guess the best would be to add it as a feature of a new major release.
My two cents (and I know, this is probably less than that 😄).
