### ISSUE TITLE
Static input toolbar - toolbar not moving with keyboard

### ISSUE THREAD

**Issue by realsurfer** [jessesquires/JSQMessagesViewController#366]
Hi,

My setup is the following. My root controller is a tab bar controller. On the active tab I have a navigation controller with a similar setup as the demo project. On pushing the message view I hide the tab bar and everything looks good. When I tap on the input toolbar the keyboard appears but the input toolbar remains at the bottom of the view. See images below. Also if I start typing multiple lines the text view doesn't expand.

Not sure if this is a bug or something wrong in my implementation. I have pretty much copy pasted the demo project code.

Thanks,
Michael

![screen shot 2014-06-18 at 19 10 47](https://cloud.githubusercontent.com/assets/2805960/3317377/aa1c6626-f70c-11e3-962f-7dd1d2283e6c.png)
![screen shot 2014-06-18 at 19 12 43](https://cloud.githubusercontent.com/assets/2805960/3317373/860be414-f70c-11e3-8342-8f688e3b6a16.png)

**Comment by Serge-Staravoitau** [comment]
Thx, guys, had the same problem.

**Comment by imuhammadjabbar** [comment]
You save my hours as well. 
Thanks a lot man.

**Comment by yadavanand** [comment]
@jessesquires Thanks a lot

**Comment by carloskekwa** [comment]
hi , 

When I had almost the same problem. When clicking on the accessory button in , i choose a picture using imagepicker and then when i come back to the JSQViewController the inputtoolbar is disappearing. I tried to use 

[self.inputToolbar.contentView.textView becomeFirstResponder]; when 

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
{
[self.inputToolbar becomeFirstResponder];
and 
 [self.inputToolbar.contentView.textView resignFirstResponder];
}

But it didnt change

**Comment by carloskekwa** [comment]
any news about this issue? @jessesquires

**Comment by kingkeishan** [comment]
thanks guys for this!
