### ISSUE TITLE
How to detect when message bubble is tapped on?

### ISSUE THREAD

**Issue by zallanx** [jessesquires/JSQMessagesViewController#367]
First of all, great project :+1: 

I would like to execute some functions based on which chat bubble the user tapped on. I tried to follow the logic of using the standard collection view method `collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath`, but noticed that the taps were not being captured. I was wondering if there is another way to determine when a particular chat bubble is tapped on?

Thanks!

**Comment by kpsdeveloper** [comment]
@zallanx Can you translate your code to swift please. I had the same issue with swift.
Regard,
Thanks

**Comment by georgepliuster** [comment]
@zallanx 
I started with 'ghost commented on Jun 19, 2014' entry above and instead of attaching the recognizer to the cell, I attached to the textView in the cell - like this:

        let singleTapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(didSingleTapOnView))
        singleTapGestureRecognizer.numberOfTapsRequired = 1
        singleTapGestureRecognizer.delegate = self
        cell.textView?.addGestureRecognizer(singleTapGestureRecognizer)

The visual affect (such as an alert, etc.) will occur when you 'touch the bubble'.

Good luck!
