### ISSUE TITLE
Sent/Received checkmark inside the bubble

### ISSUE THREAD

**Issue by mrojas** [jessesquires/JSQMessagesViewController#372]
Hello,
I've been using the cell bottom view to indicate if a message has been sent/received, like in iMessage.
Now I would like to have one or two checkmarks inside the bubble, like in Whatsapp. I would you proceed?
I have tried setting the attributedText which includes an image, but that breaks the width calculation performed by JSQMessagesViewController.

Thanks in advance!

**Comment by angeljcarrillo** [comment]
Hi i know it is a old post but, how you all fix the problem with the check marks?, I did what jessesquires said, but my check marks does not appear, because the bubble color hidden, therefore how I can fix that problem?

**Comment by syrakozz** [comment]
can we display the checkmark beside the bubble like whatsapp, 
if we can control the cellBottomLabel position it will be great
