### ISSUE TITLE
iOS 7 bug with parsing UITextView data detectors: App crashes with SIGABRT on _lockForWritingWithExceptionHandler

### ISSUE THREAD

**Issue by oanaBan** [jessesquires/JSQMessagesViewController#378]
I have multiple messages and if the user scrolls up fast and then down again the app will crash with the following message: Assertion failure in -[NSConcreteTextStorage _lockForWritingWithExceptionHandler:], /SourceCache/UIFoundation/UIFoundation-258/UIFoundation/TextSystem/NSTextStorage.m:607
libc++abi.dylib: terminate_handler unexpectedly threw an exception

Note: I saw it only on iOS 7.0 and I have the source code from commit: abdd2ddabc74eaa2855e47490b64fc5bbb3992fa, date: 17 Jun, comment: "Merge pull request #356 from ringring-io/ringring. Add Ringring.io to the apps list"

Any fixes for this?

**Comment by jessesquires** [comment]
closing this as resolved for `v8.0` of the library as it will be iOS 8+ only
