### ISSUE TITLE
Add "To: <recipient>" field like iOS Messages

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#38]
Add "To: <recipient>" field like iOS Messages

**Comment by jessesquires** [comment]
Actually, I feel like this is beyond the scope of this library. At least for now. Perhaps this can be revisited after the 8.0 release is finished

**Comment by basilmariano** [comment]
yes please! 
We badly needed it. haha 
+1000 for this feature. 

This feature is implemented in [ATLAS](https://github.com/layerhq/Atlas-iOS) but it is directly integrated with LayerKit.
