### ISSUE TITLE
How to have keyboard show up when view loads

### ISSUE THREAD

**Issue by rizhang** [jessesquires/JSQMessagesViewController#380]
I looked at #211 , but this solution animates the keyboard popping up after the view is done loading. This wastes like a second and I rather just have the keyboard already up. If I try putting `[self.inputToolbar.contentView.textView becomeFirstResponder];` in viewWillAppear or viewDidLoad, they keyboard will be over the textview because the textview never repositioned itself above the keyboard

![image](https://cloud.githubusercontent.com/assets/2416621/3377943/aa790246-fbe4-11e3-83d9-af4c5c8001b7.png)

**Comment by willia15** [comment]
Any word on this feature request? I'd love to have the keyboard up when the view loads.

**Comment by karthikgollapudi** [comment]
This worked for me once I called it from `viewDidAppear()`

**Comment by jessesquires** [comment]
Fixed by 752fd38aa8b899cbe2e21b6595de58920977bfc2
