### ISSUE TITLE
How to add commands to longpress cell menu?

### ISSUE THREAD

**Issue by ghost** [jessesquires/JSQMessagesViewController#393]
I need add some commands to menu shown when long press on a cell. I think it must be easy, but how can I do that?

**Comment by saad-ansari** [comment]
I have successfully added "delete" item but similarly if i am going to add some other item like "resend". its not adding to menu ... any help would be appreciated. Thanks

**Comment by basawarajh-cuelogic** [comment]
Hi,
How to handle delete action in JSQMessageController, I have implemented method 

        override func collectionView(collectionView: JSQMessagesCollectionView!, didDeleteMessageAtIndexPath indexPath: NSIndexPath!) {
        self.collectionView?.deleteItemsAtIndexPaths([indexPath])
    }

Also override method 

        override func collectionView(collectionView: UICollectionView, shouldShowMenuForItemAtIndexPath indexPath: NSIndexPath) -> Bool {
        // Do the custom JSQM stuff
        super.collectionView(collectionView, shouldShowMenuForItemAtIndexPath: indexPath)
        // And return true for all message types (we don't want the long press menu disabled for any message types)
        return true
    }
    
      override func collectionView(collectionView: UICollectionView, canPerformAction action: Selector, forItemAtIndexPath indexPath: NSIndexPath, withSender sender: AnyObject?) -> Bool {
        super.collectionView(collectionView, canPerformAction: action, forItemAtIndexPath: indexPath, withSender: sender)
        return true
    }
    
    override func collectionView(collectionView: UICollectionView, performAction action: Selector, forItemAtIndexPath indexPath: NSIndexPath, withSender sender: AnyObject?) {
        super.collectionView(collectionView, performAction: action, forItemAtIndexPath: indexPath, withSender: sender)
    }

but i get crash on menu item what else to be done to work, any help would be appreciated, thanks in advance.

**Comment by eliburke** [comment]
@basawarajh-cuelogic In the future, instead of cross-posting your same problem to a bunch of closed issues, please open a single new issue.

Without seeing the crash, I'm not sure what you are doing wrong. But I think you need to call registerMenuAction on "delete:". See #1282 for more information.

**Comment by vinayTree** [comment]
I need add forward commands to menu shown when long press on a cell. I tried many ways but i don't know how to add it can anyone help me with forward option in menu, where i want to forward text message like copy and delete.
