### ISSUE TITLE
[Springiness] new messages cause others to bounce down

### ISSUE THREAD

**Issue by ghazel** [jessesquires/JSQMessagesViewController#398]
Easily visible in the demo. New messages cause the display to jump down, then spring back up.

![](https://i.imgflip.com/adckz.gif)

I understand springiness is experimental. Looking forward to it!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
