### ISSUE TITLE
Pan-to-dismiss keybooard not working properly on opaque navigation bars (translucent = NO)

### ISSUE THREAD

**Issue by piercifani** [jessesquires/JSQMessagesViewController#405]
the interactive dismiss keyboard is not working properly when using opaque navigation bars.

![pan-animation](https://cloud.githubusercontent.com/assets/869981/3628720/197a67d8-0e97-11e4-8256-3326595cde98.gif)

I checked for almost an hour how the ```jsq_handlePanGestureRecognizer```works and tried to adjust it to the scrollview's inset, but with no luck.

**Comment by kartikthapar** [comment]
Is there any progress on this issue? Or a potential hack?
