### ISSUE TITLE
Need help & idea on Load earlier message implementation

### ISSUE THREAD

**Issue by Antairez** [jessesquires/JSQMessagesViewController#423]
I am trying to implement load earlier message, and I am not sure what is the best way to do this. My first thought is limiting the size of the dataSource array, remove object at the first index and append object to the end, then call [self finishReceivingMessage]. But it seems like finishReceivingMessage animated both the deletion and addition, hence every new message triggers a weird animation that is very jumpy. Can anyone enlighten me on this matter?

**Comment by rkumawat** [comment]
How can i show messages before "LoadEarlierMessages" button ,like as a facebook comments

**Comment by jessesquires** [comment]
@rkumawat please stop spamming unrelated issues with your questions
