### ISSUE TITLE
Extra bottom padding for long text messages

### ISSUE THREAD

**Issue by oonoo** [jessesquires/JSQMessagesViewController#438]
![jsqmessageviewcontroller_bug_bottom_padding](https://cloud.githubusercontent.com/assets/2565796/3920966/225e75da-23bc-11e4-8ed1-6dd739cdeb4c.png)
The bottom padding gets too big for large texts.

**Comment by jessesquires** [comment]
Hello all — See my comment on #347 for details on the "fix" for this.

https://github.com/jessesquires/JSQMessagesViewController/issues/347#issuecomment-130533179
