### ISSUE TITLE
How maintain scroll position?

### ISSUE THREAD

**Issue by educosta** [jessesquires/JSQMessagesViewController#441]
How can I still scroll position when I load new messages?

If disabled automaticallyScrollsToMostRecentMessage scroll to up, if enabled scroll to down.

Thank you

**Comment by mitchellporter** [comment]
@dim0v works perfectly even on iOS 9 ;)

**Comment by bpisano** [comment]
I have this issue too and I've tried the layoutIfNeeded. But with a lot of cells and self sizing, it completely freeze the UI.
