### ISSUE TITLE
Hiding input bar?

### ISSUE THREAD

**Issue by bliebman** [jessesquires/JSQMessagesViewController#446]
Hi Jesse,

Big fan. Is there currently a way I could hide the input toolbar in the messages view controller? Just to make it permanently disappear.

Thanks!

Brandon

**Comment by a8b** [comment]
Crash when trying to hide input bar at some later point of time
Say I have subclass of JSQMessagesViewController with property


    var chatRoomType: ChatRoomType = .Chat {
        didSet {
            if let inputToolbar = inputToolbar
                where chatRoomType == .Media {
                inputToolbar.removeFromSuperview()
            }
        }
    }

Crash happens when change chatRoomType from .Chat to .Media

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7ff5c40bec00 of class JSQMessagesComposerTextView was deallocated while key value observers were still registered with it. Current observation info: ...
