### ISSUE TITLE
[Springiness] multi-line messages do not animate in when springiness == NO

### ISSUE THREAD

**Issue by klivin** [jessesquires/JSQMessagesViewController#448]
When I send a message that is over a single line in length, the message appears immediately without animating.   When the message is a single line, it animates in as expected.
I'm using 
    [self finishSendingMessage];

With:
    self.automaticallyScrollsToMostRecentMessage = YES;

And: 
    self.collectionView.collectionViewLayout.springinessEnabled = NO;

**Comment by jadslim313** [comment]
any suggestions for fixing this one?
