### ISSUE TITLE
Chinese input: auto scroll bug when switch to another input method

### ISSUE THREAD

**Issue by chenweiyj** [jessesquires/JSQMessagesViewController#450]
hi all,

When I switch to another input method (namely, Chinese input method), the message view does not auto scroll to the last message. The screenshot shown as below indicates that a message bounded by the red circle is covered by the keyboard. 

![scrollbug](http://chenweiyj.qiniudn.com/apperror/scrollbug.png)

**Comment by jessesquires** [comment]
You can also repro this by switching between english and emjoi.

Should be an easy fix. Listen for keyboard frame change notif and adjust insets.

**Comment by JPMartha** [comment]
Hi @jessesquires, nice to meet you!

Could I ask what is this issue just in case?
The solution is scrolling to the most recent message automatically, right?
In other words, we can see the most recent message when a keyboard frame is changed.

**Comment by jessesquires** [comment]
@JPMartha Ah, yes -- that's correct!

**Comment by jessesquires** [comment]
Hm.. ok. so this is a bit more complicated now. 

We **do not** want to scroll *every* time the keyboard frame changes — only when it changes by this small amount.

**Comment by JPMartha** [comment]
I see.
I am busy until this Saturday, but it is over, I'd like to contribute to your project.

**Comment by Lucashuang0802** [comment]
@jessesquires I'm just wondering what's the status of this issue now? It seems the suggestion bar is shown automatically all the time and looks great. Perhaps because I was testing with iOS 9.3 only?

**Comment by yarodevuci** [comment]
issue is not solved...

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
