### ISSUE TITLE
Bubble resizing when reshowing in view.

### ISSUE THREAD

**Issue by yarneo** [jessesquires/JSQMessagesViewController#451]
I have added a tap to dismiss in the chat by calling  
[self.inputToolbar.contentView.textView resignFirstResponder];

However, I have noticed that when dismissing, the few bubbles that reappear from the top of the screen, have a 0.5 seconds animation where the bubble's width is resized to fit the text.
Is there a way to not make it look like that? I tend to doubt this is a feature of some sort.

Thanks!

**Comment by promisenxu** [comment]
Running 7.1.0 on iOS8 on iPhone6 and simulator (8.1 and 8.4).

I also implemented the tap to dismiss keyboard functionality similarly - by asking the textView to endEditing or resignFirstResponder or the collection view to endEditing. The bubble could be seen resizing - for outgoing message it's shrinking and for incoming message it's expanding.

I tested with the dismiss by swiping - there's actually a very fast resize as well. Use Slow Animation and it will be a lot more visible.

**Comment by promisenxu** [comment]
Thought I would update on this - I sort of hacked a solution to the problem, not elegant at all though.

I tried many many things to fix the speed or sequence of animation involved in the resetting of inset - no luck.

I ended up calling the collectionView to reloadItemsAtIndexPaths for all the items that will be created as a result of the decrease in contentInset. This seems to create the cells before any animation is shown and therefore prevent them from resizing on screen.

**Comment by jessesquires** [comment]
Thanks @promisenxu - another PR for this too? :smile:

**Comment by Phineas-z** [comment]
@promisenxu I saw the same issue even after I upgraded to 7.2.0. And finally I fixed it by adding this:

// This will force cell in correct size in current execute loop
    [self setNeedsLayout];
    [self layoutIfNeeded];

at the end of applyLayoutAttributes of JSQ cell.

You could subclass the cell or use method swizzling to achieve it without touch the code of jsq framework.

**Comment by promisenxu** [comment]
@Phineas-z The methods you mentioned do not seem to work for me. Any other changes you made? I was thinking instead of changing the content inset at the bottom, I can just change the frame?

**Comment by promisenxu** [comment]
@Phineas-z I actually have to add [self layoutSubviews] before your two lines to make it work. Also, I have to use [UIView performWithoutAnimation:] when setting mediaView on the cell to prevent media cell from resizing.
