### ISSUE TITLE
Scroll to bottom not working when load earlier messages is enabled

### ISSUE THREAD

**Issue by rezasham** [jessesquires/JSQMessagesViewController#452]
if showLoadEarlierMessagesHeader = YES;

view will not scroll all the way to the bottom, seems like its not being taken into consideration.

**Comment by charliewilliams** [comment]
I am seeing this on the latest build. Manually setting `showLoadEarlierMessagesHeader = true` in `viewDidLoad` seems to fix it, although since this value defaults to `true` that seems like unexpected behavior?
