### ISSUE TITLE
JSQMessagesCollectionViewFlowLayoutInvalidationContext missing?

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#456]
hey, just thought to report that i just downloaded the latest zip and dropped it into my app (i'm old-school and am not using pods) and noted that JSQMessagesCollectionViewFlowLayoutInvalidationContext is missing from the project. A simple drag'n'drop into the Layout folder resolves it..

**Comment by dustMason** [comment]
Strangely, I am seeing the same issue. I did a git clone of the develop branch, dropped the JSQMessagesViewController dir into my project and added `#import "JSQMessages.h"` to my bridging header.

```
.../JSQMessagesViewController/Views/JSQMessagesCollectionView.h:22:9: 'JSQMessagesCollectionViewDelegateFlowLayout.h' file not found
```

**Comment by dustMason** [comment]
Please ignore my last comment. My problem was that I was upgrading from an older version of JSQMessagesViewController and forgot to update the references in my Xcode project. I fixed it by deleting the files from the project window and re-adding them.
