### ISSUE TITLE
Breaking constraints when setting rightBarButtonItemWidth

### ISSUE THREAD

**Issue by davidganster** [jessesquires/JSQMessagesViewController#460]
Hi everybody,

I'm getting the following error messages on the latest `master` branch when trying to set `self.inputToolbar.contentView.rightBarButtonItemWidth`:

> Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at  each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
> (
>     "NSLayoutConstraint:0x9162d50 H:[UIView:0x9161180(70)]",
>     "NSLayoutConstraint:0x917ab50 H:[UIButton:0x9178fd0]-(0)-|   (Names: '|':UIView:0x9161180 )",
>     "NSAutoresizingMaskLayoutConstraint:0x9185bb0 h=--& v=--& UIButton:0x9178fd0.midX == + 25",
>     "NSAutoresizingMaskLayoutConstraint:0x9185bf0 h=--& v=--& H:[UIButton:0x9178fd0(50)]"
> )

Furthermore, the layout doesn't actually increase the size of the button.
For example, the following lines of code produce the result shown in the attached image:

```objective-c
self.inputToolbar.contentView.rightBarButtonItemWidth = 100;
[self.inputToolbar.contentView.rightBarButtonItem setTitle:@"Alt Text" forState:UIControlStateDisabled];
[self.inputToolbar.contentView.rightBarButtonItem setTitle:@"Alt Text" forState:UIControlStateNormal];
```

![screen shot 2014-08-30 at 19 33 08](https://cloud.githubusercontent.com/assets/851282/4099722/bb505b3a-306b-11e4-842a-e7a3fa57e528.png)

**Comment by phinix** [comment]
Hi @jessesquires

I'm getting same issues on version 6.1.3, how can I revise it?

**Comment by Neirys** [comment]
Hi,

I had the same issue and needed to do `self.inputToolbar.contentView.rightBarButtonItem.translatesAutoresizingMaskIntoConstraints = NO;` in order to fix it

**Comment by Katafalkas** [comment]
:+1:  @Neirys . Had same problem - that helped.

**Comment by jessesquires** [comment]
re-opening this issue to investigate
