### ISSUE TITLE
Handle mentions (@) and hashtags (#)

### ISSUE THREAD

**Issue by ortizroberto** [jessesquires/JSQMessagesViewController#461]
Is it possible to handle mentions y hashtags from the text of a Message?

**Comment by vani2** [comment]
I can add mentions and hashtags support, but it'll be the same style as other links in text view. For me, it's a little bit ugly when hashtags are underlined, but for URLs I think it's ok.

**Comment by Nykho** [comment]
How did you do that? I don't know where I could plug a 3rd party plugin to do something after someone presses a link. I would really like to use Wildcard http://www.trywildcard.com/ with JSQMessagesViewController

**Comment by vani2** [comment]
@Nykho you simply add link to attributed text of text view. When handle a press on link via delegate.

**Comment by Nykho** [comment]
Oh, it was really simple. It worked! thanks @vani2

**Comment by StormFactory** [comment]
@vani2 or @Nykho Were either of you able to get this working? If so, did you submit a pull request?

**Comment by vani2** [comment]
@StormFactory I am. Give me some days.

**Comment by vani2** [comment]
I got it PR https://github.com/jessesquires/JSQMessagesViewController/pull/919

**Comment by brbgyn** [comment]
Thank you @vani2 !

**Comment by brbgyn** [comment]
@vani2 have you experienced a strange behavior of this code when scrolling the cells ?

I'm getting the hole cell text becoming a link sometimes and there are other times when cells with no @ or # turns into links too.

It's completely random, one time a cell can be a hyperlink and after scrolling not anymore.

![ios simulator screen shot 15 08 2015 15 43 52](https://cloud.githubusercontent.com/assets/6548984/9290331/832ae592-4364-11e5-85b6-5cda482950e6.png)
![ios simulator screen shot 15 08 2015 15 44 05](https://cloud.githubusercontent.com/assets/6548984/9290332/837a3e08-4364-11e5-8ec0-fa091b0d5614.png)

**Comment by vani2** [comment]
@brbgyn  It occurs while reusing cell's textview. May be you should clear all attributes in string before applying new ones. Look at comment for specific line of my commit (https://github.com/vani2/JSQMessagesViewController/commit/a71af60d6e7edb768b1ceae71be2215a135cf33e)

**Comment by brbgyn** [comment]
Thanks @vani2 , i just downloaded the fresh jsqmessagesviewcontroller and inserted your code and saw that it works as expected.

The issue must be in my customizing.

Sure has to do with reusing, as you said.

I'm gonna check on it latter. At least i have somewhere to start.

I deleted my old post when realized that the problem was in my project.

Thank you again

**Comment by brbgyn** [comment]
Hi again @vani2 

Fixed the reusing problem with attributes:

```
-(void) observeValueForKeyPath:(NSString *) keyPath
                      ofObject:(id) object
                        change:(NSDictionary *) change
                       context:(void *) context
{
    if ([keyPath isEqualToString:@"text"]) {
        // clear all attributes in string before applying new ones
        UIFont *backupFont = self.font; // here i back up the previous settled font, due to message bubble size calculations
        NSMutableAttributedString *attributedString = [self.attributedText mutableCopy];
        NSRange originalRange = NSMakeRange(0, attributedString.length);
        [attributedString setAttributes:@{} range:originalRange];
        self.attributedText = attributedString;
        
        [self highlightMentions];
        [self highlightHashTags];
        
        self.font = backupFont;
    }
}
```

But now i found another thing:

the texts in the message bubbles when using iOS 7 are invisible:

<img width="1104" alt="captura de tela 2015-08-16 as 19 40 30" src="https://cloud.githubusercontent.com/assets/6548984/9295746/277b4778-444f-11e5-9e92-17d2e4dc7855.png">


I managed to fix it by removing ```cell.textView.text = nil;``` in the workaround for iOS data detectors in JSQMessagesViewController

```
if ([UIDevice jsq_isCurrentDeviceBeforeiOS8]) {
            //  workaround for iOS 7 textView data detectors bug
            cell.textView.text = nil; // REMOVING THIS LINE SOLVES THE PROBLEM
            NSMutableAttributedString *mutableAttributedString = cell.textView.attributedText.mutableCopy;
            if (mutableAttributedString) {
                [mutableAttributedString addAttribute:NSFontAttributeName
                                  value:collectionView.collectionViewLayout.messageBubbleFont
                                  range:NSMakeRange(0, [mutableAttributedString length])];
                }
            else {
                cell.textView.attributedText = [[NSAttributedString alloc] initWithString:[messageItem text] attributes:@{ NSFontAttributeName : collectionView.collectionViewLayout.messageBubbleFont }];
                }
        }
```

But i would like to know if it is right to remove this line.
I managed to recreate this problem with the fresh jsqmessagesviewcontroller by replacing the original code with your code above

![ios simulator screen shot 16 08 2015 19 55 35](https://cloud.githubusercontent.com/assets/6548984/9295817/104c7a16-4451-11e5-8127-2817ab2a9c90.png)
...

Thanks

**Comment by KhaledAld** [comment]
@brbgyn  how you add the switch on the top of  the messages ???

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
