### ISSUE TITLE
Long text crash on adjusting toolbar height constraint

### ISSUE THREAD

**Issue by rkj2** [jessesquires/JSQMessagesViewController#469]
Hi, 

Thanks for this awesome component ! Testing it in an app for upgrading last component. Using static data on iPhone 5, ios 7.1.1.
1. Typing in 18 lines shows the bubble with text hidden after 13 lines. (minor?)
2. Typing 16 or more lines crashes the app intermittently. 

Here's the log I could get. I am new to using constraints, hope this info is useful. It breaks at method:
- (void)jsq_adjustInputToolbarHeightConstraintByDelta:(CGFloat)dy

Snapshot of error from console: 

![jsqmessageserror](https://cloud.githubusercontent.com/assets/101253/4141573/9929d8dc-33af-11e4-8ea9-b3f2fe83edde.jpeg)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
