### ISSUE TITLE
RELEASE 6.0 — ongoing release notes

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#476]
## Welcome to JSQMessagesViewController 6.0!

This issue serves to document ongoing and upcoming changes in [release 6.0](https://github.com/jessesquires/JSQMessagesViewController/milestones) of this library, which is scheduled to finally include media message support (#223), as well as many more exciting improvements. The goal is to release 6.0 by the end of September.

All development will take place on the [release-6.0 branch](https://github.com/jessesquires/JSQMessagesViewController/tree/release-6.0). Feel free to checkout this branch at anytime, but be aware that it will be rapidly changing and will not be guaranteed to be 100% functional 100% of the time.
### FAQs

> **Will this version of the library support iOS 8?**
> Yes. However, during development I will be targeting iOS 7. After iOS 8 is public, I will address any iOS 8-specific issues.
> 
> **Will this version of the library support interoperability with Swift?**
> Yes. This library currently uses uses [modern Objective-C](https://developer.apple.com/library/ios/releasenotes/ObjectiveC/ModernizationObjC/AdoptingModernObjective-C/AdoptingModernObjective-C.html) and follows current [best practices](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/) to facilitate Swift interoperability. However, no specific efforts will be made to support compatibility with Swift until it reaches 1.0.
> 
> **What about iOS 8 frameworks?**
> Once iOS 8 is public and [Cocoapods](http://cocoapods.org) supports [CocoaTouch Frameworks](https://developer.apple.com/library/prerelease/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_6_0.html), this library will be distributed as such. It will also include a bridging header for interoperability with Swift.
### Want to help?

Any and all feedback from the community will be greatly appreciated as we move forward with this release. Please let me know what you like, dislike, and what will or will not work for your specific uses of this library. Is that any documentation that doesn't make sense? Let me know. Is there an API that could be improved, or changed completely? Let me know.
## Major API changes

**Version 6.0 _will not_ be backwards compatible with 5.x.x.** I will be documenting all major library API changes below as they happen. Note, these will likely be brief as they are not intended to be a guide for migrating from 5.x.x to 6.0. This type of more in-depth documentation will happen at the time that 6.0 is released.
- **JSQMessageData Protocol:** all instances of `sender` have been replaced with `senderId` and `senderDisplayName`. See #389 for further details.
- _REFACTOR_ `JSQMessageData`, `JSQMessage`, and associated classes.
- _NEW_ **JSQMessageBubbleImageDataSource Protocol:** this new data source protocol replaces the use of `imageView` objects for message bubble image views. The `messageBubbleImageView` of a `JSQMessagesCollectionViewCell` is now _part of the cell prototype_. This change is reflected in `JSQMessagesCollectionViewDataSource` as well as `JSQMessagesBubbleImageFactory`. See #319 for further details.

``` objective-c
// Changes in JSQMessagesCollectionViewDataSource

// OLD
- (UIImageView *)collectionView:(JSQMessagesCollectionView *)collectionView bubbleImageViewForItemAtIndexPath:(NSIndexPath *)indexPath;

// NEW
- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath;
```
- _REFACTOR_ `JSQMessagesBubbleImageFactory`
- _RENAME_ `JSQMessagesAvatarFactory` --> `JSQMessagesAvatarImageFactory`
- _NEW_ **JSQMessageAvatarImageDataSource Protocol:** this new data source protocol replaces the use of `imageView` objects for avatar image views. The `avatarImageView` of a `JSQMessagesCollectionViewCell` is now _part of the cell prototype_. This change is reflected in `JSQMessagesCollectionViewDataSource` as well as `JSQMessagesAvatarImageFactory`. See #319 for further details.

``` objective-c
// Changes in JSQMessagesCollectionViewDataSource

// OLD
- (UIImageView *)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageViewForItemAtIndexPath:(NSIndexPath *)indexPath;

// NEW
- (id<JSQMessageAvatarImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView avatarImageDataForItemAtIndexPath:(NSIndexPath *)indexPath;
```
- _REFACTOR_ `JSQMessagesAvatarImageFactory`
- _REMOVE_ `JSQMessagesViewController` --> `typingIndicatorColor`
- _ADD_ `JSQMessagesCollectionView`
  - `typingIndicatorDisplaysOnLeft`
  - `typingIndicatorMessageBubbleColor`
  - `typingIndicatorEllipsisColor`
  - `loadEarlierMessagesHeaderTextColor`
- _REFACTOR_ `JSQMessage` model object, now an abstract base class (removed `text` property)
- _REFACTOR_ `JSQMessageData` protocol
  - `- (NSString *)text` method now optional 
  - added optional `- (id<JSQMessageMediaData>)media` method
- _NEW_ `JSQMessageMediaData` protocol - similar to `JSQMessageData`, but for media data
- _NEW_ `JSQTextMessage` : concrete model object, represents text messages
- _NEW_ `JSQMediaMessage` : concrete model object, represents media messages
- _UPDATE_ `JSQMessagesCollectionViewCell` now has a `mediaView` property
- _REFACTOR_ Demo project heavily refactored
- _UPDATE_ `JSQMessagesCollectionViewCell` now has a `mediaCellReuseIdentifier` method
- _UPDATE_ `JSQMessagesViewController` now has `outgoingMediaCellIdentifier` and `incomingMediaCellIdentifier` properties
- _NEW_ `JSQPhotoMediaItem` model object for representing photo media
- _NEW_ `JSQMessagesMediaPlaceholderView` view for async loading media
- _NEW_ `JSQLocationMediaItem` model object for representing location media

---
### [6.0-beta1](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.0-beta1) released

---
- Performance improvements and minor fixes (progress on #492)
- _UPDATE_ added `isMediaMessage` to `JSQMessageData` (#530)
- Use `MKMapSnapshotter` for location media items (#529)
- Resolved #522

---
### [6.0-beta2](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.0-beta2) released

---
- Resolved #534 
- _REFACTOR_ `JSQMessageBubbleImageFactory` can now be initialized with custom images. See #535 
- Resolved #544 
- Resolved #521 

---
### [6.0-beta3](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.0-beta3) released

---
- Update `JSQSystemSoundPlayer` 2.0.0

---
### [6.0-beta4](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.0-beta4) released

---
- Closed #524 
- _NEW_ `JSQVideoMediaItem` model object for representing video media (closes #504)

---
### [6.0-beta5](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.0-beta5) released

---
- _NEW_ Localization! :tada: Closes #237 
- _NEW_ Allow using custom nibs, #563
- _NEW_ `JSQMessagesMediaViewBubbleImageMasker` for masking media views to look like message bubbles
- _NEW_ Mask media items as bubble images (#571), includes new abstract `JSQMediaItem` class. For your media items you should now specify `appliesMediaViewMaskAsOutgoing = { YES / NO }`

---
### [6.0-beta6](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.0-beta6) released

---
- _REFACTOR_ Remove previously added `JSQTextMessage` and `JSQMediaMessage` in favor of absorbing them into the original `JSQMessage` class. Closes #602

**Comment by shivamkedia007** [comment]
Hii @jessesquires , thanks for the controller. It is really a great help. Can we please allow Audio files as well ?
