### ISSUE TITLE
Optional avatars in cells

### ISSUE THREAD

**Issue by atfermin** [jessesquires/JSQMessagesViewController#491]
Was wondering if you'll support the optional avatars in some cells (like in #308). Wanted a style like this: 
![woo3_chat3_private1](https://cloud.githubusercontent.com/assets/6512090/4282458/3767745c-3d59-11e4-91e4-1fd9301b3344.jpg)

But right now it just looks like this:
![screen shot 2014-09-16 at 12 25 37 pm](https://cloud.githubusercontent.com/assets/6512090/4282468/92836f94-3d59-11e4-88dc-e7640a7a2536.png)

**Comment by PaulTaykalo** [comment]
@mrojas Well, I finished with seting avatar image size, which is pretty private property of JSQ Cell  in `- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath` method :  
```
- (void)updateCell {
    if (!msg.isMediaMessage) {
        if ([msg isKindOfClass:[MyMessageClass class]]) {
            MyMessageClass * sendingMessageData = (MyMessageClass *) msg;
            if (sendingMessageData.failedToSend) {
                cell.avatarImageView.image = [UIImage imageNamed:@"message-sending-error-icon"];
                cell.avatarViewSize = CGSizeMake(22, 22);
                cell.textView.textColor = [UIColor redColor];
            } else {
                cell.avatarImageView.image = [UIImage imageNamed:@"one-pixel-empty-fake-avatar.png"] ;
                cell.avatarViewSize = CGSizeMake(1, 1);
                cell.textView.textColor = [UIColor blackColor];
            }
        } else {
            cell.textView.textColor = [UIColor blackColor];
        }
    }
}
```

So this will work for all newly created cells, and will not work cute , if I reload cells with peformBarchUpdates   

So, in case if I see that some message changed it's state to "Normal" -> "Failed"  or vice versa, I'm updating that cell directly:   
```
- (void)refreshSendingMessageData:(MyMessageClass *)message withError:(NSError *)error {
    int index = [self.demoData indexOfObject:message];
    NSIndexPath *in = [NSIndexPath indexPathForItem:index inSection:0];
    JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *) [self.collectionView cellForItemAtIndexPath:in];

    if (cell) {
        id <JSQMessageData> msg = self.demoData[in.item];

        if (!msg.isMediaMessage) {
            id<JSQMessageBubbleImageDataSource> bubbleImageDataSource = [self.collectionView.dataSource collectionView:self.collectionView messageBubbleImageDataForItemAtIndexPath:in];
            if (bubbleImageDataSource != nil) {
                cell.messageBubbleImageView.image = [bubbleImageDataSource messageBubbleImage];
                cell.messageBubbleImageView.highlightedImage = [bubbleImageDataSource messageBubbleHighlightedImage];
            }
            if ([msg isKindOfClass:[MyMessageClass class]]) {
                MyMessageClass *sendingMessageData = (MyMessageClass *) msg;
                if (sendingMessageData.failedToSend) {
                    cell.avatarImageView.image = [UIImage imageNamed:@"message-sending-error-icon"];
                    cell.textView.textColor = [UIColor redColor];
                } else {
                    cell.avatarImageView.image = [UIImage imageNamed:@"one-pixel-empty-fake-avatar.png"];
                    cell.textView.textColor = [UIColor blackColor];
                }

               // Update avatar View Size, and call animation block
                [UIView animateWithDuration:0.3 animations:^{
                    if (sendingMessageData.failedToSend) {
                        cell.avatarViewSize = CGSizeMake(22, 22);
                    } else {
                        cell.avatarViewSize = CGSizeMake(1, 1);
                    }
                    [cell layoutIfNeeded];
                }];

            } else {
                cell.textView.textColor = [UIColor blackColor];
            }
        }
    }
}
```

**Comment by gmansata6290** [comment]
I have used the incomingAvatarSize and outgoingAvatarSize for optional Avatars in the cellForItemAtIndexPath but it is getting applied to all the cells, but not applying to particular cell.  How I can reduce the space when the avatar is not present for a cell?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
