### ISSUE TITLE
Library support for delivery status: Implement handling of messages not sent 

### ISSUE THREAD

**Issue by estemendoza** [jessesquires/JSQMessagesViewController#516]
It would be good if there's a way, like a delegate, don't know, that we can flag a message like it wasn't sent, just like the Messages in iOS does, which flags the message with a red alert icon. And when the user tap on that icon, the message is re-sent.

On my implementation, I can detect when a message was sent or not, but I don't know how to show to the user that alert, despite a simple UIAlertView.

Thanks y congratulation on this wonderful tool.

**Comment by joshuawilde** [comment]
This code is preventing me from adding a subview to the `messageBubbleContainerView` as it automatically gets deleted. Is there a workaround fo this?

```
dispatch_async(dispatch_get_main_queue(), ^{
        for (NSUInteger i = 0; i < self.messageBubbleContainerView.subviews.count; i++) {
            if (self.messageBubbleContainerView.subviews[i] != _mediaView) {
                [self.messageBubbleContainerView.subviews[i] removeFromSuperview];
            }
        }
    });
```

**Comment by calvinsug** [comment]
can i insert a pending icon instead of set "pending" the bottom label ?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
