### ISSUE TITLE
Using attributed text in cell textView? (Message bubble isn't resized properly) 

### ISSUE THREAD

**Issue by vahotm** [jessesquires/JSQMessagesViewController#520]
Actually, it is sized properly until you add an image via <code>NSTextAttachment</code> to <code>NSAttributeString</code>.

I found out, that calculations in method <code>messageBubbleSizeForItemAtIndexPath:</code> of <code>JSQMessagesCollectionViewFlowLayout</code> are based on <code>messageData.text</code> property:

<pre><code>CGRect stringRect = [[messageData text] boundingRectWithSize:CGSizeMake(maximumTextWidth, CGFLOAT_MAX)
                                                     options:(NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading)
                                                  attributes:@{ NSFontAttributeName : self.messageBubbleFont }
                                                     context:nil];</code></pre>

It may be reasonable to add a delegate method to flow layout, that will calculate bounding rect for string, based on provided size, so if user wants to put attributed string into cell, he will be responsible for its sizing.

Another way is to add attributedString property to JSQMessageData protocol, and if it is not nil, all calculations should be done on attributed string - same as how it works in UILabel and UITextView.

**Comment by muuhoffman** [comment]
@jessesquires If I'm only trying to change the messageBubbleFont property for some cells, where and when should I set/reset it?
