### ISSUE TITLE
use of '@import' when modules are disabled

### ISSUE THREAD

**Issue by chadpod** [jessesquires/JSQMessagesViewController#541]
Pretty sure I'm an edge case, but based on some of the dependencies in my particular app, I wasn't able to enable modules and the recent change to using @import for core framework modules (fd192ba, love the check in message, haha) broke my build.

Xcode throwing the following errors all over the place when building:

use of '@import' when modules are disabled

I had to revert all 

```
@import UIKit
@import Foundation

// to

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
```

I did have it close with modules enabled, but then I had a C++ file failing to compile and I still had three of the above error messages in some of the top level JSQMessages classes (even though modules where enabled everywhere). Not sure there are any advantages to the new style of import of than being more concise? Regardless, does anyone have any insight into the above problem? Thanks!

**Comment by STShenZhaoliang** [comment]
add C++ have a error, use of '@import' when modules are disabled , how to do
