### ISSUE TITLE
error with location message

### ISSUE THREAD

**Issue by kajensen** [jessesquires/JSQMessagesViewController#565]
so everytime I send a location message, I receive a bubble with the loading animation. If I send it again, the 1st message has a pin with no surrounding info, and the 2nd is "loading". I've determined that the location data is correct since I have the on tap method for these bubbles open up apple maps in the correct location. what could be the issue?

**Comment by bacancyhima** [comment]
JSQLocationMediaItem is setting location each time when collectionview reloads. so it returns empty bubble until location reloads. i don't want to reload other JSQLocationMediaItem while adding new item, anyone having solution for this?
