### ISSUE TITLE
How to add margin (left or right) on the side of an avatar?

### ISSUE THREAD

**Issue by sebinsua** [jessesquires/JSQMessagesViewController#567]
Is it possible to put a margin-left or margin-right to the side of an avatar so that it is further away from the screen? Some kind of `avatarLeftRightMargin`.

How have other people been doing this?

**Comment by z8323664** [comment]
self.collectionView.collectionViewLayout.sectionInset = UIEdgeInsetsMake(...); 

This method is invalid. 

- (UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout insetForSectionAtIndex:(NSInteger)section
{
     return  UIEdgeInsetsMake(...);
}
Same as
