### ISSUE TITLE
Custom UIMenuItem's for each cell

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#569]
@jessesquires 

Would you be open to a PR which creates a method for JSQMessagesViewController subclasses to add custom UIMenuItem actions on a per cell basis?

This could be done outside of the library if we could use a JSQMessagesCollectionViewCell subclass, but it looks like that wouldn't be a simple task.

I'm thinking the change set might be pretty simple:
1. Add a few selectors to JSQMessagesCollectionViewCell. Something like:
- (void)jsq_messageBubbleLongPressAction1:(id)sender;
- (void)jsq_messageBubbleLongPressAction2:(id)sender;
- (void)jsq_messageBubbleLongPressAction3:(id)sender;
- Extend JSQMessagesCollectionViewCellDelegate to tell the delegate that one of the selectors was triggered

Then subclasses could:
1. Override -[collectionView:shouldShowMenuForItemAtIndexPath:] to add menu items
2. Override -[collectionView:canPerformAction:forItemAtIndexPath:withSender] to say YES to the new selectors
3. Implement the new delegate callbacks to take whatever action they deem appropriate.

I admit that adding selectors on JSQMessagesCollectionViewCell is a little gross, but I think the OS forces this pattern on us if we want to achieve per-cell menu items.

Any thoughts? Instant-veto?

**Comment by jaimeslr** [comment]
I've created a category following jesses's instructions, I think It's the cleaner way to do this but It would be great if the viewController could receive the action, for example: the user touches the "CustomAction1" and the event raises in the viewController. To do this I've added a protocol to the category but with no success. Can anyone point to an example showing how to implement a protocol via category?

//  JSQMessagesCollectionViewCell+MenuItems.h
#import "JSQMessagesCollectionViewCell.h"
@protocol MenuItemsDelegate <NSObject>
- (void)deleteMessage: (id)sender;
- (void)hideMessage: (id)sender;
@end

@interface JSQMessagesCollectionViewCell (MenuItems)
@property (nonatomic, weak) id <MenuItemsDelegate> menuItemsDelegate;
@end


//  JSQMessagesCollectionViewCell+MenuItems.m
#import "JSQMessagesCollectionViewCell+MenuItems.h"
@implementation JSQMessagesCollectionViewCell(MenuItems)
@dynamic menuItemsDelegate;
- (void)deleteMessage: (id)sender {
    [self.menuItemsDelegate deleteMessage: sender];
}
- (void)hideMessage: (id)sender {
    [self.menuItemsDelegate hideMessage: sender];
}
@end

This code is not working. When I set the cell's delegate to self (in the viewController) crashes with the following error:

[JSQMessagesCollectionViewCellOutgoing setMenuItemsDelegate:]: unrecognized selector sent to instance

The point is that that class is a subclass of JSQMessagesCollectionViewCell

It's weird... any help would be apreciated

**Comment by jessesquires** [comment]
Hey @jaimeslr -- you can't add properties/instance variables to a class via a category.

**Comment by jaimeslr** [comment]
Oppps... I thought it was possible, the code compiles but don't work. Thanks! Anyway I made it work using a category and the notification center :) Thanks for your help.

**Comment by vinnybad** [comment]
@jaimeslr if you really need to add data to an existing object, you could drop to the runtime and use associated objects.  That could become a maintenance nightmare if it's not used properly though.
