### ISSUE TITLE
Using NSAttributedString for messages, add to JSQMessageData protocol

### ISSUE THREAD

**Issue by jbouaziz** [jessesquires/JSQMessagesViewController#572]
Hi,

Great job on the library. Do you guys think about adding an `attributedText` property to the `JSQMessageData` protocol, overriding the `text` property if not `nil` ?

This PR looks particularly interesting, I don't know if you changed your mind: https://github.com/jessesquires/JSQMessagesViewController/pull/125

You can use it for images or simple text formatting.

Thanks

**Comment by vhesener** [comment]
I'd also like to request this feature. Also, if you are replacing methods, I'd like to suggest changing some of the method names on this protocol. It's hard to adopt the protocol on existing model objects without clobbering implementations. "text" is a pretty common method similar to "description" on NSObject. "isMediaMessage" is another one that I can see someone using the wrong way should they find it interfaced on my model object.

**Comment by jessesquires** [comment]
Good attempt at this here: #1059. We can use this as a reference when implementing in `8.0`

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
