### ISSUE TITLE
Add typing indicator

### ISSUE THREAD

**Issue by stephenwoodford** [jessesquires/JSQMessagesViewController#58]
It looks like you plan on doing it eventually since you've got an image for it already but it doesn't seem like its implemented. Please correct me if I'm wrong. I see you're making a lot of changes this week so if you don't get a chance to get to it, I'll try working on it after your changes seem to be slowing down. Thanks!

**Comment by thudientuso01** [comment]
Hi @davidchiles , the links to 2 classes above are not accessible any more.
Could you please update?
By the way, using your solution, can I replace the bubble by my own gif? I want the gif to be played, loop forever.
Thanks

**Comment by thudientuso01** [comment]
Hi @jessesquires ,
Using v5.0 or above, can I replace the bubble by my own gif. I want the gif to be played loop forever.
Much appreciation.

**Comment by chrisballinger** [comment]
This library is deprecated, please focus new development here:
https://github.com/MessageKit/MessageKit
