### ISSUE TITLE
Double-tap on textViews shows "copy/define" menu if selectable == YES

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#591]
We want to prevent this.

Possible solution:

Subclass UITextView and ignore double tap gestures

**Comment by BruceZCQ** [comment]
I use also 6.1.3 but the problem still exists.

**Comment by jessesquires** [comment]
thanks @BruceZCQ !

actually, i think i should re-open your original issue. :blush:
