### ISSUE TITLE
Cut off Bubbles

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#597]
@jessesquires 

I updated my project to use:
`
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
`

On an iPhone 5, iOS 7.1.2 (& the simulator):
The bubble images are cut off at the bottom, as though the image are being drawn too large.

On iPhone 5 running iOS 8.1 (or in the simulator) the same code does not exhibit the issue.

Additionally, when the current podspec is used the issue does not exhibit on iPhone 5, iOS 7.1.2 (or in the simulator):
`
pod 'JSQMessagesViewController'
`

I am still gathering information, but I wanted to check wether this was a known issue or not.

**Comment by harlanhaskins** [comment]
This seems to be crashing for iOS 7 for me, on line 235 of JSQMessagesCollectionViewCell.

```
2015-08-04 11:33:32.288 Bryx 911[2055:60b] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x17858610 V:[JSQMessagesLabel:0x19d67fb0(20)]>",
    "<NSLayoutConstraint:0x19b32750 V:[JSQMessagesLabel:0x19b331b0(20)]>",
    "<NSLayoutConstraint:0x19b27ce0 V:[JSQMessagesLabel:0x19d8ef20(0)]>",
    "<NSLayoutConstraint:0x19d8e1a0 V:|-(0)-[JSQMessagesLabel:0x19d67fb0]   (Names: '|':UIView:0x19b2cd60 )>",
    "<NSLayoutConstraint:0x19db7be0 V:[JSQMessagesLabel:0x19d67fb0]-(0)-[JSQMessagesLabel:0x19b331b0]>",
    "<NSLayoutConstraint:0x19d83ec0 V:[JSQMessagesLabel:0x19b331b0]-(0)-[UIView:0x19d97f80]>",
    "<NSLayoutConstraint:0x19bcb320 V:[JSQMessagesLabel:0x19d8ef20]-(0)-|   (Names: '|':UIView:0x19b2cd60 )>",
    "<NSLayoutConstraint:0x19bcb350 V:[UIView:0x19d97f80]-(0)-[JSQMessagesLabel:0x19d8ef20]>",
    "<NSAutoresizingMaskLayoutConstraint:0x19d75d20 h=--& v=--& V:[UIView:0x19b2cd60(38)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x19b32750 V:[JSQMessagesLabel:0x19b331b0(20)]>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
(lldb) po $arg1
layout constraints are not satisfiable. // <- This is the crash.
```
![screen shot 2015-08-04 at 11 36 06 am](https://cloud.githubusercontent.com/assets/853032/9064968/0b79f698-3a9d-11e5-8605-184d4eb42cdb.png)

**Comment by jessesquires** [comment]
@harlanhaskins - this is because the project is setup to break on exceptions. if you turn exceptions off, it should be fine. definitely dropping iOS 7 soon

**Comment by harlanhaskins** [comment]
We're dropping it too. We're not really concerned about JSQMessagesViewController rendering improperly on 7...
