### ISSUE TITLE
Multiple typing indicators - one per user, with avatar

### ISSUE THREAD

**Issue by iwxxcz** [jessesquires/JSQMessagesViewController#606]
It might be usefull in group chat if typing indicator would have avatar image of typing person

**Comment by andrew-stirling** [comment]
Hi Jesse, any progress on this issue?

Would be great to have this feature in the library.

**Comment by charliewilliams** [comment]
Could do this by refactoring to allow users to register their own nib for the footer view— then you can grab and configure it yourself to show user avatar, user name, etc.

I'd be happy to give this a shot. If you want to have a quick chat about how you'd like to have it done that could get things going in the right direction.

**Comment by jessesquires** [comment]
@charliewilliams - that would be awesome :+1: we can discuss details here.

I think the todo items are:

- Add avatar and top label to the existing typing indicator footer view
- Add method to configure this, ask for an `avatarImage` and `topLabelText`

**Comment by charliewilliams** [comment]
Good shout! That shouldn't be difficult.

**Comment by charliewilliams** [comment]
Actually @jessesquires looking at this we'd want a text typing indicator to be a different height than the bubble indicator, to hide the bubble and avatar views, and (possibly) to handle alignment differently. This all seems like it might be better to define a protocol that both footerViews can adhere to, or at the very least allow registering a subclass nib to replace the built-in one.

Possibly a little bit more work, but a more elegant/flexible result?

**Comment by jessesquires** [comment]
Hm... I think we should require the colors, and only allow the avatar to be optional. If an avatar isn't provided, then default to the existing behavior, without the avatar.

**Comment by jessesquires** [comment]
Oh -- we should also coordinate this work with #1524

**Comment by grosch** [comment]
This making any progress?

**Comment by charliewilliams** [comment]
Nope— I am maxed out for the near term, so won't be able to do this. Sorry! :/

**Comment by jessesquires** [comment]
Thanks @charliewilliams ! 👍  We'll take care of moving your PR forward

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
