### ISSUE TITLE
JSQMessagesComposerTextView adding lines causes unexpected spacing

### ISSUE THREAD

**Issue by dpopov** [jessesquires/JSQMessagesViewController#609]
Let me just start by saying that this library is awesome!
I was wondering anyone had any ideas what would cause this kind of behavior:
First line of text-
![screen shot 2014-11-10 at 4 31 28 am](https://cloud.githubusercontent.com/assets/5825122/4973736/18db8432-6893-11e4-9b98-5a3c18871d35.png)
Hit return-
![screen shot 2014-11-10 at 4 31 34 am](https://cloud.githubusercontent.com/assets/5825122/4973737/18dbabc4-6893-11e4-8e64-0314841db653.png)
And in this view I cannot seem to get scrolling to work to even allow the user to scroll out of this position. 

Any help or suggestions would be greatly appreciated.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
