### ISSUE TITLE
Better support for right-to-left languages

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#611]
Need an easier way to specify the "current sender" as being on the left or right hand side, and adapt other UI accordingly.

**Comment by oanaBan** [comment]
@jessesquires any ideea how can I turn off the support for right-to-left languages?
I have some UI issues:
![img_0657](https://cloud.githubusercontent.com/assets/7047087/6266527/759cf2be-b843-11e4-8add-c51662245ee9.PNG)

**Comment by mamon96** [comment]
@oanaBan i have the same problem :/

**Comment by jessesquires** [comment]
Hey @oanaBan - there currently **isn't** any kind of **specific** LTR language support, though it is possible. (This issue was opened to track the feature of making it easier to do.)

This looks like the problems in #695, #650, #592

**Comment by oanaBan** [comment]
Thanks.

My issue was that after updating the lib from 5.3.2 to 6.1 my entire app was messed up, not just the Messages screen, when using a RTL language (eg: Hebrew). 

I fixed this by "turning off" the RTL languages support by removing the other languages from  project - Info tab - Localizations section. After removing them my app looks ok also on Hebrew, it doesn't have specific RTL language support but at least my app is not messed up.

**Comment by jessesquires** [comment]
@oanaBan - The 6.0 release was *not* backwards compatible with 5.x. See the [release notes](https://github.com/jessesquires/JSQMessagesViewController/releases/tag/6.0.0) as well as #476 for details.

**Comment by jerembab** [comment]
Hi @oanaBan , how did you manage to move to the right place (in RTL) the texts at the bottom and the top of the bubble.. I'm stuck with this issue #1859 
thanks for your help

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
