### ISSUE TITLE
Aligning attributedText for messageBubbleTopLabel with bubble messages

### ISSUE THREAD

**Issue by kartikthapar** [jessesquires/JSQMessagesViewController#612]
Consider the output below.

![new](https://cloud.githubusercontent.com/assets/810861/4983603/24935d52-691c-11e4-8ada-8d88f82e6800.png)

Basically I want the attribute label to be left aligned with the text message.

(This is a question as I am not sure where to put in this constraint OR how this would role with Auto Layout.)

**Comment by NinoScript** [comment]
I tried setting the textInsets to align both the topLabel and the bottomLabel, but although it did work for `messageBubbleTopLabel`, it didn't work for `cellBottomLabel`.

Any idea why this doesn't work for the bottom label?

**Comment by SalvatoreAD** [comment]
@NinoScript  you can use this

`cell.cellBottomLabel.textInsets.right = 40.0`
