### ISSUE TITLE
Improve demo project

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#617]
New settings for the demo:
- [ ] option for async avatars
- [ ] option for different bubble styles (stroked bubbles + colors)
- [ ] implement tapping media bubbles?
- [ ] implement tapping avatars?

**Comment by pashikua** [comment]
Hi.

Can you tell when to expect example with stroke bubbles?

E.g. JSQMessagesBubbleImageFactory can be created with ... initWithBubbleImage:[UIImage jsq_bubbleRegularStrokedImage] but it seems there is no way to apply such image to outgoingMessagesBubbleImage or incomingMessagesBubbleImage to use in cell.

**Comment by jessesquires** [comment]
@pashikua - not sure what you mean. that is exactly how you would use it.

like this: https://raw.githubusercontent.com/jessesquires/JSQMessagesViewController/develop/Screenshots/screenshot3.png

**Comment by pashikua** [comment]
@jessesquires - I mean current example doesn't show stroke bubble images and it is not obvious how to do it.
outgoingMessagesBubbleImageWithColor method always will generate solid colour image.

**Comment by dopcn** [comment]
@jessesquires Hi, thanks for your great work first. I have a question about async avatar loading.  I learned from a previous issue that the way to do that is reload after update `avatarImageDataSource`. My question is when to reload? 

I didn't find some kind of `reloadVisibleCells` method so I just reload collectionView in `viewDidAppear`. It works for now but I'm not sure this is a proper and robust way. Any suggestion?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
