### ISSUE TITLE
Avatar completion in v6

### ISSUE THREAD

**Issue by ghazel** [jessesquires/JSQMessagesViewController#621]
Previously, I would return a UIImageView from `avatarImageViewForItemAtIndexPath` which was set up with a placeholder and `SDWebImage` to populate the real image once it was downloaded.

How is this intended to work for JSQMessages v6? I can return an avatar with a placeholder from `avatarImageDataForItemAtIndexPath` and kick off a `downloadImageWithURL` but how am I supposed to display the correct image once it is downloaded?

**Comment by mikrobi** [comment]
BTW, in case you use `collectionViewLayout.springinessEnabled = YES;` a `reloadData` will cause some user visible flickering when the images are downloaded and the spring animation is still in progress. In addition the `reloadData`triggers another spring animation (which is probably not what we want). I agree with @ghazel that only updating the `UIImageView` once the avatar image is loaded seems to be more elegant.

**Comment by swennemans** [comment]
The workaround @ghazel proposed works very good.

Having the option for setting the UIImage directly would be a very nice option. 
If you could use a library like sdWebImage (or HanekeSwift) you could also skip a lot of programming logic, especially in an usecase where you would have a groupchat.

For now I've also implemented this in `cellForItemAtIndexPath`
