### ISSUE TITLE
selection highlights avatar and bubble

### ISSUE THREAD

**Issue by ghazel** [jessesquires/JSQMessagesViewController#623]
Visible in the demo; Long-press on the message bubble highlights both the bubble and the avatar, instead of just the bubble.

**Comment by OmarPedraza** [comment]
@ghazel have you found any workaround for this?

**Comment by tunidev** [comment]
Any fix for 7.3.3 version ? I am providing  the avatars with :

    `override func collectionView(collectionView: JSQMessagesCollectionView!, avatarImageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageAvatarImageDataSource! {
        let message = self.viewModel.messages.value[indexPath.row]
        return message.actor.userID == self.senderId ? self.viewModel.currentUserAvatar : self.viewModel.withUserAvatar
     }`

**Comment by tunidev** [comment]
id that a bad practice :  

    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAtIndexPath: indexPath) as! JSQMessagesCollectionViewCell
        cell.avatarImageView.highlightedImage = cell.avatarImageView.image
}

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
