### ISSUE TITLE
'JSQMessagesBubbleImageFactory.Type' does not have a member named 'outgoingMessageBubbleImageViewWithColor'

### ISSUE THREAD

**Issue by macdonjo** [jessesquires/JSQMessagesViewController#629]
'JSQMessagesBubbleImageFactory.Type' does not have a member named 'outgoingMessageBubbleImageViewWithColor'

I'm using Swift to bridge and getting error from this code:

var messages = [Message]()
    var outgoingBubbleImageView = JSQMessagesBubbleImageFactory.outgoingMessageBubbleImageViewWithColor(UIColor.jsq_messageBubbleLightGrayColor())
    var incomingBubbleImageView = JSQMessagesBubbleImageFactory.incomingMessageBubbleImageViewWithColor(UIColor.jsq_messageBubbleGreenColor())

**Comment by datomnurdin** [comment]
Even I already initialize the instance, but still not working.

Instance.swift
```
let instanceJSQMessagesBubbleImageFactory = JSQMessagesBubbleImageFactory()
```

ViewController

```
var outgoingBubbleImageView = instanceJSQMessagesBubbleImageFactory.outgoingMessageBubbleImageViewWithColor(UIColor.jsq_messageBubbleLightGrayColor())
```

**Comment by datomnurdin** [comment]
So how the feedback?

**Comment by danielhklein** [comment]
Resolution for anyone else with this issue:

    let bubbles = JSQMessagesBubbleImageFactory()
    var outgoingBubbleImageView: JSQMessagesBubbleImage {
        return bubbles.outgoingMessagesBubbleImageWithColor(UIColor.jsq_messageBubbleLightGrayColor())
    }
    var incomingBubbleImageView: JSQMessagesBubbleImage {
        return bubbles.incomingMessagesBubbleImageWithColor(UIColor.jsq_messageBubbleGreenColor())
    }
