### ISSUE TITLE
How can I add a background static image in the chat list?

### ISSUE THREAD

**Issue by Ricardo1980** [jessesquires/JSQMessagesViewController#63]
Hello!

How can I add a background static image in the chat list (to my JSMessagesViewController subclass)?

I tried setBackgroundColor with colorPattern but the image is very strange and moves with the scroll.
What I want is just a static background image (like whatsapp).
I tried addSubview and bringToBack but no success.

Any idea or suggestion?
Thanks in advance,

**Comment by lenkaiser** [comment]
@ezrasuki This is a bit of a late response but it could help others that read this question.

If the contentMode of the image is, for example, set to UIViewContentModeScaleAspectFill then the image could be wider than the bounds of the view controller. A simple solution to this problem is to set the clipToBounds property on the imageView. This will make sure the image sliced to the bounds you set when initiating the image.

Example:
```
UIImageView *imgBackground = [[UIImageView alloc] initWithFrame:self.view.bounds];
[imgBackground setContentMode:UIViewContentModeScaleAspectFill];
[imgBackground setClipsToBounds:TRUE];
```

**Comment by jocelyn-cazes** [comment]
Hello Guys,

And how do you do in swift ?

Thanks ;-)

**Comment by lenkaiser** [comment]
Something like this? Code is untested so don't shoot the messenger :-)

```
let imgBackground:UIImageView = UIImageView(frame: self.view.bounds)
imgBackground.contentMode = UIViewContentMode.ScaleAspectFill
imgBackground.clipsToBounds = true
```

**Comment by Clever91** [comment]
it worked (swift 2)
class ChatMessageViewController: JSQMessagesViewController {
...............
 override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        
        let image = DefaultUser.getUserImage(DefaultUser.USER_BACKGOUND_KEY)
        let imgBackground:UIImageView = UIImageView(frame: self.view.bounds)
        imgBackground.image = image
        imgBackground.contentMode = UIViewContentMode.ScaleAspectFill
        imgBackground.clipsToBounds = true
        self.collectionView?.backgroundView = imgBackground
    }

................
}

**Comment by shravanteegala** [comment]
i put this using Objective-C.

UIImageView *imgBackground = [[UIImageView alloc] initWithFrame:self.view.bounds];
    
    imgBackground.image = [UIImage imageNamed:@"chat_background"];
    
    [imgBackground setContentMode:UIViewContentModeScaleAspectFill];
    [imgBackground setClipsToBounds:TRUE];
    
    self.collectionView.backgroundView = imgBackground;

its working.
