### ISSUE TITLE
Add messageId to JSQMessage

### ISSUE THREAD

**Issue by realsurfer** [jessesquires/JSQMessagesViewController#630]
Hello,

I have now encountered many situations in my code where it would be practical to assign a unique message id to each JSQMessage. The way I am working around this at the moment is using the date as unique identifier for the message but I would prefer to have a messageId property.

Thanks!

**Comment by savanpatel39** [comment]
import UIKit
import JSQMessagesViewController


class Message : JSQMessage
{
    var recipientId: String!
    
    public init(senderId: String!, recipientId: String!,displayName: String!, text: String!)
    {
        self.recipientId = recipientId;
        super.init(senderId,displayName,text); // 1.  Error shows here
    }

    public required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

This is my code...
I tried to subclass JSQMessage but when I call super.init() from my custom class it is saying "Argument labels '(_:, _:, _:)' do not match any available overloads". Can you tell me what am I doing wrong here.
