### ISSUE TITLE
How to change the contents of composer text view with auto resizing?

### ISSUE THREAD

**Issue by dereck009** [jessesquires/JSQMessagesViewController#632]
Changing the contents of `inputToolbar.contentView.textView.text/attribtedText` doesn't trigger auto resize for the input toolbar. 

(I need to change it programatically to support adding inline image to the composer text view)

**Comment by GianniCarlo** [comment]
Recently ran into something similar. @jessesquires will you be open to a pull request which modifies the demo:
- Add Camera option to the Action sheet
- Example of capturing that image and inserting it (landscape or portrait) in the textView
Reasons:
- iMessage does this.
- Fairly straight do it, no external library needed to do this

let me know what you think
