### ISSUE TITLE
Add more BarButtonItems to JSQMessagesToolbarContentView

### ISSUE THREAD

**Issue by VincentSit** [jessesquires/JSQMessagesViewController#634]
`JSQMessagesToolbarContentView` contains only two BarButtonItem is unreasonable. 
If I want to add more BarButtonItem would have to modify the source code. 

I think we should change the type of `leftBarButtonItem` and`rightBarButtonItem` to `UIView`, change to high-level class can have better compatibility (Any of its subclasses can be assigned to it.), and if so, I can add  any number of `BarButtonItem` or other views to the `leftBarButtonItem` or `rightBarButtonItem` of `JSQMessagesToolbarContentView`.

**Comment by rappier** [comment]
Hello JessesQuires, 

Glad to have your library but I am struggling with adding the additional tool bar button view as explained above. Also when i want to tap on any button/action sheet menu i want to swap the keyboard active with that view.  Similar like Viber or QQ, FB Messenger app does to show the Audio control view and back again to keyboard to type if 'Aa' button pressed. Can u please advice as to how can i achieve this.

**Comment by jessesquires** [comment]
@rappier - this kind of customization will likely require a custom fork of this library

**Comment by rappier** [comment]
Can you please give directions as to how we can add this feature to the library. As I am trying to understand your abstract classes but have faced issue to access those parameters to extent the cell and input toolbar functionality.
