### ISSUE TITLE
Cells don't fill whole width

### ISSUE THREAD

**Issue by natanrolnik** [jessesquires/JSQMessagesViewController#636]
A subclass of JSQMessagesViewController, that implements only the necessary methods (as described in the example project), shows the cells like this:

![img_4288](https://cloud.githubusercontent.com/assets/1164565/5091525/0d1adbe6-6f52-11e4-9e39-d5f79479cfff.PNG)

The strange thing is, that when you scroll, sometimes the cells show correctly for a fraction of second. Also, the height of the cells seems to be correct to the length of the message (if the width would be right).

Any ideas on what's wrong?

**Comment by marcoscurvello** [comment]
What type are you using for your hash property? I'm also using realm and I facing the same issue, how id you override the messageHash ? @natanrolnik

**Comment by iamyogish** [comment]
@natanrolnik @marcoscurvello I am implementing messageHash function as it's a required function of the JSQData protocol. But, I am still facing this issue. I have posted a question on SO as well - 

https://stackoverflow.com/questions/45792202/jsqmessagebubble-doesnt-resize-properly-while-using-realm-datasource

It'd be really helpful if you guys can provide any pointers on how to fix this issue. Thanks :)
