### ISSUE TITLE
Bridging to Swift, raises lldb error

### ISSUE THREAD

**Issue by macdonjo** [jessesquires/JSQMessagesViewController#637]
![screen shot 2014-11-19 at 7 24 41 pm](https://cloud.githubusercontent.com/assets/2490900/5117393/c13dafca-7021-11e4-911c-5958ada1faf0.png)

I have looked at 2 Swift implementations in other GitHub repositories but I'm stuck on this error in lldb. Once the segue goes to the view controller that inherits JSQMessagesViewController, after viewDidLoad() is executed, a general exception is thrown. 

Bit more info on what happens in lldb: http://stackoverflow.com/questions/26987227/execution-was-interrupted-reason-exc-bad-access-code-1-address-0xb06b9940/27006833#27006833

One of the implementations I followed: https://raw.githubusercontent.com/AttilaTheFun/MentorMe/0de81e567043380ea0e1693ab70c05137b3d9da2/MentorMe/MentorMenteeMessagesViewController.swift

I have commended out everything except and empty viewDidLoad(), so the ViewController does nothing but inherit from JSQMessagesViewController.

**Comment by jessesquires** [comment]
Looks like this is old. Closing out.

If you are still seeing this problem, please let me know!
