### ISSUE TITLE
Question: imageOrientation in JSQPhotoMediaItem

### ISSUE THREAD

**Issue by alexmalek** [jessesquires/JSQMessagesViewController#647]
Quick question - do JSQPhotoMediaItem support UIImage's with different orientations? e.g. UIImageOrientationRight. Thanks for the great pod!

**Comment by jessesquires** [comment]
Ah, thanks @dereck009 ! Please submit a PR for this change, if you can

**Comment by jessesquires** [comment]
All - please see #723
