### ISSUE TITLE
ios7 height offset on tableview

### ISSUE THREAD

**Issue by jamieomatthews** [jessesquires/JSQMessagesViewController#65]
Looks like there is a slight height offset issue (the top of the tableview is going underneath the navbar).  This only happends on ios7 and only after you have opened the keyboard.  This is iPhone 4s, but I would guess it happends on 5's too. 

For example, this picture is the demo app scrolled all the way up to the top:
![img_4882](https://f.cloud.github.com/assets/1930819/1537697/192c23de-4ccd-11e3-9390-11ebe88865fd.png)

**Comment by Abhi347** [comment]
I got the same issue, so I just used the following code in `viewDidLoad`

```
self.automaticallyAdjustsScrollViewInsets = NO;
self.edgesForExtendedLayout = UIRectNone;
```

Leaving it here, in case it helps someone (or if anyone can provide explanation).
