### ISSUE TITLE
[message bubble wrong side] Bubble image containers for media messages show incorrectly?

### ISSUE THREAD

**Issue by fpena** [jessesquires/JSQMessagesViewController#650]
I think this is because within the cellForItemAtIndexPath method in JSQMessagesViewController.m, the messageBubbleImageDataForItemAtIndexPath bit of data is not considered for media messages.  

Is there any workaround for this?

Thanks a lot!

![ios simulator screen shot 26-11-2014 17 10 43](https://cloud.githubusercontent.com/assets/440097/5217497/d99b59b0-761f-11e4-96d9-db1173cd6440.png)

**Comment by alexpchung** [comment]
Here is how I set the media view bubble direction in the collectionview datasource method:

#pragma mark - JSQMessages CollectionView DataSource

- (id<JSQMessageData>)collectionView:(JSQMessagesCollectionView *)collectionView messageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
    
    JSQMessage *message = [self.demoData.messages objectAtIndex:indexPath.item];
    // Determine if the message has media content
    if (message.isMediaMessage)
    {
        // Incoming or outgoing message?
        if (![message.senderId isEqualToString:self.senderId]) {
            [((JSQMediaItem *)message.media) setAppliesMediaViewMaskAsOutgoing:NO]; // Override default setting to allow incoming media message
        }
    }
    
    return message;
}

**Comment by Abhishek-addweb** [comment]
Not working

**Comment by bhushpar82** [comment]
Its working perfectly as per Jesse's comment!!

**Comment by happiehappie** [comment]
Sorry if this is a super amateur question but how do you add the bubble for medias in the first place

**Comment by commando24** [comment]
At the creation time of MediaItem just check the sender id 
let PhotoMediaItem = 
PhotoMediaItem.appliesMediaViewMaskAsOutgoing = (message.senderId == self.sender)
thats all. :)

**Comment by swati-daffodilsw** [comment]
Hi,

How can I remove curved corner from media messages? I just need rectangle view not with curved corner in media message?

**Comment by ryderjack** [comment]
This helped!

On a related note, is anyone able to set the mask of the placeholder media view? Looking for a tail-less placeholder but unsure where to set it. 

Able to apply the mask once the image has loaded and the cell is already in the collectionView but would be great for the placeholder to mirror the finished cell.

Cheers

**Comment by uknowmeright** [comment]
this is broken for me. ALL images have Incoming masks. I have followed the instructions here word for word and have not had any luck. Anyone else still struggling with this?

**Comment by apwelsh** [comment]
Did you try commando24's suggestion?  I seem to recall there are two requirements to get the right bubble for media items.  The first is that the senderID must be set to a valid value, and the 2nd that yhe bublerypw attribute of the media item must be set. 

You may want to debug your code, and inspect the value of the property at the time it is being set.  You are likely to find the error is in your code's logic.  I had an issue where I was pulling my hair out because the tool wasnt working the. Later discovered I had some test code in play that was preventing my correct code from working correctly.
