### ISSUE TITLE
InputToolbar does not follow keyboard

### ISSUE THREAD

**Issue by rahuljiresal** [jessesquires/JSQMessagesViewController#664]
I am using version 6.1.0, the latest commit on master branch.
When I tap on the UITextField, the keyboard appears on top of it. That is, the InputToolbar does not follow the keyboard. Since the keyboard is on top, user has to get rid of the keyboard to be able to press the "send" button.

Interesting thing is, it works perfectly in the demo project. I removed the dependency from Podfile and added the code from the demo project. And it still doesn't work with my project. Any help would be useful.

I could reproduce the same bug on all devices, simulator and real.

![ios simulator screen shot dec 5 2014 9 06 27 am](https://cloud.githubusercontent.com/assets/216346/5319427/19cdbc46-7c5e-11e4-8329-7e21a01d875b.png)

**Comment by SimonaMilchevska** [comment]
Hi. I am facing the same issue, and i am calling [super viewDidAppear] ... and nothing changed. Moreover, i removed the code from the demo, and the keyboard is working perfectly without this method: - (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    
    /**
     *  Enable/disable springy bubbles, default is NO.
     *  You must set this from `viewDidAppear:`
     *  Note: this feature is mostly stable, but still experimental
     */
    //self.collectionView.collectionViewLayout.springinessEnabled = [NSUserDefaults springinessSetting];
}

What am i doing wrong?
