### ISSUE TITLE
Crash when adding springBehaviour for dynamically inserted cells. 

### ISSUE THREAD

**Issue by markst** [jessesquires/JSQMessagesViewController#670]
I'm using `JSQMessagesViewController` paired with `NSFetchedResultsController` to present new messages when they are created on my managed context. 

From within my `controllerDidChangeContent:` I'm inserting new cells from within a `performBatchUpdates:` block. `insertItemsAtIndexPaths:`

This works fine for other collection views, however `JSQMessagesViewController` fails upon adding spring behaviour within `prepareForCollectionViewUpdates:` method. 

Error reported:

`<UIDynamicAnimator: 0x7fe2fd8b5c50> (2.407495s) in <JSQMessagesCollectionViewFlowLayout: 0x7fe2fb59d750> {{0, 0}, {375, 1543}}: body <PKPhysicsBody> type:<Rectangle> representedObject:[<JSQMessagesCollectionViewLayoutAttributes: 0x7fe2fb69ed40> index path: (<NSIndexPath: 0xc0000000000d0016> {length = 2, path = 0 - 26}); frame = (4 2170.7; 367 54); ] 0x7fe2fb7a7530  PO:(187.500000,2197.695801) AN:(0.000000) VE:(0.000000,0.000000) AV:(0.000000) dy:(1) cc:(0) ar:(1) rs:(0) fr:(0.200000) re:(0.200000) de:(1.000000) gr:(0) without representedObject for item <JSQMessagesCollectionViewLayoutAttributes: 0x7fe2fd97df10> index path: (<NSIndexPath: 0xc0000000000d0016> {length = 2, path = 0 - 26}); frame = (0 603; 0 0); 
`

**Comment by njstrifork** [comment]
+1, I get the same crash on performBatchUpdates: - problem is resolved by disabling before performBatchUpdates: and enabling afterwards

**Comment by jessesquires** [comment]
Thanks for the info @njstrifork !

Solution
-----------
1. Disable `springiness` before `performBatchUpdates:`
2. Re-enable `springiness` in the completion block
