### ISSUE TITLE
Exception raised by DEALLOC related to removing gesture recognizers on view

### ISSUE THREAD

**Issue by klivin** [jessesquires/JSQMessagesViewController#674]
Here is a pic of the exception.  Happens whenever the view is dealloc'd

http://screencast.com/t/mxy1ifVl

Best, and thank you very much Jesse!

**Comment by yeissonoviedo** [comment]
I am having the same problem using JSQ 7.0.1, iOS 9. It happens both on emulator and physical device.

All I have to do for this to happen is go to home screen and come back to the app.

**Comment by eliburke** [comment]
@jessesquires I wonder if this could be the same issue from #273 and #285 (KVO exceptions that can be ignored)

@klivin @yeissonoviedo Are you still experiencing this problem? Can you try "continue"ing after the exception?

**Comment by jessesquires** [comment]
ah, based on the screenshot, it looks like this *is*  #273 and #285
