### ISSUE TITLE
Working Swift example

### ISSUE THREAD

**Issue by Katafalkas** [jessesquires/JSQMessagesViewController#675]
Hey,

I am new to iOS development and have zero knowledge of Objective-C. Started Swift with Beta 6.0.1. So excuse me for silly questions.

This is an awesome project and would love to use it. As I seen from all FAQ's you don't seem like a big fans of Swift. After almost a day of experimenting and searching, I haven't really moved much. [Possibly I am just an idiot.].

As I can see from issues, people actually got it working with Swift. Is it possible to make some sort of working example ? Like you have Objective-C Demo in your repo ? I do assume you are all busy, so If you would somewhat help me with my sample I will try to write a demo for Swift.

I got up to this point. Swift does not show any errors in build. And all protocols seem to conform. But all I am seeing is blank page.
https://gist.github.com/Katafalkas/8336d283a5ccc84a4ec4

**Comment by mschinis** [comment]
No worries @jessesquires :) Love your work. Keep at it! I will be improving my example to provide a better documentation as soon as I get the app I'm working on published on the AppStore :sunglasses: 
@ogoog That looks pretty awesome.

**Comment by francisjervis** [comment]
I recommend taking a look at https://github.com/evermeer/EVCloudKitDao
Not mine, but helped me fix the avatar issues I was struggling with.

**Comment by jayisidoro** [comment]
Are there any updates on this issue? I'm currently building in swift and unable to get anything to load. The View controller remains empty despite using the demos provided above.

**Comment by mschinis** [comment]
It works fine for me @jayisidoro.

**Comment by jayisidoro** [comment]
@mschinis i tried yours and it didn't work. i just figured out how to get the tool bar to display along with messages being. However, i'm not able to adjust the height of the collectionview, nor the buttons on the navigation controller, or other arbitrary UI aspects. Is that something that needs to be done in the VC subclassing JSQMessagesVC or another location? thank you!

**Comment by lguerra10** [comment]
My images came distorted after downloading in Background I solve it adding
 mediaView.contentMode = UIViewContentModeScaleAspectFit; in the   JSQMessagesCollectionViewCell.m. Is this the right way to do it?

**Comment by jessesquires** [comment]
Replaced by #1608
