### ISSUE TITLE
the contentInset of collectionView in IOS7 is incorrect

### ISSUE THREAD

**Issue by webpatch** [jessesquires/JSQMessagesViewController#677]
when the JSQMessagesViewController loaded, the collectionView's contentInset is {64, 0, 44, 0},that's fine. 
![qq20141212-1](https://cloud.githubusercontent.com/assets/1796834/5409327/c49dd85c-8223-11e4-8686-5bc0ffcf37f5.png)

But, when i tap on the  send input field and scroll  the collectionView up and down (the keyboard show up and then hide),the collectionView's contentInset  become {0, 0, 44, 0} ,that's incorrect. 
![qq20141212-2](https://cloud.githubusercontent.com/assets/1796834/5409156/2d4cfa2a-8221-11e4-9839-1bad148abd57.png)

by the way, this is only happend in IOS7 . IOS8 is fine

**Comment by rksaraf** [comment]
Any update on this? I see it too

**Comment by jessesquires** [comment]
We're dropping support for iOS 7, going to close this issue.
