### ISSUE TITLE
[Using SDWebImage with avatarImageView] Customized avatarImageView property on JSQMessagesCollectionViewCell is distorted until you scroll.

### ISSUE THREAD

**Issue by mitchellporter** [jessesquires/JSQMessagesViewController#678]
First off, I searched through the previously issues tagged for "help" and I realize that this issue has been discussed before, but I still can't seem to figure out what the best way is to approach this.

Before I go into detail, I'm going to show exactly how I'm customizing my avatars. Here's my custom implementation of cellForItemAtIndexPath: inside of my JSQMessagesViewController subclass:

``` Objective-C
- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *) [super collectionView:collectionView cellForItemAtIndexPath:indexPath];
    [cell.avatarImageView sd_setImageWithURL:[NSURL URLWithString:self.userSession.profilePictureUrl] placeholderImage:[UIImage imageNamed:@"profilePic"]];
    cell.avatarImageView.layer.cornerRadius = cell.avatarImageView.frame.size.width / 2;
    cell.avatarImageView.clipsToBounds = YES;
    return cell;
}
```

This almost works perfectly. The only thing is with the above code, the avatar image view should be a perfect circle, but when the collection view first loads, the avatar image views have pointy edges on the "sides" of the image view. It's like the code was 98% of the way finished transforming the square image I provided into a perfect circle and just stopped short.

If I scroll up and down, the avatar image views no longer have the pointy edges, and they are now perfect circles.

I'm not quite sure if I'm tackling this the wrong way, or if I'm missing one final step.

It looks like it used to be easier to access the avatar image views in previous versions of this repo, but now those methods have been deprecated. It also looks like most of the questions surrounding this type of issue have focused on JSQPhotoMediaItem but never on the cell's avatar image view.

I thought about just importing SDWebImage and my custom class into the JSQMessagesViewController class file and hacking around this where the avatarImageView is being set but I don't know how to import my custom class that contains the relevant image URL since JSQMessagesViewController is located in the pod, and I'm also not sure if that would even be the correct way to solve this problem.

Any help is greatly appreciated.

**Comment by Mo7amedFouad** [comment]
@mitchellporter you can use to preload the image without init a imageview
``` 
[[SDWebImageManager sharedManager] downloadImageWithURL:self.userSession.profilePictureUrl options:0 progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        self.currentUserAvatar.avatarImage = [JSQMessagesAvatarImageFactory circularAvatarImage:image withDiameter:48];
    }];
```

**Comment by trungnguyen1791** [comment]
Hi guys,
What happened if i have a chatroom? For example, we have 10 users inside a chatroom.
So do we need to create 10 globals JSQMessageAvatarImageDataSource object? 
I'm still confuse with that case. 
Better if some one can explain this. Thanks for your help.

**Comment by akhilcb** [comment]
Even I have same doubt as @trungnguyen1791. How do we handle if there are 'n' number of users in a chat room and someone can join dynamically in between. I am not quite clear about how to handle this case. Are we supposed to have reference of collection view and indexpath in JSQMessage subclass and keep refreshing avatar image from URL by calling reload indexpath methods? That sounds like breaking MVC again. Is there a better way? Can someone guide please.

**Comment by martintjandra** [comment]
If it is me, I will have an NSMutableDictionary that map between senderId and the related JSQ avatar image. Everytime the chatroom request new avatar image from new user that join the chat room that my NSMutableDictionary doesn't have, I will create a JSQ avatar with placeholder, while the avatar image and avatar highlight image is requested from SDWebImage. That way, when the image finally received, it will be updated on the view and replace the placeholder. If the image is already on the cache though, SDWebImage will immediately return the image from the cache.

**Comment by BhavinBhadani** [comment]
I done everything with this avatars ... download from url using SDWebImage but still not display images for every users ...  I really feel that you have to give option to fill image with URL too ... rather than provide imageview @jessesquires
