### ISSUE TITLE
Layout issue with iPad when initiating a JSQMVC with stored JSQMessages

### ISSUE THREAD

**Issue by zallanx** [jessesquires/JSQMessagesViewController#680]
I searched for the iPad layout issue, and it appears that this was previously an [issue](https://github.com/jessesquires/JSQMessagesViewController/issues/533) with only split views, which was resolved in JSQ 6-beta2. However, I am encountering this issue not with newly created `JSQMessages` (i.e. such as newly sent messages), but only with those stored and pulled from cache.

This is also only an issue with the iPad, and not with the 6+.

As seen, this is what happens when the messages are initially sent (working in perfect order)
![](http://i.imgur.com/Xw2zUk0.png)

And when returning to this `JSQMessageViewController`, this is the new appearance:
![](http://i.imgur.com/Sw7OobH.png).

I am using the newest JSQ 6.1.0.

**Comment by zallanx** [comment]
First, Happy new year @jessesquires !

So, I finally got around to implementing the hash, and it seems I may not have done so properly because the same issue is still showing up for iPad.

Just to confirm , here is what I have done:

1. In my custom model class .h, I have the following: `CustomMessageClass : JSQMessage <JSQMessageData>`

2. In the .m, I implement the following:
```
- (BOOL)isMediaMessage {
    return NO; //only able to send text-based messages 
}

- (NSUInteger)hash {
    return self.senderId.hash ^ self.date.hash ^ self.text.hash;
}
```
Am I missing anything in terms of implementation?

**Comment by jessesquires** [comment]
Happy new year!

That looks correct to me. In fact, `JSQMessage` provides these implementations so you shouldn't have to in your subclass.

**Comment by jarrillaga** [comment]
Hi ! I'm having the exact same problem only in iPad. Did you solve it? Thanks very much !

**Comment by Abhijay** [comment]
Anyone find a solution?

**Comment by ObjSal** [comment]
So the issue is because messageBubbleLeftRightMargin is set to 240 when running in the iPad, and works perfectly when running on iPhone because it sets the value to 50.

What I end up doing to fix this issue is to set `self.collectionView.collectionViewLayout.messageBubbleLeftRightMargin = 20;` from my ViewController's viewDidLoad method.

I hope it helps everybody using this cool project on an iPad.

**Comment by harlanhaskins** [comment]
My [Pull Request](https://github.com/jessesquires/JSQMessagesViewController/pull/1238) might fix this.

**Comment by ObjSal** [comment]
Hello harlanhaskins, I don't know if your PR fixes this issue, but it doesn't addresses the main issue, which is that messageBubbleLeftRightMargin is set to a high/wrong default value for the iPad.

The fix I suggested fixes the issue cleanly without messing with the original project source code, perhaps we should recommend @jessesquires to set a lower default value for messageBubbleLeftRightMargin when running on the iPad.

**Comment by mariusw** [comment]
Thank you so much for this, @ObjSal !

**Comment by ObjSal** [comment]
You're welcome @mariusw :+1: , I hope the fix is added to the project, I didn't create a pull request just because is fixable from outside.

**Comment by basilmariano** [comment]
`- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    context.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];
}`

this fixed the issue in my case :)

Hopefully this will help.

God bless
