### ISSUE TITLE
Display Text *and* Media

### ISSUE THREAD

**Issue by knitterb-razzle** [jessesquires/JSQMessagesViewController#681]
I really like this control, thank you!  One thing I can't figure out is how to include text AND a media item (video, photo) at the same time?  It appears this is one or the other?  Many messaging systems (MMS, Hangouts, WhatsApp) now allow for text to accompany the media message.  Is this possible?  If not, can I request that this is added?

**Comment by felipericieri** [comment]
Hi! First of all, thanks (too) for this amazing library!
I think i got the same need. I need to show text and media together (just like whatsApp do). I saw this is possible using JSQMessageMediaData protocol, but I need also resize my textView height to its content size and the method "mediaView" (which returns the UIView to display on UICollectionViewCell) is called after "mediaViewDisplaySize" (which returns its CGSize). So, after the UIView actually exists, I setted its width and height. How can I handle this?
Thank you again!

**Comment by felipericieri** [comment]
Hmmm.. I see! So, we have to show the content in separated bubbles. Ok!
Thanks!

**Comment by knitterb-razzle** [comment]
That's what we had to do too, separate bubbles for now.  Not the worst thing in the world, but does make the logic for displaying messages a little challenging.  I'm hoping to get a chance in a month or two to create a patch (pull request) with this functionality built in.  Struggling to find the time! :(

**Comment by avently** [comment]
We are awaiting your PR:)

**Comment by mverderese** [comment]
I was just going to +1 this, but after looking through the documentation, it seems like it's pretty easy to achieve this effect by implementing the `mediaView` and `mediaPlaceholderView` method in `JSQMessageMediaData`. I guess the pull request would just have to include an out-of-the-box wrapper for these methods to combine the message and image into one `UIView`

**Comment by gmansata6290** [comment]
@mverderese have you implemented Img and text in the same bubble? if yes then can you just guide me how to resize the bubble as per the content size of the textview?

**Comment by victorstewart** [comment]
+1

this would be a great addition.

 1) having the media (photos or videos) mixed with text in the textView input field, plus 2) having a default message cell type that allows 1 to n photo or video items, plus some text.

I have needs for these now, so I'm going to start building them. Maybe I'll just share the code here after?

P.S. (Link Previews would also be really nice :). I need to build those too now. )

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
