### ISSUE TITLE
App crashes when Send button is pressed

### ISSUE THREAD

**Issue by JinkProject** [jessesquires/JSQMessagesViewController#682]
Here's the error log: 

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error! required method not implemented in subclass. Need to implement -[JSQMessagesViewController didPressSendButton:withMessageText:senderId:senderDisplayName:date:]'

Yet I have implemented the code it's saying I haven't implemented in my code. I subclassed the JSQMessagesViewController and I'm using Swift. Anybody else run into this issue?

**Comment by sbauch** [comment]
Okay I have a similar and very strange issue. The send button crashes the app when I run it on my device (iPhone 6 on iOS 8.1.2). It works great on the simulator.

Further complicating things is the fact that I'm using Rubymotion (posting this on the RM google group as well, will report back if anything helpful comes of that).

Here's my implementation of didPressSendButton:withMessageText:senderId:senderDisplayName:date

Happy to post more of the view controller if that will help.

````ruby
def didPressSendButton(button, withMessageText:text, senderId:senderId, senderDisplayName:senderDisplayName, date:date)
    NSLog('pressed')

  #   JSQSystemSoundPlayer.jsq_playMessageSentSound

    message = JSQMessage.alloc.initWithSenderId(senderId, senderDisplayName:senderDisplayName, date:date,text:text)

    self.messages << message

    finishSendingMessageAnimated(true)

  end
````

Lastly, there is no help in the device logs, and the "pressed" statement isn't logged:

````
Jan  9 11:30:17 Samuel-Ss-iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.sambauch.countyoself[0x396b][263]) <Warning>: Service exited with abnormal code: 1
Jan  9 11:30:17 Samuel-Ss-iPhone SpringBoard[53] <Warning>: Application 'UIKitApplication:com.sambauch.countyoself[0x396b]' exited voluntarily.
Jan  9 11:30:17 Samuel-Ss-iPhone assertiond[63] <Warning>: pid_suspend failed for <BKNewProcess: 0x12de2b8b0; com.sambauch.countyoself; pid: 263; hostpid: -1>: Unknown error: -1, Unknown error: -1
Jan  9 11:30:17 Samuel-Ss-iPhone assertiond[63] <Warning>: Could not set priority of <BKNewProcess: 0x12de2b8b0; com.sambauch.countyoself; pid: 263; hostpid: -1> to 2, priority: No such process
Jan  9 11:30:17 Samuel-Ss-iPhone assertiond[63] <Warning>: Could not set priority of <BKNewProcess: 0x12de2b8b0; com.sambauch.countyoself; pid: 263; hostpid: -1> to 4096, priority: No such process
Jan  9 11:30:17 Samuel-Ss-iPhone UserEventAgent[20] <Warning>: id=com.sambauch.countyoself pid=263, state=0
Jan  9 11:30:17 Samuel-Ss-iPhone wifid[37] <Notice>: WiFi:[442513817.716064]: scanCache: Purging scan cache
Jan  9 11:30:22 Samuel-Ss-iPhone locationd[60] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
````

**Comment by keshavkishore09** [comment]
Facing the same problem, error is - 
 Error! required method not implemented in subclass. Need to implement -[JSQMessagesViewController didPressSendButton:withMessageText:senderId:senderDisplayName:date:]'
 I am using swift and implemented all the code in subclass of JSQMessageViewController.

@JinkProject  What was the issue with storyboard connection?
