### ISSUE TITLE
scrollToBottom delayed when pushed in

### ISSUE THREAD

**Issue by bzmario** [jessesquires/JSQMessagesViewController#687]
When I push a `JSQMessagesViewController`，I found there's a delay about half a second to scroll to bottom. So I look for the reason and I find codes in `viewWillAppear` method:

```
dispatch_async(dispatch_get_main_queue(), ^{
        [self scrollToBottomAnimated:NO];
        [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
    });
```

I'm not sure why you put these codes in a `dispatch_async`  block, but after take them out:

```
//        dispatch_async(dispatch_get_main_queue(), ^{
        [self scrollToBottomAnimated:NO];
        [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
//        });
```

The delay has gone.

**Comment by trungnguyen1791** [comment]
Sadly but in iOS 8.3 and iPhone 6, it doesn't work. If i disable that "dispatch_async", the delay has gone.
But the collection view didn't actually scroll to the bottom. It just scroll to the "latest - 1" row. And the latest row are invisible by toolbar. 

Anyone have same issue?

**Comment by spencerwhyte** [comment]
I have the exact same issue even with the latest. You can even see the issue in the example project.
