### ISSUE TITLE
Link colors flicker when updating cells in high frequency

### ISSUE THREAD

**Issue by pflenker** [jessesquires/JSQMessagesViewController#690]
Hi,

I set the colors of my text chat bubbles in this function: 
 `override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell` like this:

``` Swift
if let textView = cell.textView {
            textView.textColor = UIColor.whiteColor()
            textView.linkTextAttributes = [NSForegroundColorAttributeName:myColor, NSUnderlineStyleAttributeName: NSUnderlineStyle.StyleThick.rawValue,
                NSUnderlineColorAttributeName: mycolor];
        }
```

However, in situations where I load multiple images for image cells and refresh the collectionview each time an image has finished downloading, I can observe a flickering of the links in the text view. It flickers between having the default text color and the color I specify for links.

I am not entirely sure if this has something to do with JSQMessagesViewController, but I didn't find anything using google, so I thought I'd ask here.

Thanks for your time,

Philipp

**Comment by eschanet** [comment]
Has anyone found a fix yet?

**Comment by brokeniceinteractive** [comment]
I have the same issues, anyone solved this?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
