### ISSUE TITLE
Implement UIMenu "copy" actions for media items/cells

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#693]
Currently, the library ignores the `copy` action for media cells.

**Media items and data to copy to clipboard:**
- [x] `JSQPhotoMediaItem` — copy the photo (done in #1447)
- [x] `JSQLocationMediaItem` — ~~copy the location coordinates? copy the address (requires reverse-geocoding)?~~ copy [map link](https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html) (done in #1447)
- [ ] `JSQVideoMediaItem` — ~~copy the URL?~~ copy the video

**Any feedback is welcome here!**

---

Remaining TODOs:
- See progress from PR #1447
- Once `JSQVideoMediaItem` is implemented, let's make all protocol methods non-optional

**Comment by jeffkibuule** [comment]
I gave this one a try. First *real* open-source contribution, plus some ok-ish tests. Still scratching my head on video, it'll copy, but shows up as a generic file instead of a video. I left out support for it at the moment.

**Comment by wdcurry** [comment]
ignoring the need to implement copy, is the pathway to a custom action on a media bubble available at this point in time?

**Comment by wdcurry** [comment]
For what it is worth, i augmented JSQMessagesViewController.m to not ignore the menu, and then trapped the copy selector to remove it from the popup menu.. good to go.

**Comment by jessesquires** [comment]
@wdcurry - see https://github.com/jessesquires/JSQMessagesViewController/releases/tag/7.1.0

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
