### ISSUE TITLE
Complete layout customization

### ISSUE THREAD

**Issue by alecgorge** [jessesquires/JSQMessagesViewController#694]
Great library! I've been using it for quite a while now.

Is it possible to completely customize the layout of the messages and associated views? I am building an app and this handles many of the subtleties I like to tackle in one portion of my app but it isn't a chat app in the traditional sense.

For example: I would like every message to be full width and the name/avatar to be placed below the message.

If I need to fork the library and make bigger changes to the UICollectionView, that is alright, I would just appreciate some pointers.

**Comment by alecgorge** [comment]
Thanks for your help @jessesquires and @weekwood! I have gotten the customized look that I wanted.

I have been working on adding attributed text (most notable NSTextAttachment) support to JSQMessagesComposerTextView and the cell text view.

It has been going very well, one of the few issues remaining is with the height calculation of the JSQMessagesComposerTextView. It is always too short for the size of the image (but you can scroll and see the whole thing) and the compose view gets stuck under the keyboard when there is a NSTextAttachment in it.

Where is the height/layout calculations for the composer? Or is it all done in AutoLayout?

**Comment by itinance** [comment]
Would it be a solution to register own nib-files instead of the builtins? if yes, how could one achieve this?

**Comment by xilin** [comment]
I'm also curious about this topic. Is there a better way to do the customization?

**Comment by rkittinger** [comment]
Has anyone had experience getting animated gifs embedded in text inside the chat bubbles? NSTextAttachment and using NSAttributedString does not animate the images...
