### ISSUE TITLE
[message bubble wrong side] wrong positioning of outcoming bubble image?

### ISSUE THREAD

**Issue by cbarbera80** [jessesquires/JSQMessagesViewController#695]
Hi, i've a problem with outcoming bubble image. This is what i Get
![ios simulator screen shot 25 dic 2014 21 04 14](https://cloud.githubusercontent.com/assets/3016826/5554833/c3c92a98-8c79-11e4-8273-9ae8b8128f35.png)

How I fix that?

**Comment by lizapovalyaevaa** [comment]
I just corrected this problem. My mistake was self.sendID = NSNumber* instead self.sendID = @""
