### ISSUE TITLE
Cocoapods Swift Framework

### ISSUE THREAD

**Issue by bassrock** [jessesquires/JSQMessagesViewController#698]
I am using the swift cocopaods support and when I try to initialize my message view controller with:

```swift
var messageViewController: MessageViewController = MessageViewController(nibName: "JSQMessagesViewController", bundle: NSBundle(forClass: JSQMessagesViewController.self))
```

I get the following error:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/auser/Library/Developer/CoreSimulator/Devices/22C080F4-CC98-47CF-8E2D-475CFC29BDBF/data/Containers/Bundle/Application/53F2BE8F-B7EE-4301-B3B0-4798058B636D/AnApp.app> (loaded)' with name 'JSQMessagesToolbarContentView''
```

It seems like the controller is not loading resources from it's own bundle. For instance if I change the above initializer to:

```swift
var messageViewController: MessageViewController = MessageViewController(nibName: "JSQMessagesViewController", bundle: NSBundle.mainBundle)
```

The error messages becomes:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/auser/Library/Developer/CoreSimulator/Devices/22C080F4-CC98-47CF-8E2D-475CFC29BDBF/data/Containers/Bundle/Application/53F2BE8F-B7EE-4301-B3B0-4798058B636D/AnApp.app> (loaded)' with name 'JSQMessagesViewController''
```

Any ideas on how to make the framework load files from within it's own bundle?

**Comment by jessesquires** [comment]
Figured out the issue here. CocoaPods 0.36 uses frameworks, so `[NSBundle mainBundle]` needs to be replaced with `[NSBundle bundleForClass:]`

Related: #710

**Comment by bassrock** [comment]
OK cool! from the looks of it to, that should be a non breaking change to the library as the static libs should still work with the main bundle change.

**Comment by jessesquires** [comment]
Exactly!

Set this issue for milestone 6.1.2

**Comment by bassrock** [comment]
Sweet! Thanks!

**Comment by mypark** [comment]
I'm still getting this issue on cocopods 0.36 and 6.1.3 ... can you help diagnose or debug?  It was working fine until I reinstalled the pods directory.

**Comment by baoluo** [comment]
Same here, cocoa pods 0.39b4 and JSQ 6.1.3 ..

**Comment by jessesquires** [comment]
Hey guys -- I would update to the latest version of the library

**Comment by baoluo** [comment]
I did the update and it's working properly, thanks @jessesquires
