### ISSUE TITLE
Possible message rendering bug

### ISSUE THREAD

**Issue by kartikthapar** [jessesquires/JSQMessagesViewController#703]
[Not sure if this has been filed!]

Use the demo project with extra messages. When pushing via storyboard or programmatically, there seems to be some weird animation of cells moving from left to the right. (In fact, I believe it's just a scroll to bottom issue). This effect is more noticeable when the last few messages in the view are sent by the application user.

In my application, the effect is much more visible as compared to the demo project. I have attached two videos for you to see.

Currently, I have enabled animation in `viewWillAppear:` at line 232:

```
[self scrollToBottomAnimated:YES];
```

See the video attached.

(Some things you can't unsee bro!)

Apparently, I can't upload the videos here. Please refer to the dropbox link: https://www.dropbox.com/sh/nrjo1h9fo762d16/AACISmQwR13Ktzlx0yCuubo4a?dl=0.

Thanks very much.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
