### ISSUE TITLE
Clean collectionView after a TransitionPush animation

### ISSUE THREAD

**Issue by TediumRemedy** [jessesquires/JSQMessagesViewController#704]
Hi
I am trying to animate the collectionView. Basically I need the user to be able to swipe it and have a clean collection view after the animation has finished. Here's what i am doing:

-(void)onSwipe:(id)sender {
    [self.messages removeAllObjects];
    [self finishReceivingMessageAnimated:NO];
    [self finishSendingMessageAnimated:NO];
    CATransition *animation = [CATransition animation];
    [animation setDuration:1.5];
    [animation setType:kCATransitionPush];
    [animation setSubtype:kCATransitionFromRight];
    [animation setTimingFunction:[CAMediaTimingFunction      functionWithName:kCAMediaTimingFunctionEaseInEaseOut]];
[self.collectionView.layer addAnimation:animation forKey:nil];
}

This method performs an animation, but after the animation has completed there's sometimes one of the "previous" messages (that were there before the animation) appearing on top of the collection view, its like i haven't called the delegate's [messages removeAllObjects]. Why is this happening and is there a way i can get a clean collectionView? I would really like to have the collectionView "float away" with all the message bubbles and "float in" clean.

Thank you and Happy holidays!

**Comment by jessesquires** [comment]
Hey @TediumRemedy - you might want to consider using the `UIView` block-based animation API with collection view's `performBatchUpdates:`

Otherwise, this might be a good question for StackOverflow :smile:
