### ISSUE TITLE
Use CocoaTouch framework with Cocoapods 0.36

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#710]
Update project to use frameworks.

http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

Pending final release of CocoaPods 0.36

**Comment by Antairez** [comment]
Hi Jesse I've just read the article about the new pod framework, is there anything that us users have to do to cope with the update?

**Comment by jessesquires** [comment]
@Antairez - No, everything should be ok! :+1: 

If not, I'll put it in the release notes. :smile:

**Comment by jessesquires** [comment]
v7.0 now works with cocoa touch frameworks.
