### ISSUE TITLE
Problems with VC transitions/animations (/navigationController swipes) and JSQMessages

### ISSUE THREAD

**Issue by kajensen** [jessesquires/JSQMessagesViewController#711]
I'm experiencing a bug that is quite unusual, and I'm wondering if anyone else has experienced something before I dig deeper into it. I'm using JSQMessages in a couple VCs and after exiting (perhaps after sending a message?...its not every time or even the majority of the time so I've been hesitant to look into it immediately)- the VC transitions, gestures and animations between views gets screwed up: super fast, not really even animating even with swipes.

For all I know it could be my own code, but I'm really just using the demo code (from the 6 BETA release a month or so ago) with some slight modifications, and I'm 99% sure it happens in the Messages VC. Just wondering if anyone else can shed some light on whats going on. Thanks.

**Comment by jessesquires** [comment]
Hey @kajensen - it's hard to say without seeing some code.

If you're still on that beta release, I would highly suggest updating to the latest release.
