### ISSUE TITLE
Typing indicator doesn't move to the left edge of the screen when orientation is changed from vertical to horizontal

### ISSUE THREAD

**Issue by TediumRemedy** [jessesquires/JSQMessagesViewController#712]
This code seems to solve the problem, but would be nice if library did that by itself:

-(void)deviceOrientationDidChange:(id)notification {
    if(self.showTypingIndicator) { //let's update typing indicator position
        self.showTypingIndicator = NO; //hide it for a while
        [self.collectionView reloadData];
        self.showTypingIndicator = YES; //and show it again, so it appears where it should
        [self.collectionView reloadData];
    }
}

**Comment by TediumRemedy** [comment]
*updated the question with the solution

**Comment by jessesquires** [comment]
Thanks @TediumRemedy !
