### ISSUE TITLE
Incorrect bubble align & size (swift)

### ISSUE THREAD

**Issue by frankgumeta** [jessesquires/JSQMessagesViewController#713]
Hi everyone! =)

I'm working with this framework for my custom xmpp chat in swift. But i have the next issues. (I Know is not the best place to ask but i cannot find my error)

+ All messages cells take the height of the first message
+ I cannot align Outgoing messages to right (I have seen the examples in firechat and i swear my code is almost the same)

There is a screenshot

![img_1101](https://cloud.githubusercontent.com/assets/5852746/5603557/aabace98-9350-11e4-92b7-08c52bd5e5cc.PNG)

**Comment by jessesquires** [comment]
Hey @frankgumeta - see the [Getting Started](https://github.com/jessesquires/JSQMessagesViewController#getting-started) guide.

>Subclass JSQMessagesViewController.

>Implement the required methods in the JSQMessagesCollectionViewDataSource protocol.

>Implement the required methods in the JSQMessagesCollectionViewDelegateFlowLayout protocol.

>Set your senderId and senderDisplayName. These properties correspond to the methods found in JSQMessageData and determine which messages are incoming or outgoing.

**Comment by frankgumeta** [comment]
I swear i have done that... I followed the obj-c example given in the master branch, after that o followed the firechat example. And still happening. Do you want to see the code?

**Comment by Antairez** [comment]
I’m not sure what firechat example you have followed, but if the only example you followed is the official demo project, there shouldn’t be any problems.

If you wonder what the other example has done to your project, try implementing that example on top of the official demo project and see what happens. I bet it is the “firechat” example you’ve followed that’s causing the problem.

**Comment by frankgumeta** [comment]
Well, i think it may be true. I'm following this example for swift.
https://github.com/firebase/ios-swift-chat-example given in #675 

but c'mon, porting a implementation from obj to swift is not painfull. I have done it a lot of times. I think i'm missing other thing but i can't find what it is. =(

**Comment by hit1983** [comment]
same issue here, can someone help?

**Comment by hit1983** [comment]
found a way to correct this issue, i just implements a hash in my message model. see #680

**Comment by jessesquires** [comment]
Oh, right! Thanks @hit1983 .

@frankgumeta implementing `hash` is likely the issue.

If you're using `NSManagedObject`, you'll have some issues at the moment. See #684

**Comment by frankgumeta** [comment]
I'm trying it right now, I will let you know my results =)

**Comment by frankgumeta** [comment]
Well I'm a bit confused. Reviewing my code, I have implemented was implemented (I have had to do it when i began the implementation)... But well, the problems seems that all cells are created as ```JSQMessagesCollectionViewCellIncoming``` ... and I'm not using NSManagedObject (btw)

It sounds naive, but I don't find how to change this. =(

I have noticed too that the firechat example uses an old version of JSQMessagesViewController. In the example there is not hash implementation.

**Comment by frankgumeta** [comment]
This is my swift code =(

https://gist.github.com/frankgumeta/1367105d30a9e4476fe5

**Comment by jessesquires** [comment]
For outgoing vs. incoming:

On your view controller subclass:
>Set your senderId and senderDisplayName. These properties correspond to the methods found in JSQMessageData and determine which messages are incoming or outgoing.

**Comment by frankgumeta** [comment]
It's done in ViewDidLoad i manually assign ```self.senderId = "me"``` & ```self.senderDisplayName = "me"```

**Comment by frankgumeta** [comment]
I got it!!! 
I was not setting the senderId for the JSQMessageData object. I'm feeling like a big fool.

But i have the bubble resize problem yet. Any other clue?

Thanks for you patience =)

**Comment by frankgumeta** [comment]
Got it. My error again. The hash was not being created properly.

I'm creating it this way

```UInt(self.senderId_.hash) ^ UInt(self.date_.hash)````

if I do it using the @hit1983 way sometimes it crashes

```UInt(self.senderId_.hash) ^ UInt(self.date_.hash) ^ UInt(self.text_!.hash)```

Thanks to everybody =)

**Comment by jessesquires** [comment]
:+1: glad you got it all fixed!

**Comment by pritamhinger** [comment]
Thanks @frankgumeta .. ur fix solved my issue..

**Comment by TissaGeorge** [comment]
thank you for the guidance :)

**Comment by drosenstark** [comment]
Lots of comments in all directions here, but as @frankgumeta points out, the IDs need to match up. This is in my simple `viewDidLoad`:

```swift
for _ in (0...12) {
    let message = JSQMessage(senderId: "ernie", displayName: "blah", text: "hello")!
    messages.append(message)
}
self.senderId = "ernie"
```
