### ISSUE TITLE
ViewController always scrolling down on appearance

### ISSUE THREAD

**Issue by pflenker** [jessesquires/JSQMessagesViewController#714]
Hi there,

today I have noticed the following issue, for which I would like to ask if it is the intended behaviour:
I have several media messages, some of them with images. If I tap on one of those images, I load a new view controller and push it onto the view stack to display the image. However, if this VC is popped from stack and the JSQMessagesViewController gets visible, it scrolls to the bottom instead of staying where it was.

I am on version 6.1.1. I have not overwritten viewDidAppear or viewWillAppear, and I am using scrollToBottomAnimated only once in my code, and the issue persists if I comment it out.

Thanks!

Philipp

**Comment by jessesquires** [comment]
Hey @pflenker - yes this is expected behavior.

To get the behavior you want, you can set `self. automaticallyScrollsToMostRecentMessage = NO;` *before* you push a new VC on the stack.

**Comment by pflenker** [comment]
Hey @jessesquires , thanks for your reply! When is the best place to set this property back to `YES`? If I do it either in `viewWillAppear` or in `viewDidAppear` , it still scrolls right to the bottom.

**Comment by jessesquires** [comment]
Hm... setting back to `YES` in `viewDidAppear:` should work.

**Comment by pflenker** [comment]
It works, the problem was on my end. Thanks again!

**Comment by jessesquires** [comment]
Awesome! :+1:
