### ISSUE TITLE
How to register a custom cell ?

### ISSUE THREAD

**Issue by hit1983** [jessesquires/JSQMessagesViewController#716]
I noticed that I just can  registerNib in JSQMessagesCollectionView, is there a more flexible way to do this?
Thanks

**Comment by hit1983** [comment]
I require a totally customized cell, but i found i need modify  JSQMessagesCollectionView to made it. I think this is not a right way.
Jes do you have some advice? Thanks very much~

**Comment by fustalol** [comment]
Hey, have you solved this problem? I'm stuck in It.

**Comment by jessesquires** [comment]
Hey guys, here's how to do this:

1. Register your own cells with the collection view
2. Set these properties on `JSQMessagesViewController`: 
    * `outgoingCellIdentifier`
    * `outgoingMediaCellIdentifier`
    * `incomingCellIdentifier`
    * `incomingMediaCellIdentifier`

@hit1983 - Then, you should be able to subclass `JSQMessagesCollectionViewFlowLayout` and set it from `viewDidLoad`
