### ISSUE TITLE
Pod file doesn't contain Media or Location files . 

### ISSUE THREAD

**Issue by vishal91** [jessesquires/JSQMessagesViewController#718]
i am installing latest pod  pod 'JSQMessagesViewController' . It doesn't contain file pertaining to media sharing and location which I can see in demo file .

**Comment by jessesquires** [comment]
hey @vishal91 - not sure what you mean.

the media data (images, etc.) in the demo project are for demo purposes only. the actual library doesn't (and shouldn't) ship with these.

**Comment by jessesquires** [comment]
see the README and documentation for how to use the library to send/display your own media.

**Comment by vishal91** [comment]
Can i use Demo Files for Media in My Project ?

**Comment by jessesquires** [comment]
um....? I mean, all that's there are some pics of Tim Cook, Woz, and Steve Jobs. I'm not really sure why you would want those....
