### ISSUE TITLE
"a size that is too small to notice" is not too small to notice

### ISSUE THREAD

**Issue by ghazel** [jessesquires/JSQMessagesViewController#722]
Trying to reduce vertical spacing between stacked bubbled (like iMessage), I found it very difficult to eliminate the last few pixels. Turns out:

https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Layout/JSQMessagesCollectionViewLayoutAttributes.m#L96

```objc
- (CGFloat)jsq_correctedLabelHeightForHeight:(CGFloat)height
{
    //  cap label heights to a minimum of 1.0
    //  layout constraints sometimes throw warnings when they equal 0.0
    //  prevent this with a size that is too small to notice
    return MAX(ceilf(height), 1.0f);
}
```

is adding 1 pixel for every UILabel, of which there are three (cell bottom label, cell top label, and bubble top label).

**Comment by jessesquires** [comment]
Hey @ghazel - hahaha, thanks! :laughing: 

That happened here at https://github.com/jessesquires/JSQMessagesViewController/commit/a56ceebdd3ab169734d5654ed6b376618fece2ec as an attempt to fix those constraint warnings.

However, I later realized that https://github.com/jessesquires/JSQMessagesViewController/commit/42c29ce4a1c3f44ea55b14d00ee9f070d8f0eb42 was much better. 

So, I'm almost certain that https://github.com/jessesquires/JSQMessagesViewController/commit/a56ceebdd3ab169734d5654ed6b376618fece2ec can be reverted. I remember thinking this at the time, but never checked it.
