### ISSUE TITLE
Photos taken are rotated 90 degrees

### ISSUE THREAD

**Issue by Zilounay** [jessesquires/JSQMessagesViewController#723]
Hi,

This is more a problem than a bug, but when a picture is taken using the UICameraPicker in it's simplest manner, the images are shown with a 90° difference. I basically have to flip my phone to "landscape" when taking picture so they appear correctly in chat.

If I rotate programatically they end up being stretched.

Any idea what I could do? It looks like i'm the only one mentioning this so it's either brand new or really simple to solve. Any help us much appreciated :)

**Comment by jessesquires** [comment]
Thanks @Zilounay - see #647. This explains what's going on.

However, I just realized there was a new comment on that thread that I had not seen:

>For me this line messes up photo orientation from the camera (inside setImage):
>`_image = [UIImage imageWithCGImage:image.CGImage];`
>...converting to CGImage may lose/mess up the orientation info.
>This one works:
>`_image = [image copy];`

So, it looks like this issue can be resolved.

**Comment by febinfathah** [comment]
This is not fixed in my case Photos having big resolution again rotating 90 degree

**Comment by JRam13** [comment]
I can confirm this isn't fixed either (or maybe is a whole different problem). In the case of doing something like this:

```
JSQPhotoMediaItem *item = (JSQPhotoMediaItem *)msg.media;
UIImage *image = item.image;

[UIPasteboard generalPasteboard].image = image;
```

This will paste the image at a 90 degree angle.

**Comment by wdcurry** [comment]
Unless i am missing something, this is beyond the scope of the library itself, and up to you to manage. Search SO, there are various categories to help normalize images.

**Comment by JRam13** [comment]
@wdcurry That's what I thought, I just thought some1 would have a quick fix. 

Will do, thanks.

**Comment by wdcurry** [comment]
No worries.. and if you are comfortable creating categories, this basic method can help:

    if (self.imageOrientation == UIImageOrientationUp) return self;
    
    UIGraphicsBeginImageContextWithOptions(self.size, NO, self.scale);
    [self drawInRect:(CGRect){0, 0, self.size}];
    UIImage *normalizedImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return normalizedImage;

**Comment by jessesquires** [comment]
Thanks @wdcurry ! :smile:
