### ISSUE TITLE
JSQMessage Hash Function Crash (Swift)

### ISSUE THREAD

**Issue by frankgumeta** [jessesquires/JSQMessagesViewController#725]
Hi! Again.

I implemented successfully JSQMessages days ago. But I have noticed that sometimes (I don't know 
why) , when generating a JSQMessage the hash function example provided in #680 causes crashes

Nil values is not the problem. My code is the Swift version from the thread. It seems that sometimes the hash value is less than 0 (?) according to the console prints

SenderID & Text (The NSString Variables) seems to be the problem

![captura de pantalla 2015-01-09 a las 12 38 58](https://cloud.githubusercontent.com/assets/5852746/5685096/a072159e-97fc-11e4-89be-04467e0a5f0f.png)

Someone else having this trouble?

**Comment by jessesquires** [comment]
hey @frankgumeta - it looks like you aren't adding anything extra to your messages. i would suggest simply:

1. just use `JSQMessage` directly, or
2. Inherit directly from `JSQMessage`:

````swift
@objc class Message: JSQMessage {
       // add extra functionality that you need
}
````

**Comment by frankgumeta** [comment]
Sorry but I did'nt understand your answer =S ...

**Comment by jessesquires** [comment]
Hey @frankgumeta - based on that screenshot, it looks like you can just use `JSQMessage`. There's no need for you to make your own class.

Or, if you need to add functionality, you could simply subclass `JSQMessage`.

The `JSQMessage` class provides `hash` as well as all other basic functionality.

**Comment by brianhu** [comment]
for people who need to implement `messageHash` yourself, here is a sample:

    func messageHash() -> UInt {
        let contentHash = self.isMediaMessage() ? self.image_?.hash : self.text_?.hash
        return UInt(self.senderId_.hash ^ self.date_.hash ^ contentHash!)
    }

**Comment by dealaus** [comment]
I'm having trouble subclassing JSQMessage. I need to add a few things to each message, so I subclass it and in init(), I call super.init(senderId, displayName, text), but it keeps telling me I must call a designated initializer of JSQMessage. I don't exactly understand as I am calling a specific constructor...?

**Comment by mbalex99** [comment]
@brianhu I couldn't get your example to work either :-(

**Comment by nguyenchiencong** [comment]
This issue is not to be closed for those who wants to subsclass JSQMessage. thx

**Comment by nguyenchiencong** [comment]
After some debugging, I relalize the to hash sometimes return negative value which UInt does not accept. Thus:

```swift
    func messageHash() -> UInt {
        let contentHash = self.isMediaMessage() ? self.messageHash().hashValue : self.text_.hash
        print("*************************************")
        print(self.senderId_.hash)
        print(self.date_.hash)
        print(self.text_.hash)
        print("*************************************")
        return UInt(abs(self.senderId_.hash) ^ abs(self.date_.hash) ^ abs(contentHash))
    }
```

**Comment by harlanhaskins** [comment]
That's gonna infinitely recourse for media messages.

**Comment by nguyenchiencong** [comment]
Yeah sorry. it was a typo, I reedited my comment
