### ISSUE TITLE
PhotoMediaItem initialization with background loading?

### ISSUE THREAD

**Issue by jaimeslr** [jessesquires/JSQMessagesViewController#726]
Hello jesse, the JSQPhotoMediaItem can be initialized with an UIImage but if the image is still not cached and you need to download it first which is the best approach? I have'nt found a method like initializeWithURL which would be great.

**Comment by jessesquires** [comment]
Hey @jaimeslr - this is intentional. I like to described the views in this library as being **data-driven**. 

For this scenario, once you have downloaded your image, set the `image` property on `JSQPhotoMediaItem`, then either (1) reload the indexPath for this message, or (2) `reloadData` on the collection view. 

If the photo media cell is not visible, the next time it is dequeued, the library will do the right thing (and display the image).

**Comment by jessesquires** [comment]
Also see #678 and #476. 

These threads have a lot of discussion about this.

**Comment by jaimeslr** [comment]
Thanks for the quick response Jesse. I've already tried with this approach but I don't get a solution for the problem: I've followed your example replacing your DemoModel for a CoreData fetchedResultsController which gives me the information required to draw the cells. Y use the:

- (id<JSQMessageData>)collectionView:(JSQMessagesCollectionView *)collectionView messageDataForItemAtIndexPath:(NSIndexPath *)indexPath

to call my method "getJSQMessageFromIndex: indexPath" which transforms my CoreData model to the expected JSQMessage and returns it. The point is that I can't see a way to download the image when required and tell the cell to show the image when done. If I update the collection or just the indexPath will fire the messageDataForItemAtIndexPath all the time. I guess this is not the place to do that.

Any help would be appreciated. I've googled for a coredata example with background image loading but no success.

**Comment by jessesquires** [comment]
The point to begin downloading the photo is really up to you, and your architecture.

However, I think an appropriate time to do this would be when the message is received. Presumably, you have a structure similar to the following:

1. userA sends a message
* userB receives that message
* if the message is text, the whole payload is sent, received, and displayed
* if the message contains a photo, you need to upload it from userA, then download it to userB
* at this point, you know that data has been sent, but you can't show the photo immediately. however, you can get all of the metadata (sender, date, media type, etc.)

At this point, assuming you've downloaded this metadata to userB and have displaying a "loading" placeholder image media cell, this would be an appropriate time to begin the download.

Once your download is complete, save the image to disk, and save it's path to Core Data. And call `reloadData`. Then, be sure to return your JSQMessages with the actual `UIImage` at this path.

If it's not on screen, the library will display the right thing the next time the cell is dequeued.

**Comment by marcoscurvello** [comment]
I'm stuck in a similar scenario right now, I am implementing media exchange much like whatsapp has it.

1. Download low quality image/video, add blur filter to it, then add it as JSQPhotoMediaItem/JSQVideoMediaItem subclass to the messages array.
2. If user taps on the media, I set the media to nil and begin downloading.
3. Once download is finished I then re add the message to the array of messages.

My question is, where's the best place for theses actions to take place ? @jessesquires
