### ISSUE TITLE
The image are not shown properly 

### ISSUE THREAD

**Issue by smiless** [jessesquires/JSQMessagesViewController#729]
Hi,

I have the same issue that #723 , when i took a picture from the UICameraPicker and i saved it directly to my JSQMessageController, the images are shown with a 90° difference. The solution proposed in #723 didn't work at all for me.
I'm using JSQMessage 6.1.1 and JSQSound 2.0
Here my code (sorry I dunno how make it clear on git) and my app is in portrait only. : 

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info{
    UIImage *image = [info objectForKey:@"UIImagePickerControllerOriginalImage"];
    
   // Dismiss controller
    [picker dismissViewControllerAnimated:YES completion:nil];
   
 // Resize image
    UIGraphicsBeginImageContext(CGSizeMake(640, 960));
    [image drawInRect: CGRectMake(0, 0, 640, 960)];
    UIGraphicsEndImageContext();
 
   // Upload image
    NSData *imageData = UIImageJPEGRepresentation(image, 0.0);
    [self uploadImage:imageData];
}

- (void)uploadImage:(NSData *)imageData{
 // I do my stuff to upload the image and when the image is really 
 // saved online i saved it in a JSQMessage
       
 JSQMessage *message;
        if(media){
               JSQPhotoMediaItem *photo = [[JSQPhotoMediaItem alloc]initWithImage:[UIImage imageWithData:[media getData]]];
              message = [[JSQMessage alloc] initWithSenderId:senderId senderDisplayName:senderDisplayName date:date media:photo];
        }else{
              message = [[JSQMessage alloc] initWithSenderId:senderId
                                         senderDisplayName:senderDisplayName
                                                      date:date
                                                      text:text];
        }
        [_dataArray addObject:message];
}

Any idea how i can solve this ?  (btw this libs is awesome thanks)

**Comment by jessesquires** [comment]
hey @smiless - please update to 6.1.3 and this should be fixed
