### ISSUE TITLE
how to add 'date' label in JSQMessagesViewController

### ISSUE THREAD

**Issue by tomojiro1125** [jessesquires/JSQMessagesViewController#730]
Somehow, I could add messageBubble in chat through JSQMessagesViewController. But, I am not sure how to add "date"![enter image description here] in method.  I would like to add time that sender sent the message. Could you please teach me about it ?
I could add text through this code. I read JSQMessage Class reference, but I am not sure how to add date in initWithSenderId. I think it's better to add date property in messageWithSenderId method.

JSQMessage *message = [JSQMessage messageWithSenderId:@"user1"
                                          displayName:@"classmethod"
                                                 text:JSONDict[@"Message"][@"content"]
                                                    ];
[self.messages addObject:message];

**Comment by weekwood** [comment]
I think  JSQMessage provide methods 
```
- (instancetype)initWithSenderId:(NSString *)senderId
               senderDisplayName:(NSString *)senderDisplayName
                            date:(NSDate *)date
                            text:(NSString *)text;
```

and 

```
- (instancetype)initWithSenderId:(NSString *)senderId
               senderDisplayName:(NSString *)senderDisplayName
                            date:(NSDate *)date
                           media:(id<JSQMessageMediaData>)media;
```

By the way, your image is broken.

**Comment by tomojiro1125** [comment]
Hi, weekwood !!
Thank you for the advice. I thought this is the answer, but I am not sure how to use
instanceMethod in github though. My image is broken because I am a prisoner of bug now...

I am not sure how to add instance method... could you please give me a hint ?

////
JSQMessage *message = [[JSQMessage alloc] init];
[message initWithSenderId:@"user1" senderDisplayName:@"classmethod" date:[NSDate date] text:@"test"];
///
- (id)initWithSenderId:(NSString *)senderId
     senderDisplayName:(NSString *)senderDisplayName
                  date:(NSDate *)date
                  text:(NSString *)text{
}
////

**Comment by weekwood** [comment]
@tomojiro1125 I think you should check out **DemoModelData.m** in demo project.

**Comment by tomojiro1125** [comment]
Thank you for the advice Mr.weekwood !! I will check it out :)

**Comment by tomojiro1125** [comment]
Thanks to weekwood, I could add 'date' with 'initWithSenderId' method, but I can't configure out the time like PM 11:28 'on' or 'below' the bubble chat... what should I do ? 
-----------------------------------------------------------------------------------------------------------------------
NSDate *date = [NSDate date];
JSQMessage *message = [[JSQMessage alloc] initWithSenderId:@"user1"
                                                                       senderDisplayName:@"classmethod"
                                                                                                 date:date
                                                                                                 text:JSONDict[@"Message"][@"content"]]; [self.messages addObject:message];
-----------------------------------------------------------------------------------------------------------------------

Sincerely Regards

**Comment by tomojiro1125** [comment]
![screenshot 2015-01-12 22 18 14](https://cloud.githubusercontent.com/assets/2546011/5722931/a1bea720-9b83-11e4-9848-92164b4606b9.png)

I would like to add the time on or next to the bubble chat.

**Comment by jessesquires** [comment]
@tomojiro1125 - the library provides this.

See [the docs](http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.3/index.html) for:
`collectionView:layout:heightForCellTopLabelAtIndexPath:`
and
`collectionView:attributedTextForCellTopLabelAtIndexPath:`

There's also an example in the demo

**Comment by tomojiro1125** [comment]
![screenshot 2015-01-14 21 00 44](https://cloud.githubusercontent.com/assets/2546011/5738522/92a6ae92-9c30-11e4-80df-92c7dd37acee.png)

Thanks to the precious advise, I did it !!
I will launch iPhone apps through this amazing library.

**Comment by NikKovIos** [comment]
This can also help https://github.com/jessesquires/JSQMessagesViewController/issues/1392#issuecomment-367594318
