### ISSUE TITLE
How to add 'seen' labels to JSQMessagesVC?

### ISSUE THREAD

**Issue by ryderjack** [jessesquires/JSQMessagesViewController#731]
Hi guys,

any ideas on how i would add 'seen' labels and if there's any prepackaged methods out there to help?

Cheers,

Jack

**Comment by jessesquires** [comment]
Hey @ryderjack -- every cell has 3 labels.

Read about the design here:
http://www.jessesquires.com/introducing-jsqmessagesvc-6-0/

There are 3 delegate methods:

````objective-c
collectionView:layout:heightForCellTopLabelAtIndexPath:
collectionView:layout:heightForMessageBubbleTopLabelAtIndexPath:
collectionView:layout:heightForCellBottomLabelAtIndexPath:
````

And there are 3 corresponding data source methods:

````objective-c
collectionView:attributedTextForCellTopLabelAtIndexPath:
collectionView:attributedTextForMessageBubbleTopLabelAtIndexPath:
collectionView:attributedTextForCellBottomLabelAtIndexPath:
````

**Comment by chafzaalahmad** [comment]
I am facing height issue my code is below

`override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
        return 20.0 // also add extra space other cell
      //Not working
        //if message.senderId == self.senderId{
        //return 20.0
        //}
        //else{
        //return 0.0
        //}

    }
    
    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        let message = self.messages[indexPath.row]
        
        if message.senderId == self.senderId{
            return NSAttributedString(string: "Delivred")
        }
        else{
            return nil
        }
        
    }
`
