### ISSUE TITLE
Messages View is empty and has no KB

### ISSUE THREAD

**Issue by ericgross** [jessesquires/JSQMessagesViewController#734]
I have created my UIViewController and am displaying the UIView in a storyboard. The view is embedded in a tab view controller on the bottom. I have copied the demo and removed the parts that seem to be just for a demo (existing messages).

What should I be looking at to determine why there is no keyboard being shown or the "New Message" input. I wonder if perhaps they are behind the tab view controller, or if I am missing something.

Thanks from a JSQM newb.

**Comment by jessesquires** [comment]
hi @ericgross - please see #94
