### ISSUE TITLE
How to use asynchronous communication with JSQPhotoMediaItem

### ISSUE THREAD

**Issue by tomojiro1125** [jessesquires/JSQMessagesViewController#735]
I used JSQPhotoMediaItem to show a pic from URL.
Then, I succeeded to show a pic through below code.

````objective-c
NSURL *photoURL = [NSURL URLWithString:@"http://localhost/hoge/hoge.jpg"];
NSData *data = [NSData dataWithContentsOfURL:photoURL];
UIImage *image = [UIImage imageWithData:data];
JSQPhotoMediaItem *photoMediaItem = [[JSQPhotoMediaItem alloc] initWithImage:nil];
photoMediaItem.image = image;
````
But I think it is synchronous communication. Is it right ?
Then, how should I do asynchronous communication ?
In Apple policy, asynchronous communication is needed, indeed...

**Comment by jessesquires** [comment]
Hey @tomojiro1125 - correct.

You can:

(1) dispatch the code above to a background thread, then call `reloadData` from the main thread.
(2) Use a networking library like AFNetworking

**Comment by tomojiro1125** [comment]
Hi, jessesqulres !!
I got it, I could understand how to use JSQPhotoMediaItem with  asynchronous communication.
Thank you for the advice :+1:
