### ISSUE TITLE
[Dynamic Type] Text resizes but message bubble image does not

### ISSUE THREAD

**Issue by Foriger** [jessesquires/JSQMessagesViewController#736]
Hi,

I need dynamic type into my app, and to do this I make code as follows:
```
- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
  JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];
 
  cell.textView.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
//More code...

  cell.messageBubbleTopLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption1];
//More code...
  return cell;
}
```
```
-(void)viewDidLoad
{
//Some code....
  [[NSNotificationCenter defaultCenter] addObserver:self
                                           selector:@selector(preferredContentSizeChanged:)
                                               name:UIContentSizeCategoryDidChangeNotification
                                             object:nil];
}
```

```
- (void)preferredContentSizeChanged:(NSNotification*) notification
{
  [self.collectionView reloadData];
}
```
When I try to resize from Settings -> General -> Accessibility -> Larger Text both cell textView and cell messageBubbleTopLabel resize ok, but image always stays same.Following pictures showing this:

- This happen when I'm switch from maximum size to minimum size: 
![bubble1](https://cloud.githubusercontent.com/assets/5592392/5754863/c9707e5a-9ca6-11e4-96e2-7375fbf04289.png)

![bubble2](https://cloud.githubusercontent.com/assets/5592392/5754867/d104a768-9ca6-11e4-94f4-0e84b59fcd10.png)

- This happen when I'm switch from minimum size to maximum size: 
![bubble4](https://cloud.githubusercontent.com/assets/5592392/5754886/1b8f53b4-9ca7-11e4-89be-58fc08a187f9.png)

![bubble3](https://cloud.githubusercontent.com/assets/5592392/5754876/da464d22-9ca6-11e4-9856-de477e785185.png)

I saw, that dynamic type issue  (#497) is "Work in progress", so just want to ask if this is expected because logic is not fully implemented, or it is a bug?
Also is there some workaround for this, to resize image properly?
I think I'm missing something, but don't know what.

**Comment by jessesquires** [comment]
hey @Foriger - you'll need to invalidate the collection view layout also

**Comment by Foriger** [comment]
Hi, @jessesquires  and thanks for answer  :)
I changed resizing method and now  looks like this: 
```
- (void)preferredContentSizeChanged:(NSNotification*) notification
{
  self.collectionView.collectionViewLayout.messageBubbleFont = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
  [self.collectionView reloadItemsAtIndexPaths:[self.collectionView indexPathsForVisibleItems]];
  [self.collectionView reloadData];
}

```
And now it works works.
Instead of calling setFont method method, I tried invalidation methods like : 
```
[self.collectionView.collectionViewLayout invalidateLayout]
//Or this:
[self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
```
but none of this works.

**Comment by jessesquires** [comment]
Thanks for the update @Foriger !

I'm going to close this in favor of tracking progress/issue in #497
