### ISSUE TITLE
Markup balloon's direction is different when I use photoMediaItem

### ISSUE THREAD

**Issue by tomojiro1125** [jessesquires/JSQMessagesViewController#737]
When I use photoMediaItem to send photo in bubble chat, I have wrong balloon's direction.
In paticular, left user's ballon's direction became like right user's ballon's direction.
I am not sure it is bug or not.

■Messages
<User 1>
JSQMessage *message = [[JSQMessage alloc] initWithSenderId:@"user1"
                                                                       senderDisplayName:@"first"
                                                                                                 date:[NSDate date]
                                                                                                text:JSONDict[@"Message"][@"content"]];
[self.messages addObject:message];

<User 2>
JSQMessage *message2 = [JSQMessage messageWithSenderId:@"user2"
                                                                                    displayName:@"second"
                                                                  text:JSONDict[@"Message"][@"content"]];
[self.messages addObject:message2];

■Send photo
<User 2>
JSQMessage *photoMessage = [JSQMessage messageWithSenderId:@"user2"
                                                                                           displayName:@"second"
                                                                                                      media:photoMediaItem];
[self.messages addObject:photoMessage];

By the way the below pic is my favorite pic. When Steve Jobs went to haven, there are many apples and flowers in front of Shibuya's Apple store in Tokyo. 

Best Regards

![screenshot 2015-01-15 23 48 43](https://cloud.githubusercontent.com/assets/2546011/5759782/634f51b0-9d13-11e4-8f75-b808aabbc523.png)

**Comment by weekwood** [comment]
see #713,
You need set senderId.

**Comment by tomojiro1125** [comment]
Thank you so much, weekwood !!   I will check it out :+1:

**Comment by jessesquires** [comment]
hey @tomojiro1125 - you'll also need to set `appliesMediaViewMaskAsOutgoing` on all media items. see the docs for more details.

**Comment by JRam13** [comment]
@jessesquires Why isn't ```appliesMediaViewMaskAsOutgoing ``` set automatically? Message items are fine.
