### ISSUE TITLE
duplicate symbol for architecture x86_64

### ISSUE THREAD

**Issue by seyhunak** [jessesquires/JSQMessagesViewController#741]
I installed JSQMessagesViewController using CocoaPods. Using Xcode 6.1.1 version

    Podfile
    platform :ios, '8.1'
    pod 'Canvas', '~> 0.1'  
    pod 'Firebase', '>= 2.1.0'
    pod 'JSQMessagesViewController' 
    pod 'JSQSystemSoundPlayer'

Bridging-Header.h

    #import <Firebase/Firebase.h>
    #import <Parse/Parse.h>
    #import <FacebookSDK/FacebookSDK.h>    
    #import <ParseFacebookUtils/PFFacebookUtils.h>
    #import <Bolts/Bolts.h>
    #import "JSQMessages.h"
    #import "JSQMessageData.h"

Build Settings > Other Linked Flags
![screen shot 2015-01-16 at 16 34 23](https://cloud.githubusercontent.com/assets/170820/5777742/0c3658a2-9d9e-11e4-96c1-fb7ba3a01f0f.png)

If I remove -ObjC flag, it works but can't use JQSMessagesViewController.

Here is the stack trace
https://gist.github.com/seyhunak/bb896c70eac31a509edf

What can I fix this problem?

Thanks

**Comment by pflenker** [comment]
Hey, this is an issue with using parse and pods in parallel. I solved this
by removing the bolts framework and the parse facebook frameworks and
leaving the objc flag intact.

**Comment by seyhunak** [comment]
@pflenker yes same in here, removed pods and installed using putting folder references to frameworks folder fixed the issue, thanks.
