### ISSUE TITLE
scrollToBottomAnimated does not work with more than one section

### ISSUE THREAD

**Issue by thezonie** [jessesquires/JSQMessagesViewController#742]
If using more than one section in the UICollectionView's data source, the scrollToBottomAnimated setting does not work correctly as it only scrolls to the last item in the first section.

**Comment by jessesquires** [comment]
thanks @thezonie !

the library currently only supports having 1 section. if you have more, you've probably done some custom work.

i'm not sure what the use case would be for multiple sections right now, so going to close this.

**Comment by thezonie** [comment]
Everything that I was using with the control worked with multiple sections except for the auto-scrolling, which is why I opened the issue. :)

The use case for multiple sections that I am using the control for is pulling messages from Core Data using a NSFetchedResultsController that groups messages together via a "conversation id" 
sectionNameKeyPath so that I can mirror Apple's Messages behavior of only displaying the date and time above a group of messages. That way, when displaying the messages, I only display the timestamp if it is the first row in a section.

Thanks for replying, and for writing such a great control! :)

**Comment by jessesquires** [comment]
Ahhh interesting! Thanks for explaining, @thezonie!

It sounds like you *did not* use `UICollectionView` supplementary views, but instead wrote some logic to determine whether or not to display the `cellTopLabel` in a cell. Correct?

When rewriting this library for `UICollectionView` (v5.0), I ran into some issues using supplementary views and sections by date (thus having 3 optional labels per cell).

I would love to implement proper sections-by-date for this library, but I won't have time for this anytime soon. It will definitely require quite a bit of work. I'm happy to accept a PR for this :smile:
