### ISSUE TITLE
Messages stick to top of view after adding a static UIImageView 

### ISSUE THREAD

**Issue by alexmk92** [jessesquires/JSQMessagesViewController#744]
I had already viewed issue #63 and followed the steps through.  I was able to successfully add a static background to my chat application, but when the view loads the messages are stuck to the top of the screen as seen in the below image.

Clicking into the "Send message" box brings the messages back down to their normal position.  Any ideas why this is happening?

    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        
        // Pull messages back from parse
        loadMessages()
        
        // Use the JSQ image factory to configure chat bubbles
        let bubbleFactory = JSQMessagesBubbleImageFactory()
        
        selfBubbleColor = UIColor(red: 32.0/255.0, green: 200.0/255.0, blue: 95.0/255.0, alpha: 1.0)
        userBubbleColor = UIColor(red: 33.0/255.0, green: 178.0/255.0, blue: 219.0/255.0, alpha: 1.0)
        
        sendBubbleImage = bubbleFactory.outgoingMessagesBubbleImageWithColor(selfBubbleColor!)
        recieveBubbleImage = bubbleFactory.incomingMessagesBubbleImageWithColor(userBubbleColor)
        
        // Set the static background view and insert it as a subview
       self.collectionView.backgroundColor = UIColor.clearColor()
        backgroundView = UIImageView(frame: CGRect(x: 0, y: 0, width: view.frame.width, height: view.frame.height))
        backgroundView.image = UIImage(named: "background")
        
        self.view.insertSubview(backgroundView, atIndex: 0)
    }

![error](https://cloud.githubusercontent.com/assets/3603112/5792765/b1282de4-9f20-11e4-82a7-4e2d666a7d86.png)

**Comment by jessesquires** [comment]
Hey @alexmk92 

Hm... very odd. All of that code looks correct. It sounds and looks like your collection view insets are getting messed up when the view hierarchy changes.

I would try invalidating the layout and reloading data after you add the image.

**Comment by alexmk92** [comment]
Hi @jessesquires ,

I had already tried that as a solution, unfortunately it still produces the same results ( I assume you meant I should put my call to `loadMessages()` at the end of the function once the view hierarchy has been drawn )

Any other thoughts?

Cheers.

**Comment by jessesquires** [comment]
Yeah -- depending on what that function does.

````swift
self.view.insertSubview(backgroundView, atIndex: 0)
self.collection.collectionViewLayout.invalidateLayout()
self.collectionView.reloadData()
````

**Comment by alexmk92** [comment]
@jessesquires that's exactly what I'd tried earlier, still produces the same results.

**Comment by jessesquires** [comment]
Hey @alexmk92 - the only thing that sticks out about this is that i would make sure that the callback block in `query.findObjectsInBackgroundWithBlock` is called on the main thread.

**Comment by alexmk92** [comment]
Thanks for all your help Jesse, after looking further into the issue what happened was, Inserting the background subview invalidated the TopLayoutView constraint, to fix this I simply reset the top inset of the collection view:

    let height = self.navigationController?.navigationBar.frame.height
    if let h:CGFloat = height {
       self.collectionView.contentInset = UIEdgeInsetsMake(h, 0, 0, 0)
    }

**Comment by jessesquires** [comment]
Nice! Thanks for the update @alexmk92 !
