### ISSUE TITLE
How can I customiza avatar border?

### ISSUE THREAD

**Issue by fustalol** [jessesquires/JSQMessagesViewController#745]
As the title says, i need to put an avatar's border. How can I do that in JSQMessage?

**Comment by weekwood** [comment]
I think this should change from sub class of JSQMessageViewController, not from JSQMessage
just add *cell.avatarImageView.layer.borderWidth = Value * in 
```objc
- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
```

**Comment by fustalol** [comment]
thanks! you're point :D
