### ISSUE TITLE
Custom content in JSQMessagesInputToolbar

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#746]
@jessesquires 

I'm looking for a way to add a few extra controls above/below the existing items in the JSQMessagesInputToolbar content view.

I could subclass JSQMessagesToolbarContentView to add the controls to the contentView or 
I could subclass JSQMessagesInputToolbar and add my controls below _contentView.

Before I continue, is this already a feature I haven't notice, or is it on the road map?

Maybe I can run my thoughts by you before I go too far.
(The changes I'm considering will be challenging to manage if you're unwilling to merge a pull request.)

My thinking is this:
(1)
In -[JSQMessagesInputToolbar awakeFromNib], call a new methods:
- (UIView *)lowerContent;
- (UIView *)upperContent;
These would be places subclasses could inject additional content views. JSQMessagesInputToolbar will return nil, and will continue to operate normally.
JSQMessagesInputToolbar will set the constraints so that the toolbar is filled up with the views.

(2)
I'd like to turn kJSQMessagesInputToolbarHeightDefault into an accessor which subclasses can override.

(3)
As you know JSQMessagesViewController is instantiated from a nib.
I'm thinking that users who want this functionality will have to create their own nib to set the toolbar's subclass, and JSQMessagesViewController subclasses will have to override:
+[JSQMessagesViewController nib]
If that doesn't sound ideal, I'd need to create the inputToolbar property programmatically (which I prefer given this modification I am suggesting), but I figured a smaller changeset might be more welcome.

Would you be open to a PR along these lines?
Ray

**Comment by jessesquires** [comment]
Hey @walsh2000 - does #634 help you at all? I realize it doesn't provide "upper/lower" content, but you can access these left/right container views directly now to add more buttons. Maybe a tweak in your design would allow you to utilize this instead.

Can you provide a mockup or describe more what you're trying to do? It sounds like this would be like having an additional toolbar above/below the existing toolbar?

**Comment by walsh2000** [comment]
This is exactly like a toolbar underneath/above the existing toolbar.
Here is a screen shot of something similar to my mockup:
http://www.sociobits.org/wp-content/uploads/2014/05/Facebook-Messenger-Update1.jpg

(I am not affiliated with the product depicted in the screen shot)

**Comment by walsh2000** [comment]
I've been thinking about this more, and I think something else is going to be required to fit my desired UX.
How about I close this and open a new one once I've come up with a different proposal?

**Comment by jessesquires** [comment]
Ok - thanks @walsh2000 !

Regarding what we have here, I am hesitant to accept a PR — not because I think this is a bad idea, but because this will be quite a bit of work. (And difficult to build a good API around.)

It also seems like more of an edge case than not (haven't gotten many requests for this type of thing).
