### ISSUE TITLE
Using a Nav Controller height issues. Clearing Out all messages sent on button click.

### ISSUE THREAD

**Issue by Shanlon** [jessesquires/JSQMessagesViewController#749]
Hello, So I am creating an app using the swift converted design off of Firebase. I have integrated and got chat working with my users but I am having an issue with compensating for the top navigation bar because the first messages are hidden. Secondly, when I try to clear out the messages it sometimes crashes. Anyway to properly do this?

Thank you.

**Comment by jessesquires** [comment]
Hey @RobertHanlon - are your navbars translucent, or not?

**Comment by RobertHanlon** [comment]
My nav bars are translucent. Should they not be?

- Thanks for the fast reply.
On Jan 20, 2015, at 12:18 PM, Jesse Squires <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @RobertHanlon<https://github.com/RobertHanlon> - are your navbars translucent, or not?

**Comment by Shanlon** [comment]
They are translucent. Was able to solve the second issue. Just the navigation bar is still a issue.

**Comment by Shanlon** [comment]
Fixed the issues. Used scroll insets
