### ISSUE TITLE
Subclassing JSQMessagesInputToolbar

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#750]
@jessesquires 

If users want the input toolbar to have a row of buttons below the text field which toggle different input methods/options, there is currently no good way to do this.

Part of the work can be done as follows:

1. specify a subclass of JSQMessagesInputToolbar in a copy of JSQMessagesViewController.xib
2. override + [JSQMessagesViewController nib] to insert the new xib

With these methods, JSQMessagesInputToolbar would need to be modified because the contentView instance variable is instantiated as a JSQMessagesToolbarContentView inside awakeFromNib. If JSQMessagesInputToolbar called an override point to setup _contentView, subclasses could get in there without completely re-writing/cloning the existing awakeFromNib implementation.

Additionally, to avoid duplicating the logic in jsq_adjustInputToolbarHeightConstraintByDelta, we'd need to convert kJSQMessagesInputToolbarHeightDefault into a property of JSQMessagesInputToolbar.
There would be situations (depending upon the state of the toolbar) where the minimum height would be different.

Would you be comfortable with these two changes?

(1) Turning this snippet from -[JSQMessagesInputToolbar awakeFromNib]:
```
NSArray *nibViews = [[NSBundle bundleForClass:[self class]] loadNibNamed:NSStringFromClass([JSQMessagesToolbarContentView class])
                                                                       owner:nil
                                                                     options:nil];
JSQMessagesToolbarContentView *toolbarContentView = [nibViews firstObject];
```

into a method that JSQMessagesInputToolbar calls from awakeFromNib like:
```
- (JSQMessagesToolbarContentView *)loadContentView {
NSArray *nibViews = [[NSBundle bundleForClass:[self class]] loadNibNamed:NSStringFromClass([JSQMessagesToolbarContentView class])
                                                                       owner:nil
                                                                     options:nil];
return [nibViews firstObject];
}
```

(2) Turning the uses of kJSQMessagesInputToolbarHeightDefault in JSQMessagesViewController into:
```
- (CGFloat)inputToolbarHeightDefault {
return kJSQMessagesInputToolbarHeightDefault;
}
```
And removing its declaration from JSQMessagesInputToolbar.h

Ideally I'd also love a couple of other changes, but I've worked hard to keep this proposal as small as possible. If you're open to a few other changes in this area, here are the other two I think would enhance the usability of your library with respect to custom input toolbars:

(1) Eliminate the knowledge that JSQMessagesViewController has about the implementation details of JSQMessagesInputToolbar & his contentView. Perhaps convert JSQMessagesInputToolbar into a protocol for JSQMessagesViewController

(2) Allow subclasses to provide their own JSQMessagesInputToolbar subclasses without resorting to copy/paste the JSQMessagesViewController.xib. We could do that if the JSQMessagesInputToolbar is created by a function which subclasses can override.

Thank you for considering this use-case
Ray

**Comment by walsh2000** [comment]
To be clear, I am offering to do this work. I am preflighting the idea with you.

**Comment by jessesquires** [comment]
Thanks @walsh2000 !

I'll review and give this some thought when I have some more time! 
(But it's looking pretty good so far :+1: )

**Comment by nikilster** [comment]
@walsh2000 

Thanks for bringing this up - I'm trying to do the same thing.  How did you end up swapping out the keyboard for your custom keyboard - are you dismissing it and adding the toolbar to the main view and adding an inputView?

**Comment by walsh2000** [comment]
@nikilster 

Sorry, I didn't change out the keyboard. I was adding a second row (of buttons) below the UITextView. This change just allowed subclasses to set a different default height for the toolbar, and to inject a different NIB for the toolbar's content view.

**Comment by nikilster** [comment]
@walsh2000 Ah got it.  Would you be able to explain how you did that?  I'm trying to add some custom buttons and then have those toggle out different keyboards (as in FB Messenger).  Seeing how you did this would be super helpful - thanks in advance!  (Happy to move this over to email)

**Comment by tjwudi** [comment]
hi @walsh2000 Thanks for this!

Although I could subclass `JSQMessagesViewController` and override `loadContentView`, how can I use my subclass as `inputToolbar` in `JSQMessagesViewController`? It's readonly.

**Comment by nguyenpham** [comment]
@tjwudi 
Did you follow exactly all 2 steps?

1) specify a subclass of JSQMessagesInputToolbar in a copy of JSQMessagesViewController.xib
2) override + [JSQMessagesViewController nib] to insert the new xib

**Comment by tjwudi** [comment]
@nguyenpham Yes I did but I still can not override a private method anyway, right?

**Comment by pardypanda** [comment]
@walsh2000 

Hi Raymond, could you please direct to an example implementation of this?

I need a slightly more elaborate input toolbar. One with 2 rows. Bottom row with input text and send button and top row with various buttons for sending image, video, audio etc. 

Thanks

**Comment by pardypanda** [comment]
@nguyenpham

Hi, can you send me an example of custom input toolbar with two rows. Top row with action buttons and bottom row with text input?

Thanks

**Comment by pardypanda** [comment]
@tjwudi

Any luck with this?

I've installed the JSQMessagesViewController pods and I too want to customise the look of the toolbar acc to my own .xib

**Comment by pardypanda** [comment]
@jessesquires Hi Jesse,

Is there an example I can refer for this? I'm pretty sure this cannot be done on the pods installation and I'll probably require to copy-paste override the entire JSQMessagesViewController class itself.

Correct me if I'm wrong and do re-direct me to an example where I can create a custom input toolbar with a new row of action buttons on top of the text input bar

**Comment by zzxxx** [comment]
@pardypanda Yo, you've already figured out the problem? if not, I can record a video which will show you how to do this weekend

**Comment by pardypanda** [comment]
@zzxxx No, I haven't figured this out yet. A video will be extremely helpful. Thanks a lot.

**Comment by pardypanda** [comment]
@zzxxx 

Hi, were you able to find time for the demo?

**Comment by zzxxx** [comment]
@pardypanda Hey buddy, sorry for the delay, i prefer to make sample project not the video, i hope you enjoy and it will help you!

**Comment by pardypanda** [comment]
@zzxxx Thanks a lot man. This is really helpful. Exactly what I needed (y)

**Comment by thijsw** [comment]
@zzxxx Great demo project! Really helpful :)

**Comment by chlebta** [comment]
@pardypanda  I runed you're project an I got this : 
<img width="417" alt="screen shot 2017-03-14 at 22 30 06" src="https://cloud.githubusercontent.com/assets/1204608/23923175/ed5a2118-0905-11e7-9b37-ede43e811d81.png">

The left- right buttons ant the text is always the same you just changed the color ??
