### ISSUE TITLE
Message date doesn't follow the right timezone

### ISSUE THREAD

**Issue by fustalol** [jessesquires/JSQMessagesViewController#752]
Hey there, with a NSDate like NSDate \*  2015-01-20 16:34:13 CET
and the phone set for Italy (+1) the function attributedTextForCellTopLabelAtIndexPath
with code:
NVChatMessage *message = [self.session.messages objectAtIndex:indexPath.item];
    if (message.isDateChanged) {
        return [[JSQMessagesTimestampFormatter sharedFormatter] attributedTimestampForDate:message.date];
    }

is getting the CET and not the +1.
Why?

**Comment by jessesquires** [comment]
Hey @fustalol - I'm not sure I understand?

You can see the dateFormatter implementation here:
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Factories/JSQMessagesTimestampFormatter.m

**Comment by GuyKahlon** [comment]
Hey @fustalol - Do you have still the date formatting issue?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
