### ISSUE TITLE
Change the content of the bubble with a custom content.

### ISSUE THREAD

**Issue by fustalol** [jessesquires/JSQMessagesViewController#753]
Hi. My chat CAN have N thumbnail for message (of shared content) and i want to put it inside the bubble.
I can't use the JSQMedia because I can have from 0 to N thumbnail inside a single message.
For the - only text -messages I'm quite happy of this library! :) So, I need to make a custom cell that It's the same of the standard-only text bubble one, but It can have n imageView inside. How to customize cell?

**Comment by jessesquires** [comment]
Hey @fustalol - thanks!

This will require quite a bit of work, but it is possible to provide custom cells. See the docs for JSQMessagesViewController's cell identifier properties.

However, I wouldn't recommend have up to `N` thumbnails in a message. This design choice will probably get very cumbersome and collection view performance may not be so great. If you look at iOS messages, all attachments have their own bubble — even when you send more than 1 at a time. You may want to consider this alternative approach.
