### ISSUE TITLE
Caching UIImageView in JSQPhotoMediaItem

### ISSUE THREAD

**Issue by readytopark** [jessesquires/JSQMessagesViewController#754]
Hi!

While looking at the code in JSQPhotoMediaItem, I found that every JSQPhotoMediaItem holds reference to UIImageView(_cachedImageView). Does this mean, let's say we have an JSQMessage array of 10,000 messages with photo info in a subclass of JSQMessageViewController, that we have 10,000 cached UIImageViews?? If yes, I guess we have to rethink about the implementation of assigning a media view in

- (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath

thanks!

**Comment by jessesquires** [comment]
Hey @readytopark 

Yes, that would be the case. But, hopefully you don't have 10,000 messages in memory :smile: . I would definitely recommend batching your data, regardless of the caching situation here.

In any case, I suppose it would be good for all media items to respond to the `UIApplicationDidReceiveMemoryWarning` notification and release any cached views (which would automatically be lazily re-initialized on their next use).

I've set this as an enhancement for v6.2.0.

**Comment by readytopark** [comment]
I was just concerned about having UIImageView in all media items, not from re-use cells. Anyway, your advice about using memory warning notification would help me:)

Thanks!
