### ISSUE TITLE
AvatarImageFactory: allow avatar initials in lowercase?

### ISSUE THREAD

**Issue by LawrenceCTran** [jessesquires/JSQMessagesViewController#755]
On calling [JSQMessagesAvatarImageFactory avatarImageWithUserInitials: (bleh)], the string I pass in is always turned into uppercase. How can I disable this?

Thanks

**Comment by jessesquires** [comment]
Hey @LawrenceCTran - there's currently no way to disable this, the factory will always automatically do this.

I'll leave this open as a feature request.
