### ISSUE TITLE
How to animate JSQMessagesViewController with custom subviews

### ISSUE THREAD

**Issue by velthune** [jessesquires/JSQMessagesViewController#758]
My question is similar to: https://github.com/jessesquires/JSQMessagesViewController/issues/311.

I've another UIView that I can expand/collapse with a button. 

In iOS7 works great, iOS8 don't. (http://stackoverflow.com/questions/28093705/uiview-dont-animate-changing-constraints-programmatically)

Any ideas?

**Comment by velthune** [comment]
I've solved calling this in ViewDidLoad:

    [self setTranslatesAutoresizingMaskIntoConstraints:YES];

**Comment by jessesquires** [comment]
Thanks for the update @velthune !

**Comment by velthune** [comment]
Errata corrige. 
Yes, this solved the animation of my UIView, but now keyboard doesn't work well (https://github.com/jessesquires/JSQMessagesViewController/issues/60)

So, please, you need to update library focusing on the fact that JSQMessagesViewController could be inside a Container View and, above and/or below, may be other views with constraints applied to container.
