### ISSUE TITLE
When handling autoscrolling manually, sending a large message with multiple lines of text results in extra white space.

### ISSUE THREAD

**Issue by LawrenceCTran** [jessesquires/JSQMessagesViewController#759]
When I load the view I set  automaticallyScrollsToMostRecentMessage = false

and I handle the scrolling like this 

   override func textViewDidBeginEditing(textView: UITextView) {
        self.scrollToBottomAnimated(true)
    }
    
    override func didPressSendButton(button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: NSDate!) {
        JSQSystemSoundPlayer.jsq_playMessageSentSound()
        let message = JSQMessage(senderId: senderId, senderDisplayName: senderDisplayName, date: date, text: text)
        self.demoData.messages.addObject(message)
        
        self.finishSendingMessageAnimated(true)
        self.scrollToBottomAnimated(true)
        
    }

When I have a large message, it shows like this 

![screen shot 2015-01-22 at 11 21 24 pm](https://cloud.githubusercontent.com/assets/1444337/5870232/2c96466c-a28e-11e4-86d0-0f8b4cb91fc4.png)

**Comment by jessesquires** [comment]
hey @LawrenceCTran - it's hard to see what might be happening here with more code. I would suggesting toggling `automaticallyScrollsToMostRecentMessage` on/off as you need it instead of trying to re-implement it yourself.

Or — maybe this is where a custom fork would be best for you.
