### ISSUE TITLE
How to set avatarimageView.contentMode = UIViewContentModeScaleAspectFill?

### ISSUE THREAD

**Issue by DongjieLi** [jessesquires/JSQMessagesViewController#760]

**Comment by 25matt12** [comment]
Hello,

I have the same problem, my avatars are distorted, did you find any solution ?

thanks.

**Comment by jessesquires** [comment]
https://github.com/jessesquires/JSQMessagesViewController#quick-tips

see "customize your cells"

**Comment by andrew8712** [comment]
@jessesquires I'm having the same issue. The link is not working anymore.

**Comment by jessesquires** [comment]
https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md
