### ISSUE TITLE
Keyboard Notification Race

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#763]
@jessesquires 

Have you seen or heard of the toolbar occasionally getting out of place relative to the keyboard?

I've cornered a hard-to-reproduce situation which causes the toolbar to be behind the keyboard.

When a keyboard dismisses then is shown quickly (as when pushing from a VC which was showing the keyboard into a JSQMessagesViewController subclass) the keyboardControllerKeyboardDidHide delegate callback arrives after the frame change notifications.

1. jsq_didReceiveKeyboardDidHideNotification calls jsq_handleKeyboardNotification
2. jsq_didReceiveKeyboardDidShowNotification calls jsq_handleKeyboardNotification
3. the jsq_didReceiveKeyboardDidHideNotification animation completion block fires, calling the delegate's keyboardControllerKeyboardDidHide.

````
2015-01-26 15:53:03.856 ChatApp[6715:60b] ----- jsq_notifyKeyboardFrameNotificationForFrame
2015-01-26 15:53:03.857 ChatApp[6715:60b] keyboardDidChangeFrame
2015-01-26 15:53:03.870 ChatApp[6715:60b] ----- jsq_notifyKeyboardFrameNotificationForFrame
2015-01-26 15:53:03.871 ChatApp[6715:60b] keyboardDidChangeFrame
2015-01-26 15:53:03.873 ChatApp[6715:60b] ----- jsq_notifyKeyboardFrameNotificationForFrame
2015-01-26 15:53:03.874 ChatApp[6715:60b] keyboardDidChangeFrame
2015-01-26 15:53:03.887 ChatApp[6715:60b] ----- jsq_notifyKeyboardFrameNotificationForFrame
2015-01-26 15:53:03.888 ChatApp[6715:60b] keyboardDidChangeFrame
2015-01-26 15:53:03.889 ChatApp[6715:60b] ----- jsq_notifyKeyboardFrameNotificationForFrame
2015-01-26 15:53:03.890 ChatApp[6715:60b] keyboardDidChangeFrame
2015-01-26 15:53:03.928 ChatApp[6715:60b] HIDE jsq_handleKeyboardNotification animation finished: 1
2015-01-26 15:53:03.929 ChatApp[6715:60b] keyboardControllerKeyboardDidHide
2015-01-26 15:53:03.930 ChatApp[6715:60b] SHOW jsq_handleKeyboardNotification animation finished: 1
````

While the show animation completes after the hide animation, there is no notification to the delegate, so the delegate was last told that the keyboard did hide.

The problem is this:
The toolbar is adjusted upward when the frame changes (which is during the animation) and the toolbar is adjusted downward both when the frame changes and when keyboardControllerKeyboardDidHide is called, which is after the animation.

One solution I can see is to fire a redundant frame-change notification in the show keyboard animation completion block:

````
    [self jsq_handleKeyboardNotification:notification completion:^(BOOL finished) {
        [self.panGestureRecognizer addTarget:self action:@selector(jsq_handlePanGestureRecognizer:)];
		[self jsq_handleKeyboardNotification:notification completion:nil];
    }];
````

Another solution would be a dedicated delegate message for keyboardControllerKeyboardDidShow.
Yet another solution would be to remove the keyboardControllerKeyboardDidHide message rely on the frame change messages.

Do you have any thoughts on this issue?
Ray

**Comment by walsh2000** [comment]
I tested commenting out the body of keyboardControllerKeyboardDidHide (on iOS 7.1 & 8.1), and the UI appeared to behave normally. To my mind this may be the best solution, if you're inclined to take a fix in this area.

**Comment by jessesquires** [comment]
Thanks for the thorough report @walsh2000 !

This was introduced by PR #646 (which also introduced #706).

I'd love a fix for all of the above! :smile:

**Comment by walsh2000** [comment]
I'm just trying to make your job easier :)

I've tested that removing/commenting the code in keyboardControllerKeyboardDidHide does resolve the issue I've seen. I'll investigate what PR #646 was trying to fix to see if commenting/removing the method causes a regression.

**Comment by walsh2000** [comment]
@jessesquires 

Were you ever able to reproduce #645?
I encountered this and I resolved it by changing the keyboardDidChangeFrame logic to something like this:

````
- (void)keyboardController:(JSQMessagesKeyboardController *)keyboardController keyboardDidChangeFrame:(CGRect)keyboardFrame {
	[self setToolbarBottomLayoutGuideConstant:CGRectGetHeight(keyboardFrame)];
}
````

Instead of using the converted rect, which appeared to be bogus periodically and would lead to something like #645.

The fragile aspect of this change is that we bake in the assumption that the keyboard takes up the bottom portion of the screen.

**Comment by jessesquires** [comment]
That bug has appeared in various forms. (See #314) There was a video in #645.

Now that I re-watch that video, there's a lot more complicated UI going on there — which may be part of the issue.

I support all the changes you are suggesting here, and I think PR #646 should be reverted. (And, thus closing #706.)

Regarding the keyboard frame coordinate space, there were some attempts to fix this in PR #454, but it was never resolved. If we fixed the coordinate conversion issues, then we can close #405 too. 

In any case, all of these issues mentioned here seem to be related. I'd love to knock them all out soon.

**Comment by walsh2000** [comment]
@jessesquires 


I discovered a problem with my keyboardDidChangeFrame today (when hardware keyboards are used)

I was able to resolve the issue, still retaining the assumption that the keyboard is at the bottom of the view:
````
- (void)keyboardController:(JSQMessagesKeyboardController *)keyboardController keyboardDidChangeFrame:(CGRect)keyboardFrame {
	CGFloat height = CGRectGetHeight([[self view] frame]);
	CGFloat bottom = CGRectGetMinY(keyboardFrame);
	height -= bottom;
	[self jsq_setToolbarBottomLayoutGuideConstant:height];
}
````

I haven't tried this on iPad. I don't know how this will work with a split iPad keyboard.

**Comment by jessesquires** [comment]
@walsh2000 - related to #557 ?

**Comment by walsh2000** [comment]
@jessesquires 

Yes, I think so based upon what LeoNatan wrote:
>The only public API condoned method is to test if the keyboard's end frame will be outside of the main screen.

This fits what I was seeing when I fixed the issue with the above snippet
> (height - minY)

**Comment by jessesquires** [comment]
@walsh2000 

i started on some of this work.

how is that snippet above different from what's in develop? i'm using `CGRectGetMaxY`, but that should be equal to the view height.

**Comment by walsh2000** [comment]
I think the difference is that I'm not using the keyboardFrame's Y, which has been adjusted (corrupted) by the convertRect call in -[JSQMessagesKeyboardController jsq_handleKeyboardNotification:completion:]
````
CGRect keyboardEndFrameConverted = [self.contextView convertRect:keyboardEndFrame fromView:nil];
````

Under some circumstances the convertView does not produce a realistic value for keyboardEndFrameConverted. Perhaps convertView is offscreen or out of the view hierarchy. The notifications come in pretty fast and I didn't trace it.

So, while the keyboardFrame height/width is accurate (I tested only in Portrait), its X & Y are not always right.

That led me to believe that if I **assumed** the keyboard takes up the bottom "CGRectGetHeight" of the screen, that I could accurately compute the toolbar's bottom offset using just the height of the keyboard alone. For my unpublished app which admittedly has a very limited user-base, the above snippet has been consistently positioning the toolbar correctly.

However, it should be noted that there is an ugly assumption baked in there.
It might be worthwhile discovering what triggers convertRect to produce unexpected results. My suspicions were that the view was offscreen or was out of the view hierarchy, but I never did confirm either notion. If we could positively know when convertRect might return those unexpected results, perhaps we can compensate for it and then maintain the existing positioning logic. (Freeing us from my keyboard-position assumption)

**Comment by jessesquires** [comment]
Ahhh got it. That makes sense! Thanks @walsh2000

**Comment by markst** [comment]
Also having issues with toolbar animating behind the keyboard. 
My `UIWindow` is is offset 40pt from the top of my screen. 

I was able to resolve by the following:
```objc
CGRect keyboardEndFrameConvertedNew = [self.contextView.window convertRect:keyboardEndFrame toView:self.contextView];```
& 
```objc
CGFloat heightFromBottom = heightFromBottom = MAX(0.0f, CGRectGetMinY(keyboardFrame));
```

I'm not sure if both `UIKeyboardWillChangeFrameNotification` & `UIKeyboardDidChangeFrameNotification` both need to be observed? as this will trigger multiple animations for toolbar constraint updates. Perhaps `UIViewAnimationOptionBeginFromCurrentState` animation option could be used to avoid animation issues. 

Not had the chance to properly investigate. So take these comments lightly.

**Comment by jessesquires** [comment]
hey @walsh2000 and others - just bashed some bugs tonight and closed a number of issues.

I would love some help on this — the last major issue before the 6.1.4 release is ready for Cocoapods.

**Comment by walsh2000** [comment]
@jessesquires 

You'd like a pull request? or are you asking for help testing?
I can put together a PR for how I've worked around this in my app.

Ray

**Comment by jessesquires** [comment]
@walsh2000 - PR would be awesome!

**Comment by walsh2000** [comment]
@jessesquires 
My solution builds in an assumption that the keyboard is always at the bottom of the screen. I tested the app out with the floating/split keyboard.

Here is how the app looks before my modifications (not great, but usable)
![screen shot 2015-02-27 at 9 00 03 am](https://cloud.githubusercontent.com/assets/4912283/6417031/8cb467a8-be5f-11e4-9e47-bc770bd7d3db.png)
![screen shot 2015-02-27 at 9 00 24 am](https://cloud.githubusercontent.com/assets/4912283/6417032/91fa67bc-be5f-11e4-8c7d-921c0f073970.png)

With my modifications (in the simulator) the keyboard covers up the input field. I don't know how widely the floating and/or split keyboard is used, but I don't want to introduce this nasty regression. I'm going to investigate a more thorough solution which does not assume that the keyboard's frame is always at the bottom of the screen.

**Comment by walsh2000** [comment]
Adding on:

There are two issues:
#557 Where the keyboard's frame is occasionally reported offscreen and the toolbar reacts

#763 Where the input field resigns first responder because keyboardControllerKeyboardDidHide is called after a keyboard did appear notification.

I'm going to tackle #763 separately from #557.

**Comment by walsh2000** [comment]
More:

I looked at the two videos in #645
1. https://www.dropbox.com/s/iehlriqqc4eim9l/chat-bummer-1.mov?dl=0
I am not convinced this is due to the notifications. It could be related to some bug in the manually setting the toolbar's y offset.
2. https://www.dropbox.com/s/bv1uw6gfckoyzqa/chat-bummer-2.mov?dl=0
I didn't see anything wrong on this one. At the end of the video, the toolbar appears to rest where I would expect.

With this mindset, I'm not clear on why we need the keyboardControllerKeyboardDidHide delegate callback. However, since @toblerpwn added it, it must be helping him. Rather than suggest we remove the callback (and regressing @toblerpwn's project), I'd like to suggest we create a new property which can short circuit these two lines in keyboardControllerKeyboardDidHide:
````
    [self jsq_setToolbarBottomLayoutGuideConstant:0.0f];
    [self.inputToolbar.contentView.textView resignFirstResponder];

````

Here is a preview of the comment for this new property:
````
/**
 *  Specifies whether or not the inputToolbar should resignFirstResponder & snap to the bottom of the screen after the keyboard did hide animation.
 *
 *	@see https://github.com/jessesquires/JSQMessagesViewController/issues/763
 *  @discussion Some projects require the inputToolbar to be snapped to the bottom after the keyboardDidHide animation completes.
 *	However if the screen pushing the JSQMessagesViewController onto the UINavigationController stack was showing the keyboard
 *	that previous screen will hide the keyboard on the transition.
 *	When the JSQMessagesViewController comes on screen and becomes first responder, the previous screen's keyboardDidHide notification
 *	is picked up by the JSQMessagesViewController, causes it to resignFirstResponder. In this way, the input toolbar is not initially the first responder.
 *  Setting this property to `NO` will result in no action being taken when the keyboardControllerKeyboardDidHide message arrives.
 *	Setting this property to `YES` will result in the inputToolbar resigningFirstResponder & pinning to the bottom of the view when the keyboardControllerKeyboardDidHide message arrives.
 *	Under normal circumstances, `NO` is the right thing to do, because the keyboardController:keyboardDidChangeFrame: messages will take care of the inputToolbar's positioning.
 
 *  The default value is `NO`.
 */
@property (assign, nonatomic) BOOL resignFirstResponderOnKeyboardDidHide;
````

PR to follow.

**Comment by walsh2000** [comment]
This also addresses #706 if the new boolean is left at the default (NO)

**Comment by walsh2000** [comment]
Okay. 27d7a2e09c6f resolves this issue.
I was working off of an old fork & didn't notice that you'd reverted the changeset on 2/5.
We can close this one without a code change.

**Comment by walsh2000** [comment]
Sorry, I meant to close this. You've resolved this with the revert.

**Comment by jessesquires** [comment]
thanks @walsh2000 !

any testing that you can do on develop right now is much appreciated!

**Comment by walsh2000** [comment]
@jessesquires 

The tip of develop looks good in my app. Nothing stands out with a light smoke-test.

To verify, I was using this in my Podfile
````
pod 'JSQMessagesViewController' , :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :commit => '09db017b871a37df25d38598cba774f976bd8d13'
````

Thumbs up here! :) :+1:

**Comment by jessesquires** [comment]
@walsh2000 - thanks so much!

**Comment by toblerpwn** [comment]
heyo @jessesquires & @walsh2000 - just wanted to chime back in here and let you know that reverting the changes made in #646 prevent our app from using JSQ; both issues now re-appear in the latest public cocoapod version.

the problem with video #2 (https://www.dropbox.com/s/bv1uw6gfckoyzqa/chat-bummer-2.mov?dl=0) to be more clear is that the JSQMessagesViewController is completely off-screen, and yet its toolbar animates back on to the bottom of the screen bounds (i.e. it is overlapping a different controller and displaying completely outside of the message controller's bounds).

we are not doing anything fancy or hard-coding anything weird.

in terms of finding a solution that works for everyone, what is best? should I re-open #645? I am unsure exactly how to approach a fix without digging in deeper with one of you; my approach to fixing it would be to essentially re-do #646 which is clearly not what you want.

sorry for not replying earlier; release crunch and all that. =/

**Comment by jessesquires** [comment]
hey @toblerpwn - it's not that #645 was unwanted, just that it caused other side effects. i'm always open to other possible solutions. :smile: however, based on the video, my first thought is that this is specific to your implementation.

absolute worst case scenario: you can maintain a custom fork, and point cocoapods to fetch from your fork

**Comment by toblerpwn** [comment]
@jessesquires - yeah, we're doing the latter...I saw mention of a custom property in #823 to opt-in to the behavior we're looking for, but it looks like that was not implemented?
