### ISSUE TITLE
Add subviews inside the bubble message.

### ISSUE THREAD

**Issue by fustalol** [jessesquires/JSQMessagesViewController#768]
Hi, i need to put N UIVIew inside a single message. I've read all the customization issues before mine, but I didn't really understand. I want to add N istances of a UIview in my bubble cell. How can I achieve that? What classes I've to customize and extend? I've foun a lot of different aswers. 
Basically i want to attach this:
![schermata 2015-02-02 alle 17 33 43](https://cloud.githubusercontent.com/assets/6514972/6004259/c0ac08a2-ab01-11e4-86fc-ec9d14b628d9.png)

before the text inside a bubblechat. I've the custom UIView for A SINGLE row ready, but i don't know how to extend to attach it inside a JSQ cell. Can someone guide me to this customization? I'm freaking out D:

**Comment by fustalol** [comment]
Apparently, I'm solving this shit.
For who will read this post, to add an extremely custom Layout Cell, simply create a new cocoa-touch class inherit from JSQMediaItem, open JSQMediaPhotoItem and copy exactly what JSQMediaPhotoItem do. It works with a UIView where you can add whater you want.

**Comment by jessesquires** [comment]
Thanks for the update @fustalol - sorry I didn't have time to get to this sooner, but this is exactly the right way to do this. :+1:
