### ISSUE TITLE
Prototype: consider Using AsyncDisplayKit for performance boost

### ISSUE THREAD

**Issue by mohpor** [jessesquires/JSQMessagesViewController#769]
I'm sure all of us have faced the performance drops introduced (or worsened) by iOS 8.
There has been some workarounds like those introduced in #492 and other issues.
I have tried them all but after kicking around a few ideas, I have successfully tested `AsyncDisplayKit`: [Facebook/AsyncDisplayKit](http://asyncdisplaykit.org).
It improved the performance so much that all my scrolling stutters are now gone for good. 
I know it would introduce lots and lots of change requirements, but I believe if we want to have something as fluid as Viber™ or Facebook Messenger™, we have to do something about it.
This wonderful library currently works perfectly when used in simple scenarios, but, if the layout gets complex enough, issues arise that solving them would require such handwork that reimplementing everything (and leaving all abstractions behind, you know, for brevity sake) seems inevitable.
So, if there is enough demand for such dramatic change in this library, I think it's about time someone fork this project and re-implement it using ASDK.

**Comment by mohpor** [comment]
My current implementation so far (which unfortunately I can't share for now) has these problems:

* I didn't change the actual implementation of `UICollectionView` with `ASCollectionView`. (shouldn't be too hard, because their interfaces are almost identical)
* Media Messages flicker every time collection view gets reloaded - `ASImageNode`'s fault (the solution can be as easy as reloading individual cells instead of whole collection view: also a source of performance boost in future)
* `ASTextNode` seems to be more limited than it should be (lack of a `text` attribute is one of them - it actually supports attributed strings only!)

**Comment by jessesquires** [comment]
Thanks @mohpor - I've been considering this too, but haven't had the time to investigate. Thanks for sharing!

One thing to note is that major changes like this will require a new version release, for example v1.0 to v2.0, so timeline is very important to consider.

I'd like to get as much done as possible in v6.x (bug fixes, etc.) before jumping ship to v7.x.

**Comment by mohpor** [comment]
You're absolutely right. it does require a certain amount of re-building, but all I know is that apparently the performance drop introduced in iOS 8 will likely remain with us for at least the next couple of years (optimistically, considering Apple will recover from it), and we got to do something about it, or at least I know I do!
Anyway, from my first impression, the cuts will be deep and the least we can do is to develop two branches at the same time and finally merge them at some point. (I have the same experience doing such thing in [Mapbox iOS SDK](https://github.com/mapbox/mapbox-ios-sdk) from scroll view to openGL). This way the final result will maintain the robustness and future updates will be implanted beforehand.
Let me know what you think.

**Comment by appleguy** [comment]
@jessesquires @mohpor I was engaged in reading #492 and ended up commenting before I noticed the issue was closed — those comments actually belong here, but I'll spare the community of the duplication :).

**Comment by jessesquires** [comment]
Closing in favor of #1337.

**Comment by appleguy** [comment]
@jessesquires you have one heck of an amazing and valuable framework on your hands here, man — would you be willing to try a prototype branch with me before closing this out?  I can guarantee 60FPS on  all A5 devices, and am pretty confident we can get there on the iPhone 4 as well.  Pinterest 6.0 (coming in March) has a quite complex homefeed, but is already running at 60FPS on A5 — and we've hardly done any optimization at all.

https://www.youtube.com/watch?v=TGkZ3vXoMh0

**Comment by jessesquires** [comment]
@appleguy ha, thanks :smile: 

OK, fair enough. Nothing to loose from a prototype. :+1:

**Comment by appleguy** [comment]
@jessesquires sounds good man!  BTW - one reason for the offhanded compliment is that I saw Cocoapods now supports showing the # of apps with a framework installed.  I was genuinely impressed to see this one at ~5,000!  That's incredible!  I'm proud of ASDK breeching 1,700, and reaching its highest state of development velocity (nothing's ever perfect, though)...but sheesh, that's a huge development audience :)

**Comment by jessesquires** [comment]
@appleguy Thanks :smile: Actually, I'm pretty surprised by its popularity, too. Never expected that. :laughing:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
