### ISSUE TITLE
Unknown command: `JSQMessagesViewController`

### ISSUE THREAD

**Issue by johnnydicamillo** [jessesquires/JSQMessagesViewController#770]
I am very confused following the documentation on how to install or download this.
The documentation states:
# For latest release in cocoapods
pod 'JSQMessagesViewController'  

but I get the following from my terminal
Unknown command: `JSQMessagesViewController`

**Comment by weekwood** [comment]
You need know [what is cocoapods](http://cocoapods.org/).
