### ISSUE TITLE
JSQMessagesDatasource is extending UICollectionViewDatasource

### ISSUE THREAD

**Issue by stkhapugin** [jessesquires/JSQMessagesViewController#772]
What is the point of extending the same collection view datasource with message-specific methods? Because of this, there is no way to separate concerns of cell datasource and message datasource. So you are forced to either implement entire cell datasource separately (which defeats the point in having this component) or subclass JSQMessagesViewController and override those methods in it. The second solution is a bit ugly, since you may want to store your data providing logic (~ model layer) separately from cell providing logic (~ view layer), for instance in MVVM paradigm. Also a separate delegate would be a smaller class that is tested more easily, etc etc. 
This is basically a question of containment over inheritance, and there is a lot on this topic on the internet. 
I will gladly provide a PR to separate message datasource to a separate `@property (nonatomic, weak) id <JSQMessagesDatasource> messagesDatasource` if you agree with the above. Should be quite easy to make this compatible with existing interface too.

edit: removed another concern which was actually my fault

**Comment by jessesquires** [comment]
Thanks @stkhapugin - things are the way they are for many different legacy reasons, as well as difficulties regarding making this a reusable framework.

This is already on my TODO list. See #453 

This was attempted for the v6.0 release, but because of other major changes happening, it was de-scoped.
