### ISSUE TITLE
Fails to Load Nib `JSQMessagesViewController`. iOS 8.0, Swift, CocoaPods

### ISSUE THREAD

**Issue by charlierproctor** [jessesquires/JSQMessagesViewController#773]
When trying to load the messages view controller in `super.viewDidLoad()` of a `JSQMessagesViewController` subclass, I'm getting the following error:
```
2015-02-06 16:22:26.609 MyApp[38983:434438] *** Terminating app due to uncaught exception
'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle 
</....../Library/Developer/CoreSimulator/Devices/804E3674-2B93-47F9-8F5D-
F34DDD54842F/data/Containers/Bundle/Application/FE4D781D-F855-49B9-BBC7-
340B51E317AA/MyApp.app> (loaded)' with name 'JSQMessagesViewController''
```
I'm using Xcode 6.1.1 (6A2006) and iOS 8.0 (Swift) on a Mac with Yosemite 10.10.2. I've included `JSQMessagesViewController` `v6.1.3` via CocoaPods `v0.36.0.beta.2`.
```ruby
platform :ios, '8.0'
pod 'JSQMessagesViewController', '~> 6.1.3'
```
I've added breakpoints to hone in on the error and it seems to occur in the `+ (UINib *)nib` class function in `JSQMessagesViewController.m`:
```objc
+ (UINib *)nib
{
    return [UINib nibWithNibName:NSStringFromClass([JSQMessagesViewController class])
                          bundle:[NSBundle bundleForClass:[self class]]];
}
```
I've tried rebuilding, reinstalling the pod, resetting simulator, clearing `DerivedData`, and nothing seems to work. 
I may be doing something wrong... if so, I'd love any suggestions! Let me know what other information I should provide. Thanks!

**Comment by jessesquires** [comment]
Thanks @charlierproctor !

Damn. I think I know the problem. In the local pod, try changing the bundle to this: 

````objective-c
[NSBundle bundleForClass:[JSQMessagesViewController class]]
````

Please let me know if that fixes it.

**Comment by charlierproctor** [comment]
Yes -- works perfectly!! That fixes it. Thank you so much.

**Comment by jessesquires** [comment]
Awesome. Thanks @charlierproctor - this will be fixed in the next update

**Comment by ChandlerD** [comment]
I am having the same issue with the newest version, 7.0.2. The fix that you implemented does not seem to fix the problem.

**Comment by heartasice** [comment]
I got the same issue as @ChandlerD with the version 7.0.2 (pods) ,and I did not use Swift also. @jessesquires

**Comment by jessesquires** [comment]
@heartasice - please update to the latest release

**Comment by saurabytes** [comment]
@jessesquires ditto, using 7.1.0(latest pod) and getting this error. Few details that might help:
1) Works from a Swift project(Test) with Bridging header
2) Doesn't work from my main project which is dominantly ObjC but the ViewController in question is Swift with a storyboard

**Comment by skyefreeman** [comment]
@saurabytes Was having this same issue on version 7.2. Make sure the 'Copy Pods Resources' build phase is present on your project target.  The latest cocoapod version (0.39) had this phase omitted after running 'pod install'.  Adding it manually fixed this for me.
![image](https://cloud.githubusercontent.com/assets/4419983/10585919/bb488188-7667-11e5-88e3-53f0d77f8b13.png)

**Comment by Marindrew** [comment]
@skyefreeman thank you very much! I had the same issue with version 7.2 and unchecking "Run script only when installing" and checking it again after build solver the issue for me.

**Comment by otymartin** [comment]
@jessesquires This problem still persists in `7.3.4` Xcode `8.3.2`
