### ISSUE TITLE
How to use UIRefreshControl

### ISSUE THREAD

**Issue by tomojiro1125** [jessesquires/JSQMessagesViewController#775]
I used this below code about UIRefreshControl,
but this error message is shown.
Then, how can I add UIRefreshControll ?
Or should I add other github code about UIRefreshControl ?

***CODE***
[self.view addSubview:refreshControl];

***Error message***
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIRefreshControl may only be managed by a UITableViewController'

Sincely Regards,

**Comment by mohpor** [comment]
If you are doing it in your subclass of `JSQMessagesViewController.h` 
try this instead:

```Objective-C
    [self.collectionView addSubview:refreshControl];
```

**Comment by tomojiro1125** [comment]
Hi, mophor
Thanks to your kindness, I could solve the issue.
Thank you so much.

**Comment by mohpor** [comment]
Glad I could help
