### ISSUE TITLE
Implement Objective-C nullability 

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#776]
From [Xcode 6.3 beta release notes](http://adcdownload.apple.com//Developer_Tools/Xcode_6.3_beta/Xcode_6.3_beta_Release_Notes.pdf):

>Objective-C APIs can now express the “nullability” of parameters, return types, properties, variables, etc.
>
>The nullability qualifiers affect the optionality of the Objective-C APIs when in Swift. Instead of being imported as implicitly-unwrapped optionals (e.g., UINib!), nonnull-qualified types are imported as non-optional (e.g., UINib) and nullable-qualified types are imported as optional...

**Comment by elprl** [comment]
I'm also seeing compile errors on a Swift project when using this cocoapod with Xcode 6.3 and Swift 1.2.

**Comment by jessesquires** [comment]
@elprl - *compile* errors?

**Comment by apersaud** [comment]
+1. What would be the temporary work around? 
The problematic line is:
```objective-c
@property (readonly, nonatomic) JSQMessagesCollectionView *collectionView;
```

However, looking at the implementation `JSQMessagesCollectionViewFlowLayout`, I don't see a method defined for the `readonly` attribute. Adding the nullability options, didn't quite work.

Thanks.

**Comment by relatedcode** [comment]
+1. Same here with Xcode 6.3.

*Property type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'*

Any idea to eliminate these warnings? Thanks!

**Comment by jessesquires** [comment]
hey all - i'm aware of the warning:

````
Property type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'
````

See #453 and #828.

Everything should continue to work fine (just a warning). A fix will be coming soon.

**Comment by relatedcode** [comment]
@jessesquires Cool. Thanks!

**Comment by jessesquires** [comment]
Attempt at #1213 if someone wants to pickup where it left off

**Comment by Lucashuang0802** [comment]
I have done this before, do you prefer to continue from #1213 or start from `develop` branch?

**Comment by jessesquires** [comment]
Hey @Lucashuang0802 😄 

We should definitely start fresh from `develop`, but use #1213 as a reference. There have been a few significant changes since #1213, but most of the work there is probably still correct, so it's a good reference 👍

**Comment by Lucashuang0802** [comment]
I noticed some of them has included the modifiers. I have done this by following the existing documentation. I have also run a couple eye-scanning checks myself. lol. #1654. I do believe having another person to check is better for this change.
