### ISSUE TITLE
remove Internationalization of ressources from the pod.

### ISSUE THREAD

**Issue by benoit-pereira-da-silva** [jessesquires/JSQMessagesViewController#778]
To prevent partial localization can you remove the localization files from the pod.
May be there is a trick?

**Comment by jessesquires** [comment]
hey @benoit-pereira-da-silva - you can simply reset the various text labels to disable the localization.

**Comment by benoit-pereira-da-silva** [comment]
The simple presence of the .lproj folder declares the languages on the app store, ... To fix it temporarily I've forked and deleted the files. I feel you should declare a localization subspec.

**Comment by jessesquires** [comment]
:+1: #784 opened

**Comment by jessesquires** [comment]
Here's how you can remove localizations that you don't want:
https://github.com/mattt/FormatterKit#removing-unused-localizations

/cc: @benoit-pereira-da-silva

**Comment by benoit-pereira-da-silva** [comment]
This trick do not work for me actually with JSQMessagesViewController (7.0.0) 
What could be the best approach ? 

```
prepare_command = <<-CMD
SUPPORTED_LOCALES="['base','en']"
find . -type d ! -name "*$SUPPORTED_LOCALES.lproj" | grep .lproj | xargs rm -rf
CMD
```
![jsqmessage](https://cloud.githubusercontent.com/assets/963307/6938939/eb8beb12-d867-11e4-9452-6632ecf09039.png)

It displays Frenglish :)

![img_2792](https://cloud.githubusercontent.com/assets/963307/6938948/0872cb10-d868-11e4-822a-05dada435f31.PNG)
