### ISSUE TITLE
Scroll position jumps from top to bottom when view appears, bad viewWillAppear transition

### ISSUE THREAD

**Issue by ghazel** [jessesquires/JSQMessagesViewController#780]
Due to this change: https://github.com/jessesquires/JSQMessagesViewController/commit/da13cc302c7e76375322447e1e7eb8eb7029afb6#diff-9f8e863c5a195f9039e5062bb4d0fa1fL167 the collectionView jumps from the top to the bottom when it appears (particularly bad if the collectionView is large and slow to layout).

Why dispatch_async at all? Maybe the root issue was fixed by the scroll to bottom enhancements, like https://github.com/jessesquires/JSQMessagesViewController/commit/0d8667d14ecc3cfc7318a58fc0d74961e0ee2881 or https://github.com/jessesquires/JSQMessagesViewController/commit/697c839c80d6581e99a702315e573af292eea9af ?

In my tests, removing the dispatch_async fixes the problem, and does not introduce any noticeable issues.

**Comment by jessesquires** [comment]
Thanks @ghazel ! :+1: 

That's exactly right. The `dispatch_async` was a sad workaround for the `scrollToBottom` issues.

I set this for the next release.

**Comment by ghazel** [comment]
Ok, not quite. Without the dispatch, the last message is often offscreen when the view appears, and then scrolls animated in to place. Using one `scrollToBottomAnimated:NO` in viewWillAppear and dispatch_asyncing another makes it both appear without a jump (the original goal) and not have that last message oddity.

So, there's some other sizing or inset changing event involved here.

**Comment by ghazel** [comment]
Turns out it's not completely without consequence. I found a common case where the very last message is off screen. Waiting for `viewDidLayoutSubview` to perform the `[self scrollToBottomAnimated:NO];` seems to address it, which is at least a little bit more understandable than `dispatch_async`.

**Comment by jessesquires** [comment]
Thanks @ghazel :+1:

**Comment by jessesquires** [comment]
Nope. Looks like the "flag variable + `viewDidLayoutSubviews`" approach still breaks when pushing on a navigation stack with a lot of messages.

**Comment by ghazel** [comment]
Flag variable? I just call `scrollToBottomAnimated:NO` every time `viewDidLayoutSubviews` is called.

**Comment by jessesquires** [comment]
@ghazel - Right we definitely **do not** want this — every time the view gets laid out by the system, we'll be scrolling to the bottom. `viewDidLayoutSubviews` can be called for lots of different reasons.

thus, we would only want to do this when the view first loads.

````objective-c
- (void)viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];
    if (!self.didDoFirstLayout) {
        if (self.automaticallyScrollsToMostRecentMessage) {
            [self scrollToBottomAnimated:NO];
        }
        self.didDoFirstLayout = YES;
    }
}
````

**Comment by ghazel** [comment]
Hm. It hasn't been a problem for me, but I also manage `automaticallyScrollsToMostRecentMessage` in realtime.

I guess the first layout is insufficient. Not sure which layout is the one you'd need to wait for.

**Comment by jessesquires** [comment]
Ah, that makes sense.

`viewDidLayoutSubviews` is called on rotation, status bar changes, etc.

Looks like we'll have to stick with the `dispatch_async` for now

**Comment by ghazel** [comment]
Here's an idea; set a boolean like `firstLayout`, then use `dispatch_async` to queue up disabling it. If it's set in `viewDidLayoutSubviews`, do the scroll.

```objc
- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
    [self.view layoutIfNeeded];
    [self.collectionView.collectionViewLayout invalidateLayout];
    
    if (self.autoScrollsToMostRecentMessage) {
        self.firstLayout = YES;
        dispatch_async(dispatch_get_main_queue(), ^{
            self.firstLayout = NO;
        });
    }
    ...
}

- (void)viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];
    if (self.firstLayout && self.automaticallyScrollsToMostRecentMessage) {
        [self scrollToBottomAnimated:NO];
    }
}
```

**Comment by eviltofu** [comment]
I have a project which opens another view controller on top of a JSQMessagesViewController. When I pop the top view controller and come back to the JSQMessagesViewController, the keyboard is in the correct position but the latest messages are not being displayed. The view looks like the keyboard was not present, with the latest messages hidden behind the keyboard. I can scroll the view and see the latest messages. 
Putting a copy of the dispatch_async that calls [self scrollToBottomAnimated:NO] in my viewWillAppear: method did not change anything. Putting it in my viewDidAppear: method correctly scrolled the bottom of the messages.

**Comment by brizzly** [comment]
@ghazel solution is working like a charm for me. @eviltofu is not. Thanks guys!

**Comment by francislata** [comment]
Note that for this solution that @ghazel have it works. However do note that when you scroll somewhere in the messages view controller and push to another view that going back to the messages view controller will auto-scroll it to the bottom.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
