### ISSUE TITLE
JSQMessagesViewController datasource/delegates not getting called

### ISSUE THREAD

**Issue by attheodo** [jessesquires/JSQMessagesViewController#782]
Hello,
I've setup my ViewController like this https://gist.github.com/attheodo/a78c3578d7fd899637ab

However I can't get it to call datasource/delegate methods. Additionally the inputToolbar doesn't respond to keyboard moving in/out and the inputTextView is not growing with text.

What am I missing?

Oh, and kudos for the wonderful library, it seems it'll save me tons of time. Beers on me :)

**Comment by attheodo** [comment]
I am on Cocoapods 0.36.0.beta.2 if that helps narrowing down the issue

**Comment by attheodo** [comment]
For starters, it turned out I accidentally used some wrong datasource method names (which is why I couldn't understand the compiler wouldn't accept the `override` keyboard). I implemented again the required `datasource` methods, but still same problem.

Updated gist: https://gist.github.com/attheodo/77ba6918ab1ff075f811

The README file says I also need to implement the required delegate methods as well. I checked the docs here http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.3/Protocols/JSQMessagesCollectionViewDelegateFlowLayout.html but not method is marked as `required`.

Any ideas?

**Comment by twairball** [comment]
where is `func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int` ?

**Comment by attheodo** [comment]
@twairball what is this method? I can't find it in the datasource or delegate docs.

**Comment by attheodo** [comment]
@jessesquires do I have to manually set the dataSource/delegate for the collectionView somewhere?

**Comment by attheodo** [comment]
@twairball @jessesquires I implemented `func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int` and now the view gets populated. I still have the inputToolbar not moving up with the keyboard and the textview not growing along with the input text. Any directions?

**Comment by jessesquires** [comment]
@attheodo - make sure you're calling super in all of the view[Did/Will]Appear methods

**Comment by jessesquires** [comment]
@attheodo the method mentioned by @twairball is part of the `UICollectionView` API

**Comment by attheodo** [comment]
@jessesquires calling `super.viewDidAppear()` solved the issue. Thanks.

**Comment by jessesquires** [comment]
:+1:
