### ISSUE TITLE
Unable to simultaneously satisfy constraints - Cell Bottom label

### ISSUE THREAD

**Issue by kevindelord** [jessesquires/JSQMessagesViewController#783]
Hi,

I got the following runtime error when I set a bottom space/label of an item in the collection view.

```
Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x17028d9d0 V:[JSQMessagesLabel:0x14c6639f0(20)]>",
    "<NSLayoutConstraint:0x170292020 V:[JSQMessagesLabel:0x14c6650b0(0)]>",
    "<NSLayoutConstraint:0x170292cf0 V:[JSQMessagesLabel:0x14c67a130(70)]>",
    "<NSLayoutConstraint:0x170292d90 V:|-(0)-[JSQMessagesLabel:0x14c6639f0]   (Names: '|':UIView:0x170198c80 )>",
    "<NSLayoutConstraint:0x170292e80 V:[JSQMessagesLabel:0x14c6639f0]-(0)-[JSQMessagesLabel:0x14c6650b0]>",
    "<NSLayoutConstraint:0x170292f20 V:[JSQMessagesLabel:0x14c6650b0]-(0)-[UIView:0x170198e20]>",
    "<NSLayoutConstraint:0x170292fc0 V:[UIView:0x170198e20]-(0)-[JSQMessagesLabel:0x14c67a130]>",
    "<NSLayoutConstraint:0x170293060 V:[JSQMessagesLabel:0x14c67a130]-(0)-|   (Names: '|':UIView:0x170198c80 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x17028fe10 h=--& v=--& V:[UIView:0x170198c80(38)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170292cf0 V:[JSQMessagesLabel:0x14c67a130(70)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

The error occurs when I set the `height` of the label and with or without an attributed string.
It happens with or without the `springinessEnabled`.
What is actually pretty annoying is that it does not happens all the time.
Depending on the content of the chat everything is fine.
I tried to find a logic by testing with small texts, big ones, images, etc. 

About the devices and versions, it occurred on:
- device:  iPhone 6 iOS 8.1.3
- simulation: iPhone 6 iOS 8.3
- xcode beta: 6.3 (6D520o)
- OS X 10.10.2
- The code is in swift

Here you go with some code:

```
    override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        // if it is the latest item then add an empty text
        if (indexPath.item == (self.messages.count - 1)) {
            return NSAttributedString(string: "")
        }
        return nil
    }

    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
        // if it is the latest item then add a bottom margin
        if (indexPath.item != (self.messages.count - 1)) {
            return 70
        }
        return 0.0
    }
```

**EDIT:**
The error does NOT occur when the same bottom label and bottom height is set to `ALL` items in the collection view.

Thanks a lot,
Kevin

**Comment by jessesquires** [comment]
hey @kevindelord - which version of the lib?

**Comment by kevindelord** [comment]
Oops, I knew I forgot something.
The lib is installed as a pod:
````
pod 'JSQMessagesViewController', '~> 6.1.1'
```

**Comment by cerupcat** [comment]
We're seeing the same issue here on the obj-c side.

If we set heightForMessageBubbleTopLabelAtIndexPath and heightForCellBottomLabelAtIndexPathto always return kJSQMessagesCollectionViewCellLabelHeightDefault then this goes away.

Setting them to be the same height isn't a good solution though since it causes a gap between every cell.

**Comment by mikewadhera** [comment]
Can confirm on 7.0.2 - setting the bottom label's height equal to the top label is a workaround, but as mentioned this provide's gaps if you have messages with empty top labels.

**Comment by Luke47** [comment]
@jessesquires Any news about this issue? :) I guess it's caused about not resetting cell constraints in `prepareForReuse`? Thanks!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
