### ISSUE TITLE
inputToolbar not behaving properly

### ISSUE THREAD

**Issue by attheodo** [jessesquires/JSQMessagesViewController#785]
More details on the the problems described in (#782), please check this video: https://www.dropbox.com/s/2ckouinbf29s4hg/demo.mov?dl=0

I've set up some debugging messages and it appears `- (void)jsq_didReceiveKeyboardDidShowNotification:(NSNotification *)notification` in `JSQMessagesKeyboardController.m:189` is never getting called.

**Comment by jessesquires** [comment]
thanks @attheodo! :+1: let's keep this on the thread in #782. I've replied there with some tips
