### ISSUE TITLE
[Parse] Turning PFObject into JSQMessage

### ISSUE THREAD

**Issue by kyco16** [jessesquires/JSQMessagesViewController#786]
I have posted my question on StackOverflow and I haven't got many views probably because this a complex question but here is the link to [My StackOverflow question](http://stackoverflow.com/questions/28484821/using-jsqmessagesviewcontroller-with-parse-com). I am having trouble with this JSQMessage. I know how to take a PFObject and put them into a TableView(tableviews are pretty much the same as CollectionViews) but I do not know to transfer over or assign the values from the PFObject to the ones in JSQMessage.

 I looked at question #178 and I think that was for an older version of this library. I am still learning Objective-C, a good 6 months on my own, but I am absolutely riddled when it comes to this entire library and I really want to use it. I have posted code my entire .h and .m files on my StackOverflow question as well.

**Comment by jessesquires** [comment]
Hey @kyco16 - no worries :smile: 

It looks like your `messages` is holding `PFObject`s. In that case, my answer from #178 applies.

(updated for latest version of the library)

>Parse allows native subclasses now, so you don't have to use a plain `PFObject`. You should subclass `PFObject`, and simply have your object conform to the `JSQMessageData` protocol. There's no need to edit your existing fields/properties on your `PFObject`, just implement the methods in `JSQMessageData` and return the appropriate data.

>Then, you can simply add your `PFObject` subclass to your local datasource. (i.e., don't use `JSQMessage` -- you already have your model objects)

>I can't tell from your snippets, but it looks like `self.messages` contains might contain `PFObjects`, so the cast to `JSQMessage` won't work.

JSQMessageData: http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.3/Protocols/JSQMessageData.html

Working with protocols:
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithProtocols/WorkingwithProtocols.html

**Comment by kyco16** [comment]
Ah wow. You are really on point with these references. So what I should be doing is creating a custom class with a ```PFObject``` subclass and have that conform to the ```JSQMessageData``` protocol?

**Comment by jessesquires** [comment]
@kyco16 - exactly! let me know how that works out

**Comment by kyco16** [comment]
So I picked up on a few things while reading those two references. I didn't know delegates and protocols were like the same thing. The .h of my custom class looks like so
```
#import <Parse/Parse.h>
#import <JSQMessagesViewController/JSQMessages.h>


@interface MessageClass : PFObject <JSQMessageData>
```
so that would be a ```PFObject``` subclass conforming to the ```JSQMessageData``` protocol. In the .m of this custom class I have this

```
- (NSString *)senderDisplayName {
    return self[@"sender"];
}

- (NSString *)senderId {
    return self[@"objectID"];
}

- (NSString *)text {
    return self[@"messsage"];
}
```
I have these protocol methods being called in the ```init``` method in the custom class. I query for messages in the ViewController class and it'll load if there are no message. If I send one, only the text shows, and if there are messages coming from Parse when the view loads the exceptional break point stops at this line ```if ([messageItem isMediaMessage]) {``` in the JSQMessagesCollectionViewFlowLayout.m file

**Comment by kyco16** [comment]
Actually I just figured it out. I used this as reference since the project itself uses Parse as the backend and by looking at an example I realized what was going on. 

**Notification Chat:**
https://github.com/relatedcode/NotificationChat

It is a great reference for those are trying to use this library with the Parse backend

**Comment by jessesquires** [comment]
Thanks @kyco16 !

Please feel free to keep asking questions! :+1:
