### ISSUE TITLE
Add JSQMessagesComposerTextView delegate

### ISSUE THREAD

**Issue by gzw** [jessesquires/JSQMessagesViewController#787]
Hi, I want to catch JSQMessagesComposerTextView return-key event. so I add UITextViewDelegate in JSQMessagesToolbarContentView like this: 
1. add UITextViewDelegate in interface.
2. add  "self.textView.delegate = self;" in awakeFromNib method.
3. add UITextViewDelegate method in JSQMessagesToolbarContentView
     - (BOOL)textView:(UITextView *)textView shouldChangeTextInRange:(NSRange)range    replacementText:(NSString *)text {
        return YES;
}

I think the UITextViewDelegate method will be called. but it's not working.
I don't known why not work.

I write a simple demo about UITextViewDelegate. it works.

**Comment by jessesquires** [comment]
@gzw - If you have time, please share your solution in case others have the same question in the future. :smile:
