### ISSUE TITLE
Easiest way to change the views top margin

### ISSUE THREAD

**Issue by attheodo** [jessesquires/JSQMessagesViewController#788]
I have a custom UINavigationBar created at runtime in my JSQMessagesViewController. This is not inherited from UINavigationController. The problem is the collection's view top part is being overlapped by my custom navigation bar. What's the proper way to modify the constraints of the collection view to set it's top to be aligned with the navigation bar bottom? I tried exactly this but there was a constraint conflict and the way it was resolved the navigation bar was pushed by the collection's view top outside the view frame.

thanks

**Comment by jessesquires** [comment]
Hey @attheodo - sounds like `topContentAdditionalInset` is what you need.

http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.3/Classes/JSQMessagesViewController.html#//api/name/topContentAdditionalInset
