### ISSUE TITLE
Some characters crash editable UITextViews

### ISSUE THREAD

**Issue by ghazel** [jessesquires/JSQMessagesViewController#791]
Some characters cause UITextView to crash, when the TextView is editable. An example is: `@"पा मरप तबवहै ौो कत ऐ ँ?";` (please be very careful when using it -- it can crash Xcode too!)

`jsq_currentlyComposedMessageText` sets the text on an editable UITextView, when the user types a string:

```objc
- (NSString *)jsq_currentlyComposedMessageText
{
    //  add a space to accept any auto-correct suggestions
    NSString *text = self.inputToolbar.contentView.textView.text;
    self.inputToolbar.contentView.textView.text = [text stringByAppendingString:@" "];
    return [self.inputToolbar.contentView.textView.text jsq_stringByTrimingWhitespace];
}
```

To work around this, you can use a different strategy to accept auto-correct

```objc
- (NSString *)jsq_currentlyComposedMessageText
{
    // accept any auto-correct suggestions
    [self.inputToolbar.contentView.textView.inputDelegate selectionWillChange:self.inputToolbar.contentView.textView];
    [self.inputToolbar.contentView.textView.inputDelegate selectionDidChange:self.inputToolbar.contentView.textView];
    return self.inputToolbar.contentView.textView.text;
}
```

#466

**Comment by jessesquires** [comment]
this is awesome.

**Comment by jessesquires** [comment]
@ghazel - Y U NO SUBMIT PRs

![img](http://stickerish.com/wp-content/uploads/2011/04/YUNOGuyBlackSS.png)

**Comment by jessesquires** [comment]
![img](http://media.giphy.com/media/Un8RpWaTkAOLm/giphy.gif)
