### ISSUE TITLE
Preferred way to dynamically update label below the cell

### ISSUE THREAD

**Issue by attheodo** [jessesquires/JSQMessagesViewController#792]
Hello, 
I would like to dynamically update the label below the cell with text like "Read 13:30" or "Delivered" much like the iMessages app. This information obviously comes dynamically through NSNotificationCenter and not available to the datasource upfront. What's the preferred way for doing this without significant performance overheads... i.e reload the Collection View. Are there specific properties exposed to achieve something like this?

Thanks again

**Comment by jessesquires** [comment]
Hey @attheodo - Assuming your message model objects have some kind of "status" property that you are updating, when you receive that update, you should know at which `indexPath` that message is located. Thus, you can return the appropriate status from the delegate method and then reload the `collectionView` for that specific `indexPath`.

**Comment by attheodo** [comment]
That sounds logical. Which delegates methods should I be looking for? Also, how do I get the reference for the label below the bubble?



—

**Comment by jessesquires** [comment]
You'll want `attributedTextForCellBottomLabelAtIndexPath:`

http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.3/Protocols/JSQMessagesCollectionViewDataSource.html#//api/name/collectionView:attributedTextForCellBottomLabelAtIndexPath:

You can get the cell via `[collectionView cellForItemAtIndexPath:];`, then grab the label from that cell.
