### ISSUE TITLE
Incorrect messageBubbleImageView height in comparison with cell height

### ISSUE THREAD

**Issue by thibaultleconte** [jessesquires/JSQMessagesViewController#794]
in ViewDidLoad, I initialize up the incoming and outgoing images this way:
```
JSQMessagesBubbleImageFactory *bubbleFactory = [[JSQMessagesBubbleImageFactory alloc] init];
self.outgoingBubbleImageData = [bubbleFactory outgoingMessagesBubbleImageWithColor:[iOSAppearanceHelper getColorForCustomWUColorLow]];
self.incomingBubbleImageData = [bubbleFactory incomingMessagesBubbleImageWithColor:[iOSAppearanceHelper getColorForCustomWUColorHigh]];
```

I also set the image this way:
```
- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath {
    MessageCD *message = [self.fetchedResultsController objectAtIndexPath:indexPath];
    if ([message.uid isEqualToString:self.senderId])
        return self.outgoingBubbleImageData;
    return self.incomingBubbleImageData;
}
```

The only place i am customizing the cell height is : 
```
- (CGFloat)collectionView:(JSQMessagesCollectionView *)collectionView
                   layout:(JSQMessagesCollectionViewFlowLayout *)collectionViewLayout heightForCellTopLabelAtIndexPath:(NSIndexPath *)indexPath {
    if (indexPath.row == 0) {
        return kJSQMessagesCollectionViewCellLabelHeightDefault;
    } else if ([[[self.fetchedResultsController sections] objectAtIndex:0] numberOfObjects] >= 2) {
        MessageCD *messagecd = [self.fetchedResultsController objectAtIndexPath:indexPath];
        MessageCD *prevMessagecd = [self.fetchedResultsController objectAtIndexPath:[NSIndexPath indexPathForItem:indexPath.row-1
                                                                                                        inSection:indexPath.section]];
        if ([TimeHelper checkDate:messagecd.hour_group isEqualToDate2:prevMessagecd.hour_group] == NO)
            return kJSQMessagesCollectionViewCellLabelHeightDefault;
    }
    return 0.0f;
}
```

The cells have the right height but the bubble image seems to not respect the cell height.

I have been using Master and Develop branches : same issue with both.

Any idea where I should look at?

![screen shot 2015-02-15 at 10 40 29 am](https://cloud.githubusercontent.com/assets/881692/6203756/4ee957c6-b4ff-11e4-857b-607762d839b2.png)

**Comment by jessesquires** [comment]
hey @thibaultleconte - not sure... are you using a custom font? there are known issues with this.

**Comment by thibaultleconte** [comment]
Hi Jesse,
Thx for your answer.
I disabled the custom font the following way in viewdidload and i still have the same issue.
```
//self.collectionView.collectionViewLayout.messageBubbleFont = [iOSAppearanceHelper getFontForSize:FONT_SIZE_MEDIUM];
```
I am going to look further into that. I may have miss something with the font.
If you have a past issue with similar problem, please share it with me. I may find some hints there...
Thx for your help

**Comment by jessesquires** [comment]
@thibaultleconte - see #347

**Comment by thibaultleconte** [comment]
I figured it out!
I made a stupid mistake: I had a UIImageView category which was setting contentMode to UIViewContentModeScaleAspectFill for my entire project!
Thank you for your help and congrats on your work @jessesquires

**Comment by jessesquires** [comment]
Thanks for the update @thibaultleconte !
