### ISSUE TITLE
Portrait image not handled correctly.  

### ISSUE THREAD

**Issue by bhartsb** [jessesquires/JSQMessagesViewController#795]
In the sample app if I replace the golden gate landscape image with a portrait image taken with the camera, and then compile and run, and next add it as a media message, the media message displayed remains landscape and the image has the top and bottom thirds cropped off (I'm approximating when I say thirds).

**Comment by bhartsb** [comment]
Actually, it looks like I just need to make some modifications to the method - (CGSize)mediaViewDisplaySize in JSQMediaItem.m

**Comment by wdcurry** [comment]
Why not explain what you had to do rather than leaving it hanging?

**Comment by bhartsb** [comment]
Sorry, I haven't made the change yet, but mediaViewDisplaySize hardcodes
the mediaItem display size to landscape dimensions.  Swapping the x and y
gives better results for a portrait image, but there is still some minor
amount of clipping (note just swapping the x and y without doing anything
else makes the landscape scale poorly, and with too much clipping).  In the
class JSQPhotoMediaItem.m the method - (UIView *) mediaView is performing
the scaling by setting the contentMode = UIViewContentModeScaleAspectFill
which scales the content to fill the size of the view, and as the Apple
doc's say "...some portion of the content may be clipped to fill the view's
bounds".  So a possible solution is to make sure that mediaViewDisplaySize
calculates whether the image has portrait or landscape dimensions, and then
return a size that has the same proportions as the image, and is less than
the max width of the JSQMessagesView minus the width of the avatar columns
to the left and right.

**Comment by jessesquires** [comment]
@bhartsb - yes, the current implementation of `mediaViewDisplaySize` is very naive. it can be improved.

**Comment by scotteg** [comment]
@jessesquires @bhartsb As a quick and dirty solution, I added an extension on `JSQPhotoMediaItem` and also a custom operator to allow some leeway (10 points) in matching for square photos:

```swift
func ≃(lhs: CGFloat, rhs: CGFloat) -> Bool {
    let ratio = lhs / rhs
    return ratio > 0.95 && ratio < 1.05
}

extension JSQPhotoMediaItem {
    
    static let portraitSize = CGSize(width: 225.0, height: 315.0)
    static let landscapeSize = CGSize(width: 315.0, height: 225.0)
    static let squareSize = CGSize(width: 315.0, height: 315.0)
    
    override open func mediaViewDisplaySize() -> CGSize {
        guard let image = image else { return JSQPhotoMediaItem.landscapeSize }
        let width = image.size.width
        let height = image.size.height
        
        if width ≃ height {
            return JSQPhotoMediaItem.squareSize
        }
        
        if width > height {
            return JSQPhotoMediaItem.landscapeSize
        }
        
        return JSQPhotoMediaItem.portraitSize
    }
}
```
