### ISSUE TITLE
JSQVideoMediaItem video thumbnail image

### ISSUE THREAD

**Issue by relatedcode** [jessesquires/JSQMessagesViewController#796]

**Comment by relatedcode** [comment]
Any chance to set the JSQVideoMediaItem video thumbnail image without going deep? Thanks!

**Comment by jessesquires** [comment]
@relatedcode - not sure what you mean, but the feature is being tracked at #628

**Comment by relatedcode** [comment]
@jessesquires My original idea was: if I generate the video thumbnail by myself, how can I set the thumbnail image without digging deep inside JSQVideoMediaItem. Thanks!

**Comment by Fontinhas** [comment]
What I did was subclass the NimbeeJSQVideoMediaItem and replaced the -mediaView function with something along these lines:

```objective-c
- (UIView *)mediaView
{
    if (self.fileURL == nil || !self.isReadyToPlay) {
        return nil;
    }
    
    if (self.cachedVideoImageView == nil) {
        CGSize size = [self mediaViewDisplaySize];


        UIImage *videoThumbnail = [self generateThumbnailFromVideo];
        
        UIImageView *imageView = [[UIImageView alloc] initWithImage:videoThumbnail];
        imageView.backgroundColor = [UIColor blackColor];
        imageView.frame = CGRectMake(0.0f, 0.0f, size.width, size.height);
        imageView.contentMode = UIViewContentModeCenter;
        imageView.clipsToBounds = YES;
        [JSQMessagesMediaViewBubbleImageMasker applyBubbleImageMaskToMediaView:imageView isOutgoing:self.appliesMediaViewMaskAsOutgoing];
        self.cachedVideoImageView = imageView;
    }
    
    return self.cachedVideoImageView;
}

-(UIImage*)generateThumbnailFromVideo
{

     AVAsset *asset = [AVAsset assetWithURL: self.fileURL];
    AVAssetImageGenerator *imageGenerator = [[AVAssetImageGenerator alloc]initWithAsset:asset];
    
    [imageGenerator setAppliesPreferredTrackTransform:YES];
    CMTime time = CMTimeMake(1, 1);
    CGImageRef imageRef = [imageGenerator copyCGImageAtTime:time actualTime:NULL error:NULL];
    UIImage *thumbnail = [UIImage imageWithCGImage:imageRef];
    CGImageRelease(imageRef);

    return thumbnail;

}

```

**Comment by jessesquires** [comment]
@Fontinhas / @relatedcode - yep! subclassing like this the best solution for now. but this will become part of the library soon

**Comment by relatedcode** [comment]
@jessesquires Thanks man! :)

**Comment by jessesquires** [comment]
@relatedcode - since you resell open-source projects for profit, you should consider contributing by submitting a pull-request :smile:

**Comment by relatedcode** [comment]
@jessesquires I can't see where do I resell any open-source projects for profit, but next time I will submit a pull-request. :)

As far as I know all my projects are open source and free to use for anyone.

**Comment by jessesquires** [comment]
Ahh, I see everything has been removed from [codecanyon](http://codecanyon.net/user/relatedcode) :clap:

**Comment by relatedcode** [comment]
@jessesquires It was really long time ago. I just tried it. But now I know, open source is the nice way to play. Best regards.

**Comment by n13** [comment]
I am implementing a video view, and what I don't understand is what mediaItem is supposed to do. Is it a view? Is it a controller?

So the main issue I see with the code above is caching the view. That would mean every video item has one of these views potentially, and if I were to scroll through hundreds of videos, they would all end up in memory. 

I was tracing the code a bit further and it seems like in each instance a message has an item, and an item has a view (once displayed). Everything sticks around. This is exactly what a table / collection view should not do. It should created these views on demand, possibly recycle them, but definitely not hold on to them. Imagine a window with 10,000 video messages. 

Or am I missing something here?
