### ISSUE TITLE
Improve implementation of mediaViewDisplaySize?

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#797]
Detect `mediaItem` aspect ratio and return a more appropriate `mediaViewDisplaySize`

**Comment by bhartsb** [comment]
This is what I added/changed in my JSQPhotoMediaItem.h:

#import "JSQMessagesAvatarImageFactory.h"

static CGFloat avatarImageWidth;

- (instancetype)initWithImage:(UIImage *)image
{
    self = [super init];
    if (self) {
        _image = [image copy];
        _cachedImageView = nil;
    }
    
    
    static BOOL b = false;
    
    if (!b) {
        UIImage *mockImage = [UIImage imageNamed:@"demo_avatar_jobs"];
        JSQMessagesAvatarImage *avatar = [JSQMessagesAvatarImage avatarWithImage:mockImage];
        avatarImageWidth = avatar.avatarImage.size.width;

        b = true;
    }
    
    return self;
}

- (CGSize)mediaViewDisplaySize
{
    CGRect screenRect = [[UIScreen mainScreen] bounds];
    
    CGFloat aspectRatio = _image.size.height/_image.size.width;
    
    CGFloat newWidth = screenRect.size.width - avatarImageWidth * 1.2;
    
    CGFloat deltaX = (_image.size.width - newWidth );
    
    return CGSizeMake( newWidth, _image.size.height - (deltaX*aspectRatio) );
    
}

**Comment by jessesquires** [comment]
Thanks @bhartsb ! :+1:

**Comment by bhartsb** [comment]
Sure:)

**Comment by bhartsb** [comment]
I updated - (CGSize)mediaViewDisplaySize

**Comment by PickMe** [comment]
Is that really all you changed? I get an Error in following line in JSQMessagesViewController.m:
JSQMessagesCollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:cellIdentifier forIndexPath:indexPath];

Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [160 nan]'

**Comment by IceFloe** [comment]
@jessesquires What do you think about adding some info about layout to mediaViewDisplaySize, it is really hard to find max bubble width for example. Can we add something like this? I can extend JSQMessageMediaData and JSQMessagesBubblesSizeCalculator for this, but it will be much easier to have this info in the mediaViewDisplaySize.

**Comment by eliburke** [comment]
@IceFloe can you give an example of why you want to know the bubble width? Are you trying to fit or align something inside or outside the bubble that could maybe be handled with autolayout?

> For #797 what we want is for media items to provide an aspect ratio, the layout will then use this to find the appropriate size. - @jessesquires

Can you describe an example of this in action? I know you weren't fond of the design I used in #1522 but I don't see size+aspect being very flexible. Do you plan to have the layout "adjusting" the provided view based on the aspect value? That won't easily accommodate Fit vs Fill behaviors or non-UIImage views.

**Comment by IceFloe** [comment]
@eliburke I understand, you can look at my idea in the https://github.com/jessesquires/JSQMessagesViewController/pull/1569

I will try to understand your idea as well.

Problem is in bad control for mediaViewDisplaySize. I cant find now what size will be for bubble from MediaItem, this cause for me some problems. For example it is rly hard to find the size for mediaItem which have picture and a lot of text(text view). As I said I avoid this by extending JSQMessagesBubblesSizeCalculator.

**Comment by IceFloe** [comment]
@eliburke I just want to share my idea, for me now is easy to calculate size for bubble :) I don't put it in black box which will do something with my bubble size. I can calculate all my params for bubble and this size will be right for me.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
