### ISSUE TITLE
Add a custome view below the toolbar 

### ISSUE THREAD

**Issue by varoodhiniKonda** [jessesquires/JSQMessagesViewController#798]
I want to add a custom view below the toolbar , when left accessory button clicked i want to move the toolbar upwards and below i want to show the custom view

how to do it, is there any way or  jsq classes to do it

**Comment by anilanar** [comment]
No, there's no way to do it.

@jessesquires I guess this can be labeled as feature request.

**Comment by jessesquires** [comment]
#750 should help with implementing this on your own. (coming in the next release)

Special cases like this are unlikely to become part of the library.
