### ISSUE TITLE
scenario when keyboard doesn't open

### ISSUE THREAD

**Issue by oanaBan** [jessesquires/JSQMessagesViewController#799]
Steps to repro:
1. Paste the text bellow in the bottom text view:
"sed turpis. Sed mollis, eros et ultrices tempus, mauris ipsum aliquam libero, non adipiscing dolor urna a orci. Nulla porta dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Pellentesque dapibus hendrerit tortor. Praesent egestas tristique nibh. Sed a libero. Cras varius. Donec vitae orci sed dolor rutrum auctor. Fusce egestas elit eget lorem. Suspendisse nisl elit, rhoncus eget, elementum ac, condimentum eget, diam. Nam at tortor in tellus interdum sagittis. Aliquam lobortis. Donec orci lectus, aliquam ut, faucibus non, euismod id, nulla. Curabitur blandit mollis lacus. Nam adipiscing. Vestibulum eu odio. Vivamus laoreet. Nullam tincidunt adipiscing enim. Phasellus tempus. Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros. Fusce neque. Suspendisse faucibus, nunc et pellentesque egestas, lacus ante convallis tellus, vitae iaculis lacus elit id tortor. Vivamus aliquet elit ac"
2. scroll up in bottom text view until you reach the middle of the pasted text
3. send the text and scroll up to close the keyboard 
4. tap inside the bottom text view

Actual result: the keyboard doesn't open. 

Note: I'm using the app from branch master, v 6.1.3 last commit on 11 Jan. iPhone 5C, iOS 8.1

Thanks

**Comment by jessesquires** [comment]
thanks @oanaBan !

**Comment by oanaBan** [comment]
@jessesquires any idea how I can fix this?

**Comment by anilanar** [comment]
More accurate steps: 

- Type/paste large enough text to make text view scrollable.
- Scroll a little bit upwards but not too much.
- Send.

Actual result: Input text view is unresponsive from now on.

------------------------

*So here is my findings:*

- After text view gets unresponsive, I did a hit test debugging. Text view responds to touch events, calls `touchesBegan:withEvent:` so it is not obstructed by another view, its `userInteractionEnabled` is still `YES`.
- After it gets unresponsive, changing the content offset or anything that causes an update for text view's scroll view state resets it and it becomes responsive again.
- It is not related to contentOffset being set to a negative value.
- It is definitely a bug on Apple's side

Workaround:

- Stop calling `jsq_scrollComposerTextViewToBottomAnimated:` when toolbar size shrinks.

**Comment by jessesquires** [comment]
thanks @anilanar !

>It is definitely a bug on Apple's side

:cry: 

What side effects does this workaround have?

**Comment by anilanar** [comment]
I haven't tested this workaround extensively but @oanaBan uses this workaround in her fork so maybe she could tell?

**Comment by oanaBan** [comment]
hey guys, 

I made a change in jsq_adjustInputToolbarForComposerTextViewContentSizeChange: method from 
"    if (dy < 0) {"
to 
"    if (dy < 0 && self.inputToolbar.contentView.textView.text.length > 0) {"

This fixed my initial issue and I didn't saw any side effects, everything works ok for me now.

**Comment by jessesquires** [comment]
Should be fixed by 752fd38aa8b899cbe2e21b6595de58920977bfc2
