### ISSUE TITLE
Input Toolbar rendered behing Tab Bar in Swift & iOS 8

### ISSUE THREAD

**Issue by KBLNY** [jessesquires/JSQMessagesViewController#800]
Hello,

I successfully implemented the JSQMessages based on the well-documented given example.

However, the input toolbar is not properly rendered. It is displayed behind the Tab Bar of my view (cf. image below)

![ios simulator screen shot 17 feb 2015 12 24 52](https://cloud.githubusercontent.com/assets/11043448/6227437/20d0e410-b6a0-11e4-90cd-202b5cf00cd8.png)

I started with a new clean project, in Swift, running for iOS 8, Universal. The view[Did/Will][Load/Appear] methods start with "super" calls.

Another interesting fact is the scroll bar which fit the right container, allowing the required space for the toolbar.

I would point out that this problem not occurred with the JSQMessages Framework v 5.2.1

Any ideas?

Thanks for your help,

Kevin

**Comment by jessesquires** [comment]
please see #94

**Comment by KBLNY** [comment]
Thank you very much for your work and support!
