### ISSUE TITLE
Issue with using JSQMessagesBubbleImageFactory

### ISSUE THREAD

**Issue by dave4506** [jessesquires/JSQMessagesViewController#802]
So I am trying to use the 6.0 version and right now I am refactoring my code. When I tried to get the incoming and out coming image to change to the 6.0 I cant I looked at many examples.
![screen shot 2015-02-17 at 3 18 55 pm](https://cloud.githubusercontent.com/assets/8580267/6239428/82529bf8-b6b8-11e4-99de-fec3a0dc1296.png)
instead of a UICOLOR it is a factory... 

What is happening?

**Comment by jessesquires** [comment]
`JSQMessagesBubbleImageFactory().outgoing...`

**Comment by jessesquires** [comment]
duplicate of #629
