### ISSUE TITLE
Custom NavigationBar 

### ISSUE THREAD

**Issue by zapdroid** [jessesquires/JSQMessagesViewController#803]
Hi, 
Is there a way customize navigationbar or create a new view to top of the collectionView. When i hide navigationbar collectionview covers whole view? Can you help me?  

Is topContentAdditionalInset can help me?

**Comment by jessesquires** [comment]
@zapdroid - the nav bar can be customized like any normal nav bar.

for new views on top, yes `topContentAdditionalInset` is what you want.
