### ISSUE TITLE
Detect when user is typing message

### ISSUE THREAD

**Issue by velthune** [jessesquires/JSQMessagesViewController#804]
Is there a way to detect when user is composing a message? Like a delegate or whatever..?

**Comment by anilanar** [comment]
`JSQMessagesViewController` sets itself as the delegate for input text view. You can override `textViewDidBeginEditing:` and `textViewDidEndEditing:`. Don't forget to call `[super textViewDidBeginEditing...]` etc.

**Comment by velthune** [comment]
Thanks! In the meanwhile I had already solved! Thanks anyway!

**Comment by sebleon** [comment]
I'd actually recommend doing the following. This will work if someone sends multiple messages in a row. `textViewDidBeginEdititing` will only work for the first message sent, but won't be called if a user hits send and starts typing another

```
- (void)textViewDidChange:(UITextView *)textView
{
    [super textViewDidChange:textView];
    NSInteger textLength =  textView.text.length;
    if (textLength == 1) {
        // Tell server about typing started here
    }
}
```
