### ISSUE TITLE
Input text view height is wrong after a rotation

### ISSUE THREAD

**Issue by anilanar** [jessesquires/JSQMessagesViewController#805]
**Case 1:**

Steps to reproduce:
- Switch to horizontal orientation in iPhone.
- Paste some long text into text view.

```
sed turpis. Sed mollis, eros et ultrices tempus, mauris ipsum aliquam libero, 
non adipiscing dolor urna a orci. Nulla porta dolor. Class aptent taciti sociosqu 
ad litora torquent per conubia nostra, per inceptos hymenaeos. Pellentesque 
dapibus hendrerit tortor. Praesent egestas tristique nibh. Sed a libero. Cras 
varius. Donec vitae orci sed dolor rutrum auctor. Fusce egestas elit eget lorem. 
Suspendisse nisl elit, rhoncus eget, elementum ac, condimentum eget, diam. 
Nam at tortor in tellus interdum sagittis. Aliquam lobortis. Donec orci lectus, aliquam 
ut, faucibus non, euismod id, nulla. Curabitur blandit mollis lacus. Nam adipiscing. 
Vestibulum eu odio. Vivamus laoreet. Nullam tincidunt adipiscing enim. Phasellus 
tempus. Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, 
a accumsan nisi mauris ac eros. Fusce neque. Suspendisse faucibus, nunc et 
pellentesque egestas, lacus ante convallis tellus, vitae iaculis lacus elit id tortor.
```
- Rotate to vertical orientation.

Actual result: Top of the text view grows beyond collection view bounds. 

---

**Case 2:**

Steps to reproduce:
- Switch to vertical orientation in iPhone.
- Paste some long text into text view.
- Switch to horizontal orientation.

Actual result: Text view height shrinks to (almost?) one-line height.

**Comment by panyaspy** [comment]
anyone fix this ?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
