### ISSUE TITLE
Navigation Controller Bug

### ISSUE THREAD

**Issue by Shanlon** [jessesquires/JSQMessagesViewController#806]
When a user is on the application and they go to swipe back to the previous controller the text field will disappear and not show until the user leaves the room. Keyboard will still show but without the textfield.

EX.

User will be chatting decide they want to swipe back to the home page, they go to swipe but then decide to stay, and they have the keyboard open. They keyboard is still shown without the textfield. If a user changes there keyboard type the textfield will again appear.

Tried incorporating swipe methods, did editing etc etc, and nothing seems to work.

**Comment by jessesquires** [comment]
Please provide:

1. library version
2. xcode version
3. ios version
4. devices / simulators

**Comment by Shanlon** [comment]
1. Current Version
2. Current Version
3. iOS 8.1
4. All Devices and Simulators

You can test what I am talking about right in my app, I attached photos below to show whats happening.

![image1](https://cloud.githubusercontent.com/assets/6601267/6406324/1f169ce6-bdfd-11e4-82d5-4dbe96237039.PNG)
![image2](https://cloud.githubusercontent.com/assets/6601267/6406325/21cf35c4-bdfd-11e4-9f31-163655d84e53.PNG)

**Comment by jessesquires** [comment]
I can't reproduce this on the current pod, or on `develop`.

**Comment by Shanlon** [comment]
How can I tell which version I have, I put installed it around January 12th.

I've tried just about everything to get this bug fixed. 

I am not calling end editing, or anything to make this happen.

**Comment by Shanlon** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6601267/6407521/cc985622-be0f-11e4-81a8-1e1a49e50ae9.gif)

**Comment by jessesquires** [comment]
@Shanlon - run `pod update` or download the latest from GitHub

**Comment by Shanlon** [comment]
@jessesquires - So I installed the new version of the framework and still was getting that bug.... Still scratching my head as to why. But I was able to find a solid fix for it, which works really nice. If you would like I can post what I did tomorrow.

**Comment by jessesquires** [comment]
:+1:

**Comment by Shanlon** [comment]
So what ended up being the fix is moving when it removes the keyboard from the self.keyboardController from the superview. 

I removed it from the switch case and simply put it in the viewWillAppear since that gets called every time the user starts to swipe back then decides to stay on there current page. Here is what I did to get this to work.

Moved this
![snip20150228_3](https://cloud.githubusercontent.com/assets/6601267/6424978/ad84e482-bedf-11e4-86be-f8fbe1c593e9.png)

To here
![snip20150228_2](https://cloud.githubusercontent.com/assets/6601267/6424977/ab842260-bedf-11e4-9444-0b94abc4201a.png)

Also, I had another bug where if the user started to type in something then delete all of the text then swipe down, the keyboard would then stay being edited. Which would then not allow the user to swipe the keyboard back up or see the keyboard if they try to click into the text view. Here was my fix for that:

![snip20150228_5](https://cloud.githubusercontent.com/assets/6601267/6424980/fdc5e3ce-bedf-11e4-9c33-fea016fe73eb.png)


Thanks!

**Comment by batnom** [comment]
I had this problem after a modal view got popped then closed, tapping the input would bring up the keyboard but the input bar wouldn't shift up above it.

I had to add this in my viewWillAppear: 

`[self.keyboardController beginListeningForKeyboard];`

And now it shifts up every time.
