### ISSUE TITLE
Compile fail with Xcode63-Beta1

### ISSUE THREAD

**Issue by niklassaers** [jessesquires/JSQMessagesViewController#807]
Hi,
I've added JSQMessageViewController via CocoaPods, but Xcode63-Beta1 seems upset about

@property (readonly, nonatomic) JSQMessagesCollectionView *collectionView;

in JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.h - it doesn't seem to care about the redefinition. In particular, it complains about the following: 

"Bitcast requires types of same width\n  %.asSubstituted = bitcast i64 %1161 to i128, !dbg !1022"

I get this error when compiling with Xcode63-Beta1:

"{
  "kind": "finished",
  "name": "compile",
  "pid": 40410,
  "output": "\u001B[1m\/Users\/niklas\/projects\/TestApp\/TestApp\/TestApp-Bridging-Header.h:14:9: \u001B[0;1;30mnote: \u001B[0m\u001B[1min file included from \/Users\/niklas\/projects\/TestApp\/TestApp\/TestApp-Bridging-Header.h:14:\n\u001B[0m#import <JSQMessagesViewController\/JSQMessages.h>\n\u001B[0;1;32m        ^\n\u001B[0m\u001B[1m\/Users\/niklas\/projects\/TestApp\/Pods\/Headers\/Public\/JSQMessagesViewController\/JSQMessages.h:22:9: \u001B[0;1;30mnote: \u001B[0m\u001B[1min file included from \/Users\/niklas\/projects\/TestApp\/Pods\/Headers\/Public\/JSQMessagesViewController\/JSQMessages.h:22:\n\u001B[0m#import \"JSQMessagesViewController.h\"\n\u001B[0;1;32m        ^\n\u001B[0m\u001B[1m\/Users\/niklas\/projects\/TestApp\/Pods\/Headers\/Public\/JSQMessagesViewController\/JSQMessagesViewController.h:21:9: \u001B[0;1;30mnote: \u001B[0m\u001B[1min file included from \/Users\/niklas\/projects\/TestApp\/Pods\/Headers\/Public\/JSQMessagesViewController\/JSQMessagesViewController.h:21:\n\u001B[0m#import \"JSQMessagesCollectionView.h\"\n\u001B[0;1;32m        ^\n\u001B[0m\u001B[1m\/Users\/niklas\/projects\/TestApp\/Pods\/Headers\/Public\/JSQMessagesViewController\/JSQMessagesCollectionView.h:21:9: \u001B[0;1;30mnote: \u001B[0m\u001B[1min file included from \/Users\/niklas\/projects\/TestApp\/Pods\/Headers\/Public\/JSQMessagesViewController\/JSQMessagesCollectionView.h:21:\n\u001B[0m#import \"JSQMessagesCollectionViewFlowLayout.h\"\n\u001B[0;1;32m        ^\n\u001B[0m\u001B[1m\/Users\/niklas\/projects\/TestApp\/Pods\/Headers\/Public\/JSQMessagesViewController\/JSQMessagesCollectionViewFlowLayout.h:59:60: \u001B[0;1;35mwarning: \u001B[0m\u001B[1mproperty type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'\n\u001B[0m@property (readonly, nonatomic) JSQMessagesCollectionView *collectionView;\n\u001B[0;1;32m                                                           ^\n\u001B[0m\u001B[1m\/Applications\/Xcode63-Beta1.app\/Contents\/Developer\/Platforms\/iPhoneSimulator.platform\/Developer\/SDKs\/iPhoneSimulator8.3.sdk\/System\/Library\/Frameworks\/UIKit.framework\/Headers\/UICollectionViewLayout.h:87:51: \u001B[0;1;30mnote: \u001B[0m\u001B[1mproperty declared here\n\u001B[0m@property (nonatomic, readonly) UICollectionView *collectionView;\n\u001B[0;1;32m                                                  ^\n\u001B[0mBitcast requires types of same width\n  %.asSubstituted = bitcast i64 %1161 to i128, !dbg !1022\nLLVM ERROR: Broken function found, compilation aborted!\n",
  "exit-status": 1
}"

**Comment by jessesquires** [comment]
which version of cocoapods?

which version of the library?

are you using swift?

also -- this looks like a compiler bug/crash. consider submitting here: https://github.com/practicalswift/swift-compiler-crashes

**Comment by niklassaers** [comment]
Thanks for the link. Yes, it was with Swift. I have uncovered that it was, as you suspected, a problem with the compiler. When I took out a totally unrelated class, the issue went away.
