### ISSUE TITLE
[iOS 7.1] [iPhone 4] White screen when having long messages

### ISSUE THREAD

**Issue by oanaBan** [jessesquires/JSQMessagesViewController#808]
Cells with long text are loading very very slow when scrolling. Please see the attached screen

![img_0025](https://cloud.githubusercontent.com/assets/7047087/6288976/a9eb7e9a-b925-11e4-8f4d-92f22bd9e38b.PNG)

**Comment by jessesquires** [comment]
No longer supporting iOS 7. Closing this out. 😄
