### ISSUE TITLE
Feature request - multiple attachments & complex messages

### ISSUE THREAD

**Issue by iNiKe** [jessesquires/JSQMessagesViewController#809]
It will be great to support multiple message attachments in one message and also text message and attachments.
Maybe i'll try to implement this...
Just something like this:
![img_3383](https://cloud.githubusercontent.com/assets/1294902/6309593/fffbc09e-b95f-11e4-9a43-4e7781a4e4d2.PNG)

**Comment by jessesquires** [comment]
@iNiKe - Thanks!

Actually, this *could* be achieved within the current architecture by using a custom `MediaItem`, but it would be quite a bit of work.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by iNiKe** [comment]
Sad news man!
