### ISSUE TITLE
Easier way to handle custom menu actions

### ISSUE THREAD

**Issue by sebastianludwig** [jessesquires/JSQMessagesViewController#810]
Hi,

I've tried to add a _Delete_ action to the cell menu. I read #393 #483 and #569. As suggested I added a category on `JSQMessagesCollectionViewCell` to implement `delete:` and in the collection view delegate return `YES` for `@selector(delete:)` in `collectionView:canPerformAction:forItemAtIndexPath:withSender:`. 

But `collectionView:performAction:forItemAtIndexPath:withSender:` is only called for actions like `copy:` or `cut:`. A look at the disassembly revealed that the the cell holds an internal reference to the collection view and dispatches the messages to the delegate this way.

This is difficult to achieve with JSQ because the only way to add references through categories is using associated objects or subclassing which brings it's own problems and seems overkill.

I think it'd be cleanest to extend the `JSQMessagesCollectionViewCellDelegate` with a method `messagesCollectionViewCell:performAction:withSender:` (maybe optional). This would make it easy and straight forward to implement custom actions and perform the actual task where it belongs (not in the cell).

The only way to make it even easier would be to add an accessible reference to the collection view and dispatch to the `UICollectionViewDelegate` all the time (like Apple does).

What do you think? If you agree I'm happy to implement it and send a pull request.

**Comment by jessesquires** [comment]
Thanks @sebastianludwig :+1: I agree, the API around this is clunky and makes me :cry: 

Your suggestion sounds great — I'd love to see it. 

I hate `@optional` protocol methods, so if it's possible to avoid it then that would be even better.

**Comment by galambalazs** [comment]
+1,  I have to check this out. The new versions of JSQ, while awesome overall, made custom message actions a nightmare.

**Comment by jessesquires** [comment]
@galambalazs - PR #811 adds this functionality and I'm planning on merging it for the next release.

**Comment by galambalazs** [comment]
@jessesquires Wow, awesome man. Thanks :)

**Comment by galambalazs** [comment]
4000 stars to celebrate 7.0.0
nice :+1:

**Comment by basawarajh-cuelogic** [comment]
Hi,
How to handle delete action in JSQMessageController, I have implemented method 
override func collectionView(collectionView: JSQMessagesCollectionView!, didDeleteMessageAtIndexPath indexPath: NSIndexPath!) {
                
        self.collectionView?.deleteItemsAtIndexPaths([indexPath])
        
    }
Also override method 

override func collectionView(collectionView: UICollectionView, shouldShowMenuForItemAtIndexPath indexPath: NSIndexPath) -> Bool {
        // Do the custom JSQM stuff
        super.collectionView(collectionView, shouldShowMenuForItemAtIndexPath: indexPath)
        // And return true for all message types (we don't want the long press menu disabled for any message types)
        return true
    }
    
    override func collectionView(collectionView: UICollectionView, canPerformAction action: Selector, forItemAtIndexPath indexPath: NSIndexPath, withSender sender: AnyObject?) -> Bool {
        super.collectionView(collectionView, canPerformAction: action, forItemAtIndexPath: indexPath, withSender: sender)
        return true
    }
    
    override func collectionView(collectionView: UICollectionView, performAction action: Selector, forItemAtIndexPath indexPath: NSIndexPath, withSender sender: AnyObject?) {
        super.collectionView(collectionView, performAction: action, forItemAtIndexPath: indexPath, withSender: sender)
    }

but i get crash on menu item what else to be done to work, any help would be appreciated, thanks in advance.

**Comment by sebastianludwig** [comment]
What does the exception message say? Where and when exactly does the app crash?
