### ISSUE TITLE
[Question/Help] Usage with NSFetchedResultController and delegate

### ISSUE THREAD

**Issue by BillCarsonFr** [jessesquires/JSQMessagesViewController#812]
Hi,

I just have some questions, need some help, regarding the usage of JSQMessagesViewController with core data.
I am using core data in a very standard way, on viewWillAppear I fetch the results (list of messages ordered by date), call reloadData and then i set up the fecthedResultControllerDelegate.
On disappear, i remove the delegate (that's why i call a fecth + reload on show).

So based on this, all my updates on the table are now done on the delegate code, in case of insertion I just call insertItemsAtIndexPath (inside a perform batch update) :

     if(type == NSFetchedResultsChangeType.Insert) {
       newMessageHasBeenInserted = true
       self.collectionView!.insertItemsAtIndexPaths([newIndexPath!])
     } 

and for updates (in case of message delivery status change) i call reloadItemsAtIndexPaths(...)

Since then i never call again reloadData() on the collection view.
My question is about the following calls:

    - (void)finishSendingMessageAnimated:(BOOL)animated 
    - (void)finishReceivingMessageAnimated:(BOOL)animated 

I have noticed that they are calling 'self.collectionView reloadData()', that i don't need to call when i am using the FecthedResultController delegate, but still they are doing things that i need to do (like reseting the inputToolBar).

So my questions are:

1) Is it really an issue to call finishSendingMessageAnimated() anyway? i mean worst case, reload Data is reloading only the visible message? But can it have side effect on cell insertion animations?

2)  I am thinking of creating my custom finishSendingMessage that is not doing anything regarding data. So basically commenting out this:

        /*[self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
    [self.collectionView reloadData];
    
    if (self.automaticallyScrollsToMostRecentMessage) {
        [self scrollToBottomAnimated:animated];
    }  */

Do you foresee any issue if doing this? (i am not familiar with what invalidate layout is doing)

Also i noticed that the 'scrollToBottom'  was not working on viewWillAppear() for my use case. It's because the super.viewWillAppear() was called before i fetched the results. So i just had to do my stuff first and then call super:

    override func viewWillAppear(animated: Bool) {  
       // mystuffs : lazy init the fecthedResultController and call feth...
      
       //then call super
        super.viewWillAppear(animated)
    }

Usually i call super first, do think this might be a issue? or should i just do another dispatchAsync to scroll to bottom after my code instead of moving the call to super?

Thx for your patience if you read all that ;)

Also i'll be glad, to contribute by providing a swift sample with core data (or maybe there are already tons of, in this case please let me know).

**Comment by mohpor** [comment]
I've successfully implemented what you're trying to do. So,
1- Yes, reloading table view will interrupt insertion animation and discards it immediately
2- I haven't faced any issues regarding layout after removing all reloads from collection view.

one point of warning though, if you're going to receive a few commands too fats (insert and update on the same index path simultaneously) your animation will be cut short, so, either queue them or never mind them.

**Comment by BillCarsonFr** [comment]
Thx mohpr.
I did like that, so far i have no issue. I will continue and stress it a bit. I also need to do more test for 'fast/simultaneuous' modifications, thx for the warning

**Comment by jessesquires** [comment]
Hey guys -- I just (almost) finished a new framework for this. https://github.com/jessesquires/JSQDataSourcesKit

This handles all of the boiler plate around dataSource objects in a type-safe way. It also provides dataSource and delegate objects for `NSFetchedResultsController`. 

Check it out. There are some refinements to make, but everything is currently working. I'll be tagging a release soon.

**Comment by BillCarsonFr** [comment]
Hi Jesse, thanks for the link.
I have implemented something very similar for dataSources in my code, it makes lot more sense to do it like this. I will definitely look to move to JSQDataSourcesKit, it is way more complete and clean than my stuff.
I like the cellFactory pattern, it's clearly out of the datasource provider concerns to configure the cells.

Currently i am working on collection views with several datasource (each section is a different fetchedResultController). I don't know how common or not this usage is, but i think that it could be a candidate to be part of JSQDataSourceKit, a kind of 'CompositeDataSource'. I hope that i will soon be able to have a more complete look on your Kit.

Thx.

**Comment by nachkar** [comment]
@BillCarsonFr Do you have the code in objective c ??
