### ISSUE TITLE
Messages are clipped

### ISSUE THREAD

**Issue by igormatyushkin014** [jessesquires/JSQMessagesViewController#814]
I encountered strange layout of text within cells. All messages are clipped by length of the first message. What am I doing wrong?

Example of normal length
========

![img_0069](https://cloud.githubusercontent.com/assets/8403399/6331480/6c9d960a-bb90-11e4-86b1-d0e067ce01a1.PNG)

Example of clipped length
========

The second message actually contains `Hello`, but it has been displayed as `Hell`

![img_0070](https://cloud.githubusercontent.com/assets/8403399/6331482/6eb3e494-bb90-11e4-8650-6309c144a488.PNG)

**Comment by anilanar** [comment]
Must be something about reusing cells but not resizing them when text changes.

**Comment by jessesquires** [comment]
Sounds like you haven't implemented `hash`, or overridden it improperly.

See #631
