### ISSUE TITLE
[Springiness] Bubbles spring when device put in motion

### ISSUE THREAD

**Issue by vani2** [jessesquires/JSQMessagesViewController#815]
I got strange bug only on some devices, can't say exact steps to reproduce now. 
Look at http://youtu.be/x_bGb6Z8OiM

**Comment by jessesquires** [comment]
Thanks @vani2 !

**Comment by scottj425** [comment]
same issue on iOS 8.2 iPhone 6

**Comment by samwarfield** [comment]
Same issue including during device rotation... iOS 8.2 iPhone 6+

**Comment by jessesquires** [comment]
Thanks to all for the reports!

This is somewhat low priority. Any help is appreciated!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
