### ISSUE TITLE
Method 'hash()' overrides Objective-C method 'hash' from superclass 'NSOjbect'

### ISSUE THREAD

**Issue by attheodo** [jessesquires/JSQMessagesViewController#816]
Hello, just upgraded to latest XCode (6.3 beta 2) and it appears that they brought back the `hash` method to `NSObject`. As a result the app won't compile because the `JSQMessageData` requires the implementation of this method that has the same name.

Any workarounds?

**Comment by jessesquires** [comment]
hey @attheodo - `hash` never went away. You probably just need an `override`. I'm assuming you're using Swift?

**Comment by attheodo** [comment]
I am not really sure what happened, it worked properly before today that I updated to latest XCode. This is what used to work fine:

`
func hash() -> UInt {
        return UInt(self._uuid.hash) ^ Int(self._timetoken)
    }
`

Adding 'override' creates a complaint that `Method does not override any method from its superclass` which kind of makes sense because in the docs `hash` is a computed property (https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSObject_Protocol/index.html#//apple_ref/occ/intfm/NSObject/hash)

Any suggestions?

**Comment by attheodo** [comment]
@jessesquires yes I am on Swift 1.2... any workarounds this issue?

**Comment by attheodo** [comment]
Looks like a Swift bug to me.. :(

**Comment by attheodo** [comment]
Actually it's not a Swift bug, the made some new changes in the way Swift allows overloading/overriding. Please check http://stackoverflow.com/questions/28718577/issue-with-conforming-to-objective-c-protocol-from-swift-nsobject-subclass/28718947?noredirect=1#comment45724845_28718947

I don't see any way this could be worked around, other than changing `hash` method name in the `JSQMessageData` protocol to something else. 

What do you suggest? This totally breaks our build and I am suspecting that because I commented out the `hash` requirement from the protocol I am also getting the errors mentioned in #819

**Comment by jessesquires** [comment]
Hey @attheodo - yes, the `hash` method is a known issue. #684

**Comment by attheodo** [comment]
Do you have an ETA for a fix?

**Comment by attheodo** [comment]
@jessesquires I can see this is scheduled for the `7.0.0` milestone. Can you give me quick directions on where the `hash` method needs to be renamed apart from the protocol?

**Comment by jessesquires** [comment]
@attheodo - I'm probably going to push out 7.0 sooner rather than later to get this fixed.

(and the 6.x milestones will become 7.x)
