### ISSUE TITLE
reloading mediaView item removes image

### ISSUE THREAD

**Issue by ghazel** [jessesquires/JSQMessagesViewController#818]
When reloading a mediaView, often the image disappears. Reloading it again makes the image re-appear.

Easily reproducible in the demo if you add `[self.collectionView reloadItemsAtIndexPaths:@[indexPath]];` to any of the tap handlers, and give it a few taps.

This seems to be related to the return statement here:

```objc
- (void)setMediaView:(UIView *)mediaView
{
    if ([_mediaView isEqual:mediaView]) {
        return;
    }
   
    ... 
```

Commenting it out makes the bug go away.

**Comment by wdcurry** [comment]
and what happens elsewhere if this is commented out?

**Comment by ghazel** [comment]
I don't see any other side-effects. I believe it was just a speculative optimization.

**Comment by jessesquires** [comment]
@ghazel - that's correct
