### ISSUE TITLE
How to access Image from messageItem Media property

### ISSUE THREAD

**Issue by ryderjack** [jessesquires/JSQMessagesViewController#820]
Hi,

Basically I'm adding in the ability to tap an image that's been sent and then view it full screen. I'm accessing the messageItem and getting the media property but unsure as to how to turn this into a UIImage?

Thanks

**Comment by jessesquires** [comment]
````objective-c
JSQMessage *message = /* a message */;

if (message.isMediaMessage) {
    id<JSQMessageMediaData> mediaItem = message.media;

    if ([mediaItem isKindOfClass:[JSQPhotoMediaItem class]]) {
        JSQPhotoMediaItem *photoItem = (JSQPhotoMediaItem *)mediaItem;
        UIImage *image = photoItem.image;
        // use image
    }
}

````

**Comment by ryderjack** [comment]
Awesome, big help. Cheers!

**Comment by jessesquires** [comment]
:+1: 

@ryderjack -- other items would follow similarly

**Comment by Isuru-Nanayakkara** [comment]
@jessesquires I'm trying to do the same in Swift.

```swift
let message = messages[indexPath.item]
if message.isMediaMessage {
    let media = message.media
    if media is JSQPhotoMediaItem {
        if let photoItem = media as? JSQPhotoMediaItem {
            let image = photoItem.image
            print(image)
        }
    }
}
```

But the `image` is nil even for photo media items. Has anything changed in the library architecture since the original answer was posted?

**Comment by thongtran715** [comment]
Hello Guys 
How do I tap on the image on the jsqmessagecontroller to see the whole image? 
Thanks

**Comment by dilipiOSDeveloper** [comment]
Some one looking from getting image when tapped and showing on full screen can use below code i have tested in working project 



override func collectionView(_ collectionView: JSQMessagesCollectionView, didTapMessageBubbleAt indexPath: IndexPath) {
          let message: JSQMessage? = messages[indexPath.row]
          if message?.isMediaMessage != nil {
              let mediaItem: JSQMessageMediaData? = message?.media
               if (mediaItem is JSQPhotoMediaItem) {
                   print("Tapped photo message bubble!")
                   let photoItem = mediaItem as? JSQPhotoMediaItem
                let newImageView = UIImageView(image: photoItem?.image)
                newImageView.frame = UIScreen.main.bounds
                newImageView.backgroundColor = .gray
                newImageView.contentMode = .scaleAspectFit
                newImageView.isUserInteractionEnabled = true
                let tap = UITapGestureRecognizer(target: self, action: #selector(dismissFullscreenImage))
                newImageView.addGestureRecognizer(tap)
                self.view.addSubview(newImageView)
                self.tabBarController?.tabBar.isHidden = true
                
            }
        }
    }

    func dismissFullscreenImage(_ sender: UITapGestureRecognizer) {
        
        self.tabBarController?.tabBar.isHidden = false
        sender.view?.removeFromSuperview()
    }
