### ISSUE TITLE
I'm getting error in JSQMessagesAvatarImageFactory.m Invalid parameter not satisfying: image != nil' error

### ISSUE THREAD

**Issue by mkaya93** [jessesquires/JSQMessagesViewController#821]
/Pods/JSQMessagesViewController/JSQMessagesViewController/Factories/JSQMessagesAvatarImageFactory.m:152
2015-02-26 15:58:41.053 RibbitMessages[6176:1358094] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: image != nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c5fdf35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010c296bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010c5fdd9a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010a1055df -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   RibbitMessages                      0x0000000109747104 +[JSQMessagesAvatarImageFactory jsq_circularImage:withDiamter:highlightedColor:] + 308
	5   RibbitMessages                      0x0000000109745f8f +[JSQMessagesAvatarImageFactory circularAvatarImage:withDiameter:] + 95
	6   RibbitMessages                      0x0000000109745e66 +[JSQMessagesAvatarImageFactory avatarImageWithImage:diameter:] + 86
	7   RibbitMessages                      0x000000010972b6ea -[MessagesViewController viewDidLoad] + 826
	8   UIKit                               0x000000010ab17a90 -[UIViewController loadViewIfRequired] + 738
	9   UIKit                               0x000000010ab17c8e -[UIViewController view] + 27
	10  UIKit                               0x000000010ab3b507 -[UINavigationController _startCustomTransition:] + 633
	11  UIKit                               0x000000010ab473fe -[UINavigationController _startDeferredTransitionIfNeeded:] + 386
	12  UIKit                               0x000000010ab47f47 -[UINavigationController __viewWillLayoutSubviews] + 43
	13  UIKit                               0x000000010ac8d509 -[UILayoutContainerView layoutSubviews] + 202
	14  UIKit                               0x000000010aa6b973 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 521
	15  QuartzCore                          0x000000010a73ede8 -[CALayer layoutSublayers] + 150
	16  QuartzCore                          0x000000010a733a0e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
	17  QuartzCore                          0x000000010a73387e _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	18  QuartzCore                          0x000000010a6a163e _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 242
	19  QuartzCore                          0x000000010a6a274a _ZN2CA11Transaction6commitEv + 390
	20  QuartzCore                          0x000000010a6a2db5 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 89
	21  CoreFoundation                      0x000000010c532dc7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	22  CoreFoundation                      0x000000010c532d20 __CFRunLoopDoObservers + 368
	23  CoreFoundation                      0x000000010c528b53 __CFRunLoopRun + 1123
	24  CoreFoundation                      0x000000010c528486 CFRunLoopRunSpecific + 470
	25  GraphicsServices                    0x000000010d9b79f0 GSEventRunModal + 161
	26  UIKit                               0x000000010a9f2420 UIApplicationMain + 1282
	27  RibbitMessages                      0x00000001097376c3 main + 115
	28  libdyld.dylib                       0x000000010d5da145 start + 1
	29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

So do you know How can I figure out this issue

**Comment by jessesquires** [comment]
yep - don't pass a `nil` image to that method.

**Comment by chlebta** [comment]
I got the same issue, what to return instead of nil ? because in documentation you mentioned to return nil .
```
 /**
     *  Return `nil` here if you do not want avatars.
     *  If you do return `nil`, be sure to do the following in `viewDidLoad`:
     *
     *  self.collectionView.collectionViewLayout.incomingAvatarViewSize = CGSizeZero;
     *  self.collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero;
     *
     *  It is possible to have only outgoing avatars or only incoming avatars, too.
     */
```
