### ISSUE TITLE
customising JSQMessagesLoadEarlierHeaderView button

### ISSUE THREAD

**Issue by ilandbt** [jessesquires/JSQMessagesViewController#826]
Hi,
How can i customise the  JSQMessagesLoadEarlierHeaderView button?
I want to add a  ActivityIndicater when its pressed ,change the height and background color.
I looked at the documentation and i cant figure it out.

Thanks
(i cant figure out how to add a label to this question)

**Comment by vani2** [comment]
I use swift, so for objC almost the same.
1. Copy xib `JSQMessagesLoadEarlierHeaderView.xib` and rename it how you want.
2. Create extension for `JSQMessagesLoadEarlierHeaderView`. Override `nib()` and instantiate your copied xib. Also override `awakeFromNib` for customize.
3. Override `collectionView(collectionView: , layout collectionViewLayout: , referenceSizeForHeaderInSection section: ) -> CGSize` for proper height.

**Comment by jessesquires** [comment]
thanks @vani2 !

**Comment by ilandbt** [comment]
Thanks, 
How do i do this in swift?
I cant override nib()

**Comment by ilandbt** [comment]
and how can i handle the button Pressed action?

**Comment by vani2** [comment]
1. `- (void)collectionView:(JSQMessagesCollectionView *)collectionView header:(JSQMessagesLoadEarlierHeaderView *)headerView didTapLoadEarlierMessagesButton:(UIButton *)sender`
2. What do you mean switch exactly? After you override `nib()` your custom header will be displayed.

**Comment by ilandbt** [comment]
MY CODE: 

import UIKit
class LoadEarlier: JSQMessagesLoadEarlierHeaderView {
    @IBOutlet weak var indicater: UIActivityIndicatorView!
    override func awakeFromNib() {
        super.awakeFromNib()
        
        
    }
    
    override class func nib() -> (UINib?){
        return UINib(nibName: "JSQMessagesLoadEarlierHeaderViewCustom", bundle: nil)
    }
}

and its not showing the new header.

I meant that in a press i want to show the activityIndicator  and hide the button.
can i do this from didTapLoadEarlierMessagesButton?

Thanks,

**Comment by vani2** [comment]
1.I wrote to create **extension**, not subclass.
2. Yes, for sure.

**Comment by ilandbt** [comment]
i'm really sorry but any chance for an example i just cant figure this out.

**Comment by vani2** [comment]
//  MessagesLoadEarlierHeaderView.swift
    extension JSQMessagesLoadEarlierHeaderView {
    
    public override func awakeFromNib() {
        super.awakeFromNib()
        loadButton.setTitle(Localized("Load Previous Messages"), forState: .Normal)
    }
    
    public class func nib() -> UINib! {
        return UINib(nibName: "MyMessagesLoadEarlierHeaderView", bundle: NSBundle.mainBundle())
    }
    
    }

**Comment by chrisscholly** [comment]
![capture d ecran 2016-03-10 a 17 22 02](https://cloud.githubusercontent.com/assets/26509/13676097/b225cd16-e6e4-11e5-8605-84923eaa44af.png)

**Comment by chrisscholly** [comment]
Thanks for answer mate :)
Finally ended up subclassing JSQMessagesFooterView and using registerNib() in JSQMessagesViewController subclass.

**Comment by cboyle** [comment]
@chrisscholly I would love to get an example of how you did this - I've been trying to customize the typing indicator for a bit and am running into the same issue you posted above.

**Comment by SergeyOleynich** [comment]
@cboyle I do next steps
1 - Create Cocoa Touch file subclass JSQMessagesTypingIndicatorFooterView.
2 - In this file override class methods nib and footerReuseIdentifier.
3 - Create xib file and connect it to my file (subclass from JSQMessagesTypingIndicatorFooterView).
4 - In my class (subclass from JSQMessagesViewController) I override 
- (UICollectionReusableView *)collectionView:(JSQMessagesCollectionView *)collectionView
           viewForSupplementaryElementOfKind:(NSString *)kind
                                 atIndexPath:(NSIndexPath *)indexPath
5 - in view did load I wrote such
UINib *cellNib = [UINib nibWithNibName:NSStringFromClass([TypingIndicatorView class]) bundle:nil];
    [self.collectionView registerNib:cellNib forSupplementaryViewOfKind:UICollectionElementKindSectionFooter withReuseIdentifier:NSStringFromClass([TypingIndicatorView class])];

**Comment by chrisscholly** [comment]
thx @SergeyOleynich for answering! I do the same :)

**Comment by FlowBo** [comment]
could someone give an example with Swift 3?

**Comment by mding5692** [comment]
@FlowBo  I used below from stackoverflow:
https://stackoverflow.com/questions/38929586/uicollectionview-footer-in-swift
to stick it onto collectionView

Also copy pasted the xib file manually using terminal and then changed name, then open up in storyboard and changed the identifier there, also override the nib() function in similar fashion as above
