### ISSUE TITLE
JSQMessageVC 6.3.1 raises 7 issues within xCode 6.3 Beta 

### ISSUE THREAD

**Issue by steilerDev** [jessesquires/JSQMessagesViewController#828]
After including JSQMessageVC to my project build with CocoaPods 0.36.0.rc.1 the xCode compiler creates a total of 7 warnings: 

![screen shot 2015-03-03 at 11 05 11](https://cloud.githubusercontent.com/assets/7031616/6460170/319e599e-c195-11e4-981b-eb0a55b2ed05.png)

Not sure if this is just beta noise or something you should consider changing.

_Edit:_ My project is written in SWIFT and I am using the `use_framework!` directive within my PodFile

**Comment by jessesquires** [comment]
Thanks @steilerDev !

I've noticed this too, bug haven't looked into it yet.

**Comment by steilerDev** [comment]
Fair enough. If my knowledge of Obj-C would be better I would be happy to help, but I just started iOS development and really only looked into swift yet.

**Comment by walsh2000** [comment]
````
Auto property synthesis is synthesizing property not explicitly synthesized
````
These warnings are because of a compiler flag.
![screen shot 2015-03-09 at 10 54 40 am](https://cloud.githubusercontent.com/assets/4912283/6560913/bf5ef964-c64a-11e4-93a4-37a6c80c6ac1.png)

Perhaps that is new on by default.

**Comment by jessesquires** [comment]
@walsh2000 - seems to be it. Explicitly using `@synthesize` is no longer necessary.

**Comment by jessesquires** [comment]
Fixed most of these.

**Comment by steilerDev** [comment]
There is still a semantic issues, should I open a new issue?

This is the issues: 

    /Pods/JSQMessagesViewController/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.h:59:60: Property type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'

**Comment by jessesquires** [comment]
hey @steilerDev - yep, I'm aware of this one. it will require some refactoring though, so i'm tracking the remaining issues at #453

**Comment by steilerDev** [comment]
Perfect! Thanks for the great work and support.

**Comment by LeoNatan** [comment]
Adding warning ignores is not a correct solution! The correct solution is to add `@dynamic` to the appropriate properties. Still will not fix your covariant property though, in `JSQMessagesCollectionViewFlowLayout`. Objective C does not support property covariance. You should introduce another property.
