### ISSUE TITLE
textView and bubble padding

### ISSUE THREAD

**Issue by janroures** [jessesquires/JSQMessagesViewController#829]
Hey there, I've noticed a little (bug?) on the message bubble thing. I think there's too much padding between the text content view and the bubble right side itself. I've tried modifying constraints, insets, frames... but anything worked. Do you know how could I change that? Thank you.

kind regards,
Jan

**Comment by jessesquires** [comment]
See the docs on the layout attributes:

http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.3/Classes/JSQMessagesCollectionViewLayoutAttributes.html
