### ISSUE TITLE
How can I display a subview overlay when there are no messages?

### ISSUE THREAD

**Issue by ericgross** [jessesquires/JSQMessagesViewController#830]
I'd like to display a subview with images over the chat contents when there are no messages. I have tried to put a subview there but it must be hidden by the messages view controller because I never see it.

How can I position something on top of the messages view?

**Comment by jessesquires** [comment]
hey @ericgross - you shouldn't have any trouble doing this.

In `viewDidLoad`, something like:

````objective-c
[self.collectionView addSubview:myview];
[self.collectionView bringSubviewToFront:myview];
````
