### ISSUE TITLE
Autolayout warning when change inputToolBar button width

### ISSUE THREAD

**Issue by chienRazzle** [jessesquires/JSQMessagesViewController#834]
Subclass JSQMessageViewController and call this in viewDidLoad: [self.inputToolbar.contentView setLeftBarButtonItemWidth:30.0f];

Here's the warning:

Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fc11aebd110 H:[UIView:0x7fc11ae89140(30)]>",
    "<NSLayoutConstraint:0x7fc11ae23990 UIView:0x7fc11ae89140.leading == UIButton:0x7fc11aecb1f0.leading>",
    "<NSLayoutConstraint:0x7fc11ae239e0 H:[UIButton:0x7fc11aecb1f0]-(0)-|   (Names: '|':UIView:0x7fc11ae89140 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fc11ad28760 h=--& v=--& UIButton:0x7fc11aecb1f0.midX == + 11>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fc11ae23990 UIView:0x7fc11ae89140.leading == UIButton:0x7fc11aecb1f0.leading>

**Comment by jessesquires** [comment]
1. iOS version?
2. Library version?
3. Which devices/simulators?

I believe this has been fixed.

**Comment by chienRazzle** [comment]
Hi @jessesquires, Tested on
1. iOS 8.1
2. Lib 6.1.3
3. iPhone 6 and iPhone 6 simulator
and still give warning in the log

You can easily duplicate the bug by put [self.inputToolbar.contentView setLeftBarButtonItemWidth:30.0f]; in viewDidLoad in Demon project

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
