### ISSUE TITLE
Linker Error after pod install

### ISSUE THREAD

**Issue by thln** [jessesquires/JSQMessagesViewController#835]
Hello, I am trying to run the sweet demo. After running pod install on the project directory, I get a
```
ld: library not found for -lPods-JSQSystemSoundPlayer
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea how I can fix this? I tried looking around in the issue tracker but I haven't found an answer. Thanks.

**Comment by jessesquires** [comment]
are you using opening the `xcworkspace` or the `xcodeproj` ?

after pod install, you'll need to use the workspace.

**Comment by thln** [comment]
My bad, I was trying to open the `xcodeproj`. Opening the `xcworkspace` works. Thank you!
