### ISSUE TITLE
id<JSQMessageData> messageData EXC_BAD_INSTRUCTION problem

### ISSUE THREAD

**Issue by meshachj** [jessesquires/JSQMessagesViewController#836]
I have been trying to run my code with swift and parse but every time i try and initialize the cell, I get a the error at that line in the FlowLayout file. Any thoughts?

**Comment by meshachj** [comment]
Figured it out! :)

**Comment by jessesquires** [comment]
Please share the solution! :smile: others might find it helpful

**Comment by meshachj** [comment]
I was doing an invalid typecasting on my PFObject which kept throwing the error. So I just deleted the typecast and then it worked! :)
