### ISSUE TITLE
Importing JSQMessagesViewController to Project

### ISSUE THREAD

**Issue by schan93** [jessesquires/JSQMessagesViewController#837]
Hi, I'm a bit new to Swift and I am just having some trouble importing this project to my project. I know on the installation it reccomends to use CocoaPods I wanted to see if I could install these files by simply including this folder & JSQSystemSoundPlayer to my project. I dragged both files into my project but can't seem to compile.  I'm getting errors such as:

`Use of undeclared type 'JSQMessagesViewController'` (errors that don't recognize JSQMessagesViewController as a type) and such so I tried to add 

`#import "JSQMessages.h" and
#import "JSQMessageData.h"`

Into my project in the Bridging-Header.h but when I try to run the program, I get issues saying:

`'JSQSystemSoundPlayer/JSQSystemSoundPlayer.h' file not found
#import <JSQSystemSoundPlayer/JSQSystemSoundPlayer.h>`

and my bridging header fails to import properly. Any ideas on how I can fix this? That'd be great! Thanks!

**Comment by webhive** [comment]
Confirm - got the same issuse :+1:

**Comment by najdanovicivan** [comment]
If you haven't installed JSQSystemSoundPlayer via cocoa pods modify the line:

#import <JSQSystemSoundPlayer/JSQSystemSoundPlayer.h> 

to 

#import "JSQSystemSoundPlayer.h"

**Comment by jessesquires** [comment]
thanks for the answer @najdanovicivan !

**Comment by schan93** [comment]
Hi, that fixed most of the errors, thank you so much for the help! I have just one other issue: now I am getting issues such as:

`JSQMessagesBubbleImageFactory.Type does not have member named 'outgoingMessageBubbleImageViewWithColor'`, `Use of unresolved identifier 'JSQMessagesAvatarFactory'`, and `Type 'Message' does not conform to protocol 'JSQMessageData'`. It seems as if my program is recognizing the JSQMessagesViewController as the auto complete seems to be working  but I'm not too sure why the compiler keeps complaining about some of the methods used. I have imported `#import "JSQMessages.h"` and `#import "JSQMessageData.h"` into my bridging header and have made the changes above but am not too sure why I am still getting errors. If anyone could help me that'd be great. Thanks! @najdanovicivan @jessesquires

**Comment by jessesquires** [comment]
>JSQMessagesBubbleImageFactory.Type does not have member named 'outgoingMessageBubbleImageViewWithColor'

````swift
JSQMessagesBubbleImageFactory().outgoingMessageBubbleImageViewWithColor( /* color */)
````

this is an instance method, not a class method.

**Comment by jessesquires** [comment]
>Type 'Message' does not conform to protocol 'JSQMessageData'

Sounds like this bug: #684. 

I'm planning on pushing a fix soon.

**Comment by schan93** [comment]
@jessesquires for the first comment you posted, I made these instance methods but I am still getting errors. I am actually just trying to compile the FireChat for Swift code into my project but I don't seem to be able to get the MessageViewController.swift and Message.swift class to compile correctly for me. Do you have any tips on this? I am able to compile the code in another project, but when I try to add the files into my own project, I get the errors above. Thanks.

**Comment by jessesquires** [comment]
I know that FireChat uses an older version of this library (and maybe an older version of Swift). That might be the issue.

**Comment by BTopbas** [comment]
I have a same issue! I created swift project from zero. I dont know cacoapods and others. I want make messaging app. I created login register users view. Then searching chat ui and found this great ui. Added two folders to my project.(JSQSystemSoundPlayer & JSQMessagesViewController) and created bridge header file.  But first post errors happened.

**Comment by rajaniu** [comment]
i also have the same issue please post some solution

**Comment by einsteincreative** [comment]
Me too!

**Comment by jgschwartz** [comment]
Solution for FireChat:

If you are using FireChat you cannot install using pod, because FireChat uses an older version of JSQ. Instead, open the folder for the sample firechat-swift project. Copy the top-level folders JSQMessagesViewController and JSQSystemSoundPlayer into your project using Finder. Then inside each of those folders, drag the folder with the same name into your project navigator in Xcode. Hope that helps!

**Comment by raghunath44** [comment]
ld: warning: directory not found for option '-F/Users/Armor/Desktop/Coach Admin/System/Library/Frameworks'
ld: framework not found XCTest
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have added JSQMessageViewController folder,JSQSystemSoundPlayer.h and JSQSystemSoundPlayer.m file into my project.
Whats the solution for this?

**Comment by ekramramu** [comment]
I cant import in my project 

# Uncomment this line to define a global platform for your project
 platform :ios, "9.0"
# Uncomment this line if you're using Swift
 use_frameworks!

pod 'Firebase'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'JSQMessagesViewController'

target 'myChatOne' do

end
