### ISSUE TITLE
Why use UICollectionView to implement the message UI,but not UITableView?

### ISSUE THREAD

**Issue by zixun** [jessesquires/JSQMessagesViewController#838]
Why use UICollectionView to implement the message UI,but not UITableView? is UICollectionView batter than UITableView in implement the message UI?

**Comment by jessesquires** [comment]
hey @zixun - collection view is much more powerful and flexible. an old version of this library used tableView.

**Comment by zixun** [comment]
@jessesquires  ths!!can you description it in detail about more powerful and flexible.im interested in it! waiting for you reply~

**Comment by wdcurry** [comment]
If I may, zixun, there is plenty of discussion in past issues about this, and there are many similar chats around the Internet. Jesse et al are not here to teach ;).. In fact, are generously volunteering valuable time ;).. 

Just filter past issues for CollectionView and much will be revealed.

**Comment by jessesquires** [comment]
Here's some good places to start:

http://nshipster.com/uicollectionview/

http://www.objc.io/issue-3/collection-view-layouts.html

http://www.objc.io/issue-12/collectionview-animations.html

http://www.objc.io/issue-5/collection-views-and-uidynamics.html

**Comment by zixun** [comment]
@jessesquires  thank you!!!!!!!!
