### ISSUE TITLE
is JSQMessagesViewController support sound message？

### ISSUE THREAD

**Issue by zixun** [jessesquires/JSQMessagesViewController#839]
is JSQMessagesViewController support sound message？ the demo havn't sound message

**Comment by jessesquires** [comment]
yes. the demo does have sounds.

these sounds don't play in the simulator. this is a bug in Xcode 6.

**Comment by zixun** [comment]
@jessesquires  the demo haven't sound message even if in device~....
can u tell me where the sound message source file place,I haven't find sound message source file in the application

**Comment by jessesquires** [comment]
https://github.com/jessesquires/JSQMessagesViewController/tree/develop/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle/Sounds

**Comment by syrakozz** [comment]
you mean sound in the video, ?  what we meant is the ability to send voice message like whatsapp ? 
is this project contain this feature or there is an easy way to make it

**Comment by kshrikant** [comment]
@syrakozz how u implemented audio message in JSQ ?
