### ISSUE TITLE
Size caching on cell sizes

### ISSUE THREAD

**Issue by raull** [jessesquires/JSQMessagesViewController#842]
@jessesquires I have noticed that the sizes for the cells are getting cached. However, there is times were I want to change the size of the cell and invalidate the layout of the collection view Layout, but the cached sizes disallows this. I know  that the only access to the cache is the limit. Is there a way we could request the deletion of a phoneMessage from the cache by providing the hash?

**Comment by jessesquires** [comment]
Hey @raull - you can do this.

Layout object:

````objective-c
- (void)invalidateLayoutWithContext:(JSQMessagesCollectionViewFlowLayoutInvalidationContext *)context
````

On the [context](http://cocoadocs.org/docsets/JSQMessagesViewController/6.1.3/Classes/JSQMessagesCollectionViewFlowLayoutInvalidationContext.html) that you pass here, set `emptyCache` to `YES`.

**Comment by raull** [comment]
Man that is helpful! Thanks! Big fan of your Pod BTW @jessesquires

**Comment by jessesquires** [comment]
![img](http://media.giphy.com/media/cEYFeDYAEZ974cOS8CY/giphy.gif)

**Comment by qundingchn** [comment]
Hey, i'm new to iOS and i don't understand UICollectionView completely. So , i have tried your suggestion above , here is
     1、init a photoItem and use SDWebImage to download image from imgeUrl
     2、add the photoItem 
     3、after the imge was downloaded , i post a notification to notify JSQMessageViewController 
          to invaliate flowlayout 
       JSQMessagesCollectionViewFlowLayoutInvalidationContext *context =  [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    context.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];

sadly, it does't work . i will take some time to learn UICollectionView but also read JSQMessageViewController carefully , before i find the reason. i appreciate if you can give me some advice . 

Thanks for your time(forgive me my poor english...)
