### ISSUE TITLE
Support Carthage?

### ISSUE THREAD

**Issue by arieljake** [jessesquires/JSQMessagesViewController#843]
Just to see if it works, I added 'github "jessesquires/JSQMessagesViewController"' to my cartfile but the project seems to be ignored as there are no build messages for it.

what would it take to get this project supported by carthage?

**Comment by jessesquires** [comment]
Hey @arieljake, Carthage support will require moving to a `.framework`.

This work is being tracked at #710

**Comment by jessesquires** [comment]
Leaving this issue open as a feature request.

**Comment by arieljake** [comment]
is there work still to be done? maybe i can help

**Comment by jessesquires** [comment]
Thanks @arieljake 

It's going to be quite a big change to switch to a `.framework` so I would prefer to do it.

However, until then, you can create a custom fork and point carthage to that. 

Then, once I support it, you can just update your `cartfile`.

**Comment by hemantasapkota** [comment]
Hi all,

I've made a carthage compatible version of the awesome JSQMessagesViewController which could serve as a temporary fix for those needing carthage support. I'm using it myself for a swift project.
 
Please see https://github.com/hemantasapkota/JSQMessagesViewController

Essentially, it's a separate repo that references JSQMessagesViewController & JSQSystemSoundPlayer as git subtree modules. 

### Usage ###

Add the following to your cartfile and execute ```carthage update```
```
github "hemantasapkota/JSQMessagesViewController" ~> 1.1.0
```

Cheers
Hemanta

**Comment by Iftahh** [comment]
+1   - any update on this?

**Comment by stevenc317** [comment]
Wondering the same thing if there has been any updates on this?

**Comment by geoherna** [comment]
Still wondering if there is carthage support or not?

Adding github "jessesquires/JSQMessagesViewController" to Cartfile but getting Dependency "JSQMessagesViewController" has no shared framework schemes for any of the platforms: iOS

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
