### ISSUE TITLE
trouble with use_frameworks! in cocoapods and swift

### ISSUE THREAD

**Issue by mypark** [jessesquires/JSQMessagesViewController#844]
So the project was working fine until I upgraded to cocoapods 0.36 and set the use_framworks! flag in the podfile so that I could add the AlamoFire swift framework. 

Now I get a whole bunch of undeclared type unresolved identifier errors on JSQMessage classes.  

Here is my podfile:

   platform :ios, '8.0'
   use_frameworks!

   target 'MyApp' do
   pod 'Firebase', '>= 2.1.2'
   pod 'Alamofire', '~> 1.1'
   pod 'JSQMessagesViewController'
   end

   target 'MyAppTests' do
   end

**Comment by jessesquires** [comment]
Thanks @mypark - There are currently some known issues with Swift.

https://github.com/jessesquires/JSQMessagesViewController/labels/swift%20support

I'll be working to resolve these as soon as I can.

**Comment by jessesquires** [comment]
should be fixed in v7.0

**Comment by jessesquires** [comment]
hey @mypark - let me know if v7.0 fixes this for you

**Comment by mypark** [comment]
just tried it and it looks like it works now.

**Comment by jessesquires** [comment]
awesome! :+1:
