### ISSUE TITLE
JSQMessagesComposerTextView always one lined

### ISSUE THREAD

**Issue by mMaxy** [jessesquires/JSQMessagesViewController#846]
Hello, Jesse. I have a strange problem and really don't know where to look for solution.
I'm using your awesome project inside my library, and my problem is that JSQMessagesComposerTextView always shows only one line of text. I've updated to latest on development version and still have the same problem. On demo project everything is ok, but I couldn't find any difference in my usage, that can cause this behaviour. 
Can you help me? Maybe there is any kind of interface, that sets max number of lines on this element?
Thanks in advance.

**Comment by mMaxy** [comment]
As far as I can see, this functionality implemented in JSQMessagesViewController by
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context
But i just tried to debug it and it doesn't stopped there. Will continue investigation.

**Comment by mMaxy** [comment]
Oh, find it. Sorry to bother you, I just implemented on my VC observeVelueForKeyPath:ofObject:change:context and didn't call super class. 
Sorry again :3

**Comment by jessesquires** [comment]
no worries!
