### ISSUE TITLE
JSQMessageBubble Sending/Failure indicator

### ISSUE THREAD

**Issue by najdanovicivan** [jessesquires/JSQMessagesViewController#847]
I use JSQMessages in chat which backend is written using Node.js web socket. When user send a new message I have to wait for socket response that message is sent in order to display it in the collection view. In some cases, when user have low speed network connection, there is a lag measured in seconds between taping the send button and displaying the message to user. If message fails to send via socket I do not display it at all. I want to display message immediately when user taps the send button and have the activity indicator that message is being sent appear. When message is sent the activity indicator should disappear. If sending fails the failure icon should be presented to user in the place of activity indicator. Is there some sort of functionality like this already implemented. If not I was thinking about adding the activity indicators and imageView inside message cell and keeping their pointers in additional dictionary and then update them when I get response from the service. But I don't know how will this perform on cell reuse. Maybe I could use cell bottom label for that functionality. Or even modify the cell to have those indicators.

**Comment by jessesquires** [comment]
hey @najdanovicivan - see #516

you could also possibly use the avatarImageView for this. but, it might be best to start customizing your cells
