### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by BTopbas** [jessesquires/JSQMessagesViewController#848]
Hi;
I added two folders in my project and create header file. No problem with this. But when i try build this error happening.
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JSQMessagesAvatarImage", referenced from:
      __TMaCSo22JSQMessagesAvatarImage in ChatVC.o
  "_OBJC_CLASS_$_JSQMessagesAvatarImageFactory", referenced from:
      __TMaCSo29JSQMessagesAvatarImageFactory in ChatVC.o
  "_OBJC_CLASS_$_JSQMessagesBubbleImage", referenced from:
      __TMaCSo22JSQMessagesBubbleImage in ChatVC.o
  "_OBJC_CLASS_$_JSQMessagesBubbleImageFactory", referenced from:
      __TMaCSo29JSQMessagesBubbleImageFactory in ChatVC.o
  "_OBJC_CLASS_$_JSQMessagesCollectionViewCell", referenced from:
      __TFC16SwiftLoginScreen6ChatVC14collectionViewfS0_FTCSo16UICollectionView22cellForItemAtIndexPathCSo11NSIndexPath_CSo20UICollectionViewCell in ChatVC.o
  "_OBJC_CLASS_$_JSQMessagesViewController", referenced from:
      _OBJC_CLASS_$__TtC16SwiftLoginScreen6ChatVC in ChatVC.o
  "_OBJC_METACLASS_$_JSQMessagesViewController", referenced from:
      _OBJC_METACLASS_$__TtC16SwiftLoginScreen6ChatVC in ChatVC.o
  "_kJSQMessagesCollectionViewCellLabelHeightDefault", referenced from:
      __TFC16SwiftLoginScreen6ChatVC14collectionViewfS0_FTGSQCSo25JSQMessagesCollectionView_6layoutGSQCSo35JSQMessagesCollectionViewFlowLayout_41heightForMessageBubbleTopLabelAtIndexPathGSQCSo11NSIndexPath__V12CoreGraphics7CGFloat in ChatVC.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BTopbas** [comment]
Any advice?

**Comment by schan93** [comment]
Yes, I can confirm that I am having issues with this also as I try to compile my Swift project with the JSQMessageViewController library. Any help would be much appreciated!

**Comment by jessesquires** [comment]
hey @BTopbas - let me know if v7.0 fixes this for you

**Comment by jessesquires** [comment]
Since #844 is resolved, it looks like any issue here is not with the library itself.
