### ISSUE TITLE
AutoLayout in JSQMessagesCollectionViewCellOutgoing

### ISSUE THREAD

**Issue by samcheuk** [jessesquires/JSQMessagesViewController#849]
In `JSQMessagesCollectionViewCellOutgoing.xib`
The `Bubble container` view only trailing space to `Avatar container`
There is layout bug when call something like:

```
[cell.avatarContainerView removeFromSuperview];
```

Should `Bubble container` set trailing space to super view with a low priority?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
