### ISSUE TITLE
Media message bubble customisation 

### ISSUE THREAD

**Issue by federicocappelli** [jessesquires/JSQMessagesViewController#853]
Hi,
I'm trying to customise the bubble image for media messages using:

```
bubbleFactory = [[JSQMessagesBubbleImageFactory alloc] initWithBubbleImage:[UIImage jsq_bubbleRegularStrokedImage] capInsets:UIEdgeInsetsZero];
self.outgoingAttachmentBubbleImageData = [bubbleFactory outgoingMessagesBubbleImageWithColor:mainColor]; <----
self.incomingAttachmentBubbleImageData = [bubbleFactory incomingMessagesBubbleImageWithColor:[UIColor jsq_messageBubbleLightGrayColor]];
```

and in messageBubbleImageDataForItemAtIndexPath:
```
case MessageTypeAttachment:
        {
            if ([message.senderId isEqualToString:self.senderId])
            {
                result = self.outgoingAttachmentBubbleImageData;
            }
            else
            {
                result = self.incomingAttachmentBubbleImageData;
            }
        }
```
my JSQMessageData implementation use this:
```
- (id<JSQMessageMediaData>)media
{
    return [[NMAttachmentMediaItem alloc] initWithMessage:self];
}
```
Everything works well and I can see my media message but without a bubble image, the issue here is that messageBubbleImageDataForItemAtIndexPath: is never called for media messages and i don't know how to customise the bubble.

Any suggestion?

p.s an option is customise the view in "- (UIView *)mediaView" in the JSQMessageMediaData implementation but is harder and I can't use the really useful jsq_bubbleRegularStrokedImage.

**Comment by jessesquires** [comment]
hey @federicocappelli - correct, media views use `- (UIView *)mediaView`, not the bubble views. This is why you are seeing this behavior.

Because `mediaView` is **any** `UIView`, you *can* return the bubble image view.

You may want something more complex, in which case you can an subviews, etc.
