### ISSUE TITLE
Add iad or admob ads on typing area?

### ISSUE THREAD

**Issue by BTopbas** [jessesquires/JSQMessagesViewController#854]
Hi all; 
I wanna add iad or admob banner on the typing area. How can i add this? Sample is here. Any example or any simple usage for this?

![11047201_10206257845308619_1022941789_n](https://cloud.githubusercontent.com/assets/6390054/6599399/3d6547be-c812-11e4-8b31-c06495e4717f.jpg)

**Comment by jessesquires** [comment]
See #798 and #750
