### ISSUE TITLE
Customized NIB-Files

### ISSUE THREAD

**Issue by itinance** [jessesquires/JSQMessagesViewController#855]
Is there an efficient way to use own nib-files for the message incoming and outgoing cells without to fork the project?

I'd look at JSQMessageViewController::jsq_configureMessagesViewController and wished, that it could be overwritten; at least partly where incomingCellIdentifier and outgoingCellIdentifier will be declared.

Or shall i do a pull request?

Thank you very much for any hint.

**Comment by jessesquires** [comment]
Hey @itinance - see #716
