### ISSUE TITLE
Text getting chopped off after a few characters

### ISSUE THREAD

**Issue by machive** [jessesquires/JSQMessagesViewController#856]
Hello,
  Anybody have any idea why all of my text is getting chopped off? Also, if the text includes return characters, only one line of text is shown. Have I missed implementing some methods that will size the bubbles correctly? 

  Great tool, by the way, thanks a lot for putting this out there. 

  Best, 

  Larry

**Comment by jessesquires** [comment]
Hey @machive - can you provide more info?

Are you using a custom font? Sounds like #347

**Comment by machive** [comment]
I can't see how I'm using a custom font as I'm not sure where one specifies the custom font. I have a class that conforms to JSQMessageData and it just returns an NSString for text method. What am I missing?

**Comment by machive** [comment]
Ugh, it's a problem with the hash method which is used to store the size:

 NSValue *cachedSize = [self.messageBubbleCache objectForKey:@(messageItem.hash)];

in the messageBubbleSizeForItemAtIndexPath. 

I changed to hash the message string and now I get multiline text and correctly sized bubbles. I always assumed hash tables implemented a linear search if they hit on the same bucket but something else is going on here. 

I also don't get two different text bubbles I get the same bubble with the tail point right on both sides of the window. I guess I'm missing some other option.

**Comment by jessesquires** [comment]
Second issue sounds like #695
