### ISSUE TITLE
Swit Debugging Issues / failed to get module 'JSQMessagesViewController' from AST context

### ISSUE THREAD

**Issue by BillCarsonFr** [jessesquires/JSQMessagesViewController#861]
Hi,

I wonder if any of you have the same issue than me. I can't use the debugger when i am debugging inside my subclass of JSQMessagesViewController:

    (lldb) po self
    error: Error in auto-import:
    failed to get module 'JSQMessagesViewController' from AST context

Any idea of what can be the issue?

**Comment by jessesquires** [comment]
Hey @BillCarsonFr - how have you installed the library? Cocoapods? Manually?

**Comment by BillCarsonFr** [comment]
Installed with cocoa pod

     0.36.0.beta.2

Bridging header file:

    @import JSQMessagesViewController;

**Comment by jessesquires** [comment]
any issues should be fixed with cocoapods 0.36 (final release is out) and v7.0 of this library. 

i'll be pushing v7.0 today

**Comment by BillCarsonFr** [comment]
Just to say that I upgraded to xcode-6.3 (and also moved to xcode6.3 branch) and i don't have it anymore.
