### ISSUE TITLE
The use of .text as a test of message type is wrong

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#864]
hey Jesse et al.. a simple thought: given we have .isMediaMessage, checking inbound messages against .text is wrong. That field can easily be used for notifications, captions etc for any media message. As is, out-of-the-current-box, if we pass a caption/notif via .text, the msg renders as a text message.

just a minor fyi ;)

**Comment by jessesquires** [comment]
Ahh.. interesting use (abuse? :smile:) of those APIs. 

This wasn't how I intended those methods to be used — that is, you implement either `text` **or** `media`.

In any case, for these situations I would implement your own custom object that implements the `JSQMessageData` protocol. That way, you can override `isMediaMessage` appropriately, the configure your cells how you want.

**Comment by wdcurry** [comment]
A simple change to the isMediaMessage to test against a nil media item would allow us to use the existing property without changes to the existing model. 

One person's mis-use is another's use ;)

**Comment by jessesquires** [comment]
Haha, touche.

Actually... I'm looking through the code now. Where do we check `text` against `nil`? 

`JSQMessage` is initialized with a readonly BOOL. :confused:

**Comment by wdcurry** [comment]
Ah, it was an assumption since I passed a media message through *with* .text set and it simply appeared as a text message through the repo code. 

I remembered peeking at the Bool set weeks ago and figured it had to check against the existence, not nil, for text for this setting.

**Comment by jessesquires** [comment]
Oh I see. The initializers for `JSQMessage` restrict the behavior to what I described above.

Internally, the library only uses `isMediaMessage` to determine the type. So it sounds like what you really need is access to the *full* designated initializer:

````objective-c
- (instancetype)initWithSenderId:(NSString *)senderId
               senderDisplayName:(NSString *)senderDisplayName
                            date:(NSDate *)date
                         isMedia:(BOOL)isMedia
                           media:(id<JSQMessageMediaData>)media
                            text:(NSString *)text
````

However... this is a bit awkward (and breaks some rules that I'm trying to enforce), thus the current set of public initializers. I'll think about this a bit more. 

In the mean time, I think a custom `<JSQMessageData>` object with an initializer similar to the above will do what you need.

**Comment by wdcurry** [comment]
thanks dude.. i'll drop this in. I seem to enjoy breaking things ;) but this will lead more easily to a captioned media message at my end.
