### ISSUE TITLE
Can we modify the Flow layout?

### ISSUE THREAD

**Issue by pavm035** [jessesquires/JSQMessagesViewController#868]
Hi,

I'm building an app where i need to customize the both incoming and outgoing cell, and this i have done by subclassing them from JSQMessagesCollectionViewCell, but in order to satisfy constraints and size calculation i'm thinking to subclass JSQMessagesCollectionViewFlowLayout, but if i subclass it then i should change the custom flow layout in JSQMessagesViewController.xib, so is there any way that we can set our custom layout without modifying the nib?

**Comment by jessesquires** [comment]
hey @pavm035 - you should be able to just set your flow layout subclass.

`self.collectionView.collectionViewLayout = myLayout;`

**Comment by pavm035** [comment]
Thanks you so much i resolved it, BTW fantastic JOB, thumbs up!!!!!

**Comment by rkumawat** [comment]
Hello @pavm035 can you send me your sample for custom JSQMessagesCollectionViewCell and JSQMessagesCollectionViewFlowLayout

**Comment by pabloruan0710** [comment]
Hello @iphoneandroidtesting you have sample for custom JSQMessagesCollectionViewCell?
