### ISSUE TITLE
Input toolbar does not resize

### ISSUE THREAD

**Issue by kartikthapar** [jessesquires/JSQMessagesViewController#869]
I am not sure if this has been posted before but the input toolbar seems to clip text, i.e. does not increase the height of the context view beyond the default height. Also, couldn't reproduce it in the demo app. Here's an image:

![img_0072](https://cloud.githubusercontent.com/assets/810861/6739130/10bc2516-ce4d-11e4-9769-1733a84f5377.png)

**Comment by kartikthapar** [comment]
I just a diff on all the files wondering if I had changed something internally — None.

**Comment by jessesquires** [comment]
are you calling super on view{will/Did}appear?

**Comment by kartikthapar** [comment]
Yes, I have called super on all of this appear/disappear calls. Based on my debugging; I have also seen that the jsq_(add/remove)observer methods are called as well. But the issue is here:

    (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context

The above is not getting called.

**Comment by jessesquires** [comment]
Hm... any typos or other missing calls to super?

**Comment by kartikthapar** [comment]
Commented all view(Did/Will)(Appear/Disappear) calls. Changed the workflow about just to avoid any possible retain cycle that could have been occurred with the previous code. Still it exists. :/

**Comment by kartikthapar** [comment]
Oh good lord! In my JSQMessagesViewController subclass, I was invoking the 'observeValueForKeyPath:ofObject:change:context` method but forgot to call `super` in this one. You were right! Thanks! :X

**Comment by jessesquires** [comment]
haha, no problem :+1:
