### ISSUE TITLE
How to set extra bottom margin from latest bubble to inputToolbar?

### ISSUE THREAD

**Issue by attheodo** [jessesquires/JSQMessagesViewController#874]
In my use-case, I need to fit an extra control between the last bubble in the thread and the input toolbar. At first I was thinking to make it part of the collection view but that doesn't fit my needs after all. 

What's the easiest way I can set some bottom space from the latest chat bubble to the bottom of the collection view?

Thanks

**Comment by jessesquires** [comment]
hey @attheodo - you'll want to edit the collectionView's scroll insets, or the layout's sectionInsets.

**Comment by 10printhello** [comment]
@attheodo Here's how I did it:

self.collectionView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 100, right: 0)
