### ISSUE TITLE
Dynamic Toolbar Preferred Default Height

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#875]
@jessesquires 

I'm trying to implement a feature where the height of the toolbar is determined by some state the JSQMessagesViewController-subclass has.
I find that there is no good opportunity to pass that state to the JSQMessagesInputToolbar subclass before the toolbarHeightConstraint is set in jsq_configureMessagesViewController.

```
- (void)jsq_configureMessagesViewController
{
    self.view.backgroundColor = [UIColor whiteColor];
    self.jsq_isObserving = NO;
//Right here...
    self.toolbarHeightConstraint.constant = self.inputToolbar.preferredDefaultHeight;
```

I can work around this in one of three ways:
1. making toolbarHeightConstraint public,
2. or by making @selector(jsq_configureMessagesViewController) public,
3. or by creating a new entry point that we call from inside jsq_configureMessagesViewController just before setting the toolbarHeightConstraintConstant.

1 & 2 are not ideal solutions.
Perhaps we can break out the lines of code which configure the toolbar into something that subclasses can override, to allow subclasses to do some sort of pre-processing.

Would you be interested in seeing a PR for something like this?

The risk would be low & the net effect to existing clients would be nil.

**Comment by jessesquires** [comment]
Hey @walsh2000 - I'm open to it!

**Comment by walsh2000** [comment]
PR #877 is one way to achieve the desired effect. Low risk. Zero impact to existing consumers.

**Comment by andkon** [comment]
Been thinking about how to solve this too - as well as how to add additional buttons, views, etc. into the toolbar based on a JSQMessagesVC state. Gonna pull #877 and try it out. Have you discovered anything else since you pushed that @walsh2000?

**Comment by gcarlo89** [comment]
@walsh2000 thanks for PR #877 it was very useful

**Comment by walsh2000** [comment]
@gcarlo89 :smiley:

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
