### ISSUE TITLE
Newest bubble not shown when KB is shown

### ISSUE THREAD

**Issue by ericgross** [jessesquires/JSQMessagesViewController#876]
I would expect that when the keyboard is shown, the messages would scroll to the bottom so that you can see the latest ones but when the keyboard is shown there is no scrolling so the latest messages are hidden under the keyboard.

How can I make it scroll down whenever the kb is shown so that the latest messages are not hidden?

**Comment by jessesquires** [comment]
hmm.. sounds like you have something else wrong.

`self.automaticallyScrollsToMostRecentMessage` defaults to `YES`

**Comment by ericgross** [comment]
What are the requirements for this to work? What can I investigate since it's not working?

**Comment by manobal** [comment]
I am also facing the same issue. How did you resolve it?

Thanks

**Comment by ericgross** [comment]
I didn't.
