### ISSUE TITLE
App is crashing with NSFetchedResultController

### ISSUE THREAD

**Issue by pavm035** [jessesquires/JSQMessagesViewController#878]
Hi,

I'm implementing messaging app using this library with NSFetchedResultsController during which i'm inserting sections and rows using [self.collectionView performBatchUpdates:^{}]; but when i insert section for the first time app is crashing due to invalid index path in the following snippet
- (void)prepareForCollectionViewUpdates:(NSArray *)updateItems
{
    [super prepareForCollectionViewUpdates:updateItems];
}

after i investigated this more found that UICollectionViewUpdateItem for section will contain max_integer value for item and valid section index as explained here http://www.raizlabs.com/2013/10/animating_items_uicollectionview/. So during which if we ask delegate for message data app will crash due to invalid index path.

Please look at Item vs. Section Update (IMPORTANT) in the link.

**Comment by jessesquires** [comment]
hey @pavm035 - sounds like there's in issue with your implementation of `performBatchUpdates:`, this can be tricky, but it doesn't sound like an issue with JSQMessages.

**Comment by jcavar** [comment]
Hi, just to let you know that I have same issue. I have tried two solutions and in both same thing happens.
https://github.com/ashfurrow/UICollectionView-NSFetchedResultsController
https://github.com/radianttap/UICollectionView-NSFetchedResultsController

It might be bug in my implementation, but as @pavm035 linked, they explain what is happening in that post.

As a temporary workaround, I did additional check:
            if (attributes.representedElementCategory == UICollectionElementCategoryCell && updateItem.indexPathAfterUpdate.row != NSNotFound) {
                [self jsq_configureMessageCellLayoutAttributes:attributes];
            } 

Not sure if this will have side effects.

**Comment by pavm035** [comment]
Still an issue!!!

**Comment by jstart** [comment]
@pavm035 can you provide an example project demonstrating how this issue is caused by JSQMessagesViewController?  Seems like it is a separate issue.

**Comment by jessesquires** [comment]
Doesn't seem related since the layout checks `if (updateItem.updateAction == UICollectionUpdateActionInsert)`.

If inserting an indexPath, it would not be `NSNotFound`
