### ISSUE TITLE
Sending bubbles display to the left

### ISSUE THREAD

**Issue by meshachj** [jessesquires/JSQMessagesViewController#882]
When I send messages through my app the bubbles that are sent by me are placed on the left also. Do you have any ideas on where I should start to fix the issue?

![img_4098](https://cloud.githubusercontent.com/assets/10481638/6808890/d0967a32-d224-11e4-9a86-01eb867ce158.PNG)

**Comment by jessesquires** [comment]
see #695

**Comment by meshachj** [comment]
![img_4101](https://cloud.githubusercontent.com/assets/10481638/6814390/1f99443a-d24c-11e4-801e-21db6c51defb.PNG)
![img_4101](https://cloud.githubusercontent.com/assets/10481638/6814393/2929e158-d24c-11e4-9483-ea39616401be.PNG)

**Comment by jessesquires** [comment]
hey @meshachj 

>Bubbles are determined to be incoming/outgoing based on the value of `self.senderId` — this should match the `senderId` in your `JSQMessage` objects.

The view controller `self.senderId` is the user sending message (left side). Any `JSQMessage` objects sent by this sender should have the same `senderId` property value.

**Comment by mohonish** [comment]
Is there any way in which we can change this? such that the messages from the user sending messages appear on the right, and all other messages appear on the left?
