### ISSUE TITLE
question on manual scrolling.. 

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#884]
I have a bunch of messages being added via code. All works perfectly. I want to reset view to include the originally topmost message. The code below seems logical to me, but is having no effect. It is placed in my method after everything is done:

                NSArray *visibleIndexPaths = [self.collectionView indexPathsForVisibleItems];
                NSIndexPath *topmostIndexPath = visibleIndexPaths[0];

    {snip .. all the magic happens}

                [self.collectionView scrollToItemAtIndexPath:topmostIndexPath
                                            atScrollPosition:UICollectionViewScrollPositionBottom
                                                    animated:YES];

**Comment by jessesquires** [comment]
Hey @wdcurry - `indexPathsForVisibleItems` does not guarantee that indexPaths are returned in any certain order, so `visibleIndexPaths[0]` is *not* (necessarily) the top most item. You'll need to sort them.

Also, I would recommend using `visibleIndexPaths.firstObject` instead to get bounds-checking for free. Your current snippet would crash if the array is empty.

**Comment by wdcurry** [comment]
Thanks Jesse..  This was only a snippet, so no fear of that crash ;). I'll redo with first object. I was perplexed as I manually set insects each possible one and saw no affect on the view. Perhaps there is trailing action I am missing.
