### ISSUE TITLE
Add pull refresh feature?

### ISSUE THREAD

**Issue by ijinmao** [jessesquires/JSQMessagesViewController#885]

**Comment by jessesquires** [comment]
Hey @ijinmao - this isn't on the roadmap but I'll leave this feature request open for future consideration.

**Comment by wdcurry** [comment]
for what it is worth, in the context of general chat usage, a pull-to-refresh feature doesn't make a ton of sense. Perhaps i am missing the use-case here?

**Comment by eliburke** [comment]
I disagree. Any app that stores chat history could use pull-to-refresh to load old messages. iMessages is a perfect example. 
As for why you wouldn't just load in a ginormous history all at once... Perhaps history is server side? Migrated from another device? Cleared out of the phone's cache? Contains images? Encrypted?

**Comment by harlanhaskins** [comment]
It's not pull-to-"refresh", per se. It's infinite scrolling.

**Comment by jessesquires** [comment]
Good point. Closing this issue as a dupe in favor of #236
