### ISSUE TITLE
NavigationController problem

### ISSUE THREAD

**Issue by seyhunak** [jessesquires/JSQMessagesViewController#892]
I have MessageViewController implemented JSQMessagesViewController, everything working fine, but have two problems.

1. I need to access, MessageViewController's navigation Item "Back" button
2. From the viewcontroller history, I need to set a segue to pass to another controller (TabBarController)

It there any way to do that?

Thanks.

**Comment by jessesquires** [comment]
Hey @seyhunak - sounds like this is a more general question about presenting view controllers. I would recommend asking on StackOverflow
