### ISSUE TITLE
MessageLabelBottomLabel

### ISSUE THREAD

**Issue by Katafalkas** [jessesquires/JSQMessagesViewController#893]
Hey. Are there any plans to introduce:
```
collectionView:layout:heightForMessageBubbleBottomLabelAtIndexPath:
collectionView:attributedTextForMessageBubbleBottomLabelAtIndexPath:
```
? 

I know its not that Message app does not do it - but it would be cool to be able to align label to the bottom of the bubble :)

**Comment by jessesquires** [comment]
hey @Katafalkas - not sure what you're asking

**Comment by Katafalkas** [comment]
i believe i made a bad assumption about TopCell, BotCell and TopBubble attribute labels. I think the problem I am trying to solve is how to get the `messageBubbleContainerView` frame for every cell.
in `collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString!` I am trying to get the cell via `self.collectionView.cellForItemAtIndexPath(indexPath) as! JSQMessagesCollectionViewCell` but it returns nil.  Any ideas ?

**Comment by jessesquires** [comment]
Hm.. still not 100% sure what you're trying to do, but I don't think `cellForItemAtIndexPath` is guaranteed to return a cell. I think it might return `nil` if the cell is off screen.

**Comment by wdcurry** [comment]
I believe what is being asked (and it is early on Sunday so i might be way off) is an assumption that there exists the ability to drop a label onto the bubble of a message itself and not *around* it within the cell. I believe others have been discussing such an overlay. I am also starting to consider this as well.

Again, not minding being totally wrong here ;)
