### ISSUE TITLE
Custom Buttons

### ISSUE THREAD

**Issue by seyhunak** [jessesquires/JSQMessagesViewController#894]
I need to add  "load more" button for jump to archived chat messages.
How can I add custom button top of messages view. Any practical way to do this?

![screen shot 2015-03-30 at 20 02 39](https://cloud.githubusercontent.com/assets/170820/6901703/c58f2f2e-d717-11e4-8e94-1fb8a984b81c.png)

**Comment by jessesquires** [comment]
hey @seyhunak - #311 should help

**Comment by jessesquires** [comment]
also search issues for "top content" or "load earlier messages"
