### ISSUE TITLE
Change bubble corner radius?

### ISSUE THREAD

**Issue by nderkach** [jessesquires/JSQMessagesViewController#896]
Is there a way to change the radius of bubble corners without creating a custom UIImage?

**Comment by jessesquires** [comment]
hey @nderkach - you could return `nil` bubble images, then set the `backgroundColor` and `cornerRadius` on the textView

**Comment by dealaus** [comment]
@jessesquires do you know the corner radius of the provided bubble assets?

**Comment by milesegan** [comment]
@dealaus Looks like it's 17px on the bubble images shipped with the library.
