### ISSUE TITLE
Hide typing indicator with animation

### ISSUE THREAD

**Issue by natanrolnik** [jessesquires/JSQMessagesViewController#898]
Would be nice to have the typing indicator hiding in the same way it's shown: with animation.

I will try to implement this feature - if that's possible - and make a PR. Do you have any idea of the direction I should take?

**Comment by jessesquires** [comment]
Hey @natanrolnik - hm... the collectionView should handle the animations regarding adding/removing cells/supplementary views.

**Comment by natanrolnik** [comment]
That's strange, I'm not able to get the animation. I'll post a gif of the result I'm getting.

**Comment by natanrolnik** [comment]
There we go. The quality of the GIF isn't good enough but you can get see that happening.

![jsq-typingissue](https://cloud.githubusercontent.com/assets/1164565/6941363/ef74e3f8-d887-11e4-85e1-c5710dc65ad6.gif)

**Comment by mzekrallah** [comment]
I agree with @natanrolnik, the typing indicator animation is a bit weird and bulky .. would be great if this could be animated as well ..

**Comment by imton** [comment]
:+1:

**Comment by andrebraga** [comment]
+1

**Comment by ebfio** [comment]
+1

**Comment by ghazel** [comment]
+1

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
