### ISSUE TITLE
Is there a way to hide the toolbar programmatically?

### ISSUE THREAD

**Issue by nikilster** [jessesquires/JSQMessagesViewController#899]
Thanks for this sweet library!  

I'd like to show and hide the toolbar programmatically.  Is there a way to do this?

**Comment by asxasxasx** [comment]
+1 Hide and show.

**Comment by jessesquires** [comment]
````
[self.inputToolbar.contentView.textView becomeFirstResponder];

[self.inputToolbar.contentView.textView resignFirstResponder];
````

**Comment by asxasxasx** [comment]
Is there a way to completely remove inputToolbar and show only messages?

**Comment by fmarcheski** [comment]
+1 on hiding the complete toolbar; showing only messages. Anyone have a solution for this?

**Comment by jessesquires** [comment]
for removing the toolbar see #320
