### ISSUE TITLE
Modifying the bottomLayoutGuide

### ISSUE THREAD

**Issue by nikilster** [jessesquires/JSQMessagesViewController#900]
We're trying to start the content of the messages table view a bit bumped up to show some stuff underneath.  Is there a way to edit the bottomLayoutGuide?  I noticed that it seems to be controlled by toolbarBottomLayoutGuide property.

Thanks in advance for the help!

**Comment by jessesquires** [comment]
hey @nikilster - you can try modifying the collection view insets
