### ISSUE TITLE
Adding a header in the tableview

### ISSUE THREAD

**Issue by nikilster** [jessesquires/JSQMessagesViewController#901]
Another feature we're trying to add to this sweet library (and currently are doing this by forking the repo and modifying it) is a header in the MessagesTableView.  We want to show a bit of data at the top of the messages.

Do you have any suggestions on how to incorporate this with the current codebase - ideally without having to fork / create our own branch?  Thanks!

**Comment by jessesquires** [comment]
hey @nikilster - see #455, #311, and #325
