### ISSUE TITLE
Self.CollectionView setcontentOffset can't reach the bottom .

### ISSUE THREAD

**Issue by vedon** [jessesquires/JSQMessagesViewController#902]
I have set the self.automaticallyScrollsToMostRecentMessage = NO;
and use setcontentOffset in CollectionView, the offsetY is bigger than the collectionView.frame.size.height But it can't work as expect!
the result is :
![screen shot 2015-04-01 at 3 11 41 pm](https://cloud.githubusercontent.com/assets/1811570/6936166/a583a230-d881-11e4-8b82-fe96eea48dee.png)
 
but i want :+1: 
![screen shot 2015-04-01 at 3 12 02 pm](https://cloud.githubusercontent.com/assets/1811570/6936171/ac3d4e14-d881-11e4-96ad-763952e0160c.png)

Any ideas will be helpful!

**Comment by jessesquires** [comment]
hey @vedon - sounds like you have something off. look at the implementation of `scrollToBottomAnimated:`
