### ISSUE TITLE
Input toolbar sometimes does not follow keyboard movements

### ISSUE THREAD

**Issue by erysaj** [jessesquires/JSQMessagesViewController#906]
Sometimes you can notice that input toolbar is not placed perfectly above the keyboard.
I've been able to determine a few scenarios to reproduce (iPad iOS8) this consistently on the demo project, all of them related to undocking keyboard:
* tap input toolbar and then make "flick" gesture on the dismissal button to undock & split keyboard;
keyboard appears with springy animation and toolbar stays at keyboard path's highest point, while keyboard backs a bit
* tap input toolbar, long press dismiss button to select 'Undock' option, drage keyboard up or down,
start typing text; keyboard jumps as if trying to avoid proximity to the input field and ends up either covering toolbar or with a gap between them.

I will submit PR for this soon

**Comment by jessesquires** [comment]
thanks @erysaj !

**Comment by jessesquires** [comment]
Should be fixed by 752fd38aa8b899cbe2e21b6595de58920977bfc2
