### ISSUE TITLE
Show Indicator while Image uploading

### ISSUE THREAD

**Issue by nikunjsilicon** [jessesquires/JSQMessagesViewController#909]
Hi Jesse,

Thanks for wonderful library developed by you!!.

I am using cocoa pods latest version 7.0 and its working fine for me
and I have used PubNub API for send and receive text message, image and video from my app.

I just want to know that how can I show activity Indicator while image or video for show progress of uploading and after finished the uploading progress, I want to show image or video in message screen.

So kindly help me how can I achieve this feature or give me any comment or suggestion?

Thanks for help and appreciate in advance.

**Comment by jessesquires** [comment]
hey @nikunjsilicon - there are example of this in the demo app. send a media message, then tap the `• • •` button in the top left to simulate receiving a message asynchronously

**Comment by nikunjsilicon** [comment]
Thanks for your quick replay Jesse but I have used cocoa pod version 7.0 and just extend JSQMessagesViewController instead of default UIViewController but can't show the above asynchronously icon for send image and video.

Please let me know if any code of line for this.

**Comment by jessesquires** [comment]
ahh, i see. sound's like you'll want to implement your own custom mediaItem for this.

**Comment by nikunjsilicon** [comment]
Thanks Jesse. Ok Can you please let me know where I can implement custom mediaItem?  Do I add code in JSQMediaItem.m and JSQPhotoMediaItem.m correct?

Please let me know so I can go ahead.

Thanks in advance for support.

**Comment by srinathp90** [comment]
@nikunjsilicon Did you implemented image uploading..? Please help me here.

**Comment by nikunjsilicon** [comment]
@srinathp90 sorry, not integrate custom image uploading with indicator like what’s up. But we are sending image to our server and load the url into the message list view. Nothing more.

**Comment by srinathp90** [comment]
@nikunjsilicon  I want to show progress while downloading image.. is it possible?

**Comment by nileshrathod41** [comment]
Hello,
I want to implemented image uploading with  progress or activity Indicator. ?
(https://cloud.githubusercontent.com/assets/11441272/18050071/db5fc266-6e09-11e6-8c3d-111bf09ba79a.png)
