### ISSUE TITLE
Property type "JSQMessagesCollectionView" is incompatible with type "UICollectionView", inherited from "UICollectionViewLayout

### ISSUE THREAD

**Issue by newbie12** [jessesquires/JSQMessagesViewController#911]
Hi there,
When I introduced the files in my code, I had Xcode 6.2, and it worked perfectly. I downloaded Xcode 6.3.4 to use Swift 1.2, but now I have 40 warnings like :

"Property type "JSQMessagesCollectionView" is incompatible with type "UICollectionView", inherited from "UICollectionViewLayout""

Please, what I have to do ?
Thanks a lot

**Comment by jessesquires** [comment]
Thanks @newbie12 

Update to JSQMessages 7.x and see #828 and #453.
