### ISSUE TITLE
Message bubble top label insets hard coded to 60 or 15 points

### ISSUE THREAD

**Issue by Dridus** [jessesquires/JSQMessagesViewController#912]
in JSQMessagesViewController, it decides what insets to use like this:

```objective-c
    CGFloat bubbleTopLabelInset = (avatarImageDataSource != nil) ? 60.0f : 15.0f;

    if (isOutgoingMessage) {
        cell.messageBubbleTopLabel.textInsets = UIEdgeInsetsMake(0.0f, 0.0f, 0.0f, bubbleTopLabelInset);
    }
    else {
        cell.messageBubbleTopLabel.textInsets = UIEdgeInsetsMake(0.0f, bubbleTopLabelInset, 0.0f, 0.0f);
    }
```

but that assumes that the avatar size and text view insets inside the bubble are as expected. I can override this by poking new insets in after the fact, but thought that perhaps the default behavior should honor the avatar size and other metrics.

**Comment by jessesquires** [comment]
Thanks @Dridus !

These values also depend on the bubble images that are used. The goal here was to simply provide some reasonable default values. To customize, you can override `cellForItemAtIndexPath:`.

However, the core of this issue (respecting avatar size) will be addressed by #564

**Comment by eliburke** [comment]
I was going to submit a PR for this very issue, but lo and behold, it's already been discussed.

@jessesquires, #564 seems to be a complex issue that is taking a long time to fix properly. In the meantime, perhaps you would be willing to incorporate a smarter default value for the bubbleTopLabelInset. This lines up the cell top label with the default message bubble style for avatars that are Off or On, whatever size is set. 
```
// CGFloat bubbleTopLabelInset = (avatarImageDataSource != nil) ? 60.0f : 15.0f;
CGFloat bubbleTopLabelInset = 0.0f;
if (needsAvatar) {
    bubbleTopLabelInset = 5.0 + (isOutgoingMessage ? collectionView.collectionViewLayout.incomingAvatarViewSize.width :  collectionView.collectionViewLayout.outgoingAvatarViewSize.width);
}
```

**Comment by jessesquires** [comment]
hey @eliburke - that sounds good :+1: mind submitting a PR? :smile:

**Comment by eliburke** [comment]
Sure, just created #1188 
One thing that bugged me was the hard coded 5 pixel adjustment for the bubble's tail. I started adding the tail width as an optional on the JSQMessageBubbleImageDataSource protocol, but decided that it made more sense as an adjustable property on the JSQMessagesCollectionViewFlowLayout.
If you don't like this part of the commit, I'm willing to relocate it elsewhere.
