### ISSUE TITLE
Incoming JSQLocationMediaItem setting in data model

### ISSUE THREAD

**Issue by HalahSalih** [jessesquires/JSQMessagesViewController#913]
My message model sets the location (incoming messages )in a category of that message model. This category implements JSQMessageData protocol. I understand that setting locations requires reloading the collection view upon completion, but how can I do that while I am setting the location within the category? Any suggestions? 
(currently the when the incoming data has a locations, location cell is loaded but with loading indicator is always on, I have no problem with outgoing message because they take place within the viewControlled and I can easily reload the collection data there. 

This is how am I setting the location in the category:

     -(id<JSQMessageMediaData>) media{
    
       CLLocation *ferryBuildingInSF = [[CLLocation alloc] initWithLatitude:37.795313      longitude:-122.393757];
    
      JSQLocationMediaItem *locationItem = [[JSQLocationMediaItem alloc] init];
      [locationItem setLocation:ferryBuildingInSF withCompletionHandler:nil];
    
     return locationItem;
    
}

I tried setting the incoming location data in **messageDataForItemAtIndexPath** method, and reloading collection view upon completion, but that leads to infinite loop. 

Here are more details about the message model, it has id, type, body and user. The message types are 3: text, date and location. If the type of the message is either text or date, the message is not media message and the data is handled in the text method. If the message type is location, media method mentioned above is called.

**Comment by jessesquires** [comment]
Hey @HalahSalih - the object that sets the location on the model object can have a weak reference to the collection view and reload when necessary.

there are some examples of this in the demo project:

1. send a location message (tap the :paperclip: )
2. then tap the `•••` to simulate receiving a message (this copies the last outgoing message for the new incoming one)

**Comment by itolisto** [comment]
Hi HalahSalih, have you found a solution for this use case? 

I'm trying to do something similar but haven't had success
