### ISSUE TITLE
Use of undeclared type 'JSQMessagesViewController'

### ISSUE THREAD

**Issue by felixchan** [jessesquires/JSQMessagesViewController#916]
Hi,

I installed the framework via ```pod 'JSQMessagesViewController'  ```

I have the bridging headers set up correctly. ```#import <JSQMessagesViewController/JSQMessages.h> ```

When I compile, I receive the error.

```
import UIKit
import Foundation
class MessagesViewController: JSQMessagesViewController {
}
```

I updated to Swift 1.2 yesterday. However, when I tried the Firebase example (I'm guessing it uses 6.0?), it runs fine and everything worked.

Thank you

**Comment by taylorc93** [comment]
+ 1, I'm getting the same issue right now.  The Firebase project manually includes the library instead of using Cocoapods, so maybe the issue lies there somewhere?

**Comment by jessesquires** [comment]
This is how Swift + Cocoapods works.

When using Cocoapods with Swift projects, pods are compiled and linked as frameworks. Thus, they have their own module, thus they must be imported where you want to use them.
