### ISSUE TITLE
JSQMessagesCollectionViewFlowLayout "collectionView" property warning - incompatible property type

### ISSUE THREAD

**Issue by kilolumen** [jessesquires/JSQMessagesViewController#920]

**Comment by banxi1988** [comment]
I also faced this problem,and Which cause a release build failed,
waring message as follows:
```
JSQMessagesViewController/JSQMessagesCollectionViewFlowLayout.h:59:60: warning: property type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'
@property (readonly, nonatomic) JSQMessagesCollectionView *collectionView;
                                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UICollectionViewLayout.h:87:51: note: property declared here
@property (nonatomic, readonly) UICollectionView *collectionView;
```

**Comment by jessesquires** [comment]
Re-opening this issue to track more formally.

As of the 7.0.1 release, this warning is being suppressed via `#pragma clang diagnostic push`.

**Proposed solution:**
Rename property to `messagesCollectionView`. Breaking API change. Set for 8.0 milestone.

See also: #828  and #453

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
