### ISSUE TITLE
Message bubble resizes "randomly"

### ISSUE THREAD

**Issue by Zilounay** [jessesquires/JSQMessagesViewController#923]
Hi.

I'm loading a simple text that is about 3 lines long in a JSQ message bubble, and all is fine, 99% of the time.

I don't know if you've experienced this but sometimes, which happens to be when I relaod the tableview (to show new messages for example), some of the bubbles will layout differently and, for example, have a shorter width and therefore a bigger height to compensate.

All the text is displayed fine, but you can clearly see it if I refresh the view while we're in the view (and the bug triggers, which I don't know when yet).

And my 3-lines message suddenly becomes 4-lines which is visually obvious that something jumped.

Not a kilelr bug but definitly something to look into.

The only information i can provide is that when I get a new message/write one, I simply add it to my messages array and use reloadData, which tends to trigger that bug (and also stretch media images on every visible media cell, which is another  bug I filed last year).

**Comment by jessesquires** [comment]
hey @Zilounay - can you provide and more information? maybe a demo project that shows this?

also:

1. iOS version?
2. library version?
3. devices/simulators?

**Comment by walsh2000** [comment]
@Zilounay 

Perhaps the hashes of your messages are not unique enough and the height cache is using the wrong cached value.

**Comment by jessesquires** [comment]
that sounds about right to me. double check your implementations of `messageHash`
