### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by cecilcosta** [jessesquires/JSQMessagesViewController#925]
I'd like to know if there is a way of customizing the toolbar without changing the original code. I tried to do it inheriting from JSQMessagesInputToolbar and copying the JSQMessagesToolbarContentView.xib file into my project but it is still using the original one.

**Comment by jessesquires** [comment]
hey @cecilcosta - see #750 and #746

**Comment by dequan** [comment]
Hi, I have the same problem, I use Swift. Can you describe in detail ? Thanks!

**Comment by bishalg** [comment]
@dequan : Have you found any example describing in detail how to do it ?

Found one solution in this blog - 
http://www.scriptscoop2.com/t/b2ff94d505e8/ios-how-to-add-a-searchbar-to-jsqmessagesviewcontroller.html

He removes it from superview - 
`self.inputToolbar.removeFromSuperview()`

dont know if that is the proper way of doing this ?
