### ISSUE TITLE
Import error in swift.

### ISSUE THREAD

**Issue by jerry-sjtu** [jessesquires/JSQMessagesViewController#927]
I install the JSQMessagesViewController with the help of cocoapods, here is the content of the  podfile:
    **pod 'JSQMessagesViewController' #chat ui**

I run the command "pod install" and get the output:
   **Installing JSQMessagesViewController (7.0.0)**
   **Installing JSQSystemSoundPlayer (2.0.1)**

Which means that I install the JSQMessagesViewController successfully. I reopen the project and add 
    **#import &lt; JSQMessagesViewController/JSQMessages.h &gt;**
in my bridge file, then I get the error 
     **'JSQMessagesViewController/JSQMessages.h' file not found with <angled> include; use "quotes" instead**
I don't why I get the error when I did as the others.

**Comment by steilerDev** [comment]
Since you are using Swift in your project consider using (`use_frameworks!`)[http://blog.cocoapods.org/CocoaPods-0.36/]. This will convert your pods into dynamic swift libraries that can be imported using `import JSQMessagesViewController`.

This works for me without any problems.

**Comment by jerry-sjtu** [comment]
I add "use_framework!" to my Podfile and then I get the error: 
**no such file or directory:/Pods/Target Support Files/Pods-JSQSystemSoundPlayer/Pods-JSQSystemSoundPlayer-dummy.m**

**Comment by jerry-sjtu** [comment]
I add a detail description in stackoverflow: http://stackoverflow.com/questions/29692448/how-to-import-jsqmessagesviewcontroller-in-swift

**Comment by jessesquires** [comment]
looks like this has been answered on StackOverflow

**Comment by wangshengjia** [comment]
I have also an issue here, but not the same, when I installed with Cocoapods v3.7.2, target on iOS8 and using ```use_frameworks!```. 

In my podfile:
pod 'JSQMessagesViewController'

I run the command "pod install" and get the output:
**Installing JSQMessagesViewController (7.1.0)**
**Installing JSQSystemSoundPlayer (2.0.1)**

Everything seems to be going well until I run the project, I get a build error:

/Pods/JSQMessagesViewController/JSQMessagesViewController/Categories/JSQSystemSoundPlayer+JSQMessages.h:19:9: Include of non-modular header inside framework module 'JSQMessagesViewController.JSQSystemSoundPlayer_JSQMessages'

Any ideas?

**Comment by raghunath44** [comment]
JSQAudioMediaViewAttributes.h file not found error..How to solve ???

**Comment by danieljvdm** [comment]
I'm getting the same problem now randomly. Didn't change anything in my project and all of a sudden getting 

 /Pods/JSQMessagesViewController/JSQMessagesViewController/Categories/JSQSystemSoundPlayer+JSQMessages.h:19:9: 'JSQSystemSoundPlayer/JSQSystemSoundPlayer.h' file not found

**Comment by danieljvdm** [comment]
Fixed by deleting DerivedData
