### ISSUE TITLE
cellBottomLabel and cellTopLabel not showing

### ISSUE THREAD

**Issue by steilerDev** [jessesquires/JSQMessagesViewController#928]
I am trying to display a top and bottom label unfortunately it is not showing up.

Within my `collectionView(_:attributedTextForMessageBubbleTopLabelAtIndexPath:)` I am currently returning a simple `NSAttributedString(string: "Hello", attributes: [NSFontAttributeName: UIFont.systemFontOfSize(12.0)])`. The function is called but the labels are not shown. 

Do I have to prepare anything inside my `viewDidLoad` so I am able to show these labels?

Currently I am only doing the following view adjustments for the chat view:

      inputToolbar.contentView.rightBarButtonItem.setToDefaultColor()
      inputToolbar.contentView.leftBarButtonItem = nil
      collectionView.collectionViewLayout.outgoingAvatarViewSize = CGSizeZero

Thanks for you help!

P.S.: My app is running iOS 8.3 and is written in swift.

**Comment by jessesquires** [comment]
hey @steilerDev - there's another method that corresponds to `collectionView(_:attributedTextForMessageBubbleTopLabelAtIndexPath:)` for the height of the label.

default will be zero. see the demo project for details!

**Comment by jessesquires** [comment]
`collectionView(_:heightForMessageBubbleTopLabelAtIndexPath:)`

**Comment by YannickSteph** [comment]
override func collectionView(collectionView: JSQMessagesCollectionView!, attributedTextForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> NSAttributedString! {
        return NSAttributedString(string: "ok")
    }
    override func collectionView(collectionView: JSQMessagesCollectionView!, layout collectionViewLayout: JSQMessagesCollectionViewFlowLayout!, heightForCellBottomLabelAtIndexPath indexPath: NSIndexPath!) -> CGFloat {
        return 100
    }

Thanks @jessesquires
