### ISSUE TITLE
Error with fetch_result_controller

### ISSUE THREAD

**Issue by Djoz2** [jessesquires/JSQMessagesViewController#929]
Hello i'm trying to use Core data with this great framework you have crated but some staff here are un clear and I couldn't find no place to get help so let me explain.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Message messageHash]: unrecognized selector sent to instance 0x7f93540932d0'
*** First throw call stack:
1]so what is this "message Hash"? 

2] how to set the cell of the collection view to return my Core Data info into all messages .
IN the JSQMessages (DemoModelData ) it's seems like you can only set demo messages I need some one to explain me how to return all the messages array from "fetchedResultsController.fetchedObjects" to the collection view cell without getting the app crash? 

I'm pretty new to Core-Data in general so take it easy with me :+1:  

also see my question that I posted to understand me batter : 

http://stackoverflow.com/questions/29616620/how-to-return-all-messages-from-array?noredirect=1#comment47380272_29616620

**Comment by jessesquires** [comment]
hey @Djoz2 

See the docs and the *Getting Started* section of the README.

1. you need to implement the `messageHash` method in your `Message` class. 
2. in your view controller subclass, you need to override the data source methods to return your objects from the fetched results controller. there are lots of other resources on the web for how to do this.

**Comment by Djoz2** [comment]
Hey @jessesquires  thank you for you're awesome framework and comment. I did what you said and it worked great I now able to send messages but can't see the returned messages. How can I get my returned messages from fetchedResultsController?  I Think it's something wrong with my bubbles data source. Do you have some example of Core-data with this framework btw? And this is my code for the bubbles data source: 


- (id<JSQMessageBubbleImageDataSource>)collectionView:(JSQMessagesCollectionView *)collectionView
             messageBubbleImageDataForItemAtIndexPath:(NSIndexPath *)indexPath
{
   
 for (Message *msg in _fetchedResultsController.fetchedObjects) {
        
        if ([msg.senderId isEqualToString:self.user_id]) {
            
            return bubbleImageOutgoing;
        }
        
    
    
    else return bubbleImageIncoming;
    }
return nil;
}

**Comment by atmacaberke** [comment]
Are you sure that you change your data into JSQMessage format which may like:

JSQMessage *newMessage = [[JSQMessage alloc]
                                      initWithSenderId:[NSString stringWithFormat:@"%@",response[i][@"id"]
                                      senderDisplayName:response[i][@"name"]
                                      date:response[i][@"time"]
                                      text:response[i][@"text"]];
