### ISSUE TITLE
how to implement swipe up to show keyboard

### ISSUE THREAD

**Issue by hermanccw** [jessesquires/JSQMessagesViewController#930]
First of all, great library!

I want to implement something like the FB messenger app where when the user swipe up when latest message in in view, it shows the keyboard.

looking into the code, seems like the best way to do it is to subclass JSQMessagesKeyboardController to do the change there, is that the right way to go?

Herman

**Comment by jessesquires** [comment]
Hey @hermanccw - that would be correct.

But beware, there be dragons.

**Comment by hermanccw** [comment]
@jessesquires heh, care to tell me what kind of dragons?

**Comment by jessesquires** [comment]
lol. just all the APIs around the keyboard are kind of awful.

the fact that the KeyboardController class is necessary to get the behavior we want/need makes me :cry:

**Comment by hermanccw** [comment]
@jessesquires ah... got it.  yeah, keyboard related stuff is way too complicated

**Comment by andkon** [comment]
@hermanccw did you end up solving this? And when you subclass KeyboardController, how are you changing the keyboardController property on JSQMessagesVC?

**Comment by hermanccw** [comment]
@andkon not yet, you probably have to subclass JSQMessageVC as well.
