### ISSUE TITLE
Avatar image factory only works properly with square avatar images

### ISSUE THREAD

**Issue by BillCarsonFr** [jessesquires/JSQMessagesViewController#931]
The Avatar Image Factory is breaking aspect ratio if the original image is not square.
'[image drawInRect:frame]' is scaling the image to fit in a square

What is the recommended way to build avatar circular images from any source?

In 

    + (UIImage *)jsq_circularImage:(UIImage *)image withDiameter:(NSUInteger)diameter highlightedColor:(UIColor *)highlightedColor
    ....

    CGRect frame = CGRectMake(0.0f, 0.0f, diameter, diameter);
    UIImage *newImage = nil;

    UIGraphicsBeginImageContextWithOptions(frame.size, NO, [UIScreen mainScreen].scale);
    {
        CGContextRef context = UIGraphicsGetCurrentContext();
        CGContextSaveGState(context);

        UIBezierPath *imgPath = [UIBezierPath bezierPathWithOvalInRect:frame];
        [imgPath addClip];
        [image drawInRect:frame];

        if (highlightedColor != nil) {
            CGContextSetFillColorWithColor(context, highlightedColor.CGColor);
            CGContextFillEllipseInRect(context, frame);
        }

        newImage = UIGraphicsGetImageFromCurrentImageContext();

        CGContextRestoreGState(context);
    }

    ....

**Comment by jessesquires** [comment]
hey @BillCarsonFr - this is correct. The avatar factory is more of a helper class (along with the other factory classes). 

One of the goals of this library in general is to provide basic functionality and sensible default settings/values for the most common use cases.

In this situation, I feel that any more advanced image processing is beyond the scope of this library.

You have a couple of options here:
1. Handle your own image processing completely, don't use the avatar factory
2. Pass square images to the factory, after doing some minimal processing/cropping

**Comment by BillCarsonFr** [comment]
Thx @jessesquires,
What do you think of the option where a cornerRadius and clipToBounds is applied directly to the cell's avatarImageView?
Will it bring some performance issues? Is it preferable to draw the avatar round as it is done in the factory method?

Thx.

**Comment by jessesquires** [comment]
Hey @BillCarsonFr - that is definitely an option, but I've always felt that those are somewhat hacky solutions to getting a circular view.

I think cornerRadius is good if you want a rounded rectangle, but not a circle.

Also, if your image dimensions are smaller than the imageView, you can end up with weird "half-circle"-looking images. 

With my solution in the library, all image processing happens only once — the image is cached, then you're simply setting it in the imageView.
