### ISSUE TITLE
Issue with TopContentAdditionalInset

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#935]
@jessesquires 

I've run into an issue where I'm setting the TopContentAdditionalInset on viewDidAppear and that causes the chat bubbles to appear shifted down by 64 pixels (height of status bar + height of nav bar)

![screen shot 2015-04-20 at 11 55 07 am](https://cloud.githubusercontent.com/assets/4912283/7240381/62f7fa54-e765-11e4-9804-c029a0457085.png)

On iOS8 this issue only occurs when the view is appearing from having pushed another VC onto the navigation controller (we're popping from the detail vc)
-- Imagine that tapping on an image cell will push the full-res version of the image. When you pop that full-res image, the chat bubbles are all shifted down by 64.

On iOS7, this diff alone will create the 64 pixel shift

```
diff --git a/JSQMessagesViewController/Controllers/JSQMessagesViewController.m b/JSQMessagesViewController/Controllers/JSQMessagesViewController.m
index 36f224c..7d8a09d 100644
--- a/JSQMessagesViewController/Controllers/JSQMessagesViewController.m
+++ b/JSQMessagesViewController/Controllers/JSQMessagesViewController.m
@@ -239,6 +239,8 @@ static void * kJSQMessagesKeyValueObservingContext = &kJSQMessagesKeyValueObserv
     }

     [self jsq_updateKeyboardTriggerPoint];
+    [self setTopContentAdditionalInset:1];
 }
```

The problem appears to be that [self topLayoutGuide] is 0 on the initial viewWillAppear, but after viewDidAppear the topLayoutGuide is 64, so the subsequent viewWillAppear sets the contentInset to 128 (64 for the actual top layout guide, and 64 for the user-requested contentInset which was computed in jsq_updateCollectionViewInsets)

I'm wondering whether we need to include topLayoutGuide in the computation in jsq_updateCollectionViewInsets. Looking back through the commit history I cannot find a time when we were not using topLayoutGuide for the call to jsq_setCollectionViewInsetsTopValue, however take note that on the iOS8.3 simulator it appears to be 0 always (unless you push another VC into the nav controller)

Do you recall why we needed to use self.topLayoutGuide.length here?

**Comment by jessesquires** [comment]
Hey @walsh2000 

`self.topLayoutGuide.length` is needed to properly support translucent/non-translucent nav bars.

**Comment by walsh2000** [comment]
Interesting. I'll look at the value of topLayoutGuide pre-viewDidAppear.

What do you think about that diff causing the attached picture?

**Comment by jessesquires** [comment]
hm... interesting. 

the timing of when `self.topLayoutGuide` has a valid value seems to be the issue, based on what you've described.

to elaborate more, `[self jsq_setCollectionViewInsetsTopValue:self.topLayoutGuide.length ...` is necessary because without it, the messages would be "stuck" underneath the nav bar. the docs on `topLayoutGuide` and `topLayoutGuide.length` should help explain better.

**Comment by jessesquires** [comment]
maybe #455 is related?

**Comment by walsh2000** [comment]
@jessesquires 

Could the bubbles-under-navbar issue be resolved by removing UIRectEdgeTop in the value for edgesForExtendedLayout?

As for #455:
Although he is setting the TopContentAdditionalInset, his NavBar's do not appear to be translucent, so I would expect that the content is not expected to extend under the NavBar by default.
Reading his complaint, it sounds to me like the collection view's size isn't computed correctly. Perhaps there is a significant amount offscreen below (145 pixels perhaps)

Something like:
````
po [[[UIApplication sharedApplication] keyWindow] recursiveDescription]
````
would tell us whether the collection view is entirely onscreen.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
