### ISSUE TITLE
How can I show the message status like seen, deliver?

### ISSUE THREAD

**Issue by kyawmyintthein** [jessesquires/JSQMessagesViewController#936]

**Comment by jessesquires** [comment]
See #891.

Please don't open duplicate issues! :smile:

**Comment by Jeyhey** [comment]
I don't see how this issue is related to #891. I'm also stuck with how showing a status like 'delivered' or 'could not be delivered' below the message bubble. Is there a way to do this?

**Comment by GianniCarlo** [comment]
@Jeyhey @kyawmyintthein you can set your message status in one of the labels of the cell, maybe using `collectionView:attributedTextForCellBottomLabelAtIndexPath:` like so:
```objective-c
-(NSAttributedString *)collectionView:(JSQMessagesCollectionView *)collectionView attributedTextForCellBottomLabelAtIndexPath:(NSIndexPath *)indexPath{
    BLMessage *currentMessage = [self.visibleMessagesArray objectAtIndex:indexPath.item];
    
    //check if outgoing
    if ([self.senderId isEqualToString:currentMessage.senderId]) {
        //status could be: 'sent', 'sending', etc
        return [[NSAttributedString alloc] initWithString:currentMessage.status];
    }
    
    //return nothing for incoming messages
    return nil;
}
```

**Comment by Jeyhey** [comment]
great thanks a lot.

**Comment by mariocarvalho** [comment]
@GianniCarlo JSQMessage doesn't have any property named `status`. How to get or set it?

**Comment by marioacarvalho** [comment]
@GianniCarlo JSQMessage doesn't have any property named `status`. How to get or set it?

**Comment by GianniCarlo** [comment]
@marioacarvalho you can have two approaches to this:

1.- You could add a function in an extension if you're doing it in Swift or in a category of JSQMessage if you're on Objective-C. 
2.- You can have your own class which conforms to the protocol `JSQMessageData` which is the requirement to use it with the collectionView.

Then you can define status however you see fit

Cheers!
