### ISSUE TITLE
JSQMessagesViewController's implementation of the UICollectionViewDelegate calls self instead of collection view.

### ISSUE THREAD

**Issue by bearclough** [jessesquires/JSQMessagesViewController#937]
Line 611 of JSQMessagesViewController is causing a crash when a message is trying to be copied.  The performAction:forItemAtIndexPath: method should call the data source of the collection view argument instead of JSQMessagesViewController's implementation of messageDataForItemAtIndexPath.

This line should be changed to be as follows, pull request to come shortly :)

'id<JSQMessageData> messageData = [collectionView.dataSource collectionView:collectionView messageDataForItemAtIndexPath:indexPath];'

**Comment by jessesquires** [comment]
thanks @bearclough ! :smile:

**Comment by jessesquires** [comment]
closed by 6b58a21
