### ISSUE TITLE
UITabbarController display issues when tabbar is visible

### ISSUE THREAD

**Issue by michaelis** [jessesquires/JSQMessagesViewController#94]
I'm using this control in a application that has a tab bar (main menu) and the input box doesn't get displayed, it appears to be hidden bellow that tabbar. Is there a way to solve this wihout changing the code of the control?

Thanks!

**Comment by qi-wang** [comment]
This might be late, but just found a work around. In your view controller, set edgesForExtendedLayout.
```
override public func viewDidLoad() {
      super.viewDidLoad()
      self.edgesForExtendedLayout = UIRectEdge.None
}
```
Then your input toolbar would be visible, above the tab bar.

**Comment by jessesquires** [comment]
thanks @qi-wang ! :smile: good to know

**Comment by tuzzo77** [comment]
Thanks to all!!!

**Comment by spartangian** [comment]
for swift 3 I did this: 
self.edgesForExtendedLayout = []

**Comment by LucasVanDongen** [comment]
I have it working in iOS 10 / Xcode 8.1, but when the keyboard comes up it doesn't move the input bar because the keyboard events somehow are not triggered.
