### ISSUE TITLE
CollectionView datasource methods not being called in JSQMessagesViewController subclass

### ISSUE THREAD

**Issue by danielwmsun** [jessesquires/JSQMessagesViewController#940]
I've subclassed JSQMessagesViewController - and have set the collectionView dataSource to be the instance of the subclass. With the exception of the senderDisplayName and senderId getters, I can't get the rest of the dataSource methods to be called, (collectionView:messageDataForItemAtIndexPath: or collectionView:messageBubbleImageDataForItemAtIndexPath: or collectionView:avatarImageDataForItemAtIndexPath:)

I've put breakpoints to ensure that the dataSource is correctly being set to my VC subclass. Which step am I missing? Is it the way that I am initializing the viewController? (It is currently one of the viewcontrollers of a tab bar controller. I've tried both the default init and the messagesViewController instance methods. (I am not using storyboard).

I think i'm just overlooking something very simple. Any help would be very greatly appreciated.

**Comment by danielwmsun** [comment]
I apologize, I should've done a better search through all the issues before I opened this issue.

**Comment by danipralea** [comment]
Banged my head against the wall for a few good hours. 
I guess the most obvious and simple mistakes strike again.

This has helped me a lot! Thanks!
