### ISSUE TITLE
Toolbar without collection view

### ISSUE THREAD

**Issue by avently** [jessesquires/JSQMessagesViewController#942]
Hey, Jesse. I'm using JSQMessagesViewController in chat's part of my app. Now i want to add toolbar from you library to other parts of the app. For example, user can leave a comment with resizable textview. So i do not need collectionview - just toolbar with textview in it and buttons around it. Is there a way to make it without too much headache?

**Comment by jessesquires** [comment]
hey @avently - you should be able to load this view from the nib and add it as a subview elsewhere in your app just like you would any other view.

see the source for how JSQMessagesVC does it to get started. i wouldn't expect there to be an issues.
