### ISSUE TITLE
about messageHash error:[GotyeOCMessage messageHash]: unrecognized selector sent to instance 0x9056f60

### ISSUE THREAD

**Issue by LINAICAI** [jessesquires/JSQMessagesViewController#944]
I have a class MyMessage like:
@interface MyMessage : GotyeOCMessage<JSQMessageData>

and I also implement messageHash method in MyMessage 

help me how can I do with above?

**Comment by jessesquires** [comment]
hey @LINAICAI - see the demo and the README

**Comment by LINAICAI** [comment]
Thanks.
But I've realized <JSQMessageData> to MyMessage and I am sure the messageHash  method have call by receive message ,when I send new message ,this error happen.

**Comment by LINAICAI** [comment]
This is my code:
@interface MyMessage : GotyeOCMessage<JSQMessageData>
