### ISSUE TITLE
checking if delegate responds to method in jsq_handleTapGesture of JSQMessagesCollectionViewCell

### ISSUE THREAD

**Issue by hermanccw** [jessesquires/JSQMessagesViewController#945]
This is not a bug per se but it makes it hard to implement my use case.  reference code here: https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Views/JSQMessagesCollectionViewCell.m#L316-L329

I implemented my own MediaItem which shows a custom mediaView.  When a user tap on the custom MediaView, I want to act differently depending on where was tap.  In the current scenario, when a user tap on my custom MediaView, it is calling "messagesCollectionViewCellDidTapMessageBubble" even though I did not implement that method in my controller.  What I wanted is to have it call "messagesCollectionViewCellDidTapCell:atPosition:" so that I can act accordingly.

Simply adding a respondsToSelector would do the trick I think.

**Comment by hermanccw** [comment]
hm.... spoke too soon.  seems like it it calling a delegate in JSQMessageCollectionView, I guess it doesn't hurt to call both "messagesCollectionViewCellDidTapMessageBubble" and "messagesCollectionViewCellDidTapCell" at the same time. @jessesquires what do you think?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by GianniCarlo** [comment]
@jessesquires it was a fun ride. Hope I have the chance to contribute in one of your future open source libraries 👌
