### ISSUE TITLE
Configuring CellTopLabel (not attributedStringForCellTopLabel)

### ISSUE THREAD

**Issue by aramusss** [jessesquires/JSQMessagesViewController#946]
Hello, this library is amazing, but I cannot find any way of modifying the label itself (or the cell) containing the time (the same text that is created on `- (NSAttributedString *)collectionView:(JSQMessagesCollectionView *)collectionView attributedTextForCellTopLabelAtIndexPath:(NSIndexPath *)indexPath`.
I need to add a background color and round corners, and the NSAttributedString class doesn't let me do all that. Is there any "correct" way of approaching this?
Thank you in advance.

**Comment by jessesquires** [comment]
hey @aramusss 

see the README:
https://github.com/jessesquires/JSQMessagesViewController#customize-your-cells
