### ISSUE TITLE
textView in JSQMessagesCollectionViewCell does not resize to fit text on iPad Popover

### ISSUE THREAD

**Issue by scotteg** [jessesquires/JSQMessagesViewController#947]
I am embedding a JSQMessagesViewController in container view (all 4 edges pinned) within another UIViewController presented as a popover. On iPad, the textView does not resize to fit the text, instead presenting each message on one line, cut off. The screenshot with the blue incoming bubbles was on iPad, the purple one on iPhone.

![ipad](https://cloud.githubusercontent.com/assets/1337867/7329556/260ec7be-eaa6-11e4-989c-cd5140e4fd9f.png)
![iphone](https://cloud.githubusercontent.com/assets/1337867/7329579/51d9d1a4-eaa6-11e4-8740-da5f6eee71a9.png)

**Comment by jessesquires** [comment]
Hey @scotteg - this shouldn't be happening. bubbles will size within the collection view bounds.

it appears that the frame of the collection view in the popover is wrong. my guess is that the popover isn't configured quite right.

can you provide more info on how you produced this? library version, ios version, etc.

**Comment by scotteg** [comment]
Hi @jessesquires, I'm using JSQMessagesViewController 7.0.1 and iOS 8.3. I'm using the same parent popover class throughout. Seems to work fine everywhere else. The same storyboard, class, and storyboard scene are used for for presenting a contained JSQMessagesViewController on iPhone and iPad. There are no special adaptive layouts implemented for size classes, just pinned constraints to ensure the contained JSQMessagesViewController fills the container; i.e., this is a pretty basic implementation. It displays fine on all iPhone models (and simulator) I've tested, but all iPad models (and simulator) I've tested experience this issue. See attached screenshot of storyboard and let me know if you want to take a look at the class files. Thanks!

![locstoryboardjsqmessagesviewcontroller](https://cloud.githubusercontent.com/assets/1337867/7418468/afc2f958-ef33-11e4-8f0d-fa52e897cc03.png)

**Comment by jessesquires** [comment]
Hm... thanks @scotteg !

Could you modify the demo project to reproduce this, and post a link to that branch?

**Comment by scotteg** [comment]
Here's a preliminary demo, in which I can demonstrate that the bubbles get truncated, although the text bubbles are not being compressed to one line. So I believe there is more to the issue:

https://github.com/scotteg/JSQMessagesViewController/tree/demo-issue-947

Steps I took:

1. Enabled using size classes in order to use the popover presentation I'm using in my app.

2. Replaced the storyboard contents to replicate the arrangement I'm using in my app:

![jsqmessagesviewcontrollerissue947_deploymenttarget7 0](https://cloud.githubusercontent.com/assets/1337867/7419581/8a608a42-ef3b-11e4-8c66-89f85c5de5dd.png)

Console output:
Please check the values return by the delegate.
the behavior of the UICollectionViewFlowLayout is not defined because:
the item width must be less than the width of the UICollectionView minus the section insets left and right values.
Please check the values return by the delegate.
the behavior of the UICollectionViewFlowLayout is not defined because:
the item width must be less than the width of the UICollectionView minus the section insets left and right values.

3. Changed deployment target to 8.3:

![jsqmessagesviewcontrollerissue947_deploymenttarget8 3](https://cloud.githubusercontent.com/assets/1337867/7419613/c4f80f2c-ef3b-11e4-8db1-dd30332289e8.png)

(Same console output)

As I mentioned, there's something more to the issue, because it my app (which is implicitly targeting 8.3), all text bubbles are compressed to one line:

![loc_implicitdeploymenttarget8 3](https://cloud.githubusercontent.com/assets/1337867/7419799/24c7bd52-ef3d-11e4-8e8b-39304c44c82f.png)

(Same console output)

Yet when I explicitly target 7.0, text bubble are no longer compressed to a single line but they are still truncated; the width being the same (vs. in the demo-issue-947 branch of the demo project) is expected because I am explicitly setting contentSize:

![loc_deploymenttarget7 0](https://cloud.githubusercontent.com/assets/1337867/7419851/6ed0a260-ef3d-11e4-917a-45970582c517.png)

(Same console output)

**Comment by jessesquires** [comment]
Thanks @scotteg ! I'll look at this when I can.

New idea: have you tried adjusting `messageBubbleLeftRightMargin` ?

http://cocoadocs.org/docsets/JSQMessagesViewController/7.0.1/Classes/JSQMessagesCollectionViewFlowLayout.html#//api/name/messageBubbleLeftRightMargin

**Comment by scotteg** [comment]
Adjusting `messageBubbleLeftRightMargin` did not resolve the issue.

**Comment by jessesquires** [comment]
@scotteg awesome! :tada: 

thanks for updating the issue! :+1:
