### ISSUE TITLE
[Advice Wanted] MediaItem transition to Modal

### ISSUE THREAD

**Issue by Liampronan** [jessesquires/JSQMessagesViewController#948]
Hello!

I'm looking for ways to incorporate a nice, non-standard transition from an image media message to a modal that contains that image (with some other details)-- I realize this is not part of the core offerings of this library but would love any pointers people may have and felt any findings would be helpful to other users.

Side note: this library is awesome! 

Thanks,
Liam

**Comment by jessesquires** [comment]
thanks @Liampronan !

there are delegate callbacks to get notified of taps on message bubbles, you can use this to begin the transition.

from there, it's probably best to check other resources online for how to do custom view controller transitions.
