### ISSUE TITLE
Integrating AFNetworking into this Lib- Fails to load upon dispatch findfinishReceivingMessage and reloadData

### ISSUE THREAD

**Issue by fresh83** [jessesquires/JSQMessagesViewController#952]
As mentioned , here is what were doing in viewDidLoad, does not do a thing.We originally tried to use the supplied datamodel, but we were not clear on how exactly we would be able to call the jsmess controller from the data model to reload. 

    NSLog(@"messageThreadViewController | preloadMessages");
       AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    manager.responseSerializer = [HMFJSONResponseSerializerWithData serializer];
    NSDictionary *parameters = @{@"recip_uid":@"1"};
    [MBHUDView hudWithBody:@"Hold up.." type:MBAlertViewHUDTypeActivityIndicator hidesAfter:10.0 show:YES];
    
    [manager.requestSerializer setValue:token forHTTPHeaderField:@"token"];
    NSString* client =@"iOS";
    [manager.requestSerializer setValue:client forHTTPHeaderField:@"client"];
    NSString *fullurl = [buhzURL stringByAppendingString:@"wiggyWoooo/format/json"];
    [manager POST:fullurl parameters:parameters  success:^(AFHTTPRequestOperation *operation, id responseObject) {
        [MBHUDView dismissCurrentHUD];
        NSLog(@"JSON: %@", @"networking complete");
        
        
        
        NSMutableArray *messages = [[NSMutableArray alloc] initWithObjects:
                                    [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdSquires
                                                       senderDisplayName:kJSQDemoAvatarDisplayNameSquires
                                                                    date:[NSDate distantPast]
                                                                    text:@"Welcome to JSQMessages: A messaging UI framework for iOS."],
                                    
                                    [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdWoz
                                                       senderDisplayName:kJSQDemoAvatarDisplayNameWoz
                                                                    date:[NSDate distantPast]
                                                                    text:@"It is simple, elegant, and easy to use. There are super sweet default settings, but you can customize like crazy."],
                                    
                                    [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdSquires
                                                       senderDisplayName:kJSQDemoAvatarDisplayNameSquires
                                                                    date:[NSDate distantPast]
                                                                    text:@"It even has data detectors. You can call me tonight. My cell number is 123-456-7890. My website is www.hexedbits.com."],
                                    
                                    [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdJobs
                                                       senderDisplayName:kJSQDemoAvatarDisplayNameJobs
                                                                    date:[NSDate date]
                                                                    text:@"JSQMessagesViewController is nearly an exact replica of the iOS Messages App. And perhaps, better."],
                                    
                                    [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdCook
                                                       senderDisplayName:kJSQDemoAvatarDisplayNameCook
                                                                    date:[NSDate date]
                                                                    text:@"It is unit-tested, free, open-source, and documented."],
                                    
                                    [[JSQMessage alloc] initWithSenderId:kJSQDemoAvatarIdSquires
                                                       senderDisplayName:kJSQDemoAvatarDisplayNameSquires
                                                                    date:[NSDate date]
                                                                    text:@"Now with media messages!"],
                                    nil];
        
          _messages=[messages mutableCopy];
        NSLog(@"SELF.MESSAGES_INSIDE:%@",_messages);
        
        
      
        
        dispatch_async(dispatch_get_main_queue(), ^{
            [self finishReceivingMessage];
            [self.collectionView reloadData];
        });
      
        
        
        
        
    }failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        [MBHUDView dismissCurrentHUD];
        
        if(operation.response.statusCode == 0){
            NSLog(@"STATUS_CODE=0");
            NSMutableDictionary *userInfo = [[error userInfo]mutableCopy];
            
            NSString *errorString = [[userInfo objectForKey:NSUnderlyingErrorKey] localizedDescription];
            
            
            
            
            NSLog(@"ERROR_STRING->%@",errorString);
            
            
            NSString *localizedFailureReason = [error localizedFailureReason];
            OLGhostAlertView *demo3 = [[OLGhostAlertView alloc] initWithTitle:@"Unexpected Error" message:@"Please try again"];
            demo3.style = OLGhostAlertViewStyleDark;
            demo3.timeout=3.0;
            demo3.show;
            
            
        }else if(operation.response.statusCode == -1001){
            NSLog(@"STATUS_CODE=-1001");
            OLGhostAlertView *demo3 = [[OLGhostAlertView alloc] initWithTitle:@"No Connection" message:@"Try again when you find a few bars homie"];
            demo3.style = OLGhostAlertViewStyleDark;
            demo3.timeout=5.0;
            demo3.show;
            
        }else if (operation.response.statusCode == 401) {
            NSLog(@"NSLOG | STATUS CODE==401");
            
            
            
        }else{
            
            
            
            NSLog(@"BODY_Error: %@", error);
            
            NSError *e;
            NSMutableDictionary *userInfo = [[error userInfo]mutableCopy];
            
            
            if([[error userInfo] objectForKey:@"body"] != [NSNull null] && [[error userInfo] objectForKey:@"body"]!=nil){
                NSLog(@"BODY!=NULL");
                NSString *error_body=[[error userInfo] objectForKey:@"body"];
                
                
                
                NSDictionary *response_body = [NSJSONSerialization JSONObjectWithData: [[[error userInfo] objectForKey:@"body"] dataUsingEncoding:NSUTF8StringEncoding]
                                                                              options: NSJSONReadingMutableContainers
                                                                                error: &e];
                
                
                
                if(response_body!= [ NSNull null ]){
                    
                    
                    NSDictionary *error_dictionary=[response_body objectForKey:@"error"];
                    if(error_dictionary!=[NSNull null]){
                        NSLog(@"response body: %@",error_dictionary);
                        NSString *error_msg=[error_dictionary objectForKey:@"message"];
                        NSString *msg= [NSString stringWithFormat:@"ERROR:%@",error_msg];
                        if(error_msg.length>0){
                            OLGhostAlertView *demo3 = [[OLGhostAlertView alloc] initWithTitle:@"Error:" message:error_msg];
                            demo3.style = OLGhostAlertViewStyleDark;
                            demo3.timeout=4.0;
                            demo3.show;
                            
                        }else{
                            
                            OLGhostAlertView *demo3 = [[OLGhostAlertView alloc] initWithTitle:@"Error:" message:@"a unexpected error occured"];
                            demo3.style = OLGhostAlertViewStyleDark;
                            demo3.timeout=3.0;
                            demo3.show;
                            
                        }
                        
                    }else{
                        OLGhostAlertView *demo3 = [[OLGhostAlertView alloc] initWithTitle:@"Error:" message:@"a unexpected error occured"];
                        demo3.style = OLGhostAlertViewStyleDark;
                        demo3.timeout=3.0;
                        demo3.show;
                        
                        
                    }
                    
                }else{
                    
                    OLGhostAlertView *demo3 = [[OLGhostAlertView alloc] initWithTitle:@"Error:" message:@"a unexpected error occured"];
                    demo3.style = OLGhostAlertViewStyleDark;
                    demo3.timeout=3.0;
                    demo3.show;
                    
                }
                
                
            }else{
                
                
                NSString *errorString = [[userInfo objectForKey:NSUnderlyingErrorKey] localizedDescription];
                
                // NSError *underlyingError=[userInfo objectForKey:NSUnderlyingErrorKey];
                
                OLGhostAlertView *demo3 = [[OLGhostAlertView alloc] initWithTitle:@"Error:" message:errorString];
                demo3.style = OLGhostAlertViewStyleDark;
                demo3.timeout=3.0;
                demo3.show;
            }
            
        }
        
    }];

    }

**Comment by jessesquires** [comment]
hey @fresh83 - this is probably better suited for StackOverflow

**Comment by fresh83** [comment]
It's not it's your library.


—

**Comment by svtechnology** [comment]
@fresh83 I see quite a few issues with the code you have posted. As suggested by @jessesquires, post this question on StackOverflow since it has very less to do with the library.

PS: Please don't get offended but posting comments like `It's not it's your library` would definitely not help.
