### ISSUE TITLE
Context Menu (long press over a cell)

### ISSUE THREAD

**Issue by jaimeslr** [jessesquires/JSQMessagesViewController#953]
Hi, Id like to change the longpress behavior to show the copy context menu from the bubble to the full cell. For example you longpress the cell out of the bubble but in the bubble row and the context menu appears in order to achive showing the menu even if the cell is a link. When you send a message with just a link or a phone number the long press will show the actionsheet disabling the possibility of copying the cell which is not the expected behavior.

I've tried to modify the jsq_didReceiveMenuWillShowNotification to create the CGRect with the selectedCell.frame (not the messageBubbleContainerView.frame) and does not work :(

Any help would be appreciated.

**Comment by jessesquires** [comment]
hey @jaimeslr - this is currently expected behavior.

the actionsheet provides a "copy" option, so this shouldn't be too much of an issue.

**Comment by jaimeslr** [comment]
Hi jesse, you're right but when you are using a context menu with a custom option (i.e.: Delete) will not appear in the actionsheet (ovbious). If the long press could be done over the row this action could be supported.

**Comment by jessesquires** [comment]
Ahhhhh. Now I understand. re-opened as an enhancement issue.
