### ISSUE TITLE
Incoming message with NSFetchedResultsController

### ISSUE THREAD

**Issue by Djoz2** [jessesquires/JSQMessagesViewController#954]
Hey @jessesquires , i'm trying now for the past week to use you're library with Core-Data.

My Message Class for Core-Data is looking like this:

@interface Message : NSManagedObject
@property (nonatomic, retain) NSNumber * read;
@property (nonatomic, retain) NSString * receiver;
@property (nonatomic, retain) NSString * sender;
@property (nonatomic, retain) NSDate * date;
@property (nonatomic, retain) NSString * text;
@property (nonatomic, retain) NSNumber * messageHash;
@property (nonatomic, retain) NSString *senderId;

OK now for the problem:

First of all let me show you the why I use NSFetchedResultsController:

- (NSFetchedResultsController *)fetchedResultsController {
 NSFetchRequest *fetchRequest = [[NSFetchRequest alloc] init];
    NSEntityDescription *entity = [NSEntityDescription entityForName:@"Message" inManagedObjectContext:_managedObjectContext];
    [fetchRequest setEntity:entity];
 NSSortDescriptor *sortDescriptor = [[NSSortDescriptor alloc] initWithKey:@"date"
                                                                   ascending:YES];
    [fetchRequest setSortDescriptors:[NSArray arrayWithObjects:sortDescriptor, nil]];

So when I send message to "User 1" and when I'm "User 2" I can see all incoming and outgoing message just fine, but If I'm "User 3" I can see all the same messages that "User 1" sent to "User 2".

The result:

http://s13.postimg.org/fe8gp0phz/Screen_Shot_2015_04_27_at_19_06_06.png
http://s29.postimg.org/ub4ulde93/i_OS_Simulator_Screen_Shot_Apr_27_2015_19_04_17.png
http://s28.postimg.org/l10g6oi0t/i_OS_Simulator_Screen_Shot_Apr_27_2015_19_04_23.png
http://s12.postimg.org/9etsq1tkt/Screen_Shot_2015_04_27_at_19_07_14.png

For that I just added a predicate to my fetch results right? so now its looking like this:

 NSPredicate *predicate = [NSPredicate predicateWithFormat:@"sender = %@ and receiver = %@", user_email, receiver ];
[fetchRequest setPredicate:predicate];

But now I can only see the outgoing messages because the predicate find only the same user as the predicate code say's. 

So the result now is just outgoing messages:

http://s28.postimg.org/fhaxsr22l/i_OS_Simulator_Screen_Shot_Apr_27_2015_19_13_21.png

So for trying to fix this what I did is just some helper code:
 for incoming messages I added a little helper code which just check incoming message or outgoing message And then called this in the bubble messages data source delegate:
- (BOOL)incoming:(Message *)message
{
    return ([message.senderId isEqualToString:self.senderId] == NO);
}
- (BOOL)outgoing:(Message *)message
{
    
    return ([message.senderId isEqualToString:self.senderId] == YES);
}

But still its not working!

1) Is it good to use Core-Data for messages app?
2) https://github.com/jessesquires/JSQDataSourcesKit  I saw you made this code for NSFetchedResultsController, but my problem is that it's in .swift does it have something to do with my problem?
3) I understand my problem which is the JSQ is handling the sender id incoming outgoing messages but I don't know how to fix it.

4)Do you please have some code example with Core-Data for this framework?

5)How can I fix this and show the user is messages and not all message or just outgoing messages?

@jessesquires  please help me I'm getting crazy already from this issue.
@jessesquires  I went all over the docs and saw the senderId is a unique key for the user who send the message... you should really give more info on how to use this.
and there should be something such as sender receiver ID or just string for the Receiver who should receive the message. Thank you from advance and thank you for this great library.

**Comment by jessesquires** [comment]
hey @Djoz2 - these sound like more generic core data questions rather than something specific to JSQMessages. i would try asking on StackOverflow.

the `JSQMessageData` protocol purely for the library to display messages. it contains all methods necessary for the framework to do its job. you could (and should) add additional properties/methods to your model objects if needed, which you could then use for your predicate.

**Comment by Djoz2** [comment]
hey @jessesquires  do you have any example of you're framework with core-data please?
I just can't figure out how to predicate some staff in core data to make it all work with harmony with you're framework thanks.
