### ISSUE TITLE
Input toolbar height does not update after setting text

### ISSUE THREAD

**Issue by matthewcheok** [jessesquires/JSQMessagesViewController#955]
I'm trying to set an initial value for the textview in the input toolbar in viewDidLoad but its height doesn't update correctly:

```
self.inputToolbar.contentView.textView.text = lastMessage;
```

Any idea how to fix this?

**Comment by jessesquires** [comment]
hey @matthewcheok - this is because the `textViewDidChange` event isn't trigged when setting text programmatically.

````
[[NSNotificationCenter defaultCenter] postNotificationName:UITextViewTextDidChangeNotification object:textView];
````

**Comment by matthewcheok** [comment]
This doesn't seem to adjust the height of the toolbar.

**Comment by yeissonoviedo** [comment]
Same problem here

**Comment by waterlee23** [comment]
The problem could be solved if you put the code in viewDidAppear

**Comment by ImperoIT** [comment]
m still facing the issue which code should be placed in viewdidappear ?

**Comment by waterlee23** [comment]
@ImperoIT put "self.inputToolbar.contentView.textView.text = yourText;" in viewDidAppear

**Comment by ImperoIT** [comment]
@waterlee23 in didappearthe height doesnt change at all ....When the code was in didload it expands little bit but not complete
Can you please guide how you resolved ?

**Comment by waterlee23** [comment]
@ImperoIT Then try the method jessesquires suggested, manually post UITextViewTextDidChangeNotification and pass your textView, in viewWillAppear or viewDidAppear

**Comment by ImperoIT** [comment]
Still no luck
