### ISSUE TITLE
Message text color automatically changes?

### ISSUE THREAD

**Issue by danielwmsun** [jessesquires/JSQMessagesViewController#956]
Hey! 

For some reason, my outgoing bubbles' text colors automatically change from white to black once another message is added to the datasource array. (Starts white, then when I add an incoming bubble when I receive a message, the text changes to black)

The incoming ones are fine.

I've checked out issue #470 but the demo link provided no longer exists :(

I haven't tried to change the text color anywhere in my code and am using your provided messages and bubble image classes.

Any thoughts?

![img_1327](https://cloud.githubusercontent.com/assets/7768248/7435102/936b887a-f00e-11e4-95bb-931ff4e92696.jpg)

**Comment by jessesquires** [comment]
hey @danielwmsun - sounds like you might be doing something wrong.

the demo project doesn't have this issue, trying checking to see if you are doing something differently

**Comment by ipranay** [comment]
I have faced the same issue a few times. It's not consistent and happens sparingly. Did you find a solution to this?

**Comment by sadgb** [comment]
+1 same issue

**Comment by GianniCarlo** [comment]
@danielwmsun , @ipranay , @sadgb I'm having the same issue, did anybody find out what was causing it?

**Comment by danielwmsun** [comment]
@GianniCarlo No, I didn't :( sorry.

**Comment by GianniCarlo** [comment]
This no longer happens to me. @danielwmsun I think my problem happened while I was looking for a fix to the flicker of some cells (which I kind of achieved). I was testing different things and there was a time that I removed explicitely setting the colors for my cells (I don't remember why). 

Anyways, you should be fine if you have something like this:
```objective-c
-(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath{
    /**
     *  Override point for customizing cells
     */
    JSQMessagesCollectionViewCell *cell = (JSQMessagesCollectionViewCell *)[super collectionView:collectionView cellForItemAtIndexPath:indexPath];
    
    JSQMessage *message = [self.visibleMessagesArray objectAtIndex:indexPath.item];
    
    //check if outgoing
    if ([message.senderId isEqualToString:self.senderId]) {
        cell.textView.textColor = [UIColor whiteColor];
    else{
        cell.textView.textColor = [UIColor blackColor];
    }
    return cell;
}
```
Also, if you have custom cells, and you are experimenting flashes everytime you call `[self finishSendingMessageAnimated:YES]` then what helped was overriding that function with:
```objective-c
- (void)finishSendingMessageAnimated:(BOOL)animated {
    
    UITextView *textView = self.inputToolbar.contentView.textView;
    textView.text = nil;
    [textView.undoManager removeAllActions];
    
    [self.inputToolbar toggleSendButtonEnabled];
    
    [[NSNotificationCenter defaultCenter] postNotificationName:UITextViewTextDidChangeNotification object:textView];
    
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
    [self.collectionView insertItemsAtIndexPaths:@[[NSIndexPath indexPathForItem:self.visibleMessagesArray.count-1 inSection:0]]];
    
    if (self.automaticallyScrollsToMostRecentMessage) {
        [self scrollToBottomAnimated:animated];
    }
}
```
The main difference between this and the library, is that the library calls `reloadData` which is known to make sometimes flicker the contents of the cell.

**Comment by patniemeyer** [comment]
+1 same issue intermittently.

**Comment by VitorHugoDS** [comment]
Just happened to me. Funny one to see.
It changes old texts' colors as new messages arrive.
Closed the controller and opened again, couldn't reproduce.

**Comment by Isuru-Nanayakkara** [comment]
Same happens to me too. But only under a certain circumstance. When I send normal text messages, it all works fine. But after I send a link, the previous message cells' text color randomly starts to switch to black. I uploaded a demo project [here](https://www.dropbox.com/s/1k501dbyzfiv90i/SEChatBug.zip?dl=0). 

![img_3153](https://cloud.githubusercontent.com/assets/2551877/23053687/521feeca-f501-11e6-902b-f0b3c2fb854d.PNG)

**Comment by prototypeSean** [comment]
same issue here, need help...

**Comment by JTambunt** [comment]
Getting this same issue. Random messages seem to turn black. Haven't messed around with colors nor made custom cells.

**Comment by GianniCarlo** [comment]
@Isuru-Nanayakkara I checked your demo project, and as I stated before in this thread, you need to explicitly declare what's in the `cell.textView.textColor` and `cell.textView.linkTextAttributes`.

In your demo you're not including `collectionView:cellForItemAtIndexPath:`, I added the following code and it no longer occurs to me:

```swift
override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as! JSQMessagesCollectionViewCell
        
        let message = self.messages[indexPath.item]
        
        var isOutgoing = false
        
        if message.senderId == self.senderId {
            isOutgoing = true
        }
        
        if isOutgoing {
            cell.textView.textColor = UIColor.white
            cell.textView.linkTextAttributes = [NSForegroundColorAttributeName : UIColor.white, NSUnderlineStyleAttributeName : NSUnderlineStyle.styleSingle.rawValue]
        } else {
            cell.textView.textColor = UIColor.black
            cell.textView.linkTextAttributes = [NSForegroundColorAttributeName : UIColor.black, NSUnderlineStyleAttributeName : NSUnderlineStyle.styleSingle.rawValue]
        }
        
        return cell
    }
```

@prototypeSean @JTambunt @VitorHugoDS can you make sure that you're explicitly assigning the content of `textColor` and `linkTextAttributes` inside `collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell`?

**Comment by Isuru-Nanayakkara** [comment]
Thanks @GianniCarlo!
