### ISSUE TITLE
gcd timer ,nstimer  invalid  in vc  that inherts  JSQMessagesViewController

### ISSUE THREAD

**Issue by berained** [jessesquires/JSQMessagesViewController#959]
uint64_t interval =  1* NSEC_PER_SEC;  
    dispatch_queue_t queue = dispatch_queue_create("GetNewMsgInChatListVCQueue1", NULL);
    _timer = dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER, 0, 0, queue);
    dispatch_source_set_timer(self.timer, DISPATCH_TIME_NOW, interval, 1 * NSEC_PER_SEC);
    dispatch_source_set_event_handler(self.timer, ^{   
        [self testRepeat];
    });
    dispatch_resume(self.timer);
============
the codes above execute once time ,why not repeat? (timer is property)
same way in using NSTimer ,it can not repeat too !

**Comment by berained** [comment]
problem above   occurred  in    NewVC  inherit  JSQMessagesViewController
  It's normal in  other vc

**Comment by jessesquires** [comment]
hi @berained - i don't really understand what you're trying to do, but this issue doesn't look like a problem  with this library

**Comment by berained** [comment]
add gcd timer or nastier in DemoMessagesViewController.m ,it did not work. can you try?

**Comment by berained** [comment]
add gcd timer or nstimer  in DemoMessagesViewController.m ,it did not work really. 
 can you try?
