### ISSUE TITLE
odd question: create UIImage from full bubble of message?

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#967]
I am not sure exactly how to frame the question, but i had an odd use-case where it might be groovy to be able to create the exact bubble containing a message (media OR text) within an image. This might be easily done, i simply have never hit this functionality before.

I don't mind doing the research, but a few pointers would be awesome if somebody has time. thanks..

ps: to be clear, i am not referring to the media content itself, i have that no worries, i want the entire bubble.

**Comment by jessesquires** [comment]
I think you're looking for `- snapshotViewAfterScreenUpdates:`

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/index.html#//apple_ref/occ/instm/UIView/snapshotViewAfterScreenUpdates:

**Comment by wdcurry** [comment]
Thanks dude.. the pointer was appreciated. Now that you helped get me there, the effort seems straightforward, but i am wondering if the library is somehow burying or messing with the rendering process, as i am only getting a black image from:

  UIView *msgSnapshot1 = [tappedCell.contentView snapshotViewAfterScreenUpdates:YES];

I know this is likely an SO question, but the few issues posted there seem to indicate this just "works". The UIView is transformed normally with:

  -(UIImage *) imageWithView:(UIView *)view
{
    UIGraphicsBeginImageContextWithOptions(view.bounds.size, view.opaque, 0.0f);
    [view drawViewHierarchyInRect:view.bounds afterScreenUpdates:NO];
    UIImage * snapshotImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return snapshotImage;
}

I will trawl SO tomorrow but thought to post this in case others find it interesting, or in case the JSQMessagesCollectionViewCell class is somehow interfering. I rendered the UIView directly from UICollectionViiewCell just in case, to test, same deal though.

** this is not critical, just a nice-to-have for a project ;)

**Comment by jessesquires** [comment]
Hm.. interesting. So even snapshotting the entire cell gives a black bubble?

**Comment by wdcurry** [comment]
yes, black if opaque=YES, white if opaque=NO..

I posted a more detailed question at:

https://stackoverflow.com/questions/30085554/render-uicollectionviewcell-snapshot-to-another-uiimage-control

I took to grabbing a raw UICollectionViewCell instance instead of the JSQ version because the bubble disappeared after the pushed detailViewController was done. The regular cell does not exhibit this behaviour, and in both cases the snapshot was the same.
