### ISSUE TITLE
The font size affect the boundingRectWithSize function???

### ISSUE THREAD

**Issue by vedon** [jessesquires/JSQMessagesViewController#968]
![screen shot 2015-05-06 at 4 31 18 pm](https://cloud.githubusercontent.com/assets/1811570/7489822/7a8111ec-f40d-11e4-9ca6-ef3fa5f95287.png)

I have change the font size to 20.0 pt .The problem as the pic show:
![screen shot 2015-05-06 at 4 31 38 pm](https://cloud.githubusercontent.com/assets/1811570/7489824/7c18d72e-f40d-11e4-9b45-0184f2a24ce1.png)

the function of the  boundingRectWithSize   return the wrong height . Any solution to solve this issue?

**Comment by jessesquires** [comment]
hey @vedon - see #347 #438

**Comment by vedon** [comment]
In your current release version ,the issue still there . The 7.1.0 version has fixed this issue?
