### ISSUE TITLE
Implement delete: action for cells

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#970]
Now possible (and much easier) for the library to provide since merging #811

**Comment by jessesquires** [comment]
work in-progress @ 9859d3a.

currently weird crashing issues.

**Comment by Foriger** [comment]
Hello, @jessesquires 
I update to  development branch and it looks like there are no crashes. Is this issue still valid?

**Comment by happiehappie** [comment]
How do we implement a custom action for delete? Example maybe create a UIAlertController with a NO(dismiss) and a YES(execute delete) UIAlertAction
