### ISSUE TITLE
[Question] Dynamic avatar image from URL

### ISSUE THREAD

**Issue by trungnguyen1791** [jessesquires/JSQMessagesViewController#977]
Hi Jesses.
Currently i'm working with an app have room chat features. It almost work well.
But i'm facing a problem with avatar for each people in my room. I don't know how to set that avatar image from URL (that url came from a message's property ).

Do you have any suggestions on it problems?
Thanks

**Comment by jessesquires** [comment]
hey @trungnguyen1791 - this implementation is up to you.

once you have your image, you just need to return in from the data source method.
