### ISSUE TITLE
minimumizing spacing between cells...

### ISSUE THREAD

**Issue by wdcurry** [jessesquires/JSQMessagesViewController#978]
hey Jesse et al, is there something in the library is that is creating spacing between cells? I am trying to remove ALL space between cells to allow a contiguous block of cells with a particular background to look unbroken.

I added the following to overrides but there is a faint spacing that i cannot seem to remove. I will replace the graphic i am using, but i doubt that is the issue. I have fiddled with the bounds of the rect of the image even extending it too far but the faint empty space remains. It looks like it is about a height of 1.

This space is at the bottom of the cell as the next bubble is butted up against the top of the space.

**Comment by jessesquires** [comment]
are you returning zero height for all the cell labels? on the `collectionViewFlowLayout`, you can also set a `minimumItemSpacing`

**Comment by wdcurry** [comment]
no, as i am using them as per my requirements, but that part is working properly, or so it seems. The logic in the setting of the data is exactly paralleling the logic of the returned heights, but i will double check. Perhaps there is an issue with the bottom label's background not being set. As far i can tell at this point, this is not the case, but i have been wrong before.

I also have the following in place:

    - (CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionView *)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section
        {return 0.0f; // This is the minimum inter item spacing, can be more}

    - (CGFloat)collectionView:(UICollectionView *)collectionView layout:(UICollectionView *)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section 
        {return 0.0f; // This is the minimum inter item spacing, can be more}

I have yet to see a reasonable explanation as to why Apple pushed us to write separate methods to handle the content and the height, as the two are seldom NOT connected. It is a pain of design.

**Comment by wdcurry** [comment]
kind of perplexing, as i have tweaked just about everything, I may re-examine the background setting process, but i removed all sizing and just pushed it through, just in case, with no change. 

I will adapt the latest demo to see if this exists there. {when time permits as this is not a critical sprint}

**Comment by jessesquires** [comment]
Thanks @wdcurry !

Going to close. Please post here if/when you can repro in the demo!
