### ISSUE TITLE
- (CGSize)messageBubbleSizeForItemAtIndexPath:(NSIndexPath *)indexPath return a wrong size

### ISSUE THREAD

**Issue by kirayamato1989** [jessesquires/JSQMessagesViewController#980]
![img_0556](https://cloud.githubusercontent.com/assets/7197021/7581383/e3097ca8-f8b4-11e4-9e0d-3cedc03ed29b.PNG)

sometimes I got a wrong CGSize for messageBubble , help~

**Comment by jessesquires** [comment]
@kirayamato1989 - are you using a custom font?

**Comment by kirayamato1989** [comment]
hi jessesquires!
I'm not using a custom font, only change the cell.textView.textColor .  >_<

**Comment by jessesquires** [comment]
hm... are you seeing the same results when using the english keyboard?

**Comment by kirayamato1989** [comment]
Yes, i got the same results when using english keyboard~~~*3*
![img_0557](https://cloud.githubusercontent.com/assets/7197021/7626949/a1a3648c-fa43-11e4-9129-eed4b37206b8.PNG)

**Comment by Losiowaty** [comment]
I'm having similiar problems with both polish / english text. The size also changes on subsequent enters to my view controller. Meaning that one time it will be okay, the next one it won't. @jessesquires what are you testing on? I'm having this issue on both simulator and physical device (iOS 8.3, iPhone 5).

**Comment by jessesquires** [comment]
Sounds like a hashing problem. Are you returning unique values from `messageHash` ?

**Comment by kirayamato1989** [comment]
Oh, problem solved with return unique messageHash!

**Comment by kirayamato1989** [comment]
Thx!

**Comment by jessesquires** [comment]
next time, please read the docs first! :smile: 

http://cocoadocs.org/docsets/JSQMessagesViewController/7.0.1/Protocols/JSQMessageData.html#//api/name/messageHash
