### ISSUE TITLE
Unable to add uibuttons to jsqmessageviewcontroller, as it only supports textview and background image view,

### ISSUE THREAD

**Issue by GDSys** [jessesquires/JSQMessagesViewController#981]
Unable to add uibuttons to jsqmessageviewcontroller, as it supports textview and background image view. I am manually adding uibutton on cellfor.. method in subclass of jsqmessageVC, by adding it on cell.contentview. And output is ugly, since it repeats on different other past messages.

Please help.

Thanks

**Comment by jessesquires** [comment]
hey @GDSys - it's possible to provide completely custom cells.

previous issues cover this topic:
https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+custom+cells+is%3Aclosed
