### ISSUE TITLE
Inputtoolbar disappears if I dismiss the view and than present it again

### ISSUE THREAD

**Issue by zhangtemplar** [jessesquires/JSQMessagesViewController#982]
![screen shot 2015-05-13 at 11 57 29 pm](https://cloud.githubusercontent.com/assets/5475267/7627416/df781a96-f9cb-11e4-8b2b-e2a0e6b43140.png)

Hi, I am writing a small chat app, where I use the JSQMessageViewController for the main component of the chat view controller. Beyond that, I have another view, which contains a table showing the list of current chats, where I should open the chat by clicking the cells of the table.

The problem is that, opening the chat by clicking the cells of the table is fine at the first time; but after I dismiss that chat by clicking left top button of the navigation bar and try to reopen the chat by clicking the  cell again, the problem happens, where the inputtoolbar doesn't show anymore.

Any idea on it?

**Comment by jayisidoro** [comment]
are you using swift or Objective c for your project?

**Comment by zhangtemplar** [comment]
@jayisidoro I am using objective c. Thanks!

**Comment by A1exandre** [comment]
Same issue and I am using Swift

**Comment by kakashysen** [comment]
For me is fixed when change the `modalTransitionStyle` from default value `.coverVertical` to any other style e.g. `.flipHorizontal`

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
