### ISSUE TITLE
Cannot get the JSQMessages to show in swift

### ISSUE THREAD

**Issue by jayisidoro** [jessesquires/JSQMessagesViewController#983]
I started with swift and haven't learned objective c, so I'm struggling to get this library imported into my app. I used cocoapods to install it, and then have created a bridging file with the import line. 

Despite following several online swift examples, none of them can reproduce a working demo. I either 
A: keep running into errors regarding the senderisplayname/senderId/JSQMessagesCollectionviewdatasource 
or 
B: Cannot get anything to appear in the view.

Can anyone provide a link to a current working example or offer advice on how to incorporate this into my app?

**Comment by jayisidoro** [comment]
i figured it out.

**Comment by henryeverett** [comment]
Care to share your solution?
