### ISSUE TITLE
Scrolling into a JSQMessageMediaData causes a crash

### ISSUE THREAD

**Issue by nathanielescribano** [jessesquires/JSQMessagesViewController#984]
Maybe I'm missing something, but even though I'm able to load up images, if I scroll away and scroll back to the image I get an app crash. Any thoughts on what might be causing this? I'm running 7.0.2 and xcode 6.3.1

**Comment by nathanielescribano** [comment]
figured it out.

**Comment by JohnnyTseng** [comment]
Hi @nathanielescribano ,
I'm facing this issue too, could you share your solution?

Thanks!

**Comment by jocelyn-cazes** [comment]
Hi @nathanielescribano ,

Please give an explaination before closing the issue.

Thanks...
