### ISSUE TITLE
cacheSize in messageBubbleSizeForItemAtIndexPath:(NSIndexPath *)indexPath maybe wrong

### ISSUE THREAD

**Issue by zihuyishi** [jessesquires/JSQMessagesViewController#985]
I put JSQMessagesViewController in a container view and I found when I change the container's width, the - (CGSize)messageBubbleSizeForItemAtIndexPath:(NSIndexPath *)indexPath function in JSQMessagesCollectionViewFlowLayout.m file will return wrong size, because the messageBubbleCache property return the old bubble size.
I think I need a function clear it when I change the view's width.

**Comment by jessesquires** [comment]
hey @zihuyishi - you can clear the layout cache by invalidating it with the custom invalidation context.

**Comment by zihuyishi** [comment]
Thank you, I write this function 
- (void)invalidJSQCache
{
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    context.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];
}
and it works fine.
