### ISSUE TITLE
Use of undeclared type 'JSQMessageData'

### ISSUE THREAD

**Issue by datomnurdin** [jessesquires/JSQMessagesViewController#988]
I got this error message when trying to add model.

```
/Users/MNurdin/Documents/iOS/xxxxx/Models/Message.swift:11:27: Use of undeclared type 'JSQMessageData'
```

Model code

```
class Message : NSObject, JSQMessageData {
```

Even i already tried import JSQMessage, but still not successful.

```
import JSQMessage
```

I got this error message after that

```
/Users/MNurdin/Documents/iOS/xxxxx/Models/Message.swift:10:8: No such module 'JSQMessage'
```

Please advice. Thank you.

**Comment by twairball** [comment]
are you sure you have the bridging header done right ? doing `#import "JSQMessages.h"` is sufficient to get everything into swift.

**Comment by datomnurdin** [comment]
Yes, I'm pretty sure.

**Comment by wimagguc** [comment]
Just use JSQMessagesViewController:
`import JSQMessagesViewController`
