### ISSUE TITLE
Scroll position is not maintained when switching orientation

### ISSUE THREAD

**Issue by BillCarsonFr** [jessesquires/JSQMessagesViewController#989]
I noticed that when switching orientation, the visible item on screens are not the same before and after the change.
I believe that the contentOffset is maintained, but as the cells height are not the same in portrait and landscape you don't see the expected message.

I tried to save the last indexPath before the rotation and then move back to it when the change is done (viewWillTransitionToSize) but the result is not very good. If i animate the scroll, the 2 steps are too visible, if i don't animate the jump is a bit 'strange'

Can this work can be done by the CollectionViewLayout? Do you have any direction on how to fix this?

Thx.

**Comment by erysaj** [comment]
I had the similar requirement and ended up saving and restoring content offset manually in `JSQMessagesViewController` subclass (though not via `-[UICollectionView scrollToItemAtIndexPath:atScrollPosition:animated:]` but explicitly changing content offset)

Still I suppose I overriding `-[UICollectionViewLayout targetContentOffsetForProposedContentOffset:]` may work as well, the method is called from animation block during rotation and when performing updates

**Comment by jessesquires** [comment]
Hey guys -- this should be helped by the work done in #1112.

Coming up in 7.2.0, you can set message bubbles to be fixed-width (so that they don't change size during rotation.)

**Comment by brbgyn** [comment]
Nice

By the way, whatsapp does change the bubbles width and still maintain scroll position.....

Any chance of achieving that ?

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
