### ISSUE TITLE
How to subclass JSQMessagesTypingIndicatorFooterView?

### ISSUE THREAD

**Issue by archbrys** [jessesquires/JSQMessagesViewController#995]
How can we subclass JSQMessagesTypingIndicatorFooterView? My reason is that I'm animating the typingIndicatorImageView and I don't want to modify the JSQMessagesTypingIndicatorFooterView just to achieve this.

![animation](https://cloud.githubusercontent.com/assets/9855401/7722955/55a847ae-ff17-11e4-89ca-381015f1db13.gif)

**Comment by jessesquires** [comment]
Hey @archbrys - Customizing the footer is the same as the header. See #826 for details.

**Comment by archbrys** [comment]
@jessesquires thanks for this.
