### ISSUE TITLE
JSQMessagesCollectionViewFlowLayout bubbleImageAssetWidth

### ISSUE THREAD

**Issue by walsh2000** [jessesquires/JSQMessagesViewController#997]
@jessesquires 

I've tracked down a visual bug to the value set to _bubbleImageAssetWidth in JSQMessagesCollectionViewFlowLayout.

When clients use a different image factory with a template image smaller than bubble_min,png, one/two letter messages (such as "k") have incorrect bubble sizes. The value bubbleImageAssetWidth is using bubble_min (a 48 px image) where the custom factory is using a smaller image (38px for example).

This MAX() statement in JSQMessagesCollectionViewFlowLayout.m chooses the 48 of the bubble_min.png which makes the chat bubble look 10+ pixels too wide:

```
CGFloat finalWidth = MAX(stringSize.width + horizontalInsetsTotal, self.bubbleImageAssetWidth) + 2.0f;
```

I can work around this by subclassing JSQMessagesCollectionViewFlowLayout and overriding the bubbleImageAssetWidth getter, but it might be nice for that value to be settable, or for the image-factory to be the source of this information rather than hard-coding the use of bubble_min.

Changing the value to readwrite would be a simple change with little/no impact to existing consumers. Bringing the factory in to be the source of truth would require some thought & effort.

Would you be interested in a PR which makes bubbleImageAssetWidth a settable property?
-- No urgency on my part as I have a fairly-clean work around.

**Comment by jessesquires** [comment]
>Would you be interested in a PR which makes bubbleImageAssetWidth a settable property?

Sounds good! :+1:

**Comment by jessesquires** [comment]
Hey @walsh2000 - I think 983fb58 addresses this issue. Going to close. 

If that's not correct, let me know and I'll re-open.

**Comment by walsh2000** [comment]
@jessesquires 
Yes, the 2nd init method, taking min bubble width, solves this issue.  :muscle: :facepunch:
