### ISSUE TITLE
Toolbar stays at the bottom when keyboard is shown (it doesn't stick on top of keyboard)

### ISSUE THREAD

**Issue by pml2571** [jessesquires/JSQMessagesViewController#998]
When the textfield is tapped inside toolbar, the keyboard shows up but the toolbar stays at the bottom, it doesn't stick to the keyboard. I'm still able to enter text to the textfield when the keyboard is up. Ive attached pics below. Is there are any solutions to this problem? Your help is much appreciated. Thanks

iphone 5s, ios 8.3

![img_4982](https://cloud.githubusercontent.com/assets/3819719/7782401/0cd8663a-00ca-11e5-9863-03d6f1bb58e9.PNG)
![img_4983](https://cloud.githubusercontent.com/assets/3819719/7782410/563c4dbe-00ca-11e5-9eb1-0baccf6bd64a.PNG)
![img_4984](https://cloud.githubusercontent.com/assets/3819719/7782411/5e6361b2-00ca-11e5-8ed6-6fe3791f6211.PNG)

**Comment by jessesquires** [comment]
are you calling `super` on all of the view lifecycle methods?

**Comment by pml2571** [comment]
Yes, all 'super' are called in all view's lifecycle methods

**Comment by pml2571** [comment]
Update: after thorough checking, it looked like i was missing calling super on 'viewdidappear' in my viewcontroller that inherits Jsqmessageviewcontroller. Also, I found closed issue related to this. Thanks!!:)

**Comment by sree127** [comment]
Thanks for this! I was struggling with the same :+1:
