### ISSUE TITLE
JSQMessages rendered rotated sometimes

### ISSUE THREAD

**Issue by stephen-riley** [jessesquires/JSQMessagesViewController#999]
See attached image.

I cannot repro this deterministically.  Currently happens on iOS 8, iPhone 6 and 6+.  I _think_ I've seen it in the simulator.

![messages rotated](https://cloud.githubusercontent.com/assets/8561865/7793193/27af25f0-0270-11e5-860e-70b8631f4cc2.png)

If anyone has a thought as to what might be happening, I'd appreciate the hint and I'll try to run this to ground.

Thanks!

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
